### ISSUE TITLE
long text stuck 

### ISSUE THREAD

**Issue by fakerange** [usememos/memos#1000]
### Describe the bug

insert a long text (45KB)，and then memos will be stuck in loading for long time.

### Steps to reproduce

-

### Screenshots or additional context

-

**Comment by itschip** [comment]
@fakerange could you provide some sample text? I'd like to try and reproduce it.

**Comment by fakerange** [comment]
> @fakerange could you provide some sample text? I'd like to try and reproduce it.

When I tried again, it wasn't stuck。 the sample text contains 46900 any characters 。
