### ISSUE TITLE
Resources are publicly accessible

### ISSUE THREAD

**Issue by Erwyn** [usememos/memos#1006]
### Describe the bug

If I add a resource to a memo, I can access it directly with its url although my memo is private.

### Steps to reproduce

1. create a memo only visible to you
2. add a resource
3. in another unauthenticated session browse to the url of the resource

**Comment by Zeng1998** [comment]
Duplicate of #822

**Comment by alexleyn** [comment]
Resources are still accessible public. It's impossible to make resource private.
