### ISSUE TITLE
Memos unsupported arm on raspberry pi

### ISSUE THREAD

**Issue by f97** [usememos/memos#101]
When I install memos on my raspberry pi using docker it gives me an unsupported arm64 error, is there any way to solve this? 

Thanks very much.

```bash
root@pi:~# docker run --name memos --publish 5230:5230 --volume /www/wwwroot/note.f97.xyz:/var/opt/memos
 -e mode=prod -e port=5230 neosmemo/memos:0.1.3
Unable to find image 'neosmemo/memos:0.1.3' locally
0.1.3: Pulling from neosmemo/memos
97518928ae5f: Pull complete
0408c3031dd8: Pull complete
6cfeef34c3ab: Pull complete
d9f790065503: Pull complete
f7da0a14d252: Pull complete
Digest: sha256:b11e90f2ace97911b8cda578659adf4ff1079d3e5118d5701f330415bd2af4be
Status: Downloaded newer image for neosmemo/memos:0.1.3
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform 
(linux/arm64/v8) and no specific platform was requested
exec ./memos: exec format error
root@pi:~#
```

![image](https://user-images.githubusercontent.com/35532964/177038397-20735f76-acb2-4a33-b0d1-c5e6e8debf39.png)

**Comment by boojack** [comment]
It might be a docker issue, please see: https://github.com/docker/for-linux/issues/1170#issuecomment-750311549

**Comment by boojack** [comment]
`arm64` platform is supported and will be releasing in next version. You can try it with the `dev` tag.

<img width="934" alt="image" src="https://user-images.githubusercontent.com/24653555/177045540-22eefe73-2a63-4e30-82e2-7d56679ba24d.png">
