### ISSUE TITLE
如果标签包含如下形式，将导致无法删除标签：#/issue/userview?id=testetstetestetstet

### ISSUE THREAD

**Issue by Nyar233** [usememos/memos#1015]
### Describe the bug

如果标签为如下形式，将导致无法删除标签：`#/issue/userview?id=testetstetestetstet`

If the tag is in the following form, it will cause the tag to be unable to be deleted: `#/issue/userview?id=testetstetestetstet`.

### Steps to reproduce

1.打开Momes
2.在文本框内键入`#/issue/userview?id=testetstetestetstet`并发布
3.尝试删除，momos无响应。

1.Open Momes. 
2.Type `#/issue/userview?id=testetstetestetstet` in the text box and post it. 
3.Attempt to delete it, but Momes does not respond.

### Screenshots or additional context

![firefox_S7DLOKO0kZ](https://user-images.githubusercontent.com/30363595/216497596-75db9bf0-d346-4184-8a8a-00b394210d04.gif)

**Comment by Zeng1998** [comment]
It maybe due to the symbol `#/`,  will be fixed after confirmation.

**Comment by jxpsert** [comment]
Are we allowing tags to start with non-alphanumeric characters? If so, I think we should stop that immediately.

**Comment by Zeng1998** [comment]
I think don't detect the tag if it start with some special characters like `/`, may helpful, at least in these cases.

> Are we allowing tags to start with non-alphanumeric characters? If so, I think we should stop that immediately.

It maybe overkill in some languages?
