### ISSUE TITLE
Editing the date of a post

### ISSUE THREAD

**Issue by whosee** [usememos/memos#1017]
### Is your feature request related to a problem?

Hello, no, Thank you for your hard work on this amazing piece of software.

### Describe the solution you'd like

Being able to also edit the date of a post, when you click on edit memo. 

### Additional context

I would like to get my diary from another platform to this one, so in order to import them I would need the option to change the date of the posts.

**Comment by Zeng1998** [comment]
try to double click the time on the left-top of one memo.

**Comment by whosee** [comment]
Thank you so much!

**Comment by TheNomad11** [comment]
> try to double click the time on the left-top of one memo.

Doesn't work for me. After double-clicking the note opens in the details view that is non-editable

**Comment by u23a** [comment]
Doesn't work for me too.

**Comment by Zeng1998** [comment]
@TheNomad11 @u23a 

Hey, try `Alt+click` the date.

![image](https://user-images.githubusercontent.com/31177490/236665837-c873404d-2608-45c0-ad98-9238adec6fef.png)

**Comment by TheNomad11** [comment]
thanks, but doesn't work either. maybe it is an configuration issue then? Maybe my reverse proxy is too basic? In the docs there is only an example for nginy, but I am using Apache, might this be the reason?

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerName memos.mydomain.com
    AllowEncodedSlashes On
    ProxyPreserveHost On
    ProxyPass "/"  "http://localhost:5230/"

SSLCertificateFile /etc/letsencrypt/live/memos.mydomain.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/memos.mydomain.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

**Comment by itsfeng** [comment]
> @TheNomad11 @u23a
> 
> Hey, try `Alt+click` the date.
> 
> ![image](https://user-images.githubusercontent.com/31177490/236665837-c873404d-2608-45c0-ad98-9238adec6fef.png)

Hi, is there a way to achieve this on mobile?

**Comment by Zeng1998** [comment]
@itsfeng 

Unfortunately no. 

We are thinking about how to make this operation more user-friendly.
