### ISSUE TITLE
实验性选项【评论将总是可见】失效

### ISSUE THREAD

**Issue by masclown** [usememos/memos#1018]
### Describe the bug

Memo评论后，重新打开Memos，未显示评论。
重新开启【评论将总是可见】选项，Memo下评论并未显示。

### Steps to reproduce

1、打开【评论将总是可见】。
2、对Memo进行评论，这时评论显示于Memo下方。
3、关闭Memos窗口，重新打开Memos，评论在Memos界面消失。
4、关闭【评论将总是可见】，同步文件，关闭Obsidian。
5、重新打开【评论将总是可见】，打开Memos，评论仍未显示在Memo下方。

### Screenshots or additional context

![image](https://user-images.githubusercontent.com/31032168/216548828-6c6af294-c82e-4ae6-88e0-fa6c36320aab.png)
![image](https://user-images.githubusercontent.com/31032168/216549012-157c881c-51a2-45b2-ace2-87da2ec8b061.png)
![image](https://user-images.githubusercontent.com/31032168/216549154-34eaa408-2b46-4c72-9dae-fb939e345e11.png)

**Comment by Zeng1998** [comment]
Are you sure there is a feature of comments in Memos?

**Comment by masclown** [comment]
> Are you sure there is a feature of comments in Memos?

是的，请看bug提报的截图，左侧为笔记界面，右侧为Memos。
每一条Memo评论的右上方，均可以点击评论按钮进行评论。
![image](https://user-images.githubusercontent.com/31032168/216554691-74662ec0-8a6e-4f1e-be5b-db1e769337e7.png)
![image](https://user-images.githubusercontent.com/31032168/216554747-7d4c0b52-3e1d-45c4-8ba8-0a7bf56e889a.png)
![image](https://user-images.githubusercontent.com/31032168/216554864-bb4fec93-50cb-41d2-a7ea-77849590eb3f.png)
此时关闭Memos，再重新启动。
![image](https://user-images.githubusercontent.com/31032168/216555019-b6b6e9ab-6779-441d-a0ce-250c96bc5173.png)
Memos的评论不见了。
![image](https://user-images.githubusercontent.com/31032168/216555125-3de95c04-83f7-4ad3-bd98-f939604fe74d.png)

**Comment by Zeng1998** [comment]
I mean, ... the comments of Memos is still on the roadmap. 

Any misunderstanding?
