### ISSUE TITLE
部署完成后访问频繁出错

### ISSUE THREAD

**Issue by ieasyseek** [usememos/memos#1025]
### Describe the bug

用腾讯云轻量服务器 Ubuntu20.04-Docker20 部署，部署完成后电脑网页访问频繁出现错误，手机访问没有问题，请问这是什么问题？

### Steps to reproduce

电脑访问IP:5230 报错

### Screenshots or additional context

![1675584112188](https://user-images.githubusercontent.com/78068033/216808405-a2c495c5-dfce-4d45-8167-bccb4a54c30d.png)
![1675584240453](https://user-images.githubusercontent.com/78068033/216808408-afc5a322-1321-4984-adc2-894a332ddea8.png)
![1675584584837](https://user-images.githubusercontent.com/78068033/216808458-b555241b-bf08-438b-914e-469f0aaea2fb.png)

**Comment by nuwoo** [comment]
+1

**Comment by boojack** [comment]
@ieasyseek 试试打开电脑端浏览器的无痕模式，可能是有缓存过期的问题。

**Comment by ieasyseek** [comment]
> 

无痕模式访问也是一样的问题。
