### ISSUE TITLE
是否能导入浮墨的备份，增加微信及TG录入？

### ISSUE THREAD

**Issue by Java2Boy** [usememos/memos#1038]
### Is your feature request related to a problem?

1：之前一直使用浮墨，想改用自己搭的服务，如果能增加相互导入或导出就好了
2：常用的TG或微信，如果支持转发录入就太好了

### Describe the solution you'd like

1：现在浮墨的备份文件，是否支持导入？
2：能否实现TG机器人或微信公众号录入？

非常感谢

**Comment by Zeng1998** [comment]
1. https://github.com/usememos/memos/discussions/223
2. https://github.com/usememos/memos#products-made-by-community
