### ISSUE TITLE
关于时区的问题以及中文用户名的问题

### ISSUE THREAD

**Issue by A2Data** [usememos/memos#1050]
### Describe the bug

1、注册中文用户名，三个字说字符过短问题
2、发表之后，时区问题，显示八小时后

### Steps to reproduce

1. When registering a Chinese user name, the three characters are too short
2. After the publication, the time zone problem shows that it will be eight hours later

**Comment by A2Data** [comment]
<img width="964" alt="image" src="https://user-images.githubusercontent.com/39373008/217579460-b0eb36a7-fe5e-4aa5-b3c9-7029c05aa5b9.png">

**Comment by boojack** [comment]
> 发表之后，时区问题，显示八小时后

应该和你的 docker 启动环境相关，可以参考下：
https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes

**Comment by boojack** [comment]
建议用户名使用英文字符，展示昵称可以用中文。
