### ISSUE TITLE
像素级抄袭，竟然只字不提原作Flomo，着实过分了。

### ISSUE THREAD

**Issue by icedfish** [usememos/memos#1051]
### Describe the bug

各位国人程序员们，能不能从我做起，尊重知识产权。

### Steps to reproduce

哎

**Comment by iamxvbaba** [comment]
我看某人多少有点毛病

**Comment by lollipopkit** [comment]
6

**Comment by ooohoc** [comment]
6.1k star，大家都没有意见，就你有意见

**Comment by ooohoc** [comment]
还有这都能扯到国人程序员？微软、谷歌抄袭别人的时候怎么没看见你出来说？

**Comment by boojack** [comment]
> 像素级抄袭

@icedfish 如果你指的是 UI 上，之前 flomo 网页端的一些样式小细节做得很差很粗糙，memos 在这些像素级的细节上尝试做过了很多调整，所以应该不能算像素级抄袭。

如果指的是代码上，那应该是没有任何抄袭的。

> 竟然只字不提原作Flomo

（👆 建议中英文之间加空格，以及 F 应该是小写。）

指的是需要在 [README](https://github.com/usememos/memos#readme) 里面为 flomo 引流吗？类似于这样 memos is an open source alternative to flomo?

我认为目前 memos 已经有了**可见性的设置**，同时支持了 **TODO 块**、**代码块**等等语法，目测这些在 flomo 中是不支持的，也可能不会被支持的。所以 memos 就不能算一个 optional alternative，倒像是个 flomo 增强版（[Mastodon](https://joinmastodon.org/) + [Gist](https://gist.github.com/)）🤔️。

---

*BTW，与其在这里讨论抄袭，不如多多续费会员来支持 flomo 💪*

**Comment by icedfish** [comment]
@boojack 竟然连少楠坚持用奇怪的flomo小写开头都知道，研究的挺细啊。

请不要混淆什么叫抄袭，“像素级”的表述是我不严谨，我道歉，毕竟我只看了你们项目首页的截图
![image](https://user-images.githubusercontent.com/1222861/217973149-a817fa18-54e4-4560-a1fb-971f752322b0.png)

抄袭不是指两者一模一样，那叫克隆。 抄袭设计是更常见的行为，有兴趣可以读一下：
https://mp.weixin.qq.com/s/DmX8dgnFv3l5bv3HqsGcsQ
抄一个页面的设计就是抄，非商业项目没人会告你们。 和flomo主创聊了，大家也就一笑。

但是请注意，各位如果在公司上班的时候“借鉴了别人的产品”，是会给公司惹麻烦的。

**Comment by icedfish** [comment]
表达目的达到，也不指望什么变化。 88。

**Comment by boojack** [comment]
> 但是请注意，各位如果在公司上班的时候“借鉴了别人的产品”，是会给公司惹麻烦的。

没必要上升到国人程序员们或者公司等群体。

> 表达目的达到，也不指望什么变化。 88。

不过我倒是期望 flomo 有些变化，比如补全一些可以做但是刻意不做的功能（e.g. 支持代码块以及 TODO 块的语法等等）。这样我们还是很乐意给 flomo 引流，作为一个主流的非私有化部署的使用方案。

---

@icedfish 另外还是建议在中英文之间留空格。😜

![image](https://user-images.githubusercontent.com/24653555/217982316-53bb3b32-a9f0-4ac5-ae03-1b568b999137.png)
