### ISSUE TITLE
I get the error "Missing user in session" when I use Firefox or sometimes Microsoft Edge

### ISSUE THREAD

**Issue by Isaiahh146** [usememos/memos#1057]
How to reproduce: Go to Memos using Firefox and scroll through notes with several images, after a while the Memos counter will go to 0, then when you try to create or modify a note, it says "Missing user in session".

It's only started to do this recently, and only consistently when using Firefox, it works fine most of the time when using Edge. Thought it may be due to my database with 278 images?

I'm using Memos version 10.2 running under a Docker container that is running on Ubuntu Server.

Server Specs: Cisco UCS C210 M2 w/ 1x Intel Xeon X5650 and 16gb RAM

**Comment by boojack** [comment]
This PR might fix your problem. #1059

**Comment by Isaiahh146** [comment]
Still having the issue in 0.10.3

**Comment by boojack** [comment]
Could you provide some backend logs with related contexts?

**Comment by Isaiahh146** [comment]
These are the logs leading up to the error


{"time":"2023-02-13T17:39:58Z","method":"POST","uri":"/api/auth/signout","status":200,"error":""},
{"time":"2023-02-13T17:40:13Z","method":"GET","uri":"/o/r/118/image.png","status":200,"error":""},
{"time":"2023-02-13T17:42:05Z","method":"GET","uri":"/api/status","status":200,"error":""},
{"time":"2023-02-13T17:42:13Z","method":"POST","uri":"/api/tag","status":401,"error":"code=401, message=Missing user in session"},
{"time":"2023-02-13T17:40:14Z","method":"GET","uri":"/api/memo/stats?creatorId=1","status":200,"error":""},
{"time":"2023-02-13T17:40:13Z","method":"GET","uri":"/o/r/140/20230131_131149.jpg","status":200,"error":""},
{"time":"2023-02-13T17:40:13Z","method":"GET","uri":"/o/r/139/20230131_131229.jpg","status":200,"error":""},
{"time":"2023-02-13T17:40:13Z","method":"GET","uri":"/o/r/138/20230131_131240.jpg","status":200,"error":""},
{"time":"2023-02-13T17:40:13Z","method":"GET","uri":"/o/r/119/image.png","status":200,"error":""},
{"time":"2023-02-13T17:40:13Z","method":"GET","uri":"/o/r/141/20230131_133445.jpg","status":200,"error":""},
{"time":"2023-02-13T17:40:13Z","method":"GET","uri":"/o/r/120/image.png","status":200,"error":""},
{"time":"2023-02-13T17:40:13Z","method":"GET","uri":"/o/r/121/image.png","status":200,"error":""},
{"time":"2023-02-13T17:40:13Z","method":"GET","uri":"/o/r/137/Math%20Lesson%2068.jpg","status":200,"error":""},
{"time":"2023-02-13T17:40:13Z","method":"GET","uri":"/o/r/136/image.png","status":200,"error":""},
{"time":"2023-02-13T17:42:03Z","method":"GET","uri":"/api/user","status":401,"error":"code=401, message=Missing user in session"},
{"time":"2023-02-13T17:42:13Z","method":"PATCH","uri":"/api/memo/36","status":401,"error":"code=401, message=Missing user in session"}

After error 401 the number of notes goes to 0 and the database size goes to 0 bytes

**Comment by Isaiahh146** [comment]
So it looks like 1.13.0 actually fixed this issue
