### ISSUE TITLE
Navbar covers upper part of memo after scroll

### ISSUE THREAD

**Issue by alvanrahimli** [usememos/memos#1063]
### Describe the bug

After editing and saving memo, UI scrolls to memo but navbar covers upper part of memo. Maybe we need to add offset to scroll

### Steps to reproduce

1. Write memos so much that you have to scroll to them
2. Edit one of earlier memos and click save
3. UI scrolls to memo to take you back to it
4. Memo gets aligned to top of screen, but **navbar covers upper part of it**

### Screenshots or additional context

![image](https://user-images.githubusercontent.com/41202771/218160917-7156bf35-5b64-4165-b4d6-d4b2aeec1a0b.png)

**Comment by boojack** [comment]
Fixed in the recent version.
