### ISSUE TITLE
Change the order of resources in memo

### ISSUE THREAD

**Issue by hahahumble** [usememos/memos#1071]
### Is your feature request related to a problem?

Resources in memo are now sorted by name. I hope to change the order of resources by drag and drop(or other way).

### Describe the solution you'd like

User can change the order of resources after they are created.

**Comment by joneldominic** [comment]
Hello @hahahumble, would you mind giving more details on what you expect regarding this feature?

**Comment by hahahumble** [comment]
![image-V3Yi1Q7q](https://user-images.githubusercontent.com/81009071/221412044-47d22556-a481-4288-b1dc-01abd2e56b3d.png)

![image-ponJMgff](https://user-images.githubusercontent.com/81009071/221412078-63a9986b-f9e8-4b07-a4da-dca8adf4d286.png)

The added resources are sorted by file name, and I wish I could change this order.

**Comment by joneldominic** [comment]
Ohh, I see. I think Drag and Drop would be great for this case.

**Comment by joneldominic** [comment]
Regarding the sorting behavior. Should it be automatically persisted when the order is changed? or it needs to be saved manually?

**Comment by hahahumble** [comment]
I think the order will be persisted only when the save button is clicked.
