### ISSUE TITLE
深色模式下markdown复选框显示问题

### ISSUE THREAD

**Issue by TTT-TD** [usememos/memos#1082]
### Describe the bug

深色模式复选框基本不可见，仔细看才能看到一点点，建议添加边框

### Steps to reproduce

使用`- [] '语法创建复选框

### Screenshots or additional context

![Screenshot_20230212_201005.jpg](https://input-s3.mn.input.im/adm-group/1/20230212/63e8e04d1e1d4.jpg)

**Comment by hahahumble** [comment]
我是 v0.10.3，没有遇到这个问题

![image-y5Tc3iSy](https://user-images.githubusercontent.com/81009071/218314841-360a2473-753a-48cd-8b6c-0a47d83e1041.gif)

**Comment by BigUIFU** [comment]
> 我是 v0.10.3，没有遇到这个问题
> 
> ![image-y5Tc3iSy](https://user-images.githubusercontent.com/81009071/218314841-360a2473-753a-48cd-8b6c-0a47d83e1041.gif) [ ![image-y5Tc3iSy](https://user-images.githubusercontent.com/81009071/218314841-360a2473-753a-48cd-8b6c-0a47d83e1041.gif) ](https://user-images.githubusercontent.com/81009071/218314841-360a2473-753a-48cd-8b6c-0a47d83e1041.gif) [ ](https://user-images.githubusercontent.com/81009071/218314841-360a2473-753a-48cd-8b6c-0a47d83e1041.gif)

好吧，看上去是我浏览器的问题，我换了浏览器确实是正常的
