### ISSUE TITLE
cannot type "enter" under Chinese input on macos

### ISSUE THREAD

**Issue by flymin** [usememos/memos#1084]
### Describe the bug

Sometimes I want to input English words with the Chinese input mode. However, if I type "enter", it fails to input the word. The "enter" seems to be caught by the text editing, not the input method.

### Steps to reproduce

1. edit with Chinese input mode
2. type a word and hit "enter" rather than "space"

### Screenshots or additional context

![2023-02-13 12 48 20](https://user-images.githubusercontent.com/28671430/218373138-b7a656fb-18a2-4eff-ba67-d0dcfd8e5051.gif)

version: v0.10.3
Only observe on MACOS regardless of browsers, not on Windows with Sogou input.

**Comment by boojack** [comment]
@flymin Could you please try it again in our demo site: https://demo.usememos.com/ 💗

**Comment by boojack** [comment]
Fixed in `v0.11.0`. Please feel free to reopen this if issue still exist.

**Comment by flymin** [comment]
Sorry for the late response. The issue is fixed in v0.11.0. Thank you!

**Comment by flymin** [comment]
This bug still exits if type markdown list. A leading "-" will lead to the problem in my previous video.

**Comment by boojack** [comment]
Fixed in https://github.com/usememos/memos/pull/1371
