### ISSUE TITLE
tags parser make a mistake in url with `#` 

### ISSUE THREAD

**Issue by MoCongxin** [usememos/memos#1085]
### Describe the bug

e.g.: 
chrome://net-internals/#hsts

#hsts will parse as a tag

### Steps to reproduce

create a note, and typing `chrome://net-internals/#hsts`

### Screenshots or additional context

![image](https://user-images.githubusercontent.com/7183018/218381823-e5280a84-71d3-4595-89ca-b91a0a75f40b.png)

**Comment by Zeng1998** [comment]
Which version? I cannot reproduce on the demo site.

**Comment by Yinr** [comment]
> Which version? I cannot reproduce on the demo site.

I tested in demo site, and the wrong tag is found in tag suggestions.

Since go is not support before text matching(`(?=re)`), `tagRegexp` may be like `(^|\s)#([^\s#/][^\s#]*)` and then get the second catch group?

**Comment by MoCongxin** [comment]
@Zeng1998 I use [v0.10.3](https://github.com/usememos/memos/releases/tag/v0.10.3) now, but this problem may be appear in older version too.

**Comment by Zeng1998** [comment]
So can you reproduce on the demo site?  I am sure there is no such issue on my Memos instance and the demo.

**Comment by Yinr** [comment]
Yes, in demo site, but the wrong tag only shows in `Create Tag` -> `Tag suggestions`.

**Comment by MoCongxin** [comment]
@Zeng1998 sure, the same thing in demo site.
![image](https://user-images.githubusercontent.com/7183018/218419678-5635cc1c-0a17-4c86-b031-e4c7dcc09089.png)

**Comment by Zeng1998** [comment]
Are you sure that you (or other users) didn't add this tag (`abcd`) manually?

**Comment by Zeng1998** [comment]
As for the tag suggestion, I prefer to regard it as a feature, not a bug.

**Comment by Zeng1998** [comment]
As shown by this video, there is no bug here. It is as expected for now.

**Comment by MoCongxin** [comment]
I dont think save an url such as `https://github.com/usememos/memos/issues/1085#issuecomment-1428032275`, and it create a tag `#issuecomment-1428032275` could consider "expected".

**Comment by Zeng1998** [comment]
What I see in the video is that you add the tag yourself. 

And, tag suggestions are just tag suggestions.

**Comment by Zeng1998** [comment]
> what I want is to save some url with # and do not create tags(like this: chrome://net-internals/#hsts).

As I said, this doesn't happen on the demo site and other instances of version 0.10.3.

**Comment by boojack** [comment]
@MoCongxin Do you mean the tag `abcd` will be creating directly when you create a memo with `chrome://net-internals/#abcd`? 

https://user-images.githubusercontent.com/24653555/219520073-a401cfcf-79d0-4c0a-88dd-b671e8f9be28.mp4

Or it just appears in the **tag suggestions** like the video above.

**Comment by MoCongxin** [comment]
I apologize, I messed up something. In my memory, a previous version had put all my tags into tag suggestions, so I always thought tag suggestions meant 'tags not displayed on the homepage'.
