### ISSUE TITLE
ios:单行输入长文本，并保存后，显示文本超出文本框，而且主体可以向左滑动

### ISSUE THREAD

**Issue by JeazW** [usememos/memos#1093]
### Describe the bug

![微信图片_20230215165750](https://user-images.githubusercontent.com/75829171/218981290-3fc78ac8-9799-4ccf-be6e-25597918d03d.jpg)
![微信图片_20230215165802](https://user-images.githubusercontent.com/75829171/218981302-5724855c-667e-475b-b1cb-2cb5b39559e5.jpg)
系统：IOS
版本：13.6
浏览器：safari、微信内置浏览器、夸克浏览器

### Steps to reproduce

1，输入长文本
2，保存
3，向左滑动

**Comment by CorrectRoadH** [comment]
我在iOS16里的safari和微信里复现不了，可能是浏览器旧版本的问题吧。
