### ISSUE TITLE
RSS标题建议使用正文截断

### ISSUE THREAD

**Issue by skyue** [usememos/memos#1098]
### Is your feature request related to a problem?

null

### Describe the solution you'd like

使用正文截断作为标题，纯图片就用「图片」做标题之类的

**Comment by hyoban** [comment]
就现在的实现来说，只要你在 memo 里首行使用 `# xxx` 来创建一个标题，就会使用它。直接固定正文截断也不是很优雅。

**Comment by skyue** [comment]
@hyoban 我有用rsshub订单一些微博，也是用的正文截断，感觉还行。这个事要从订阅者角度考虑，不建议增加创作者成本。
