### ISSUE TITLE
Support SSO like oauth or saml?

### ISSUE THREAD

**Issue by Yoshino-s** [usememos/memos#1103]
### Is your feature request related to a problem?

We have a centralized authentication platform that supports oauth or saml type sso, so we request to support sso

### Describe the solution you'd like

add oauth or saml protocol support

**Comment by cedroid09** [comment]
I back this! Support for SAML or OIDC will be great. Even a must for securing public instances of memos. But apps like https://github.com/mudkipme/MoeMemos will have to adapt.

**Comment by cedroid09** [comment]
@boojack thanks for #1118
I successfully implemented Oauth authentication with Keycloak as provider. I would like to document it if that can be useful to others.

**Comment by boojack** [comment]
@cedroid09 Sounds great! Please feel free to contribute to our documentation site https://github.com/usememos/dotcom
