### ISSUE TITLE
Localization with Weblate or Crowdin

### ISSUE THREAD

**Issue by AmadeusGraves** [usememos/memos#1107]
### Is your feature request related to a problem?

I am helping with the Spanish translation of the project, but it always gives a lot of problems to compare the different files to get the missing items to be translated. 

### Describe the solution you'd like

We should automate it with Crowdin or Weblate. I leave here the Urls.
https://crowdin.com/
https://weblate.org/en/

**Comment by Yoshino-s** [comment]
I made a weblate project for this https://hosted.weblate.org/access/memos ,but it needs admin's approve and configure to work and integrete, please check this @boojack

**Comment by AmadeusGraves** [comment]
Perfect, thanks!
