### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by yyysuo** [usememos/memos#111]
升级了今天的镜像出现这个错误了。

**Comment by boojack** [comment]
dev 镜像不太稳定，建议用 released 的 tag，目前最新是 0.1.3

**Comment by hyoban** [comment]
应该是生产环境下需要先创建用户导致的？你可以先手动到登录界面创建用户试试？不太确定

**Comment by boojack** [comment]
> 应该是生产环境下需要先创建用户导致的？你可以先手动到登录界面创建用户试试？不太确定

最新的 dev 版存在着 schema 的变更，我估计是这个导致的

**Comment by rebron1900** [comment]
因为使用了watchtower的自动更新，用的dev版本的镜像也出现这个问题了。
大佬的意思是以后用latest的话能无损升级吗？

**Comment by boojack** [comment]
> 因为使用了watchtower的自动更新，用的dev版本的镜像也出现这个问题了。 大佬的意思是以后用latest的话能无损升级吗？

是的，`0.1.3` -> `0.2.0` 可以直接升级

**Comment by rebron1900** [comment]
之前用的dev版本不行是么？

**Comment by yyysuo** [comment]
> dev 镜像不太稳定，建议用 released 的 tag，目前最新是 0.1.3

用lastes重新创建了镜像，现在创建的用户默认不是管理员用户了，并且101 demo@usememos.com和102 jack@usememos.com这2个用户无法删除。

**Comment by yyysuo** [comment]
docker run -d --name memos --restart=unless-stopped --mount type=tmpfs,destination=/tmp -p 5230:8080 -v /mnt/sda3/memos/:/var/opt/memos -e mode=prod neosmemo/memos:latest

创建之后在/mnt/sda3/memos下面竟然没有数据库，好奇怪。

**Comment by boojack** [comment]
docker 部署命令变了 https://github.com/usememos/memos#%EF%B8%8F-deploy-with-docker

**Comment by boojack** [comment]
> 之前用的dev版本不行是么？

之前和之后的 dev 都不能保证能直接更新，所有还是不要使用 `dev`（当然如果你想折腾的话就另说

**Comment by yyysuo** [comment]
> docker 部署命令变了
> 
> ```
> docker run \
>   --name memos \
>   --publish 5230:5230 \
>   --volume ~/.memos/:/var/opt/memos \
>   neosmemo/memos:latest \
>   --mode prod \
>   --port 5230
> ```

我有点看不懂呀，没有composer，只能是命令创建
docker run -d --name memos --restart=unless-stopped --mount type=tmpfs,destination=/tmp -p 5230:5230 -v /mnt/sda3/memos/:/var/opt/memos -e mode=prod -e port=5230 neosmemo/memos:latest

这样创建访问10.10.10.200:5230是访问不了的。

docker run -d --name memos --restart=unless-stopped --mount type=tmpfs,destination=/tmp -p 5230:8080 -v /mnt/sda3/memos/:/var/opt/memos -e mode=prod -e port=5230 neosmemo/memos:latest

这样创建能访问，但是只能用demo账户访问。

现在搞不清楚正常创建好了应该是什么状态，第一次登陆的账号就是默认的管理员么，这样只能是demo账户是管理员呀。

**Comment by yyysuo** [comment]
看了一下docker的日志，端口还是8080呢，并且数据库的位置不太对，后缀还是dev

---
profile

v
port: 8080
dsn: /usr/local/memos/memos_dev.db
version: 0.2.0
---
Version 0.2.0 has started at :8080

**Comment by boojack** [comment]
之前是从 env 获取配置（mode, port 等），现在改成了从 flag 获取，所以之前的启动命令无效了，需要改成最新的，可以直接从 README 里复制运行。

**Comment by yyysuo** [comment]
> 之前是从 env 获取配置（mode, port 等），现在改成了从 flag 获取，所以之前的启动命令无效了，需要改成最新的，可以直接从 README 里复制运行。

感谢大佬，终于搞定了。
