### ISSUE TITLE
复制文本过多，超出限制，问题账户出现问题

### ISSUE THREAD

**Issue by Flxshin** [usememos/memos#1135]
### Is your feature request related to a problem?

![image](https://user-images.githubusercontent.com/106539404/220518097-5d367441-f99b-4e76-bf9a-d1547ad0b02c.png)

### Describe the solution you'd like

怎么来取消掉复制文本

**Comment by Zeng1998** [comment]
You can delete this record in the database.

**Comment by boojack** [comment]
Fixed in https://github.com/usememos/memos/pull/1138

The maximum content size will be 1MB.
