### ISSUE TITLE
Tiled card layout similar to Google Keep

### ISSUE THREAD

**Issue by huang3303** [usememos/memos#1136]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

Could add a tiled card layout similar to Google Keep, which can display more notes.

**Comment by byjosue** [comment]
Also in addition to the tile design I'd also love to see the ability to color memos. Maybe implemented in a way that it reflects how important a memo is for later review but even just being able to change the color would be nice

**Comment by arromattic** [comment]
Is this issue in progress ?
