### ISSUE TITLE
S3存储文件命名及文件夹问题

### ISSUE THREAD

**Issue by yylqing** [usememos/memos#1144]
### Describe the bug

1. 配置好阿里云OSS存储之后，截图在编辑栏粘贴，图片上传
2. 由于上传的图片名字 “image.png” 没有重命名成别的名字上传到OSS中，导致OSS中存储的文件名始终为“image.png”，实际情况就是新上传的图片将旧图片替换了
3. 建议：上传时创建一个文件夹，如“memos”，然后上传的文件放在文件夹内（当前是放在oss的根目录下）；然后图片可以按“时间戳_随机数” 进行重命名，避免文件重名覆盖的情况

### Steps to reproduce

1. 直接截图在输入框上传，然后保存
2. 再次截图在输入框上传，然后保存
3. 刷新网页，发现第一次上传的图片被覆盖；查看oss的文件列表，只有最新的图片文件

### Screenshots or additional context

![image](https://user-images.githubusercontent.com/18625743/221072405-976f8e3f-9841-4ec2-9fac-9ede58b00824.png)
![image](https://user-images.githubusercontent.com/18625743/221072454-416acb2d-7094-4425-910b-edc66d9e15d9.png)

![image](https://user-images.githubusercontent.com/18625743/221072942-7df228e6-3571-4377-aac1-d8d457c6604e.png)

**Comment by qazxcdswe123** [comment]
Suggestion: Rename file before uploading, for example `{year}/{month}/{md5}.{extName}`

Besides, I personally suggest adding an option to compress file/convert to `webp` format before uploading

**Comment by Yoshino-s** [comment]
imageflow or https://wsrv.nl/ may fit for you to doing image convert
And we will add new feature to specific uploaded file name format

**Comment by qazxcdswe123** [comment]
> imageflow or https://wsrv.nl/ may fit for you to doing image convert And we will add new feature to specific uploaded file name format

The point is to compress images (direct img compress or webp format compress) and thus reduce bucket size + faster loading time, not about a specific format, but this is a `good to have` though.

**Comment by MiracleXYZ** [comment]
I have the same issue. Renaming files automatically before uploading them seems to be a good workaround.

**Comment by hatice12x** [comment]
![Uploading memos-2023_02_27 20_57_09.png…]()

**Comment by zhongjingxia** [comment]
> > Issue is not in English. It has been translated automatically.
> 
> **Title:** S3 storage file naming and folder problems

测试

**Comment by skyue** [comment]
刚刚升级到0.11.1，发现这个问题没修复？
这不是普通bug，属于功能无法使用的bug，期待官方早点修复下。

**Comment by ivanusong** [comment]
I have the same problem and hope it can be resolved soon.
