### ISSUE TITLE
有没有可能集成本地短地址服务？

### ISSUE THREAD

**Issue by 17huiwei** [usememos/memos#1145]
### Is your feature request related to a problem?

如果是很长的域名，就会让页面变得很丑。

### Describe the solution you'd like

类似于 https://github.com/jwma/jump-jump 这样的本地短地址服务（不建议远程的，就是为了持久和安全）

**Comment by Yoshino-s** [comment]
What are the security risks of using external URL shortening services?

**Comment by jxpsert** [comment]
In what way is a URL too long? Your domain name is as long as you make it, no?
