### ISSUE TITLE
同局域网ip+端口/端口映射后 不能访问

### ISSUE THREAD

**Issue by i0czf** [usememos/memos#1153]
### Describe the bug

本地 win 电脑 docker 装好 memos 后，本机 ip + 5230 访问正常
同局域网另外台电脑 ip + 端口不能访问
端口映射后咋不能访问

### Steps to reproduce

同个局域网下，另外台Mac，访问服务器（win电脑）ip+5230 不行

**Comment by boojack** [comment]
> 本地 win 电脑 docker 装好 memos 后，本机 ip + 5230 访问正常。同局域网另外台电脑 ip + 端口不能访问

和 memos 无关，建议看看局域网访问相关的文章，比如 https://www.quora.com/How-do-I-share-something-with-other-computers-via-an-IP-address
