### ISSUE TITLE
如果发布大量文字，能不能以摘要的形式展现，增加一个详情超链接到详情页面

### ISSUE THREAD

**Issue by sucaimap** [usememos/memos#1155]
### Is your feature request related to a problem?

如果发布大量文字，能不能以摘要的形式展现，增加一个详情超链接到详情页面

### Describe the solution you'd like

如果发布大量文字，能不能以摘要的形式展现，增加一个详情超链接到详情页面

**Comment by Zeng1998** [comment]
大量文字可以自己控制，通过 `---` 折叠，进入详情页面也很方便。

应该没有必要再加额外的处理。
