### ISSUE TITLE
sso中的Identifier是什么

### ISSUE THREAD

**Issue by bboysoulcn** [usememos/memos#1159]
使用gitea登陆的时候报错
```json
{
  "error": "code=500, message=Failed to get user info, internal=the field \"access_token\" is not found in claims or has empty value",
  "message": "Failed to get user info"
}
```

**Comment by boojack** [comment]
应该是 `login`
https://gitea.com/api/swagger#/user/userGetCurrent

**Comment by bboysoulcn** [comment]
> 应该是 `login` https://gitea.com/api/swagger#/user/userGetCurrent

不是login

**Comment by bboysoulcn** [comment]
{
  "error": "code=500, message=Failed to get user info, internal=the field \"login\" is not found in claims or has empty value",
  "message": "Failed to get user info"
}

**Comment by boojack** [comment]
发一下配置信息？看看这几个值是否正确 https://docs.gitea.io/en-us/oauth2-provider

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/24653555/221358315-4e11ff7f-94c7-4976-a3a9-242b55ef35be.png">

**Comment by bboysoulcn** [comment]
```bash
Name: gitea
Identifier filter: 
Client ID: xxxxx
Client secret: 
Authorization endpoint: https://xxx/login/oauth/authorize
Token endpoint: https://xxx/login/oauth/access_token
User info endpoint: https://xxx/login/oauth/userinfo
Scopes: user
Identifier: login
Display name: user
Email: email
```



Identifier filter是空的

**Comment by boojack** [comment]
试试把 `User info endpoint` 换成 `/api/v1/user` 
https://try.gitea.io/api/swagger#/user/userGetCurrent

**Comment by bboysoulcn** [comment]
> 试试把 `User info endpoint` 换成 `/api/v1/user` https://try.gitea.io/api/swagger#/user/userGetCurrent

可以了感谢
