### ISSUE TITLE
Environment variables are invalid

### ISSUE THREAD

**Issue by NoverNobida** [usememos/memos#116]
All environment variables are invalid and cannot be started with a non-root user in version 0.2.0. This did not appear in version 0.1.3.

**0.2.0**:
![图片](https://user-images.githubusercontent.com/46912250/178403868-a355d622-b8a9-43b2-b3d7-9db3fb13d90c.png)

**0.1.3**:
![图片](https://user-images.githubusercontent.com/46912250/178404640-5f6f957f-bd9a-4b53-80bb-483be6954b2a.png)

**Comment by boojack** [comment]
`environment variables` is no longer used, please check the latest command: [deploy-with-docker](https://github.com/usememos/memos#%EF%B8%8F-deploy-with-docker)

**Comment by DHS1001** [comment]
I have the same issue here with 0.2.0, is is possible to provide a docker-compose? thanks

**Comment by DHS1001** [comment]
Thanks a lot @boojack , it is working properly now.
