### ISSUE TITLE
一处奇怪的翻译和关于页面外链跳出建议

### ISSUE THREAD

**Issue by Seevil** [usememos/memos#1160]
### Is your feature request related to a problem?

一处感觉奇怪的翻译 和 关于页面 外链跳出 、RSS订阅处标题调用 建议

话题外的项目建议：
本地文件存储系统的上线，上传的文件和数据库分开存储应该尽快上线，不然时间越久对已使用的用户来说更新迁移成本越高。项目本身定位就有隐私、私密属性，按理说这个在项目开发初期就应该已经规划好的基础功能😂 
数据库里存文件是谁的想法上去就是梆梆两拳<img width="50"  src="https://user-images.githubusercontent.com/7334510/221354508-dc8aee79-1c68-463d-8bfc-2c64a4d82145.gif"/>

### Describe the solution you'd like

奇怪的翻译：
![image](https://user-images.githubusercontent.com/7334510/221352867-2262a824-7579-4998-baac-66f27ea0396a.png)

`所有 Memo 已就绪 🎉` 是否可以翻译为 `所有 便签 已就绪 🎉`  比较好  

![image](https://user-images.githubusercontent.com/7334510/221352951-9caff0f3-ce50-4551-a24b-c88ef5760bf5.png)

或者是把emoji表情移除换成英文句号 `所有 Memo 已就绪 .`
![image](https://user-images.githubusercontent.com/7334510/221352905-b9ca1607-510f-4c36-99e1-fc3c711086ea.png)

![image](https://user-images.githubusercontent.com/7334510/221352797-db837db2-9def-4a59-a6b2-e5cdb1d636ec.png)

RSS订阅处标题调用：
这里是否应该调用 设置>系统>服务名称 里的服务名称 ？
![image](https://user-images.githubusercontent.com/7334510/221353033-46b698f9-7771-4d0e-a0ba-3985873ad0bd.png)

外链跳出建议：
![image](https://user-images.githubusercontent.com/7334510/221351789-0a601a5e-5028-44b3-8c92-62b9cc4a4262.png)

这几处超链接建议加个` target="_blank"` 新标签打开，不然每次点击都会覆盖当前站点

**Comment by loryncien** [comment]
超链接新标签打开 +1

**Comment by Zeng1998** [comment]
1. Memo 在这应该是一个 ”专有名词“，不建议修改。至于 emoji ，这种见仁见智的东西，通过自定义脚本修改也可。
2. 所提到的标题处我不确定是否是 BUG，因为放项目名称（Memos）其实也说得过去？

**Comment by Zeng1998** [comment]
（本地文件系统，第三方平台存储，就我个人来说这些都不是预期计划要做的东西，至少不算是 ”基础功能“。

**Comment by Seevil** [comment]
> （本地文件系统，第三方平台存储，就我个人来说这些都不是预期计划要做的东西，至少不算是 ”基础功能“。

明白呢，就像那句话来着 不主动就是不喜欢（没做就是不想做）。哈哈果然男人都是拿着答案问问题🤣老鸡汤味很纯啊。
 没事哈，只不过是说些个人意愿~

**Comment by boojack** [comment]
> 本地文件存储系统的上线

让子弹再飞一会 https://github.com/usememos/memos/pull/1130

**Comment by Seevil** [comment]
> > 本地文件存储系统的上线
> 
> 让子弹再飞一会 #1130

哦豁，期待下个版本😍👍
