### ISSUE TITLE
Markdown hyperlinks with parenthesis in take first closing parenthesis as final

### ISSUE THREAD

**Issue by nickcowans** [usememos/memos#1162]
### Describe the bug

For example `[Severance](https://en.wikipedia.org/wiki/Severance_(TV_series))` will create a link to "https://en.wikipedia.org/wiki/Severance_(TV_series", rather than "https://en.wikipedia.org/wiki/Severance_(TV_series)"

### Steps to reproduce

1. Paste `[Severance](https://en.wikipedia.org/wiki/Severance_(TV_series))` into a memo
2. Click Save
3. Click on the created link, it will be to "https://en.wikipedia.org/wiki/Severance_(TV_series"

**Comment by HappyZ** [comment]
+1

also `[ [paper](https://arxiv.org/abs/2112.10752) ]` renders as [\[paper](https://arxiv.org/abs/2112.10752) ] which looks to be a similar issue

**Comment by HappyZ** [comment]
maybe `/\[([^[\]\n]+)\]\(([^)\n]+)\)/g` for link extraction instead of `/\[(.*?)\]\((.+?)\)+/` here: https://github.com/usememos/memos/blob/1847756ade10debffee6e4b00271700d41a805d3/web/src/labs/marked/parser/Link.tsx#L9

took a quick look at https://github.com/usememos/memos/blob/1847756ade10debffee6e4b00271700d41a805d3/web/src/labs/marked/parser/PlainLink.tsx#L3 and it doesn't look right either. I'm thinking: `/(https?:\/\/\S+)(?:\s|$)/g`

**Comment by TheRealJd3** [comment]
Changing the regex [here](https://github.com/usememos/memos/blob/1847756ade10debffee6e4b00271700d41a805d3/web/src/labs/marked/parser/Link.tsx#L9) to `/\[(.*?)\]\((.+?)\)$/` also fixes things

**Comment by HappyZ** [comment]
for my own curiosity how does the parser work for single line string containing multiple links?

**Comment by TheRealJd3** [comment]
It doesn't handle them - good point !

**Comment by HappyZ** [comment]
Found https://stackoverflow.com/questions/67940820/how-to-extract-markdown-links-with-a-regex and modified to exclude /n as well: `/\[([^][\n]+)\](\(((?:[^()\n]+|(?2))+)\))/g`

this might work for both scenarios + multiple links in one string

**Comment by boojack** [comment]
Current frontend parser is very simple and mainly using to get tags from a raw content.

And we've planned a Markdown parser in Go. Very much looking forward to getting contributions. https://github.com/orgs/usememos/projects/5?pane=issue&itemId=16186604
