### ISSUE TITLE
How to change RSS link?

### ISSUE THREAD

**Issue by HappyZ** [usememos/memos#1168]
### Describe the bug

Was hosting it in a docker and it's using localhost with port 5230. After setting up reverse proxy in nginx `proxy_pass http://127.0.0.1:5230;`, things all work fine except the RSS feed shows link http://127.0.0.1:5230. Looking at the code it's using host info and I didn't find anywhere to override it when running with docker. Can someone help point to the right direction? Thx

### Steps to reproduce

1. Bring up a docker
2. Set up nginx with reverse proxy to listen at port 80 and point it to

```
location / {
    proxy_pass http://127.0.0.1:5230;
}
```

### Screenshots or additional context

xml file now is:

```
<rss xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
<channel>
<title>Notebook</title>
<link>http://127.0.0.1:5230</link>
<description/>
<pubDate>Sun, 26 Feb 2023 20:57:51 +0000</pubDate>
</channel>
</rss>
```

**Comment by hyoban** [comment]
please check [X-Forwarded-Host](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host) and [X-Forwarded-Proto](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto) your nginx conf

**Comment by HappyZ** [comment]
gotcha, thx

added

```
	location / {
	    proxy_pass http://127.0.0.1:5230;

            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host  $host;
	}
```

problem solved :) thx
