### ISSUE TITLE
manage mambers

### ISSUE THREAD

**Issue by alexkutsan** [usememos/memos#117]
I can see default members : 
<img width="753" alt="изображение" src="https://user-images.githubusercontent.com/860357/178725785-b47b34e5-07a4-4bba-b115-dc663a28df6f.png">

And when I change my user name from Default Host to my user name and password for my custom password I still have to log in with demo@usememos.com

How can I remove `demo@usememos.com` and `jack@usememos.com` and make my own admin user?

**Comment by boojack** [comment]
I think it's in `dev` mode. Could you please take a screenshot about this?

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/24653555/178730281-14f04eef-cbf4-4819-b929-f85e65d2af2d.png">

**Comment by alexkutsan** [comment]
Yep, i was in dev mode because of the wrong docker-compose that I created.
I took one from https://github.com/usememos/memos/issues/116 and now it works fine
