### ISSUE TITLE
现在rss输出正文是markdown，转成html好些

### ISSUE THREAD

**Issue by skyue** [usememos/memos#1172]
### Is your feature request related to a problem?

如题

### Describe the solution you'd like

如题

**Comment by hyoban** [comment]
考虑了一下，目前正文格式到页面上的卡片的处理就是前端的 parser 单独做的，感觉在后端引入 markdown 转 html 的库可能不是个好的选择。不知道 rss 阅读器对于 markdown 格式的处理如何？

**Comment by skyue** [comment]
@hyoban  我目前用的两个inoreader和本地的NetNewsWire，都是markdown原始文本输出。如下图：
<img width="792" alt="image" src="https://user-images.githubusercontent.com/10450242/222035184-13a93e47-dad5-4f2e-9657-aea96c4b1d17.png">


从现在的rss输出内容看，`description`字段并未指定格式，如果指定格式`markdown`，不知道阅读器会不会额外处理。（也不太了解，xml标准是否支持指定文本类型）

总的来讲，这是nice to have的功能，优先级不高，没想好要不要在服务端引入markdown渲染的话，不增加为好。

**Comment by boojack** [comment]
Already done in `v0.13.0`
