### ISSUE TITLE
Login Security issue

### ISSUE THREAD

**Issue by thareekanvar** [usememos/memos#1174]
### Describe the bug

Hello

i justed this securities issue while im using ur demo account . Ur demo account password is wrong so i got a toast like hashedpassword is not the hash of the given password. In my view point this notification is a security issue . Some one who login with some id and password the understand this user is here his password is wrong.

i think the toast must be like “ Your login credentials are incorrect please check “ something like that. 

Also the toast is not hiding its stay longtime i think until i change the page .. in UX perspective its not good .

### Steps to reproduce

1. Go to login
2. Give a wrong password with demohero username
3. U will get the error

### Screenshots or additional context

![D0DB56A5-158F-46F0-ABA7-F787651E0AFE](https://user-images.githubusercontent.com/26960181/221484722-5c3f5836-be8b-4058-adef-9e9a901dd2f1.png)

**Comment by johnykary** [comment]
Hello,

I am new to the open source community and I would like to get into contribution. I saw that in this case you display the message from the server directly by passing the error directly to the toastHelper

`toastHelper.error(error.response.data.error);`

Is it planned in the near future to start handling some of these errors with translations? Like in this example maybe for the case of 

``User not found with username``, ``Incorrect password`` maybe you can give some more generic error like @thareekanvar suggests ( Your login credentials are incorrect please check) .

I could work on creating such a function so we can use the translations for some cases if you want.

Also about the toast it has the functionality to close when you click on it. Maybe it is not obvious for the user the first time. I can change it like that if you want.


![image](https://user-images.githubusercontent.com/19289530/221643831-f68c3026-443d-495e-bc33-ee4c81ad9067.png)

**Comment by johnykary** [comment]
Hello @thareekanvar @boojack . 

I see in your commits @thareekanvar you changed the errors from backend. Should I proceed with creating a system in front end to translate the api messages and the x button in toast? Should i create a new branch from you?

**Comment by johnykary** [comment]
Hello @thareekanvar @boojack . I would like to suggest the following and tell me if you agree. 

We can create a function under `/helpers/translate/` that will do the following:

`import { i18n } from "i18next";

export const translate = (i18n : i18n, t: Function, message: string) =>{
    if (message === "Incorrect login credentials, please try again"){
        if (i18n.exists("apiErrors.invalid_credentials")) return t("apiErrors.invalid_credentials")
    }

    return  message;
}`

And in catch we can do the following
`  toastHelper.error(translate(i18n, t, error.response.data.message));`

In case there is no translation for the error message we will display the message from BE. What do you think?
