### ISSUE TITLE
能否增加TLS/SSL协议支持

### ISSUE THREAD

**Issue by hook-hash** [usememos/memos#1175]
### Is your feature request related to a problem?

memos能否考虑使用HTTPS，TLS/SSL协议对数据行加密，保障传输数据的安全性

### Describe the solution you'd like

memos能否考虑使用HTTPS，TLS/SSL协议对数据行加密，保障传输数据的安全性

**Comment by qrzbing** [comment]
你可以使用 nginx、caddy 等工具反代啊，我觉得这不算是 memos 的**核心**功能吧，除了增大代码体积之外意义不大
