### ISSUE TITLE
S3 Storage supports to set UsePathStyle to true

### ISSUE THREAD

**Issue by HappyZ** [usememos/memos#1176]
### Is your feature request related to a problem?

Not familiar with how web interface works so not sure how to add an option to the form.

But the idea is to add to https://github.com/usememos/memos/blob/main/plugin/storage/s3/s3.go#L46 like the following:

```
	client := awss3.NewFromConfig(cfg, func(options *awss3.Options) {
		options.UsePathStyle = awss3.Bool(true)
	})
```

I need this because I locally set up storage with MinIO using nginx reverse proxy, and it does not support DNS style hosts like `somebucket.mys3.com`. Instead I'd like to use `mys3.com/somebucket`.

### Describe the solution you'd like

Adds 
```
	client := awss3.NewFromConfig(cfg, func(options *awss3.Options) {
		options.UsePathStyle = awss3.Bool(true)
	})
```

Or if folks like it to be an optional thing:

```
	client := awss3.NewFromConfig(cfg, func(options *awss3.Options) {
		options.UsePathStyle = awss3.Bool(config.UsePathStyle)
	})
```

Then add UsePathStyle to the config and UI. Thanks.

**Comment by Zeng1998** [comment]
The path-style URLs will be deprecessed in the future. So I don't recommend implementing it. 

As for MinIO, there should be some corresponding solutions can be find.

https://aws.amazon.com/cn/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/

**Comment by HappyZ** [comment]
gotcha, will see if I find anything for MinIO. Likely an nginx hack

**Comment by HappyZ** [comment]
lol I didn't do anything but a hack to the input. Using above example, so I created a bucket named `somebucket`.

The config is:

```
Name: minio
EndPoint(S3-compatible server URL): https://mys3.com/somebucket
Region(Region name): xxx
AccessKey(Access Key / Access ID): xxx
SecretKey(Secret Key / Secret Access Key): xxx
Bucket(Bucket name): somebucket
URLPrefix(Custom URL prefix; Optional): <empty>
```

Is is expected when you rename/delete a resource in db, it does not delete in s3 storage? @Zeng1998

**Comment by Zeng1998** [comment]
Yes, it's expected for now.  A resource in memos is just a reference to the external storage if you use S3.

**Comment by IIllIIIlll** [comment]
> I am using memo's with selfhosted minio and am running into similar issues where I can only use path-style url's. I see that amazon in deprecating that method of using S3, but there are other implementation that rely on it. I would love to see this implemented

It can be simply solved by setting **URL prefix** in memos web settings pannel. This is what I do, assuming that you have minio endpoint as https://data.example.com and bucket name memos. You can easily set URL prefix to https://data.example.com/memos. Then you choose minio as your storage method. Upload somethings to resources, and check minio admin pannel, you will find what you have just uploaded.
