### ISSUE TITLE
希望能提供二进制发布版

### ISSUE THREAD

**Issue by fcwys** [usememos/memos#118]
希望能提供二进制发布版，更方便部署，谢谢！

**Comment by boojack** [comment]
好奇为什么二进制会更方便点？你是要在本机上部署吗？通常在云服务器上，用 docker 来部署和管理会是更好的方式。

**Comment by fcwys** [comment]
在本机部署呢

**Comment by boojack** [comment]
在本机我也是放在 docker 里。因为 memos 可以看成一个服务，而不是一个可以安装的应用程序，所以二进制的可执行文件反而会更加麻烦（特别是在版本更新时），还是建议使用 docker。

不过在版本发布时，有空的话之后会加上二进制的可执行文件。

**Comment by fcwys** [comment]
我通常会在本地先测试在放到服务器，本地是win或者linux跑虚拟机，有二进制方便些，谢谢啦

**Comment by Kellermaan** [comment]
我也觉得docker部署非常方便啊。

**Comment by fierceX** [comment]
建议每次发布提供一些二进制版本。照顾下freebsd的同学

**Comment by lentikr** [comment]
> 在本机我也是放在 docker 里。因为 memos 可以看成一个服务，而不是一个可以安装的应用程序，所以二进制的可执行文件反而会更加麻烦（特别是在版本更新时），还是建议使用 docker。
> 
> 不过在版本发布时，有空的话之后会加上二进制的可执行文件。

Windows 端docker不是原生，感觉太占内存了，而且应该有一部分小白用户没有自己的VPS，也不了解docker如何部署。所以提供二进制版本应该还是有必要的。
另外，能否申请加入到scoop的extra源中？使用scoop管理的话应该能比较好地解决版本更新的问题。

**Comment by lhuanyun** [comment]
也希望有个二进制版本的，感谢大佬的超好用，极简备忘录。
另外，希望可以不用邮箱作为账号。邮箱太长，不是很方便

**Comment by xudaolong** [comment]
https://github.com/xudaolong/memos-desktop 我制作了windows和mac版本的 定期升级版本。

**Comment by fcwys** [comment]
Thinks.

**Comment by asasn** [comment]
> 好奇为什么二进制会更方便点？你是要在本机上部署吗？通常在云服务器上，用 docker 来部署和管理会是更好的方式。

因为不会，而且麻烦啊！

觉得docker部署好，是典型的程序员思维，不是用户思维，找到GitHub来的，大部分都认同docker部署，才导致了幸存者效应般的认知偏差……

大众用户其实并没有跨平台的需要，仅仅只是想要找个方便的记事本，作为本地的flomo替代

而且对于电脑小白来说，这种方式还是太麻烦了些，要另外装一个好几百mb的docker，还不确定资料储存在哪里

私以为类似obsidian那种直接能在本地使用，能看到文件在哪里，比较适合大众用户的习惯，好些人都在obsidian里面使用memos的插件……

如果能够使用webdav支持同步Windows和安卓端同步就更好了。

现在出现一些第三方的桌面版本，说明的确是存在这种需求的，只可惜官方仓库一直没有这方面的计划。
