### ISSUE TITLE
Is PWA functional with share intent on Android?

### ISSUE THREAD

**Issue by tiagoprn** [usememos/memos#1180]
From what I saw on the issues this app can be uses as a PWA. I am pretty much interested for the "share intent" functionality on Android, so I can share e.g. a link, text etc. natively on Android. Is that possible? If so, could you add on the site/README the steps to do that? That is awesome functionality and IMO something that must be stated on its' core features.

Thank you very much for this tool which is awesome!

**Comment by jt-wang** [comment]
@tiagoprn #2425 looks the author intentionally removes PWA support, but they didn't elaborate why so.
