### ISSUE TITLE
资源库预览相关问题

### ISSUE THREAD

**Issue by lentikr** [usememos/memos#1183]
### Describe the bug

1. 预览窗口应在资源库菜单上层，而不是被资源库菜单覆盖在下面
2. 预览窗口应添加左右箭头用于切换上/下一个图片

### Steps to reproduce

1. 资源库
2. 随便找一个图片，点击“…”->“预览”

### Screenshots or additional context

![image](https://user-images.githubusercontent.com/95539012/221565017-f5e5a4d2-e07a-4a81-998f-14e10875e116.png)

![image](https://user-images.githubusercontent.com/95539012/221565385-864e2a4f-1cf4-4fac-abe9-5263a36bec9a.png)

**Comment by Zeng1998** [comment]
Fixed by #1171 and please wait for the next release.

**Comment by Zeng1998** [comment]
It is strongly recommended to create one issue for one thing, as this practice facilitates tracking and resolving.
