### ISSUE TITLE
Time stamp

### ISSUE THREAD

**Issue by cliffordx** [usememos/memos#1184]
### Is your feature request related to a problem?

I suggest adding a timestamp each time I write.

### Describe the solution you'd like

Each sentence or paragraph, I can do keyboard shortcut (on Mac, i.e., Command+t) to enter current time.

**Comment by TheRealJd3** [comment]
By default `Wed Mar 01 2023 16:50:17 GMT+0000 (Greenwich Mean Time)` would be the output of this shortcut - would you like it changed to some other format?

**Comment by cliffordx** [comment]
> By default `Wed Mar 01 2023 16:50:17 GMT+0000 (Greenwich Mean Time)` would be the output of this shortcut - would you like it changed to some other format?

Yes no issue. Cmd+m is better I guess because of the placement of `m` :)

**Comment by Zeng1998** [comment]
Maybe we won't do it, as it's not a common need. You can try to implement it with the custom Javascript.
