### ISSUE TITLE
Ability to add more admins

### ISSUE THREAD

**Issue by jxpsert** [usememos/memos#1188]
### Is your feature request related to a problem?

I just enabled GitHub SSO. I love this feature and would like to use it, except: I don't have any admin permissions on it. 

### Describe the solution you'd like

I would love a feature to be able to turn a member into an admin, and give them the same rights as the 'site host'. Or, if you're bored, maybe an entire permissions thing.

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/6d5e1def7650962c6a3d1c5f7bd9d6631aa26f4d
