### ISSUE TITLE
How to change the port used by memos?

### ISSUE THREAD

**Issue by longyangxi** [usememos/memos#1192]
How to change the port used by memos? I found I can't change it. It always uses 5230

**Comment by TheRealJd3** [comment]
[Dockerfile](https://github.com/usememos/memos/blob/9577f6dbe8a05e40c6f629fb402d17f16f8d4077/Dockerfile#L29)  and [Docker compose](https://github.com/usememos/memos/blob/9577f6dbe8a05e40c6f629fb402d17f16f8d4077/docker-compose.yaml#L9)

**Comment by longyangxi** [comment]
@mmoo97 @TheRealJd3 Thank you all, I am new to Docker and will study that.
