### ISSUE TITLE
Can memos support web3 base login?

### ISSUE THREAD

**Issue by 9cat** [usememos/memos#1193]
### Is your feature request related to a problem?

Can memos support web3 base login?

### Describe the solution you'd like

using meta-mask or wallet connect as ID to  login,and could anonymous

**Comment by mikestaub** [comment]
I like the idea of supporting multiple identity providers, but not any that have a token associated. https://github.com/bluesky-social/atproto or https://github.com/nostr-protocol/nostr could be candidates

**Comment by boojack** [comment]
> Can memos support web3 base login?

Probably not in the last few years.
