### ISSUE TITLE
Minor Grammar Issues

### ISSUE THREAD

**Issue by fiumad** [usememos/memos#1194]
### Describe the bug

There are a few minor English grammar issues in the english locale file.  

### Steps to reproduce

1. Set language to English.

**Comment by Zeng1998** [comment]
What? Where?

**Comment by fiumad** [comment]
> What? Where?

Hi! Sorry, I am new to contributing to projects. I fixed all of the errors and will be submitting a pull request momentarily.

**Comment by fiumad** [comment]
PR complete!

**Comment by boojack** [comment]
> PR complete!

Good catch! Thanks
