### ISSUE TITLE
memos-editor-wrapper does not have rounded corners

### ISSUE THREAD

**Issue by fiumad** [usememos/memos#1208]
### Describe the bug

The memos-editor-wrapper does not have rounded corners which results in a visible element behind the editor when the background color is changed via the custom CSS themes.

![Image](https://user-images.githubusercontent.com/81405199/221976827-1380881d-3353-4f63-9d7b-593153acf4f0.png)

### Steps to reproduce

1. In the settings menu add these two lines of custom CSS
`.memo-list-container {background-color: #5a7684;}`
`.page-container {background-color: #5a7684;}`

2. Return to the home page and view the Memo

**Comment by hyoban** [comment]
easy to fix, i will handle it

**Comment by fiumad** [comment]
> easy to fix, i will handle it

No need. I submitted a PR with the fix!

**Comment by TheRealJd3** [comment]
This can be closed now
