### ISSUE TITLE
功能建议：图片上传功能支持对象存储

### ISSUE THREAD

**Issue by monlor** [usememos/memos#121]
1. 图片上传支持上传到对象存储，在前端可以配置默认的图片上传方式，本地或s3
2. 同时兼容适配现有的图片上传api，自动选择用户配置的上传方式，返回图床的url
3. 支持配置图床的cdn访问地址，自动替换

目前腾讯cos，阿里oss，华为云obs，都是支持s3协议，只要适配了亚马逊的s3协议，就都能支持
腾讯有额外必输字段，region和项目，这个要注意
极力推荐作者优先适配cos，个人用户量挺大的

**Comment by rebron1900** [comment]
之前也提过图床功能，可以参考下[twikoo](https://github.com/imaegoo/twikoo)

**Comment by Kellermaan** [comment]
同意+1

**Comment by necoic** [comment]
希望支持sm.ms

**Comment by Fyeanes** [comment]
对象存储有消息了吗

**Comment by Zeng1998** [comment]
#1086 
#1088

**Comment by cloverzrg** [comment]
bug：
对于 private 的不希望外部直接访问仓库，直接url访问是返回403的，后端返回储存在minio的文件的url给前端的时候，需要在url里添加凭据
目前是通过在仓库设置匿名访问解决

**Comment by chendx-github** [comment]
配置了s3 之后，图像会直接访问s3的数据，这样有一个问题，如果是访问端无法访问到s3的服务器，那就会无法访问数据，应该增加一个选项，代理数据传输，通过memos传输数据而不是直接从客户端访问数据
