### ISSUE TITLE
API `amount` dosen't work

### ISSUE THREAD

**Issue by eallion** [usememos/memos#1214]
### Describe the bug

API `amount` dosen't work

### Steps to reproduce

https://demo.usememos.com/api/memo/amount?creatorId=101

return error message:
```
{
  "error": "code=400, message=ID is not a number: amount, internal=strconv.Atoi: parsing \"amount\": invalid syntax",
  "message": "ID is not a number: amount"
}
```

**Comment by Zeng1998** [comment]
It has been removed.

https://github.com/usememos/memos/blob/main/server/memo.go
