### ISSUE TITLE
S3 storage for uploaded file name md5

### ISSUE THREAD

**Issue by ixxmu** [usememos/memos#1215]
### Is your feature request related to a problem?

The files uploaded to sso storage exposed the file real name in URL.

### Describe the solution you'd like

I want the files uploaded to the image bed or s3 storage to be automatically saved with a hash or md5 name instead of the name of the file itself.

### Additional context

Thanks developers maked this awesome project！

**Comment by Zeng1998** [comment]
Add path template in #1285 .
