### ISSUE TITLE
BUG：分享时出现图片无法显示的问题

### ISSUE THREAD

**Issue by monlor** [usememos/memos#122]
浏览器：Safari
设备：iPad，mac应该也有
操作步骤：
1. 点击memo上的分享按钮，弹出框中的图片空白，多点几次后才正常
2. 点击Daily Review按钮，再点击分享按钮，弹出框中的图片也是空白

参考优化方式：
可以考虑点击分享按钮后直接下载图片，不用显示预览效果😂

另外有个PING的小细节优化：
对于已经置顶的memo，点击PIN的按钮时，按钮应该是填充状态。
主页中`PINNED`这几个字也可以给一个高亮效果😉

**Comment by boojack** [comment]
好像图片空白的问题只会发生在 Safari 浏览器上 🤔
