### ISSUE TITLE
The login button on the explore page is missing. 

### ISSUE THREAD

**Issue by fireworksdancewindsing** [usememos/memos#1222]
### Describe the bug

The login button on the explore page is missing. 

### Steps to reproduce

The login button on the explore page is missing.

**Comment by TheRealJd3** [comment]
Clicking the logo/icon takes you to the login/auth page

**Comment by fireworksdancewindsing** [comment]
I don't want to open the login page by clicking on the logo. Because a lot of unregistered visitors don't do that. 
It is better to be able to register directly out of the login button.

**Comment by Zeng1998** [comment]
I think this issue has been resolved in the latest version.

Feel free to reopen it if needed.
