### ISSUE TITLE
Allow users to customize the refresh time for Daily Reviews

### ISSUE THREAD

**Issue by MiracleXYZ** [usememos/memos#1223]
### Is your feature request related to a problem?

Currently, the daily reviews generated are split at midnight. However, I often find myself taking notes after midnight, which means that those notes get included in the daily review for the next day.

### Describe the solution you'd like

To solve this issue, I would like to suggest adding a feature that allows users to customize the refresh time for their daily reviews. For example, users could set the refresh time to 4:00 AM, which would include all notes taken after midnight in the daily review.

I believe this feature would greatly improve the user experience and make the daily reviews more flexible for those who work late or have different schedules.

**Comment by titanventura** [comment]
Would like to take this up. Please assign !

**Comment by titanventura** [comment]
Here is my proposed solution. I need some suggestions before i start working on this.
1. The daily review time offset can be set by the user in the preferences section in settings.
2. The change will remain local similar to `Enable folding memo` and `Enable double-click to edit`. 
Are these assumptions right ?

**Comment by titanventura** [comment]
ping !

**Comment by boojack** [comment]
> Here is my proposed solution. I need some suggestions before i start working on this.
> 
> 1. The daily review time offset can be set by the user in the preferences section in settings. Currently i'm planning to place a select input for `hh` and `mm` fields to represent the time offset.
> 
> 2. The change will remain local similar to `Enable folding memo` and `Enable double-click to edit`. 
> 
> Are these assumptions right ?

SGTM

**Comment by titanventura** [comment]
#1313

**Comment by MiracleXYZ** [comment]
Works like a charm. Thanks!
