### ISSUE TITLE
only listen on ipv6:8081, no ipv4:8081 on linux system

### ISSUE THREAD

**Issue by toarms** [usememos/memos#1226]
### Describe the bug

compile and run memos on linux system, it only listen on ipv6 address, and not used ipv4.
suggest add an option to specify to use ipv6 or ipv4

### Steps to reproduce

1. go build
2. ./memos
3. netstat -ltn

**Comment by CorrectRoadH** [comment]
Are you have more information? I can't reproduce it.

**Comment by my-360** [comment]
I also have no ipv4 addr listen.
use command to start: 
docker run -d   --init    --name memos    --publish 5230:5230    --volume ~/.memos/:/var/opt/memos   ghcr.io/usememos/memos:latest

log as:
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:1399            0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:9993            0.0.0.0:*               LISTEN      -                   
tcp        1      0 127.0.0.1:47044         127.0.0.1:8091          CLOSE_WAIT  -                   
tcp        1      0 127.0.0.1:47026         127.0.0.1:8091          CLOSE_WAIT  -                   
tcp        1      0 127.0.0.1:58970         127.0.0.1:8091          CLOSE_WAIT  -                   
tcp        1      0 127.0.0.1:44702         127.0.0.1:8091          CLOSE_WAIT  -                   
tcp        0      0 172.27.94.195:43870     100.100.30.28:80        ESTABLISHED -                   
tcp        0      0 172.27.94.195:48288     100.100.0.70:80         TIME_WAIT   -                   
tcp        1      0 127.0.0.1:47054         127.0.0.1:8091          CLOSE_WAIT  -                   
tcp        0    432 172.27.94.195:22        183.238.238.29:53854    ESTABLISHED -                   
tcp        1      0 127.0.0.1:47030         127.0.0.1:8091          CLOSE_WAIT  -                   
tcp        1      0 127.0.0.1:45938         127.0.0.1:8091          CLOSE_WAIT  -                   
tcp6       0      0 :::5230                 :::*                    LISTEN      494058/containers-r 
tcp6       0      0 :::80                   :::*                    LISTEN      -                   
tcp6       0      0 :::443                  :::*                    LISTEN      -                   
tcp6       0      0 :::1399                 :::*                    LISTEN      -                   
tcp6       0      0 :::29418                :::*                    LISTEN      -                   
tcp6       0      0 :::8088                 :::*                    LISTEN      -                   
tcp6       0      0 :::8091                 :::*                    LISTEN      -                   
tcp6       0      0 :::8081                 :::*                    LISTEN      -                   
tcp6       0      0 :::9993                 :::*                    LISTEN      -
