### ISSUE TITLE
API amount has been removed. Is there any replacement？

### ISSUE THREAD

**Issue by penndu** [usememos/memos#1227]
### Describe the bug

API amount has been removed. Is there any replacement？

### Steps to reproduce

https://demo.usememos.com/api/memo/amount?creatorId=101

**Comment by boojack** [comment]
use `/api/memo/stats` https://github.com/usememos/memos/blob/main/server/memo.go#L336

**Comment by liweibiao** [comment]
<script>
  function clearInput() {
    const talkSearch = document.getElementById('talkSearch');
    talkSearch.value = '';
  }

  // 获取 Memos 总条数
  function getTotal() {
    var totalUrl = "https://memos网址/api/memo/stats?creatorId=101";
    fetch(totalUrl).then(response => {
      return response.json();
    }).then(data => {
      // 统计 data 数量并引用
      var memosCount = document.getElementById('memosCount');
      memosCount.innerHTML = data.data.length;
    }).catch(err => {
      // Do something for an error here
    });
  };

  window.onload = getTotal();
</script>
