### ISSUE TITLE
Update home page layout

### ISSUE THREAD

**Issue by boojack** [usememos/memos#1234]
We need to update the layout of the home page to a more modern three-column design, similar to Twitter and Mastodon, that is optimized for contemporary large-screen devices.

![Image](https://user-images.githubusercontent.com/24653555/222510064-3b08e2b9-5572-4771-a8d4-d9cb6906381b.png)

**Comment by jxpsert** [comment]
Where's the grid thingy going?

**Comment by boojack** [comment]
> Where's the grid thingy going?

Any ideas?
