### ISSUE TITLE
Upload local file wrong

### ISSUE THREAD

**Issue by Juskinbo** [usememos/memos#1237]
### Describe the bug

When I use pwa, and update local image, there is something wrong with the site.    

### Steps to reproduce

1. Using an iPhone
2. Using Safari
3. Adding the site to screen
4. Open the pwa 
5. Update local image

### Screenshots or additional context

![image](https://user-images.githubusercontent.com/54654557/222621268-84784ec6-0d58-462e-9dab-bcb2e03a7af0.png)
It's wierd that updating gif succeed, but jpg/png.... failed.

**Comment by jxpsert** [comment]
What exactly do you mean by 'pwa'?

**Comment by Juskinbo** [comment]
Progressive Web App, open a website and add to home screen to use it.

**Comment by Juskinbo** [comment]
> What exactly do you mean by 'pwa'?

Progressive Web App, open a website and add to home screen to use it.

**Comment by Juskinbo** [comment]
It looks like the new version fix it, thx.
