### ISSUE TITLE
能否添加自动识别设备语言？

### ISSUE THREAD

**Issue by powersee** [usememos/memos#1238]
### Is your feature request related to a problem?

目前程序运行后，默认使用的是英文。能否在第一次访问的时候，自动检查用户的系统语言，并自动切换？

### Describe the solution you'd like

我搜索了一下，似乎可以通过 js 来获取用户浏览器的语言，感觉应该是可以实现的。

**Comment by CorrectRoadH** [comment]
I reproduce it. It is a useful feature and a friendly design. I will code for implementing the feature.
