### ISSUE TITLE
允许设定带有某个tag的memos为默认公开，或私人

### ISSUE THREAD

**Issue by happyokay** [usememos/memos#1241]
### Is your feature request related to a problem?

当我设定memos为默认私人时，如果想公开某个memo，需要手动去调整。
如果可以设定打有某个tag的memo为默认公开（或私人）时，免去了我手动设置的动作。

### Describe the solution you'd like

允许我设定，打上某个tag的memo，默认状态为公开或私人
比如：当给一个memo加上#pubilic标签时，这个memo默认为公开的memo

**Comment by jxpsert** [comment]
Sounds like too complicated behaviour for memos. memos' beauty is simplicity.
I can't think of an implementation for this that isn't ugly.

**Comment by Zeng1998** [comment]
What's the difference in action between "add a tag #public" and "select the visibility of PUBLIC"?

And as @jxpsert said, its implementation is too complicated and ugly, in my imagination.

**Comment by b1n9s** [comment]
One case that I can think of is when you have a fair amount of private memos that contain the same tag, and then you want to make them public, instead of updating them one by one, is it possible to update them in a batch?
