### ISSUE TITLE
Create a `release/latest` branch to automatically deploy stable versions on render.com

### ISSUE THREAD

**Issue by MiracleXYZ** [usememos/memos#1244]
### Is your feature request related to a problem?

I currently have auto-deploy enabled on render.com, which is monitoring the `main` branch. However, the `main` branch is less stable compared to the `release/*` branches. If I switch to the `release/0.11.0` branch for stability purposes, auto-deploy will not function since no changes will be made to that particular branch.

### Describe the solution you'd like

Create a `release/latest` branch that mirrors the latest release branch. This way, switching to the `release/latest` branch will automatically trigger deployment whenever a new version of `memos` is released.

**Comment by jxpsert** [comment]
Sounds like easy implementation, high value.
