### ISSUE TITLE
交互式日历视图在0.11.1取消了，其实这个功能还挺好的

### ISSUE THREAD

**Issue by liu7526539** [usememos/memos#1253]
### Is your feature request related to a problem?

交互式日历视图在0.11.1取消了，其实这个功能还挺好的，作为日记使用的时候可以非常方便的看到之前一天的内容。也挺好看的

### Describe the solution you'd like

或许可以增加个开关来打开或关闭交互式日历视图，如果不能添加，可以在每日回顾里对有记录的日期进行作色突出显示
![20230304213430](https://user-images.githubusercontent.com/39986130/222905282-7701f4bc-1a23-499f-9660-1342afd2e1c6.png)

**Comment by MiracleXYZ** [comment]
I also miss this feature.

**Comment by moulai** [comment]
I also miss that heatmap, it really provided me with a lot of motivation to record memos. I hope there could be a switch that allows us to set whether or not to display the recording heatmap.

**Comment by moulai** [comment]
> I also miss that heatmap, it really provided me with a lot of motivation to record memos. I hope there could be a switch that allows us to set whether or not to display the recording heatmap.

Additionally, I hope there can be a switch to enable or disable the "Ask AI" feature. On one hand, some users (like myself) may not want to use AI assistance in their memos. On the other hand, OpenAI is inaccessible for users in certain regions.
