### ISSUE TITLE
How to install without Docker

### ISSUE THREAD

**Issue by YuzeTT** [usememos/memos#1254]
### Is your feature request related to a problem?

I need to install memos on the server without docker

### Describe the solution you'd like

I hope to run memos directly

**Comment by jxpsert** [comment]
The easy Docker setup is one of the things that makes memos so great. Why can't you use Docker?

**Comment by Mahoo12138** [comment]
```bash
cd web 
yarn
yarn build
# move the web/dist to server/dist
cd .. 
mv web/dist  server/dist
go build -o memos ./main.go
./memos --mode=prod --port=5230 --data=/your-data-path
```

**Comment by r0bbie** [comment]
Thanks for sharing build instructions @Mahoo12138! Might I suggest it would be worth including build instructions on https://usememos.com/docs/install ? And even better, providing built binary packages for those who aren't using Docker? :)

**Comment by jxpsert** [comment]
Feel free to make a PR on usememos/dotcom for this.

**Comment by 1michaelbrown** [comment]
@Mahoo12138 This almost worked for me. but For some reason I get this error in browser "No frontend embeded" on server side I get `{"time":"2023-08-25T22:51:45Z","method":"GET","uri":"/","status":200,"error":""}`

**Comment by jxpsert** [comment]
Is the API running?

**Comment by 1michaelbrown** [comment]
NO at least not to my knowledge. I only used the commands above.

**Comment by jxpsert** [comment]
Well that'll cause your error then

**Comment by 1michaelbrown** [comment]
Ok so I feel kind of dump asking. How do I get the api running?

**Comment by Mahoo12138** [comment]
> @Mahoo12138 This almost worked for me. but For some reason I get this error in browser "No frontend embeded" on server side I get `{"time":"2023-08-25T22:51:45Z","method":"GET","uri":"/","status":200,"error":""}` 

Check if the path `server/dist` is empty

**Comment by 1michaelbrown** [comment]
@Mahoo12138 It has the dist and web folder in it along with and index.html file

**Comment by 1michaelbrown** [comment]
@Mahoo12138 here is my install process if this helps.

When I run the command yarn in the web directory

yarn install v1.22.19
warning package.json: No license field  
info No lockfile found.
warning memos: No license field
[1/4] Resolving packages...
warning react-use > nano-css > sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "react-hot-toast > goober@2.1.13" has unmet peer dependency "csstype@^3.0.10".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 288.93s.



![Screenshot 2023-08-26 at 7 18 23 PM](https://github.com/usememos/memos/assets/123066581/78408b04-a628-44c6-a645-cb76c3f844d3)

Then I do yarn build 



![Screenshot 2023-08-26 at 7 24 18 PM](https://github.com/usememos/memos/assets/123066581/f3346201-e8c8-4ee9-b3c9-98536a531fa9)

Then I move the web and dist directory to server/dist

Then I run the command `go build -o memos ./main.go` in the root directory (memos)

go: downloading modernc.org/sqlite v1.24.0
go: downloading github.com/spf13/cobra v1.6.1
go: downloading github.com/spf13/viper v1.15.0
go: downloading go.uber.org/zap v1.24.0
go: downloading golang.org/x/crypto v0.12.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/fsnotify/fsnotify v1.6.0
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/spf13/afero v1.9.3
go: downloading github.com/spf13/cast v1.5.0
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading github.com/google/uuid v1.3.0
go: downloading github.com/labstack/echo/v4 v4.11.1
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/swaggo/echo-swagger v1.4.0
go: downloading go.uber.org/atomic v1.9.0
go: downloading go.uber.org/multierr v1.8.0
go: downloading golang.org/x/sys v0.11.0
go: downloading golang.org/x/text v0.12.0
go: downloading github.com/subosito/gotenv v1.4.2
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading gopkg.in/ini.v1 v1.67.0
go: downloading github.com/magiconair/properties v1.8.7
go: downloading github.com/pelletier/go-toml/v2 v2.0.6
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/labstack/gommon v0.4.0
go: downloading golang.org/x/net v0.14.0
go: downloading github.com/golang-jwt/jwt v3.2.2+incompatible
go: downloading github.com/valyala/fasttemplate v1.2.2
go: downloading golang.org/x/time v0.3.0
go: downloading github.com/swaggo/files/v2 v2.0.0
go: downloading github.com/swaggo/swag v1.16.1
go: downloading github.com/disintegration/imaging v1.6.2
go: downloading github.com/golang-jwt/jwt/v4 v4.5.0
go: downloading github.com/gorilla/feeds v1.1.1
go: downloading github.com/yuin/goldmark v1.5.4
go: downloading golang.org/x/exp v0.0.0-20230111222715-75897c7a292a
go: downloading github.com/google/cel-go v0.17.1
go: downloading github.com/grpc-ecosystem/grpc-gateway/v2 v2.16.2
go: downloading google.golang.org/grpc v1.57.0
go: downloading golang.org/x/mod v0.12.0
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/mattn/go-isatty v0.0.19
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: downloading github.com/KyleBanks/depth v1.2.1
go: downloading github.com/go-openapi/spec v0.20.9
go: downloading golang.org/x/tools v0.11.1
go: downloading golang.org/x/image v0.7.0
go: downloading golang.org/x/oauth2 v0.10.0
go: downloading github.com/aws/aws-sdk-go-v2 v1.17.4
go: downloading github.com/aws/aws-sdk-go-v2/config v1.18.12
go: downloading github.com/aws/aws-sdk-go-v2/credentials v1.13.12
go: downloading github.com/aws/aws-sdk-go-v2/feature/s3/manager v1.11.51
go: downloading github.com/aws/aws-sdk-go-v2/service/s3 v1.30.3
go: downloading google.golang.org/protobuf v1.31.0
go: downloading google.golang.org/genproto/googleapis/api v0.0.0-20230726155614-23370e0ffb3e
go: downloading google.golang.org/genproto v0.0.0-20230706204954-ccb25ca9f130
go: downloading google.golang.org/genproto/googleapis/rpc v0.0.0-20230726155614-23370e0ffb3e
go: downloading modernc.org/libc v1.22.5
go: downloading github.com/go-openapi/jsonpointer v0.20.0
go: downloading github.com/go-openapi/jsonreference v0.20.2
go: downloading github.com/go-openapi/swag v0.22.4
go: downloading github.com/aws/smithy-go v1.13.5
go: downloading github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.12.22
go: downloading github.com/aws/aws-sdk-go-v2/internal/ini v1.3.29
go: downloading github.com/aws/aws-sdk-go-v2/service/sso v1.12.1
go: downloading github.com/aws/aws-sdk-go-v2/service/ssooidc v1.14.1
go: downloading github.com/aws/aws-sdk-go-v2/service/sts v1.18.3
go: downloading github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream v1.4.10
go: downloading github.com/aws/aws-sdk-go-v2/internal/configsources v1.1.28
go: downloading github.com/aws/aws-sdk-go-v2/internal/v4a v1.0.20
go: downloading github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.9.11
go: downloading github.com/aws/aws-sdk-go-v2/service/internal/checksum v1.1.23
go: downloading github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.9.22
go: downloading github.com/aws/aws-sdk-go-v2/service/internal/s3shared v1.13.22
go: downloading github.com/stoewer/go-strcase v1.2.0
go: downloading github.com/antlr/antlr4/runtime/Go/antlr/v4 v4.0.0-20230305170008-8188dc5388df
go: downloading github.com/golang/protobuf v1.5.3
go: downloading github.com/dustin/go-humanize v1.0.1
go: downloading modernc.org/mathutil v1.5.0
go: downloading modernc.org/memory v1.5.0
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading github.com/jmespath/go-jmespath v0.4.0
go: downloading github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.4.22
go: downloading github.com/remyoudompheng/bigfft v0.0.0-20230129092748-24d4a6f8daec
go: downloading github.com/josharian/intern v1.0.0

I then run the last command `./memos --mode=prod --port=5230 --data=/home/mike/memos/data`


![Screenshot 2023-08-26 at 7 32 05 PM](https://github.com/usememos/memos/assets/123066581/40df14b1-430e-46e3-abb5-e0713de958d4)

**Comment by Jungack** [comment]
This is based on what I found in the `./Dockerfile`. Updated for Release 0.15.2.

0. Having `Go`, `nodejs` and `npm` installed. Try to have the latest versions of these programs or this can lead to unexpected errors (For example, having used a verison of `Go` < 1.21 lead to some problems for me).
1. Install `buf` (https://buf.build/docs/installation). For example, from binary (It seems better according to the doc to install from binary than install from source as `./Dockerfile` does):

```
# Substitute BIN for your bin directory.
# Substitute VERSION for the current released version.
BIN="/usr/local/bin" && \
VERSION="1.26.1" && \
curl -sSL \
"https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-$(uname -s)-$(uname -m)" \
-o "${BIN}/buf" && \
chmod +x "${BIN}/buf"
```

2. Go to `./proto`
3. Execute command `buf generate`
4. Go to `./web`
5. Execute command `corepack enable && pnpm i --frozen-lockfile`
6. Execute command `pnpm build`
7. Go to `./`
8. Copy the content of dist folder of `./web` to the dist folder of `./server` with: `cp ./web/dist/* ./server/dist/`
9. Execute command `CGO_ENABLED=0 go build -o memos ./main.go`

Now when you want to launch memos, just execute
`MEMOS_MODE="prod" MEMOS_PORT="5230" MEMOS_DATA=/var/opt/memos ./memos`
in the root of the project. Be sure to have `MEMOS_DATA` directory created, else create before executing the command.
On the web browser, just go to `localhost:5230` and sign up for first use.

Note that there a `build.sh` script in `./scripts`, but It seems that It has not been updated to add the steps of using `buf`.
