### ISSUE TITLE
Is encryption planned?

### ISSUE THREAD

**Issue by foozzi** [usememos/memos#1258]
AES-256/CHACHA20?

**Comment by foozzi** [comment]
> What part of the content needs to be encrypted? memo's content?

Yes, memo's content

**Comment by okainov** [comment]
Also not sure, why was this closed? See also #2161 #1480 which are closed without comments. @boojack could you please clarify the direction here?

**Comment by albotroz** [comment]
I also wonder why this feature suggestion of all things is constantly being closed.

**Comment by salemaziel** [comment]
Also wonder why this keeps getting close, and would also like to see this feature
