### ISSUE TITLE
Feature request - share notes to other users in memos

### ISSUE THREAD

**Issue by DHS1001** [usememos/memos#126]
**Describe feature**
Currently, the notes in Memos is not able be shared to other users in Memos, unless it is set to public.
But when setting the notes to public, it is available to all (with or without being a user in Memos).
Is it  possible to add the feature to share the notes to specific users (or user group) in Memos?

Thanks

**Comment by boojack** [comment]
> share the notes to specific users

This might be some tough to do. But I think we can share the notes to the users in memos firstly. wdyt?

**Comment by DHS1001** [comment]
> But I think we can share the notes to the users in memos firstly

I can see share button is to save as local png file. 
Can you please advise how to share with other users in memos ? Thanks

**Comment by DHS1001** [comment]
> I'd like to add a new type `PROTECTED` which means visible for **all members**.

@boojack  That would be awesome if the `PROTECTED` type will be available soon.

**Comment by boojack** [comment]
TODO list:
- [x] udpate memo table schema; https://github.com/usememos/memos/pull/132
- [ ] update backend api;
- [ ] update frontend UI;

**Comment by boojack** [comment]
@DHS1001 Released in [v0.3.0](https://github.com/usememos/memos/releases/tag/v0.3.0)
