### ISSUE TITLE
Sort memos by updatedTs

### ISSUE THREAD

**Issue by Zeng1998** [usememos/memos#1261]
### Is your feature request related to a problem?

I'm sure this is necessary for some users.

### Describe the solution you'd like

It is expected to select the sorting way directly on the home page.

There is no good implementation for now. I think it depends on the query API on the backend.

**Comment by moulai** [comment]
I need this feature too! Thanks a lot.

**Comment by titanventura** [comment]
Would like to work on this. Please assign !

**Comment by titanventura** [comment]
Im thinking of giving this as a preference to the user. They can upsert remote setting in the preferences page and in the backend, the list memos endpoint can return memos either in sorted or unsorted way based on the preference. Please let me know if this approach is fine to work on.

**Comment by titanventura** [comment]
or probably a better option would be to keep the preference locally and use a query param for sorting in the `MemoFind` object.

**Comment by Zeng1998** [comment]
In fact, it was implemented in the old versions, you can refer to it.

**Comment by titanventura** [comment]
may i know which issue/commit/PR to refer to for this ?

**Comment by Zeng1998** [comment]
#312

Just for reference, feel free to try by yourself.

**Comment by titanventura** [comment]
should i implement the sorting logic in the frontend or in the backend ?
