### ISSUE TITLE
热力图的位置，星期显示有点问题

### ISSUE THREAD

**Issue by liu7526539** [usememos/memos#1265]
### Describe the bug

热力图的位置，星期显示有点问题
![20230305092426](https://user-images.githubusercontent.com/39986130/222936582-6b57b230-cdf6-468a-bfc8-70e5b4c599ef.png)

### Steps to reproduce

1.首页
2.右上角热力图
星期不显示

**Comment by jaywhen** [comment]
应该是改成了鼠标 hover 可见了，详见这个pr [1255](https://github.com/usememos/memos/pull/1255/files)
