### ISSUE TITLE
使用标签搜索后，点击“主页”，无法显示全部的备忘录

### ISSUE THREAD

**Issue by liu7526539** [usememos/memos#1266]
### Describe the bug

使用标签搜索后，点击“主页”，无法显示全部的备忘录。希望能改成点击“主页”，页面显示全部的备忘录

### Steps to reproduce

1.在主页使用搜索
2.点击主页
页面没有变化，还是之前搜索时的内容，希望能在点击“主页”后，去除搜索条件

**Comment by jxpsert** [comment]
duplicate of #1257
