### ISSUE TITLE
更新0.11.1后热力图消失了。

### ISSUE THREAD

**Issue by hellspector** [usememos/memos#1268]
### Describe the bug

昨天更新后热力图消失了。
![image](https://user-images.githubusercontent.com/80568889/222941263-e0f58779-536a-47eb-9fcd-a0e56bc83e0b.png)

### Steps to reproduce

更新0.11.1右边侧栏势力图消失。
重装删除docker安装，还是没有。

**Comment by boojack** [comment]
再拉一下最新的 latest image

**Comment by hellspector** [comment]
好的~~
