### ISSUE TITLE
0.11.1移动端搜索框的位置

### ISSUE THREAD

**Issue by hellspector** [usememos/memos#1269]
### Is your feature request related to a problem?

更新0.11.1后，移动端搜索框的位置也发生了变化，直接变成一个按钮了。
其实搜索这个功能非常常用，以前只需要点击搜索框就可以输入内容了，

现在要两步：
点击搜索
然后再点击框输入内容。

如下图，原来在输入内容框右上角挺好的。
![image](https://user-images.githubusercontent.com/80568889/222941421-adc61997-f9fd-4168-bbb1-4edc1c525c32.png)

### Describe the solution you'd like

更新到0.11.1后出现的问题。

**Comment by jas0ncn** [comment]
可以关注下 https://github.com/usememos/memos/pull/1304
