### ISSUE TITLE
关于nginx反向代理后无法上传图片的问题

### ISSUE THREAD

**Issue by Kellermaan** [usememos/memos#128]
你好，很喜欢你的这个作品，我在使用的时候碰到一个问题。就是我如果使用nginx作为反向代理的话，好像没办法上传图片。不知道是我的使用问题还是什么？非常感谢。

**Comment by boojack** [comment]
可以提供下报错信息吗，比如网页端的请求返回数据，或者可以通过 `docker logs` 来查看后台的日志。

**Comment by Kellermaan** [comment]
更新一下问题，问题好像是，如果这个服务隐藏在nginx后面，那我只能上传很小的图片。如果是比较大的图片会在右侧出现一个白框，不知道是什么意思。红色框框标注的地方。
![图片](https://user-images.githubusercontent.com/11674190/180611515-8cd0f868-ea2d-4ab9-aa7d-4fcced4995b9.png)

**Comment by Kellermaan** [comment]
> 可以提供下报错信息吗，比如网页端的请求返回数据，或者可以通过 `docker logs` 来查看后台的日志。

后端docker没发现有log，网页端报告的是这个：

Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bmessage%2C%20name%2C%20code%2C%20config%2C%20request%2C%20response%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    Si https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:30
    w https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:30
    Fe https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:32
    sy https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:32
    iy https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:32
    o1 https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:32
    fa https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:32
    Eu https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:32
    ny https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:32
    C https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:17
    K https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:17
    jO https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:17
    jO https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:17
    Jv https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:1
    <anonymous> https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:84
[index.ce4d7ff1.js:32:175](https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js)
Uncaught Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bmessage%2C%20name%2C%20code%2C%20config%2C%20request%2C%20response%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    Si https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:30
    w https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:30
    Fe https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:32
    sy https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:32
    iy https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:32
    o1 https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:32
    fa https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:32
    Eu https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:32
    ny https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:32
    C https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:17
    K https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:17
    jO https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:17
    jO https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:17
    Jv https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:1
    <anonymous> https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js:84
[index.ce4d7ff1.js:30:12797](https://memos.ichengj.com:4433/assets/index.ce4d7ff1.js)

​

**Comment by boojack** [comment]
> 更新一下问题，问题好像是，如果这个服务隐藏在nginx后面，那我只能上传很小的图片。如果是比较大的图片会在右侧出现一个白框，不知道是什么意思。红色框框标注的地方。

“比较大”大概是多大呀，目前好像是限制在 8MB 一下。

**Comment by Kellermaan** [comment]
> > 更新一下问题，问题好像是，如果这个服务隐藏在nginx后面，那我只能上传很小的图片。如果是比较大的图片会在右侧出现一个白框，不知道是什么意思。红色框框标注的地方。
> 
> “比较大”大概是多大呀，目前好像是限制在 8MB 一下。

三四MB的就不行了，刚刚试了几百k的可以。

**Comment by Kellermaan** [comment]
顺便插一句嘴，如果图片可以上传的对象存储，这里做一个链接引用会很好，图片加载也会快很多，我看到有人提这个需求了。

**Comment by boojack** [comment]
> 顺便插一句嘴，如果图片可以上传的对象存储，这里做一个链接引用会很好，图片加载也会快很多，我看到有人提这个需求了。

目前图片显示的话就是一个图片链接，可以理解为目前自带了一个对象存储。

**Comment by Kellermaan** [comment]
> > 顺便插一句嘴，如果图片可以上传的对象存储，这里做一个链接引用会很好，图片加载也会快很多，我看到有人提这个需求了。
> 
> 目前图片显示的话就是一个图片链接，可以理解为目前自带了一个对象存储。

好的，主要是考虑到图片流量分流的问题，不过的确，这个功能有没有也不重要，就算用markdown另外引用也可以。

这个问题你复现出来了么？

**Comment by Kellermaan** [comment]
我在你的demo上好像也能复现这个问题。

**Comment by boojack** [comment]
没能复现，要不你把能出问题的图片发下 ;(

**Comment by Kellermaan** [comment]
我用的这张图片，就不行。或者是不是nginx有什么特殊的配置我需要加的？
![STScI-01G7WCK1PJEM49E118GEG0Q729](https://user-images.githubusercontent.com/11674190/180612992-cc38dc74-2769-4d7a-99c9-05e234d2b4cd.png)

**Comment by Kellermaan** [comment]
找到原因了，是我的nginx 没有配置client_max_body_size，配完了这个就可以了，非常感谢。
