### ISSUE TITLE
ai 允许设置反代地址

### ISSUE THREAD

**Issue by lmm214** [usememos/memos#1280]
### Is your feature request related to a problem?

若 ask ai 也允许设置反代地址，那就方便多了

### Describe the solution you'd like

顺利用上 [使用 Cloudflare Workers 解决 OpenAI 和 ChatGPT 的 API 无法访问的问题] (https://github.com/noobnooc/noobnooc/discussions/9)

**Comment by s544838371** [comment]
ask ai在哪里设置反代地址？没找到设置地方
