### ISSUE TITLE
日语键盘回车是输入单词，ask ai按一个回车就提交了，有更好的解决方案吗

### ISSUE THREAD

**Issue by SonnTakuu** [usememos/memos#1283]
### Describe the bug

日语键盘回车是输入单词，ask ai按一个回车就提交了.
有更好的解决方案吗

### Steps to reproduce

点击Ask ai
使用日语输入法输入单词
确认单词使用的是[Enter] Key
然后就被提交了

**Comment by Joeywzr** [comment]
Same question

**Comment by gitkeniwo** [comment]
I have the same problem when using Pinyin keyboard on macos to type English words for convenience. When I press Enter the word simply doubles.
