### ISSUE TITLE
v0.11.1丢失pwa模式

### ISSUE THREAD

**Issue by xxzj990** [usememos/memos#1284]
### Describe the bug

PC环境，使用最新版的chrome，打开网页后地址栏没有pwa的图标了，无法以pwa的形式创建应用。

### Steps to reproduce

1、更新到v0.11.1
2、使用最新版chrome打开web页面
3、无法添加pwa

### Screenshots or additional context

没有pwa图标，如下图：
![1](https://user-images.githubusercontent.com/5134154/223006503-5cc0c77d-79e5-4f62-bd9a-67a63f3f2527.png)

正常应该如下图：
![2](https://user-images.githubusercontent.com/5134154/223006551-dd53a62c-291b-4046-a88c-7e61a6027f9c.png)

**Comment by Zeng1998** [comment]
![image](https://user-images.githubusercontent.com/31177490/223007251-f73f0c2d-5873-4fd5-9a7e-1d7e06fd370b.png)

**Comment by xxzj990** [comment]
> ![image](https://user-images.githubusercontent.com/31177490/223007251-f73f0c2d-5873-4fd5-9a7e-1d7e06fd370b.png)

好奇怪，demo确实是好的，我的就是出不来。。。有可能是我环境的问题，我试了清缓存好像也不行
