### ISSUE TITLE
Change shortcut key in settings

### ISSUE THREAD

**Issue by kazuki-hanai** [usememos/memos#1286]
### Is your feature request related to a problem?

I useally use `ctrl + e` as go to end of line in editor. But in memos, this shortcut is used as inputting backticks(``) . 

### Describe the solution you'd like

We should manage shortcuts in settings.

**Comment by boojack** [comment]
I'd like to remove the auto-complete action with `ctrl + e`. WDYT?

**Comment by kazuki-hanai** [comment]
@boojack I think it's a good change.

**Comment by kazuki-hanai** [comment]
I think `ctrl+c` is better because of below reasons.
- `ctrl+c` doesn't conflict other shortcuts
- It's easier to see that `c` means code shortcut
