### ISSUE TITLE
Should support automatic renaming of uploaded files.

### ISSUE THREAD

**Issue by sssoa** [usememos/memos#1295]
### Is your feature request related to a problem?

I am using Minio to set up a file storage. When I upload multiple images with the same name (but different contents), only the last uploaded file is saved for download, and the previously uploaded file with the same name is overwritten.

### Describe the solution you'd like

Add an option to the storage management system that automatically modifies the file name to a random name (e.g. UUID) when uploading a file to the storage.

**Comment by boojack** [comment]
We don't rename it automatically, which is not a good solution. Instead, we'd like to add a path template in https://github.com/usememos/memos/pull/1285.
