### ISSUE TITLE
Ask AI history list reversed when loading answer

### ISSUE THREAD

**Issue by jaywhen** [usememos/memos#1297]
### Describe the bug

before ask ai question the history list will be like：
<img width="552" alt="2023-03-07 01 18 04" src="https://user-images.githubusercontent.com/50481203/223184610-6176a557-ea4a-48ab-b2a2-a4cf9cec4588.png">

when enter the question, will show loading, and the history list will reverse：

<img width="747" alt="2023-03-07 01 18 20" src="https://user-images.githubusercontent.com/50481203/223185478-cac4dc1f-bc94-4c21-ae99-2b7cffe2ed23.png">

perhaps it's a feature not a bug 😅

### Steps to reproduce

1. Ask AI
2. ask 3+ question, watch for changes in the history list

### Screenshots or additional context

if it's not a feature, i think insert the new anwser at the head of the historyList and render `historyList.map(...` at line 89 will be a solution to resolve this
https://github.com/usememos/memos/blob/595dbdb0ecb1eada129e21f1c1580d86dd256534/web/src/components/AskAIDialog.tsx#L62-L68

**Comment by boojack** [comment]
> perhaps it's a feature not a bug 😅

This is definitely a bug🐛
