### ISSUE TITLE
v0.11.1版本好像账号信息无法修改！

### ISSUE THREAD

**Issue by YydsChen** [usememos/memos#1303]
### Describe the bug

Memos`v0.11.1`版本好像账号信息无法修改！

### Steps to reproduce

我测试了好多次，包括换安装环境都是一样。😑

**Comment by Zeng1998** [comment]
Fixed, just re-pull the latest image.

**Comment by YydsChen** [comment]
0k, thank you.

**Comment by YydsChen** [comment]
@Zeng1998

好的，感谢~
