### ISSUE TITLE
Aliyun OSS upload error

### ISSUE THREAD

**Issue by shelken** [usememos/memos#1305]
### Describe the bug

配置阿里云oss上传错误
Configuring Aliyun OSS upload error.

### Steps to reproduce

![](https://assets.shelken.top/ali/PicGo/2023-03/60c773fa.png)

```
{
  "error": "code=500, message=Failed to upload via s3 client, internal=operation error S3: PutObject, https response error StatusCode: 403, RequestID: xxxx, HostID: xxxxx.oss-cn-hongkong.aliyuncs.com, api error SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.",
  "message": "Failed to upload via s3 client"
}


```

**Comment by Ren-0804** [comment]
我是像这样配置的 可以上传
[https://tc.iimx.cn/picgo/202303080855289.png](url)

**Comment by Ren-0804** [comment]
我是像这样配置的 可以上传
![](https://tc.iimx.cn/picgo/202303080855289.png)

**Comment by shelken** [comment]
问题解决了，Storage Path多了个「/」: /memos -> memos

The problem has been solved. Storage Path has written an extra "/": /memos ->memory
