### ISSUE TITLE
请问支持多用户吗？支持的话应该怎么添加别的用户呢？

### ISSUE THREAD

**Issue by Kellermaan** [usememos/memos#131]
非常喜欢你的作品，我找了好几年了，都没找到如此符合我心意的开源解决方案。非常感谢。
我有一个问题。
请问支持多用户吗？支持的话应该怎么添加别的用户呢？

**Comment by boojack** [comment]
如果你是 HOST 用户（类似于管理员的概念），可以到 Setting -> Member -> Create a member

<img width="717" alt="image" src="https://user-images.githubusercontent.com/24653555/180630490-5be23a59-884a-4da8-b1be-856f800abade.png">

（BTW，可以加一下 tg 群，之前有人问过这样的问题

**Comment by Kellermaan** [comment]
好，学会了。感谢感谢！
