### ISSUE TITLE
新标签未出现在标签列表中

### ISSUE THREAD

**Issue by skyue** [usememos/memos#1310]
### Describe the bug

如图所示
版本：0.11.1

### Steps to reproduce

null

### Screenshots or additional context

<img width="713" alt="image" src="https://user-images.githubusercontent.com/10450242/223717468-5804e817-a24e-4439-80d2-519b2e18bee7.png">

**Comment by skyue** [comment]
@boojack  哦哦，我使用了ios版Moe Memos发布的。其它没有什么特别的了。不确定是不是客户端问题。

**Comment by qrzbing** [comment]
> @boojack 哦哦，我使用了ios版Moe Memos发布的。其它没有什么特别的了。不确定是不是客户端问题。

这是客户端的问题，在使用网页发布 memo 时，它的行为是 `POST /api/memo`，然后对你添加的 tag 分别 `POST /api/tag`。但是 MoeMemos 客户端的行为只有前一个，也就是仅 `POST /api/memo`
