### ISSUE TITLE
Allow path style access for s3 compatible service

### ISSUE THREAD

**Issue by Cologler** [usememos/memos#1320]
### Is your feature request related to a problem?

By default (https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-bucket-intro.html), the S3 client will use virtual hosted bucket addressing, which causes memos unable to access the local minio server with IP.

### Describe the solution you'd like

An option to set use path style endpoint or not.

**Comment by Zeng1998** [comment]
#1176
