### ISSUE TITLE
ASK AI’s search box will go beyond the screen display on mobile devices.

### ISSUE THREAD

**Issue by smalljunxing** [usememos/memos#1329]
### Describe the bug

As the title says, ASK AI’s search box will go beyond the screen display on mobile devices.

### Steps to reproduce

For example: as long as on mobile devices, or screen width is less than 480px, the search box will display abnormally.

### Screenshots or additional context

![image.png](https://s2.loli.net/2023/03/10/UjkznXHVhuNYZxy.png)

**Comment by Wujiao233** [comment]
Already fix in #1277 . You can waiting for next release.
