### ISSUE TITLE
提供对一条 memos 进行类似评论的功能

### ISSUE THREAD

**Issue by alimy** [usememos/memos#1335]
### Is your feature request related to a problem?

写了一条memos后，记录了当下的想法，之后(几小时、几天、更久)或许有与该memos相关的新想法或者新批注，虽然memos可以随时重新编辑的功能，但是我依然想保留旧的memos，仅仅添加关于该memos的新想法，以保留 该memos的 想法演进脉络。

### Describe the solution you'd like

* 添加类似评论功能，自己的memos自己评论，也不违和啊，也可以开放给其他人来评论。
* 评论功能可以使用其他名字装饰，比如 批注？ 但是UI体验应该和评论类似，简单、快捷、有效。

**Comment by SkysCrystal** [comment]
I second this.

**Comment by tianrking** [comment]
I love this idea XD

**Comment by musnows** [comment]
I love this idea

**Comment by liuts** [comment]
I love this idea

**Comment by alimy** [comment]
Nice job~
