### ISSUE TITLE
支持Ask AI 走代理

### ISSUE THREAD

**Issue by wolfcdd** [usememos/memos#1340]
### Is your feature request related to a problem?

目前Ask AI 只能走全局代理，希望能单独给Ask AI设置独立的代理

### Describe the solution you'd like

通过给Ask AI 设置独立的代理接入chatgpt的api

**Comment by boojack** [comment]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/24653555/230239443-6c15d425-ea00-48f3-9388-6e43ef5bf430.png">
