### ISSUE TITLE
storage minio not work

### ISSUE THREAD

**Issue by kylehz** [usememos/memos#1344]
### Describe the bug

我创建了一个minio的storage，如下
<img width="424" alt="SCR-20230312-wcp" src="https://user-images.githubusercontent.com/20038464/224554346-5fe66b0e-f98b-4711-9556-ecc69e164593.png">
几个问题：
1.我的minio api地址是 `https://minio-api.example.com` ，但是我创建时候Endpoint不得不填成`https://example.com`，然后在bucket这边填`minio-api`，这样最终传图片的时候才会拼接成正确的api地址
2.图片是上传成功了，但是无法访问，如图：
<img width="973" alt="image" src="https://user-images.githubusercontent.com/20038464/224554521-9b85ce8a-d29e-4c59-a26b-061f463b32c4.png">

原因是图片是错的，从新标签打开图片得到的链接是：
`https://demo.usememos.com/aa/memos/2023/03/download_icon.png.image/png`

### Steps to reproduce

1.配置minio
2.上传图片

**Comment by Zeng1998** [comment]
1. It's expected.
2. Check if you have selected MinIO as your storage service.

**Comment by kylehz** [comment]
> 1. It's expected.
> 2. Check if you have selected MinIO as your storage service.
我当然是选了minio，图片上传是成功的，但是无法显示，另外就是在memos中minio配置不方便

**Comment by boojack** [comment]
> 我配置了URL Prefix为`https://minio-api.example.com`，得到的图片地址是 ` https://minio-api.example.com/memos/2023/03/download_icon.png.image/png `  依然无法访问图片

试试把 path 后面的 .filetype 去掉

**Comment by kylehz** [comment]
> 试试把 path 后面的 .｛filetype｝ 去掉

地址是对了，`https://minio-api.example.com/memos/2023/03/download_icon.png`
但是AccessDenied了，访问图片没有带上秘钥吗

```
<Code>AccessDenied</Code>
<Message>Access Denied.</Message>
<Key>2023/03/download_icon.png</Key>
<BucketName>memos</BucketName>
<Resource>/memos/2023/03/download_icon.png</Resource>
<RequestId>174C263F022BF893</RequestId>
<HostId>d669934d-6605-4c3f-ae5f-320acfbea834</HostId>
```

**Comment by ivanusong** [comment]
我遇到了一样的问题，虽然我解决了。但是 `{filename}` 变量获取的是带了扩展名的文件名称（当然也包含那个点），而且 `{filetype}` 竟然获取的不是文件扩展名，而是像是 `image/png` 这样的文件类型，这些是我真正希望修复的。当然，如果能早日解决附件存储在数据库外部的问题，应该也不会考虑自己搭建 minio 了吧

**Comment by s544838371** [comment]
我想咨询下，我的当前存储没法选择minio，选择了会自动跳回到Database，这是为什么？
EndPoint是https://share.域名:端口，我哪里填的不对吗，我相同配置的另外一个Bucket，在SiYuan笔记里就能正常用，但是在Memos里不行
