### ISSUE TITLE
最新版本，手机端web界面异常

### ISSUE THREAD

**Issue by hellspector** [usememos/memos#1345]
### Describe the bug

更新最新版本后，手机端web界面异常2点
1.展开按钮跑到菜单上面了
2.整体界面出现了横线的滚动条，滚动的时候，整个界面是可以左右拉动的。以前版本是没有的。

### Steps to reproduce

手机web打开memo就行safari chrome都一样。

### Screenshots or additional context

![6048A3DE-60A7-44CF-90DC-2CC6B59F278D](https://user-images.githubusercontent.com/80568889/224559168-06aaee69-6f58-48bd-9c2a-fc357eba6c59.jpeg)

**Comment by powersee** [comment]
![Screenshot_2023-03-15-21-18-21-073_com yandex browser](https://user-images.githubusercontent.com/38074760/225320563-8bc1e794-c46a-4a20-a4ef-7a9de2d883ed.jpg)

补充一个刚发现的 bug ，在手机端点击搜索，点击一次，自己弹出键盘，需要再点击一次搜索，才能出现搜索框。刚好看到这个 issue 是反馈 web 界面的，就在这下面补充一下。

**Comment by smalljunxing** [comment]
补充一个：我使用安卓 Chrome 浏览器点击搜索，侧栏会弹出一下然后自动收回。

**Comment by boojack** [comment]
应该已经修复了，有空的话试试最新的 demo: https://demo.usememos.com/

**Comment by hellspector** [comment]
> 应该已经修复了，有空的话试试最新的 demo: https://demo.usememos.com/

没有修复，手机上还是有莫名其妙的更像滚动条，向下滚动的时候，界面会左右滑动。

**Comment by lhuanyun** [comment]
距离最新版本发布至今21天，demo站点对于ios15 依赖存在视图偏移错位的问题，慢慢等待修复了

**Comment by Mahoo12138** [comment]
> 补充一个：我使用安卓 Chrome 浏览器点击搜索，侧栏会弹出一下然后自动收回。

https://github.com/usememos/memos/issues/1483

**Comment by boojack** [comment]
Maybe already fixed in `v0.13.0`. Feel free to reopen this if it still exists.
