### ISSUE TITLE
demo 的登陆好像出问题了 ~

### ISSUE THREAD

**Issue by izkizk8** [usememos/memos#1353]
### Describe the bug

demo 的默认账号登陆出现问题

### Steps to reproduce

1. Go to [live demo](https://demo.usememos.com/explore)
2. Click Sign in
3. See error

### Screenshots or additional context

![image](https://user-images.githubusercontent.com/68503578/225056785-9360a3a1-d953-4601-a2cd-eadbc1e85671.png)

**Comment by boojack** [comment]
应该是有人修改 demo 用户的密码了，环境已经重制，感谢反馈
