### ISSUE TITLE
Visible to anyone who gets the link

### ISSUE THREAD

**Issue by nexmoe** [usememos/memos#1361]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

attach a random key when copying the link, and those who visit the link with the correct key can see the content

**Comment by chaosclarity84** [comment]
Would also like to see this. Send like a basic sharing fundamental that is really needed.

**Comment by chaosclarity84** [comment]
This isn't implemented yet. The feature should be a unique link that is shareable to anyone publicly, while also keeping the memo private. This would be akin to something like sharing a google photos link to anyone as long as they have the unique link.

**Comment by athurg** [comment]
If we can view a memo with a special link, we also need to support revoke  or refresh it. And consider whether we need more than one link for a specified memo.

By the way, how about support this in other objects, such as resources.
