### ISSUE TITLE
Can the editor support shortcut key paste function to help me quickly upload image resources?

### ISSUE THREAD

**Issue by EliazTray** [usememos/memos#1363]
### Is your feature request related to a problem?

When editing a memo, if I need to insert an image, I have to manually upload it which interrupts my workflow.

### Describe the solution you'd like

When I use the "paste" command(such as Command + V), the contents of the clipboard will be uploaded to a remote OSS service.

**Comment by boojack** [comment]
This should have been already implemented. You can paste your image in the editor with `cmd/ctrl + v`.

**Comment by EliazTray** [comment]
> This should have been already implemented. You can paste your image in the editor with `cmd/ctrl + v`.

okay.
The reason for the previous failure was that the image was too large(300kb) when using R2.
