### ISSUE TITLE
i updated to v0.11.2 lost all my previous memos😢

### ISSUE THREAD

**Issue by lewislovelock** [usememos/memos#1364]
### Describe the bug

I followed these steps:
```
docker stop memos
docker rm memos
docker pull neosmemo/memos:latest
docker run -d --name memos -p 5230:5230 -v ~/.memos/:/var/opt/memos neosmemo/memos:latest
```
then I signed in with another username by mistake.
even when I switch back to my previous username and password,
all my memos are now gone.😭

Could someone please tell me the right steps?

### Steps to reproduce

```
docker stop memos
docker rm memos
docker pull neosmemo/memos:latest
docker run -d --name memos -p 5230:5230 -v ~/.memos/:/var/opt/memos neosmemo/memos:latest
```

**Comment by unliar** [comment]
你需要确认一下之前被你删掉的 container 是否挂载磁盘目录到宿主机了。

You need to confirm whether the container you deleted earlier has mounted a disk directory to the host machine.

**Comment by unliar** [comment]
由于你已经删除了container， 要是你没有挂载磁盘目录，我觉得你的数据可能救不回来了。

Since you have already deleted the container, if you did not mount a disk directory, I think it may not be possible to recover your data.

**Comment by lewislovelock** [comment]
> 由于你已经删除了container， 要是你没有挂载磁盘目录，我觉得你的数据可能救不回来了。
> 
> Since you have already deleted the container, if you did not mount a disk directory, I think it may not be possible to recover your data.

十分感谢，我可能第一次没有正确挂到磁盘目录，之前的数据不多，问题不大。

Thanks a lot. I may not have mounted the disk directory correctly for the first time, and there wasn't much data before, so it's not a big problem.
