### ISSUE TITLE
memos是否可以增强安全性

### ISSUE THREAD

**Issue by mossexplore** [usememos/memos#1365]
### Is your feature request related to a problem?

1、memos当前用户登录只有用户名和密码，是否可以加个登录验证码验证，或者Authenticator验证器，防止暴力破解，增强系统安全性
2、当前api无鉴权便可直接访问，从接口角度考虑，是否可以添加api的ak和sk访问机制？按照当前的使用方式，任何人可以调用接口写内容，完全可以整垮系统

### Describe the solution you'd like

1、登录有验证机制
2、api有签名机制

**Comment by boojack** [comment]
> 是否可以加个登录验证码验证，或者Authenticator验证器，防止暴力破解，增强系统安全性

已经在 roadmap 里了

> api 无鉴权便可直接访问

应该是有鉴权相关的逻辑，具体是哪个 api 不需鉴权就能写内容？

**Comment by njlcl** [comment]
> > 是否可以加个登录验证码验证，或者Authenticator验证器，防止暴力破解，增强系统安全性
> 
> 已经在 roadmap 里了
> 
> > api 无鉴权便可直接访问
> 
> 应该是有鉴权相关的逻辑，具体是哪个 api 不需鉴权就能写内容？

我的账号中的Open Api: 
POST https://XXXXXX/api/memo?openId=XXXXXXXXXX
Content-type: application/json
{
  "content": "Hello #memos from XXXXXXXXXX"
}

**Comment by boojack** [comment]
> 我的账号中的Open Api:
> POST https://xxxxxx/api/memo?openId=XXXXXXXXXX

没有 openId 或者错误的 openId 是不能通过这个 API 创建 memo 的。你说的“不需鉴权”指的是？

**Comment by mossexplore** [comment]
> > 我的账号中的Open Api:
> > POST https://xxxxxx/api/memo?openId=XXXXXXXXXX
> 
> 没有 openId 或者错误的 openId 是不能通过这个 API 创建 memo 的。你说的“不需鉴权”指的是？

是的，尽管这个id是个uuid，但是从接口角度看没AK和SK认证安全

**Comment by Cologler** [comment]
以 UUID 作为令牌足以防止暴力破解，在考虑被成功暴力破解出正确的 UUID 以前，你得先考虑你服务器受到这个量级（以 UUID 4 变体 1 可能性 2^122 算，每秒一百万请求并持续 1.68*10^22 年）的 DDoS 攻击能否承受得住。
