### ISSUE TITLE
Toggleable auto-folding behavior

### ISSUE THREAD

**Issue by NiekSulter** [usememos/memos#1369]
### Is your feature request related to a problem?

Update 0.11.2 added the automatic folding of memos when content overflows.

### Describe the solution you'd like

Make the automatic folding behavior toggleable in the settings menu.

**Comment by boojack** [comment]
As you wish

<img width="1134" alt="image" src="https://github.com/usememos/memos/assets/24653555/23d397fa-7b32-4817-9815-9d060dbb2d53">
