### ISSUE TITLE
the tag can not be recognized if the tag is at the end of memo

### ISSUE THREAD

**Issue by theChrisWei** [usememos/memos#137]
## the tag can not be recognized if the tag is at the end of memo.
for example,
`test tag #tag1`
the `tag1` can not be recognized due to its location is at the end of memo
but
`test tag #tag1 test`
the `tag1` can be recognized as expected

screenshot shown as below:
<img width="638" alt="image" src="https://user-images.githubusercontent.com/38000639/182994320-2a232fbb-e280-46da-9da8-66dabfd74815.png">

**Comment by boojack** [comment]
There should be a space after the tag, e.g. `#tag `
