### ISSUE TITLE
Show full content in the detail page

### ISSUE THREAD

**Issue by gera2ld** [usememos/memos#1373]
### Is your feature request related to a problem?

When open the detail page of a long memo, I'll see the full content first and then it's folded into a small card.

1. The flash of content is not a good UX.
2. It doesn't make sense to only show a small card since this is the detail page of the memo.

### Describe the solution you'd like

Just show the full content in the detail page.

### Additional context

![image](https://user-images.githubusercontent.com/3139113/226088278-c2f11c27-8ee2-40bf-bf3b-01c054629ec7.png)

**Comment by Kolucci69** [comment]
Hey guys I don’t know what to do can u splain so I can help because I am
lost “?
