### ISSUE TITLE
为什么要归档后才能删除, 能添加直接在首页删除记录吗?

### ISSUE THREAD

**Issue by yeli008** [usememos/memos#1376]
### Is your feature request related to a problem?

我希望直接能在首页删除记录而不是归档后删除, 请问是否有办法添加这个功能?

### Describe the solution you'd like

直接添加一个删除按钮,或者右上角三个点点开有删除选项

**Comment by Jonnyan404** [comment]
可以把归档理解为回收站,是为了方便误删恢复.

**Comment by winwangqi** [comment]
> 可以把归档理解为回收站,是为了方便误删恢复.

在删除的时候可以增加确认弹窗以防止误删。
删除的意思是我完全不需要了，需要永久消失。
归档的意思是我不需要关注了，不需要出现在我的关注列表里，但需要保留做存档，方便日后进行搜索。
回收站会提供一键清空和自动清空的功能，显然归档不应该包含这些功能。

A confirmation popup can be added to prevent accidental deletion at the time of deletion.
Deleted means I don't need it at all anymore and it needs to disappear permanently.
Archiving means I don't need to follow anymore, it doesn't need to appear in my follow list, but it needs to be kept as an archive for easy searching later.
Recycle Bin will provide one-click emptying and auto-emptying features, and obviously archiving should not include these features.

**Comment by lhuanyun** [comment]
以前我也觉得没必要归档，慢慢感觉，归档也是很好的功能，你可以认为归档就是永久删除了，加了后悔药。
别心理强迫，这是个好功能。文本记录器，不差一星半点存储。大文件，手动整理一下也没事。

**Comment by winwangqi** [comment]
> 以前我也觉得没必要归档，慢慢感觉，归档也是很好的功能，你可以认为归档就是永久删除了，加了后悔药。 别心理强迫，这是个好功能。文本记录器，不差一星半点存储。大文件，手动整理一下也没事。

存档功能是有价值的，或许我们还需要一个直接删除功能。
