### ISSUE TITLE
The path is error in docker

### ISSUE THREAD

**Issue by ljw98** [usememos/memos#139]
Path：/var/opt/memos
TAG：0.1.1 is OK
TAG：0.3.1 is Error(i cannt find SQLite db file in /var/opt/memos)

**Comment by boojack** [comment]
If you are upgrading from v0.1.x, you need to use the newest starting command. Please check the readme.

**Comment by Jonnyan404** [comment]
我是直接无法注册，注册就报400~~~

**Comment by Jonnyan404** [comment]
> * 部署方式：docker
> * memos版本：0.3.1
> 
> ### 问题现象
> 首次部署，我是直接无法注册，注册就报400~~~
> 
> 导致目前，我连界面都进不去。。。

问题已解决，原因是密码长度不够，但是提示不明确，误以为是跨域问题！！！！！！

**Comment by ljw98** [comment]
> Path：/var/opt/memos TAG：0.1.1 is OK TAG：0.3.1 is Error(i cannt find SQLite db file in /var/opt/memos)

已解决，安装时参数问题
