### ISSUE TITLE
提供历史memo随机阅读的功能

### ISSUE THREAD

**Issue by cdredfox** [usememos/memos#1396]
### Is your feature request related to a problem?

随着记录的时间越长，想法越来越多，有时候没有什么灵感的时候，想在以往记录的灵感中找一找灵感

### Describe the solution you'd like

希望能够提供随机看看几条过往memo的功能，方便有时候可以随机的回顾以往的想法，能够从中找到一些灵感，可能是以前随手记下来的想法。可以自已根据tag来圈定回顾的范围

**Comment by i-iooi-i** [comment]
支持，感觉这种类似OB笔记里的随机笔记功能，才更接近“探索”的功能。

**Comment by GreenHatHG** [comment]
简单实现：
https://github.com/orgs/usememos/discussions/974

**Comment by hillerliao** [comment]
https://github.com/hillerliao/random-memos  用简单的脚本从数据库里读取一条，推送到telegram。

**Comment by GreenHatHG** [comment]
你的邮件已收到！
