### ISSUE TITLE
When rename pictures in Resources, all exist notes with pictures referenced will be broken

### ISSUE THREAD

**Issue by hpsls** [usememos/memos#1399]
### Describe the bug

When rename pictures in Resources, all exist notes with pictures reference will be broken. Can be reproduced in LiveDemo.

### Steps to reproduce

1. publish a note with a picture
2. go to resources and change the name of that picture
3. return to main page, we find note like following:
<img width="294" alt="image" src="https://user-images.githubusercontent.com/12387736/226798934-0927b14a-4b97-40db-a2e6-5c7395f3eaf1.png">
4. reedit the note, just press resources in the bottom of editbox, we can find renamed picture associated with this note, click ok, the note will restore normal

**Comment by Zeng1998** [comment]
Where are your resources stored? database? local? Or S3?

**Comment by hpsls** [comment]
Just database, I recall there was an update of memos(0.12?) changed my storage config to local, so I change that back manually. At that time I read the source code of api and checked the response is correct, so maybe the bug may occur at the front end.
Now with the latest version, I can't reproduce the bug, so THX, I will close this issue.
