### ISSUE TITLE
【建议】编辑器中使用 ctrl v 快捷键粘贴剪贴板里的截图，会自动生成文件名为 image.png，能不能给文件名加上时间戳

### ISSUE THREAD

**Issue by geekyouth** [usememos/memos#1403]
### Is your feature request related to a problem?

编辑器中使用 ctrl v 快捷键粘贴剪贴板里的截图，会自动生成文件名为 image.png，能不能给文件名加上时间戳

### Describe the solution you'd like

能不能给文件名加上时间戳，否则资源浏览器中的文件名都一样

### Additional context

![image](https://user-images.githubusercontent.com/12899262/227103480-fe9d5b4f-55c6-4436-91e7-c5a94e7c0584.png)

**Comment by RotterL** [comment]
同意。不止是资源文件名都一样的问题，使用oss部署的时候会直接替换到之前的同名的文件，导致直接无法使用

**Comment by Zeng1998** [comment]
Please use the path template.
