### ISSUE TITLE
可否在 memo 的 ... 处添加个“复制链接”？

### ISSUE THREAD

**Issue by jetsung** [usememos/memos#1408]
### Is your feature request related to a problem?

是

### Describe the solution you'd like

希望在 `memo` 的 ... 处添加个“复制链接”
![image](https://user-images.githubusercontent.com/3362147/227546530-3b32805f-0f81-46e9-8c20-e705087e35f8.png)

因为当内容很长，比如代码分享时，需要滚动鼠标滚轮到下方才能找到“链接”，很不方便
![image](https://user-images.githubusercontent.com/3362147/227548340-76725071-c3ea-4b1e-8c47-fa9c9a3929d4.png)

**Comment by HappyZ** [comment]
Might be even simpler to move the bottom row to the top :P 

I like the idea to add copy link though to simplify user journey

**Comment by HappyZ** [comment]
I'll take it.

**Comment by HappyZ** [comment]
Updated 1.12.1 and noticed #1498 this change removed copy link in each memo, which basically rolls back the original CL. Can I learn a bit more why it's removed again?

**Comment by HappyZ** [comment]
@boojack

**Comment by boojack** [comment]
@HappyZ The main reason is to reduce the number of buttons, while the link is part of sharing, so it is put in the share dialog. Just like Twitter does.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/24653555/230803351-7a145ca4-f2a0-4c85-8049-dc079c0e6cc8.png">
