### ISSUE TITLE
Hyperlink is wrong when last character is period (.) to finish a sentence..

### ISSUE THREAD

**Issue by HappyZ** [usememos/memos#1409]
### Describe the bug

Try:  https://catfact.ninja/fact.

It will parse it as [https://catfact.ninja/fact.](https://catfact.ninja/fact.)

Instead of [https://catfact.ninja/fact](https://catfact.ninja/fact) with a period in the end.

### Steps to reproduce

See above.

**Comment by HappyZ** [comment]
I'm playing with link parsing in each memo for threading / preview. Got a better regex for plain link. But it looks like there will be an update on markdown overall. Will hold off any fix on this

**Comment by boojack** [comment]
Personally suggest adding a space after the link instead of `.`

**Comment by boojack** [comment]
Personally suggest adding a space after the link instead of `.`

**Comment by Zeng1998** [comment]
I don't think it's a bug, `https://catfact.ninja/fact.` is a valid url.
