### ISSUE TITLE
render.com auto deploy failed

### ISSUE THREAD

**Issue by geekyouth** [usememos/memos#1426]
### Describe the bug

feat: limit the num of lines for filename (#1424) * feat: limit the linenum of filename * change the implement of line-clamp

![image](https://user-images.githubusercontent.com/12899262/228862026-db886a45-09c0-474d-9bb3-b89966c29285.png)

feat: limit the num of lines for filename (#1424) · usememos/memos@3c2578f
https://github.com/usememos/memos/commit/3c2578f666b86b081a926bcb76124d954482be72

### Steps to reproduce

render.com auto deploy

**Comment by boojack** [comment]
Please try again with `Clear build cache & deploy`

<img width="374" alt="image" src="https://user-images.githubusercontent.com/24653555/228895224-2ec19647-17fc-4c38-84b7-ce9b3b531c14.png">
