### ISSUE TITLE
Delete memo enhancement

### ISSUE THREAD

**Issue by winwangqi** [usememos/memos#1430]
### Is your feature request related to a problem?

When I want to delete a memo, I have to archive it first, then navigate to the "Archived" page to delete the memo, then navigate to the "Resources" page to delete the memo related resources.

### Describe the solution you'd like

Add "Delete" option on the topRight menus, when I delete a memo, will delete the memo directly, and delete the memo related resources, unless the resources is used by other memos. (If a memo reference 3 resources, 2 resources is only used by current memo, 1 resource is also used by other memo, when I delete current memo, auto delete the 2 resources and reserve the by used resource).

Once the current feature is implemented, perhaps we can consider removing the "Resources" on the left menus, the user doesn't need to care about the Resources perspective.

**Comment by boojack** [comment]
As you wish

<img width="1170" alt="image" src="https://github.com/usememos/memos/assets/24653555/8d020017-406b-4dce-b8f3-bcf7e3ea5f95">
