### ISSUE TITLE
Popup editor when editing a memo

### ISSUE THREAD

**Issue by winwangqi** [usememos/memos#1431]
### Is your feature request related to a problem?

When I editing a memo, the page will scroll to top, when I complete the memo, I lost my scroll position, then I have to scroll to my previous memo manually.

### Describe the solution you'd like

I can edit a memo in a popup editor, when I complete edit, I can continue read without lost scroll position. This is also suitable for delete operations.

On top of that, when I scroll the page and the editor disappears, I expect a create new memo button to hover over the page,  when I click the create button, there are a popup editor on the page, it's same as edit popup editor, so I can quickly create a new memo without going back to the top of the page.

**Comment by boojack** [comment]
Done in the recently version.
