### ISSUE TITLE
GPT This model's maximum context length is 4097 tokens

### ISSUE THREAD

**Issue by voctot** [usememos/memos#1458]
### Is your feature request related to a problem?

> {code=500, message=Failed to post chat completion, internal={"code":"context_length_exceeded","message":"This model's maximum context length is 4097 tokens. However, you requested 4108 tokens (2108 in the messages, 2000 in the completion). Please reduce the length of the messages or completion.","param":"messages","type":"invalid_request_error"}

### Describe the solution you'd like

Is it possible to add a function to clean up records.

### Additional context

![image](https://user-images.githubusercontent.com/36097179/229467091-148dddd9-a0c1-4a94-8f5c-29587f1f332a.png)

**Comment by boojack** [comment]
Ask AI has been removed.
