### ISSUE TITLE
搜索时『加载更多』实现优化

### ISSUE THREAD

**Issue by Vespa314** [usememos/memos#1461]
在搜索某部分内容的时候，滚到最下面点击加载更多，有时候加载很多新的，有时候只有1条，有时候又完全没有加载任何新内容。

是因为每次加载都尝试在数据库里面检索N条，看N条里面有多少匹配到搜索条件么？

**Comment by i-iooi-i** [comment]
遇到了相同的问题，每次加载，数量好像都不同。

**Comment by kylehz** [comment]
因为关键词是在前端匹配的 不知道当初设计的人怎么想的
