### ISSUE TITLE
0.12.0 每日回顾重复请求 /api/memo?rowStatus=NORMAL&limit=20

### ISSUE THREAD

**Issue by Weibin74** [usememos/memos#1466]
### Describe the bug

![WX20230404-101308](https://user-images.githubusercontent.com/24431872/229668910-4ff0b3ff-e9eb-4535-9f15-9fdd2bb37a8b.png)

### Steps to reproduce

1. 选择每日回顾
2. 选择前一天
3. 前端开始无限制重复请求 
4. 刷新页面可以停止, 点击其他位置不能, 还会加剧请求频率

### Screenshots or additional context

docker 环境

**Comment by Weibin74** [comment]
> 

我在无扩展的情况也试过了, 还是同样的问题. 并且还发现一个现象, 在主页中筛选会重复请求的一天, 这里调用的接口有偏移量(`offset`)参数, 但是在每日回顾里只是重复请求. 是否为这个原因, 遗忘了偏移量的添加

![4_3_repeat](https://user-images.githubusercontent.com/24431872/230263685-cf89fc84-81ce-4fda-bbdc-cc7490775b79.png)

![4_3_offset](https://user-images.githubusercontent.com/24431872/230263677-e3496587-fa18-4c59-8842-e890524e1d0b.png)

**Comment by ychisbest** [comment]
相似的bug

**Comment by ychisbest** [comment]
应该是 memos/web/src/pages/DailyReview.tsx 中 useEffect 函数导致的，具体还不清楚怎么触发

**Comment by boojack** [comment]
Maybe fixed in the recent release. Feel free to open a new issue if it still existed.
