### ISSUE TITLE
Allow to disable version checking

### ISSUE THREAD

**Issue by honmaple** [usememos/memos#1469]
### Is your feature request related to a problem?

After upgrade to 0.12.0, I got 'Incorrect login credentials...' when I login to my memos, after I reset password by updating the `memos_prod.db` and login sucess, I found some resource can't show with error 
```
{
  "error": "code=500, message=Failed to find resource by ID: 17, internal=not found",
  "message": "Failed to find resource by ID: 17"
}
```
but this resource is existed from `select * from resource` 

Relead issue https://github.com/usememos/memos/issues/1462

### Describe the solution you'd like

Allow to disable version checking insead of fetch github tag info every refresh.

**Comment by kaizh102** [comment]
> ### Is your feature request related to a problem?
> After upgrade to 0.12.0, I got 'Incorrect login credentials...' when I login to my memos, after I reset password by updating the `memos_prod.db` and login sucess, I found some resource can't show with error
> 
> ```
> {
>   "error": "code=500, message=Failed to find resource by ID: 17, internal=not found",
>   "message": "Failed to find resource by ID: 17"
> }
> ```
> 
> but this resource is existed from `select * from resource`
> 
> Relead issue #1462
> 
> ### Describe the solution you'd like
> Allow to disable version checking insead of fetch github tag info every refresh.
> 
> ### Additional context
> _No response_

Could you please specify how did you update the memos_prod.db? I am having similar issue: after changing the docker-compose.yml file, I can no longer login  with the orignial email/passwd.

**Comment by honmaple** [comment]
@kaizh102 
```
└──╼ sqlite3 memos_prod.db
SQLite version 3.32.2 2021-07-12 15:00:17
Enter ".help" for usage hints.
sqlite> select * from user;
...
sqlite> update user set password_hash="$2a$14$ajq8Q7fbtFRQvXpdCq7Jcuy.Rx1h/L4J60Otx.gyNLbAYctGMJ9tK" where id=1;
sqlite> .quit
```
The password would be changed to **secret**，remember to backup memos_prod.db before making changes
