### ISSUE TITLE
手机页面 搜索 功能不能使用 BUG

### ISSUE THREAD

**Issue by QiTianQingShui** [usememos/memos#1483]
### Describe the bug

在手机页面点击搜索图标，第一次点击会闪现 右侧隐藏的内容，第二次点击没有反应。

### Steps to reproduce

1. 在手机浏览器 edge (Edge Version 110.0.1587.66) 上登录 memos 
2. 点击搜索

### Screenshots or additional context

https://user-images.githubusercontent.com/30709259/230344198-0a3ba078-79f8-4917-8e1b-989e09c7dc2a.mp4

**Comment by raiots** [comment]
same issue. happens on Android chrome browser. This bug starts from memos v0.11.2

**Comment by wanghuzhou** [comment]
you need to click the button twice，but it's clearly a bug

**Comment by boojack** [comment]
Maybe already fixed. Please check the demo site again.

**Comment by raiots** [comment]
> Maybe already fixed. Please check the demo site again.

thanks! The search button on demo site works good now, but it seems to appear a new bug, when the left panel shows up, i cannot type in search field. Just like the screenshot below.

https://user-images.githubusercontent.com/60507671/230749140-8ec8da0f-b59d-4e5c-955d-6d621cff5999.mp4

**Comment by boojack** [comment]
I'm on iOS safari and it's working fine. Could you provide the browser app and version? Or maybe you can try it on the latest Chrome?

**Comment by raiots** [comment]
> @raiots I'm on iOS safari and it's working fine. Could you provide the browser app and version? Or maybe you can try it on the latest Chrome?

Im using Chrome on MIUI 13, the chrome version is Chrome 112.0.5615.47, which is the latest version, and the System version is: Android 12; Mi 10 Build/SKQ1.211006.001.

This issue happens not only on chrome, but also on Quark browser and bing browser.

https://user-images.githubusercontent.com/60507671/230753718-fca9dd17-5327-4bc2-8830-fc0ebfb6b414.mp4

**Comment by boojack** [comment]
Sorry, my devices cannot reproduce this. Please help yourself.

**Comment by raiots** [comment]
> Sorry, my devices cannot reproduce this. Please help yourself.

Sure, thanks for helping.

**Comment by Mahoo12138** [comment]
In the Android Chromium browser, when the input method pops up, it will trigger the "resize" event, as shown in the following code:
If `window.innerWidth < resolution.md`, the Sidebar will be closed.
https://github.com/usememos/memos/blob/a9218ed5f007826942c972ea63b1dc473a8eb9b8/web/src/components/HomeSidebar.tsx#L15-L26

**Comment by Mahoo12138** [comment]
> In the Android Chromium browser, when the input method pops up, it will trigger the "resize" event, as shown in the following code: If `window.innerWidth < resolution.md`(certainly), the Sidebar will be closed.
> 
> https://github.com/usememos/memos/blob/a9218ed5f007826942c972ea63b1dc473a8eb9b8/web/src/components/HomeSidebar.tsx#L15-L26

Maybe add a `IsInputing` flag to help resize handler.
