### ISSUE TITLE
#tag 后面必须有个空格才能创建tag

### ISSUE THREAD

**Issue by ZhaoUncle** [usememos/memos#149]
今天尝试了下 memos 的 tag 功能，发现只有在“#tag_test ”后面多个空格，然后点击 save 才能创建 Tag。和换不换行好像没啥关系。不知道是功能设定还是什么原因，这里留个言探讨下。
<img width="789" alt="image" src="https://user-images.githubusercontent.com/31182637/185780336-49b68f0f-d618-414e-ade1-ea5876989c7b.png">

**Comment by boojack** [comment]
`tag` 是从所有 `memo` 中按照一定规则提取出来的，目前的规则是`#tag `（后面需要跟一个空格）
