### ISSUE TITLE
建议出中文使用文档

### ISSUE THREAD

**Issue by Cyiming** [usememos/memos#150]
想要项目有更广泛的发展 降低使用门槛 应该出个中文文档 讲下每个功能的作用

如api的使用

Shortcuts使用

可见性三种模式

资源库的使用

历次更新说明

……

**Comment by boojack** [comment]
已经在之后的 roadmap 中，目前还是先在代码层面上完善项目，之后再逐步更新相关文档。如果有问题的话可以加入 [tg 讨论群](https://t.me/+-_tNF1k70UU4ZTc9)。
