### ISSUE TITLE
Markdown 語法

### ISSUE THREAD

**Issue by kindomLee** [usememos/memos#151]
行內程式碼 "`" (反引號)，剛剛測試沒有生效

另外 Markdown 語法，如果在符號外空格會造成版面跑掉 

![image](https://user-images.githubusercontent.com/9668312/185820406-8131283e-9ac4-4eb1-b265-39dc83d4b7c2.png)

**Comment by jeechoul** [comment]
好像就支持一个： - 
其他的大多都没有效果
希望可以升级支持完整的MD语法
