### ISSUE TITLE
支持坚果云同步

### ISSUE THREAD

**Issue by 99fukong** [usememos/memos#1512]
### Is your feature request related to a problem?

我希望momes笔记能够同步到坚果云中特定的文件夹下面，这样当我logseq同步坚果云中的笔记时，memos的笔记也同步过来了

### Describe the solution you'd like

我希望momes笔记能够同步到坚果云中特定的文件夹下面，每个记录对用坚果云中一个文件，文件名采用日期格式

**Comment by 121592512** [comment]
楼主的问题解决了吗

**Comment by musnows** [comment]
备注：坚果云是一个支持webdav协议的云盘，所以只需要支持webdav同步即可
>offical website: https://www.jianguoyun.com/
