### ISSUE TITLE
Where is the option to allow collapsing memos?

### ISSUE THREAD

**Issue by sfan5** [usememos/memos#1513]
### Describe the bug

I wanted to report a minor visual bug regarding collapsed memos and wanted to test it on https://demo.usememos.com/ first.
However, I can't find the option to allow collapsing memos in user settings anymore.

### Steps to reproduce

1. Try to find the option to enable collapsed memos

### Screenshots or additional context

0.12.0 or 0.12.1

**Comment by sfan5** [comment]
Was this fixed? I am running v0.12.2 and still don't see the option.

**Comment by Zeng1998** [comment]
Wait for next release please. #1550
