### ISSUE TITLE
RSS - Memos is behind apache2

### ISSUE THREAD

**Issue by TaoChan1005** [usememos/memos#1514]
### Describe the bug

When I clik RSS, proxy error.

### Steps to reproduce

1. Clik RSS
2. go to new page https://<HOSTNAME>/u/2/rss.xml
3. Proxy error page.

### Screenshots or additional context

<img width="497" alt="image" src="https://user-images.githubusercontent.com/42793494/231011152-364691a0-8431-4bc3-b105-7b4a00c9ded6.png">

**Comment by boojack** [comment]
fixed in #1534
