### ISSUE TITLE
域名远程登录失败

### ISSUE THREAD

**Issue by jinfeng1985** [usememos/memos#1516]
### Describe the bug

使用 iOS 客户端登陆，使用域名，提示资源无法被加载，端口以放开，网页版无问题。

### Steps to reproduce

使用 iOS 客户端登陆，使用域名，提示资源无法被加载，端口以放开，网页版无问题。

**Comment by HaileYin** [comment]
遇到了同样的问题 请开发大佬 解决下

**Comment by kingcard1131** [comment]
the same issue i met also！！！

**Comment by chqcxd** [comment]
https ？

**Comment by d8349565** [comment]
the same issue i met also！！！

**Comment by Zeng1998** [comment]
https://github.com/mudkipme/MoeMemos

This is the repository for the iOS app.
