### ISSUE TITLE
关于搜索功能的建议

### ISSUE THREAD

**Issue by snipersteve** [usememos/memos#152]
目前版本的protect功能有意思，在某种程度上说可作为小团队笔记工具使用，即每个人各自写自己的笔记，适合团队内共享的就按protect处理，私人笔记则按private处理。

希望提供一个搜索全部成员protect、public笔记的功能，这样可以把团队知识效用最大化。

**Comment by lqwakeup** [comment]
SGTM，类似于语雀的「广场」页面
