### ISSUE TITLE
Tags shouldn't be case sensitive

### ISSUE THREAD

**Issue by iansoper** [usememos/memos#1522]
### Describe the bug

If I have two tags that have the same characters (but one is upper case and one is lower case), they show up as different tags in the sidebar. I would like for them to be one tag, not two.

### Steps to reproduce

1. Create two different memos, one tagged as `#Tag` and the other as `#tag`
2. Both tags will show up in the sidebar

Expected: One tag will be in the sidebar, ignoring the case.

**Comment by gitkeniwo** [comment]
> I've also noticed that tags also include punctuation, when they probably shouldn't. For instance, when you create a note like this: `#Today I'm at home. Feeling good #today, how are you feeling #today? #today`. I would expect all of those to be the **same tag**, but it makes 4 different tags: `#Today`, `#today,`, `#today?`, and `#today`

You could add an extra space to mark the end of a tag, like `#today ,`. Sometimes people may need punctuations in their tag. I don't think excluding the punctuations is the ideal solution.
