### ISSUE TITLE
Link preview

### ISSUE THREAD

**Issue by gitkeniwo** [usememos/memos#1528]
### Is your feature request related to a problem?

Many social apps have link preview feature, e.g. twitter, mastodon. After entering a link in a tweet, Twitter will automatically grab a preview for the link and render it as a card.

Since memos essentially aims to provide a twitter-like posting experience, I think it'd be nice to have this feature considering the urls nowadays tend to be long and ugly and markdown `[]()` does not entail picture previews, and it is convenient.

许多应用都有链接预览功能，例如Twitter、Mastodon。在推文中输入链接后，Twitter会自动抓取链接的预览，并将其呈现为卡片形式。

由于Memos本质上是模拟类似twitter的发布体验，考虑到现在的urls往往又长又丑，而且markdown的`[]()`很不显眼，所以有这个feature还是很有必要的。

### Describe the solution you'd like

Try rendering the first URL in the post as a preview card. It could be problematic when you have several links and I havent thought about it yet. Maybe just rendering the first one is okay.

**Comment by makidrone** [comment]
I would like this feature too

**Comment by wodepig** [comment]
I would like this feature too

**Comment by rodhfr** [comment]
Yeah, would like this feature too!

**Comment by HidemaruOwO** [comment]
me too

**Comment by MRobi1** [comment]
Would really love to see this feature implemented.

**Comment by Forceu** [comment]
Yes, it would be great to have this feature

**Comment by MehadND** [comment]
This [PR](https://github.com/usememos/memos/pull/2812) ok or not?

**Comment by MehadND** [comment]
@boojack I made a new PR related to this please have a look at it #3043
