### ISSUE TITLE
提供 Windows Server 的二进制的可执行文件

### ISSUE THREAD

**Issue by LittleArray** [usememos/memos#1540]
### Is your feature request related to a problem?

在Windows server 2012 r2中运行docker过于麻烦

### Describe the solution you'd like

提供一个适用于Windows的服务端二进制文件

**Comment by guanzi008** [comment]
这个我编译了一个单文件运行的Windows amd64和arm
以及Linux arm64和AMD64

**Comment by LittleArray** [comment]
> 这个我编译了一个单文件运行的Windows amd64和arm 以及Linux arm64和AMD64

能单独发我或者告诉我怎么编译吗
邮箱地址：3354889203@qq.com
mail:3354889203@qq.com

**Comment by LittleArray** [comment]
ok 解决了

**Comment by fff89** [comment]
> 这个我编译了一个单文件运行的Windows amd64和arm 以及Linux arm64和AMD64

同求，我win下编译失败了，一头雾水,

fengbju86@163.com

**Comment by guanzi008** [comment]
已解决测试编译单文件正常
