### ISSUE TITLE
Unexpected Application Error报错该怎么解决呢?

### ISSUE THREAD

**Issue by ben531** [usememos/memos#1547]
### Describe the bug

我把一个超长文本记录到mem中了, 然后就报了这个错:
Unexpected Application Error!
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded

而且, 我重启docker后仍然解决不了, 求教怎么办

### Steps to reproduce

1. 将超长文本贴到文本框, 
2. 点击记下.

**Comment by Zeng1998** [comment]
You can only delete this memo from the database.
