### ISSUE TITLE
rss.xml 新增 enclosure 字段

### ISSUE THREAD

**Issue by lmm214** [usememos/memos#1548]
### Is your feature request related to a problem?

目前 rss.xml 没有加入通过附件上传的图片或其它资源，所以订阅的话是无法显示的。

```
<item>
<title>#折腾 添加了一个机器人，解除频道消息在群组的置顶 [Telegram: Contact @areply_b...</title>
<link>http://me.edui.fun/m/1518</link>
<description>#折腾 添加了一个机器人，解除频道消息在群组的置顶 [Telegram: Contact @areply_bot](https://t.me/areply_bot) 群组里稍微顺眼了一些！🤷‍♂️</description>
<pubDate>Sun, 16 Apr 2023 14:19:02 +0000</pubDate>
</item>
```

### Describe the solution you'd like

<enclosure> 此项目相关的多媒体附件。属性url表示附件网址，属性length表示附件字节数，属性type表示附件的MIME类型。 

<enclosure url="http://www.bobopo.com/video/rss.mp3" length="16131450" type="audio/mpeg" />

建议加入 <enclosure> 字段。

**Comment by skyue** [comment]
rss不是html输出，也很影响阅读体验。

**Comment by Zeng1998** [comment]
#1559 .
