### ISSUE TITLE
Ask AI reports error 404

### ISSUE THREAD

**Issue by deveshXm** [usememos/memos#1549]
### Describe the bug

When I tried to ask "Ask AI" something it resulted in a popup that says "code=400, message=OpenAI API key not set"

### Steps to reproduce

- Install memos with docker
- sign in
- ask something in Ask AI

### Screenshots or additional context

![image](https://user-images.githubusercontent.com/80701176/232325751-48757856-4d9d-4d5c-b6d4-4f021c08dbfb.png)

**Comment by simplelifelfk** [comment]
In order for this to work, you have to have an API key for OpenAI (https://openai.com), and put that API key into Memos.  Without it...you won't get a connection to the chatbot.  Did you do this?

**Comment by deveshXm** [comment]
@simplelifelfk Ah! I see, I apologise for it, didn't knew about it. Could you please mention this in the documentation.
