### ISSUE TITLE
No frontend embeded.

### ISSUE THREAD

**Issue by SuperDPX** [usememos/memos#1551]
### Describe the bug

How to build a single file？

### Steps to reproduce

After I directly compiled it into a binary file, "No frontend embeded."was displayed all the time, so I ran "pnpm build" to generate a directory named "dist", and then packaged it again, but still could not solve the problem

**Comment by Zeng1998** [comment]
Did you build it following the Dockerfile? 
https://github.com/usememos/memos/blob/main/Dockerfile
