### ISSUE TITLE
是否可以同步到Obsidian中（或增加此功能）

### ISSUE THREAD

**Issue by ProteinPig** [usememos/memos#1558]
### Is your feature request related to a problem?

因为一些许可证可能性的限制，工作计算机不能安装Obsidian，所以在使用Docker创建的Memos，然后Web使用。
所以想问一下是否有可能，Memos收集，然后Obsidian汇总呢？

### Describe the solution you'd like

Memos作为碎片化的收集入口，Obsidian汇总管理

**Comment by zhaoscsc** [comment]
要是能够实现就太棒了

**Comment by i-iooi-i** [comment]
支持，同样需要这类功能。

**Comment by hyoban** [comment]
Check this demo, I will release this obsidian plugin soon.

https://github.com/usememos/memos/assets/38493346/c58d650d-520e-4108-af87-5cd1a89a6c28

**Comment by zhaoscsc** [comment]
> Check this demo, I will release this obsidian plugin soon.
> 
>  Screen.Recording.2023-05-14.at.1.24.41.PM.mov

期待。啥时候可以上架商店呢

**Comment by i-iooi-i** [comment]
> Check this demo, I will release this obsidian plugin soon.
> 
>  Screen.Recording.2023-05-14.at.1.24.41.PM.mov

酷哇大佬，求发布，求试用。😍

**Comment by hyoban** [comment]
@i-iooi-i @zhaoscsc I have created a PR at https://github.com/obsidianmd/obsidian-releases/pull/1955

**Comment by i-iooi-i** [comment]
> @i-iooi-i @zhaoscsc I have created a PR at [obsidianmd/obsidian-releases#1955](https://github.com/obsidianmd/obsidian-releases/pull/1955)

It's really great, thank you very much. 😘

**Comment by Zeng1998** [comment]
Thanks for your awesome work! @hyoban 
I'll close this issue and everyone can discuss in https://github.com/hyoban/obsidian-memos-plugin .

**Comment by quanru** [comment]
[Periodic PARA](https://github.com/quanru/obsidian-periodic-para#daily-record) 插件现在支持从 usememos 中拉取记录到日记中，不过目前只支持拉取文本：
> [Periodic PARA](https://github.com/quanru/obsidian-periodic-para#daily-record) plugin now supports pulling records from usememos into the diary, but currently only supports pulling text:

https://github.com/quanru/obsidian-periodic-para/assets/11739753/3d967527-b021-4a15-acd4-f5e6b0701a99
