### ISSUE TITLE
能否默认是展开？

### ISSUE THREAD

**Issue by wangweitung** [usememos/memos#1561]
### Is your feature request related to a problem?

![图片](https://user-images.githubusercontent.com/8080125/232645107-c3acff94-0f60-4a54-8cd1-dcea124071a2.png)

### Describe the solution you'd like

建议增加设置，默认展开。
自己可选择折叠。

**Comment by polyeung** [comment]
hello, 最新的merge里面加入了这个auto-collapse option 可以在preference里面关闭就所有的memos都可以取消折叠：  #1550

**Comment by wangweitung** [comment]
> hello, 最新的merge里面加入了这个auto-collapse option 可以在preference里面关闭就所有的memos都可以取消折叠： #1550

好的，感谢！
