### ISSUE TITLE
无法在本地开发

### ISSUE THREAD

**Issue by xyhcode** [usememos/memos#1564]
### Describe the bug

我在本地拉取项目，但是在执行`air -c scripts/.air.toml`时全部超时，我也开了代理

### Steps to reproduce

air -c scripts/.air.toml

### Screenshots or additional context

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/64968400/232788532-e99193b7-1b55-4da4-af69-4fa9d991750b.png">

**Comment by Zeng1998** [comment]
Please check your network. This is not a bug related to memos.

**Comment by wuxiao-ling197** [comment]
@xyhcode  hi ,did you resolve this problem? I tried go intall air many times but none of them successful ? if you were ok could you help me for a little while? Thank you.
