### ISSUE TITLE
ASK AI 聊天历史增多的情况下，继续聊天会报错

### ISSUE THREAD

**Issue by wangbaojie** [usememos/memos#1568]
### Describe the bug

当使用ask ai 每聊天一次都会传历史的聊天记录过去，这样就会导致token增多。大佬可以考虑做一个清楚按钮，当不需要上文的时候，做一个清除，清除掉前面的聊天信息，可以重新开始聊天。

### Steps to reproduce

在ask ai 中多次聊天

### Screenshots or additional context

code=500, message=Failed to post chat completion, internal={"code":"context_length_exceeded","message":"This model's maximum context length is 4097 tokens. However, you requested 4247 tokens (2247 in the messages, 2000 in the completion). Please reduce the length of the messages or completion.","param":"messages","type":"invalid_request_error"}

**Comment by wangbaojie** [comment]
您发的邮件我已经收到，您辛苦了！This is an automatic reply, confirming that your e-mail was received.Thank you这是一个自动回复，确认您的电子邮件收到了。

**Comment by ewader** [comment]
这个功能确实需要，不然就要清空浏览器缓存

**Comment by NoverNobida** [comment]
在不同浏览器历史记录是不能同步的，在新的客户端无法看到其他端的历史记录。
是否考虑新增特性：将单个或多个记录直接保存为一条memo，并添加ai的标签，和/或保存历史记录而建立新的会话。

**Comment by wangbaojie** [comment]
您发的邮件我已经收到，您辛苦了！This is an automatic reply, confirming that your e-mail was received.Thank you这是一个自动回复，确认您的电子邮件收到了。

**Comment by boojack** [comment]
Ask AI has been removed in the recent version.
