### ISSUE TITLE
[萌新]图片储存在哪里(哪个文件夹)了

### ISSUE THREAD

**Issue by Yuelioi** [usememos/memos#157]
使用的linux + 宝塔

配置项大概如下
ports:5230:5230
volumes:/www/wwwroot/memos.yuelili.com/  :  /var/opt/memos
command: --mode prod --port 5230
image: neosmemo/memos:latest

**Comment by Rookiewan** [comment]
看起来 图片 转 blob 存 DB 数据库了

**Comment by boojack** [comment]
可以参考：
https://github.com/usememos/memos/issues/153

最后应该是存在 /www/wwwroot/memos.yuelili.com/memo_prod.db 数据库文件里了

**Comment by Yuelioi** [comment]
谢谢大佬们 原来全在db文件里 那我就放心了

**Comment by NoverNobida** [comment]
但是我发现每个版本的更新都会有数据库结构变化，无法直接使用原来的数据库。所以实际上每次更新只能通过在网站导出json（只有纯文本），删除数据库，更新后重建数据库，重建账号，再导入json。

**Comment by Yuelioi** [comment]
> 但是我发现每个版本的更新都会有数据库结构变化，无法直接使用原来的数据库。所以实际上每次更新只能通过在网站导出json（只有纯文本），删除数据库，更新后重建数据库，重建账号，再导入json。

啊...在哪导出json啊 我没看到

**Comment by lqwakeup** [comment]
@NoverNobida 目前版本的命名规则采用的是[Semantic Version](https://semver.org/): `MAJOR.MINOR.PATCH`，数据库 schema 的变更只发生在 MINOR，并不是每次版本更新都会有。而且**从 `0.2.x` 开始，是可以直接升级的。**

**Comment by NoverNobida** [comment]
0.4.0版本以前在设置-偏好设置里面，0.4.0版本不知道为什么直接去掉了，现在0.4.0版本既不能读取0.3.x的数据库，提示`Failed to find userSettingList`，也不能导入了。。。

**Comment by boojack** [comment]
> 0.4.0版本以前在设置-偏好设置里面，0.4.0版本不知道为什么直接去掉了

之前的导入功能也只是为了方便测试，而且整个数据库文件都在用户那里，所以没必要再导入导出，这次就直接去掉了。

**Comment by boojack** [comment]
>现在0.4.0版本既不能读取0.3.x的数据库，提示`Failed to find userSettingList`，也不能导入了。。。

正常来说是可以直接无感升级的，可以先自行排查：通过一个数据库管理工具打开你的 .db 的数据文件，查看有没有一个表叫 user_setting，如果没有的话，可以拷贝下文件，再执行一下这个 patch 语句 https://raw.githubusercontent.com/usememos/memos/main/store/db/migration/prod/0.4/00__user_setting.sql

如果担心数据弄坏了，可以加入 tg 群私聊我

**Comment by NoverNobida** [comment]
@boojack 确实没有这个表，用语句加了这个表之后就没有报错了。但是我不知道为什么每次数据库有变动，都会报错，而不是在启动之前执行数据库结构更新。

**Comment by boojack** [comment]
@NoverNobida 代码上就是在启动服务前检查并执行数据库 schema 变更。
