### ISSUE TITLE
支持数据一键导出和导入

### ISSUE THREAD

**Issue by Naroncai** [usememos/memos#1573]
### Is your feature request related to a problem?

之前在本地部署了，数据都在电脑里。现在转到线上部署，想让数据同步过来

### Describe the solution you'd like

支持一键导出全部数据，然后也支持历史数据一键导入，这样方便备份和提取

**Comment by Wxinfeng** [comment]
How to implement data backup and data export.

**Comment by wayner6** [comment]
I need  it, too!

**Comment by gotname** [comment]
The function of importing and exporting this data is very important！！！！！！！！！！

**Comment by wayner6** [comment]
I hope you can support exporting data by cloud or webdav and syncing automatically, thanks 😍😍😍

**Comment by Zeng1998** [comment]
Discuss in #778 .
