### ISSUE TITLE
批量删除资源库功能不可用

### ISSUE THREAD

**Issue by Pauluooooo** [usememos/memos#1576]
### Describe the bug

web端，批量删除资源库功能和单个删除一样，都只会删除一个项目。

### Steps to reproduce

1. 点击资源库
2. 全选所有资源
3. 删除
4. 结果只有最后一个文件被删除。

**Comment by Pauluooooo** [comment]
并且希望能够在主页同样提供批量删除的功能。

**Comment by CorrectRoadH** [comment]
Already been fixed in https://github.com/usememos/memos/pull/1578 🥳
