### ISSUE TITLE
overload max size: 32MB

### ISSUE THREAD

**Issue by LittleArray** [usememos/memos#1577]
### Describe the bug

overload max size: 32MB

### Steps to reproduce

1. Go to "Resources"
2. Click “Add” icon
3. Upload File

### Screenshots or additional context

![image](https://user-images.githubusercontent.com/88972417/233374067-3aa97a4a-8959-4f97-a009-71c99ce3adbd.png)

**Comment by Jonnyan404** [comment]
一样问题

**Comment by Jonnyan404** [comment]
作为官方正式解决之前的补充方案,
基于 v0.12.2 版本,我修改了 32MB 限制到 320MB,并重新打包.

修改Docker命令中 `neosmemo/memos:latest` --> `jonnyan404/memos:latest` 即可.

**Comment by zjy2931** [comment]
have a config to set the size of file？
