### ISSUE TITLE
Bad performance with a lot of large images in the list

### ISSUE THREAD

**Issue by aisensiy** [usememos/memos#1579]
### Describe the bug

This is not a bug, this is a performance issue.

It seems that the default memos list will load the full size images.

### Steps to reproduce

1. Upload three or more images in a memo
2. Create the memo
3. Refresh the page

**Comment by sixmillions** [comment]
The file is saved to the sqlite database by default,
My practice is to store files in OSS
Good luck

**Comment by aisensiy** [comment]
Thanks for your reply. I checked my configs. Right now the file will saved as local file. But the performance is still not good enough. I will try the OSS way.

**Comment by Zeng1998** [comment]
The image thumbnail is supported now. 

#1641.
