### ISSUE TITLE
Delete tag

### ISSUE THREAD

**Issue by m1k3s0** [usememos/memos#1588]
### Is your feature request related to a problem?

Cannot delete stored tag after it's created

### Describe the solution you'd like

Sometimes tags are created in error. I would like the ability to either rename tags or delete them. Expected behavior would be for tag to be removed if no memos have the tag.

**Comment by gabstehr** [comment]
This feature is already here. Click on the right side on "Tag +" to show the tag cloud. Just click on a specific tag to delete it
