### ISSUE TITLE
Mobile interface

### ISSUE THREAD

**Issue by eallion** [usememos/memos#1594]
### Describe the bug

When clicking on the input box for the first time on a mobile device, the search box will automatically appear and cover the input box.

### Steps to reproduce

You can open the memos app on any mobile device.

### Screenshots or additional context

![Screenshot_2023-04-24-09-41-06-102_com android chrome](https://user-images.githubusercontent.com/1698841/233882035-264021f3-f6ee-40e6-a612-fd7f9b677ad6.jpg)

**Comment by CorrectRoadH** [comment]
which version are your memos? I can't reproduce it 👀

**Comment by eallion** [comment]
Latest, Android PWA.

**Comment by CorrectRoadH** [comment]
> Latest, Android PWA.

I reproduce it on my Android phone🤯 it is a hard-to-debug bug.
