### ISSUE TITLE
Files uploaded to local storage in memos can be accessed without authentication

### ISSUE THREAD

**Issue by eMUQI** [usememos/memos#1595]
### Describe the bug

Hi, developers.
I'm happy to see that memos has recently launched local storage feature.
However, I have noticed that the files uploaded to local storage can be accessed without authentication, simply by using the file's URL. Even private memos files. I am wondering if this is an intentional design or a bug in memos.

### Steps to reproduce

1. Login in
2. Create a private memos. Add file. Click "Create".
3. Upload a file.
4. Save the memos.
5. Copy the link of the file attach to the memos.
6. Open another browser that is not logged into memos and visit the previously mentioned link.

### Screenshots or additional context
version: v0.12.2

**Comment by athurg** [comment]
I'm going to deal with the problem

**Comment by athurg** [comment]
This issue was duplicated with #1361 , just closed here.
