### ISSUE TITLE
[Security Report] Registration

### ISSUE THREAD

**Issue by eallion** [usememos/memos#1596]
### Describe the bug

Someone registered an account in my memos, but I am sure that I have disabled the registration, and my password was also generated by Bitwarden.   
Today, I found a username called `ysjiang4869` in the backend, and it was definitely not registered by me.

### Steps to reproduce

n

**Comment by athurg** [comment]
Could you please check your *Memos* log, which contains *ysjiang4869* ?

**Comment by mnqazi** [comment]
It is possible to do this with my reported bug, #1619 
Fix it as soon as possible.

**Comment by eallion** [comment]
Logs deleted. Since I submitted the issue, more than 10 new users have registered. I have deleted all of them and reset the Memos. This is a very serious security issue.
