### ISSUE TITLE
Regression: S3 storage broken after upgrading to 0.12.2 from 0.12.1

### ISSUE THREAD

**Issue by HappyZ** [usememos/memos#1597]
### Describe the bug

Whenever I try to upload a file, it fails to upload saying there's issue with S3 storage. Downgrading to 0.12.1 worked fine. Using 0.12.2, I see the error and the response code is 405 which is odd. 

### Steps to reproduce

I configured MinIO without URL prefix or suffix in 0.12.1.

**Comment by boojack** [comment]
It looks like caused by https://github.com/usememos/memos/pull/1230. Have you solved this?
