### ISSUE TITLE
markdown语法支持建议

### ISSUE THREAD

**Issue by selfancy** [usememos/memos#1600]
## 1. 当前不支持二级引用
![image](https://user-images.githubusercontent.com/41697753/234464684-e935b8d1-7fb0-43e5-864a-e198adeb16b6.png)

## 2. 当前不支持表格
![image](https://user-images.githubusercontent.com/41697753/234464861-33cb49de-6a91-4221-93ab-4bf3cfa9579a.png)

## 3. 当前不支持mermaid语法，流程图等
![image](https://user-images.githubusercontent.com/41697753/234465038-bbd008f3-d582-43c2-9082-95b0d6b30c0c.png)

## 4. 当前不支持markdown编写预览

希望以上可以支持下😘

## 1. 二级引用效果
> 一级引用
>> 二级引用

## 2. 表格效果
First Header | Second Header | Third Header
--- | --- | ---
Content Cell | Content Cell | Content Cell
Content Cell | Content Cell | Content Cell

## 3. mermaid流程图效果
```mermaid
sequenceDiagram
participant Alice as A
participant Bob as B
Alice->John: Hello John, how are you?
John-->Alice: Great!
John->Bob: How about you?
Bob-->John: Jolly good!
```

**Comment by Zeng1998** [comment]
Do you really need to input these complex things ?

**Comment by selfancy** [comment]
@Zeng1998 The table is very useful

**Comment by ocean0117** [comment]
Maybe KaTeX can be added as well?
