### ISSUE TITLE
置顶状态的Memo编辑后接口返回值丢失置顶状态

### ISSUE THREAD

**Issue by Rabithua** [usememos/memos#1608]
## 实际请求API
<img width="360" alt="截屏2023-04-27 13 12 51" src="https://user-images.githubusercontent.com/34543831/234765244-b295cc4d-3808-41bf-86b1-7b95da03c986.png">

## 返回结果
<img width="589" alt="截屏2023-04-27 13 10 38" src="https://user-images.githubusercontent.com/34543831/234765097-a2714d9b-6ee2-4a20-adfe-676fd3509980.png">

**然而实际上这条Memo状态一直是置顶的**

### Steps to reproduce

如上图

**Comment by CorrectRoadH** [comment]
It has been fixed in #1629
