### ISSUE TITLE
Hope to support installation in casaOS

### ISSUE THREAD

**Issue by lowy** [usememos/memos#1611]
### Is your feature request related to a problem?

docker support installation in casaOS. but i don't install memos in casaOS.

### Describe the solution you'd like

I hope to provide a customized installation method in casaOS. Or add memos to casaOS appstore better.

**Comment by CorrectRoadH** [comment]
I submit a PR in [here](https://github.com/IceWhaleTech/CasaOS-AppStore/pull/37). wait for them to merge to the main branch.🥳

**Comment by CorrectRoadH** [comment]
🎉The PR has been merged! So we can install memos in casaOS😄
