### ISSUE TITLE
删除时报错Failed to delete memo ID: 5

### ISSUE THREAD

**Issue by RamSong** [usememos/memos#1624]
### Describe the bug

我在删除时发现点了删除没反应
我将其归档后删除
开始报Failed to delete memo ID: 5

### Steps to reproduce

1.编译安装memos.v0.12.2
2../memos -d ./da/ -m prod -p 5230
3.注册账号
4.发后删除
5.报错

### Screenshots or additional context

{
    "error": "code=500, message=Failed to delete memo ID: 5, internal=no such table: memo_relation",
    "message": "Failed to delete memo ID: 5"
}

**Comment by Zeng1998** [comment]
> internal=no such table: memo_relation

**Make sure you have migrated to the latest database schema.**

We strongly discourage compiling and running the code manually if you do not have sufficient development experience.
