### ISSUE TITLE
从资源库选中多图时的顺序问题

### ISSUE THREAD

**Issue by leslievan** [usememos/memos#1626]
### Is your feature request related to a problem?

1. 用户从资源库插入多张图片时按顺序逐个选中图片，但前端为无序列表，实际的显示顺序和用户选中的顺序无关。
2. 用户从本地上传多张图片到资源库/S3存储中时，按顺序逐个选中图片，在前端显示如下：
    <img width="355" alt="image" src="https://user-images.githubusercontent.com/19423232/235816773-7866595f-2ee7-4202-9ae7-62428c78b526.png">
    但上传后在资源库中显示的顺序同样是无序的
    <img width="590" alt="image" src="https://user-images.githubusercontent.com/19423232/235816864-783a94e0-51b6-47a6-bd09-067b09d7c066.png">

### Describe the solution you'd like

1. 希望在编辑 memo 从资源库插入多张图片时能够按照用户选中的顺序插入，像微信/QQ 选择多张图片时右下角会出现图片序号
2. 希望在上传图片时，上传后资源库的显示/排序结果，能够和前端选中的顺序一致

两个只要有一个能实现应该就能解决用户希望有序插入图片的需求。

**Comment by hyoban** [comment]
html input 标签拿到的上传文件列表就是不保证按用户顺序的。除了自定义上传组件，应该就是手动排序了
