### ISSUE TITLE
支持更多的 DB 类型

### ISSUE THREAD

**Issue by Allenxuxu** [usememos/memos#163]
感谢开源这么棒的作品，请问考虑支持更多的 db 类型吗？Mysql 或者 postgresql 等等。

**Comment by boojack** [comment]
SQLite 非常适合用在笔记类服务的私有化部署上，目前整个 memos docker image 才 11MB，非常轻量化。同时 SQLite 对于数据存储上也完全够用，不会迁移到 MySQL、PostgreSQL 等。

**Comment by Allenxuxu** [comment]
> SQLite 非常适合用在笔记类服务的私有化部署上，目前整个 memos docker image 才 11MB，非常轻量化。同时 SQLite 对于数据存储上也完全够用，不会迁移到 MySQL、PostgreSQL 等。

并非所有人都有服务器，支持了 MySQL、PostgreSQL 等，可以使用一些云数据库和 Serverless 厂商的免费额度服务部署🤔。

**Comment by boojack** [comment]
> 并非所有人都有服务器

同感，我就没有服务器，就一直在本地运行，还挺好用。

> 可以使用一些云数据库和 Serverless 厂商的免费额度服务部署

这样就会存在系统与元数据库分开的问题，整个系统的响应速度就会变慢许多。所以如果想要好的体验，稍微花点钱买个服务器可能会是更好的解法。

**Comment by Allenxuxu** [comment]
> > 并非所有人都有服务器
> 
> 同感，我就没有服务器，就一直在本地运行，还挺好用。
> 
> > 可以使用一些云数据库和 Serverless 厂商的免费额度服务部署
> 
> 这样就会存在系统与元数据库分开的问题，整个系统的响应速度就会变慢许多。所以如果想要好的体验，稍微花点钱买个服务器可能会是更好的解法。

我个人的场景就是相用它的 open api 来输入东西，比如浏览器插件收藏一些文字或者链接之类，或者命令做个小工具从命令行输入之类的。本地跑的话，不能多设备了。
而且本身这个项目是支持多账号的，要想朋友间共享就得云端部署。
还是要支持一下其他数据库比较好，可以使用 gorm 之类的 orm 框架，这样会省事很多。

**Comment by leeyaunlong** [comment]
附件 能不能直接存文件方式, 存几个大图sqlite膨胀太快. 删除后, 还要做收缩.
