### ISSUE TITLE
手机端显示无法换行超出屏幕

### ISSUE THREAD

**Issue by xxzj990** [usememos/memos#1633]
### Describe the bug

使用下面一段文本新建一条记录显示会超出屏幕，导致所有记录都显示不正常

\```
/var/lib/flatpak/exports/bin/org.libretro.RetroArch
\```

### Steps to reproduce

1、新建记录
2、填入如下文本
\```
/var/lib/flatpak/exports/bin/org.libretro.RetroArch
\```
3、需要标记为代码（添加 \``` 内容 \```）
4、查看显示

### Screenshots or additional context

截图：
![微信图片_20230504155251](https://user-images.githubusercontent.com/5134154/236143244-4fcbfafe-c4ed-4ec1-a9db-6237d694eef0.jpg)

**Comment by xxzj990** [comment]
目前只发现这种带有路径的特殊文本标记为代码时有这个问题

**Comment by Zeng1998** [comment]
Which system? which version? and which browser?

I cannot reproduce that.

**Comment by xxzj990** [comment]
> 

memos version:0.12.2
system version:iOS 15.4.1
browser:Safari

**Comment by xxzj990** [comment]
此问题在0.13.1测试已经有所改善，不影响使用了。

如图，虽然还会超出去，但是可以拖动，超出去的部分不是很多，基本不影响使用了。

![9f603521f14b89a2de53fb9dfb33aee](https://github.com/usememos/memos/assets/5134154/18f36a9a-b800-4a22-afff-da4ef12eefd1)
