### ISSUE TITLE
取消选中[标签]出错

### ISSUE THREAD

**Issue by junweiin** [usememos/memos#1637]
### Describe the bug

取消 **标签** 后，加载全部数据。

### Steps to reproduce

1. 过滤器 取消标签
2. 页面加载反应变慢
3. 加载全部的数据，没有等待加载的状态了，没有 **点击此处获取更多**的按钮。 
4. 不在过滤器取消标签选择，直接刷新页面的话，正常。底部出现 **点击此处获取更多**的按钮。

注：自行在数据库中添加了数据。

### Screenshots or additional context

![过滤器中选中](https://www.junwei.ml/i/i/2023/05/06/3yyi8i.png)
![刷新后，正常，出现点击此处获取更多](https://www.junwei.ml/i/i/2023/05/06/41i1rj.png)

**Comment by CorrectRoadH** [comment]
👀你的意思是说选中一个标签之后，再取消会导致把所有的memos都加载出来，然后这样会很慢是吗?
