### ISSUE TITLE
iFrame中包含memos页面，登录时报Missing access token

### ISSUE THREAD

**Issue by ccxuy** [usememos/memos#1642]
### Describe the bug

iFrame中包含memos页面，登录时报Missing access token

### Steps to reproduce

1. 在Organizr中以ifram方式包含memos页面
2. 登录
3. 报Missing access token错误

**Comment by SurvivaLlama** [comment]
same. trying to log in using android app. correct https:// address and username / password, but only getting "Missing access token"

**Comment by boojack** [comment]
The memos and container website should been served in https.

* https://stackoverflow.com/questions/51151183/cookie-not-being-set-in-iframe
