### ISSUE TITLE
Authentik OAuth2 issue

### ISSUE THREAD

**Issue by Typhonragewind** [usememos/memos#1643]
### Describe the bug

When i try to configure OAuth2 (using custom template) using Authentik as the provider, i get the following error:

{
  "error": "code=500, message=Failed to get user info, internal=failed to unmarshal response body: unexpected end of JSON input",
  "message": "Failed to get user info"
}

My configs are like this:
![image](https://user-images.githubusercontent.com/7875917/236860524-06067f93-e620-459e-9b5e-94f16efab4eb.png)

I use Authentik OAuth2 with other services, so far it's just memos that does not like it :swe

### Steps to reproduce

1. Configure Memos SS with Authentik OAuth2 endpoints
2.  Try to login

**Comment by bugmaschine** [comment]
I have the same issue

**Comment by phutur1st** [comment]
try adding username to user scopes

**Comment by Typhonragewind** [comment]
> try adding username to the scopes
> 
> openid email profile username

I did actually get it work now, without using the username as a scope. I changed nothing in the settings, but tried in a different computer (instead of my laptop9 when i got home. It might have been some leftover cache that was messing stuff up

**Comment by Jab2870** [comment]
Sorry to comment on an old issue, but I am also experiencing this. Cleared all my caches, and added username to the scopes but still getting it.
