### ISSUE TITLE
 Disable sign up per oauth source

### ISSUE THREAD

**Issue by Shuenhoy** [usememos/memos#1652]
### Is your feature request related to a problem?

In #1620, new users from Oauth are also rejected if sign-up is disabled. However, the other way should also be useful, e.g. when you are running a private Gitea instance, and want to allow any user there to also be able to use memos.

### Describe the solution you'd like

I propose to enable/disable sign-up separately for each auth source, the current option then only disables sign-up from the form.

**Comment by Shuenhoy** [comment]
> You can fill the identifier filter in SSO setting. It will only allow those user who passes the filter checks. https://github.com/usememos/memos/blob/main/server/auth.go#L88
> 
> <img alt="image" width="769" src="https://user-images.githubusercontent.com/24653555/239245531-ecef4203-203c-4fde-82a9-9eae38947b75.png">

Thanks for your reply!

I think I need to clarify: I want to prevent anyone to register an account with the built-in register form, but allow new users from SSO sources, not about preventing certain users from an SSO source. In the current release version 0.12.2, this is possible, but after #1620, this seems to be impossible. Or maybe I misunderstood something about #1620 and there is nothing to worry about?

**Comment by boojack** [comment]
Removed the `disable sign up in UI` check for SSO https://github.com/usememos/memos/pull/1684

**Comment by bestrocker221** [comment]
I noticed that an SSO user sign up works only if the general "Allow user signup" is enabled. This allows also normal user (non-sso) to sign up.
How to allow *only* SSO user to sign up?

**Comment by looksimplers** [comment]
Need the feature only sso user to sign up too.
