### ISSUE TITLE
本地存储预设值未生效

### ISSUE THREAD

**Issue by Jonnyan404** [usememos/memos#1661]
### Describe the bug

https://github.com/usememos/memos/commit/bdc00d67b2ff774b0654a461086f304af2b58137

这个commit实际并未生效

### Steps to reproduce

1. 部署 0.12.2 版本memos以及当前(2023年05月15日)test版本,
2. 设置为存储为本地存储
3. 随意上传2张图片,即可复现

**Comment by Zeng1998** [comment]
#1665 .
