### ISSUE TITLE
安卓pwa模式下,每次打开首次点击输入框,搜索页面就会弹出

### ISSUE THREAD

**Issue by Jonnyan404** [usememos/memos#1667]
### Describe the bug

- 设备: Android
- 浏览器: chrome
- memos版本: 当前日期test镜像 

安卓pwa模式下,每次打开首次点击输入框,搜索页面就会弹出,很烦人

### Steps to reproduce

1. 打开memos的pwa页面
2. 点击输入框准备输入内容
3. 右侧就会弹出本应该是搜索按钮才触发的页面

**Comment by Zeng1998** [comment]
#1594 .
