### ISSUE TITLE
Regarding how to edit a memo

### ISSUE THREAD

**Issue by ximing** [usememos/memos#1671]
### Is your feature request related to a problem?

NO

### Describe the solution you'd like

I recently encountered an issue while using the memos. 
When editing an existing memo, it jumps back to the top of the editor, disrupting the scrolling position. I would like to know the reason behind this design and why the viewed memo is not directly transformed into an editable state. If it was implemented this way to quickly achieve the prototype functionality, I can provide a relevant pull request to enhance this feature.

**Comment by Zeng1998** [comment]
Indeed, it's terrible when you scroll down and then double-click to edit a memo.

**Comment by gitkeniwo** [comment]
How about making it an option for the editing box being able to stick to the top while scrolling? Like V2EX

**Comment by boojack** [comment]
> When editing an existing memo, it jumps back to the top of the editor, disrupting the scrolling position.

Now the editor will now be displayed as a pop-up dialog.
