### ISSUE TITLE
系统设置里面 自定义样式 有断行bug

### ISSUE THREAD

**Issue by dianso** [usememos/memos#1675]
### Is your feature request related to a problem?

系统设置里面 自定义样式 有断行bug

比如我要隐藏探索

//隐藏探索
#header-explore{visibility:hidden;height:0;margin:0;padding:0}

保存后生效，下次我增加其他功能，比如给热力图换个颜色，我打开自定义样式这个界面，发现以前填写的#header-explore{visibility:hidden;height:0;margin:0;padding:0}中间有换行符号，导致保存后失效，必须手动再修改一次。
方便。
能不能增加多个自定义样式，每个样式可以填写一次代码保存，下次新增删减

### Describe the solution you'd like

如上

### Additional context

如上

**Comment by Zeng1998** [comment]
I can't reproduce it.
