### ISSUE TITLE
升级v0.13.0后无法显示图片缩略图

### ISSUE THREAD

**Issue by rieds** [usememos/memos#1686]
### Describe the bug

缩略图加载失败，但是点开图片能看到原图。 存储切换到数据库或本地都不行。
有报错
error
: 
"code=500, message=Failed to resize thumbnail image: /var/opt/memos/.thumbnail_cache/249b38a8-49d4-407c-8548-e78fb4456d60.png, internal=open /var/opt/memos/.thumbnail_cache/249b38a8-49d4-407c-8548-e78fb4456d60.png: no such file or directory"
message
: 
"Failed to resize thumbnail image: /var/opt/memos/.thumbnail_cache/249b38a8-49d4-407c-8548-e78fb4456d60.png"

### Steps to reproduce

1. 随意上传一张图片
2. 刷新查看
3. 缩略图显示失败
4. 点击失败图标能查看到原图

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/86068459/8e8104c8-0dce-4327-8f2f-b3dd29bc00b7)
![image](https://github.com/usememos/memos/assets/86068459/da1865da-6268-44eb-9d95-da278f36d6a9)

**Comment by lechengyu** [comment]
升级v0.13.0后，网页端遇到同样问题。

**Comment by tufeiping** [comment]
![image](https://github.com/usememos/memos/assets/7630984/c6f69808-0848-486a-ba19-4e37121be29a)

这里处理有点瑕疵，建议在`decode`失败的情况，且类型确定为`image/jpg`或`image/png`的情况下，可以直接复制`blob`数据到`.thumbnail_cach`目录下，也采用`public_id`同名，至少确保 **blog** 条目显示正常！

我手工处理了自己的博客，这种方案虽然不是最好的，但至少博客算是显示正常了！
