### ISSUE TITLE
Strikethrough in header

### ISSUE THREAD

**Issue by noxonad** [usememos/memos#1688]
### Describe the bug

Markdown strikethrough isn't working in headers

### Steps to reproduce

1. Type: `# ~~Some Text~~`
2. Expected result:

# ~~Some Text~~

4. Actual result:
# \~\~Some Text~~

**Comment by TejsinghDhaosriya** [comment]
Can I pick this one @noxonad  if not fixed yet ? assign to me

**Comment by noxonad** [comment]
As far as I can see, it's still valid. You're free to fork this repo and push your fix when it's done for a review. Also, it'll be easier for the dev team to view what your push is about if you mention the issue number.
