### ISSUE TITLE
Hide Checked Items

### ISSUE THREAD

**Issue by Froghut** [usememos/memos#1689]
### Is your feature request related to a problem?

I would like to use this as an alternative to Google Keep, but the one feature that is missing for me is the ability to hide checked items which is really useful when using a memo as a shopping list.

### Describe the solution you'd like

As stated, add an option to hide checked items.

**Comment by Zeng1998** [comment]
Hey, what do you mean about "hide"? Can you show me a example? 

I guess it can be solved by additional css.

**Comment by Froghut** [comment]
Here as an example how Google Keep does it - but I don't care about the actual implementation, i.e. moving checked items to the bottom, just hiding them completely, as long as there is a way to only see items that are not yet checked.
![20230521_125056](https://github.com/usememos/memos/assets/1702171/03526f36-3147-42a4-ae07-e61a1e52f7da)

**Comment by Zeng1998** [comment]
```css
.todo-block.done{color:#c8c6c4;}
.todo-block.done+span{text-decoration:line-through;color:#c8c6c4;}
```

![image](https://github.com/usememos/memos/assets/31177490/adf0d2a6-cbaa-410c-b00f-2234c2503d6e)

Hey @Froghut, perhaps this additional CSS can help you in some way. However, it is worth noting that currently we do not sort the todo items, i.e. moving the completed items to the bottom as shown in the above image.

This may be an interesting idea, but I am not sure if it will be implemented.

**Comment by wsw70** [comment]
I rely heavily on TODOs and seeing the completed ones together with the missing ones is a bit disturbing (the done ones are actually more visible).
Would there be a chance to revive this, or at least sort the TODOs so that there is a clear separation between them?
