### ISSUE TITLE
markdown语法支持的不是太好

### ISSUE THREAD

**Issue by Rotel11** [usememos/memos#169]
好多markdown语法都不支持，比如引用，标题，好多都无法实现，希望大佬支持，还有能有个别的颜色的背景和主题

**Comment by boojack** [comment]
不会完全支持 markdown，目前支持了部分常用的语法：加粗、斜体、列表、代码块、链接等。

毕竟 memos 不是来写文章的，所以不会去支持标题的语法，不过可以加一个引用。

**Comment by boojack** [comment]
Related issue: #151
