### ISSUE TITLE
[Feature request] Add config options (file or ENV) to be able to configure the app without the web UI

### ISSUE THREAD

**Issue by Byh0ki** [usememos/memos#1690]
### Is your feature request related to a problem?

Hello,

First of all, thank you for this nice app!

I'm wondering if it would be possible to add an option to configure the app using a config file or ENV vars? I'm deploying the app using Infra as Code tooling and it would be very convenient to be able to define the app name, SSO config, storage config, etc using templatable options.

### Describe the solution you'd like

The config could be loaded either from a config file by enabling it using an argument (ex: `--config-file=/memos.conf`) or using the ENV for some option like secrets (ex: `SSO_CLIENT_SECRET=my_super_seret`).

**Comment by athurg** [comment]
Currently `Memos` not support config System Setting in ENV or config file.

There is a walk around to IaaS or SaaS, which is inject a pre-defined memo db file by default.

For example, you can run a fresh `Memos` from local, and config all options in the UI. After all, you can save the db file as a feed in your new instance.

**Comment by Byh0ki** [comment]
It's not very convenient, I think I'll stay with the manual way for now.

Do you plan to add the feature one day?
