### ISSUE TITLE
After updating to version 0.13.0, the media file thumbnail attached to the post will not be displayed.

### ISSUE THREAD

**Issue by gitous** [usememos/memos#1692]
### Describe the bug

更新到0.13.0版本后，发文附带的媒体文件缩略图不显示，点击可以看大图，资源库中也不显示
After updating to version 0.13.0, the media file thumbnail attached to the post will not be displayed. Click to see a larger image, and it will not be displayed in the resource library

![屏幕截图 2023-05-21 073431](https://github.com/usememos/memos/assets/32594402/338d155e-f43a-4eac-9865-ffd62288ec71)
![屏幕截图 2023-05-21 073451](https://github.com/usememos/memos/assets/32594402/cf711c2b-f573-4f4a-8588-b8570ed6dc32)

### Steps to reproduce

群晖docker中部署，原本12.2版本无异常。
watchcat自动升级至0.13.0后缩略图不显示

Deployed in Synology DSM Docker, there were no abnormalities in the original version 0.12.2.
When watchcat automatically upgrades to 0.13.0 ,thumbnails doesn't displayed

**Comment by Zeng1998** [comment]
Pull the latest image again.

**Comment by heronaly** [comment]
我也是同一个问题啊

**Comment by gitous** [comment]
> 我也是同一个问题啊

拉最新的镜像就好了

Pull the latest image as Zeng1998 said
