### ISSUE TITLE
Editing shortcut with display time filter resets date when editing

### ISSUE THREAD

**Issue by adamshand** [usememos/memos#1698]
### Describe the bug

When editing a shortcut with a display time filter, the displayed date is set to today, regardless of what the actual date for the filter is.

### Steps to reproduce

1. Create a shortcut with a display time filter 
2. Edit the shortcut
3. In the edit widget, the display time will be shown as the time you edited the shortcut (instead of the time that it is actually set to).

**Comment by boojack** [comment]
Shortcuts have been removed in the recent release.
