### ISSUE TITLE
Hide Ask AI

### ISSUE THREAD

**Issue by egs2003** [usememos/memos#1702]
### Is your feature request related to a problem?

I would like to see ask ai hidden if you don't want to use it. Either through a switch in the settings or if the API key is not specified.

### Describe the solution you'd like

I would like to see ask ai hidden if you don't want to use it. Either through a switch in the settings or if the API key is not specified.

**Comment by Zeng1998** [comment]
use the additional css.

```css
#header-ask-ai {
  display: none;
}
```

**Comment by jxpsert** [comment]
> use the additional css.
> 
> ```css
> #header-ask-ai {
>   display: none;
> }
> ```

That's a nice workaround, yes. A toggle would be most appreciated, though.

**Comment by Zeng1998** [comment]
> > use the additional css.
> > ```css
> > #header-ask-ai {
> >   display: none;
> > }
> > ```
> 
> That's a nice workaround, yes. A toggle would be most appreciated, though.

I agree but the change might not be trivial.

You can see this PR. https://github.com/usememos/memos/pull/1539#issuecomment-1510027883
