### ISSUE TITLE
A Markdown preview would be nice

### ISSUE THREAD

**Issue by egs2003** [usememos/memos#1703]
### Is your feature request related to a problem?

A Markdown preview would be nice

### Describe the solution you'd like

A Markdown preview would be nice

**Comment by diomed** [comment]
agreed. 

all that free space on the right side seems like ideal for preview

**Comment by ty114514** [comment]
Maybe we just need use ByteMD, that can support preview and full markdown syntax

**Comment by boojack** [comment]
<img width="325" alt="image" src="https://github.com/usememos/memos/assets/24653555/53ffdf27-9530-4b12-acf1-4dcf005c2cbd">
