### ISSUE TITLE
反向代理绑定域名无法访问

### ISSUE THREAD

**Issue by absir1949** [usememos/memos#1712]
### Describe the bug

安装使用默认，docker 建立5230:5230。

之后使用IP+端口，可直接访问。

但是添加反代(SSL)后，访问主页，图标会加载出来，但是页面无法访问
<img width="598" alt="image" src="https://github.com/usememos/memos/assets/14873265/7a35d319-69a1-4d8f-b65a-adbdd970c0f6">

<img width="633" alt="image" src="https://github.com/usememos/memos/assets/14873265/fc44176a-68e9-47cd-af4f-6566f2534303">

### Steps to reproduce

1.安装
> docker run -d --name memos -p 5230:5230 -v ~/.memos/:/var/opt/memos neosmemo/memos:latest
2.使用域名+端口，访问正常
3.添加反向代理，访问页面加载异常

**Comment by GodMeowIceSun** [comment]
能发下详细的
nginx.conf
或者
conf.d/xxx.conf文件内容看下么

**Comment by absir1949** [comment]
反向代理的配置如下
@GodMeowIceSun 

```
location /
{
    proxy_pass http://127.0.0.1:5230;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_http_version 1.1;
    # proxy_hide_header Upgrade;

    add_header X-Cache $upstream_cache_status;

    #Set Nginx Cache


    set $static_fileOrJjXx5G 0;
    if ( $uri ~* "\.(gif|png|jpg|css|js|woff|woff2)$" )
    {
    	set $static_fileOrJjXx5G 1;
    	expires 1m;
        }
    if ( $static_fileOrJjXx5G = 0 )
    {
    add_header Cache-Control no-cache;
    }
}

#PROXY-END/
```

**Comment by athurg** [comment]
@absir1949 你截图完美的把错误信息楼掉了。

**Comment by absir1949** [comment]
<img width="1011" alt="image" src="https://github.com/usememos/memos/assets/14873265/564debf1-6aa0-4507-be98-ead9143b3b9b">
@athurg  是这个错误

**Comment by GodMeowIceSun** [comment]
建议把nginx配置 server那层的也给出，我怀疑是HTTP/2相关支持的问题，尝试将 
```
listen 443 ssl http2; 
```

中的 http2 去掉试试

**Comment by boojack** [comment]
> 2. 使用域名+端口，访问正常
> 3. 添加反向代理，访问页面加载异常

无法访问和 memos 无关，请检查你的 nginx 配置。
