### ISSUE TITLE
修改时间问题

### ISSUE THREAD

**Issue by flyklmwl** [usememos/memos#1714]
### Is your feature request related to a problem?

您好，之前的版本可以点击时间区域弹出一个datepick 来修改时间，现在没有了。 请问新版本(0.13.0)是不支持修改创建时间了么？

### Describe the solution you'd like

期望还是能修改创建时间，时间线和每日回顾对于单人用户 用得还是挺多的

**Comment by athurg** [comment]
Use `Alt` + `Click` to modify time of an exists memos.

**Comment by flyklmwl** [comment]
哦哦，试了一下，确实可以修改，感谢感谢

**Comment by relines** [comment]
希望能修改分钟和秒钟，现在只能修改30分钟，颗粒度太粗糙了
