### ISSUE TITLE
URLs with # data in them are treated as tags

### ISSUE THREAD

**Issue by buggithubs** [usememos/memos#1715]
### Describe the bug

https://github.com/usememos/memos/blob/3b1bab651a525faaf8baa0fb8cd0374ed7ef8305/server/tag_test.go#L37
This is a link that `http://123123.com?123123#tag2`
should not get `#tag2` as a tag

### Steps to reproduce

go to describe

**Comment by gitous** [comment]
also in code mode
```
save a password in this aera like 123456#123456
```

**Comment by boojack** [comment]
We are implementing a markdown parser in go that will solve this problem effectively. Feel free to contribute code if you are interested! https://github.com/usememos/memos/tree/main/plugin/gomark

**Comment by jon-f-novastor** [comment]
Even if create a new note with a plain text single line text entry like this, it will show the issue with tagging that note, even though you have a space character between the # and the P:

Amazon Reference ID # P05-4145350-0458458

**Comment by s0urcelab** [comment]
> We are implementing a markdown parser in go that will solve this problem effectively. Feel free to contribute code if you are interested! https://github.com/usememos/memos/tree/main/plugin/gomark

So is there a plan to migrate all the markdown parse from frontend to backend?
PS: Why implementing markdown parser by yourself not using some 3rd library?

**Comment by boojack** [comment]
Maybe fixed in the recent releases.

<img width="879" alt="image" src="https://github.com/usememos/memos/assets/24653555/29feec65-c5c5-4056-a9d9-4e51fb1b6996">
