### ISSUE TITLE
FR: 把模板文件夹分离出来，方便用户定制/开发全新的主题。

### ISSUE THREAD

**Issue by skyue** [usememos/memos#1720]
### Is your feature request related to a problem?

虽然在设置中能增加css和js，但依然太受限了。建议把模板完全分离出来。
（技术小白，不确定是不是Go的限制，如果是请忽略这条FR）

### Describe the solution you'd like

no

**Comment by athurg** [comment]
Golang并没有这个限制。但是现在前端页面整体是和React揉在一起的，并不是你想要的那种「后端➕HTML模板」的结构。

换句话说，本来就没有「主题」机制。

但是因为页面本身比较简单，所以基本上CSS定制也能解决大多数需求了。如果有更高级的想法，比如要调整页面布局什么的。可能带来的改变就太大了
