### ISSUE TITLE
連接超時

### ISSUE THREAD

**Issue by imaletion** [usememos/memos#1721]
### Describe the bug

不知道為什麼就突然連接超時了 
但其他的服務沒有超時 
只有memos

### Steps to reproduce

第一步
輸入ip:5230
第二步
打不開
第三步
開代理 依舊打不開

**Comment by boojack** [comment]
Could you provide some detail error messages?

**Comment by imaletion** [comment]
The status of docker is exited
I don't know how it became like this
Then delete and reinstall and still have the original data

**Comment by boojack** [comment]
@imaletion So did you solve this problem?

**Comment by imaletion** [comment]
Yes,i did. But I don't know how it happened and next time what should I do ?

**Comment by Zeng1998** [comment]
God knows.

**Comment by athurg** [comment]
Maybe it because the container was exit by OOM while generate image thumbnail. You can just check the status or logs of the dead container.
