### ISSUE TITLE
The preview images before April are all displayed the same.(2023年4月之前的图片预览图展示全部一样)

### ISSUE THREAD

**Issue by Jonnyan404** [usememos/memos#1734]
### Describe the bug

The preview images before April are all displayed the same

### Steps to reproduce

You can view the pictures before April.

**Comment by Jonnyan404** [comment]
Because the UUID was only added on April 3rd, the UUID values before this date are the same, resulting in the same preview image being parsed.

https://github.com/usememos/memos/commit/1cab30f32f737844090240434defdd834b01ea74

**Comment by boojack** [comment]
Execute the following SQL into your database or wait next release.

```sql
UPDATE
  resource
SET
  public_id = printf (
    '%s-%s-%s-%s-%s',
    lower(hex(randomblob(4))),
    lower(hex(randomblob(2))),
    lower(hex(randomblob(2))),
    lower(hex(randomblob(2))),
    lower(hex(randomblob(6)))
  );
```
