### ISSUE TITLE
我想在群晖内安装2个memos

### ISSUE THREAD

**Issue by jeechoul** [usememos/memos#1735]
### Is your feature request related to a problem?

我想在群晖内安装2个memos，请问该如何操作，容器的端口5230只能安装一个，小白求助，感谢

### Describe the solution you'd like

在同一个NAS下安装2个MEMOS

**Comment by Zeng1998** [comment]
map the container port to different host ports.

https://docs.docker.com/config/containers/container-networking/

**Comment by jeechoul** [comment]
> map the container port to different host ports.

感谢回复，但是容器的端口不是固定的5230吗？已经启动一个memos占用了5230端口了呢

**Comment by Zeng1998** [comment]
Please take a few minutes to learn about the container port, host port and the mapping of them.

**Comment by leafney** [comment]
在群晖docker的`端口设置`那里，将你第二个容器的 `本地端口` 改为其他的比如 `5231`，`容器端口` 保持 `5230` 不变。这样就可以通过 `http://群晖IP:5231` 来访问第二个容器了。
也建议花点时间去了解下容器相关的概念。
