### ISSUE TITLE
How to upgrade memos

### ISSUE THREAD

**Issue by da1234cao** [usememos/memos#1736]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

- Convenient upgrade commands or scripts to quickly experience new features
- 便捷的升级命令或脚本，以快速的体验新的功能

### Additional context

I deploy memos with docker in linux

```shell
docker run -d --name memos -p 5230:5230 -v ~/.memos/:/var/opt/memos ghcr.io/usememos/memos:latest
```

_No response_

**Comment by Zeng1998** [comment]
![image](https://github.com/usememos/memos/assets/31177490/5b631e88-b417-4a13-82de-70771d3f57d7)

**Comment by da1234cao** [comment]
Yes, Thanks. The following is the command to update memos to the latest version。

```shell
```shell
# 最开始安装memos
docker run -d --name memos -p 5230:5230 -v ~/.memos/:/var/opt/memos ghcr.io/usememos/memos:latest

# 查看有哪些镜像
docker image ls
# 查看容器状态
docker ps -a
# 启动容器
docker start memos

# 停止容器
docker stop memos
# 删除容器
docker rm memos
# 拉取最新版本
docker pull ghcr.io/usememos/memos:latest
# 重新启动
docker run -d --name memos -p 5230:5230 -v ~/.memos/:/var/opt/memos ghcr.io/usememos/memos:latest
``````
