### ISSUE TITLE
希望增加导入功能

### ISSUE THREAD

**Issue by jxjxjhjh** [usememos/memos#1749]
### Is your feature request related to a problem?

md格式的日记文件，文件名是2023-05-22.md，导入memos，日期为文件名日期。

### Describe the solution you'd like

希望能实现这样的功能，或者有别的办法实现，两年的日记几百个文件，手动真心没办法。

**Comment by hyoban** [comment]
已经在 https://github.com/hyoban/kirika 中支持，如果有任何使用上的问题，欢迎提 issue。
