### ISSUE TITLE
github sso配置好后登录报错

### ISSUE THREAD

**Issue by Meteor-showers** [usememos/memos#1752]
### Describe the bug

{
  "error": "code=500, message=Failed to get user info, internal=failed to unmarshal response body: invalid character '<' looking for beginning of value",
  "message": "Failed to get user info"
}

### Steps to reproduce

配置如图

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/32284743/e5b89913-06fd-40c0-b926-c845b15deb57)

**Comment by boojack** [comment]
Please update your configuration follow by the latest templates. https://github.com/usememos/memos/pull/1753/files

**Comment by Meteor-showers** [comment]
sso登录会重新创建一个新的账号 能否绑定之前的账号数据呢

从 Windows 版邮件发送

发件人: boojack
发送时间: 2023年5月26日 22:24
收件人: usememos/memos
抄送: Meteor-showers; Author
主题: Re: [usememos/memos] github sso配置好后登录报错 (Issue #1752)

Closed #1752 as completed.
