### ISSUE TITLE
0.13.1 Archive API 无效

### ISSUE THREAD

**Issue by linsein** [usememos/memos#1757]
## 现象
在网页页面点击 Archive 后无效，记录类型仍然为 `NORMAL`

### API URL 
`https://memos.lin.moe/api/memo/32`
### Request Payload :  
```json
{"id":32,"rowStatus":"ARCHIVED"}
```
### Response: 
```
{
  "data": {
    "id": 32,
    "rowStatus": "NORMAL",
    "creatorId": 1,
    "createdTs": 1681781820,
    "updatedTs": 1685180714,
    "content": "Vapoursynth 是一个视频剪辑软件  \n动画字幕压制经常拿来用  \n可以用一种类似 python 的脚本来编写处理流程",
    "visibility": "PUBLIC",
    "pinned": false,
    "creatorName": "Lindsay",
    "resourceList": [],
    "relationList": []
  }
}
```

## 后台日志：
```
May 27 17:45:14 seiga.host.lin.moe memos[589376]: {"time":"2023-05-27T17:45:14+08:00","method":"PATCH","uri":"/api/memo/32","status":200,"error":""}
```
## 软件信息
+ Memos 版本： 0.13.1 

+ 运行方式：二进制，编译方式参考 [Aur PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=memos-git) 中的 build 函数  

+ 启动参数：`/usr/bin/memos -d /var/lib/memos -m prod -p 5230`

### Steps to reproduce

1. 编译二进制版本 memos v0.13.1
2. 使用上述参数启动 memos 
3. 使用新用户新建记录并点击页面上的 Archive 按钮

**Comment by boojack** [comment]
Already fixed, please pull the latest image again.
