### ISSUE TITLE
点击tags或者捷径搜索很容易卡死

### ISSUE THREAD

**Issue by flyklmwl** [usememos/memos#1759]
### Describe the bug

点击tags或者捷径搜索很容易卡死

### Steps to reproduce

使用的云服务器，记录的memos在1400+记录。 数据库在300kb+，点击捷径或者标签搜索。 特别容易卡死。日志里面就是一堆类似的请求不停的刷。
看了一下版本的更新，好像是做了性能优化不知道是不是解决了这个问题。不过我用的0.13.1 版本还是特别卡，基本搜索不出来。 如果把所有记录都刷出来后再搜索，倒是能很快的搜索出来结果。

### Screenshots or additional context

{"time":"2023-05-27T13:50:49Z","method":"GET","uri":"/api/memo?rowStatus=NORMAL&offset=240&limit=20","status":200,"error":""}
{"time":"2023-05-27T13:50:49Z","method":"GET","uri":"/api/memo?rowStatus=NORMAL&offset=240&limit=20","status":200,"error":""}
{"time":"2023-05-27T13:50:49Z","method":"GET","uri":"/api/memo?rowStatus=NORMAL&offset=240&limit=20","status":200,"error":""}
{"time":"2023-05-27T13:50:49Z","method":"GET","uri":"/api/memo?rowStatus=NORMAL&offset=240&limit=20","status":200,"error":""}
{"time":"2023-05-27T13:50:50Z","method":"GET","uri":"/api/memo?rowStatus=NORMAL&offset=240&limit=20","status":200,"error":""}
{"time":"2023-05-27T13:50:50Z","method":"GET","uri":"/api/memo?rowStatus=NORMAL&offset=240&limit=20","status":200,"error":""}
{"time":"2023-05-27T13:50:50Z","method":"GET","uri":"/api/memo?rowStatus=NORMAL&offset=240&
{"time":"2023-05-27T13:50:50Z","method":"GET","uri":"/api/memo?rowStatus=NORMAL&offset=240&limit=20","status":200,"error":""}
{"time":"2023-05-27T13:50:50Z","method":"GET","uri":"/api/memo?rowStatus=NORMAL&offset=240&limit=20","status":200,"error":""}

**Comment by athurg** [comment]
It'll be fixed in #1773.
