### ISSUE TITLE
Numbered lists should only happen if the number is only at the start, or after whitespace

### ISSUE THREAD

**Issue by limdingwen** [usememos/memos#176]
<img width="620" alt="Screenshot 2022-08-26 at 14 24 31" src="https://user-images.githubusercontent.com/1744967/186836522-49dd44b1-6f06-4929-a361-309954206e24.png">

Gives this result:

<img width="623" alt="Screenshot 2022-08-26 at 14 24 35" src="https://user-images.githubusercontent.com/1744967/186836530-0a937502-93b8-4dc7-8ad2-0b9b79a53e39.png">

I think numbered lists should only happen if the number is either at the start of the line, or has only whitespace before the number. I think this is a bug. What do you think?

**Comment by boojack** [comment]
It's a bug at all. The memo content parser is simply written by myself which will only parse part of markdown syntax. And I'm going to find a better solution to fix these unwanted problems.
