### ISSUE TITLE
如何使用反代地址来访问telegrambot

### ISSUE THREAD

**Issue by assassinliujie** [usememos/memos#1763]
### Is your feature request related to a problem?

大陆无法直接访问tg bot api，我建立了反代来使用，但似乎docker中不太好编辑这一请求地址，我在源文件中找到了这一项，但是似乎不太好部署

### Describe the solution you'd like

一个可以在docker-compose中配置的环境变量，用于填写tg bot api地址，就像可以填openai api反代地址一样

**Comment by athurg** [comment]
下一个版本提供吧，如果需要的话。

**Comment by assassinliujie** [comment]
感谢发自我的荣耀手机-------- 原始邮件 --------发件人： Athurg Gooth ***@***.***>日期： 2023年5月28日周日 晚上9:02收件人： usememos/memos ***@***.***>抄送： assassinliujie ***@***.***>, Author ***@***.***>主    题： Re: [usememos/memos] 如何使用反代地址来访问telegrambot (Issue #1763)
下一个版本提供吧，如果需要的话。
