### ISSUE TITLE
v0.13.1 start error

### ISSUE THREAD

**Issue by bboysoulcn** [usememos/memos#1768]
### Describe the bug

failed to get profile, error: 1 error(s) decoding:

* cannot parse 'Port' as int: strconv.ParseInt: parsing "tcp://10.43.238.103:80": invalid syntax
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xd7adfd]

goroutine 1 [running]:
github.com/usememos/memos/store/db.(*DB).Open(0xc00039fb18?, {0x1448d98?, 0xc0002f5b00?})
	/backend-build/store/db/db.go:41 +0x3d
github.com/usememos/memos/server.NewServer({0x1448d98, 0xc0002f5b00}, 0x0)
	/backend-build/server/server.go:39 +0xa5
github.com/usememos/memos/cmd.glob..func1(0x197fd80?, {0x1030071?, 0x0?, 0x0?})
	/backend-build/cmd/memos.go:44 +0x57
github.com/spf13/cobra.(*Command).execute(0x197fd80, {0xc0001921f0, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x197fd80)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/usememos/memos/cmd.Execute(...)
	/backend-build/cmd/memos.go:112
main.main()

	/backend-build/main.go:10 +0x25
failed to get profile, error: 1 error(s) decoding:

### Steps to reproduce

start error

**Comment by Zeng1998** [comment]
No one knows your environment. No one knows what you have done.

![image](https://github.com/usememos/memos/assets/31177490/fbd843fb-201b-4f32-8fcf-d9507268a57e)

BTW, A bad issue can save you time temporarily, but it won't help solve the problem, causing more time wasted.
