### ISSUE TITLE
Error on container accessing https://api.openai.com: "Failed to post chat completion"

### ISSUE THREAD

**Issue by Crazy-FuQing** [usememos/memos#1771]
### Describe the bug

Error on container accessing https://api.openai.com: "Failed to post chat completion"以下是我的错误日志
{
  "error": "code=500, message=Failed to post chat completion, internal={\"code\":\"invalid_api_key\",\"message\":\"\",\"param\":null,\"type\":\"invalid_request_error\"}",
  "message": "Failed to post chat completion"
}
![无标题](https://github.com/usememos/memos/assets/46838021/a486b351-e5ba-4deb-83f8-831084cba0f4)

### Steps to reproduce

1. 容器配置代理上网保证和https://api.openai.com的正常通信
2. 在设置页面配置了有效的OpenAI的API 密钥
3. 在“问ai”功能中发送消息就会得到这个错误

**Comment by boojack** [comment]
应该是服务器无法连接到 openai API，不过该功能目前已经下线，可以自行使用其他 ChatGPT 相关的项目。
