### ISSUE TITLE
能设置宽屏页面么?

### ISSUE THREAD

**Issue by star2k** [usememos/memos#1774]
### Is your feature request related to a problem?

左右空白较多，能添加宽屏按钮么？
![1212](https://github.com/usememos/memos/assets/9582078/d923dd69-1420-4b0a-af9a-aab6dfb32e14)

### Describe the solution you'd like

左右空白较多，能添加宽屏按钮么？
![1212](https://github.com/usememos/memos/assets/9582078/d923dd69-1420-4b0a-af9a-aab6dfb32e14)

**Comment by jifeiyun** [comment]
I hope to make the middl
![0002222](https://github.com/usememos/memos/assets/33753479/6e7a6c5d-8d05-4ee1-bfc9-5709f87a41ea)
e bar a little wider, but now the screens are relatively large, looking a little smaller.

**Comment by salvoza** [comment]
It would be awesome if we could get a wider memos on wide screens

**Comment by boojack** [comment]
The latest demo site(https://demo.usememos.com) has been updated with relevant layout to work better on wide screens. You guys can try it out and give some feedback! @star2k @jifeiyun @salvoza

**Comment by star2k** [comment]
> The latest demo site(https://demo.usememos.com) has been updated with relevant layout to work better on wide screens. You guys can try it out and give some feedback! 最新演示网站( https://demo.usememos.com) 已更新相关布局，以便在宽屏上更好地运行。你们可以试一试并提供一些反馈意见！@star2k @jifeiyun @salvoza



> The latest demo site(https://demo.usememos.com) has been updated with relevant layout to work better on wide screens. You guys can try it out and give some feedback! 最新演示网站( https://demo.usememos.com) 已更新相关布局，以便在宽屏上更好地运行。你们可以试一试并提供一些反馈意见！@star2k @jifeiyun @salvoza

How to achieve your effect?

**Comment by boojack** [comment]
@star2k It will be updated in the next release.
