### ISSUE TITLE
Ask AI不支持流式输出

### ISSUE THREAD

**Issue by JeazW** [usememos/memos#1776]
### Describe the bug

Ask AI不支持流式（stream）输出（打字机效果）,希望可以修复；另外这个功能可不可以加个开关，关闭后不显示这个功能。多谢。

### Steps to reproduce

1.点击ASK AI
2.提问
3.等待回答（目前是所有文本返回完成后才一次性显示出来，而不是流式打印到屏幕上）

**Comment by boojack** [comment]
Ask AI has been removed.
