### ISSUE TITLE
图片不见了

### ISSUE THREAD

**Issue by jeechoul** [usememos/memos#1778]
今天突然发现以前发布的memos一些图片不见了，请问有办法恢复吗，每次升级都有导出备份

![image](https://github.com/usememos/memos/assets/92965195/27c217f8-a2c9-409b-ab80-aab8ef6bc103)

![image](https://github.com/usememos/memos/assets/92965195/876ad1f9-9c5c-47da-b98a-6bf12eb860a2)

![image](https://github.com/usememos/memos/assets/92965195/d791f1dd-9280-4ea2-b02f-bc47df3488f1)

![image](https://github.com/usememos/memos/assets/92965195/5f70c51b-8082-4b6d-9324-d4aa2d80fe62)

**Comment by boojack** [comment]
Already fixed in `v0.13.1`
