### ISSUE TITLE
[feature request][Mobile] Swipe to archive item

### ISSUE THREAD

**Issue by JJPro** [usememos/memos#178]

**Comment by jxpsert** [comment]
This repo isn't the mobile app, nor is it the same creator. For iOS, go [here](https://github.com/mudkipme/MoeMemos), for Android go [here](https://github.com/mudkipme/MoeMemosAndroid).

**Comment by boojack** [comment]
Touch gestures should be the interaction of mobile software. And it's hard in a responsive website.
