### ISSUE TITLE
升级成0.13.1内部图片资源失效

### ISSUE THREAD

**Issue by marksam-cn** [usememos/memos#1780]
### Describe the bug

升级成0.13.1内部图片资源失效

### Steps to reproduce

![2023-05-31_104041](https://github.com/usememos/memos/assets/20943953/1a888bb7-0f7f-4cba-aeae-bbd29984b35f)
![2023-05-31_104056](https://github.com/usememos/memos/assets/20943953/5bab9239-c190-48a3-9e6f-6e41a6c9df80)
修改成这样才能正常显示
![2023-05-31_105202](https://github.com/usememos/memos/assets/20943953/39f7374e-8670-44bd-b902-81e637cea381)
引用位置不可以修改
![2023-05-31_105338](https://github.com/usememos/memos/assets/20943953/ef02b830-3fce-45ff-98d3-5400b66d8257)
同时编辑内容也不可以复制

**Comment by Zeng1998** [comment]
A strong recommendation:  do **NOT** use markdown syntax to reference images in the resource store.

BTW, it is also not recommended to discuss multiple unrelated topics within the same issue.
