### ISSUE TITLE
Cannot parse 'Port' as int: strconv.ParseInt in K3s

### ISSUE THREAD

**Issue by Dan6erbond** [usememos/memos#1782]
### Describe the bug

When running the container with minimal configuration the following error appears in Kubernetes (K3s):

```go
* cannot parse 'Port' as int: strconv.ParseInt: parsing "tcp://10.43.7.62:5230": invalid syntax
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xd7adfd]
```

### Steps to reproduce

Deploy the app to K3s.

**Comment by boojack** [comment]
> cannot parse 'Port' as int: strconv.ParseInt: parsing "tcp://10.43.7.62:5230": invalid syntax panic: runtime error: invalid memory address or nil pointer dereference

It looks like you passed an invalid port parameter.

**Comment by Arkmusn** [comment]
Same problem. I have try to change the service name to "memos-web", but it still doesn't work.

**Comment by Skaronator** [comment]
Just hit the same issue in my Kubernetes cluster. It's a bit unfortunate that Kubernetes default injected Environment Variable collide with memos environment variable.  I'd really appreciate it if the environment variable could be renamed in memos. Maybe name it MEMOS_HTTP_PORT instead?

Funny enough, I hit the same issue with Trillium as you can see here: https://github.com/zadam/trilium/issues/3177

A workaround would be to manually set MEMOS_PORT as an environment variable in your deployment. This will overwrite the default injected environment variables created by Kubernetes.

**Comment by tadasgedgaudas** [comment]
Changing deployment name didn't work for me, only changing Docker tag to `:0.13.0` worked

For anyone who's coming here:

```
kubectl get deployment memos -o yaml > deployment.yaml -n memos
```

Edit `:latest` -> `:0.13.0`

```
kubectl apply -f deployment.yaml
```


But really the port variable should be changed since it's conflicting

**Comment by mcbtaguiad** [comment]
Changing deployment name did the trick for me.

**Comment by czasg** [comment]
> Similarly with this issue [mattermost/mattermost-helm#228 (comment)](https://github.com/mattermost/mattermost-helm/issues/228#issuecomment-865469560)
> 
> with the latest tag (0.14.2 at 23-07-26 utc), after I setting env in deployment like below, it works now:
> 
> Method 1: edit deployment, add
> 
> ```yaml
>           env:
>             - name: MEMOS_PORT
>               value: "5230"
> ```
> 
> or:
> 
> Method 2: using cli to set env `kubectl set env deployment/focalboard MEMOS_PORT=5230`

it works for me.
