### ISSUE TITLE
unable to open database

### ISSUE THREAD

**Issue by zzy-design** [usememos/memos#1783]
### Steps to reproduce

1，docker run -d --name memos -p 5230:5230 -v /root/memos/:/var/opt/memos ghcr.io/usememos/memos:latest

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/69064727/7b1b0da9-90b1-4626-9fa7-1461bcea1dbf)

**Comment by Zeng1998** [comment]
Make sure that the `/root/memos/` exists.

**Comment by zzy-design** [comment]
> Make sure that the `/root/memos/` exists.
I used this parameter (--privileged=true) to complete
