### ISSUE TITLE
Failed to compose memo response after upgraded to 0.13.1 (from 0.13.0)

### ISSUE THREAD

**Issue by xu4wang** [usememos/memos#1784]
### Describe the bug

Upgraded the docker image from 0.13.0 to 0.13.1, the old notes cannot be open anymore.

There is error in the docker logs.

```
{"time":"2023-05-31T16:37:08Z","method":"GET","uri":"/api/memo?rowStatus=NORMAL&limit=20","status":500,"error":"code=500, message=Failed to compose memo response, internal=not found"}
```

### Steps to reproduce

1. stop current container
2. remove container memos
3. pull the latest image 0.13.1
4. start memos with the latest image
5. open browser, there is error message on the upper right conner "Failed to compose memo response"

### Screenshots or additional context

This is not a browser cache issue.  I also tried using incognito mode and with different browser.

**Comment by boojack** [comment]
<img width="1122" alt="image" src="https://github.com/usememos/memos/assets/24653555/7ded1dab-c9d5-4cae-93e1-57a933ff424b">

Could you please try to vacuum database with this button? Maybe it will works.

**Comment by xu4wang** [comment]
> <img alt="image" width="1122" src="https://user-images.githubusercontent.com/24653555/242436832-7ded1dab-c9d5-4cae-93e1-57a933ff424b.png">
> Could you please try to vacuum database with this button? Maybe it will works.

What does that mean? "vacuum" looks scary for me.

**Comment by Zeng1998** [comment]
> > <img alt="image" width="1122" src="https://user-images.githubusercontent.com/24653555/242436832-7ded1dab-c9d5-4cae-93e1-57a933ff424b.png">
> > Could you please try to vacuum database with this button? Maybe it will works.
> 
> What does that mean? "vacuum" looks scary for me.

https://www.sqlite.org/lang_vacuum.html

> The VACUUM command rebuilds the database file, repacking it into a minimal amount of disk space.

**Comment by xu4wang** [comment]
> > > <img alt="image" width="1122" src="https://user-images.githubusercontent.com/24653555/242436832-7ded1dab-c9d5-4cae-93e1-57a933ff424b.png">
> > > Could you please try to vacuum database with this button? Maybe it will works.
> > 
> > 
> > What does that mean? "vacuum" looks scary for me.
> 
> https://www.sqlite.org/lang_vacuum.html
> 
> > The VACUUM command rebuilds the database file, repacking it into a minimal amount of disk space.

VACUUM works. Thanks @boojack @Zeng1998
