### ISSUE TITLE
能不能在memos图标旁边加个刷新按钮，或者下拉刷新？

### ISSUE THREAD

**Issue by pxd0207** [usememos/memos#1789]
### Is your feature request related to a problem?

手机端PWA网页无法刷新

### Describe the solution you'd like

电脑端还好可以刷新网页，但是在手机上的PWA没有刷新按钮要滑后台重进才能刷新。

**Comment by athurg** [comment]
It'll be cool to pin the nav bar always in the top, and refresh the page by 
- pull-down after scroll to the top of page.
- click on the nav bar

**Comment by athurg** [comment]
@pxd0207 You can just click on the site title `MEMOS` to reload the page with the latest `test` version.
