### ISSUE TITLE
RangeError: Value need to be finite number for Intl.RelativeTimeFormat.prototype.format()

### ISSUE THREAD

**Issue by chencd97** [usememos/memos#1798]
### Describe the bug

在 `web/src/components/Memo.tsx` 中

```ts
getRelativeTimeString(memo.displayTs)
```

方法会报错, 原因是后端没有返回的displayTs, 导致前端对象memo中的displayTs值为NaN, 转换时会出现 `RangeError: Value need to be finite number for Intl.RelativeTimeFormat.prototype.format()` 错误

### Steps to reproduce

pnpm dev

### response content:
![image](https://github.com/usememos/memos/assets/15999183/f0b24b52-4ac2-4eba-8a2b-cb88ebe1981c)

### The console prints the memo object:
![image](https://github.com/usememos/memos/assets/15999183/ad366d0b-b0d0-4421-a16a-2623e3a6f41f)

### web error msg:
![image](https://github.com/usememos/memos/assets/15999183/495c6e73-af35-44de-b0fb-90f620f67ea0)

### code (Memo.tsx):
![image](https://github.com/usememos/memos/assets/15999183/39f7c304-0e34-4d9d-bfc0-fd6b00a6169a)

**Comment by tranquanghuy0801** [comment]
@chencd97 I could not replicate this issue. Could you please provide more steps on how to replicate this?

**Comment by boojack** [comment]
Maybe already fixed in the latest version.

**Comment by tranquanghuy0801** [comment]
Yeah this is what I am thinking
