### ISSUE TITLE
Using bold and italics together causes formatting issues.

### ISSUE THREAD

**Issue by JefrinJabez** [usememos/memos#1810]
### Describe the bug

Using three asterisks together to format a part of the text to use both bold and italics causes formatting and paragraphing errors after the part where three asterisks are used.

### Steps to reproduce

1. Create a new post
2. Use text with three asterisks before and after it.
3. Include a heading in the next line (or any other kind of text)

### Screenshots or additional context

![Screenshot 2023-06-08 at 11 11 55 AM](https://github.com/usememos/memos/assets/135850048/8d605b09-0f4d-400b-a47f-3dff0b987314)

![Screenshot 2023-06-08 at 11 12 26 AM](https://github.com/usememos/memos/assets/135850048/84e43e26-bd27-43fd-892c-af1810a2c4e2)

**Comment by boojack** [comment]
Fixed in the latest main.

<img width="534" alt="image" src="https://github.com/usememos/memos/assets/24653555/a6109bb8-5cd3-4410-8109-384c4c7ba44a">
