### ISSUE TITLE
Unexpected error message when saving Telegram Token

### ISSUE THREAD

**Issue by oregonpillow** [usememos/memos#1819]
### Describe the bug

If you save a Telegram Robot Token in settings the confirmation message that pops up is "OpenAI Config updated".
It shoud say something like "Telegram Token updated"

### Steps to reproduce

1. Within app, go to `Settings > System`
2. Add or update `Telgram Robot Token`

**Comment by Zeng1998** [comment]
Already fixed by this PR #1767 .
