### ISSUE TITLE
 An error will occur when the file name contains a plus sign.

### ISSUE THREAD

**Issue by fiifff** [usememos/memos#1820]
### Describe the bug

I am currently using version 0.13.1. When I use local storage, the file should be in the "year" directory, but instead an extra level of directory is created, causing problems when the original file name has "+".
` "error": "code=500, message=Failed to find resource by ID: 10053, internal=not found",
  "message": "Failed to find resource by ID: 10053"`
And at that time, clearing unnecessary resources and folders did not result in the deletion of the folder itself; only the contents of the files were deleted. In previous versions, a separate folder was not created for each attachment.

### Steps to reproduce

1. Upload a file with a name that contains a plus sign.
2. save
3. An error will occur when clicking to view the attachment.

**Comment by athurg** [comment]
You can paste you storage config, such as the storage type and directory. This maybe useful to handle this issue.

**Comment by fiifff** [comment]
this is my local storage config
`assets/{year}/{timestamp}_{filename}`
I only used this local storage configuration and never changed it, but after using 0.13.1, an additional level of directory was created.

**Comment by athurg** [comment]
Just replace the `{filename}` to `{publicid}` in your config to fix this problem.

**Comment by fiifff** [comment]
- According to the docs configuration, I didn't know there was this new configuration option.
-  In this way, the original file name will be replaced with CID  :(  .
-  even if the configuration option is changed,Even if there is a plus sign in the file name, it will still result in an error.

**Comment by athurg** [comment]
This issue will be fixed in #1892 .

And again again again, we do really need to avoid use the original filename from user.
