### ISSUE TITLE
The resource could not be loaded

### ISSUE THREAD

**Issue by crayhuang** [usememos/memos#1821]
### Describe the bug

I got this error when I setup the app for iOS
![image](https://github.com/usememos/memos/assets/3095930/2ba67a5d-4d15-4a9a-82ac-f7847c1a7724)

### Steps to reproduce

1. Config iOS app with openAPI info

**Comment by jxpsert** [comment]
The iOS app isn't ours. Make an issue in https://github.com/mudkipme/MoeMemos.

**Comment by crayhuang** [comment]
> The iOS app isn't ours. Make an issue in https://github.com/mudkipme/MoeMemos.

Noted with thanks.
