### ISSUE TITLE
Store GPS/Location data with each note

### ISSUE THREAD

**Issue by justyns** [usememos/memos#1826]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

When creating a note/memo, sometimes I'd like the option to save my current gps location when using a mobile browser.   I'm not exactly sure how this would look in the UI, but maybe just a checkbox or user preference?

### Additional context

I'm still new to memos, but I like to create notes from my mobile device and sometimes having the context of where I was at the time can help future me.

**Comment by ituri** [comment]
Would very much love to see that too!

**Comment by Doradx** [comment]
This is really a good idea and it would be nice to have a map to show this!

**Comment by boojack** [comment]
Refer to https://github.com/usememos/memos/issues/2903
