### ISSUE TITLE
希望全屏编辑时tag选择框向上展开

### ISSUE THREAD

**Issue by Vespa314** [usememos/memos#1834]
![image](https://github.com/usememos/memos/assets/6339395/a3804a4a-27b2-43b0-b89e-195b43dc7f86)

当前全屏编辑的时候，点击tag框是显示在tag按钮下面的，当tag比较多的时候，下面的tag是没办法选到的。

**Comment by CorrectRoadH** [comment]
👀如果加一个滚动条之类的，让下面的tag可以被选到是不是也是一种思路

**Comment by boojack** [comment]
Fullscreen mode will be removed in the next version.
