### ISSUE TITLE
Files are not physically deleted from storage

### ISSUE THREAD

**Issue by jewink** [usememos/memos#1837]
### Describe the bug

If you delete a file in Resources they are not physically delted on the storage. This applies to both local files and files stored in S3.
Used version: v0.13.1 on docker

### Steps to reproduce

1. Upload a file in Resources
2. Check where it is stored in the file system
3. Delete the file in Resources
4. The entry disappears in the web, but not on the storage

**Comment by MauroGuida** [comment]
Furthermore, I would like to add that if you upload a resource from an external link, even when you delete that resource, it will still appear in third-party apps but not in the web app or the assets folder.
