### ISSUE TITLE
Login Failure

### ISSUE THREAD

**Issue by BenSellnow** [usememos/memos#1839]
### Describe the bug

As soon as you use the default username and password and click connect as host it said `Failed to find users`.This continues to not let me log in.

### Steps to reproduce

Go to login page
Attempt to login

**Comment by albertopasqualetto** [comment]
Talking about demo

**Comment by boojack** [comment]
Thanks for your report, I'll redeploy the demo site later.

**Comment by boojack** [comment]
Please check the latest demo site: https://demo.usememos.com/
