### ISSUE TITLE
Markdown tables support

### ISSUE THREAD

**Issue by dejanstojanovic** [usememos/memos#1843]
### Is your feature request related to a problem?

I was trying to add a table to my note in common format and notice that it does not work

| column1 | column 2 |
|-----------|----------- |
| value 1   | valuee 2   |

It would be nice if we could add a table to a note content

### Describe the solution you'd like

Render out markdown table syntax

**Comment by turtaf** [comment]
+1

**Comment by rvnkcode** [comment]
Tables aren't rendered in `0.18.2`.
