### ISSUE TITLE
是否可加入个功能筛选所有带有未完成待办事项的记录

### ISSUE THREAD

**Issue by jameslhc** [usememos/memos#1850]
### Is your feature request related to a problem?

没问题

### Describe the solution you'd like

有些记录是做了待办事项，但是累积多了就会忽略之前忘记的待办事项。
如果有个筛选能仅显示未完成的待办，这样就方便多了。

**Comment by songmyc** [comment]
加个tag？

**Comment by boojack** [comment]
It can be filtered by search `- [ ] `

<img width="769" alt="image" src="https://github.com/usememos/memos/assets/24653555/729cc15c-1850-47c5-9cff-907640d69eb2">
