### ISSUE TITLE
能否支持语音输入？

### ISSUE THREAD

**Issue by JerryWesler** [usememos/memos#1852]
### Is your feature request related to a problem?

这样能在telegram或者Apple Watch的快捷方式里，可以便捷用语音记录。

### Describe the solution you'd like

如果可行，最好也能配合OpenAI自动识别成文字的概要，这个概要可以支持隐藏或者显示，方便日后搜索。

**Comment by songmyc** [comment]
memos的api加快捷指令可以实现语音输入

**Comment by pisceswb** [comment]
> memos的api加快捷指令可以实现语音输入

请问能用在Android手机上吗?怎样实现，能不能给一个具体的实现方法，谢谢！
