### ISSUE TITLE
自定义脚本失败

### ISSUE THREAD

**Issue by RobKing9** [usememos/memos#1857]
### Describe the bug

通过 Docker 搭建的放在服务器，用Nginx Proxy 做反向代理。然后想用Umami来监控访问数据，之前用我基本都是在自定义脚本添加 Umami提供的代码，但是Memos好像统计不到数据
![image](https://github.com/usememos/memos/assets/78016475/a0a72dc1-a78e-400c-a0fb-6a2f48ed0155)
![image](https://github.com/usememos/memos/assets/78016475/e361b103-2a9b-4af7-8a2b-b67e614d385c)

### Steps to reproduce

通过浏览器 开发者工具检查

**Comment by RobKing9** [comment]
https://cool.robking.top/
Memos网站链接

**Comment by boojack** [comment]
This is the correct way to use:

```js
const script = document.createElement('script');
script.src ='your_link';
document.body.appendChild(script);
```
