### ISSUE TITLE
input # can not pop up label window

### ISSUE THREAD

**Issue by gujin03** [usememos/memos#1858]
### Describe the bug

When I click # on the interface, the prompt box of the label can pop up, but when I manually input #, the prompt box of the label does not pop up.

### Steps to reproduce

When I click # on the interface, the prompt box of the label can pop up, but when I manually input #, the prompt box of the label does not pop up.

**Comment by tranquanghuy0801** [comment]
I think we can do both at here, the first one already exists, we just need to do the 2nd one, which I think is more user-friendly, like how we use @ to mention someone
