### ISSUE TITLE
Does not refresh upon open (as iOS Home webapp)

### ISSUE THREAD

**Issue by JJPro** [usememos/memos#187]
First of all, Thanks for the great work. Really enjoyed using this simple convenient app. 

I added this web app to iPhone's home screen, so it can behave like a native app. 
But it always shows old data from last operation. If I make changes on my desktop, and then switch to my iPhone, the data is not synced. And as a home screen webapp, there is no refresh button like in the browser. 
I wish there is a way to auto-refresh the page upon switching back to it. 
Or at least show a button that let users manually refresh.

Maybe websocket or long-polling could be a potential consideration for server-client syncing, but I don't known how these techniques will affect phone batteries when the webapp is running in background.

**Comment by boojack** [comment]
At present, you can click the MEMOS text in the header to refresh manually. I don't want to display a refresh icon directly, it looks a bit wired.

Related issue comment: https://github.com/usememos/memos/issues/160#issuecomment-1229148557

**Comment by JJPro** [comment]
Oh Thank you, I didn't know the header is clickable.
