### ISSUE TITLE
Will there be a Web clipper

### ISSUE THREAD

**Issue by arromattic** [usememos/memos#1876]
### Is your feature request related to a problem?

The lack of an web clipper like KEEP

### Describe the solution you'd like

A webclipper that has 
1. selection text
2. page screenshot
3. select screenshot
4. save page text
5. works on firefox.

**Comment by boojack** [comment]
Maybe it should be a extension function. And there is an open source browser extension https://github.com/lmm214/memos-bber. You can request a feature to it.
