### ISSUE TITLE
忘记密码

### ISSUE THREAD

**Issue by Yuelioi** [usememos/memos#188]
本来想着反正有数据库 大不了重搭备份下数据库, 结果我忘了就一个db文件 重搭了还是用这个用户信息...

能不能后台搞个指令 一键重置密码之类

**Comment by boojack** [comment]
可以先用某个可视化工具（Navicat、TablePlus 等）打开你的 SQLite 数据库文件直接改数据，建议改成这个[sample hash password](https://github.com/usememos/memos/blob/main/store/db/seed/10001__user.sql#L18)，然后密码就会是 `secret` 了

**Comment by i-iooi-i** [comment]
对于小白来说，重置密码的功能还是有必要的~🥲

**Comment by Siomt** [comment]
这个db文件在哪个目录下，我用docker安装的

**Comment by SilverFox008** [comment]
为什么不能打开memos_prod.db文件，提示报错 14 - unable to open database file

**Comment by 2144291529** [comment]
算了 我写个重置密码的全过程吧 

忘记密码怎么办（全网独一份教程）
1.首先进到docker部署挂载的目录 /opt/memos ，将两个文件下载下来到单独的文件夹中
memos_prod.db
memos_prod.db-wal

然后将服务器上的/opt/memos文件移到其他地方备份下
 mv /opt/memos/* /tmp
本地电脑打开
载Navicat并安装 打开后选择试用
文件-新建链接-SQLITE链接
新建SQLITE3 选择你的db文件
在表里找到user , 对应password_hash改为 $2a$14$ajq8Q7fbtFRQvXpdCq7Jcuy.Rx1h/L4J60Otx.gyNLbAYctGMJ9tK
直接ctrl S 保存,然后把这个目录下的三个文件传回服务器，为什么会是三个，因为会自动生成一个文件shm
密码这时候是secret
服务器收到文件放到原来目录下，重启docker服务即可，电脑浏览就可以访问了，最后打开f12禁用缓存
【差点把我数据搞丢了，特地写的，当然只要你docker部署做了本地化映射部署，把文件备份，丢数据情况应该不会有】

**Comment by xyhcode** [comment]
。。。
My orbstack installation cannot find this file at all
