### ISSUE TITLE
v0.13.2 界面越改越糙了

### ISSUE THREAD

**Issue by cethink** [usememos/memos#1881]
### Is your feature request related to a problem?

。

### Describe the solution you'd like

新建按钮好突兀，感觉可以直接把输入框固定在顶部。另外不能找个设计师么，程序员果然不擅长界面。

**Comment by liu7526539** [comment]
确实

**Comment by Nicolasking007** [comment]
![image](https://github.com/usememos/memos/assets/45583166/fe0ecff8-4961-4728-9556-1ebe90140ed8)

**Comment by cethink** [comment]
![image](https://github.com/usememos/memos/assets/756512/b46ee736-7da5-44cd-8d10-926fed163629)
感觉在抄twitter

**Comment by boojack** [comment]
> 新建按钮好突兀

目前所有页面都不用弹窗的方式来展示了，加个按钮可以在其他页面做创建。如果不加的话，就只能在 home 页进行创建操作。

> 感觉可以直接把输入框固定在顶部

能解决上述问题？

> 另外不能找个设计师么，程序员果然不擅长界面

哪里来的刻板印象？？？

> 感觉在抄 twitter

能解决问题就行，抄不抄的和你有什么关系？与其在这里敲键盘，不如动点脑子想想解决方案。
