### ISSUE TITLE
Invalid access token error on Moe Memos mobile app with memos 0.13.2

### ISSUE THREAD

**Issue by jl-678** [usememos/memos#1882]
### Describe the bug

After upgrading to 0.13.2, I can no longer access memos via the mobile app. I put in the right credentials, and it refuses to load saying "invalid access token." Rolling back to 0.13.1 fixes the issue.

### Steps to reproduce

Run 0.13.2 and try to access Memos via the Moe Memos app, and it fails with an "invalid access token" error. The behavior is consistent.

**Comment by boojack** [comment]
Here are some api changes in `v0.13.2`, so you can still use the website in mobile browser. And if you do need to use the mobile app, you can go to [moememos](https://github.com/mudkipme/MoeMemos) and create an issue.

**Comment by jl-678** [comment]
Thx. I just opened an issue there too.
