### ISSUE TITLE
希望SSO可以支持QQ登录或者微信登录

### ISSUE THREAD

**Issue by jkjoy** [usememos/memos#1887]
### Is your feature request related to a problem?

{
  "error": "code=500, message=Failed to exchange token, internal=failed to exchange access token: invalid character 'a' looking for beginning of value",
  "message": "Failed to exchange token"
}

### Describe the solution you'd like

照顾中国用户- -

**Comment by boojack** [comment]
只要 QQ/微信支持 OAuth2 协议就是支持的，相关的配置信息自行探索。

**Comment by jkjoy** [comment]
QQ支持 OAuth2 协议,但是报错了..

**Comment by jkjoy** [comment]
![QQ截图20230717104650](https://github.com/usememos/memos/assets/23159890/f0375db4-82e8-4b97-bcc6-9b7a4a5370dd)

**Comment by jkjoy** [comment]
就是不知道范围和标识符这里具体应该填写什么
