### ISSUE TITLE
希望每日回顾可以使用创建时间而不是编辑时间

### ISSUE THREAD

**Issue by InoryLwc** [usememos/memos#1894]
### Is your feature request related to a problem?

Yes

### Describe the solution you'd like

每日回顾使用编辑时间，会让以前的代办事项在编辑之后变成当天的内容了。
建议给个配置选项让用户选择使用创建时间还是编辑时间。

**Comment by boojack** [comment]
启用了这个设置项就会用更新时间，没启用的话就是创建时间。

<img width="909" alt="image" src="https://github.com/usememos/memos/assets/24653555/1cd94881-074a-407d-b2e3-b71b6944e4d0">
