### ISSUE TITLE
Telegram上传图片bug

### ISSUE THREAD

**Issue by cuiyanjie** [usememos/memos#1902]
### Describe the bug

通过Telegram上传的图片会被强制保存在数据库，而并非设置好的对象存储里。
建议像Telegram bot 询问可见属性那样，询问图片保存在数据库还是已经设置的对象存储里

### Steps to reproduce

1. Telegram里上传图片
2. 选择公开或者私有可见
3.  web页面查看刚才上传的图片没有保存在对象存储里（已经设置并使用了对象存储）

**Comment by athurg** [comment]
This is as expected, because the first version was designed like that.

We'll change this in the next version, which share the storage setting as the HTTP API.
