### ISSUE TITLE
web页面删除Telegram上传的图片后导致系统崩溃

### ISSUE THREAD

**Issue by cuiyanjie** [usememos/memos#1903]
### Describe the bug

素材是从telegram上传的，因为telegram上传素材的bug没解决，默认存到了数据库，于是今天从web端删除这张照片重新上传以便存到对象存储里，结果删除后就崩了！所有操作都Failed to compose memo response了。

### Steps to reproduce

1.Telegram上传图片并写一些文字
2.web页面看到了上传的图片，双击文字进行编辑，删除了图片
3.web页面刷新，所有记录没有了显示Failed to compose memo response
4.重启docker 容器无效
5.替换之前备份的memos_prod.db文件可恢复

**Comment by boojack** [comment]
Fixed in `v0.14.0`

**Comment by cuiyanjie** [comment]
Thanks
