### ISSUE TITLE
“回忆插入”功能

### ISSUE THREAD

**Issue by cuiyanjie** [usememos/memos#1904]
### Is your feature request related to a problem?

可以在过去的日子里插入新的卡片。如今天是7月6日，想起7月3日原本想记录的事情忘记记录了，但7月3日当天没有任何记录，所以没有“便签”可以容纳补充记录。希望可以在7月3日日历处增加新记录功能，或者在新建记录的时候可以选择往过去某天添加。
这类后补的记录颜色可以显示成橘黄色或者黑白色，代表后补的回忆插入。

### Describe the solution you'd like

不限定方法，比如在日历视图新建或者在现有新建视图里增加选择日期功能

**Comment by DocMiao** [comment]
在新建卡片的时候可以默认是今天，但是这个时间开放用户可以修改为某一天就可以了，有些事情是需要未来某一天做的，或者也有事情是之前做过忘了记录的
