### ISSUE TITLE
多个Telegram 账号对应同一个 memos 账号

### ISSUE THREAD

**Issue by cuiyanjie** [usememos/memos#1906]
### Is your feature request related to a problem?

多个Telegram用户的User ID 填入 Memos同一个账号中，便于多人共同往同一个Memos 账号下记录内容。

### Describe the solution you'd like

![示例图](https://raw.githubusercontent.com/cuiyanjie/tata/master/memos.jpg)

**Comment by jkjoy** [comment]
你这个要求有点离谱,一个人一个账户不好么...不明白你这样的需求是什么

**Comment by cuiyanjie** [comment]
因为每个Memos账号只能看到自己的卡片，想要多人共同看彼此发的卡片就得设置成公共可见还得切换成探索模式。

**Comment by jkjoy** [comment]
> 

那你使用web共享账号直接发不就好了?更何况还有各种API,何必用TG呢.为了你想拥有的功能去开发一堆对其他人而言没实用性的功能我觉得不大可能

**Comment by cuiyanjie** [comment]
作者让我这里提一下的哦

**Comment by athurg** [comment]
> 因为每个Memos账号只能看到自己的卡片，想要多人共同看彼此发的卡片就得设置成公共可见还得切换成探索模式。
> 这个需求其实场景挺多的，比如：1.几个家长共同记录孩子成长，如果分不同账号，就看不到别人记录的。2.定向运动几个人共同打卡同一场次目标 3.一个项目组共同写一个日志。还有很多场景。虽然分账号1对1也可以，但不如多对1方便。
> 其实模型类似，公司大群，里面有项目组小群，又有几个关系好的再拉私群。多对1可以实现，几个人共同记录，且设置成私有可见，这样其他人在这里用别的账号记录就看不到了。还有其他原因，本质就是一个排列组合问题，如果有了这个多对一，应用领域又可以拓展很多。

h2. 「家长记录孩子成长」
这种场景，其实用「登录模式可见」或者「公开可见」是能满足需求的。

h2. 「定向运动」或者「小组日志记录」
这种背后的逻辑，其实并不是「多个人一起记录」，而是希望将可见范围，从「全体」、「登录用户」、「自己」三个固定的类别进行拓展，拓展为可配置的、指定范围的「用户组」。

这就不光是「Telegram账号多对一」，而是对整个权限系统需要重新设计。这样一来，不光是Telegram发送的消息，包括网页上发送的消息都应该有对应的支持和改造。

虽然我们可以只在或者先在Telegram实现，但是毕竟是一个半成品。如果设计上完善，实现上可以分步做。但如果设计上没有完善，不建议动手。

h2. 建议
就现阶段来讲，我建议这种共享账号发送的场景，有两种办法：
- 可以自己调用API；
- 或者通过共享一个账号/密码/AccessKey

其中第二种方案也不存在敏感信息泄露的问题。因为如果多个人都能发同样的Memo和看同样的Memo，那他们本质上就是一样的了。
