### ISSUE TITLE
不同域名导致对象存储的图片无法显示

### ISSUE THREAD

**Issue by cuiyanjie** [usememos/memos#1910]
### Describe the bug

我有两个域名都指向了同一个Memos，经常用A访问来写卡片传图片，图片上传到腾讯云对象存储，我发现用B域名访问时，所有对象存储的图片都看不到了，只有占位符，无论是文章里还是资源库，都显示不了图片（文件在），单击打开也不显示，复制地址然后浏览器打开是对的，没问题。
换成IP访问也有上述问题，只有使用当初传图片的A域名访问才没有问题。
但无论是A域名还是B域名，使用OpenAPI（域名不一样）通过Kirika同步到本地的时候，不显示的图片都可以顺利同步到本地。

### Steps to reproduce

我有两个域名都指向了同一个Memos，经常用A访问来写卡片传图片，图片上传到腾讯云对象存储，我发现用B域名访问时，所有对象存储的图片都看不到了，只有占位符，无论是文章里还是资源库，都显示不了图片（文件在），单击打开也不显示，复制地址然后浏览器打开是对的，没问题。
换成IP访问也有上述问题，只有使用当初传图片的A域名访问才没有问题。
但无论是A域名还是B域名，使用OpenAPI（域名不一样）通过Kirika同步到本地的时候，不显示的图片都可以顺利同步到本地。

**Comment by boojack** [comment]
可能是个跨域问题，和 memos 本身无关，可以去了解下相关的知识点

* https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
