### ISSUE TITLE
Host user duplicate registration 

### ISSUE THREAD

**Issue by Yuansheng-Liang** [usememos/memos#1914]
### Describe the bug

在memos网页自动刷新之后，有时会出现host的注册界面（之前已经注册过了），如果这个时候使用原来的host账号（用户名和密码）进行注册，那么这个用户名就会被重新占用，并且原本的memo全部消失了。

问题在于：
1.在已经注册有host的情况下，在网页刷新后却依然进入host注册界面
2.这次注册host能够使用之前已经注册的用户名

After the memos web page is automatically refreshed, sometimes the registration screen of host (which has been registered before) will appear. If the original host account (username and password) is used to register at this time, the username will be reoccupied and the original memo will all disappear.

The problem is:
1. In the case of already registered host, after the web page is refreshed, but still enter the host registration interface
2. This time, I can use the user name that I have already registered before to register the host.

### Steps to reproduce

1.在已经注册有host的情况下，在网页刷新后却依然进入host注册界面
2.这次注册host能够使用之前已经注册的用户名

1. In the case of already registered host, after the web page is refreshed, but still enter the host registration interface
2. This time, I can use the user name that I have already registered before to register the host.

**Comment by Yuansheng-Liang** [comment]
在进入host注册页面的时候，如果再多次刷新页面，会进入正常的登录界面

When you enter the host registration page, if you refresh the page several times again, you will enter the normal login screen

**Comment by Cyang39** [comment]
这个问题我之前因 #1911 也遇到过很多次，可以猜到问题出在 status 接口，简单地右键屏蔽该接口路径就能复现：
![image](https://github.com/usememos/memos/assets/11350270/25be0bfe-f0b3-4792-bdc3-9c167e1fe9c0)

**Comment by Yuansheng-Liang** [comment]
> 这个问题我之前因 #1911 也遇到过很多次，可以猜到问题出在 status 接口，简单地右键屏蔽该接口路径就能复现： ![image](https://user-images.githubusercontent.com/11350270/252133117-25be0bfe-f0b3-4792-bdc3-9c167e1fe9c0.png)

那应该就是注册校验的问题了，只有前端做了校验，服务端没做，结果被前端绕过了。

That should be the problem of registration checks, only the front end did the checks, the server did not do, the result was bypassed by the front end.
