### ISSUE TITLE
Username URLs instead of account number

### ISSUE THREAD

**Issue by jrbgit** [usememos/memos#1916]
### Is your feature request related to a problem?

It would be nice to have the url be /u/username instead of /u/1

### Describe the solution you'd like

Not sure if this is possible. my guess is it would need to be done on the 'server' and then possibly need some conf changes if it's running behind a reverse proxy like nginx

### Additional context

not a big issue - just a thought

**Comment by aatumaykin** [comment]
fixed to https://github.com/usememos/memos/pull/1977
