### ISSUE TITLE
Disable public memos

### ISSUE THREAD

**Issue by jrbgit** [usememos/memos#1917]
### Is your feature request related to a problem?

It seems like even though 'public messages' is disabled, any previous public messages are still visible. (this might be the correct way to do it. I'm not sure.)

But the real issue I am facing is that there are only 2 options for post visibility 

### Describe the solution you'd like

I would have thought that after disabling public messages that previous messages would no longer be public.

As for the real issue, there are 3 types of posts, Private/Member/Public
But the option available disables everyone's ability to post. The admin account can only post to all members, and users can only post private. So my only option is to leave public messages on if I want to allow my users to store both member visible and private messages. It seems like disabling public posts does more than it should. 

Option: Disable Public Posts (This should mean anyone can post private or member messages, previous public posts are no longer visible unless logged in.
Option: Enable member messages (This option is only available if public posts is disabled) Enabling this allows the admin and all users to post both member and private messages....

If keeping the admin account to only members, this wouldn't be an issue as I can then create a personal account for myself and only use the admin account for administrative messages.

**Comment by boojack** [comment]
`Disable Public Memos` will prevent regular users from saving public memos, but allow administrators to do so.
