### ISSUE TITLE
allow to make OpenAPI disable or enable for each user

### ISSUE THREAD

**Issue by Samanw** [usememos/memos#1921]
### Is your feature request related to a problem?

Hello is it possible to make OpenAPI disable or enable in setting

### Describe the solution you'd like

would be great if users can make OpenAPI of their own enable or disable

**Comment by boojack** [comment]
OpenID will be removed in the next version. The **access token** will be displayed in the UI. 

* A new access token will be created for each login operation. 
* User can manually create access tokens that will not expire to call the api.

<img width="781" alt="image" src="https://github.com/usememos/memos/assets/24653555/d3eddb45-f958-434d-bfc9-ec01af58320d">
