### ISSUE TITLE
Multi factor authentication - MFA

### ISSUE THREAD

**Issue by cakeseyboy** [usememos/memos#1922]
### Is your feature request related to a problem?

Request

### Describe the solution you'd like

Hello, I am loving this project! Are there any plans in the roadmap to add the ability to have multifactor authentication on the admin account? 

### Additional context

I currently have my memos instance behind Cloudflare zero trust but I would like to make it public so I can share memos publicly. Just need 2FA on my account! :)

**Comment by boojack** [comment]
Duplicated with https://github.com/usememos/memos/issues/984
