### ISSUE TITLE
Removing/deleting tags

### ISSUE THREAD

**Issue by jl-678** [usememos/memos#1926]
### Describe the bug

I have a post that has a URL that includes something like "https://www.foo.com#school". Memos automatically created a "school" tag for this, but I don't want that. Now, I edited the post to remove "#school" from the URL, but memos still shows the tag. 

I click the tag, and it takes me to another random and unrelated post. It shows "Filter: school" underneath, and I mouse over it and a strikethrough appears. When I click on the strikethrough, the post closes, and the tag still exists. The expected behavior is that the tag would be deleted.

This brings additional questions:

1. How do I delete a tag? Did I do something wrong?
2. Will deleting "school" from the tags table in the sqlite database address this problem?

TIA!

### Steps to reproduce

Described above. Add a tag to a post and wait for it to be autocreated. Remove the tag in the post and then try to remove the tag.

**Comment by jl-678** [comment]
This was a user error issue. Sorry. Instructions for deleting tags are here:
https://usememos.com/docs/faq#how-to-delete-old-tags

**Comment by esturniolo** [comment]
There is a chance to put the option to remove the tags in another friendly site?
I mean you need to click on "Add" (+) tag to delete one.
Thanks!
