### ISSUE TITLE
为什么不让配置其他数据库了？

### ISSUE THREAD

**Issue by zero5652pzj** [usememos/memos#1955]
### Describe the bug

现在使用的是默认的sqlite。在多端多台电脑上登录同一个帐号时，发现sqlite出现死锁现象。必须重启容器才能正常使用。

### Steps to reproduce

1. 使用同一个帐号登录；
2. 在电脑、移动端打开；
3. 使用第三个设备打开memos；
4. 会跳转到设置账号为管理员的页面。

**Comment by jkjoy** [comment]
跳转到设置账号为管理员的页面。这个问题经常遇到 清空缓存或许有用

**Comment by boojack** [comment]
> 为什么不让配置其他数据库了？

从来没有支持过其他类型数据库。

> 发现sqlite出现死锁现象

最新版本里有相关的优化。
