### ISSUE TITLE
cannot take note and cannot login again after quit

### ISSUE THREAD

**Issue by PeterYAN-hk** [usememos/memos#1962]
### Describe the bug

cannot take note and cannot login again after quit

### Steps to reproduce

use docker to deploy the latest version,
1. after take the second note, 
2. then modify it, 
3. save it, failed.
4. quit it
5. login again, failed.

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/131185126/cac20ec4-2317-499d-89c0-864df0819d61)

**Comment by zhr520v** [comment]
I'm having the same problem. I can't log in with a different browser.

**Comment by Batman313v** [comment]
I have gotten this to be pretty repeatable (At least with my setup) by Adding a tag that doesn't exist to a new note and adding it with ctrl+enter. This results in the note being added but on a page re-fresh it logs me out and goes to the setup page again. Restarting the Docker instance with `docker compose restart` fixes it until I do it again.
