### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by hanimedialab** [usememos/memos#1975]
### Describe the bug

I deployed memos in vercel. (https://simplememo.vercel.app)
But when I sign up, an error message appears "Request failed with status code 404".
I didn't edit any code.

How can I solve it?

### Steps to reproduce

1. Go to 'https://simplememo.vercel.com'

**Comment by Ajaykumbhare** [comment]
<img width="1260" alt="image" src="https://github.com/usememos/memos/assets/17526893/99f37541-eeb2-468a-8a55-e86be2d32f58">

I see DEPLOYMENT_NOT_FOUND, Could you please provide the detailed steps to reproduce?

**Comment by asadal** [comment]
Oh, could you check again '[](https://simplememo.vercel.app)'
I set the root directory to 'web' and got 'succeeded' message.
But when I create admin account, there is an error '404'.

How can I fix it, and how can I deploy memos to vercel?

**Comment by Ajaykumbhare** [comment]
I am not familiar with the Go language, so I am uncertain about how to deploy a server using it. Could you please review these options from the following link: https://usememos.com/docs/install/cloud

**Comment by boojack** [comment]
Vercel is mainly using to deploy static website which cannot run docker image.
