### ISSUE TITLE
偏好设置里提供编辑后是否更新笔记时间选项

### ISSUE THREAD

**Issue by shoreson** [usememos/memos#1976]
### Is your feature request related to a problem?

之前一直用的老版本，作为日记和工作记录使用的，再编辑后，时间也不会更新，比较符合我的用途，现在新版本默认更新了

### Describe the solution you'd like

希望能把这个功能单独出来，谢谢

**Comment by boojack** [comment]
Disable the following setting field.

<img width="1123" alt="image" src="https://github.com/usememos/memos/assets/24653555/8f1a3c10-f472-4d96-b5a1-4a471f3e43c7">
