### ISSUE TITLE
前端文件走CDN

### ISSUE THREAD

**Issue by earthjasonlin** [usememos/memos#1978]
### Is your feature request related to a problem?

无

### Describe the solution you'd like

可否让所有前端文件，js，css等直接走公共的cdn呢，比如jsdelivr等

**Comment by Cyang39** [comment]
项目本身就是前后端分离的，其实完全可以将前端独立出来的。作者这么没这么做的原因在于希望程序打包成单个可执行文件，对外部没有任何依赖，也包括无互联网的情况。所以前端文件走 CDN 违背了这一设计，不太可能会满足这个需求。

因为这个程序大多都是自己使用，浏览器本身会有缓存，对服务器、对流量的压力不大，对加载的速度影响也不大。如果真的需要很多人使用的话，考虑用 Cloudflare 的免费 CDN 加速也行。
