### ISSUE TITLE
最后一个资源不是图片时，资源库预览错误显示上一个资源文件

### ISSUE THREAD

**Issue by bfansheng** [usememos/memos#1990]
### Describe the bug

资源库中正常都是图片的情况下不会出现这个问题，但是最后一个文件不是图片（只尝试过.mp3和.txt）的情况会出现预览显示的是上一个资源的情况

### Steps to reproduce

1. 上传图片1和图片2
2. 再上传一个mp3文件
3. 点击预览图片2，发现显示的是图片1，资源请求的也是1
![异常](https://github.com/usememos/memos/assets/16935251/69013ad4-3ac1-4f1c-9a37-3add3abaa9b0)

### Screenshots or additional context

没上传mp3文件前：
![正常](https://github.com/usememos/memos/assets/16935251/1e5f2c73-0a4e-457e-9509-94b800b887b6)

**Comment by boojack** [comment]
Fixed in `v0.14.2`
