### ISSUE TITLE
[Bug] The server crashes when I search

### ISSUE THREAD

**Issue by eallion** [usememos/memos#1997]
### Describe the bug

The server crashes when I search, 100% sure.

### Steps to reproduce

To be more rigorous, I tested it 5 times, and each time the server crashed when I performed the search.

**Comment by NicoleRobin** [comment]
1、which version are you using
2、which serch are you using? the home search or the resource search 
3、can you provide some log when server creash
@eallion

**Comment by eallion** [comment]
Latest verison, home search.

**Comment by NicoleRobin** [comment]
i can't reproduced this issue use version:v0.14.1, pls provide more infomation and log. @eallion
