### ISSUE TITLE
Multi-level tag not rendered properly

### ISSUE THREAD

**Issue by skyue** [usememos/memos#2009]
### Describe the bug

如图，class="tag-span"的标签渲染不对，多级tag没有完全包含进来。
<img width="687" alt="image" src="https://github.com/usememos/memos/assets/10450242/1710aa84-b964-439f-9cb8-d18cd2c6a3d6">

### Steps to reproduce

null

**Comment by boojack** [comment]
Maybe related PR https://github.com/usememos/memos/pull/1974
