### ISSUE TITLE
visibility setting doesn't work

### ISSUE THREAD

**Issue by woshichenghaibo** [usememos/memos#2012]
### Describe the bug

Default memo visibility set to 
Public to everyone
but doesn't work....

### Steps to reproduce

every time

### Screenshots or additional context

![Screenshot_2023-07-23-08-04-11-862_mark via](https://github.com/usememos/memos/assets/80568737/baaf4a62-89f1-42d0-a0da-882efb6bf544)
![Screenshot_2023-07-23-08-04-19-219_mark via](https://github.com/usememos/memos/assets/80568737/7c30b791-caa3-4919-a4ec-1ffc7c61b2c0)

**Comment by tranquanghuy0801** [comment]
@woshichenghaibo I think when you have this setting, it only applies to the new memo instead of the existing ones

**Comment by woshichenghaibo** [comment]
新旧动态，一律不能生效。
________________________________
发件人: Harry Tran ***@***.***>
发送时间: 2023年7月24日 14:10
收件人: usememos/memos ***@***.***>
抄送: woshichenghaibo ***@***.***>; Mention ***@***.***>
主题: Re: [usememos/memos] visibility setting doesn't work (Issue #2012)


@woshichenghaibo<https://github.com/woshichenghaibo> I think when you have this setting, it only applies to the new memo instead of the existing ones

―
