### ISSUE TITLE
Wrong thumbnail in image attachment preview

### ISSUE THREAD

**Issue by NiklasRosenstein** [usememos/memos#2015]
### Describe the bug

I am encountering an issue where the first image attachment from a member is showing the thumbnail of the very first image attachment from another member. To clarify,

* the first memo that was created contains an image attachment and the preview is rendered as `<img src="https://memos.nr0.app/o/r/1?thumbnail=1" ...>`
* the second memo that was created (by another user, unsure if that's relevant) contains multiple image attachments where the first preview images of them is rendered as `<img src="https://memos.nr0.app/o/r/2?thumbnail=1" ...>`

When I manually change the `src` attribute in the Developer Console, it displays the correct thumbnail:

```diff
- <img src="https://memos.nr0.app/o/r/2?thumbnail=1" ...>
+ <img src="https://memos.nr0.app/o/r/2?thumbnail=2" ...>
```

*Edit*: I suppose that is a red herring because it appears not specifying the `thumbnail` parameter at all or giving it a gibberish value also returns the right image; probably the original attachment instead of a smaller thumbnail.

### Steps to reproduce

The bug I'm encountering happened in this scenario:

* User 1 creates a memo with one image attachment, then
* User 2 creates another memo with multiple image attachments

**Comment by boojack** [comment]
`thumbnail` is a parameter/flag to indicate whether a compressed image instead of the original one will be returned.

https://github.com/usememos/memos/blob/06dbd8731161245444f4b50f4f9ed267f7c3cf63/api/v1/resource.go#L383
