### ISSUE TITLE
Hashtag filter not working for certain tags

### ISSUE THREAD

**Issue by Ajaykumbhare** [usememos/memos#2016]
### Describe the bug

The hashTag filter is not functioning correctly on the home page when clicking on specific hashtags in the posts.

### Steps to reproduce

1. Go to the home page.
2. Add a new post with the content: "I love #apple and #banana! #fruit_lover."
3. Click on the save button to post the content.
4. Observe the timeline where the posts are displayed.
5. Click on #apple and #banana hashTags

### Screenshots or additional context

<img width="1158" alt="image" src="https://github.com/usememos/memos/assets/17526893/6c6b5f01-46e8-47b0-87bc-77707b95ccd7">

<img width="1158" alt="image" src="https://github.com/usememos/memos/assets/17526893/c8f676a9-7886-4026-86a5-08de58feaf73">

<img width="1158" alt="image" src="https://github.com/usememos/memos/assets/17526893/eab66bca-6af6-4d38-bfe0-10e9c7caaa73">

<img width="1158" alt="image" src="https://github.com/usememos/memos/assets/17526893/72d3331d-619c-4397-b16d-f8d846277326">

**Comment by gujin03** [comment]
same as https://github.com/usememos/memos/issues/2013
