### ISSUE TITLE
No OpenAI settings visible on fresh 0.14.1 install

### ISSUE THREAD

**Issue by eschack** [usememos/memos#2019]
### Describe the bug

I did a fresh docker-compose installation of 0.14.1, but dont see the Ask AI button or any options related to it in the settings.

### Steps to reproduce

1. Fresh installation (0.14.1) using the docker compose defaults
2. Observe no OpenAI settings visible anywhere

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/128665/c14bf7a9-0a17-42d5-8a65-bec992b5b8c0)

**Comment by earthjasonlin** [comment]
It's being reconstructed, will come back later

**Comment by boojack** [comment]
As our developers have limited time, memos needs to improve the usability of the main features first. So AI-related third-party features have been removed and will no longer be integrated.

**Comment by boojack** [comment]
@JokerQyou It looks like a bug. Please create a new issue for it.
