### ISSUE TITLE
[Feature Request] option to vacuum the sqlite database

### ISSUE THREAD

**Issue by DHS1001** [usememos/memos#202]
Is it possible to add the option to vacuum the sqlite database?
This function is useful when resource has been delete.
Thanks

**Comment by boojack** [comment]
How about just delete your `.db` file? And I want to know why you need to clean your database when deleting a resource.

**Comment by DHS1001** [comment]
> And I want to know why you need to clean your database when deleting a resource.

If, for example, a photo is removed from resource, the db size is not changed back. 
With the vacuum of the database, it will "rebuilds the database file, repacking it into a **minimal amount of disk space**".
[https://www.sqlite.org/lang_vacuum.html](https://www.sqlite.org/lang_vacuum.html)
