### ISSUE TITLE
docker升级最新的版本后，ios app提示未能读取数据，因为它的格式不正确

### ISSUE THREAD

**Issue by wangningyu** [usememos/memos#2020]
### Describe the bug

请教一下这个如何解决，不胜感激!
![IMG_9687](https://github.com/usememos/memos/assets/8290780/a385f8d2-97b1-4d40-83df-09dbb104a9ff)

ios app提示未能读取数据，因为它的格式不正确

### Steps to reproduce

打开app输入https url和登录均提示

**Comment by dianso** [comment]
第三方的一堆问题，别用就是了

web问题

你很搞笑，不去找这些所谓的第三方，来这里问

**Comment by wangningyu** [comment]
抱歉，打扰了，我以为那个app是官方的

**Comment by wangningyu** [comment]
I'm very sorry, I thought this was an official application. Please remove this issue

**Comment by boojack** [comment]
@wangningyu 如果问题还是存在的话，可以去这里提个 issue：https://github.com/mudkipme/MoeMemos
