### ISSUE TITLE
[feat] deleting archives on a regular basis

### ISSUE THREAD

**Issue by gujin03** [usememos/memos#2022]
### Is your feature request related to a problem?

Expect developers to add the feature of deleting archives on a regular basis, adding a parameter of 30 days to delete archives by default, when the user changes to 0 do not delete archives.

### Describe the solution you'd like

Expect developers to add the feature of deleting archives on a regular basis, adding a parameter of 30 days to delete archives by default, when the user changes to 0 do not delete archives.

**Comment by boojack** [comment]
If you want to delete it, do it manually yourself. Let's keep it simple.
