### ISSUE TITLE
Tags containing dash can't render properly

### ISSUE THREAD

**Issue by waterdrops** [usememos/memos#2024]
### Describe the bug

Tags containing dash can't render properly, 
for example
#rock-climbing  #day-trip

### Steps to reproduce

Null

### Screenshots or additional context

![CleanShot 2023-07-24 at 10 50 23](https://github.com/usememos/memos/assets/7233747/b5f719f9-7c3a-4ed3-b911-7e503a9b8b62)

**Comment by tranquanghuy0801** [comment]
This behavior is catched by this regex `/#((?:[^\s\p{P}]|_)+)/u`, and therefore you cannot use the hyphen in here. 
You can use the underscore instead eg: `#day_trip`, `#rock_climbing`

**Comment by waterdrops** [comment]
> This behavior is catched by this regex `/#((?:[^\s\p{P}]|_)+)/u`, and therefore you cannot use the hyphen in here. You can use the underscore instead eg: `#day_trip`, `#rock_climbing`

Thank you for your quick reply, @tranquanghuy0801. I have rolled back to the previous version(0.14.0) and I'm very happy it is working properly on v0.14.0. Here is a sample:
![v0.14.0](https://github.com/usememos/memos/assets/7233747/262e22f2-2e36-4105-b8af-36bc2df600ab)

**Comment by tranquanghuy0801** [comment]
@waterdrops  I believe we have this behaviour as we have this PR mered in version 0.14.1 https://github.com/usememos/memos/pull/1974

**Comment by waterdrops** [comment]
Thanks @tranquanghuy0801, I'll close this issue.

**Comment by tranquanghuy0801** [comment]
@waterdrops Sorry for annoying you, but the issue has not been closed yet

**Comment by waterdrops** [comment]
@tranquanghuy0801 You're very welcome, Let me share more info about this issue: 
I pulled the latest code and built an image using the main branch (PR #1974 has been merged into main), and tags with underscores can now render properly. However, tags containing hyphens are still not rendering correctly.

![CleanShot 2023-07-25 at 14 44 40](https://github.com/usememos/memos/assets/7233747/47c2b87e-6c1c-4049-936d-f7b925a61e8a)

**Comment by tranquanghuy0801** [comment]
@waterdrops I mean the PR #1974 exclude all chars in the tag name except for the underscore. So I think the output showed in your image is reasonable.

**Comment by waterdrops** [comment]
I'll close this issue, By the way, I was wondering if it would be possible to include hyphens in tags.

**Comment by tranquanghuy0801** [comment]
@waterdrops I would suggest adding your comment in that PR to ask the team why we need to do that

**Comment by stepech** [comment]
Hi, just found this issue on my instance too. It is quite unexpected behaviour, the change also doesn't seem to be very well rolled out, because now the filters by tag don't work at all (viz. screenshots) so all tags with dashes prior to 0.14.1 are not usable.

![image](https://github.com/usememos/memos/assets/29132060/0bd2c906-ca4f-4909-bbb0-3c94b37846e3)
![image](https://github.com/usememos/memos/assets/29132060/fca446b2-faaa-4c4c-9f6f-7475c991d848)
![image](https://github.com/usememos/memos/assets/29132060/72aa8123-859d-4e8f-b8b5-2c8629dad4f8)



I personally don't like the change, the support of the dashes was nice and (at least for me) expected feature.

**Comment by EgorBakanov** [comment]
> Hi, just found this issue on my instance too. It is quite unexpected behaviour, the change also doesn't seem to be very well rolled out, because now the filters by tag don't work at all (viz. screenshots) so all tags with dashes prior to 0.14.1 are not usable.

It can be related to #2027

**Comment by tranquanghuy0801** [comment]
Probably the question is for @boojack. Any reasons why we have the PR https://github.com/usememos/memos/pull/1974 as this one prevents rendering dashes in tags

**Comment by tranquanghuy0801** [comment]
This issue has been fixed in v0.14.2 https://github.com/usememos/memos/releases/tag/v0.14.2
