### ISSUE TITLE
The performance is poor

### ISSUE THREAD

**Issue by gujin03** [usememos/memos#2031]
### Describe the bug

![image](https://github.com/usememos/memos/assets/38389059/3fd82068-55f1-49d5-9f35-0f4ec72bb417)
last for 7 seconds
![image](https://github.com/usememos/memos/assets/38389059/d1459ed7-9e49-46f9-9086-5f3a0939ea07)

### Steps to reproduce

1.create a filter
2.click the filter

**Comment by boojack** [comment]
Shortcuts have been removed in the recent version.
