### ISSUE TITLE
How would it be happened when the zeabur's memos rebooted?

### ISSUE THREAD

**Issue by kezade** [usememos/memos#2038]
### Describe the bug

Yesterday, the service of memos deployed in zeabur was good. But when I open the web of memos, the version backs to the 0.12.2. And all datas of my memos can not reach. What's wrong with the memos in zeabur's version? Before the problem happended, my version is 0.14.1. Did the memos in zeabur market rollback? I can not understand. 

### Steps to reproduce

1. go to the zeabur's admin web
2. suspend the service of memos and reboot it.

### Screenshots or additional context

03:19terminated received.
03:19memos stopped properly
03:19---
03:19Server profile
03:19dsn: /var/opt/memos/memos_prod.db
03:19port: 5230
03:19mode: prod
03:19version: 0.12.2
03:19---
03:19███╗   ███╗███████╗███╗   ███╗ ██████╗ ███████╗
03:19████╗ ████║██╔════╝████╗ ████║██╔═══██╗██╔════╝
03:19██╔████╔██║█████╗  ██╔████╔██║██║   ██║███████╗
03:19██║╚██╔╝██║██╔══╝  ██║╚██╔╝██║██║   ██║╚════██║
03:19██║ ╚═╝ ██║███████╗██║ ╚═╝ ██║╚██████╔╝███████║
03:19╚═╝     ╚═╝╚══════╝╚═╝     ╚═╝ ╚═════╝ ╚══════╝
03:19Version 0.12.2 has started at :5230

**Comment by cxplay** [comment]
As far as I know zeabur doesn't provide data persistence support, so theoretically your "reboot" will probably be a "re-deploy", which will make you lose all your data. My advice is to ask zeabur for help.

**Comment by kezade** [comment]
> As far as I know zeabur doesn't provide data persistence support, so theoretically your "reboot" will probably be a "re-deploy", which will make you lose all your data. My advice is to ask zeabur for help.

so, where is the docker image of memos in zeabur from? who takes responsable for the maintaince of memos's version  in zeabur?

**Comment by cxplay** [comment]
> > As far as I know zeabur doesn't provide data persistence support, so theoretically your "reboot" will probably be a "re-deploy", which will make you lose all your data. My advice is to ask zeabur for help.
> 
> so, where is the docker image of memos in zeabur from? who takes responsable for the maintaince of memos's version in zeabur?

From the deployment templates used to known that: <https://dash.zeabur.com/templates/LPCVAH>
![image](https://github.com/usememos/memos/assets/62034099/91d1bf3c-8e3f-4da9-a5d3-f7df8af16c1b)

> @MichaelYuhe

He is Zeabur Co-Founder.

**Comment by MichaelYuhe** [comment]
We're working on a new solution for data storage. For now we can't provide data persistence support for memos, but services like MongoDB or MySQL can have a persistent storage. We use memos' official docker image, you can check here. https://github.com/zeabur/zeabur/blob/main/marketplace/memos.json
For the downgrade issue, please go to our Discord server for help.

**Comment by kezade** [comment]
> We're working on a new solution for data storage. For now we can't provide data persistence support for memos, but services like MongoDB or MySQL can have a persistent storage. We use memos' official docker image, you can check here. https://github.com/zeabur/zeabur/blob/main/marketplace/memos.json For the downgrade issue, please go to our Discord server for help.

3Q for your reply. So, when does the memos support RDB, like MySQL, or NoSQL, like MongoDB? Do your team have any plan or issue to develop?

**Comment by kezade** [comment]
> > > As far as I know zeabur doesn't provide data persistence support, so theoretically your "reboot" will probably be a "re-deploy", which will make you lose all your data. My advice is to ask zeabur for help.
> > 
> > 
> > so, where is the docker image of memos in zeabur from? who takes responsable for the maintaince of memos's version in zeabur?
> 
> From the deployment templates used to known that: https://dash.zeabur.com/templates/LPCVAH ![image](https://user-images.githubusercontent.com/62034099/257522226-91d1bf3c-8e3f-4da9-a5d3-f7df8af16c1b.png)
> 
> > @MichaelYuhe
> 
> He is Zeabur Co-Founder.

3Q for your reply. I didn't use the template to deploy memos in zeabur, but chose the one in Market. Are they the same?

**Comment by cxplay** [comment]
> 3Q for your reply. I didn't use the template to deploy memos in zeabur, but chose the one in Market. Are they the same?

IDK, you should look for it by yourself.
