### ISSUE TITLE
Wrong / no database size displayed in 0.14.2

### ISSUE THREAD

**Issue by raisinbear** [usememos/memos#2044]
### Describe the bug

Hi,

just migrated from 0.13.2 to 0.14.2. The size of the database under `System` -> `Settings` was roughly 30 MB in 0.13.2 and is now displayed to be `0 Bytes`. So far it seems like no data is missing, but it doesn't really give a trustworthy impression that the database state can't be fully fetched 😅
I tried a database cleanup and restart, still the size is `0`.

Also set up a new instance and uploaded some small files. Size is `0` as well.

### Steps to reproduce

1. Use minimalistic setup - only DB.
2. Have some data in your instance. Text / images, whatever.
3. Go to `Settings` -> `System`, observe DB size entry doesn't reflect actual size.

### Screenshots or additional context

![grafik](https://github.com/usememos/memos/assets/68740188/ac666b77-103f-49ba-ab75-b391f3043137)

**Comment by VlaK0r** [comment]
I have the same thing!

![image](https://github.com/usememos/memos/assets/77666575/10748490-50fc-431f-95dc-00edbbb79aba)
