### ISSUE TITLE
允许添加HTML标签 Allow add HTML tags

### ISSUE THREAD

**Issue by rong6** [usememos/memos#2066]
### Is your feature request related to a problem?

CN：
现阶段，如果直接输入HTML标签，会直接当做文本处理。

EN:
At this stage, if an HTML tag is entered directly, it is treated as text directly.

### Describe the solution you'd like

CN：
允许添加HTML标签，这样就可以实现例如iframe嵌入等操作。

EN:
Allows the addition of HTML tags so that operations such as iframe embedding can be implemented.

**Comment by yslemmo** [comment]
可以嵌入音乐播放器的话就很赞

**Comment by rong6** [comment]
> 可以嵌入音乐播放器的话就很赞

**Comment by rong6** [comment]
诶我去这issues怎么关了

**Comment by Vitotian** [comment]
参考:https://www.usememos.com/docs/getting-started/content-syntax#rendering-custom-html
