### ISSUE TITLE
After rebooting loses all memos

### ISSUE THREAD

**Issue by teocto** [usememos/memos#2068]
### Describe the bug

After rebooting loses all memos

### Steps to reproduce

1. Add docker-compose 
2. Reboot
3. Lose data

**Comment by ojoanalogo** [comment]
Hi @teocto, can you attach your docker-compose file?

**Comment by teocto** [comment]
> Hi @teocto, can you attach your docker-compose file?
Hi,
@Issues-translate-bot @ojoanalogo 
my docker-compose.yml file contains
version: "3.0"
services:
  memos:
    image: neosmemo/memos:latest
    container_name: memos
    volumes:
      - ~/.memos/:/var/opt/memos
    ports:
      - 5230:5230

**Comment by boojack** [comment]
Please provide more context, such as OS, memos version?

**Comment by letswritetw** [comment]
I'm using Windows 10 and installed using Docker:

```
docker run -d --name memos -p 8503:5230 -v ~/.memos/:/var/opt/memos ghcr.io/usememos/memos:latest
```

When I restarted Docker Desktop, I would encounter the same problem. All the previous records were gone and my account had to be re-registered.

memos verson：0.16.0
