### ISSUE TITLE
feat(telegram): Support Telegram Channel

### ISSUE THREAD

**Issue by qazxcdswe123** [usememos/memos#2070]
### Is your feature request related to a problem?

Read message from channel as a way to support multiple telegram user

closes: https://github.com/usememos/memos/issues/1906

### Describe the solution you'd like

I'm interested in working on adding this feature, but I want to make sure it aligns with the project's goals before implementing it.

Once I receive approval from the maintainer, I will begin working on implementing this feature.

Details

- Backend: Check if message is `channel_post`. Should only continue when the channel name match
    - If so, send api request to memos (and I'm not sure if button to change visibility is going to work on channel or not)
    - If not, reply to user as is

- Frontend:
  - Add channel name option

**Comment by boojack** [comment]
Please go ahead. If you have any questions about the implementation, you can ask some helps from @athurg.

**Comment by qazxcdswe123** [comment]
Update:

I managed to support channel post, however, there is not such `userid` in channel, the only identifier will be the channel name, which leads to another kv pair (key: `telegram-channel-name`) in table `user_setting`

**Comment by boojack** [comment]
> the only identifier will be the channel name

It might be better to put it into system setting instead of user setting.

**Comment by qazxcdswe123** [comment]
> > the only identifier will be the channel name
> 
> It might be better to put it into system setting instead of user setting.

Hi

Currently the `telegram-user-id` is stored in `user_setting`, so I think putting them in the same table would be more aligned with the current implementation?
