### ISSUE TITLE
Hope to support markdown's mathematical formula rendering

### ISSUE THREAD

**Issue by mch-anmc** [usememos/memos#2075]
### Is your feature request related to a problem?

Occasionally, I think of a formula and want to write it down immediately, but this markdown does not support mathematical formula rendering.

### Describe the solution you'd like

Hope to support markdown's mathematical formula rendering

**Comment by nalderto** [comment]
@mch-anmc Memos [supports](https://www.usememos.com/docs/getting-started/content-syntax) LaTeX syntax now, so I think this issue can be closed now.
