### ISSUE TITLE
#explore

### ISSUE THREAD

**Issue by lianj-141** [usememos/memos#2087]
### Describe the bug

The content visible to logged-in users is no longer visible in #explore. Currently, only public content can be seen.

### Steps to reproduce

1. User 1 publishes content visible to friends.
2. User 2 cannot see it in #explore.

**Comment by lianj-141** [comment]
When deploying and updating to version v0.14.3 using Docker, I encountered some issues.

**Comment by boojack** [comment]
Cannot reproduce. https://demo.usememos.com/explore

<img width="1012" alt="image" src="https://github.com/usememos/memos/assets/24653555/b24b70dd-8909-4fcf-aac8-3b0fd1160e67">
