### ISSUE TITLE
[feat] Input Labels friendly

### ISSUE THREAD

**Issue by gujin03** [usememos/memos#2097]
### Is your feature request related to a problem?

We hope to further optimize this. Currently, after the label window is displayed, you need to click the mouse to select the label. 

### Describe the solution you'd like

Thank you for adding the tag association feature.  @maciej-ka 

The logic to be optimized is as follows:
1. If there is only one matching tag, press Enter or Tab to enter the tag.
2. If there are multiple labels, press the up and down keys on the keyboard to select labels and then press Enter.

**Comment by rpishgithub** [comment]
I posted the same FR(https://github.com/usememos/memos/issues/2111) in the hope that case insensitive would also be supported, which would make the whole experience infinitely closer to flomo.

**Comment by maciej-ka** [comment]
@gujin03 I started working on it. It would help me if you could:
1. visit ticket https://github.com/usememos/memos/pull/2126
2. suggest answers to functionality questions (todo items starting with "decide")

**Comment by gujin03** [comment]
v0.15.0 is good
