### ISSUE TITLE
caddy反向代理无法访问静态资源

### ISSUE THREAD

**Issue by jaychoubaby** [usememos/memos#2099]
### Describe the bug

我是用caddy反向代理，提示静态资源404

### Steps to reproduce

1.docker部署成功，ip可以正常访问
2.caddy反向代理配置如下：
`reverse_proxy /blog http://ip:5230 {
        header_up Host {http.request.host}
        header_up X-Forwarded-Proto {http.request.scheme}
}`
3.访问  https://ip/blog,报错如下：
![image](https://github.com/usememos/memos/assets/26641387/140442c6-552f-41b5-9821-89efc20ccd5a)

**Comment by yoghurtlee-thu** [comment]
想问一下最后是怎么解决的呢？

**Comment by jaychoubaby** [comment]
> 想问一下最后是怎么解决的呢？

新开了子域名，重写了指向

**Comment by jaychoubaby** [comment]
> @jaychoubaby  你好，我现在也是出现这个问题，想请教一下这个问题你最后怎么解决的
> 
> <img width="1026" height="512" alt="Image" src="https://github.com/user-attachments/assets/5d9de36e-3ec0-4eca-92d2-0bc03e18fb23" />

用子域名就可以了

**Comment by ufxelv80** [comment]
> > [@jaychoubaby](https://github.com/jaychoubaby)  你好，我现在也出现这个问题，想请教一下这个问题你最后怎么解决的
> > <img alt="图像" width="1026" height="512" src="https://private-user-images.githubusercontent.com/120778315/483477458-5d9de36e-3ec0-4eca-92d2-0bc03e18fb23.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY0NTA2NTAsIm5iZiI6MTc1NjQ1MDM1MCwicGF0aCI6Ii8xMjA3NzgzMTUvNDgzNDc3NDU4LTVkOWRlMzZlLTNlYzAtNGVjYS05MmQyLTBiYzAzZTE4ZmIyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyOVQwNjUyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDAyMDFjNTNkZGY1NDljMWUzZTBhZWNhMjNhZjAwNTMzMzE4N2FiMWRlZWJkYTdhMWVjZDBkZjQ1ZjcyODk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gZmBwjNJS9jmGD0yHjO-MFXeuQKRcGNcd3WtNAgqwQs">
> 
> 使用子域名就可以了

可以给个具体的配置例子吗？谢谢！！！
