### ISSUE TITLE
memos是否提供自定义脚本使用的钩子事件？

### ISSUE THREAD

**Issue by iampcfox** [usememos/memos#2103]
### Describe the bug

自定义脚本处理的时候会用到url判断，我尝试了onhashchange，但没有作用，现在只能用定时器来代替，但觉得这样写不太优雅，所以想知道memos有没有暴露什么api、生命周期之类的钩子事件。

### Steps to reproduce

以上为问题

**Comment by FxPixels** [comment]
translate: Does memos provide hook events for custom scripts?
