### ISSUE TITLE
Is the memos heat map color inverted?

### ISSUE THREAD

**Issue by dwong33** [usememos/memos#2104]
### Describe the bug

Thank you for bringing such a good tool to the community.

When I am using memos, I realize the activity heat map color is different from intuition, as shown below, the more the activities, the dimmer the color. In github (as captured below) and other platforms, the setting is different, more activities, the brighter the color it is.

Is this a bug, or a feature only in memos?

Memos:
<img width="174" alt="image" src="https://github.com/usememos/memos/assets/12155059/f3262cab-9f64-47c7-93ec-6630baaac829">

Github:
<img width="546" alt="image" src="https://github.com/usememos/memos/assets/12155059/2eb3f4ba-65e3-4aa5-82df-7f0c7eec50b0">

### Steps to reproduce

Normal usage
It happened in both bright and dark mode.

**Comment by jxpsert** [comment]
Yeah, that sounds like either a bug or a weird (?) design choice. Either way, I support turning this the other way around.

**Comment by diomed** [comment]
it's definitely a bug

because brighter something is, more life is in it, dimmer it is, life goes out. so this should be fixed.

**Comment by jxpsert** [comment]
Anyone feeling like fixing this: ``web/src/less/usage-heat-map.less`` line 13 to 27.

**Comment by Bodyes26** [comment]
fixed in my PR
