### ISSUE TITLE
不能正确显示”展开“选项

### ISSUE THREAD

**Issue by bfansheng** [usememos/memos#2112]
### Describe the bug

界面上显示的，展开按钮没有正确出现
![image](https://github.com/usememos/memos/assets/16935251/4165eb43-90c2-4288-9ee1-9dc56ae1acb5)

实际内容：
![image](https://github.com/usememos/memos/assets/16935251/34a0ddbf-ed61-4204-a317-a35645ff5299)

### Steps to reproduce

1. 增加12行内容
2. 展开按钮未出现

**Comment by sprite82y** [comment]
我还是倾向于把这折叠功能交给用户自己选择 （https://github.com/usememos/memos/wiki/Tips）
自动折叠的位置经常不是我想要的

**Comment by xxzj990** [comment]
我在v0.14.4遇到了同样的问题
