### ISSUE TITLE
Clicking on tag does not show all results sporadically

### ISSUE THREAD

**Issue by skyrunner15** [usememos/memos#2114]
### Describe the bug

v0.14.3
I have a small number of notes but when I click the tag, it's spotty at displaying all records. Sometimes I get blanks, or if I click between tags, then I get the full set of records... (This happens locally or over https).

### Steps to reproduce
Using Google Chrome on Windows 11. Cleared all cache, cookies, etc.
1. Go to tags on the right hand side of the main page
2. Click tag
3. A few results show up, along with some "blank" boxes
4. Click a different tag
5. All results show
6. Click original tag from step 2 - then all results may show

### Screenshots or additional context

![memos tag issue](https://github.com/usememos/memos/assets/54626606/4c6ebd88-a4e8-49d6-84d9-cc25dd5b348c)
![server log](https://github.com/usememos/memos/assets/54626606/bf757f4b-8782-4d99-b872-cfd0f4af72c9)

**Comment by skyrunner15** [comment]
I was able to replicate this on multiple docker instances with Edge and Chrome browsers.

**Comment by bfansheng** [comment]
我也遇到了同样的问题

**Comment by daydaya** [comment]
meto
