### ISSUE TITLE
请问5231端口是什么作用？源代码中没搜到关于5231的信息

### ISSUE THREAD

**Issue by xtay573269555** [usememos/memos#2119]
您好，请问5231端口是什么作用？源代码中没搜到关于5231的信息。

我使用docker的 --network host 方式部署 memos 时发现 memos 同时监听了 5230 和 5231 端口。但不知道这个 5231 端口是什么作用，在源代码和介绍中也没搜索到5231端口相关的信息。是否有配置可以不启用该端口的监听？

<img width="573" alt="pic_20230810173628" src="https://github.com/usememos/memos/assets/5844466/0d3d5a2d-4695-439b-a3cf-3a59dc7925c1">

**Comment by boojack** [comment]
The port of gRPC server.

https://github.com/usememos/memos/blob/main/server/server.go#L124
