### ISSUE TITLE
cannot refresh on mobile app (无法刷新）

### ISSUE THREAD

**Issue by kakarukeys** [usememos/memos#2121]
### Describe the bug

v0.14.3
If a user uses both the desktop browser and mobile app (not mobile browser) to open memos, an update on desktop cannot be pushed to mobile app, because there is no refresh function on mobile app and memos is not real-time.

### Steps to reproduce

1. Install mobile app by opening memos website on mobile browser, clicking on the sharing icon on Safari, and select "Add to Home Screen" (iPhone)
2. Click the mobile app icon to open memos and sign in.
3. Edit a memo on homepage on desktop browser.
4. There is no way to refresh on the mobile app, there is no server push to send the update and swipe-down doesn't work. The mobile app will show the memo before edit.

### Screenshots or additional context

[mobile app1](https://plik.kakarukeys.quest/file/iInYCrhv7kr5eA3Q/eyTxWIqH7uD2ApiY/IMG_1329.png)
[mobile app2](https://plik.kakarukeys.quest/file/iInYCrhv7kr5eA3Q/ABdbULPd9SEslsv2/IMG_1328.png)

**Comment by ligusx** [comment]
I am the same, v0.14.3 version, two computers access memos, the content is out of sync

**Comment by ligusx** [comment]
解决了，我这情况是缓存时间设置的太长了

**Comment by boojack** [comment]
> mobile app (not mobile browser)

Please create an issue in the mobile app you use.

**Comment by kakarukeys** [comment]
> 解决了，我这情况是缓存时间设置的太长了
缓存时间在哪设？

> > mobile app (not mobile browser)
> 
> Please create an issue in the mobile app you use.
memos does not have a dedicated mobile app project, only this project.

**Comment by kakarukeys** [comment]
@boojack I am not sure if I understand you. **You have closed my bug report**, but the bug still exists. Not a good idea.

You have asked me to *"create an issue in the mobile app you use"*.
I've added a self-hosted memos website as an app, using iPhone "Add to Home Screen".
I am not using any 3rd party mobile app client.

I cannot find any official mobile app project page under @usememos
If there is one, please point me to there, I will create an issue there.
