### ISSUE TITLE
live demo is breaking

### ISSUE THREAD

**Issue by wbxl2000** [usememos/memos#2122]
### Describe the bug

<img width="1390" alt="image" src="https://github.com/usememos/memos/assets/57169560/a4b66c28-2f6a-42ce-8906-e7ec65a55a84">

### Steps to reproduce

https://demo.usememos.com/

**Comment by igxlin** [comment]
Look like it is an issue of Cloudflare instead of the demo server. Open the website again. I think it may be fixed. :see_no_evil:

**Comment by wbxl2000** [comment]
It is working now, cool
