### ISSUE TITLE
Starting memos with docker and failed with error

### ISSUE THREAD

**Issue by JonathanLiii** [usememos/memos#2125]
### Describe the bug

When I try to use docker image to start memos, cannot start with this error:
<img width="1125" alt="image" src="https://github.com/usememos/memos/assets/97082046/f5f8a9f7-84d8-4a10-a3a6-873cb74a9f19">

This is my docker-compose file:
<img width="501" alt="image" src="https://github.com/usememos/memos/assets/97082046/f8dc17a7-1f9b-4813-8211-6acb5d875182">

### Steps to reproduce

Follow the document to run memos

**Comment by kakarukeys** [comment]
I am running the latest memos with docker and have no issue. This is likely due to the problem on your setup.
note the error: disk I/O error.

**Comment by boojack** [comment]
> I am running the latest memos with docker and have no issue. This is likely due to the problem on your setup.

Agree with @kakarukeys. Feel free to provide more detail context about this issue.
