### ISSUE TITLE
Base Url Installation Support / 二级目录安装支持 and my partial workaround

### ISSUE THREAD

**Issue by sulisu** [usememos/memos#2129]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Please add suppport for base url when possible. So Memos can run from a base url such as:

https://www.acme.com/private/memos/

### Additional context

mode: prod
version: 0.14.3

Run from windows binary directly.

Now ,I managed to make a partial workaround with Caddy2(replace plugin)

Web client works with some little problem, while 3rd party app can not login.

My reverse proxy config for memos 

```
  redir /{Base Url}       /{Base Url}/       301

  route /{Base Url}/* {
    uri strip_prefix /{Base Url}
    replace {
      "/assets/" "/{Base Url}/assets/"
      "/api/" "/{Base Url}/api/"
      "\"assets/" "\"{Base Url}/assets/"
      "\"/auth" "\"/{Base Url}/auth"
      "\"/manifest.json" "\"/{Base Url}/manifest.json"
      "\"/logo.webp" "\"/{Base Url}/logo.webp"
      "o/r" "{Base Url}/o/r"
      "href=\"/\"" "href=\"/{Base Url}\""
      "register(\"/" "register(\"/{Base Url}/"
    }
    reverse_proxy {memos server ip}:{port} {
      header_up X-Script-Name /{Base Url}
      header_up Accept-Encoding identity

    }
  }

```

**Comment by dianso** [comment]
nginx 反向代理就行

我就是把50000端口反代到a.com/memos

**Comment by sulisu** [comment]
> nginx 反向代理就行
> 
> 我就是把50000端口反代到a.com/memos

nginx和memos都是默认配置，不需要特殊配置吗？

因为我看http往返内容，如果不在反向代理上对response内容替换字符串添加baseurl，返回的进一步访问请求都是域名后面直接跟memos自身路径比如/assets，不带baseurl的。因为我在caddy2上配置了过滤，不是baseurl路径下的访问请求全部401。如果不配置替换，在chrome的开发者工具下，是会看到第一个带baseurl的访问之后，后面的访问请求都没有baseurl，而且全部被caddy2返回401拒绝（是caddy2返回的，不是memos返回的）。

您可以试下，如果在nginx下配置了访问策略，只允许hostname:50000/memos路径访问，对hostname:50000/assets这样的访问全部拒绝，是不是还能正常访问。

**Comment by dianso** [comment]
晚上我试试吧，我用的倒是没问题，没用docker，直接是二进制运行

**Comment by bfahrenfort** [comment]
Also unable to get memos working in a subdirectory like `my-domain.com/memos`. `memos.my-domain.com` works just fine for now, but this requires another DNS record pointing `memos.my-domain.com` to the IP of my server.

**Comment by boojack** [comment]
> `memos.my-domain.com` works just fine for now

I recommend this as standard usage.

**Comment by kolserdav** [comment]
> > `memos.my-domain.com` works just fine for now
> 
> I recommend this as standard usage.

This is not a good solution. For example, I don't want everyone to have access to my public notes list. But anyone can scan the subdomain list and get access to public notes and the `memos` login panel.

**Comment by sulisu** [comment]
> [@boojack](https://github.com/boojack) You only think about yourself, how you feel comfortable. Look at how many people need this solution. For example, I'm trying to deploy memos on a local network accessible via VPN. Where did you find the subdomain on the local network?

How do you access this memos server on local network? local domain name or ip address, if ip address is used, you can define a second ip on the server nic, and use this ip to access memos without base url.

**Comment by sulisu** [comment]
I don't use k3s, but I guess you use 192.168.0.200 as app gateway, and want to use app route to access app behind the gateway and you want to run service on standard http port such as 443 or 80?

Do you have some restriction on the LAN that clients are allowed to access certain ip and port only? If not, why not just assign another ip address to the k3s server, such as 192.168.0.201. Bind the Memos server with this ip address side to side with the 192.168.0.200 gateway as if you installed memos on a standalone server. I think in most cases the client side won't notice the difference. Each ip bind to same interface has its own port pool, so you can use 443 or 80 port too.

I opened this issue because I don't know at that time that I can get a free wildcard cert for my internet domain name and my dns hosting provider supports wildcard domain name resolving. Now I don't bother to setup base url for my self-hosting services anymore.

> [@sulisu](https://github.com/sulisu) I use my k3s's 192.168.0.200 ip with custom SSL certs to connect to services like /grafana, etc. For now I go with https://192.168.0.200:8080 for memos instance as the only solution

**Comment by rewhex** [comment]
> why not just assign another ip address to the k3s server

Because it's a pain to update a self signed certificate and reinstall it all across devices:
Router, cluster nodes with services that use it, all clients devices including Android, iOS, windows and macos, some raspberry pi's. Right now I don't need to update the address list every time I change something on my server.
