### ISSUE TITLE
Excalidraw integration

### ISSUE THREAD

**Issue by gal064** [usememos/memos#2133]
### Is your feature request related to a problem?

Ability to add free style drawings to notes (ideally embedded, but if not as attachments)

### Describe the solution you'd like

Excalidraw integration that allows to add drawings, edit them, etc..

**Comment by neliets** [comment]
> Would be cool to support also a self hosted Excalidraw.

I assume this would be integrated in the docker image. Similar to bunch of other apps like Logseq etc. Shouldn't bloat it too much.

**Comment by helmut72** [comment]
> > Would be cool to support also a self hosted Excalidraw.
> 
> I assume this would be integrated in the docker image. Similar to bunch of other apps like Logseq etc. Shouldn't bloat it too much.

An URL to a Excalidraw instance (cloud or self-hosted) is the normal way. A container isn't a VM. One container, one process (plus chillds).
