### ISSUE TITLE
Add comment function

### ISSUE THREAD

**Issue by rong6** [usememos/memos#2137]
### Is your feature request related to a problem?

CN：
没有评论功能。

EN：
No comment function.

### Describe the solution you'd like

CN：
添加评论功能，游客也可以进行评论（只要输入名称、邮箱等信息即可）。

EN：
Add a comment feature so that visitors can comment as well (just enter name, email, etc.).

**Comment by klsdfjo** [comment]
I also want this comment function, I am very eager

**Comment by wbfz89** [comment]
同样渴望，毕竟如果开放使用，基本的评论和点赞都是必须的

**Comment by grand-lotus-iroh** [comment]
I share the same sentiment and would also appreciate the addition of this feature. Maybe consider incorporating a toggle checkbox in the options menu to enable comments. and / or emoji reactions, akin to how they work in GitHub issues.

**Comment by boojack** [comment]
See more in #820
