### ISSUE TITLE
toggleable memos ordering (just two is enough)

### ISSUE THREAD

**Issue by Oaklight** [usememos/memos#2140]
### Is your feature request related to a problem?

Thanks for building the memos app!
People who use memos as (journal-like) notebooks may frequently head back to edit the memo note. Current default ordering (updated time descending) messes up the sequence. @Zeng1998 @boojack 

### Describe the solution you'd like

It would be very helpful to have at least these two options in memos ordering:
- by creation time
- by updated time (the default at 0.14.4)
it would be even nicer if double-clicking on the ordering criteria would toggle ascending/descending by that criteria.

### Additional context

It was brought up in #966 once

**Comment by boojack** [comment]
@Oaklight You can enable this setting item to order data by updated time. (Default should be ordering by created time)

<img width="1090" alt="image" src="https://github.com/usememos/memos/assets/24653555/a215152f-707e-42ac-abf6-6ead5a9e403e">
