### ISSUE TITLE
I suggest that you add the function of uploading pictures to the picture bed

### ISSUE THREAD

**Issue by Robert-Stackflow** [usememos/memos#2141]
### Is your feature request related to a problem?

- When I want to change my avatar, I can only choose to upload an image instead of entering an image link as my avatar
- When I upload a resource, such as an image, it can only be uploaded to the server. But due to the low bandwidth of my server, the images load slowly when I visit the website. I would appreciate it if you could add the ability to upload pictures to the image bed.

### Describe the solution you'd like

- For my first suggestion: By using the v1 version of the api, I saw that when uploading the avatar locally, the avatarURL field will be the base64 encoding of the picture, and the avatarURL field can be directly modified into a picture link through the api. Then directly adding an option to enter a picture link in the web can solve this requirement.
- For my second suggestion: I think you can refer to the solution of Typora software - use the open source PicGo software. Here is the warehouse address: [https://github.com/Molunerfinn/PicGo](PicGo)

Thanks for checking out my suggestions while you're busy！

**Comment by lucumt** [comment]
@Robert-Stackflow 突然间发现你的博客很炫！
