### ISSUE TITLE
Excuse me, direct connection mp3 and mp4 with external link inserted cannot be played

### ISSUE THREAD

**Issue by langvs** [usememos/memos#2143]
### Describe the bug

Excuse me, direct connection mp3 and mp4 with external link inserted cannot be played, how can I solve this problem.

### Steps to reproduce

Use Add Media as normal
![QQ图片20230816024153](https://github.com/usememos/memos/assets/55701615/baf5a259-23bd-47dd-b844-0478e549638b)

### Screenshots or additional context

![QQ图片20230816023328](https://github.com/usememos/memos/assets/55701615/1e6763e4-a00c-4422-982c-d32508765056)

![QQ图片20230816023438](https://github.com/usememos/memos/assets/55701615/2aae891e-613a-428f-845e-9f3caec68601)
![QQ图片20230816023403](https://github.com/usememos/memos/assets/55701615/6bf3d523-0bc6-48af-8e23-074e676565a1)

**Comment by Zeng1998** [comment]
Does your memo site run with HTTPS ?

**Comment by langvs** [comment]
Using nginx anti proxy and enabling SSL certificate. However, the direct link address is a list program for onedrive! This direct link address works well in other programs~

**Comment by Zeng1998** [comment]
It seems that the html tags audio and video do not support the file types of `audio/*` and `video/*`. That should be fixed by specifying the specific type.

**Comment by Zeng1998** [comment]
I think an auto detection for file types would be great.

**Comment by boojack** [comment]
Fixed in https://github.com/usememos/memos/commit/73980e9644dd3978753328912f7c454a3f45cd67

**Comment by amirasyraf** [comment]
What happened to this "Create Resource" feature? I don't see it anywhere in latest 0.24.2
