### ISSUE TITLE
Low loading speed in Safari (iOS, macOS)

### ISSUE THREAD

**Issue by miroslavbucek** [usememos/memos#2144]
### Describe the bug

The problem is that images load 2x in Safari.

<img width="274" alt="Snímek obrazovky 2023-08-15 v 21 57 51" src="https://github.com/usememos/memos/assets/2242078/da4c4084-d153-4d8b-80e5-e592bd9e2422">

### Steps to reproduce

The problem only occurs in Safari, in Chrome the loading is fast and the image loads them once.

**Comment by boojack** [comment]
> The problem only occurs in Safari, in Chrome the loading is fast and the image loads them once.

As you said, I think this may be a problem with Safari. However, if you get any relevant optimization guides, please show them to us.
