### ISSUE TITLE
The height  of operate dialog in "Create SSO" page is too big,would be better to reduce it

### ISSUE THREAD

**Issue by lucumt** [usememos/memos#2146]
### Is your feature request related to a problem?

After login into `memos`,click `Settings` -> `SSO` -> `Create`,it will show a dialog as below, the height is big thus the scroll bar appears,and it's very hard to read and input,we need to scroll the page
![image](https://github.com/usememos/memos/assets/5226038/1a90e73f-be17-40df-a8ca-0127f2cbb623)

### Describe the solution you'd like

I think it would be better to has multiple columns  in each row to display it ,so that we can not need to scroll the page and can view all form components.

**Comment by boojack** [comment]
Great point! SSO is a feature under beta and ensuring its usability is more important. But at this stage, we don't have time to update the UI.

**Comment by lucumt** [comment]
@boojack  So if someone make a PR for it,is it accessiable now?

**Comment by boojack** [comment]
@lucumt Of course, maybe we can discuss your ideas first in this issue, such as the general UI.

**Comment by lucumt** [comment]
@boojack I had created a sample page at [https://jsfiddle.net/gncz53wu/](https://jsfiddle.net/gncz53wu/), you can check it further.

Below is the comparsion page to show the origin page and what I want to update for
![memos_create_sso_page](https://github.com/usememos/memos/assets/5226038/da1584dc-b0b3-43af-82d0-512e0e55cb31)

**Comment by lucumt** [comment]
@boojack I had created a sample page at [https://jsfiddle.net/gncz53wu/](https://jsfiddle.net/gncz53wu/), you can check it further.

Below is the comparsion page to show the origin page and what I want to update for
![memos_create_sso_page](https://github.com/usememos/memos/assets/5226038/da1584dc-b0b3-43af-82d0-512e0e55cb31)

**Comment by boojack** [comment]
@lucumt LGTM, and please keep an eye out for responsible styles in mobiles.

**Comment by lucumt** [comment]
@boojack It's memos support responsible styles in mobiles now?

**Comment by boojack** [comment]
@lucumt 

| PC | Mobile |
|--------|--------|
| ![image](https://github.com/usememos/memos/assets/24653555/eef77a8b-8af7-4434-8d07-ccd37615fce6) | ![image](https://github.com/usememos/memos/assets/24653555/c2f88bf7-87ab-489f-a9b6-4e254177d349) |

**Comment by MehadND** [comment]
@boojack If anyone is not tackling this then please assign this to me. I would like to work on this.

**Comment by MehadND** [comment]
@boojack I made a PR related to this. Please take a look at it. Thanks
