### ISSUE TITLE
当一个标签的内容全部删完之后，右侧栏和输入框位置的标签还存在

### ISSUE THREAD

**Issue by jhk5263** [usememos/memos#2148]
### Describe the bug

当一个标签的内容全部删完之后，右侧栏和输入框位置的标签还存在
![e86cf994-e9a0-4e89-ae62-c7d652885d66](https://github.com/usememos/memos/assets/71970354/34bb60d4-da86-4ee8-8585-8b382580f876)

写成标签所属下的内容没有的时候，标签就删除掉合理点

或者单独设置个可以清除的地方，一些废弃的标签才好清掉不会台冗长

### Steps to reproduce

当一个标签的内容全部删完之后，右侧栏和输入框位置的标签还存在

**Comment by sulisu** [comment]
这好像是一个feature，不是bug。

tag虽然可以随条目自动创建，但是是独立存在的。

点击右侧栏Tags旁边的加号，在Create Tag对话框下方有All Tags，把鼠标放到某个tag上，这个tag上会出现删除线，点击就删除了。

**Comment by boojack** [comment]
Just like @sulisu said.
