### ISSUE TITLE
安卓版的moe memos客户端连接V0.14.2无法连接

### ISSUE THREAD

**Issue by rdhhb0513** [usememos/memos#2158]
### Describe the bug

安卓版的moe memos客户端，在连接V0.14.2版本时无法连接，请开发的高手帮忙排查一下，用网页版没有问题，
我退回到V0.13.1，这个版本是好用的

### Steps to reproduce

安卓版的moe memos客户端，在连接V0.14.2版本时无法连接，请开发的高手帮忙排查一下，用网页版没有问题，
我退回到V0.13.1，这个版本是好用的

**Comment by aholeye** [comment]
提供一下MoeMemos客户端的版本号。另外，无法连接是指登录无响应吗？

**Comment by dianso** [comment]
这家伙天天出问题，又不开源，去找作者修复啊，来这里干什么。

**Comment by rdhhb0513** [comment]
我返回到0.13.1了。可以用😂😂



胡宏博
手机：13160360686
邮箱：  ***@***.***




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月26日 15:06 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [usememos/memos] 安卓版的moe memos客户端连接V0.14.2无法连接 (Issue #2158) |

这家伙天天出问题，又不开源，去找作者修复啊，来这里干什么。

**Comment by boojack** [comment]
> 这家伙天天出问题，又不开源，去找作者修复啊，来这里干什么。

Moe Memos 也是开源的 https://memos.moe

遇到相关的问题可以直接去提 issue。
