### ISSUE TITLE
建议使用 ProseMirror 替换 textarea

### ISSUE THREAD

**Issue by ChasLui** [usememos/memos#216]
1. flomo 的编辑器也是使用的 ProseMirror
2. 方便未来扩展基于 yjs 实现实时协同
3. 天然的对 markdown 支持友好
4. 有比较好的生态,非常容易能实现 list 等功能

**Comment by ChasLui** [comment]
基于 ProseMirror 还有一个比较好的 React 组件封装: https://github.com/remirror/remirror

**Comment by boojack** [comment]
我对于编辑器上的想法是：纯文本输入框 + 实现部分常用的 Markdown 语法，但 [ProseMirror](https://prosemirror.net/) 看上去是一个富文本编辑器 ，要不还是极简为主吧🤔️。

现在的纯文本编辑器属于可用的状态，我觉得可以对 markdown 语法相关的解析再做优化，可能会比完全换成 rich editor 更好一点。
