### ISSUE TITLE
代码里面有 - [ ]  后面的todo，点击顺序会混乱

### ISSUE THREAD

**Issue by toou1234** [usememos/memos#2160]
### Describe the bug

![Snipaste_2023-08-21_16-27-08](https://github.com/usememos/memos/assets/32186783/a1dbdb9d-e074-4333-a65a-1983425a1763)
![Snipaste_2023-08-21_16-23-55](https://github.com/usememos/memos/assets/32186783/bad168c4-1909-48b9-aa26-e95386b870d3)

### Steps to reproduce

版本：v0.14.3

**Comment by boojack** [comment]
Fixed in `0.18.2`.
