### ISSUE TITLE
Data encryption

### ISSUE THREAD

**Issue by bluetechgirl** [usememos/memos#2161]
### Is your feature request related to a problem?

As far as I know memos are stored in an unencrypted format. Adding it would give some peace of mind, especially if you're not hosting it on your own server.

### Describe the solution you'd like

Could support for encrypting memos be added?

**Comment by Chris1320** [comment]
+1 for end-to-end encryption. This would be a great feature if it ever becomes available because I plan to use memos as my personal journaling solution.

**Comment by kidultff** [comment]
+1.

Memos is a great application, thanks to the contributors for their selfless dedication.

I also use memos as a solution for personal diaries, but plaintext SQLite databases do still have security risks, such as being stolen by cloud service providers, or being read by someone who steals a NAS hard drive.

I think memos can use `sqlcipher` to encrypt the database, or use end-to-end encryption to store the ciphertext in the database.

Thanks again to the contributors of memos, memos is a very important application to me.

**Comment by davbauer** [comment]
+1 for this feature.

As someone who's considering memos for my personal journaling needs, the aspect of data security is paramount. The nature of journal entries often being personal and sensitive makes encryption not just a nice-to-have, but a necessity.

Thanks for taking this feedback into account!

**Comment by BastionNtB** [comment]
+1 to this.

**Comment by secondtruth** [comment]
+1

**Comment by t41372** [comment]
+1
