### ISSUE TITLE
ios手机端登录显示异常

### ISSUE THREAD

**Issue by noonecheck** [usememos/memos#2163]
### Describe the bug

ios端能正常显示，但是单击登录，会提示如下问题，请问有没有遇到的，怎么处理应该，谢谢
Unexpected Application Error!
undefined is not a constructor (evaluating 'new Intl.DisplayNames([i],{type:"language"})')
https://www.**********.xyz/assets/index-4ca98ffb.js:328:1961668
map@[native code]
OK@https://www.**********.xyz/assets/index-4ca98ffb.js:328:1961634
$5@https://www.**********.xyz/assets/index-4ca98ffb.js:83:195570
zq@https://www.**********.xyz/assets/index-4ca98ffb.js:85:248199
Uq@https://www.**********.xyz/assets/index-4ca98ffb.js:85:243917
Kne@https://www.**********.xyz/assets/index-4ca98ffb.js:85:243843
dN@https://www.**********.xyz/assets/index-4ca98ffb.js:85:243695
r3@https://www.**********.xyz/assets/index-4ca98ffb.js:85:240057
Lq@https://www.**********.xyz/assets/index-4ca98ffb.js:85:239004
Lq@[native code]
T@https://www.**********.xyz/assets/index-4ca98ffb.js:70:128971
z@https://www.**********.xyz/assets/index-4ca98ffb.js:70:129332

### Steps to reproduce

...

**Comment by kun775** [comment]
同样的错误，用的是iPhone11，已经越狱（有没有可能是这个原因，因为我用同事的安卓手机可以登录），无论是谷歌浏览器还是safari，亦或是via都是一样的错误，无法登录

**Comment by boojack** [comment]
Duplicated with https://github.com/usememos/memos/issues/2197
