### ISSUE TITLE
数据好像未进行物理删除

### ISSUE THREAD

**Issue by lxivQ** [usememos/memos#217]
1、通过测试发现上传附件之后，memos_prod.db会增加，但是删除附件之后，memos_prod.db大小不会减小？逻辑删除吗
2、附件访问好像没有做权限控制？知道地址可以直接访问

**Comment by boojack** [comment]
1. Related issue: https://github.com/usememos/memos/issues/202
2. 目前 resource 都是公开的，可能之后会加入访问控制；
