### ISSUE TITLE
Deleting a post with an attachment (image) does not delete the file in the storage bucket

### ISSUE THREAD

**Issue by ituri** [usememos/memos#2172]
### Describe the bug

Hi,

I followed [the instructions](https://usememos.com/docs/storage) to set up a R2 storage bucket. However, when I delete a post the corresponding file in the bucket is not being deleted. IMHO this should be the default; otherwise my bucket will start to collect unused files over time.

### Steps to reproduce

c.f above.

**Comment by ituri** [comment]
I actually noticed the same behaviour when using local assets.

**Comment by sunteta** [comment]
this is very important issue. like

**Comment by boojack** [comment]
Duplicated with #1837
