### ISSUE TITLE
When editing the memos, there should be a prompt when 'esc' key is pressed to avoid loss of edits.

### ISSUE THREAD

**Issue by dwong33** [usememos/memos#2174]
### Is your feature request related to a problem?

When we attempt to edit a memo, there will be a editing panel pop out, when we type certain words, sometimes you will need to key in the 'esc', this is especially common when you use Chinese input methods.

The current behavior is whenever an 'esc' is keyed in, the edit will be cancelled and will lose all the typed in words.

A more ideal and common practice is when we press 'esc', a prompt will pop out and ask for whether we really want to cancel the edit.

### Describe the solution you'd like

In the editing mode, when we press 'esc', a prompt comes out and ask whether we really want to cancel the edit. If press yes, then cancel the edit and return to the memo stream. If no, then return to the edit mode.

**Comment by boojack** [comment]
The content cache for memo editor has been implemented in https://github.com/usememos/memos/issues/2206. So the prompt might not be needed anymore.
