### ISSUE TITLE
不知为何，nginx用不了

### ISSUE THREAD

**Issue by linyecheng** [usememos/memos#2182]
小白提问
nginx的配置是这样：

	location  /memos/ {
		proxy_pass http://127.0.0.1:5230/;
	}

然后打开是一片白的页面：
![image](https://github.com/usememos/memos/assets/38659947/01d2d706-f593-49e3-bd01-aed071e970f9)

nginx的error.log是这样的：
![image](https://github.com/usememos/memos/assets/38659947/596436de-2012-484a-92f6-380634a7a942)

是哪里没设置好么

**Comment by sprite82y** [comment]
用端口转发吧，因为程序用的是绝对路径 `/asserts/xxxxx` ，并不会自动给你加上 /memos/ 变成 `/memos/asserts/xxxxx`

**Comment by la0wei** [comment]
@sprite82y is right.
Add some additional information.
Using npm reverse proxy in a sub directory to memos. Like this.
![image](https://github.com/usememos/memos/assets/3761308/e8285e6c-9ee1-4c78-ae98-4bce52ddda20)

But in the browser, the page was blank.

In the web developer tool,it shows
![image](https://github.com/usememos/memos/assets/3761308/eac3c227-6e51-488a-8b07-02c1f678834a)

What I want is https://DOMAIN/**memos**/assets/index-BgLbTvS8.js

In the source of the page, it shows
![image](https://github.com/usememos/memos/assets/3761308/25ae54da-de79-4424-a8db-7357642e1bbe)
