### ISSUE TITLE
console error: Could not find the language 'conf', did you forget to load/include a language module?

### ISSUE THREAD

**Issue by bmphjhu906** [usememos/memos#2188]
### Describe the bug

console error: Could not find the language 'conf', did you forget to load/include a language module?

### Steps to reproduce

1. f12

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/120728683/35d3fe69-72d2-4f6d-b9d6-77bdc5e6a4bd)

**Comment by boojack** [comment]
Please try to reproduce it on the latest demo. https://demo.usememos.com
