### ISSUE TITLE
点击探索，选择查看任意其他人，再点击每日回顾，会将自己的说和之前查看过的人说说合并展示

### ISSUE THREAD

**Issue by penndu** [usememos/memos#2189]
### Describe the bug

复现地址：https://s.dusays.com
![image](https://github.com/usememos/memos/assets/46226528/8c3daeb3-2427-4c19-9ac7-46e829294153)
![image](https://github.com/usememos/memos/assets/46226528/5b61851c-9d8c-40d1-9af2-9332fd1ecd6b)

### Steps to reproduce

1. 登录
2. 点击探索
3. 点击每日回顾

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/58429f88a0e5a0da0e369cf1e5ecb35ff0d95d13
