### ISSUE TITLE
存储支持七牛云吗？

### ISSUE THREAD

**Issue by bmphjhu906** [usememos/memos#2190]
![image](https://github.com/usememos/memos/assets/120728683/570ab16c-5745-42f6-84c8-4a46cb9ea1cb)
配置七牛云存储上传文件报错：
![image](https://github.com/usememos/memos/assets/120728683/fe3680f7-04f1-4574-af8d-6690c8619d6d)

```json
{
    "error": "code=500, message=Failed to save resource, internal=Failed to upload via s3 client: operation error S3: PutObject, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Put \"/s3.cn-north-1.qiniucs.com/scdn-nodjoy/robots.txt?x-id=PutObject\": unsupported protocol scheme \"\"",
    "message": "Failed to save resource"
}
```

**Comment by Duinks** [comment]
我的可以用

**Comment by bmphjhu906** [comment]
> 我的可以用

怎么配置的啊，大佬

**Comment by jemygraw** [comment]
> > 我的可以用
> 
> 怎么配置的啊，大佬

你已经配置对了大部分，就是那个端点前面要加 http:// 就可以了

**Comment by wangyunzi** [comment]
> > > 我的可以用
> > 
> > 
> > 怎么配置的啊，大佬
> 
> 你已经配置对了大部分，就是那个端点前面要加 http:// 就可以了

感谢解决了我的问题
