### ISSUE TITLE
failed to log in through Safari

### ISSUE THREAD

**Issue by mzeng2** [usememos/memos#2197]
### Describe the bug

My device is macOS 10.14.6 with Safari version 14.0.3 (14610.4.3.1.6). I failed to log in memo through safari and please see the error from the screenshot below. I guess the problem may come from language because on Safari, the interface turn into Chinese and I can't found the options to change the language. However, when I open the localhost:5230 on Edge the language is default (English).

I check the image status, the service works well and  I can use it on Edge. But it would be great if you guys can solve the bugs on Safari, thanks.

![image](https://github.com/usememos/memos/assets/110366384/9d3008d3-7b7a-467f-8ed7-e16a46692dd3)

### Steps to reproduce

1. enter localhost:5230 in Safari and go
2. click 登陆 
3. the error come up

**Comment by boojack** [comment]
Might be fixed with ca336af4faa98818ec1dca422f1fb4ce958802eb. Please try again in the demo site. https://demo.usememos.com
