### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by wa1kb0y** [usememos/memos#2199]
### Is your feature request related to a problem?

I expected to find font size value in settings to make it little bit less. Cant believe its not there.

### Describe the solution you'd like

Add font size setting in settings.

### Additional context

Thank you!

**Comment by gvenusleo** [comment]
Maybe you can achieve a smaller font using custom CSS.

**Comment by wa1kb0y** [comment]
Good idea, i achieved desired result with `.memo-content-text { zoom: 0.8; }` thanks, but i still think it would be good to add it as setting.

**Comment by boojack** [comment]
Custom CSS is a more general solution instead of adding a new setting item.
