### ISSUE TITLE
Allow us to edit the date of a memo

### ISSUE THREAD

**Issue by maticboncina** [usememos/memos#2200]
### Is your feature request related to a problem?

Sometimes I forget to capture ideas / cannot do it at that very moment. Since I am using this as a journal I'd like to add times in the past. Also currently, it's super frustrating, because I cannot import old entries easily.

### Describe the solution you'd like

By double-clicking the time "XX minutes ago" for example (this one) 👇

![CleanShot 2023-09-08 at 13 19 10@2x](https://github.com/usememos/memos/assets/54638868/b07c5080-6b0b-4122-a45e-b5cd0d022ddb)

You can change the date and time of entry of the memo. This would make capturing ideas chronological and allow us to import old entries easily. 

Honestly, this feature can be implemented in any way, I'd just like to see it in production :)

### Additional context

If there is anything else that I can do now, to import old notes, please do let me know! (I guess editing the database is an option, but I am not sure what to change)

**Comment by boojack** [comment]
> By double-clicking the time "XX minutes ago" for example (this one) 👇

Updated in the main branch, and will be released in the next version.

**Comment by maticboncina** [comment]
Thank you!

**Comment by tombatti** [comment]
Hi, 
do you know if this feature has been released to date? 
I don't think it's possible to change the date and time yet

Thanks
Tomas

**Comment by tombatti** [comment]
> > Hi, do you know if this feature has been released to date? I don't think it's possible to change the date and time yet
> > Thanks Tomas
> 
> You can press option + left click on the date entry after you submit the entry in the journal to show the popup that allows you to edit the time. It's alt + left-click on nonmac devices.

Sorry, but I didn't understand how to do it, I can't find any option to change the date or time from the website

Thanks
Tomas

**Comment by tombatti** [comment]
> > Hi, do you know if this feature has been released to date? I don't think it's possible to change the date and time yet
> > Thanks Tomas
> 
> You can press option + left click on the date entry after you submit the entry in the journal to show the popup that allows you to edit the time. It's alt + left-click on nonmac devices.

I found how to do it, but even after editing, the calendar on the side doesn't update, it shows me all the posts as if they were created on the same day, same thing with the daily review...so this change is of no use if the site then it doesn't show me updated data

Thanks

**Comment by maticboncina** [comment]
Here is the video for you. 

https://github.com/usememos/memos/assets/54638868/01fa5703-0c69-4bdb-981f-366fdbed8001

Additionally, you need to toggle this option:
![1](https://github.com/usememos/memos/assets/54638868/257b3ac9-91aa-4875-8e0f-53fe1f04256b)

Hope it helps.

**Comment by tombatti** [comment]
> Here is the video for you.
> 

Great, that's how everything works

Thanks for your help

**Comment by shao-xy** [comment]
I met the same thing... The trick that matters is to toggle off "Display with updated time". Thx anyway

**Comment by amirasyraf** [comment]
@maticboncina 

Has this been removed? I'm on `v0.23.1` and can't seem to edit the timestamp as demonstrated

**Comment by maticboncina** [comment]
I am not sure. Haven't updated the release since the version on the original issue. Best to wait for the developer to answer or ping him.

**Comment by amirasyraf** [comment]
> I am not sure. Haven't updated the release since the version on the original issue. Best to wait for the developer to answer or ping him.

Resolved - The feature is still there. You just have to edit a post and click on the timestamp. No need to ALT + click. It gives you a nice datepicker

![Image](https://github.com/user-attachments/assets/caa103db-6355-4cd1-b8e8-02f8627f638a)

**Comment by rheckly** [comment]
I'm on version 0.25.3 - using chrome - i have to edit the post so I can change the date - this calendar date picker doesn't pop up.
--> ok, just found it - in the dark design the calendar picker is not really visible ;-)

But question is how to change the date on the iPhone app - how to change the date with Moe Memos on iPhone?
