### ISSUE TITLE
Share notes only with selected users

### ISSUE THREAD

**Issue by oskargesina** [usememos/memos#2202]
### Is your feature request related to a problem?

I'd love to share notes only with selected users, eg. @johnmiles insead of nobody or everyone

### Describe the solution you'd like

One more option in sharing dialog would be great: Share with user, and then input for username.

**Comment by mwllgr** [comment]
+1 for this! Would be a really cool feature if implemented correctly.

**Comment by mwllgr** [comment]
Just a heads-up here. Is this really not planned?

**Comment by nesges** [comment]
i know it's closed and nobody will see this, but just in case: I'd **really** like to see this
