### ISSUE TITLE
编辑器的本地缓存功能丢了。The editor cache is gone !

### ISSUE THREAD

**Issue by TinyRei** [usememos/memos#2207]
### Describe the bug

@boojack 

大佬你好，Memo编辑器的本地缓存功能从v0.13.2开始就没有了，很容易发生未保存memo，但是关闭了编辑器或是网页导致丢失。
能否将本地缓存功能恢复，或是做成功能可以选择开启关闭。

Hi,
there is no editor local cache from version 0.13.2. It's a very important function.
pls help it back, or it's better to control it open.
I'm appreciate it !

### Steps to reproduce

1. 在编辑器输入文字，type in editor
2. 刷新网页，refresh the web
3. 丢失所有文字，it's lost

**Comment by boojack** [comment]
Duplicated with #2206
