### ISSUE TITLE
使用makrdown 代码遇到的问题

### ISSUE THREAD

**Issue by 929126387** [usememos/memos#2210]
### Describe the bug

使用makrdown  ``` 代码 ``` 语法  手机端不显示代码，显示为 undefined 
![photo_2023-09-12_19-14-08](https://github.com/usememos/memos/assets/77496052/d82d1e00-c6a0-4392-8838-3220dc2622be)

### Steps to reproduce

![photo_2023-09-12_19-14-08](https://github.com/usememos/memos/assets/77496052/f7b0741e-1a75-4a0e-b90a-5ce4ba0ea8aa)

**Comment by 929126387** [comment]
``` 三个点  代码语法

**Comment by 929126387** [comment]
![这是图片](https://xxx.com/o/r/26/923672b5-fd8a-4ae2-b546-20fe602a3ce9/%E9%9A%8F%E6%9C%BA%E7%9B%90.png)  图片代码  手机app 也不显示图片

**Comment by boojack** [comment]
> 手机端不显示代码，显示为 undefined

memos provides an official web page but not a mobile app.
