### ISSUE TITLE
Can not reset password if forget the original password

### ISSUE THREAD

**Issue by lucumt** [usememos/memos#2213]
### Is your feature request related to a problem?

I have forget login password and can not find a way to reset my password in internal network
![image](https://github.com/usememos/memos/assets/5226038/9cfffa34-edef-4a34-86e0-32f11fc5ff17)

### Describe the solution you'd like

Add a way to reset password

**Comment by boojack** [comment]
Reference: https://github.com/usememos/memos/issues/188
