### ISSUE TITLE
WYSIWYG Editor

### ISSUE THREAD

**Issue by sadden3194** [usememos/memos#2216]
### Is your feature request related to a problem?

Only markdown syntax available

### Describe the solution you'd like

I would like to easy format my text with a WYSIWYG editor instead of markdown syntax

**Comment by diomed** [comment]
basically you actually want markdown editor to be part of memos - so something like this:

https://lab.lepture.com/editor/

**Comment by neliets** [comment]
I am also hoping something similar gets implemented. And with that perhaps a few markdown features enabled, like tables, quotes etc.

**Comment by boojack** [comment]
> Memos primarily focuses on plain text recording, but also supports some commonly used Markdown syntax. Here is a list of supported content syntax:

Learn more in https://www.usememos.com/docs/getting-started/content-syntax
