### ISSUE TITLE
Unresponsive page when fetching data

### ISSUE THREAD

**Issue by HappyZ** [usememos/memos#2223]
### Describe the bug

Have about 500kb+ database which is relatively small. Has S3 storage endpoint set. On the latest version.

The first time I open the page it will halt (not allow any interactions) to load data. Once loaded (no picture yet) it worked fine. And then images will be loaded without problems.

If then scroll down enough that trigger to load new data ("fetching data..." shows), it stuck again until data is loaded.

It only happens in scroll to load after logged in. If I was in explore mode (public), it worked out ok (probably because I need to manually click).

Feel like it has to do with scroll loading because the page background shows some slight flashes somehow while it stuck. 

### Steps to reproduce

As described in the bug above.

**Comment by boojack** [comment]
> it stuck again until data is loaded

What is the `stuck`/`unresponsive page` looks like? I recorded one that only pulls off 3 pieces of data at a time + automatically pulls off the data. I didn't find the page is stuck with the data being pulled.

https://github.com/usememos/memos/assets/24653555/97ce9f83-4243-4bc4-8b5f-54ec8e0cf2ce

**Comment by HappyZ** [comment]
Thanks I tried on Safari it worked fine. Looks to have something to do with the Chrome browser, on both phone and macbook.

**Comment by HappyZ** [comment]
After some tests, I found my chrome has flag "Auto Dark Mode for Web Contents" forced on. I turned it off and it's all good.

**Comment by so02iti01** [comment]
> After some tests, I found my chrome has flag "Auto Dark Mode for Web Contents" forced on. I turned it off and it's all good.

Thanks a lot. It works.
