### ISSUE TITLE
Upgrade Docker Container loses memos - AGAIN

### ISSUE THREAD

**Issue by axelder** [usememos/memos#2225]
### Describe the bug

I am having this issue #613 since I upgraded to the latest version with docker-compose pull command:
How can I fix this this ?

### Steps to reproduce

1. docker-compose pull
2. docker-compose down
3. docker-compose up

**Comment by cxplay** [comment]
Did you back up your database?

**Comment by axelder** [comment]
Unfortunately no !

**Comment by cxplay** [comment]
> Unfortunately no !

Unfortunately too, the damage is irreparable. The first version of v0.15 had some problems, and now a second version, v0.15, has been released, which solves the database problems.

**Comment by axelder** [comment]
(-̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥᷄_-̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥᷅ )

**Comment by ntomita** [comment]
@axelder Sorry for your data loss. I encountered this issue page while researching memos before installation. I will definitely add a cron job to regularly backup my database.
