### ISSUE TITLE
MEMOS upgrades to the latest version, the homepage error appears

### ISSUE THREAD

**Issue by voctot** [usememos/memos#2226]
### Describe the bug

Failed to compose memo response。

### Steps to reproduce

You can see on the homepage。

### Screenshots or additional context

![1694852602805](https://github.com/usememos/memos/assets/36097179/735d1a25-38b4-40eb-bf2d-ee189dc77ea8)

**Comment by zhaoyibo** [comment]
try to log in again?

**Comment by boojack** [comment]
1. Re-login with your admin account;
2. Go to setting page directly with url `/setting`;
3. Click the **Vacuum** button in the system setting section;

<img width="1023" alt="image" src="https://github.com/usememos/memos/assets/24653555/a9145fb5-d099-4493-89d0-3a4100db331e">

**Comment by voctot** [comment]
> 1. Re-login with your admin account;
> 2. Go to setting page directly with url `/setting`;
> 3. Click the **Vacuum** button in the system setting section;
> 
> <img alt="image" width="1023" src="https://user-images.githubusercontent.com/24653555/268454346-a9145fb5-d099-4493-89d0-3a4100db331e.png">

I have tried it, there is no effect

**Comment by boojack** [comment]
Maybe fixed in https://github.com/usememos/memos/commit/b452d63fa6b2fbf7d4f74976ee12cf60d7a09f4c
