### ISSUE TITLE
After upgrading to 0.15.0, the Object Storage is set to "Local" instead of "Database" but it doesn't change anything

### ISSUE THREAD

**Issue by 8mnl** [usememos/memos#2232]
### Describe the bug

I always used the Database Storage in Memos. After upgrading from 0.14.3 to 0.15.0, I noticed that the "Current Object Storage" was changed from "Database" to "Local". After trying to access /assets/ to see if my memos are now stored local, I just received an Internal Server Error in the JSON message, so memos are still saved in the database even tho the Storage is set to Local.

### Steps to reproduce

1. Shut down the docker container, backup the memos_prod.db
2. Use the migration script (https://raw.githubusercontent.com/usememos/memos/main/store/db/migration/prod/0.15/00__drop_user_open_id.sql) or type it in manually
3. docker compose pull && docker compose up -d
4. Navigate to Settings → Storage with your MOD account and see that the "Current Object Storage" has changed

**Comment by boojack** [comment]
> trying to access /assets/ to see if my memos are now stored local.

Only the binary resources(image/video/other files) will be saving to local folder, not memo content.

**Comment by boojack** [comment]
> Use the migration script (https://raw.githubusercontent.com/usememos/memos/main/store/db/migration/prod/0.15/00__drop_user_open_id.sql) or type it in manually

Memos will auto detect your current version and run these script if needed. So you don't need to execute the script manually.

**Comment by boojack** [comment]
> Navigate to Settings → Storage with your MOD account and see that the "Current Object Storage" has changed

After `v0.15.0`, the default storage of resources will be `local`. It means that new added resources will be saved into local folder. When you change the settings, it only affects the newly added data.

**Comment by 8mnl** [comment]
Thanks for the responses and the additional infos. :)

> After v0.15.0, the default storage of resources will be local. It means that new added resources will be saved into local folder. When you change the settings, it only affects the newly added data.

Maybe you could add this to the change log? At least I was pretty confused that it changed.
