### ISSUE TITLE
/api/v2/users/username return 503

### ISSUE THREAD

**Issue by sudoexec** [usememos/memos#2234]
### Describe the bug

When login with GitLab, the UI is always rendering. And `/api/v2/users/username` return 503.
```
{
    "code": 14,
    "message": "connection error: desc = \"error reading server preface: EOF\"",
    "details": []
}
```

### Steps to reproduce

1. Login with GitLab
2. UI crashed

**Comment by sudoexec** [comment]
At last, I found the root cause is the HTTP_PROXY/HTTPS_PROXY environment variable.

It looks like the server architecture changed, there're some local RPC requests go to the proxy by mistake.

Hi @boojack , how can I use the solution described in https://github.com/orgs/usememos/discussions/1893 for v0.15.0?I've added http://127.0.0.1 and http://localhost to NO_PROXY, but it didn't work.

**Comment by boojack** [comment]
@sudoexec I cannot reproduce in demo site. https://demo.usememos.com/api/v2/users/demohero

**Comment by sudoexec** [comment]
Hi @boojack, Look here:


> At last, I found the root cause is the HTTP_PROXY/HTTPS_PROXY environment variable.
> 
> It looks like the server architecture changed, there're some local RPC requests go to the proxy by mistake.
> 
> Hi @boojack , how can I use the solution described in https://github.com/orgs/usememos/discussions/1893 for v0.15.0?I've added http://127.0.0.1 and http://localhost to NO_PROXY, but it didn't work.
