### ISSUE TITLE
User profile BUG

### ISSUE THREAD

**Issue by s544838371** [usememos/memos#2239]
### Describe the bug

v0.15.0 I see a new page：User profile: A separate home page for yourself.
But when I opened it, Prompt me that the user was not found
I use f12, I found that there was an error in passing in parameters when calling the API
Because my username is ```xxxx@qq.com```
But ```/api/v2/users/xxxx```
Missing ```@qq.com```

Now What should I do？

### Steps to reproduce

1. login memos
2. open User profile
3. use F12
4. find a error：Failed to load resource: the server responded with a status of 404 ()

**Comment by s544838371** [comment]
when i change my username to xxx-per
then i open User profile
same error
Because Missing ```-per```

**Comment by songxin6** [comment]
The same problem
![memos问题](https://github.com/usememos/memos/assets/51051155/36598960-2080-461b-87b4-37ec5d37acbd)

**Comment by boojack** [comment]
It's mainly because of the invalid username. A standard username format(lowercase) should be `^[a-z]([a-z0-9-]{2,30}[a-z0-9])?$`.

**Comment by boojack** [comment]
Fixed in https://github.com/usememos/memos/commit/8fbd33be0951578ba7b4809c2347864700c318d2.

**Comment by s544838371** [comment]
cool
