### ISSUE TITLE
Resources with timeline view

### ISSUE THREAD

**Issue by s544838371** [usememos/memos#2240]
### Is your feature request related to a problem?

# Resources with timeline view

when i open Resources with timeline view
I realized that I don't know which file I'm looking for

### Describe the solution you'd like

Now，I guess Should the resource name be displayed instead of the resource type， because If the resource is a file, I cannot see the name of the file

### Additional context

![微信截图_20230918112746](https://github.com/usememos/memos/assets/40713819/bb27ac5f-d984-431a-b715-ba3f67978c44)

**Comment by boojack** [comment]
Updated in https://github.com/usememos/memos/commit/14adcb56da04808733d9be79f612b6bb4b359386

<img width="786" alt="image" src="https://github.com/usememos/memos/assets/24653555/c728637a-83c5-41ef-9042-6dc284338992">
