### ISSUE TITLE
使memos bot可以通过消息指令更改最近一条memo的公开/私密状态

### ISSUE THREAD

**Issue by vessel00** [usememos/memos#2244]
### Is your feature request related to a problem?

当在其他群组/频道浏览信息时，会有批量保存到memos的需求，但并非所有内容都想设为公开。转发给bot之后可以通过bot回复的消息进行设置，但这需要事后一条条分别设置，较为麻烦，体验比较割裂。所以希望可以通过消息指令更改最近一条memo的公开/私密状态。

### Describe the solution you'd like

使用类似`/public` `/private`的消息指令控制最近一条memo的公开/私密。使用情况如：转发消息到bot时，在附加信息中写`/public`，使得bot接收到信息存入memos，并根据附加信息设为公开状态。

**Comment by athurg** [comment]
While you forward messages in Telegram, there is no place to attach anything, so where do you think you input the `/public` command ?

**Comment by 0Vessel0** [comment]
Thanks for your reply, I think `/public` can be inputed here.
![66d7992a773630752c13936bd76a74b](https://github.com/usememos/memos/assets/109258462/bfc4d5b3-d50b-487c-ba2c-0cc02345d8a7)

**Comment by 0Vessel0** [comment]
> While you forward messages in Telegram, there is no place to attach anything, so where do you think you input the `/public` command ?当你在 Telegram 中转发消息时，没有地方可以附加任何东西，那么你认为你在哪里输入 `/public` 命令？

Thanks for your reply, I think /public can be inputed here.
![aea405598114127a4c0c0d6b98a1d14](https://github.com/usememos/memos/assets/109258462/9315dcc9-e88f-4d55-8a0d-e5e9069046f3)

**Comment by athurg** [comment]
I didn't find the screen looks like you provide by forward message in Telegram, both iOS and Android.

Are you sure this is in the official Telegram client, and could you provide more context, such as a screen record video.

By the way, I can find a similar UI in iOS's system shared action. But in this action, the attached comment with the resources will be used as a new text message by Telegram, not the capital of the resources.

**Comment by 0Vessel0** [comment]
Yeah, this is the latest version of the Android app downloaded directly from the official website. The button that triggers this interface is shown in the picture. You need to be inside a channel to have access to this button.
![IMG_20230921_161753](https://github.com/usememos/memos/assets/109258462/9ba31260-b998-4b5f-b222-6dcdd064513f)

**Comment by athurg** [comment]
I got it. But if you forward a message with a comment there, you got TWO messages, the forwarded message and a comment message, not ONE forwarded message with comment.

**Comment by 0Vessel0** [comment]
Yes, so what I suggest is to control the public/privateness of the latest memo by a command.

Recently, I discovered that some third-party Telegram clients like Nagram allow sending an additional message behind the forwarding message. So, the idea is to "set the status of the PREVIOUS message by a command."

However, this option is not available in the official app, so we can try a different approach: In Android 11 and above versions, Telegram allows direct message replies from the notification panel. Therefore, we can directly input the command '/public' (or use a shorter version like '/p') in the notification panel to change the memo's status without leaving your current location.

**Comment by athurg** [comment]
You didn’t need it. Every messenge sends to telegram bot will get a reply with buttons,which you can change the visiabillity of the memo.发自我的 iPhone在 2023年9月23日，00:35，Vessel ***@***.***> 写道：﻿
Yes, so what I suggest is to control the public/privateness of the latest memo by a command.
Recently, I discovered that some third-party Telegram clients like Nagram allow sending an additional message behind the forwarding message. So, the idea is to "set the status of the PREVIOUS message by a command."
However, this option is not available in the official app, so we can try a different approach: In Android 11 and above versions, Telegram allows direct message replies from the notification panel. Therefore, we can directly input the command '/public' (or use a shorter version like '/p') in the notification panel to change the memo's status without leaving your current location.

**Comment by 0Vessel0** [comment]
So, what I want to say is, "After forwarding the message to the bot, immediately exit the channel, enter the bot interface to set the privacy status, and then return to the channel." Having to scroll back and forth in the message list makes the experience feel disjointed. "Setting the privacy status after forwarding multiple messages together" is not a good experience as it is prone to accidental tapping.

**Comment by athurg** [comment]
I got it, but I think it won't be changed at this moment.

In Telegram, the message attachment with the forward is same as the normal message, the bot didn't know a text message is a 'Attachment Message' or a 'Directly message'.

Even though we know the send time is very similar normally, but it's not enough to do this.

**Comment by 0Vessel0** [comment]
What I mean is: Be able to set the status of the "last" memo with a command. Don't need to know if this is an 'Attachment Message' or a 'Directly message', and don't need to check the send time, but just need to set the status of the 'last' memo after receiving this message.
