### ISSUE TITLE
Error on new resources page

### ISSUE THREAD

**Issue by sardaukar** [usememos/memos#2247]
### Describe the bug

When I select "Resources" on the left sidebar, I see this:

![image](https://github.com/usememos/memos/assets/153407/3efbdd3b-2782-476f-9561-4a8c2c7295ce)

And the browser console shows:

```
Uncaught (in promise) ClientError: /memos.api.v2.ResourceService/ListResources INTERNAL: failed to list tags: sql: Scan error on column index 0, name "related_memo_id": converting driver.Value type string ("2,5") to a int32: invalid syntax
    st https://URL/assets/index-e6411619.js:309
    ClientError https://URL/assets/index-e6411619.js:309
    makeCall https://URL/assets/index-e6411619.js:310
```

I'm using 0.15.1 on the latest Firefox

### Steps to reproduce

1. Login
2. Click "Resources" on the sidebar

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/153407/c7fdd6ed-2b19-43a1-b98a-5843c64f8a53)

**Comment by boojack** [comment]
Fixed in https://github.com/usememos/memos/commit/9bf1979fa879b18c88e25009e1f23d311d6ae5b1. You can pull the latest docker image later.
