### ISSUE TITLE
HTML Embeds

### ISSUE THREAD

**Issue by osevenlan** [usememos/memos#2252]
### Is your feature request related to a problem?

N/A

### Describe the solution you'd like

When pasting in a link from, for example, Twitter, Memos would pull any text and images/video and would display it in memos. 

### Additional context

(discord preview of twitter link)

![image](https://github.com/usememos/memos/assets/89861921/23708757-0031-45dc-b900-de071fa74ade)

**Comment by MRobi1** [comment]
I'll second this FR. I think this would be a pretty core feature.

**Comment by MehadND** [comment]
@osevenlan and @MRobi1 can you kindly check this [PR](https://github.com/usememos/memos/pull/2812) and see if this fits your need. As of now it is only for YT but I'm hoping something similar for X/Twitter

**Comment by MRobi1** [comment]
> @osevenlan and @MRobi1 can you kindly check this [PR](https://github.com/usememos/memos/pull/2812) and see if this fits your need. As of now it is only for YT but I'm hoping something similar for X/Twitter

Yup, this is exactly it! Except looking more along the website lines like X/Twitter rather than YT.

**Comment by MehadND** [comment]
> > @osevenlan and @MRobi1 can you kindly check this [PR](https://github.com/usememos/memos/pull/2812) and see if this fits your need. As of now it is only for YT but I'm hoping something similar for X/Twitter
> 
> 
> 
> Yup, this is exactly it! Except looking more along the website lines like X/Twitter rather than YT. 

This might be tough since I think X/Twitter now has a paywall in between for people trying to do this but I might try and look into creating something of my own from scratch.
