### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by matoung** [usememos/memos#2254]
### Describe the bug

在使用https://github.com/eallion/memos.top作为memos的浏览前端，分属同一域名的不同端口，发现升级到最新版本memos.top无法读到memos的内容，浏览器报跨域错误：
Access to fetch at 'https://xxx:8086/api/v1/memo/stats?openId=xxx&creatorId=1' from origin 'https://xxx:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

查询代码发现是删掉了echo框架的CORS支持，请问是否能重新打开？
main/server/server.go
对应Commit：https://github.com/usememos/memos/commit/72ca4e74eea9b0dd17cd9a6772daaa9039322514
被删代码：e.Use(middleware.CORS())

### Steps to reproduce

部署并访问memos.top前端：https://github.com/eallion/memos.top
配置好最新的memos服务端

**Comment by boojack** [comment]
updated with https://github.com/usememos/memos/commit/6d45616dbe501680c56d71b67c0d0aaafbbfdda4
