### ISSUE TITLE
How can I add memo for specific user?

### ISSUE THREAD

**Issue by ashay8us** [usememos/memos#2261]
### Is your feature request related to a problem?

is this possible? 

### Describe the solution you'd like

If not, please add feature.

**Comment by boojack** [comment]
You mean creating memo for other users? I'd like to know what's the scenario for using it.

**Comment by ashay8us** [comment]
Memo targeted at that specific heaters where they can only see. A single user can only see the memo I create. Almost like a chat conversation between users. Is that possible?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by boojack** [comment]
> Memo targeted at that specific heaters where they can only see. A single user can only see the memo I create. Almost like a chat conversation between users. Is that possible?

Maybe not.
