### ISSUE TITLE
After updating to 0.15.1, I cannot log in using a reverse proxy

### ISSUE THREAD

**Issue by gitous** [usememos/memos#2263]
### Describe the bug

I deployed memos in Synology's docker, using Synology's own reverse proxy. After updating to 0.15.1, you can go to the home page, enter the account password to log in and get stuck on the loading page. Using the API with moe memos on the mobile phone can be used normally, and bypassing the reverse proxy and directly using the docker port can log in normally. 

### Steps to reproduce

update to 0.15.1
log in using reverse proxy address
stuck on loading page

### Screenshots or additional context

![微信截图_20230921095928](https://github.com/usememos/memos/assets/32594402/cf535c35-d44e-4204-9c52-070008853564)
Load page after login

![微信截图_20230921100127](https://github.com/usememos/memos/assets/32594402/346c01cf-1f77-484a-b57f-a2af6fc6b058)
Synology's logs

**Comment by athurg** [comment]
Maybe the browsers network requests log will be more helpful. I guest some requests to the new gRPC service have been blocked by the browser.

**Comment by gitous** [comment]
![微信截图_20230921132356](https://github.com/usememos/memos/assets/32594402/a5f76e2d-6c9b-4c49-a24b-e95cfc02ba57)
Maybe this kind of log would be useful?

**Comment by Ronny200** [comment]
Same problem, can be accessed within the LAN when updating 0.15.1,
phone app tip not found

**Comment by rdtm443** [comment]
> Same problem, can be accessed within the LAN when updating 0.15.1,
> phone app tip not found

Same problem here. Cannot accessed with Android phone app (MoeMemos): "Required value 'openid' missing at $".

**Comment by boojack** [comment]
Try the latest version again.

**Comment by xinfli** [comment]
Is there any workaround for this problem? I updated to latest version (0.18.0) but still get same error:
```
ClientError: /memos.api.v2.AuthService/GetAuthStatus UNKNOWN: Response stream closed without gRPC status. This may indicate a misconfigured CORS policy on the server: Access-Control-Expose-Headers must include "grpc-status" and "grpc-message".
    ct https://memos.x2log.net/assets/index-1fac1b39.js:299
    ClientError https://memos.x2log.net/assets/index-1fac1b39.js:299
    makeCall https://memos.x2log.net/assets/index-1fac1b39.js:300
```
