### ISSUE TITLE
Failed to resolve import "./types/proto/api/v2/memo_service" from "src/grpcweb.ts". Does the file exist?

### ISSUE THREAD

**Issue by ideager** [usememos/memos#2264]
### Describe the bug

`[plugin:vite:import-analysis] Failed to resolve import "./types/proto/api/v2/memo_service" from "src/grpcweb.ts". Does the file exist?
/Users/***/memos-main/web/src/grpcweb.ts:2:38
1  |  import { createChannel, createClientFactory, FetchTransport } from "nice-grpc-web";
2  |  import { MemoServiceDefinition } from "./types/proto/api/v2/memo_service";
   |                                         ^
3  |  import { ResourceServiceDefinition } from "./types/proto/api/v2/resource_service";
4  |  import { SystemServiceDefinition } from "./types/proto/api/v2/system_service";
`

### Steps to reproduce

Local test error

**Comment by boojack** [comment]
https://github.com/usememos/memos/blob/main/docs/development.md#steps

Use `buf generate` in `./proto`.
