### ISSUE TITLE
Demo user have too much perms

### ISSUE THREAD

**Issue by AnAverageBeing** [usememos/memos#2265]
### Describe the bug

demo user can change 
their name , server name , Maximum upload size , Allow user signup (toggle) , they also add js and too much acess plz fix it as soon as possible

### Steps to reproduce

login as demo user and see for ur self

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/84959276/4ef87e0e-9cd6-4ba7-8413-2fd7981b53c8)
![image](https://github.com/usememos/memos/assets/84959276/8c15fa00-dfa4-444d-8c25-e7a949f1898a)
![image](https://github.com/usememos/memos/assets/84959276/e3ff4159-7909-4906-a2cb-78041c585d9d)

**Comment by boojack** [comment]
Thanks for your report, it's redeployed now.
