### ISSUE TITLE
v0.15.1 cannot display memo visibility

### ISSUE THREAD

**Issue by aoemon** [usememos/memos#2266]
### Describe the bug

After modifying the memo visibility, the current memo visibility icon cannot be displayed on the homepage

### Steps to reproduce

Add or modify a memo, and specify visibility

### Screenshots or additional context

current:

![image](https://github.com/usememos/memos/assets/20963003/787aeadf-dd8c-4041-a961-d3c277f0cdba)

expected:

![image](https://github.com/usememos/memos/assets/20963003/df199eb1-d640-4714-9a4c-15ca573f4a4e)

**Comment by boojack** [comment]
It will be released in `v0.16.0`.

<img width="683" alt="image" src="https://github.com/usememos/memos/assets/24653555/c36d4661-2d46-44f6-bbf4-187c8f1a2438">
