### ISSUE TITLE
已经替换了系统图标，但是这里未登录的头像还是显示的默认头像。

### ISSUE THREAD

**Issue by alanblogooo** [usememos/memos#2267]
### Describe the bug

![image](https://github.com/usememos/memos/assets/35328276/f3cfc3dc-adec-46de-bfcb-842a9d46cbab)
已经替换了系统图标，但是这里未登录的头像还是显示的默认头像。

### Steps to reproduce

未登录场景下。

**Comment by Ursas-i** [comment]
Hi, I think this feature is to change the user's avatar, not the default avatar, if you want this feature, it would be better to propose a feature issue.
