### ISSUE TITLE
The "full screen" mode button in memo editor

### ISSUE THREAD

**Issue by bofeng** [usememos/memos#2270]
### Describe the bug

After upgrade to version 0.15.1, I found that the "full screen" edit button is gone. I think it was here before:
<img width="474" alt="Screenshot 2023-09-22 at 11 03 17 AM" src="https://github.com/usememos/memos/assets/3884670/c1864b5d-22f0-49d8-ae5d-1373f3eeaab6">

Not sure if this is removed on purpose or a bug. I personally found it is useful, could you bring it back?

Thank you!

### Steps to reproduce

After login, you will see that the "full screen edit" icon is gone

**Comment by Zeng1998** [comment]
See #2255 .

**Comment by bofeng** [comment]
Thank you for the response. Since this is a free and open source software, you and @boojack (or other maintainers) apparently can make any feature decisions, and I respect that.

However, I feel this "full screen" feature removal might not be a good idea. As @boojack mentioned in issue #2255 :
> memos is suitable for saving short texts, not long one.

This seems the authors want users to use the software in the way they want, but not based on how users actually use it or user's feedbacks. I am not sure how the removal decision has been made, and I am wondering that does this feature hurt anything or is there anyone complained about it?

I personally love the "full screen editing" feature, apparently the creator of issue #2255 loves it too, and I am sure there are many others like us. On my personal use experiences, most of my memos are short, but sometimes I need to write longer ones, e.g. includes some book quotes and my own thoughts, in such cases, the "full screen editing" is very convenient.

I love this software and donated before (not trying to put pressure here since my little donation doesn't deserve your hard work in any way, but just try to prove that I really like it). As I said in the beginning that I respect the team's decision and I'll keep supporting this project, however, for this case, I sincerely ask the team to re-consider this "full screen editing" removal decision, and bring it back if possible.

Thank you!

**Comment by msreedata** [comment]
I agree with @bofeng. 

The full screen editing is quite useful. Please bring back this feature.

Thanks

**Comment by jermanoid** [comment]
I'd also appreciate the return of the enlarged editing window which seems to hopefully be making a return. I noticed it was missing today when writing a short bulleted list for a meeting. I have shorter notes but it's easer to use the full screen mode just for the clarity and focus, especially when using markdown. Also when using it for meeting notes, it takes more time to find the smaller window within the page if I'm doing other things like presenting. I did notice that if you click the date of an existing memo, it brings it up in a nice full screen view only page. If the devs are going for simplifying the interface, perhaps they could leverage that and provide edit functionality there.

**Comment by Irvingouj** [comment]
Some people may find it useful, please at least put a setting that allows large screen edit.

**Comment by JerryBian** [comment]
Do we have any update on this feature?

**Comment by jjaychen1e** [comment]
I'm new to memos and trying to find the missing full screen editing feature. Will appreciate it if we can have this feature back.
