### ISSUE TITLE
Pin icon missing from pinned memos

### ISSUE THREAD

**Issue by peveleigh** [usememos/memos#2272]
### Describe the bug

Pinned memos used to be denoted by a pin icon. That icon is missing in the latest update.

### Steps to reproduce

1. Create a pinned memo

**Comment by boojack** [comment]
It will be released in `v0.16.0`.

<img width="682" alt="image" src="https://github.com/usememos/memos/assets/24653555/a5a1cc5c-ef48-4650-9fe1-ebffad7b84b0">
