### ISSUE TITLE
exe file

### ISSUE THREAD

**Issue by stunlocked1** [usememos/memos#2273]
### Is your feature request related to a problem?

isnt docker similar to running a separate OS that needs to boot and uses all the OS resources? could maybe we get a exe file? I feel like having to wait for it to boot is a psychological barrier and makes it so that I cant be bothered to add daily note into it

### Describe the solution you'd like

make it into an exe file please

**Comment by yihangpro** [comment]
+1，hope there will be a Windows installation version！

**Comment by diomed** [comment]
I hope for Electron or Tauri app at least

**Comment by Yuansheng-Liang** [comment]
You can keep your Docker running in the background so you can take notes instantly. 
Or just set it up on a server that runs all the time, so you can visit it every moment.
Even if you have an exe file, you still have to wait for it to load.
