### ISSUE TITLE
Changing the memos date, does not make expected change

### ISSUE THREAD

**Issue by maticboncina** [usememos/memos#2274]
### Describe the bug

There is a minor issue even if one changes the creation date, the memos still think the memos were created today. 

For example. I've set this to the 1st of August (I tried both 01/08/2023 and 08/01/2023, showing just one here):
![CleanShot 2023-09-24 at 08 04 33@2x](https://github.com/usememos/memos/assets/54638868/8dbb81b6-bb0a-4652-98e5-5fabe311049b)

But it does not show under the 1st of August
<img width="837" alt="CleanShot 2023-09-24 at 08 06 38@2x" src="https://github.com/usememos/memos/assets/54638868/49ac796b-1760-4dcb-98b4-94b042a61834">

Rather still under today, when the memo was **actually** created
![CleanShot 2023-09-24 at 08 05 59@2x](https://github.com/usememos/memos/assets/54638868/c2244206-7eff-4e23-80fb-46e673a2cc85)

The home page also reports it as today, instead of the adjusted date
![CleanShot 2023-09-24 at 08 07 01@2x](https://github.com/usememos/memos/assets/54638868/1ec721bf-55ca-4a01-958e-0ee3d05f12be)

Can this be fixed? It's a bit inconvenient because if we import old notes from other software they will not show chronologically correctly, thus this feature is not usable at the moment, because it does not function.

The expected result is to adjust the date and show memos under the correct day / adjust the creation time. 

Thank you! Best, Matic

### Steps to reproduce

1. Create a memo like you normally would
2. Adjust the date by double-clicking the timestamp "seconds ago"
3. After adjusting the date to something in the past, you will see that the change is not reflected on the daily review or anywhere and the memos still think it was created today, despite changing the date.

### Screenshots or additional context

Included in the original report for clarity.

**Comment by boojack** [comment]
Cannot reproduce in my instance. Do you open the option of `Display with updated time`?

<img width="776" alt="image" src="https://github.com/usememos/memos/assets/24653555/16e56bc7-d1c5-47f4-afaf-f04f6e845835">

**Comment by maticboncina** [comment]
Hi!

<img width="844" alt="CleanShot 2023-09-26 at 16 30 06@2x" src="https://github.com/usememos/memos/assets/54638868/2ffdb426-0687-4eca-b538-3bf764065b3f">

Yes, it's toggled on.

**Comment by maticboncina** [comment]
Attaching a video too: 

https://github.com/usememos/memos/assets/54638868/0a1205f3-a000-4828-b36c-a30e57716088

**Comment by boojack** [comment]
You are changing the memo's created time but display with updated time.

**Comment by maticboncina** [comment]
You are right. I apologize. Thank you for spotting my error.
