### ISSUE TITLE
Embed Youtube Videos

### ISSUE THREAD

**Issue by saitauthao** [usememos/memos#2275]
### Is your feature request related to a problem?

Would like to be able to embed youtube videos & twitter post to memos post

### Describe the solution you'd like

Would like to be able to embed youtube videos & twitter post to memos post

**Comment by AxelRHD** [comment]
That would be a great feature!

**Comment by MehadND** [comment]
I've been working on preview cards for links so let's hope it gets accepted

Only works with twitter/x and youtube video/shorts (but only `.com` domains)

![image](https://github.com/usememos/memos/assets/34424878/f485ae3f-f905-4a20-b242-cfa81b73a370)

solid dot - yt video
outlined dot - yt shorts

**Comment by MehadND** [comment]
Hello @saitauthao & @AxelRHD,

I am working on something like this so let's hope it gets accepted.

> Warning: Only available for Twitter.com (not X) and Youtube.com (with video and shorts)

![image](https://github.com/usememos/memos/assets/34424878/b2bdf40d-fdbd-4995-abcd-50d35b45cc91)

**Comment by amirasyraf** [comment]
@boojack I don't think this is completed. There is Youtube link preview, but not embed. Would be great to have actual embed because videos on Memos has horrible performance unless it's super low bitrate

**Comment by boojack** [comment]
@amirasyraf You can always render any HTML using the special syntax supported by memos.

<img width="715" alt="Image" src="https://github.com/user-attachments/assets/1df48453-1643-4a67-a693-2d30ef7e2912" />

**Comment by amirasyraf** [comment]
Thanks @boojack, works great 👍
