### ISSUE TITLE
 Failure creating user "jfk" "Invalid username" - allow 3 character usernames?

### ISSUE THREAD

**Issue by TheLinuxGuy** [usememos/memos#2276]
### Describe the bug

I'm trying out memos as a new user and it fails creating a new username = "jfk" on the main form http://192.168.70.135:5230/auth at first start of the app.

The error "Invalid username" is ambiguous but it seems to be related to the 3 character nature of it? using "admin" as username during "registering as the Site host" works.

This ambiguous error also shows up when trying to manually create "jfk" user in http://192.168.70.135:5230/setting page.

### Steps to reproduce

1. Spin up memos container.
2. Attempt to register a new account with 3 characters.
3. See error message top right of page.

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/ad3487a9ac00c036f438f4530932e29c8131e87c

**Comment by TheLinuxGuy** [comment]
Thanks for the quick fix!
