### ISSUE TITLE
month is not translated in resources

### ISSUE THREAD

**Issue by diomed** [usememos/memos#2284]
### Describe the bug

screenshot speaks for itself;

anyway, whatever language is set, that month string remains in english, but it shouldnt.

### Steps to reproduce

.

### Screenshots or additional context

![Screenshot_2](https://github.com/usememos/memos/assets/72777/6ecad2c8-b7be-46b6-bfff-e6d8d8acb616)

**Comment by jxpsert** [comment]
Culprit is line 92 in Resources.tsx
Should probably add month translations to the locale files, just like the days are.

https://github.com/usememos/memos/blob/a928c4f845891fbef9c3eeefb4860ff923bb3488/web/src/pages/Resources.tsx#L92C20-L92C124

**Comment by diomed** [comment]
damn. I really thougth months are covered. :|
