### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by HubKing** [usememos/memos#2285]
### Is your feature request related to a problem?

Users could overwrite something important and save it by mistake, and may want to see what was overwritten and maybe even want to revert the changes.

### Describe the solution you'd like

Some sort of versioning. It could be simply creating a copy of the text before saving changes made to the text. Users could set if they want to enable this or not, or how many copies will be preserved.

**Comment by q2apro** [comment]
In other apps, something like this is mostly achieved by plugins. 

But yes, this would be a great feature: Revision History for Memos.

**Comment by 0xorial** [comment]
This would be sooo great!
