### ISSUE TITLE
Back to top button

### ISSUE THREAD

**Issue by diomed** [usememos/memos#2287]
### Is your feature request related to a problem?

There should be back to top button.

### Describe the solution you'd like

- back to top solution with svg image
```
<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-circle-chevron-up" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
   <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
   <path d="M9 13l3 -3l3 3"></path>
   <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path>
</svg>
```

**Comment by boojack** [comment]
As you wish. https://github.com/usememos/memos/commit/952225d1da1df925040c11393141af87418f5412

<img width="955" alt="image" src="https://github.com/usememos/memos/assets/24653555/9bb0f26a-7147-487d-bd69-d496dabbc52c">
