### ISSUE TITLE
为什么我资源库里面的资源很多都看不到了？

### ISSUE THREAD

**Issue by mygit20230606** [usememos/memos#2289]
### Describe the bug

我在资源库里面放了很多图片资源，我一般都是先把图片手动添加到资源库，然后在memos里面 用![图片](url)的方式嵌入到memos里面，我发现我打开资源库都看不到了，另外怎么手动添加资源？ 不在memos正文里面添加

### Steps to reproduce

略

**Comment by tnnevol** [comment]
资源看不到了，但是还能访问

**Comment by mygit20230606** [comment]
> 资源看不到了，但是还能访问

对  并且清理未使用资源也是  只把资源用链接的方式放在memos里面 是识别不到被引用的 会被清理

**Comment by boojack** [comment]
The `[](http://the-link-to-your-resource)` syntax is not recommended as it's impossible to get the relation between memo and resource. 

Those unused resources will be shown in the following section.

<img width="1008" alt="image" src="https://github.com/usememos/memos/assets/24653555/201911e1-6bb3-4bb1-90e0-8ccda54fc21a">

**Comment by mygit20230606** [comment]
> The `[](http://the-link-to-your-resource)` syntax is not recommended as it's impossible to get the relation between memo and resource.不建议使用 `[](http://the-link-to-your-resource)` 语法，因为不可能获取备忘录和资源之间的关系。
> 
> Those unused resources will be shown in the following section.这些未使用的资源将在下一节中显示。
> 
> <img alt="image" width="1008" src="https://user-images.githubusercontent.com/24653555/272752838-201911e1-6bb3-4bb1-90e0-8ccda54fc21a.png">

新版本，资源库依然不能高效的管理资源啊 例如删除单个资源，，我喜欢用语法链接的方式在memos里面嵌入资源，因为那样我可以随心所欲的把资源放在正文里的任何位置，而不是最后
