### ISSUE TITLE
找不到Memos Access Tokens

### ISSUE THREAD

**Issue by zhongbuliu** [usememos/memos#2296]
### Describe the bug

我的设置里只有OpenAPI，没有Memos Access Tokens

### Steps to reproduce

![image](https://github.com/usememos/memos/assets/66763831/b4dfee8e-1a31-4142-840e-8e931e013aeb)

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/66763831/09a4c832-8b8a-4144-aa7e-58bea8ff6933)

**Comment by boojack** [comment]
Upgrade your version to `0.15.x` if you need access tokens
