### ISSUE TITLE
当上传的附件是html/htm时，直接点击附件链接能不能显示成页面，而不是显示出单纯的文本？

### ISSUE THREAD

**Issue by iampcfox** [usememos/memos#2297]
这个是我自己的解决方法：https://me.96e227.cc/m/125
希望memos也可以根据附件类型来决定附件的响应头类型

**Comment by iampcfox** [comment]
![image](https://github.com/usememos/memos/assets/25996313/f1c1fe71-6553-4470-9a98-6013d5319473)
This is my own solution

**Comment by boojack** [comment]
For security reasons, it's not supported for now.
