### ISSUE TITLE
[BUG] Failed to fetch memo list

### ISSUE THREAD

**Issue by devioa** [usememos/memos#2301]
```
method=GET uri=/api/v1/memo?creatorUsername=***&rowStatus=NORMAL&limit=20 status=500 error=code=500, message=Failed to fetch memo list, internal=SQL logic error: no such column: resource.memo_id (1)
```
![image](https://github.com/usememos/memos/assets/38558065/195f73cc-fb23-410d-9d60-e8550ce1f761)

built from source code with latest commit c54febd024c7ec8a37a358c3b07c1c1bbd88a79c

**Comment by boojack** [comment]
The main branch is under development and not for production. If you still want to use it, you should run memo in `dev` mode instead of `prod`.
