### ISSUE TITLE
pinned item isnt pined in frontend

### ISSUE THREAD

**Issue by diomed** [usememos/memos#2302]
### Describe the bug

why is it when I pin item, it's pinned only in backend,  and surely I see it pinned, but it isnt pinned at all in frontend.
that's not expected behavior. it's suppposed to be pinned and seen as first by whoever opens up app.

### Steps to reproduce

- pin item
- open app with another browser or in incognito  - item is not displayed as first at all

**Comment by Zeng1998** [comment]
Are you sure? Can you reproduce this on the demo site?

**Comment by diomed** [comment]
> Are you sure? Can you reproduce this on the demo site?

I wouldnt rreport it if I wasnt sure.
https://memoi.zeabur.app/explore
![2023-09-28 08 40 31 memoi zeabur app 156ee3bc310b](https://github.com/usememos/memos/assets/72777/f97d4ada-e713-4fe6-a25c-c885c35a5086)

**Comment by boojack** [comment]
The first memo is pinned as it has same border style as editor. We'll update the style later to make sure it's more visible.

<img width="526" alt="image" src="https://github.com/usememos/memos/assets/24653555/db83d874-f51e-4184-b78b-1a3cc485af89">

**Comment by diomed** [comment]
> The first memo is pinned as it has same border style as editor. We'll update the style later to make sure it's more visible.
> 
> <img alt="image" width="526" src="https://user-images.githubusercontent.com/24653555/272753207-db83d874-f51e-4184-b78b-1a3cc485af89.png">

You dont seem to understand. 

This is a bug!!!

When I mark my item as PINNED it should display as **FIRST** - above everything else!

This **does not happen** at the moment.

- yes, in backend it does happen , **but it does not happen in the frontend** where it just treats it like it was never checked.
