### ISSUE TITLE
Double click to edit time does not work anymore

### ISSUE THREAD

**Issue by maticboncina** [usememos/memos#2306]
### Describe the bug

We used to be able to double-click on the "timestamp" entry to adjust the time when the memos were supposed to be recorded.

This is no longer possible and it simply redirects you to the note itself. Seems like it broke after the last update. 

The expected behavior is that it shows a popup where the date could be edited. I have "allow double click" to edit turned on.

### Steps to reproduce

Video:

1. Make a memos
2. Try double-clicking to edit the timestamp
3. You will see that it opens a memos in full screen mode instead of popup where the time could be eidted.

### Screenshots or additional context

Video of the issue and steps to reproduce: 

https://github.com/usememos/memos/assets/54638868/f35529c9-5049-4603-8e9e-71feccb1a442

**Comment by boojack** [comment]
Try to single click with `alt` pressed?

**Comment by maticboncina** [comment]
> Try to single click with `alt` pressed?

Got it, thank you. For those looking it's the left "option" key on the Mac systems.

**Comment by TheNomad11** [comment]
whatever I try to do editing the date is not possible (Dell, Linux Mint)
