### ISSUE TITLE
[Feature] Colors ? 💯 

### ISSUE THREAD

**Issue by ckocyigit** [usememos/memos#2312]
### Is your feature request related to a problem?

Colors would be nice to have :)

### Describe the solution you'd like

Maybe via a markdown processor which allows inline HTML?

**Comment by sifanx** [comment]
字体变颜色的语法是这样的
$\color{red} {这里填上你需要显示红色的字体} $

**Comment by jhademcconnell** [comment]
@ckocyigit the syntax to show a colored text was shared. You can try in your Memos instance:

> $\color{red} {这里填上你需要显示红色的字体} $

Could you please mark this issue as completed/closed?
