### ISSUE TITLE
"Visible to Members" not working

### ISSUE THREAD

**Issue by dsouzadrian** [usememos/memos#2313]
### Describe the bug

Posts created by one user with "Visible to members" visibility aren't visible by other members.
Posts set as "Public" are also not visible to other members once signed in.
Am I misunderstanding how visibility is supposed to work in Memos. These posts are available under the "Explore" tab, just not showing up in the home feed.

### Steps to reproduce

1. Log in as User 1
2. Create a post. Set visibility to "Visible to Members".
3. Create another post and set visibility to  "Public".
4. Open an incognito window and navigate to your memos instance.
5. The public post is visible without logging in.
6. Log in as User 2.
7. Both posts are not visible to user 2 once logged in.
8. I'd expect both posts to show up in User 2's home feed.

**Comment by boojack** [comment]
> User 2's home feed

Home page only show yourself data. You can see other users in Explore page.
