### ISSUE TITLE
四张图片有一张不显示

### ISSUE THREAD

**Issue by jxjxjhjh** [usememos/memos#2315]
### Describe the bug

外链图片，源地址看过正常，之前半个月正常，今天一看有一张图不显示了，怎么刷新都没用。
本来之前上传图片的时候就很有问题，无论是外链、本地、s3都会出现显示不了的问题。
另外，现在的版本已经没法在资源库中删除无效资源了，也无法点击无效资源跳转到条目上通过编辑上传。

### Steps to reproduce

https://191954.xyz/explore

**Comment by boojack** [comment]
Please make sure it's a memos bug when creating the issue. 🙏

<img width="1022" alt="image" src="https://github.com/usememos/memos/assets/24653555/033242a9-b1bd-40d1-83be-1b2d9009a902">
