### ISSUE TITLE
Fix weblate

### ISSUE THREAD

**Issue by jxpsert** [usememos/memos#2317]
### Describe the bug

Until quite a while ago, there was an instance of Weblate connected to memos, to translate into different languages. It's been broken due to merge problems.

Current locale files are out of sync. Keys exist in nl.json that don't in en.json, and vice versa. This (can) result(s) in translation issues for some languages.

### Steps to reproduce

 The weblate URL is here: https://hosted.weblate.org/projects/memos/
 The alert shows it happened 6 months ago.

**Comment by boojack** [comment]
> The weblate URL is here: https://hosted.weblate.org/projects/memos/

This may not be maintained anymore, please use the code file as the main guide.

**Comment by jxpsert** [comment]
Using the locale files is incredibly complicated and inaccurate. There's keys that are in different orders and no easy way to copy over new keys to all files.

**Comment by boojack** [comment]
Done: https://hosted.weblate.org/projects/memos-i18n
