### ISSUE TITLE
分享功能被砍了？

### ISSUE THREAD

**Issue by huhexian** [usememos/memos#2318]
### Describe the bug

![image](https://github.com/usememos/memos/assets/42113492/7dc458a2-82d0-4930-b8f8-6ea9762631bf)
原本有分享功能，现在没有了。

### Steps to reproduce

go to...

**Comment by boojack** [comment]
You can go to the memo details page to get the share button. https://demo.usememos.com/m/1

<img width="737" alt="image" src="https://github.com/usememos/memos/assets/24653555/022dbc3c-4542-482b-94f1-9f3bddb5536a">

**Comment by huhexian** [comment]
进入详情页再分享，这不是多此一举吗？
要么就都取消分享，要么就在原来的位置添加分享。现在这个操作难以理解。
