### ISSUE TITLE
Use Front Matter for tags

### ISSUE THREAD

**Issue by helmut72** [usememos/memos#2319]
### Is your feature request related to a problem?

Having tags anywhere in a page with a `#` char is error prone. Eg. I've added a bookmark:

<img width="637" alt="Bildschirmfoto 2023-09-30 um 13 57 45" src="https://github.com/usememos/memos/assets/1388751/fa2d9d7c-4590-4263-8b35-e7c7f28ccd84">

Now I have this tag (and I don't want it):

<img width="213" alt="Bildschirmfoto 2023-09-30 um 13 58 08" src="https://github.com/usememos/memos/assets/1388751/abc7bb87-ff07-415b-9066-8ae37d42c2cf">

### Describe the solution you'd like

Use Front Matter for metadata like tags, titles, dates...
https://gohugo.io/content-management/front-matter/

**Comment by nalderto** [comment]
Looks like pound signs in URLs no longer get parsed as a tags in Memos :rocket: 
![image](https://github.com/usememos/memos/assets/25762130/414c1144-214e-4449-8d54-5fca069dd1de)

**Comment by helmut72** [comment]
Thank you, looks good! But this is just one example of many. If I write something by #mistake, the tag `#mistake,` is added.
Or when I just copy/paste from somewhere where `#another` mistakes are included. My tags exploding.

This type of tagging is error prone and imho something better exists. Front matter. This is why I think the issue isn't resolved.

**Comment by helmut72** [comment]
One more example is here #2689 
Now I have `#2689` in my tags.
