### ISSUE TITLE
Telegram bot如何用？

### ISSUE THREAD

**Issue by penndu** [usememos/memos#2322]
已通过https://www.jianshu.com/p/667d2f27d74d搭建代理。
已获取TOKEN
![image](https://github.com/usememos/memos/assets/46226528/fa051648-11f2-4935-9d99-d26be011c77f)
但是设置完成后没能获取userid。
![image](https://github.com/usememos/memos/assets/46226528/46558096-725d-4ffe-8dd1-be0dfe33bbb0)

**Comment by boojack** [comment]
<img width="693" alt="image" src="https://github.com/usememos/memos/assets/24653555/b2ac7de0-31b9-47ff-9d18-59406f848fc4">

Reference: https://usememos.com/docs/integration/telegram-bot

**Comment by antitiron** [comment]
Hi!

Same problem, but the token is set correctly.

![2023-10-11 09-16-14 osu-memos - Google Chrome](https://github.com/usememos/memos/assets/7191601/51f21e57-31e5-4dc5-b842-0ddd12c57ab5)
![2023-10-11 09-16-40 memos_osu @ Igor Menshchikov](https://github.com/usememos/memos/assets/7191601/13264510-60b4-404c-a03d-6ccfe0f64d66)

**Comment by iqyiqy** [comment]
我也出现同样问题。
cloudflare反代的似乎有问题。可能代码不够bug？
最后使用国外服务器nginx反代一下api就行了。
但是这样的话，其实也可以直接部署在国外服务器。
