### ISSUE TITLE
Reinstate arm/v7 support for docker images

### ISSUE THREAD

**Issue by 82MHz** [usememos/memos#2324]
Commit https://github.com/usememos/memos/commit/0a811e19ba1b2575719fbe18471cbab53917df4e removed support for docker images on the arm/v7 platform with no reason given. 

I was using this on my raspberry pi and can't get updates anymore. If there is no functional reason behind this decision, I'd ask to reinstate arm/v7 support.

**Comment by cadamsdev** [comment]
Having same issue as well on my raspberry pi. I would like this as well. @boojack

**Comment by boojack** [comment]
Sorry, tried to add it back but the build failed due to missing dependencies.

https://github.com/usememos/memos/actions/runs/6593960554/job/17917230538#step:9:1145

**Comment by JuanIgnaciosj** [comment]
So finally that will be this never i'll back again?
