### ISSUE TITLE
RSS中的link希望改为当前网址的域名

### ISSUE THREAD

**Issue by ridd1ot** [usememos/memos#2327]
### Describe the bug

希望可以把https://xxxxxxxx/u/1/rss.xml中的link希望改为当前网址的域名

I would like to change the ip of the URL in the RSS to the domain name of the current URL.

### Steps to reproduce

https://xxxxxxxx/u/1/rss.xml

### Screenshots or additional context

![屏幕截图 2023-10-03 174625](https://github.com/usememos/memos/assets/25028968/9b34bc5d-4e3d-4c18-a2ff-b4ac0b7cbb78)

**Comment by boojack** [comment]
It actually is the domain name from your request and works normal in demo site. https://demo.usememos.com/u/101/rss.xml

reference: https://github.com/usememos/memos/blob/main/api/v1/rss.go#L55
