### ISSUE TITLE
Put resources into text

### ISSUE THREAD

**Issue by pztrn** [usememos/memos#2328]
### Is your feature request related to a problem?

I'm unable to put images right into text, only attach to post as resource.

### Describe the solution you'd like

Ability to put images into text like:

> Some text.
> 
> pic here
>
> Some other text.

### Additional context

Memos v0.15.2 in Docker.

**Comment by boojack** [comment]
You can use `[](http://the-link-to-your-resource)` to embed your images into content, but not recommended as it's impossible to get the relation between memo and resource.

<img width="655" alt="image" src="https://github.com/usememos/memos/assets/24653555/b1c72be8-df85-4202-ab26-ddbe2ffc1664">

**Comment by pztrn** [comment]
That's why I requested builtin way which will support renaming.

Without that functionality memos less useful for public notes, e.g. "Set up OSPFv3 on mikrotik" which will require screenshots of winbox app in proper places.

**Comment by boojack** [comment]
> That's why I requested builtin way which will support renaming.

No, you don't need to filename at the link of resource. Just an integer id `http://domain/o/r/{id}`
