### ISSUE TITLE
附件支持一次选择多个

### ISSUE THREAD

**Issue by postblue** [usememos/memos#2330]
### Is your feature request related to a problem?

附件功能，我想要一次性可以选择多个文件。 假如我有9张图片，我要重复9次才能添加完，太浪费时间

### Describe the solution you'd like

附件功能，我想要一次性可以选择多个文件。 假如我有9张图片，我要重复9次才能添加完，太浪费时间

**Comment by boojack** [comment]
Already supported.

<img width="675" alt="image" src="https://github.com/usememos/memos/assets/24653555/a1e9e74b-4272-4bd0-a806-5af1b24346bd">

**Comment by postblue** [comment]
我没找到批量上传的入口。 请看我操作的gif图片。
![未支持批量上传](https://github.com/usememos/memos/assets/39828275/7e2489d5-41fe-4fba-a58b-e91847a8cfa7)
