### ISSUE TITLE
After access token expires you can still view and edit notes - potentially a security issue

### ISSUE THREAD

**Issue by meldarionqeusse** [usememos/memos#2331]
### Describe the bug

If the access token expires and notes are still visible you can edit notes. The missing token error message will appear however once you log in you initially do not see the edit but if you edit the same note you can see that the edit indeed took place. I can only replicate the issue with the admin account the one that shows mod.

### Steps to reproduce

- Log in with admin account and create and save a note (Screenshots do not show my admin account )

![image](https://user-images.githubusercontent.com/21668964/272504905-567d9cab-0815-480f-8bfc-c5a55021072b.png)

- Go to Settings > my account and delete the access token used to log in
![image](https://user-images.githubusercontent.com/21668964/272505131-203633a6-9e14-48a4-ae61-4712114f4474.png)

- Click on Name at the top left where the memos icon is and go to profile

![image](https://user-images.githubusercontent.com/21668964/272505238-bf9811c1-f82c-43b6-a178-1d8d12bf27b5.png)

- you will see all the notes, click on the three dots and you can edit the note

![image](https://user-images.githubusercontent.com/21668964/272505294-d758724a-0783-4434-9935-967731eeca82.png)

![image](https://user-images.githubusercontent.com/21668964/272505488-88f420a5-2dd6-45de-a0ba-2f6023539d35.png)

- Missing token error will appear

![image](https://user-images.githubusercontent.com/21668964/272505430-173cc367-3cbf-453d-9540-5cc44db0e194.png)

- Reload and Sign in again you will see the note which does not show the edit however if you edit the note you will be able to see the edit that you made when the access token was supposed to be missing. 

![image](https://user-images.githubusercontent.com/21668964/272507731-da0995d3-f1cf-45f7-aac3-02befa202c76.png)

![image](https://user-images.githubusercontent.com/21668964/272507763-9cef1379-cbed-481d-9b3c-18e353172d75.png)

### Impact

If you log into a public computer and forget to logout someone could access your information even if you remove the access token to that computer.

**Comment by boojack** [comment]
@meldarionqeusse Thanks for such a detailed description. I tried it on the [demo site](https://demo.usememos.com/) and found that it couldn't be reproduced.

**Comment by meldarionqeusse** [comment]
I can reproduce it with my account on my instance. I am running the arm version not sure if that's any different. I will try to find some time to do some more investigation this weekend maybe set up another instance and I will report back with the findings.

**Comment by boojack** [comment]
> I noticed the demo is running v0.16 I am running v0.15.2 maybe it has been fixed in v0.16?

There are no associated changes in `v0.16.0`. So please try again on the demo site.

**Comment by meldarionqeusse** [comment]
I have done some quick experimenting. I removed the access token I edited the note saved got the missing token and then I looked at the note from another device and I did not see the edit. When I signed back from my primary device and hit edit I saw the edit there. 

I cannot replicate the behavior on the demo. However what I can replicate on the demo is the fact that if you remove the access token you or log out and go to profile you can still see the notes which might still be a security concern. This is especially true if you have a single not which is publicly available anyone would be able to click on the image at the top left corner hit profile and view all your notes.

Currently log out of the demo
![image](https://github.com/usememos/memos/assets/21668964/da780d6f-94f1-4c08-8644-614755ddc84a)

I go to profile
![image](https://github.com/usememos/memos/assets/21668964/ce23cd69-1719-4433-9fca-f446594e0811)

and I can see all the notes
![image](https://github.com/usememos/memos/assets/21668964/2982a582-8453-41f2-8199-efce2f38afda)

If I clear the cache I end up with this I am not sure if it would be possible to implement something to get to this state where the profile button is not available once logout/remove access token. I am not sure if there's a way to force a clear cache once you logout.
![image](https://github.com/usememos/memos/assets/21668964/36a0c81b-2793-4174-890d-fe2a337a6115)

**Comment by boojack** [comment]
> However what I can replicate on the demo is the fact that if you remove the access token you or log out and go to profile you can still see the notes which might still be a security concern.

This is expected. Currently there is no need to regularly check whether the token has expired in web. But we can do this feature later when we have enough development resources. However, thanks for the report.
