### ISSUE TITLE
 Issue with Database Upgrade to v0.16.0 and Data Loss

### ISSUE THREAD

**Issue by erbanku** [usememos/memos#2334]
### Describe the bug

Hi there,

I have upgraded my instance to version v0.16.0 of the Memos instance and encountered some issues with my database. Unfortunately, my instance data seems to have disappeared after the upgrade, and I am also being prompted to sign up again.

Fortunately, I backed up my database before the upgrade, but I am unsure how to restore and resolve it. I would greatly appreciate any guidance or instructions you can provide to help me resolve this situation.

Thank you for your assistance in advance.

### Steps to reproduce

Simply upgrade the docker container instance to v0.16.0

**Comment by boojack** [comment]
> I have upgraded my instance to version v0.16.0 of the Memos instance and encountered some issues with my database.

What's the error message of `some issues`?

> Fortunately, I backed up my database before the upgrade, but I am unsure how to restore and resolve it. I would greatly appreciate any guidance or instructions you can provide to help me resolve this situation.

To restore your database, you can just directly replace the existing file with your backup database file.

**Comment by erbanku** [comment]
I have successfully restored my instance after deploying again and overwriting database files. Thanks anyway.
