### ISSUE TITLE
插入外链视频无法正常播放

### ISSUE THREAD

**Issue by beiminglongkun** [usememos/memos#2341]
### Describe the bug

插入外链视频不显示。
视频链接：https://txmov2.a.kwimgs.com/upic/2023/02/14/16/BMjAyMzAyMTQxNjQyMThfMTQwNzc4Njk4N185NjIwNTY3OTQyNV8xXzM=_b_Bb37e7971032420ce77672984a7930a51.mp4
视频资源本身无任何限制，通过下方操作无法正常播放视频。
![Snipaste_2023-10-07_00-59-27](https://github.com/usememos/memos/assets/55775124/a81814b7-e238-4144-bcf5-c8a1ceccc44f)
但通过调试，直接使用video标签插入src值可以正常播放视频：
![1](https://github.com/usememos/memos/assets/55775124/09ee0d42-26b1-42f2-8f06-d36f4b0b6607)

### Steps to reproduce

![Snipaste_2023-10-07_00-49-01](https://github.com/usememos/memos/assets/55775124/4050bd46-8d2d-4536-a22b-b71089e3e5e8)

**Comment by boojack** [comment]
Fixed in https://github.com/usememos/memos/commit/73980e9644dd3978753328912f7c454a3f45cd67
