### ISSUE TITLE
support comment from anonymous visitor

### ISSUE THREAD

**Issue by xu4wang** [usememos/memos#2344]
### Is your feature request related to a problem?

Just tried the brand new comment feature (V0.16.0), I am not able to add a comment without log in.

Is it by design?

### Describe the solution you'd like

 possible to support adding comment from anonymous visitor? I'm thinking to use memos as blog.

**Comment by beiminglongkun** [comment]
如果后期要开发游客评论，最好配套对应的审核系统，例如必须先审核后发布，或者当内容中存在链接进行审核等，以保证不被广告或者垃圾信息侵扰。
