### ISSUE TITLE
Multiple tag filter

### ISSUE THREAD

**Issue by m-arabi** [usememos/memos#2345]
### Is your feature request related to a problem?

Currently not able select multiple tags for filter.
If I select one tag for filter and then select the second one, first selected tag filter is replaced with second tag.

### Describe the solution you'd like

Need to able to select multiple tags for filter.

**Comment by rheicide** [comment]
This would be very nice to have. Hopefully it'll be implemented soon 🤞🏽

**Comment by erauner12** [comment]
Can we re-open this one? Having multiple tags would be amazing. For the timeline view specifically.
