### ISSUE TITLE
Failed to create resource in MySQL

### ISSUE THREAD

**Issue by alex-guoba** [usememos/memos#2346]
### Describe the bug

{"time":"2023-10-07T17:14:21+08:00","method":"POST","uri":"/api/v1/resource/blob","status":500,"error":"code=500, message=Failed to create resource, internal=Error 1406 (22001): Data too long for column 'blob' at row 1"}

 
Max size for mysql blob field is 64 Kb, should we modify blob column  to  `MEDIUMBLOB ` type ? 

https://www.tutorialspoint.com/What-is-the-maximum-length-of-data-we-can-put-in-a-BLOB-column-in-MySQL

### Steps to reproduce

1: storage setting to `database`
2: upload a image of 77K size

### Screenshots or additional context

<img width="268" alt="image" src="https://github.com/usememos/memos/assets/2872637/01528329-4e32-4736-b950-ae1697285748">

**Comment by boojack** [comment]
Good catch, thanks for the report. MySQL support is under active development.

**Comment by boojack** [comment]
Fixed in https://github.com/usememos/memos/commit/553de3cc7e37a55a587c357ed665b419fcd70020
