### ISSUE TITLE
TODO 无法勾选或取消

### ISSUE THREAD

**Issue by Rookiewan** [usememos/memos#235]
#### 问题
TODO 保存编辑后，无法勾选或取消

#### 版本
0.4.4-prod

#### 复现步骤
1. 创建 TODO `- [ ] xxxx`， 并保存
2. 列表中点击复选框，无法勾选，无报错（上个版本可以正常使用）

#### 期望
跟之前一样可以勾选或取消

**Comment by boojack** [comment]
Thanks for your report. It has been fixed and will be updated in the next release.
