### ISSUE TITLE
Dark mode is no longer persistent

### ISSUE THREAD

**Issue by mariushosting** [usememos/memos#2351]
### Describe the bug

I set dark mode in the settings, when I log out the theme is back again to light mode.

### Steps to reproduce

I set dark mode in the settings / preferences, when I log out the theme is back again to light mode. So the dark mode is not persistent if you click sign-out and you are not logged in.

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/3ff4d197821b9c7932e4ede0c85ef943049fb9b4

**Comment by DerTobi75** [comment]
Dark Mode still switches back to "Follow System" when you open your timeline.
Version 0.18.2
