### ISSUE TITLE
今日回顾功能默认显示逻辑

### ISSUE THREAD

**Issue by beiminglongkun** [usememos/memos#2368]
### Is your feature request related to a problem?

今日回顾默认显示当天的内容

### Describe the solution you'd like

今日回顾Web端现在默认显示的是上次选择的日期的回顾内容。
顾名思义，今日回顾今日回顾，默认显示的应该是当天内容。
若当天没有则建议显示最近更新一天的内容，而不是上次选择的日期的内容。

**Comment by boojack** [comment]
Maybe fixed in the latest version.
