### ISSUE TITLE
上传mkv视频后无法预览播放

### ISSUE THREAD

**Issue by Yuansheng-Liang** [usememos/memos#2376]
### Describe the bug

上传mkv视频后无法预览播放

### Steps to reproduce

1. 上传mkv视频
2. 查看这条笔记
3. 
![image](https://github.com/usememos/memos/assets/54231251/46844dae-d357-4ae1-a222-315be6101830)

**Comment by boojack** [comment]
Maybe the browser is not supported for MKV.

<img width="689" alt="image" src="https://github.com/usememos/memos/assets/24653555/12b83458-2083-4cb1-b408-fa9f7cf389da">
