### ISSUE TITLE
新建编辑笔记时无法全屏放大编辑

### ISSUE THREAD

**Issue by Yuansheng-Liang** [usememos/memos#2377]
### Describe the bug

新建编辑笔记时无法全屏放大编辑

### Steps to reproduce

新建编辑笔记时无法全屏放大编辑
![image](https://github.com/usememos/memos/assets/54231251/341c4782-b467-46f3-b0a3-cf2455ccedc6)

**Comment by WaaSakura** [comment]
Yes, the content is squeezed together during editing

**Comment by boojack** [comment]
Stay tuned on #2270
