### ISSUE TITLE
Long LaTeX expressions cause entire Memos UI to stretch

### ISSUE THREAD

**Issue by ganyuke** [usememos/memos#2379]
### Describe the bug

Entering a long LaTeX expression into a memo body causes the interface to expand to the point that you need to horizontally scroll. It will also prevent you from posting new notes because when you scroll over and click the Save button, it just scrolls you back to the left edge without doing anything.

Side note, found this while writing some notes involving money. Is there a way to escape the LaTeX for situations like that?

### Steps to reproduce

1. Create a new memo.
2. Type in a really long string surrounded by $ symbols.
3. Post the memo.

### Screenshots or additional context

Tested on the demo instance:
![memos-stretch-1](https://github.com/usememos/memos/assets/95439147/21ac85ea-f544-473e-b4db-0ff834eb5558)
![memos-stretch-2](https://github.com/usememos/memos/assets/95439147/6810cc0a-070a-4677-981f-b3a4f6535820)
![memos-stretch-3](https://github.com/usememos/memos/assets/95439147/1ddc6467-5bd0-4efa-8ddf-46ddc1404b0f)

**Comment by Zeng1998** [comment]
I don't think latex formulas can wrap automatically.

**Comment by boojack** [comment]
Fixed in https://github.com/usememos/memos/commit/20e5597104c4349df61c112899fab42227ad8c19

<img width="1056" alt="image" src="https://github.com/usememos/memos/assets/24653555/74d159ee-76ce-478f-99d4-a37a819da780">
