### ISSUE TITLE
官网无法登录/注册 Unable to login/signup

### ISSUE THREAD

**Issue by yoghurtlee-thu** [usememos/memos#2386]
### Describe the bug

这是我第一次使用这个项目。我想在网页端注册一个账号，然而总是提示"signup disabled".后来我下载了memos desktop，在那里成功注册了账号，但是回到网页端登录时，却提示“Incorrect login credentials, please try again”，反复试验多次都没有解决，请问这是一个bug吗？还是我操作的问题？

This is my first time using this program. I tried to register an account on the website, only to receive "signup disabled". Later I downloaded memos desktop and successfully registered an account there, but when I tried
 to login on the website, I was prompted with "Incorrect login credentials, please try again", which was not resolved even after repeated attempts. Is this a bug? Or is it all my fault?

### Steps to reproduce

1. 进入[网站](https://usememos.com/)
2. 点击Live Demo
3. 进入示例后点击登录
4. 将用户名和密码改为自己的个人用户名和密码/在"注册"中输入用户名和密码
5. 报错

---

1. Go to the [website](https://usememos.com/)
2. Click on "Live Demo"
3. Click on "Sign in" after entering the demo
4. change the username and password to my own/Enter your username and password in the "Sign up" page
5. See an error

### Screenshots or additional context

<img width="431" alt="image" src="https://github.com/usememos/memos/assets/146422759/7fd4f451-9168-4712-877f-9c9ed9d2f558">

**Comment by Zeng1998** [comment]
Your memos site, the demo site, and the memos desktop are three **different** instances.
