### ISSUE TITLE
Is there a way to set expires of login ?

### ISSUE THREAD

**Issue by mebtte** [usememos/memos#2388]
### Is your feature request related to a problem?

When I open the `memos` after days of login on web browser, it's unauthorized. I must re-login by entering username and password, it's  annoying. Is there a way to set expires of login, so I can skip the repeated and repeated login every few days ?

> I only see the setting of access token's expires, but I don't know how to login by token on browser.

### Describe the solution you'd like

On the setting page, It has a configuration of login's expires which can be set as custom duration or infinity.

**Comment by jl-678** [comment]
I completely agree with this. The constant logging out of the client is frustrating. It would be great to be able to set login expiration with the option of extending it longer or even infinite.

As an aside, I do see multiple access tokens listed with the expiration of "never", but my logins still expire.
