### ISSUE TITLE
I hope the search can support archive memo, or the archive page also provides a search box

### ISSUE THREAD

**Issue by Crazyokd** [usememos/memos#2398]
### Is your feature request related to a problem?

I'll archive memos that make sense. So when searching for a memo, there's a good chance that the result I'm looking for will already be archived. But currently only the home page memo search is supported.

### Describe the solution you'd like

I hope the search can support archive memo, or provide a search box for the archive page.

### Additional context

My memos version is `v0.15.2`.

**Comment by q2apro** [comment]
To search through archived notes is **absolutely necessary**.

Like in all other note taking apps I know.

Please add this with high priority.

**Comment by boojack** [comment]
Updated in https://github.com/usememos/memos/commit/2a4ebf5774c3b622d5e03f2811e8f67aef59bbcd
