### ISSUE TITLE
兼容性问题，更新后有些手机上打不开了

### ISSUE THREAD

**Issue by wangwanjie** [usememos/memos#2400]
### Describe the bug

<img width="907" alt="iShot_2023-10-18_11 37 57" src="https://github.com/usememos/memos/assets/15172899/c24edb85-c6c7-4cd0-902a-96440073708d">

### Steps to reproduce

在 iOS 13.3.1  safari 和 chrome 都打不开页面了

**Comment by boojack** [comment]
> 在 iOS 13.3.1 safari 和 chrome 都打不开页面了

Maybe try to upgrade your system OS.
