### ISSUE TITLE
How to restore a backup?

### ISSUE THREAD

**Issue by ik3r4b** [usememos/memos#2406]
### Describe the bug

I have deleted my memos docker container but i have backup of all 
![image](https://github.com/usememos/memos/assets/73933049/adea7ea8-3757-42ec-81ec-d2870b61bae7)

how to restore that backup in a new container? putting that files in the .memos directory doesn`t work

### Steps to reproduce

.

**Comment by haitispaceagency** [comment]
Did you ever figure this out? 

I started a new instance of memos and was able to put all of my notes into it and it worked fine, but i've been trying to do that again like, 3 weeks later and it isn't working (or i just forgot what I did)

**Comment by 20kaushik02** [comment]
https://www.usememos.com/docs/install/upgrade#manual-upgrade

Backup: Stop, copy, start
Restore backup: stop, copy back, start...?

**Comment by RoccoSmit** [comment]
For local storage copy the assets folder as well
