### ISSUE TITLE
分享保存的海报里面不显示图片

### ISSUE THREAD

**Issue by Duinks** [usememos/memos#2411]
### Describe the bug

![IMG_2034](https://github.com/usememos/memos/assets/43784195/6aad4b77-b9fe-4218-8af9-33f70963fcca)
![memos-2023_10_20 19_29_50](https://github.com/usememos/memos/assets/43784195/86c6d83f-0b70-4f2e-9884-7383f1fc4ed9)

### Steps to reproduce

刚开始我以为是跨域问题，没想到试了一下本地图片，也是这样

**Comment by boojack** [comment]
Cannot reproduce in demo site.

<img width="1044" alt="image" src="https://github.com/usememos/memos/assets/24653555/2e01d069-3bce-4f0f-8fb0-c57a082c577e">
