### ISSUE TITLE
Memos 评论系统能否直接接入第三方评论系统呢？

### ISSUE THREAD

**Issue by lmm214** [usememos/memos#2416]
### Is your feature request related to a problem?

Memos 评论系统能否直接接入第三方评论系统呢？

### Describe the solution you'd like

接入现有第三方评论如： artalk、twikoo
后台设置里留个评论的css、js开启设置，前端加上对应dom，系统级加入第三方评论。

**Comment by supersu097** [comment]
it's a good idea, i think there is no need to implement the comment functionality by memos itself, coz too much dirty work which needs to do, it's better to directly leverage the 3rd party's power to integrate a comment plugin.

**Comment by annieappflowy** [comment]
https://help.disqus.com/en/articles/1717053-what-is-disqus
Is it feasible to integrate Disqus
