### ISSUE TITLE
希望使用对象存储时，附件的地址能使用 相对路径

### ISSUE THREAD

**Issue by iqyiqy** [usememos/memos#2419]
### Is your feature request related to a problem?

目前文件上传之后，网址是写死固定的。
如果使用的对象存储搬家，或者更换域名。导致之前的文件，图片就不能访问了。
只能手动修改数据库，批量替换域名的前缀。

### Describe the solution you'd like

不知道是否能够写成相对路径，然后根据端点（Endpoint）或者自定义的URL 前缀，拼接出网址。

**Comment by okhanyu** [comment]
支持，也希望附件使用相对路径
