### ISSUE TITLE
Can memos support modifying the default token expiration time?

### ISSUE THREAD

**Issue by NPCDW** [usememos/memos#2424]
### Is your feature request related to a problem?

I want to set a default expiration time of 12 hours on my work computer and never expire on my personal computer, just like the `bitwarden` browser plugin

### Describe the solution you'd like

memos can modify the default expiration time of token and save it on the browser
![image](https://github.com/usememos/memos/assets/32638459/2762ef87-c5fb-4776-be5e-8120b64af4d2)

**Comment by boojack** [comment]
Refer to #984
