### ISSUE TITLE
Android Chrome: PWA broken after upgrading to v0.16.1

### ISSUE THREAD

**Issue by samuelthng** [usememos/memos#2425]
### Describe the bug

PWA install button no longer shows up on android Chrome.

### Steps to reproduce

1. Host memos v0.16.1 on docker with SSL
2. Navigate to hosted site
3. Note that Install App button no longer shows, this was previously working.

### Screenshots or additional context

https://github.com/usememos/memos/assets/19360561/5b2c7f52-6619-4bdb-a5c3-a1c0a0e87bf5

P.S. I like the logo. It's very cute. 👍🏻

**Comment by boojack** [comment]
Issue outdated.

**Comment by samuelthng** [comment]
Hello @boojack, why is this outdated actually? It seems the PWA functionality is still not available.
Is having Memos as PWA removed from the project's scope?

**Comment by boojack** [comment]
@samuelthng Refer to https://github.com/usememos/memos/issues/2709

**Comment by samuelthng** [comment]
@boojack thank you for the link, but again, what is the reason it is removed?
