### ISSUE TITLE
Document or Allow opt-out of metrics collections

### ISSUE THREAD

**Issue by KevinSJ** [usememos/memos#2433]
### Is your feature request related to a problem?

First and foremost, I have to say thank you for creating this product. As a user, I really appreicate the time and effort that have gone into its development. While my feature request may come across as a bit candid, I sincerely hope that my suggestions can be taken into consideration.

I noticed there's been a significant change of behavior for this application since upgrading to v0.16.1: it began collecting and sending metrics data to posthog, This came to my attention primarily because my ad-blocker started actively intercepting and blocking outbound traffic to the Posthog domain.

Here's an image illustrating the issue:
![image](https://github.com/usememos/memos/assets/7546654/ef88345c-36a0-4654-b154-ad285e14063f)

And further search in the code base proved that this was added as part of v0.16.1

https://github.com/usememos/memos/blob/79bbe4b82aeb0fe0f41e8410fc7fa1eff6b1aae9/server/service/metric/metric.go

### Describe the solution you'd like

As a dev myself, I understand the importance of collecting metrics in a product. As a user of this **privacy-first** application, I'd like to request:

- **Documentation in README**: It would be highly beneficial to clearly outlines what metrics are being collected and how they are utilized. This will provide a decent level of transparency and help the users understand how their data are being collected.
- **Opt-Out Mechanism or Explict Notification**: Provide a way to opt-out of the metrics collection and/or explictly stating metrics are being collected.

### Additional context

I'd like to emphasize that I'm offering this suggestion from a user perspective, and with no desire to incite a debate on the whether the product should collect any metrics. 

Ultimately, the team behind the product should have the final say on their product's policies and practices.

That said, I'm more than happy to implment either of the suggestions I made.

**Comment by boojack** [comment]
See more on our [privacy policy](https://www.usememos.com/legal/privacy-policy).

**Comment by boojack** [comment]
> Opt-Out Mechanism or Explict Notification: Provide a way to opt-out of the metrics collection and/or explictly stating metrics are being collected.

SGTM, please feel free to make a PR for this. @KevinSJ

**Comment by athurg** [comment]
I fully agree with you, @KevinSJ . I think we'd better do not collection anything from user, because it is a Self-Host product, who's user maybe very care about it's data.

As a compromise, I think we should add a param to disable this at least.

**Comment by KevinSJ** [comment]
@athurg @boojack Thank you both for your response and the work that's been done to resolve this issue. Really appreciate it.

**Comment by dwong33** [comment]
It seems that this opt-out bottom is not found in the release? Or where can we configure it? Thank you.

**Comment by athurg** [comment]
@dwong33 There is a command line flag `metric` to control this. Run your *Memos* with `--metric=false` or just add a environment `MEMOS_METRIC=false` in your Docker's container.

**Comment by dwong33** [comment]
Thank you so much! But will it be better to include this param setting in the setting page?
