### ISSUE TITLE
Cloudflare R2 对象存储显示图片的时候 400 bad request，文字和上传图片是可以的

### ISSUE THREAD

**Issue by edonyzpc** [usememos/memos#2436]
### Describe the bug

如下图所示，配置好 R2 存储之后，添加图片，然后查看记录发现获取图片失败。

- CORS 已经配置
```
[
  {
    "AllowedOrigins": [
      "*"
    ],
    "AllowedMethods": [
      "GET",
      "HEAD"
    ],
    "AllowedHeaders": [
      "*"
    ],
    "MaxAgeSeconds": 3600
  }
]
```

<img width="1343" alt="image" src="https://github.com/usememos/memos/assets/7744664/f1ae6b8e-b077-4e3c-a2dc-2877be5a943b">

### Steps to reproduce

1. 按照指导文档配置 R2 存储
2. 添加图片
3. 查看记录的时候图片

**Comment by athurg** [comment]
Maybe there's something wrong with your *Cloudflare* configurations, I suggest you to check that first.

**Comment by edonyzpc** [comment]
Thank you for your reply, I tried the Cloudflare R2 configurations but it failed. So CORS can not be blamed.

I tried to access the object file in Chrome, there is some response like the following image.
<img width="966" alt="image" src="https://github.com/usememos/memos/assets/7744664/0069eeeb-19b0-4186-8258-e5fe7d30913d">


It seems that R2 S3 API is not supporting this way to access, the `src` attribute of `img` is `${R2_Bucket_S3_API}/${bucket_name}/image_object.png`, if I configure the public access with custom domains provided by Cloudflare it worked.
<img width="1074" alt="image" src="https://github.com/usememos/memos/assets/7744664/a12f7528-50e0-4e32-941f-1112bc4bc137">

So I checked the memos R2 storage configuration, and I found that I missed the URL prefix configuration. However according to Cloudflare, it is not a good idea for product use.
<img width="842" alt="image" src="https://github.com/usememos/memos/assets/7744664/dd623fe6-b1a0-46b1-9b85-012247b1a55b">

Can memos support customized domain public access configuration for R2?
<img width="1072" alt="image" src="https://github.com/usememos/memos/assets/7744664/a20955c5-181f-485f-aeca-51fb8db9cf49">

And I tested it successfully by adding customized javascript to auto-replace the image URL. Of course, it's testing, the code can be more elegant when it is in the backend.
```js
function refresher() {
    setTimeout(function () {
        for (item of document.getElementsByClassName('mt-2')) {
            for (img of item.getElementsByTagName('img')) {
                if (img.src.startsWith('https://img.edony.ink/memos')) continue;
                img.setAttribute('src', 'https://img.edony.ink/memos/' + img.src.split('/')[img.src.split('/').length - 1]);
            }
        }
    }, 1500)
}

setInterval(function () {
    refresher();
}, 30000)

```

**Comment by edonyzpc** [comment]
it seems that it is R2 access problem not memos and close the issue.
