### ISSUE TITLE
新版本无法通过cloudflare 访问

### ISSUE THREAD

**Issue by fgott** [usememos/memos#2441]
### Describe the bug

![image](https://github.com/usememos/memos/assets/28496066/2d0e91fb-2045-4f1f-a3d5-6ab7a6dfe354)

用了很长一段时间，通过cloudflare tunnle去访问。但是这周就突然不行了，相同配置下其他端口其他程序页面都是可以正常访问的。

### Steps to reproduce

1、本地docker安装部署。
2、通过另一台机安装 cloudflare tunnel，并配置好域名访问该服务端口
3、在外网通过配置好的域名。

**Comment by athurg** [comment]
Your Cloudflare return HTTP 403 error, you should check your Cloudflare's config.

**Comment by fgott** [comment]
> Your Cloudflare return HTTP 403 error, you should check your Cloudflare's config.

But with the same configuration, access to other sites is normal and functional.  （by GPT translate ）

**Comment by troilus** [comment]
same problem
