### ISSUE TITLE
 Momes软件 最新版开启备份后，直接将磁盘占满。

### ISSUE THREAD

**Issue by Tony-TF** [usememos/memos#2442]
### Is your feature request related to a problem?

![memos](https://github.com/usememos/memos/assets/35761167/fae6e8ae-fd68-4512-a0d3-f056642e95a0)

### Describe the solution you'd like

请问作者应该如何对这些进行清理，是直接删除掉。还是只需要保存memos_prod.db即可。期待你的回复

**Comment by athurg** [comment]
Those backup files (`*.bak`) could be remove safely if you don't need it.

And you can disable the backup schedule in **Setting/Admin/System**, just change **Auto backup interval (seconds)** into `0`.

**Comment by Tony-TF** [comment]
谢谢你的回答，已经解决问题了。
