### ISSUE TITLE
Integrating Cloudflare Turnstile (Invisible) into Memos Project

### ISSUE THREAD

**Issue by BaksiLi** [usememos/memos#2443]
### Is your feature request related to a problem?

I‘ve noticed that there have been an increasing number of bot registrations (?) on my own Memos instance. It is taxing my resources unnecessarily.

### Describe the solution you'd like

I have seen other projects integrating [Cloudflare Turnstile](https://developers.cloudflare.com/turnstile/) (invisible) to their website. Cloudflare Turnstile offers superior bot detection and prevents abusive behaviour such as fraudulent registrations and logins. And it should increase security without compromising the performance too much.

[An official demo](https://demo.turnstile.workers.dev/) shows how it should look like. This example is intrusive, but it could be set to invisible.

### Additional context

Is this a good idea? I can implement it if needed.

Looking forward to hearing everyone’s thoughts on this.

**Comment by boojack** [comment]
SGTM, I'd like to get your implementation idea. And I think this should be a workspace level setting item like `disable sign up`.
