### ISSUE TITLE
v0.4.4 重启服务数据丢失

### ISSUE THREAD

**Issue by anno189** [usememos/memos#245]
版本：v0.4.4 
服务器：ubuntu 20.04
部署：没有使用 dock，使用命令行方式。nginx 代理。使用pm2管理。

服务器运行第二天，重启前端服务后，数据被初始化，已录入数据丢失。

刚刚部署的服务器，不会出现这个问题。
第二天就有大概率出现，服务运行超过2天，出现率100%。

**Comment by boojack** [comment]
建议直接使用 docker 部署： https://github.com/usememos/memos#docker-run

**Comment by anno189** [comment]
我知道了，还是需要使用编译后的发布版本的。谢谢。
