### ISSUE TITLE
通过编辑memos取消关联附件，附件不会被删除且在资源库也找不到

### ISSUE THREAD

**Issue by bfansheng** [usememos/memos#2451]
### Describe the bug

取消关联附件后，文件在服务器上仍然存在，在memos资源库中也找不到。

### Steps to reproduce

1. 添加一条memos并关联附件
2. 编辑memos取消关联附件
3. 服务器上发现文件仍然存在
4. 资源库中无法查找到附件

**Comment by athurg** [comment]
It looks like there is no purge if the resource is save in the disk. Maybe we remove the file while the resource's deleted.
