### ISSUE TITLE
Pinned Memo

### ISSUE THREAD

**Issue by brandon0824** [usememos/memos#2459]
### Is your feature request related to a problem?

Can you set a logged in user to pin a memo, and have a non-logged in user also see the pinned memo when they visit the site? 
I noticed that memo doesn't have this functionality.

### Describe the solution you'd like

When a non-logged in user visits the site, they are unable to see the effect of a logged in user pinning a memo.

**Comment by boojack** [comment]
The pinned memos will display in users' page `/u/{username}`.

<img width="714" alt="image" src="https://github.com/usememos/memos/assets/24653555/9af0125d-44e5-4225-b488-3403d14811f6">
