### ISSUE TITLE
Disable public memos - not working

### ISSUE THREAD

**Issue by bestrocker221** [usememos/memos#2462]
### Describe the bug

The flag "Disable public memos" does not block public notes from being created or viewed publicly.

### Steps to reproduce

1. enable "Disable public memos"
2. create a public note
3. browse to the public note from unauth session

**Comment by itschip** [comment]
This is likely my fault when adding the "disable public memos" feature :D I'll create a fix for it

**Comment by bugbounce** [comment]
Hello @itschip . This issue still exists in 0.17.1. I can still see old and newly created public notes from an unauthenticated session. Kindly take a look. Thanks for your time.

**Comment by itschip** [comment]
@bugbounce can you please create a new issue and I will have a look :D
