### ISSUE TITLE
Search component loaded abnormally and could not be displayed in its entirety

### ISSUE THREAD

**Issue by ccsen** [usememos/memos#2466]
### Describe the bug

Search component loaded abnormally and could not be displayed in its entirety.

Iphone SE3 iOS 17.1 safari

### Steps to reproduce

1. go to the "home"
2. Slide up page
3. touch search logo

### Screenshots or additional context

![IMG_3453](https://github.com/usememos/memos/assets/25996944/745bd16f-f802-4b14-8adb-1742eeaed92e)
![IMG_3452](https://github.com/usememos/memos/assets/25996944/35238054-dd5b-4f7a-b769-1fa6d56194b7)

**Comment by hellspector** [comment]
the same issue. seems to be a bug.

i like the old way, the search bar  is on the right top.   

now when i want to search, i must touch the screen twice to type the content.

**Comment by boojack** [comment]
Fixed in https://github.com/usememos/memos/commit/65a34ee41ac4ad3b9494b4950a0e257877afb3cf
