### ISSUE TITLE
add the "@" symbol to mention other usernames

### ISSUE THREAD

**Issue by Fog3719** [usememos/memos#2467]
### Is your feature request related to a problem?

My use case is that my wife and I use memos as our family diary. There are some tasks that require her assistance, and occasionally she also comments on my notes. Sometimes I need to remind her to take a look at the notes I've collected.

### Describe the solution you'd like

 Now that there is a feature for other users to comment, I'm wondering if it's possible to add the "@" symbol to mention other usernames as a way of sending notifications. Thank you.

**Comment by filippobenozzi** [comment]
I would love to have this feature
