### ISSUE TITLE
二级标签管理的小建议

### ISSUE THREAD

**Issue by ChiehJang** [usememos/memos#2471]
### Describe the bug

现在标签管理有默认的字数限制，当添加2级标签的时候多余的字会被"..."的形式隐藏显示，希望隐藏的同时加上鼠标移入，显示全部的名称，不然无法得知该标签到底是什么，只能看到一级标签。

### Steps to reproduce

看下面截图

### Screenshots or additional context

![标签管理](https://i.imgur.com/CbQU1EQ.jpg)

**Comment by boojack** [comment]
https://github.com/usememos/memos/commit/32cafbff9b6bb697f9516e62f2938a7652b95f12

<img width="347" alt="image" src="https://github.com/usememos/memos/assets/24653555/a8fb4ed0-3d4d-41cc-a4bd-eb01abac9f76">
