### ISSUE TITLE
Markdown Parser/Angle brackets surrounded link unsupported

### ISSUE THREAD

**Issue by sicl5300** [usememos/memos#2475]
### Describe the bug

Markdown parser does not support "Angle bracket surrounded link". As a result, any inline links/ link references like `<https://www.domain.tld/>` will be parsed into `<a href="https://www.domain.tld/"> https://www.domain.tld/> </a>`.

<https://daringfireball.net/projects/markdown/syntax#link>

```plaintext
The link URL may, optionally, be surrounded by angle brackets:
[id]: <http://example.com/>  "Optional Title Here"
```

### Steps to reproduce

```markdown
Raw link https://www.lorem.com/ipsum/a.
Link [Link](https://www.lorem.com/ipsum/a).
Reference:
[Link Reference]: https://www.lorem.com/ipsum/a.
Raw link with brackets <https://www.lorem.com/ipsum/a>.
Reference Link with brackets:
[Link Reference]: <https://www.lorem.com/ipsum/a>.
```

### Screenshots or additional context

![cc7f7ec59ea0dd84dcbe67edebf4d93](https://github.com/usememos/memos/assets/47028479/6427ae4b-549a-409c-8d2c-83d9a213f6fb)

**Comment by boojack** [comment]
Maybe fixed in the latest version. Please try it again in demo site: https://demo.usememos.com
