### ISSUE TITLE
DAY and DATE not correct

### ISSUE THREAD

**Issue by tenebrisnox** [usememos/memos#2476]
### Describe the bug

I'm using v0.17.0.
I'm in UK (in case it's a time-zone issue.)

Just noticed that the days and dates seem to be wrong. 
Today is correctly 2/10/2023 - but says that it's Wednesday (when it's actually Thursday).

### Steps to reproduce

1. Go to Daily Review.
2. Click on Date.

### Screenshots or additional context

![FireShot Capture 013 - memos - 192 168 0 109](https://github.com/usememos/memos/assets/89422923/5e6a4591-6ca5-4f8a-99be-08921c7e1eb4)

**Comment by boojack** [comment]
Fixed in https://github.com/usememos/memos/commit/982b0285c9376c0883ad4f3b4b66a4894b054fcc
