### ISSUE TITLE
允许重命名标签

### ISSUE THREAD

**Issue by hellspector** [usememos/memos#2477]
### Is your feature request related to a problem?

我发现，memos以前有很多很好用的功能都被删除了，好遗憾啊。

https://github.com/usememos/memos/issues/1054#issue-1577936169

这个issue里面提到的重命名标签，以前都是有的，现在却没有了。
能否重新加上呢？

像以前还有一个捷径，是可以预设一些内容筛选的，现在也没有 了。T_T

### Describe the solution you'd like

有的时候整理memos时，需要重新命名tag，以前是可以用重命名的，现在只能一个一个命名。。

**Comment by Hou-Xiaoxuan** [comment]
好奇为什么会删掉这个功能。是 与现有其他功能不兼容了吗？另外，看到issue有些人的界面是有标签收藏的，但是最新版(dock er)没有了。
I'm curious why this feature was removed. Is it incompatible with existing features? Also, I noticed in some issue that some people's interfaces have tag favorites, but the latest version (docker) doesn't have them.

**Comment by hellspector** [comment]
> 好奇为什么会删掉这个功能。是 与现有其他功能不兼容了吗？另外，看到issue有些人的界面是有标签收藏的，但是最新版(dock er)没有了。 I'm curious why this feature was removed. Is it incompatible with existing features? Also, I noticed in some issue that some people's interfaces have tag favorites, but the latest version (docker) doesn't have them.

memos以前有好多功能都挺好用的，比如说快捷方式，后来都取消掉了。一停不停改用户习惯，也不知道为什么。
改到现在最好用的还是图片的管理与显示方式比较好。

**Comment by boojack** [comment]
标签只有创建和删除，没有重命名和收藏，之前的版本也没有实现过。

> 以前是可以用重命名的，现在只能一个一个命名

因为 tag 是和 memo 分开的，重命名标签不会去同步修改 memo 里的 tags，所以重命名是没有意义的

**Comment by teacup418** [comment]
> 标签只有创建和删除，没有重命名和收藏，之前的版本也没有实现过。
> 
> > 以前是可以用重命名的，现在只能一个一个命名
> 
> 因为 tag 是和 memo 分开的，重命名标签不会去同步修改 memo 里的 tags，所以重命名是没有意义的

不是哥们，我以为是按照flomo竞品来做的，还以为原生支持重命名标签，原来还要找第三方方案吗？

**Comment by hellspector** [comment]
> > 标签只有创建和删除，没有重命名和收藏，之前的版本也没有实现过。
> > > 以前是可以用重命名的，现在只能一个一个命名
> > 
> > 
> > 因为 tag 是和 memo 分开的，重命名标签不会去同步修改 memo 里的 tags，所以重命名是没有意义的
> 
> 不是哥们，我以为是按照flomo竞品来做的，还以为原生支持重命名标签，原来还要找第三方方案吗？

我已经很早就放弃这个usememos了。这个对作者来说就是个玩具，很多breaking changes

另外有了openclaw后，这种usememo级别的小工具，自己手搓都能弄出来。我现在自己搞的那个更贴合我自己的需求。
