### ISSUE TITLE
Request hotkey for searching all memos

### ISSUE THREAD

**Issue by Arom1a** [usememos/memos#2479]
### Is your feature request related to a problem?

Nop

### Describe the solution you'd like

There are shortcuts like `ctrl+f` and `/` to start searching quickly on many websites, without moving the mouse to focus on the search bar. 

Also, it will be great to customize some shortcuts in the settings.

**Comment by grand-lotus-iroh** [comment]
focus the search box when the user presses `CTRL` + `/` by adding event listener in settings > Additional script

```
document.addEventListener('keydown', function(event) {
  if (event.ctrlKey && event.key === '/') {
    const searchBox = document.querySelector('input[placeholder="Search memos"]');
    if (searchBox) {
      searchBox.focus();
    }
  }
});
```
