### ISSUE TITLE
How to edit this icon?

### ISSUE THREAD

**Issue by Handsome1080P** [usememos/memos#2481]
![image](https://github.com/usememos/memos/assets/13675031/34b17f20-7ec8-427a-8b84-96008418a2d8)
how to edit this

**Comment by boojack** [comment]
Settings -> System -> Basic

<img width="836" alt="image" src="https://github.com/usememos/memos/assets/24653555/64a51a72-974f-4d1b-a30d-f9c5372f5ea3">

**Comment by Handsome1080P** [comment]
> Settings -> System -> Basic
> 
> <img alt="image" width="836" src="https://user-images.githubusercontent.com/24653555/280480979-64a51a72-974f-4d1b-a30d-f9c5372f5ea3.png">

not works.still default pic.
![image](https://github.com/usememos/memos/assets/13675031/1bc31137-5887-4bd2-af45-f12328aeb222)

**Comment by Handsome1080P** [comment]
> * If you are a visitor, then the icon will be the system setting; `Settings -> System -> Basic`
> * If you have logged in, then the icon will be your user avatar; `Settings -> My Account`

Already changed system/basic setting.But for visitors still default image
