### ISSUE TITLE
Update from 0.16.1 to 0.17.0-Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by qiezigao** [usememos/memos#2484]
### Describe the bug

I use this command to upgrade. 
`docker-compose down && docker image rm neosmemo/memos:latest && docker-compose up -d`
It shows upgrade successful.

But can't access the home page.
`Unexpected Application Error!
Failed to fetch dynamically imported module: https://domain/assets/Home-3c29e03d.js
TypeError: Failed to fetch dynamically imported module: https://domain/assets/Home-3c29e03d.js`

### Steps to reproduce

Upgrade from 0.16.1 to 0.17.0

**Comment by jtsang4** [comment]
Meet the same issue, the unloaded module in my situation is "/assets/Home-d0ce7fcf.js".

**Comment by boojack** [comment]
Might be some unwanted cache from browser or Nginx?

**Comment by jtsang4** [comment]
> Might be some unwanted cache from browser or Nginx?

It works for me now. I tested in private mode of browser before, so it is maybe Nginx cache.

**Comment by justamanm** [comment]
Encountered the same issue, but it's ok after almost 2 hours, don't know why. But it does annoying.
