### ISSUE TITLE
从探索页回到主页，会不展示最新20条memo

### ISSUE THREAD

**Issue by Vespa314** [usememos/memos#2496]
### Describe the bug

假如我有21条memo，
<img width="921" alt="image" src="https://github.com/usememos/memos/assets/6339395/45588d96-bde3-458e-bca5-e9b342ccd430">

如果直接进去/explore（不清楚是否需要这里超过20条才可以复现，假如explore页面的memo都是别人的），然后点击左侧边栏的Home回到主页：

此时看接口会拉取offset=20的memo
<img width="971" alt="image" src="https://github.com/usememos/memos/assets/6339395/c399187a-cbe1-4063-a64c-71d533f8ac5e">

所以首页展示看不到最新的20条：
<img width="1158" alt="image" src="https://github.com/usememos/memos/assets/6339395/b9b8e128-8ac3-44d2-b323-331c9e384231">

### Steps to reproduce

如上所言

**Comment by boojack** [comment]
Fixed in https://github.com/usememos/memos/commit/94c71cb834bf901263f730f6a0f50e6164e022ae
