### ISSUE TITLE
设置默认系统语言后对未登录用户无效

### ISSUE THREAD

**Issue by xhemj** [usememos/memos#2503]
### Describe the bug

设置默认系统语言后对未登录用户无效，未登录用户进去语言一直都是英文

### Steps to reproduce

1. 进入设置-系统-“服务名称”旁边的编辑按钮-服务器语言环境
2. 设置语言为“简体中文”
3. 点击保存并退出
4. 无痕模式重新进入页面后还是显示为英文

### Screenshots or additional context

看到 #1681 曾经修复过这个问题，但目前来看这个问题似乎仍然存在

**Comment by weqoocu** [comment]
我也遇到这个问题
