### ISSUE TITLE
Enhancing Tag Display in Candidate Options

### ISSUE THREAD

**Issue by wingkin** [usememos/memos#2504]
### Is your feature request related to a problem?

Thank you for creating such a great program. 
There's a small aspect I hope to see improvement in. When entering tags and the candidate options pop up, if the tag hierarchy is too long, the latter part may not be fully displayed. 

### Describe the solution you'd like

I'm wondering if it's possible to increase the display width for this or perhaps omit the middle portion instead of the latter part.

### Additional context

<img width="416" alt="image" src="https://github.com/usememos/memos/assets/18586433/3f9f80c0-140c-4421-8b69-d501e6cf65d3">

**Comment by boojack** [comment]
Updated in https://github.com/usememos/memos/commit/0bb0407f4649c0a4314aee0c6378f0c1e8242c7f

**Comment by wingkin** [comment]
Hi, @boojack,
Thank you for promptly addressing this issue. I've updated to the latest version 0.17.1, and it seems that the problem of not displaying the entire tag after a certain length still exists in the official live demo (version 0.18.01). 
Since users focus on the information in the last level of tags, I hope the last part won't be omitted.

<img width="453" alt="image" src="https://github.com/usememos/memos/assets/18586433/c67f980c-e45b-466b-ac51-ddd8919a9428">
