### ISSUE TITLE
Add voice recording function in the Android app

### ISSUE THREAD

**Issue by pisceswb** [usememos/memos#2507]
### Is your feature request related to a problem?

May I ask if it is possible to add voice recording function in the Android app. The combination of voice and photography will be perfect

### Describe the solution you'd like

Take a photo, and then the meaning of taking this photo can be explained by voice recording. Perfect!

**Comment by athurg** [comment]
*Memos* does not provide a Android app directly, you should contact the App's author you're currently used.
