### ISSUE TITLE
如何滚动右侧标签树

### ISSUE THREAD

**Issue by Vespa314** [usememos/memos#2508]
### Is your feature request related to a problem?

当前当tag很多的时候，上下滚动页面只会滚动memo list部分，而右侧tag树是不会移动的；

那么当我要查看的标签在树中非常靠下方的时候，我无法通过滚动页面来进行查看/展开；

目前唯一想到的方法就是搜索一个完全不存在的东西，使得memo list变空，然后再上下滚动；

但显然这不是一个好方法。。
<img width="910" alt="1" src="https://github.com/usememos/memos/assets/6339395/c9517baa-a7c7-4f88-9e09-1a0f9c31e737">

### Describe the solution you'd like

当鼠标放置在标签树所在dom时，上下拖动不再是拖动memo list。

**Comment by boojack** [comment]
Fixed in https://github.com/usememos/memos/commit/c1a6dc9bac3567239751510aa9b68386e526c4ae
