### ISSUE TITLE
每日回顾如果查看很久之前日期的话，加载非常慢

### ISSUE THREAD

**Issue by Vespa314** [usememos/memos#2514]
### Is your feature request related to a problem?

在我memo非常多的情况下，如果在日期选择器上选择一个很久远的日期的话，页面要过很久才出现memo；

看代码是因为不断调整offset，用api/v1/memo轮询拉取的，所以如果那一天之后有1000条memo，那至少要等50次接口拉取后才可以看到memo；

### Describe the solution you'd like

后端listmemo这个接口是不是可以支持日期范围过滤，直接定位到某一天的memo，一次拉取就返回（除非那天有超过20条memo）

### Additional context

另外，如果这个机制实现了，是不是可以实现热力图日期点击，直接跳转到dailyreview的这一天，或者直接首页memo_list直接过滤出这一天的memo？

**Comment by athurg** [comment]
热力图上点击现在就支持跳转。

接口提供按时间过滤返回问题不大，但是配套的前端整体的架构调整巨大。现在前端很多机制，都是基于「动态拉取并缓存，然后在本地搜索过滤」的机制来做的。

**Comment by Vespa314** [comment]
> 热力图上点击现在就支持跳转。
> 
> 接口提供按时间过滤返回问题不大，但是配套的前端整体的架构调整巨大。现在前端很多机制，都是基于「动态拉取并缓存，然后在本地搜索过滤」的机制来做的。

我觉得当前这套机制从长远看来，上限不高，之后一定会遇到各种诸如搜索性能低下等问题，长期发展来看，感觉早晚会被迭代掉的；

当下是不是可以拿daily review这个页面来做试点优化（仅建议）；

**Comment by boojack** [comment]
Fixed in latest version. See more in the demo site: https://demo.usememos.com
