### ISSUE TITLE
Postgres DB Driver Support

### ISSUE THREAD

**Issue by debugger24** [usememos/memos#2517]
### Is your feature request related to a problem?

Postgres is widely used database, adding support for Postgres will be very handy for others too.

### Describe the solution you'd like

Either using a ORM or adding one more configuration for postgres db support.

**Comment by Irvingouj** [comment]
Can I take this one @boojack ?

**Comment by boojack** [comment]
@Irvingouj Of course you can, maybe adding one more configuration for Postgres is a better solution than using ORM. WDYT?

**Comment by Irvingouj** [comment]
@boojack you mean follow the existing pattern and avoid using ORM?
Correct me if I'm wrong, currently for Mysql and SQLite, all implementation of the Driver interface is string concatenation of sqls. If you think in future, there will be no more database to support, we may just not add a new ORM for extra layer of abstraction and follow what is already there. 

However, using ORM will solve the problems where
 **If there is any database changes, we need to manually update all sqlite, mysql and postgres implementation, which is error prone and repetitive**

Though, Golang ORMs had very bad reputations. Alternatively, we may not necessarily need an ORM. The solutions we have is 
1. [sqlc](https://github.com/sqlc-dev/sqlc), where all we do is writting SQL quries and go code is generated for us, and it supports all sqlite, mysql and posgres.
2. sqlbuilders, though which sqlbuilder to chose is debatable, but most of them supports all three database we discussed here.


Let me know what do you think, and I will proceed accordingly.

**Comment by Irvingouj** [comment]
> @Irvingouj We also think that Go's ORM is kind of not good, so we'd not to use it. As for the two options you mention, the `sqlc` looks a little weird to use. So I prefer the second way, but I feel it's pretty much the same as the existing way, except that now it's just splicing the string directly into the SQL string.

I will give an implementation from a sqlbuilder and support postgres, then we may explore the posibility of replacing it with current database changes

**Comment by Irvingouj** [comment]
WIP
https://github.com/Irvingouj/memos/tree/TrySquirrel
