### ISSUE TITLE
web端设置默认备忘录可见性为‘公开’，但安卓端仍为‘仅自己可见’

### ISSUE THREAD

**Issue by chahushui** [usememos/memos#2520]
### Describe the bug

偏好设置：默认备忘录可见性   并没有同步。

### Steps to reproduce

1. web端设置默认备忘录可见性为‘公开’，在web端确实达到目的了，新memo默认为公开，很好；
2. 但，安卓端仍为‘仅自己可见’，每次用手机端提交前，都得去设置一下为‘公开’（但很大情况下，我会忘记设置，别人说，看不到我的新内容）

希望：安卓端可同步web的配置。

**Comment by dianso** [comment]
不存在所谓安卓端，非官方
