### ISSUE TITLE
增加资源搜索的功能，比如按图片名搜索

### ISSUE THREAD

**Issue by liweibiao** [usememos/memos#2522]
### Is your feature request related to a problem?

我在memos发图片单词记忆图片来复习，发的纯图片，图片是单词名称，不能通过图片名搜索。

### Describe the solution you'd like

想要API能支持filename字段的请求  或者能直接搜索到资源

**Comment by boojack** [comment]
Updated in https://github.com/usememos/memos/commit/d317b0383285526da6af861b7ec47ca305a8b07d
