### ISSUE TITLE
为什么 $ \Omega $ 这种数学符号位分行

### ISSUE THREAD

**Issue by Kiris-tingna** [usememos/memos#2523]
### Describe the bug

应该是内联的不会分行吧

### Steps to reproduce

 $ \Omega $ 

### Screenshots or additional context

![企业微信截图_17001848412649](https://github.com/usememos/memos/assets/10670294/34fb1e7d-f8b0-408e-ab75-2960eac8eded)

**Comment by Kiris-tingna** [comment]
怎么又改回去了

**Comment by boojack** [comment]
Fixed in https://github.com/usememos/memos/commit/b1128fc786fb8f69fabdd8c96487fb0082a9e977
