### ISSUE TITLE
Upload mp4 video file will failure, 500 Internal Error

### ISSUE THREAD

**Issue by shwangdev** [usememos/memos#2529]
### Describe the bug

Upload a small-size mp4 video file through the portal. It will raise 500 Internal Error

### Steps to reproduce

1. click the create resource button.
2. select a small size of mp4 file.
3.  click upload.

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/702829/d9f5e944-ed8a-445a-9c52-bfb9f26b94a9)

**Comment by athurg** [comment]
What's the size of your MP4 file?
