### ISSUE TITLE
Feature request: Cross-post to microblogging sites (Twitter, Mastodon, Threads, etc)

### ISSUE THREAD

**Issue by r0bbie** [usememos/memos#2533]
### Is your feature request related to a problem?

Been using Memos for personal note taking synced to Logseq, for which it's brilliant.

It can also work as a really nice, lightweight personal microblogging platform however (which should be even more capable once ActivityPub support is added! https://github.com/usememos/memos/issues/878)

It would be amazing if Memos could go a step further, and allow cross-posting memos to other sites (perhaps as an option that could be toggled on/off on each memo post). This would serve a further headache, which is that there are now a recent abundance of microblogging sites!

### Describe the solution you'd like

Ideally cross-posting which supported:

- Twitter / X
- Mastodon
- Threads
- Bluesky Social
- Tumblr?
- Facebook?
- Maybe micro.blog?

Could either be a toggle option for cross-posting on each memo, or a user-wide setting to automatically cross-post public memos?

### Additional context

While this would be a really, really cool feature to have within Memos, I also understand if it was considered out of scope of the project. Also note that upcoming support for webhooks (https://github.com/usememos/memos/issues/1039) may enable this flow to be implemented by having Memos trigger a webhook on an external cross-posting service.

**Comment by boojack** [comment]
FYI, webhooks has been implement after `v0.18.0`. Some other content might be duplicated with https://github.com/usememos/memos/issues/878.
