### ISSUE TITLE
无法进入容器执行 copydb 命令

### ISSUE THREAD

**Issue by leoshcn** [usememos/memos#2534]
### Describe the bug

设置好 mysql 连接并成功创建新的数据库，希望将 sqlite 数据迁移至数据库。用 docker exec 命令进入容器执行 copydb 命令失败。
返回错误
“/bin/sh: can't open 'mysql': No such file or directory”

### Steps to reproduce

1. Start memos container
2. run "docker exec -it CONTAINERID /bin/sh"
3. run "/usr/local/bin/memos --driver mysql --dsn 'dbuser:dbpass@tcp(dbhost)/dbname' copydb --from sqlite://path_to_your_memos_prod.db"
4. get error message “/bin/sh: can't open 'mysql': No such file or directory”

**Comment by jkjoy** [comment]
0.17.1 会报错`Error: unknown flag: --driver`
0.17.0 可以使用`/usr/local/memos/memos --driver mysql --dsn 'dbuser:dbpass@tcp(dbhost)/dbname' copydb --from sqlite://path_to_your_memos_prod.db`

**Comment by athurg** [comment]
@leoshcn 

The `memos` binary is located in `/usr/local/memos/memos`, **NOT** `/usr/local/bin/memos`, you should modify your command.

@jkjoy 

I've tried the command provided by you, and there isn't any errors like `unknown flag: --driver`, could you provide more information about this?

**Comment by leoshcn** [comment]
@athurg  It works. But maybe the documentation should be updated 
https://www.usememos.com/docs/advanced-settings/mysql

**Comment by athurg** [comment]
> @athurg It works. But maybe the documentation should be updated
> https://www.usememos.com/docs/advanced-settings/mysql

You're right, I have [updated](https://github.com/usememos/dotcom/commit/3fb9575e4f908812e2d277a86b7c32ed18da8edc) the document. Thank's for your suggestion.

**Comment by jkjoy** [comment]
0.17.1 使用docker run 会报错Error: unknown flag: --driver
