### ISSUE TITLE
Getting an Unexpected Application Error due to no connection with https://api.posthog.com

### ISSUE THREAD

**Issue by MeneerHeijpaal** [usememos/memos#2535]
### Describe the bug

I have a custom DNS-configuration with my Docker Containers, so that it's possible for me to work offline.

If I login to memos, I get this error:

```
Unexpected Application Error!
Unable to preload CSS for /assets/Memo-251294cc.css

__vitePreload/</</<@https://mymemos-docker.example.com/assets/index-677cc5ea.js:297:10926
EventListener.handleEvent*__vitePreload/</<@https://mymemos-docker.example.com/assets/index-677cc5ea.js:297:10894
__vitePreload/<@https://mymemos-docker.example.com/assets/index-677cc5ea.js:297:10838
__vitePreload@https://mymemos-docker.example.com/assets/index-677cc5ea.js:297:10377
Home<@https://mymemos-docker.example.com/assets/index-677cc5ea.js:323:25478
T$2@https://mymemos-docker.example.com/assets/index-677cc5ea.js:9:3653
Wk@https://mymemos-docker.example.com/assets/index-677cc5ea.js:77:48993
Vk@https://mymemos-docker.example.com/assets/index-677cc5ea.js:77:43776
Mk@https://mymemos-docker.example.com/assets/index-677cc5ea.js:77:43745
Hk@https://mymemos-docker.example.com/assets/index-677cc5ea.js:77:38226
Lt@https://mymemos-docker.example.com/assets/index-677cc5ea.js:62:1731
Gt@https://mymemos-docker.example.com/assets/index-677cc5ea.js:62:2141
EventHandlerNonNull*@https://mymemos-docker.example.com/assets/index-677cc5ea.js:62:2322
@https://mymemos-docker.example.com/assets/index-677cc5ea.js:62:4212
```

In the error log of the container I get this error message:
`posthog 2023/11/20 10:53:29 ERROR: sending request - Post "https://app.posthog.com/batch/": dial tcp 0.0.0.0:443: connect: connection refused`

### Steps to reproduce

Be offline or block acces to the URL.

**Comment by boojack** [comment]
By default, memos collects the usage counts of some important function. It is used for development program planning. And you can still refer to our [starting parameter options docs](https://www.usememos.com/docs/install/self-hosting#parameter-options) to set whether to turn it on or not.

**Comment by MeneerHeijpaal** [comment]
@boojack : Thank you! I didn't look at the parameter options. My bad.
