### ISSUE TITLE
0.4.5更新0.5.0后提示Failed to fetch memo list.无法解析先前的memos

### ISSUE THREAD

**Issue by lentikr** [usememos/memos#254]
![image](https://user-images.githubusercontent.com/95539012/193604391-dd612dd1-8aaa-4da6-9e56-22027408e64b.png)

**Comment by boojack** [comment]
麻烦通过 devtools 看一下更详尽的错误信息

<img width="544" alt="image" src="https://user-images.githubusercontent.com/24653555/193605668-f26bac02-3b99-434c-bcd8-59fccce4117a.png">

**Comment by lentikr** [comment]
状态码是500：Internal Server Error
![image](https://user-images.githubusercontent.com/95539012/193607245-fc1876be-5b93-4622-93a3-309d5168ab4d.png)

**Comment by boojack** [comment]
看样子是数据库 schema 没更新成功，有空的话麻烦到 telegram 里私聊我一下

**Comment by lentikr** [comment]
> 看样子是数据库 schema 没更新成功，有空的话麻烦到 telegram 里私聊我一下

qq或者微信可以吗，没有telegram

**Comment by boojack** [comment]
> qq或者微信可以吗，没有telegram

可以通过邮件把你的QQ/微信发我一下（[stevenlgtm@gmail.com](mailto:stevenlgtm@gmail.com)），不过还是建议使用 telegram

**Comment by boojack** [comment]
Fixed offline. Maybe you should update the docker image version manually.
