### ISSUE TITLE
执行 copydb 命令时出现 out of memory 错误

### ISSUE THREAD

**Issue by leoshcn** [usememos/memos#2542]
### Describe the bug

使用 copydb 命令时出现 out of memory 错误

### Steps to reproduce

1. start memos container in sqlite mode
2. run docker exec command
3. run "copydb" command as instructed in memos doc
4. error occurs

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/10073447/711065ea-9004-4de5-9cf8-6f9f51bee637)

**Comment by leoshcn** [comment]
I just found that I used incorrect path for sqlite file

**Comment by skyrunner15** [comment]
What was the path used?
