### ISSUE TITLE
VIM and Emacs editor support for editing thoughts

### ISSUE THREAD

**Issue by Arom1a** [usememos/memos#2544]
### Is your feature request related to a problem?

It is painful to move the cursor around just using the arrow keys. 

### Describe the solution you'd like

Add an option in the Preferences to enable VIM or Emacs mode in the thoughts' editor.

**Comment by itschip** [comment]
https://github.com/FelixKratz/SketchyVim if you're on macos. There are likely other options for Linux/Win :)
