### ISSUE TITLE
我希望对此项目发起捐赠

### ISSUE THREAD

**Issue by juestchaos** [usememos/memos#2547]
### Describe the bug

我希望对此项目发起捐赠
请问有无项目成员与我对接

### Steps to reproduce

我希望对此项目发起捐赠
请问有无项目成员与我对接

**Comment by boojack** [comment]
Hi @juestchaos, our sponsorship channels are always open:

* GitHub Sponsor: https://github.com/sponsors/usememos
* Open Collective: https://opencollective.com/memos

**Comment by juestchaos** [comment]
抱歉，我无法使用这两个渠道

**Comment by juestchaos** [comment]
是否有其他方式？

**Comment by boojack** [comment]
@juestchaos Sorry, to ensure openness and transparency, we only support these two channels for now. If you have some other questions, you can send an email to usememos@gmail.com
