### ISSUE TITLE
Healthcheck endpoint

### ISSUE THREAD

**Issue by JokerQyou** [usememos/memos#2550]
### Is your feature request related to a problem?

No, it's a regular feature request.

### Describe the solution you'd like

Would like to have an endpoint like `/api/healthz` for use with monitoring services. Ideally this endpoint would require no authentication, and returns empty 204 response or simple text/JSON 200 response.

### Additional context

Gitea has `/api/healthz`.

**Comment by boojack** [comment]
Updated in https://github.com/usememos/memos/commit/8586ebf0987a5e14ff86f9987a5f4f285be3ebfc

**Comment by stanthewizzard** [comment]
sorry to reopen this ticket
/healthz is working
but in portainer the container is only running no healthcheck is returned
how do I have healthy in it ? 
(same in command line)

Thanks
