### ISSUE TITLE
只要涉及到我自己本地上传的图片的页面加载都特别慢

### ISSUE THREAD

**Issue by cgx739991089** [usememos/memos#2551]
### Describe the bug

只要涉及到我自己本地上传的图片的页面加载都特别慢，比如我修改了头像或者发布了一个带图片的笔记，页面加载都特别慢，控制台显示是图片加载慢

### Steps to reproduce

只要涉及到我自己本地上传的图片的页面加载都特别慢，比如我修改了头像或者发布了一个带图片的笔记，页面加载都特别慢，控制台显示是图片加载慢

**Comment by wangzexi** [comment]
大概率是你的服务器带宽问题，localhost慢吗？

**Comment by cgx739991089** [comment]
> 大概率是你的服务器带宽问题，localhost慢吗？

确实是这个问题，加了cdn好多了，但是出现了另一个问题。。https://github.com/usememos/memos/issues/2557  只要上传稍微大一点的文件就会报错，传不上去，但是配置的各种相关选项又远大我上传的文件的大小
