### ISSUE TITLE
Can RSS output content with formatting? | 可以让RSS的输出格式保持和memos中一致吗？

### ISSUE THREAD

**Issue by rebron1900** [usememos/memos#2553]
### Is your feature request related to a problem?

通过RSS的XML文件，我发现目前memos内容的格式都被清除了，所有文本被放在一个P标签内，这导致了一些现在通过rss同步内容的第三方服务出现了一些格式问题，如[哔哔广场](https://immmmm.com/bbs/)内的所有内容就全部失去了换行，文本内容拥挤在一行内，十分影响阅读。

---

Through the XML file of the RSS, I discovered that the formatting of the current memos content has been cleared. All text is placed within a `<p>` tag, causing some formatting issues with third-party services that sync content through RSS. For example, all the content within [哔哔广场](https://immmmm.com/bbs/) has lost its line breaks, resulting in crowded text on a single line, which greatly affects readability.

### Describe the solution you'd like

- 让Rss的内容保持原有memos中的格式
- 或者增加可选的配置选项

---

- Keep the original formatting of the content in RSS feeds
- Or add optional configuration options

**Comment by boojack** [comment]
The latest 0.18.1 uses a customized markdown parser, which solves some problems you mentioned.
