### ISSUE TITLE
为啥这么慢?

### ISSUE THREAD

**Issue by weichangdong** [usememos/memos#2554]
### Describe the bug

用WordPress搭建了一个小博客，想着memos可能会更快，结果很慢，随便看了下，为什么请求这么多资源
不理解为什么简简单单的前端展示，加载这么多语言的js文件呢？一种语言足够了吧

![memos-bug](https://github.com/usememos/memos/assets/2841874/8eaa5856-98b1-4d0c-b34e-de2ba541c0dd)

### Steps to reproduce

Built a small blog with WordPress, thinking memos may be faster, the result is very slow, just look at it, why request so many resources
Don't understand why simple front-end display, load so many languages of js files? One language is enough

**Comment by changsen-dev** [comment]
不光你一个人感觉慢，我的也是，辣鸡golang能快到哪里去，再加上一堆无用资源加载，想不卡都难

**Comment by weichangdong** [comment]
说golang垃圾 这有点不负责吧 
我觉得主要慢 是因为加载了一堆 没必要的资源，本身后端golang的接口还是很快的。就如同我上面的图片，那么多 多语言的js文件，你按需加载即可，为啥都要加载一遍啊。

**Comment by Irvingouj** [comment]
Inappropriate language should not be tolerated @boojack

**Comment by okhanyu** [comment]
memos的默认前端页面确实非常非常慢，而且js和css资源还是使用的 / 这种根路径引用，也没有办法简单方便的将js等静态资源放到CDN或者云存储，咱们个人买的服务器一般带宽都小，甚至不备案的话，使用海外非cn2gia的网络一般也都不会太好。
这个慢的问题确实很难受。

**Comment by boojack** [comment]
> 为什么简简单单的前端展示，加载这么多语言的js文件呢？一种语言足够了吧

You can always build your own single language version from source code. The official docker image will always be packaged with all supported languages.

**Comment by jneeee** [comment]
Can this change to "Only response the prefer Language.js according to the setting in Setting-preferences"? instand of response all xx.js

**Comment by luoda2024** [comment]
同感，手机加载太慢了。
