### ISSUE TITLE
Cannot access public memos from other users after logged in

### ISSUE THREAD

**Issue by Irvingouj** [usememos/memos#2555]
### Describe the bug

I invited a few friends to use memos together, I can see their public memos before log in, however, it is not accessible anymore from explore section after I logged in.

### Steps to reproduce

Register two accounts, posting two public memos separately, see if you can see the public post from each other.

**Comment by boojack** [comment]
Any more details to reproduce? It works right in my instance.

<img width="732" alt="image" src="https://github.com/usememos/memos/assets/24653555/5b9d3738-1d36-4655-b68a-e7a6163970cb">

**Comment by Irvingouj** [comment]
Let me reproduce this and get back to you.

**Comment by Irvingouj** [comment]
Tried a few times, so, it will happen if the user who send the memo contains a image, and have never send second memo, please see the screen shot
here, we cannot see the public memo with a picture
![noshow in explore](https://github.com/usememos/memos/assets/49964599/2e0b1fd6-298d-4ff7-98f6-13f94feda2a6)
however, it indeed show, when it is in public
![show in public](https://github.com/usememos/memos/assets/49964599/686158fb-04be-4574-ba37-4f2468884291)
Then I tried to send a text memo in public
![show after send text](https://github.com/usememos/memos/assets/49964599/3d43f1ed-66a1-4e33-93b5-0122becedc79)

then both test text and test with image memo showed up.

seem wired to me, but given that it is not always happen and only happen in such an edge case, I would recommand to put this on a low priority

**Comment by boojack** [comment]
See more in https://github.com/usememos/memos/issues/2637
