### ISSUE TITLE
copyDB 依旧失败

### ISSUE THREAD

**Issue by zj-dreamly** [usememos/memos#2560]
### Describe the bug

升级了最新版本，执行 copyDB 命令，依旧提示如下报错

### Steps to reproduce

![image](https://github.com/usememos/memos/assets/33167831/db5b9063-c7a4-47ec-b0dd-a643e2f805a1)

之前在 #2463 曾提过类似问题，现在有个新的报错 ，不太清楚是怎么导致的。

**Comment by boojack** [comment]
`copyDB` is about to be removed because it is not related to the main product. You can use ChatGPT to generate migration scripts, for example: https://www.usememos.com/docs/advanced-settings/database#migrating-data-between-different-drivers
