### ISSUE TITLE
查询为什么要全部遍历数据？如果数据很多怎么办？

### ISSUE THREAD

**Issue by tianyunperfect** [usememos/memos#2561]
### Is your feature request related to a problem?

如图，当我搜索内容时，先查询所有的数据，再过滤，这是正常的逻辑吗？？？
![image](https://github.com/usememos/memos/assets/23491291/4e68e479-2354-4e26-8455-cdc21ea637d2)

### Describe the solution you'd like

希望有一个正常的搜索接口，而不是查询全部

**Comment by boojack** [comment]
Fixed in latest version. See more in the demo site: https://demo.usememos.com
