### ISSUE TITLE
Keep only resources outside database storage

### ISSUE THREAD

**Issue by webysther** [usememos/memos#2563]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

For database storage, maybe will be very good for performance to have resources outside the sqlite database like happens with thumbnail cache already:

![image](https://github.com/usememos/memos/assets/750007/6d360ce2-3f20-40b9-8499-098d1118aff3)

**Comment by boojack** [comment]
You can use local stroage for your resources. Learn more in https://www.usememos.com/docs/advanced-settings/local-storage

**Comment by webysther** [comment]
Yeap, my ideia was more to have resources like images outside sqlite and all information inside the database, the main reason is because the search can stay fast but the database dont grow to bigger, but maybe I just overthinking about...

**Comment by webysther** [comment]
But with support to pgsql maybe this can be ignored
