### ISSUE TITLE
v0.5.0 代码块和内容之间无空格或回车会吞内容

### ISSUE THREAD

**Issue by CtkGHoSt** [usememos/memos#257]
version：0.5.0

markdown：
![](https://p.sda1.dev/7/ca6c10ecb33fc470b545de63ac46e904/code.png)

显示：
![](https://p.sda1.dev/7/b0e114a1aeb0b14291909c144bd08e5b/result.png)

**Comment by boojack** [comment]
markdown正确的代码块写法是第一种。
