### ISSUE TITLE
Add Delete, Archive and Pin button to memo detail pages

### ISSUE THREAD

**Issue by gitkeniwo** [usememos/memos#2575]
### Is your feature request related to a problem?

When you click a marked / linked memo from another memo, you are navigated to the detail page of that memo (`your.site/m/memo_id`) and if you would like to delete / pin this memo, you'll have to go back and search for it again.

### Describe the solution you'd like

Add Delete, Archive and Pin button to memo detail pages

**Comment by MehadND** [comment]
@boojack are you accepting PR for this issue or for any issue in milestone? Or are these just for your self?
