### ISSUE TITLE
Telegram机器人链接问题

### ISSUE THREAD

**Issue by tslcat** [usememos/memos#2578]
### Describe the bug

按“https://www.usememos.com/docs/integration/telegram-bot”教程设置后  不能链接  Telegram发送内容后提示“Please set your telegram userid 3           8 in UserSetting of memos”  

### Steps to reproduce

设置提示全部成功

**Comment by athurg** [comment]
This bug looks like caused by the API was migrate from *v1* to *v2*, and the backend code has some compatible problems.

This'll be fixed in next version.

**Comment by tslcat** [comment]
> 這個bug看起來是由於API從_v1_遷移到_v2_引起的，且後端程式碼存在一些相容問題。
> 
> 這將在下一個版本中修復。

谢谢 期待下一个版本上线
