### ISSUE TITLE
v0.5.0 点击tag无法筛选出memo

### ISSUE THREAD

**Issue by CtkGHoSt** [usememos/memos#258]
version：0.5.0

website: [https://memos.j8.ee](https://memos.j8.ee)

点击tag：
![](https://p.sda1.dev/7/d53c73bc78da7b93cd886b38da650cee/tag.png)

搜索：
![](https://p.sda1.dev/7/46c2a2256763e3670e200f24666ce4f4/yc.png)

**Comment by boojack** [comment]
无法复现

<img width="668" alt="image" src="https://user-images.githubusercontent.com/24653555/193710508-3e4b9d69-e9d9-4daf-a5fc-bf5cc7312a44.png">

**Comment by CtkGHoSt** [comment]
你好，经过复现，如果一个memo有多个tag时，不能显示最后一条

未筛选：
![](https://p.sda1.dev/7/5b8315e3a7991b09d31c1e65da05c880/aa.png)

#筛选test_tag：
![](https://p.sda1.dev/7/3dfa3fd0962d13c80a08e1a1afc397ac/bb.png)

#筛选原创tag：
![](https://p.sda1.dev/7/72ad34d26a0eca49b7fab3db9f6e8d34/cc.png)
