### ISSUE TITLE
全局置顶功能

### ISSUE THREAD

**Issue by xzyone** [usememos/memos#2583]
### Is your feature request related to a problem?

无法向用户展示重要公告，也无法向未登录状态下的游客展示置顶的memo.

### Describe the solution you'd like

希望增加管理员可以设置全局置顶（或公告）功能。

**Comment by boojack** [comment]
You can do it by insert some text into body with custom script. See more in https://www.usememos.com/docs/advanced-settings/custom-style-and-script
