### ISSUE TITLE
Increase use of screen real-estate. 

### ISSUE THREAD

**Issue by easez88** [usememos/memos#2584]
### Is your feature request related to a problem?

Memos has a lot of wasted space on the sides. 
![image](https://github.com/usememos/memos/assets/54665292/4beadede-b56e-4971-be1b-1a1f520fc3a9)
![image](https://github.com/usememos/memos/assets/54665292/101fd54e-9e41-48d3-9c2b-322172754906)

### Describe the solution you'd like

It would be great if memos has better use of its space by setting the max width to be higher for max-w-6xl and max-w-3xl to look something like this:
![image](https://github.com/usememos/memos/assets/54665292/c8f4ab3e-e7ea-43b9-b577-aecb13829bb6)
![image](https://github.com/usememos/memos/assets/54665292/44dfd6a4-cad4-47fc-a061-e29632fbef34)

### Additional context

I am aware that this can be accomplished with custom css, but I thought i would suggest it as a good quality of life upgrade as a whole.

**Comment by boojack** [comment]
Will be updated in v0.18.2.
