### ISSUE TITLE
French translation updated

### ISSUE THREAD

**Issue by 3zmana** [usememos/memos#2586]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Hello, I've updated the French translation :)
I may have to make some minor corrections later because sometimes it's not easy to understand the context of the feature in weblate.

### Additional context

I have one more question: how do you see the word memos ? Is it a brand name for you ? Or should I translate it in French ?

**Comment by boojack** [comment]
> I have one more question: how do you see the word memos ? Is it a brand name for you ? Or should I translate it in French ?

It shouldn't have to be translated. It is a brand for the most part.

**Comment by 3zmana** [comment]
Thank you for your reply :)
I'll make the correction in the old translation when I have some time on my hands.
