### ISSUE TITLE
Lost all memos after updating docker image

### ISSUE THREAD

**Issue by haitispaceagency** [usememos/memos#2590]
### Describe the bug

I followed the instructions in the official [documentation](https://www.usememos.com/docs/install/self-hosting) and after pulling and starting the new image, none of my previous notes are available to read. I did make a back up of the db as the instructions say. Do I just replace the current memos_prod.db with my backup?

### Steps to reproduce

1. have months worth of notes
2. docker stop memos && docker rm memos
3. cp -r ~/.memos/memos_prod.db ~/.memos/memos_prod.db.bak
4. docker pull ghcr.io/usememos/memos:latest
5. docker run -d \
  --init \
  --name memos \
  --publish 5230:5230 \
  --volume ~/.memos/:/var/opt/memos \
  ghcr.io/usememos/memos:latest

6. and then the notes are gone

**Comment by Irvingouj** [comment]
I am sorry about your lost, that happened to me once before as well. I initially thought it was because of I did not mount the volume.

**Comment by Steaunk** [comment]
The same. I can login, but "Failed to fetch memo list".

**Comment by shazril** [comment]
Same happened to my instance.

**Comment by haitispaceagency** [comment]
> I can access back my old notes by rolling back to docker tag [0.15.2](https://hub.docker.com/layers/neosmemo/memos/0.15.2/images/sha256-237380e3d734198ec158c0d8d5308fbd109958560573235b5ee1a99d0ffc1378?context=explore).

That worked for me as well. Thanks for the suggestion!

**Comment by Steaunk** [comment]
> I can access back my old notes by rolling back to docker tag [0.15.2](https://hub.docker.com/layers/neosmemo/memos/0.15.2/images/sha256-237380e3d734198ec158c0d8d5308fbd109958560573235b5ee1a99d0ffc1378?context=explore).

That's right. I can access when rolling back to 0.15.0, but I wonder how we can upgrade.

**Comment by Steaunk** [comment]
> > I can access back my old notes by rolling back to docker tag [0.15.2](https://hub.docker.com/layers/neosmemo/memos/0.15.2/images/sha256-237380e3d734198ec158c0d8d5308fbd109958560573235b5ee1a99d0ffc1378?context=explore).
> 
> That's right. I can access when rolling back to 0.15.0, but I wonder how we can upgrade.

I find the log shows `ERROR   cmd/memos.go:57 failed to migrate db ... migrate error: -- webhook` and I manage to switch to 0.18 by removing table webhook in db.
