### ISSUE TITLE
家人们，请问之前删掉的“捷径”功能还会回归吗？

### ISSUE THREAD

**Issue by i-iooi-i** [usememos/memos#2593]
### Is your feature request related to a problem?

![Snipaste_2023-12-10_14-12-49](https://github.com/usememos/memos/assets/1827701/0a3f9c0a-6202-46e9-9e15-10abc61c74df)
之前这个捷径功能很好用的，筛选图像之类的很方便。
但是这个功能删除很久了，还会回来吗？

### Describe the solution you'd like

暂无

**Comment by i-iooi-i** [comment]
没有人知道吗？

**Comment by boojack** [comment]
Hi @i-iooi-i, the shortcuts actually on the roadmap with backlog status. You can see more in https://github.com/orgs/usememos/projects/5/views/1?pane=issue&itemId=16186802 

You can describe what you want to do with shortcuts in more detail. When we figure out how to do that, we'll start the implemention.

**Comment by i-iooi-i** [comment]
> 你好@i-iooi-i，路线图上实际存在积压状态的快捷方式。您可以在[https://github.com/orgs/usememos/projects/5/views/1?pane=issue&itemId=16186802中查看更多信息](https://github.com/orgs/usememos/projects/5/views/1?pane=issue&itemId=16186802)
> 
> 您可以更详细地描述您想要使用快捷方式执行的操作。当我们弄清楚如何做到这一点时，我们将开始实施。

感谢大佬，期待可以早日见到，这个筛选功能还是很好用的。🫡🫡
