### ISSUE TITLE
Memo comments are listed in memo list

### ISSUE THREAD

**Issue by Chrisg2000** [usememos/memos#2595]
### Describe the bug

Hey,

so either this is a undocumented _new_ feature, or it accidentally changes toward 0.18.0:

In the "home" tab memo comments are now listed besides the actual memos
![image](https://github.com/usememos/memos/assets/6640352/c57cf0db-7281-4aa7-bd57-2eed899e8081)

I do understand, that it might be useful to have it like this, but it removes any kind of structure one had with the comments.

I'm using the SQLite backend.

### Steps to reproduce

1. Have a lot of comments on memos
2. Update to 1.18.0
3. Open Home Tab

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/a297cc3140a535f6ab721fd2c0ddb7eb7de64ff3
