### ISSUE TITLE
instructions to migrate to postgresql backend?

### ISSUE THREAD

**Issue by ahgraber** [usememos/memos#2596]
### Describe the bug

Now that postgresql is available as a database backend, I would like to migrate to it.  Are there instructions for redeploying with a different db backend while retaining current data?

### Steps to reproduce

I do not see instructions for a db migration.

**Comment by gabe565** [comment]
It seems the instructions have been left off of the new database page, but here is a link to the [instructions from SQLite to MySQL](https://www.usememos.com/docs/advanced-settings/mysql#migrating-data-from-sqlite-to-mysql). Migrating to Postgres will be the same, but fails at the moment (#2600). This will be possible once my PR to fix this has been merged and released (#2601)
