### ISSUE TITLE
除了ID是101的用户外，用户即使选择了在工作区发送帖子，帖子的属性仍然是私有。

### ISSUE THREAD

**Issue by pharaohnie** [usememos/memos#2597]
### Describe the bug

除了ID是101的用户外，用户即使选择了在工作区发送帖子，帖子的属性仍然是私有。

### Steps to reproduce

1. 发帖时，设置可见性是“工作区”
2. 发帖后，帖子可见性还是“私有”
3. 编辑帖子改为“工作区”后再刷新，帖子的可见性变为“工作区”

这个问题不存在于ID是101的管理员，只有其他用户才有这个问题。
并且，即使全局设置默认可见性是“工作区”，也有这个问题。

**Comment by maocis** [comment]
同样碰到了这个问题，求解决

**Comment by noumqn** [comment]
Hello dev, great self-hosted application by you. But I am also facing this issue

**Bug**: Except for the mod, even if the user chooses to send a post in the **workspace**, the attribute of the post is still **private**.

**Steps to reproduce**:

    When posting, set the visibility to "Workspace"
    After posting, the visibility of the post is still "private"

    Edit the post and change it to "Workspace" and then refresh it. The visibility of the post will change to "Workspace".

This problem does not exist for the administrator, only **other users** have this problem.
And, I have this problem even if the system default visibility is "Workspace".
