### ISSUE TITLE
Left and right too much blank space, can automatically adapt to the page！

### ISSUE THREAD

**Issue by star2k** [usememos/memos#2598]
### Is your feature request related to a problem?

![Snipaste_2023-12-11_08-56-15](https://github.com/usememos/memos/assets/9582078/85461dd8-4026-45a8-832e-62abc330b613)

Left and right too much blank space, can automatically adapt to the page！

### Describe the solution you'd like

Left and right too much blank space, can automatically adapt to the page！

### Additional context

Left and right too much blank space, can automatically adapt to the page！
![Snipaste_2023-12-11_08-56-15](https://github.com/usememos/memos/assets/9582078/69d17b4d-8145-428a-92e7-17ef6aee52a9)

**Comment by meldarionqeusse** [comment]
Under Settings > System add the following CSS under `Additional style`, save and refresh the page. 

```
.max-w-6xl{
max-width: 100rem;
}
```

![image](https://github.com/usememos/memos/assets/21668964/b6e3345e-7055-4107-be4e-e0566739ae37)



Before: 
![image](https://github.com/usememos/memos/assets/21668964/6d5771be-16a7-4195-baf8-93df7ba7e113)


After:
![image](https://github.com/usememos/memos/assets/21668964/2f194f76-7cae-48eb-8c2a-2ff0504432ed)

**Comment by boojack** [comment]
Duplicated with https://github.com/usememos/memos/issues/2584
