### ISSUE TITLE
pgsql 迁移时候报错

### ISSUE THREAD

**Issue by 7788jay** [usememos/memos#2599]
### Describe the bug

因为user在pgsql上面是关键字，默认会有一张user表，`select * from user` 默认是查询当前用户，
所以迁移的时候会报错：fail to copydb: table 'user' is not empty

### Steps to reproduce

执行 `/usr/local/memos/memos --driver postgres --dsn 'postgresql://root:xxxx@postgresql:5432/memos' copydb --from sqlite:///var/opt/memos/memos_prod.db`

**Comment by boojack** [comment]
Fixed in https://github.com/usememos/memos/pull/2601
