### ISSUE TITLE
Postgres migration error: "fail to copydb: table 'user' is not empty"

### ISSUE THREAD

**Issue by gabe565** [usememos/memos#2600]
### Describe the bug

I just upgraded to v0.18.0 and am attempting to migrate from MariaDB to Postgres, but migration fails with the error:
```
fail to copydb: table 'user' is not empty
```

`user` is a [reserved word](https://www.postgresql.org/docs/current/sql-keywords-appendix.html) in Postgres. It seems like running queries without quoting the `user` table name results in the internal Postgres user table to be used.

### Steps to reproduce

1. Deploy Memos
2. Deploy Postgres
3. Attempt migration from SQLite or MariaDB

### Screenshots or additional context

If I select from the `user` table that Memos created, there are no rows as expected:
```
memos=> select * from "user";
 id | created_ts | updated_ts | row_status | username | role | email | nickname | password_hash | avatar_url
----+------------+------------+------------+----------+------+-------+----------+---------------+------------
(0 rows)
```

But if I run that query without quotes, I get the output of the Postgres users table:
```
memos=> select * from user;
 user
-------
 memos
(1 row)
```

<details>
  <summary>Full log</summary>

```
/usr/local/memos $ MEMOS_DRIVER=postgres MEMOS_DSN='postgresql://memos:***@postgresql/memos' ./memos copydb --from='mysql://memos:***@tcp(mariadb)/memos'
---
Server profile
data: /var/opt/memos
dsn: postgresql://memos:***@postgresql/memos
addr:
port: 5230
mode: prod
driver: postgres
version: 0.18.0
metric: true
---
Checking activity...
Checking memo_relation...
Checking system_setting...
Checking tag...
Checking idp...
Checking memo...
Checking memo_organizer...
Checking resource...
Checking storage...
Checking user...
fail to copydb: table 'user' is not empty
```
</details>

**Comment by 7788jay** [comment]
老哥，你用pgsql删除有问题，我删除其他一条，全部都删除了。
![PixPin_2023-12-11_16-22-42](https://github.com/usememos/memos/assets/7473436/9f8816b2-a0ac-4de2-aeab-646dc7ad8168)
