### ISSUE TITLE
编辑缓存优化建议

### ISSUE THREAD

**Issue by raxpkwd** [usememos/memos#2602]
### Is your feature request related to a problem?

在公司的电脑A上添加了一条待办清单后，
- [ ] item A

这时双击编辑后再关闭，这时电脑A上有了编辑器缓存

回到家后在电脑B上，又新加了一条待办清单，
- [ ] item A
- [ ] item B

第二天到公司进行编辑，加载的是电脑A浏览器里的缓存，
这时如果没有注意点了保存，就会丢失 itemB 的信息
尤其在内容比较多时，很难发现是否少了内容

### Describe the solution you'd like

也许可以在编辑内容，加载缓存的时候，
先从服务器获取该条数据的内容以及更新时间，
与本地缓存的时间对比后，来判断是加载浏览器里的缓存还是最新数据

或许也可以让用户配置在线缓存，
防止在电脑A上编辑了一大段文字没有保存，在电脑B添加了内容后，被覆盖了

**Comment by boojack** [comment]
Refer to: https://github.com/usememos/memos/issues/2737
