### ISSUE TITLE
[BUG] Delete one memo will delete all memos

### ISSUE THREAD

**Issue by Cologler** [usememos/memos#2605]
### Describe the bug

Call `DELETE ${endpoint}/api/v1/memo/${id}` API will delete all memos.

Database driver: PostgreSQL
Memos version: 0.18.0 via Docker

### Steps to reproduce

1. Create a lot of memos from WebUI;
2. Query database to ensure they exist;
3. Delete one memo from WebUI;
4. All memos are deleted.

**Comment by 7788jay** [comment]
![PixPin_2023-12-11_16-22-42](https://github.com/usememos/memos/assets/7473436/40a973ab-1a27-485d-8ea1-0f658c9784a2)

**Comment by Cologler** [comment]
The `vacuumMemo` was generated SQL `DELETE FROM memo WHERE creator_id NOT IN (SELECT id FROM user)`, which should be `DELETE FROM memo WHERE creator_id NOT IN (SELECT id FROM "user")`.

https://github.com/usememos/memos/blob/ec7992553f6b33227058c7bde59d329f9cfe24de/store/db/postgres/memo.go#L227-L246
