### ISSUE TITLE
Postgres driver always "failed to migrate db" on startup

### ISSUE THREAD

**Issue by mariushosting** [usememos/memos#2606]
### Describe the bug

Using the postgres driver I always get "failed to migrate db" on startup on a fresh installation.

### Steps to reproduce

Only the mysql work, PostgreSQL is not fully implemented in this version.

**Comment by jhademcconnell** [comment]
@mariushosting can you share the DSN environment variable you used?

**Comment by mariushosting** [comment]
> @mariushosting can you share the DSN environment variable you used?
I'm using this: 'postgresql://postgres:mypassword@localhost:5432/memos'

**Comment by Lyxon1337** [comment]
same error on my side.

compose environment from db:
      POSTGRES_DB: memos
      POSTGRES_USER: memosuser
      POSTGRES_PASSWORD: memospass

enviroment from memos:
      MEMOS_DRIVER: postgres
      MEMOS_DSN: 'postgresql://memosuser:memospass@memos-db:5432/memos'

After deploy this giant error from memos Container:

`ERROR	cmd/memos.go:57	failed to migrate db	{"error": "failed to exec SQL -- drop all tables first (PostgreSQL style)\nDROP TABLE IF EXISTS migration_history CASCADE;\nDROP TABLE IF EXISTS system_setting CASCADE;\nDROP TABLE IF EXISTS \"user\" CASCADE;\nDROP TABLE IF EXISTS user_setting CASCADE;\nDROP TABLE IF EXISTS memo CASCADE;\nDROP TABLE IF EXISTS memo_organizer CASCADE;\nDROP TABLE IF EXISTS memo_relation CASCADE;\nDROP TABLE IF EXISTS resource CASCADE;\nDROP TABLE IF EXISTS tag CASCADE;\nDROP TABLE IF EXISTS activity CASCADE;\nDROP TABLE IF EXISTS storage CASCADE;\nDROP TABLE IF EXISTS idp CASCADE;\nDROP TABLE IF EXISTS inbox CASCADE;\nDROP TABLE IF EXISTS webhook CASCADE;\n\n-- migration_history\nCREATE TABLE migration_history (\n  version TEXT NOT NULL PRIMARY KEY,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())\n);\n\n-- system_setting\nCREATE TABLE system_setting (\n  name TEXT NOT NULL PRIMARY KEY,\n  value TEXT NOT NULL,\n  description TEXT NOT NULL\n);\n\n-- user\nCREATE TABLE \"user\" (\n  id SERIAL PRIMARY KEY,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  row_status TEXT NOT NULL DEFAULT 'NORMAL',\n  username TEXT NOT NULL UNIQUE,\n  role TEXT NOT NULL DEFAULT 'USER',\n  email TEXT NOT NULL DEFAULT '',\n  nickname TEXT NOT NULL DEFAULT '',\n  password_hash TEXT NOT NULL,\n  avatar_url TEXT NOT NULL\n);\n\n-- user_setting\nCREATE TABLE user_setting (\n  user_id INTEGER NOT NULL,\n  key TEXT NOT NULL,\n  value TEXT NOT NULL,\n  UNIQUE(user_id, key)\n);\n\n-- memo\nCREATE TABLE memo (\n  id SERIAL PRIMARY KEY,\n  creator_id INTEGER NOT NULL,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  row_status TEXT NOT NULL DEFAULT 'NORMAL',\n  content TEXT NOT NULL,\n  visibility TEXT NOT NULL DEFAULT 'PRIVATE'\n);\n\n-- memo_organizer\nCREATE TABLE memo_organizer (\n  memo_id INTEGER NOT NULL,\n  user_id INTEGER NOT NULL,\n  pinned INTEGER NOT NULL DEFAULT 0,\n  UNIQUE(memo_id, user_id)\n);\n\n-- memo_relation\nCREATE TABLE memo_relation (\n  memo_id INTEGER NOT NULL,\n  related_memo_id INTEGER NOT NULL,\n  type TEXT NOT NULL,\n  UNIQUE(memo_id, related_memo_id, type)\n);\n\n-- resource\nCREATE TABLE resource (\n  id SERIAL PRIMARY KEY,\n  creator_id INTEGER NOT NULL,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  filename TEXT NOT NULL,\n  blob BYTEA,\n  external_link TEXT NOT NULL,\n  type TEXT NOT NULL DEFAULT '',\n  size INTEGER NOT NULL DEFAULT 0,\n  internal_path TEXT NOT NULL DEFAULT '',\n  memo_id INTEGER DEFAULT NULL\n);\n\n-- tag\nCREATE TABLE tag (\n  name TEXT NOT NULL,\n  creator_id INTEGER NOT NULL,\n  UNIQUE(name, creator_id)\n);\n\n-- activity\nCREATE TABLE activity (\n  id SERIAL PRIMARY KEY,\n  creator_id INTEGER NOT NULL,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  type TEXT NOT NULL DEFAULT '',\n  level TEXT NOT NULL DEFAULT 'INFO',\n  payload JSONB NOT NULL DEFAULT '{}'\n);\n\n-- storage\nCREATE TABLE storage (\n  id SERIAL PRIMARY KEY,\n  name TEXT NOT NULL,\n  type TEXT NOT NULL,\n  config JSONB NOT NULL DEFAULT '{}'\n);\n\n-- idp\nCREATE TABLE idp (\n  id SERIAL PRIMARY KEY,\n  name TEXT NOT NULL,\n  type TEXT NOT NULL,\n  identifier_filter TEXT NOT NULL DEFAULT '',\n  config JSONB NOT NULL DEFAULT '{}'\n);\n\n-- inbox\nCREATE TABLE inbox (\n  id SERIAL PRIMARY KEY,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  sender_id INTEGER NOT NULL,\n  receiver_id INTEGER NOT NULL,\n  status TEXT NOT NULL,\n  message TEXT NOT NULL\n);\n\n-- webhook\nCREATE TABLE webhook (\n  id SERIAL PRIMARY KEY,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  row_status TEXT NOT NULL DEFAULT 'NORMAL',\n  creator_id INTEGER NOT NULL,\n  name TEXT NOT NULL,\n  url TEXT NOT NULL\n);\n: pq: SSL is not enabled on the server", "errorVerbose": "failed to exec SQL -- drop all tables first (PostgreSQL style)\nDROP TABLE IF EXISTS migration_history CASCADE;\nDROP TABLE IF EXISTS system_setting CASCADE;\nDROP TABLE IF EXISTS \"user\" CASCADE;\nDROP TABLE IF EXISTS user_setting CASCADE;\nDROP TABLE IF EXISTS memo CASCADE;\nDROP TABLE IF EXISTS memo_organizer CASCADE;\nDROP TABLE IF EXISTS memo_relation CASCADE;\nDROP TABLE IF EXISTS resource CASCADE;\nDROP TABLE IF EXISTS tag CASCADE;\nDROP TABLE IF EXISTS activity CASCADE;\nDROP TABLE IF EXISTS storage CASCADE;\nDROP TABLE IF EXISTS idp CASCADE;\nDROP TABLE IF EXISTS inbox CASCADE;\nDROP TABLE IF EXISTS webhook CASCADE;\n\n-- migration_history\nCREATE TABLE migration_history (\n  version TEXT NOT NULL PRIMARY KEY,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())\n);\n\n-- system_setting\nCREATE TABLE system_setting (\n  name TEXT NOT NULL PRIMARY KEY,\n  value TEXT NOT NULL,\n  description TEXT NOT NULL\n);\n\n-- user\nCREATE TABLE \"user\" (\n  id SERIAL PRIMARY KEY,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  row_status TEXT NOT NULL DEFAULT 'NORMAL',\n  username TEXT NOT NULL UNIQUE,\n  role TEXT NOT NULL DEFAULT 'USER',\n  email TEXT NOT NULL DEFAULT '',\n  nickname TEXT NOT NULL DEFAULT '',\n  password_hash TEXT NOT NULL,\n  avatar_url TEXT NOT NULL\n);\n\n-- user_setting\nCREATE TABLE user_setting (\n  user_id INTEGER NOT NULL,\n  key TEXT NOT NULL,\n  value TEXT NOT NULL,\n  UNIQUE(user_id, key)\n);\n\n-- memo\nCREATE TABLE memo (\n  id SERIAL PRIMARY KEY,\n  creator_id INTEGER NOT NULL,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  row_status TEXT NOT NULL DEFAULT 'NORMAL',\n  content TEXT NOT NULL,\n  visibility TEXT NOT NULL DEFAULT 'PRIVATE'\n);\n\n-- memo_organizer\nCREATE TABLE memo_organizer (\n  memo_id INTEGER NOT NULL,\n  user_id INTEGER NOT NULL,\n  pinned INTEGER NOT NULL DEFAULT 0,\n  UNIQUE(memo_id, user_id)\n);\n\n-- memo_relation\nCREATE TABLE memo_relation (\n  memo_id INTEGER NOT NULL,\n  related_memo_id INTEGER NOT NULL,\n  type TEXT NOT NULL,\n  UNIQUE(memo_id, related_memo_id, type)\n);\n\n-- resource\nCREATE TABLE resource (\n  id SERIAL PRIMARY KEY,\n  creator_id INTEGER NOT NULL,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  filename TEXT NOT NULL,\n  blob BYTEA,\n  external_link TEXT NOT NULL,\n  type TEXT NOT NULL DEFAULT '',\n  size INTEGER NOT NULL DEFAULT 0,\n  internal_path TEXT NOT NULL DEFAULT '',\n  memo_id INTEGER DEFAULT NULL\n);\n\n-- tag\nCREATE TABLE tag (\n  name TEXT NOT NULL,\n  creator_id INTEGER NOT NULL,\n  UNIQUE(name, creator_id)\n);\n\n-- activity\nCREATE TABLE activity (\n  id SERIAL PRIMARY KEY,\n  creator_id INTEGER NOT NULL,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  type TEXT NOT NULL DEFAULT '',\n  level TEXT NOT NULL DEFAULT 'INFO',\n  payload JSONB NOT NULL DEFAULT '{}'\n);\n\n-- storage\nCREATE TABLE storage (\n  id SERIAL PRIMARY KEY,\n  name TEXT NOT NULL,\n  type TEXT NOT NULL,\n  config JSONB NOT NULL DEFAULT '{}'\n);\n\n-- idp\nCREATE TABLE idp (\n  id SERIAL PRIMARY KEY,\n  name TEXT NOT NULL,\n  type TEXT NOT NULL,\n  identifier_filter TEXT NOT NULL DEFAULT '',\n  config JSONB NOT NULL DEFAULT '{}'\n);\n\n-- inbox\nCREATE TABLE inbox (\n  id SERIAL PRIMARY KEY,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  sender_id INTEGER NOT NULL,\n  receiver_id INTEGER NOT NULL,\n  status TEXT NOT NULL,\n  message TEXT NOT NULL\n);\n\n-- webhook\nCREATE TABLE webhook (\n  id SERIAL PRIMARY KEY,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  row_status TEXT NOT NULL DEFAULT 'NORMAL',\n  creator_id INTEGER NOT NULL,\n  name TEXT NOT NULL,\n  url TEXT NOT NULL\n);\n: pq: SSL is not enabled on the server\ngithub.com/usememos/memos/store/db/postgres.(*DB).prodMigrate\n\t/backend-build/store/db/postgres/migrator.go:90\ngithub.com/usememos/memos/store/db/postgres.(*DB).Migrate\n\t/backend-build/store/db/postgres/migrator.go:30\ngithub.com/usememos/memos/cmd.glob..func2\n\t/backend-build/cmd/memos.go:55\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\ngithub.com/usememos/memos/cmd.Execute\n\t/backend-build/cmd/memos.go:103\nmain.main\n\t/backend-build/main.go:11\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650"}
`

**Comment by jhademcconnell** [comment]
@mariushosting @Lyxon1337 can you try the DSN's environment value using this pattern to see if it works:

`postgresql:///{DB_NAME}?host={DB_HOST}&user=postgres&password={DB_PW}&sslmode=disable`

Replace the {variables} with your values

**Comment by Cologler** [comment]
@Lyxon1337 Your logs show `pq: SSL is not enabled on the server`

**Comment by Lyxon1337** [comment]
ah jesus the SSL not seen...
the: `MEMOS_DSN: 'postgresql://memosuser:memospass@memos-db:5432/memos?sslmode=disable'` are working... noice
