### ISSUE TITLE
Cannot add emoji

### ISSUE THREAD

**Issue by cjmdaixi** [usememos/memos#2608]
### Describe the bug

In latest version, I cannot add emoji to my memos. Emoji like 😂

### Steps to reproduce

1. Open memos.
2. Add any memo with emoji, e.g. Hello 😂
3. Click submit. Error shows as "Failed to create memo!"

### Screenshots or additional context

![Uploading Snipaste_2023-12-12_15-49-05.png…](https://nas.chenjinming.space:2002/i/2023/12/12/pmxura-2.png)

**Comment by boojack** [comment]
Cannot reproduce.

<img width="701" alt="image" src="https://github.com/usememos/memos/assets/24653555/f08eb3e7-6364-4df5-9d69-aac263273560">

**Comment by cjmdaixi** [comment]
> Cannot reproduce.
> 
> <img alt="image" width="701" src="https://private-user-images.githubusercontent.com/24653555/289852276-f08eb3e7-6364-4df5-9d69-aac263273560.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDIwMDgsIm5iZiI6MTcwMjU0MTcwOCwicGF0aCI6Ii8yNDY1MzU1NS8yODk4NTIyNzYtZjA4ZWIzZTctNjM2NC00ZGY1LTlkNjktYWFjMjYzMjczNTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA4MTUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMjkzMTZhZjEwYjQwNTc5MjJmNDU3NTc4OWI4OTI1MzBlZmYzM2E4ZjkzMDgyNzdiYzMzMGU1YWYwZjU2NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q9BX9v1Tbg-dGei4WjtsaUL_ySwn3IQOyqxmG7yMdO8">

HI, sorry not providing some details. I deployed my memos server on my Synology NAS using Docker. I use MariaDB as data storage. Then the bug can be reproduces.

And I also found the reason behind it: the data type of `content` in the table `memos` is utf8mb3_general_ci. After I manually changed the type to utf8mb4_general_ci, the bug is gone. And Now I can insert any emoji as I want.

<img width="260" alt="emoji_bug" src="https://github.com/usememos/memos/assets/3907725/4693d6e9-43cf-4451-b18c-1d9843ea413f">

**Comment by boojack** [comment]
It looks like it's a character set issue with your database.
