### ISSUE TITLE
Please add conflict resolution

### ISSUE THREAD

**Issue by pisceswb** [usememos/memos#2612]
### Is your feature request related to a problem?

1. Mobile phones always like to keep apps running in the background.
2. If a memo is modified on the PC side.
3. Call up the app from the mobile background and directly edit the same memo. After synchronization, the modified content on the PC will be lost. No prompts or warnings.
4. Can you add the conflict resolution mechanism ? To prevent accidental loss of data.

Thank you!

### Describe the solution you'd like

Please add conflict resolution

**Comment by boojack** [comment]
See more in https://github.com/usememos/memos/issues/2637
