### ISSUE TITLE
Please add recording and photo buttons when using on the mobile browser.

### ISSUE THREAD

**Issue by pisceswb** [usememos/memos#2613]
### Is your feature request related to a problem?

The existing mobile apps of memos are not very user-friendly. For example, unable to record audio, unable to record videos, and easily causing data conflicts and unintentional loss of notes. 
I want to use my mobile browser to open Memos. Could you please add a recording button and a photo button for memos used on mobile browser? 
Thank you!

### Describe the solution you'd like

add recording and photo buttons when using on the mobile browser

**Comment by boojack** [comment]
The button to upload resource(including photo and audio) is already in the website.

**Comment by pisceswb** [comment]
> The button to upload resource(including photo and audio) is already in the website.

Can only add existing photos in the album, but cannot take photos

**Comment by boojack** [comment]
![image](https://github.com/usememos/memos/assets/24653555/74fc53b0-a687-4aea-bb9d-888b54142d9f)

**Comment by pisceswb** [comment]
Not for Android phones.
After clicking the Select File button, it will directly open the recent files page of the phone system.
@boojack

**Comment by boojack** [comment]
Try to upgrade your os version or change a device. We won't do this adaptation.

![Screenshot_2024-01-16-09-01-07-003_com.android.intentresolver.jpg](https://github.com/usememos/memos/assets/24653555/609113b3-db0d-4ea4-b6fa-cfa872fe296d)

**Comment by pisceswb** [comment]
I tried Edge browser. It has functions such as taking photos, recording videos, and opening files, but lacks voice recording.
A more serious flaw is that it can only upload one file at a time. If you take two photos, only the last one will be saved, and the first photo will disappear without any prompts.
Hopefully it will be optimized for the edge browser, which has a lot of users.
In addition, can you tell me the name of your current Android browser, thank you !
@boojack 
![293253f9bac8ef61b2bd68ce6e1090d](https://github.com/usememos/memos/assets/104658457/efeb5484-5951-4947-9391-c9a97d8b4725)

**Comment by pisceswb** [comment]
Audio recordings in amr format uploaded by mobile phones cannot be played
