### ISSUE TITLE
Deleting a memo also deletes the resources of other memos

### ISSUE THREAD

**Issue by jhademcconnell** [usememos/memos#2616]
### Describe the bug

After deleting a memo, memos with resources (like a picture) are deleted. The memo intended to be deleted is removed, but the resources in other memos are also removed. The text in other memos are still visible.

The image is built using the latest codebase pulled for the delete issue: https://github.com/usememos/memos/commit/6bda64064e4dc8a6401e48f83f282833121e8afe

This setup uses a postgresql DB.

### Steps to reproduce

1. Create a memo with text and a resource (a picture)
2. Create another with text
3. Delete the memo from step 2
4. Refresh the page
5. The memo's resource from step 1 is also deleted (also verified in the "resources" tab that no resources exists)

### Screenshots or additional context

https://github.com/usememos/memos/assets/13276370/47fc08f9-3242-4f77-b11e-0f023ecf3fbe

**Comment by Cologler** [comment]
I can confirm the bug is there:

https://github.com/usememos/memos/blob/b20e0097cfd7c84546ceb9daff38e82b330b6223/store/db/postgres/resource.go#L188

**Comment by boojack** [comment]
Fixed in https://github.com/usememos/memos/commit/2d9c5d16e1a38dc9a225ee8d56bf862b41e7f3a8
