### ISSUE TITLE
Add a options to change telegram API url.

### ISSUE THREAD

**Issue by LxnChan** [usememos/memos#2618]
### Is your feature request related to a problem?

In areas with poor network conditions or behind firewalls, it may not be possible to correctly access Telegram's API (api.telegram.org). However, it can set up a proxy using Cloudflare Workers to access the API properly.

### Describe the solution you'd like

Add a text box or other ways to set the HOST of telegram API for the request.
![image](https://github.com/usememos/memos/assets/46388610/6cce96dc-5909-4b5f-a306-1055dd85febb)

**Comment by boojack** [comment]
See more in: https://www.usememos.com/docs/integration/telegram-bot#use-a-proxy-for-telegram-api
