### ISSUE TITLE
The memo list is often incorrect

### ISSUE THREAD

**Issue by shinyes** [usememos/memos#2619]
### Describe the bug

The memo list is often incorrect and needs to be refreshed to display the correct memo list

### Steps to reproduce

1. Click on Home or Explore

**Comment by gitkeniwo** [comment]
I have the same problem from time to time, but still unsure how to reproduce. Occasionally some recent memos are missing. Could happen in both main timeline and the Explore page.

**Comment by shinyes** [comment]
before:
![PixPin_2023-12-16_14-43-40](https://github.com/usememos/memos/assets/44279849/9f21fbb4-ca31-4c2b-90d8-fafcb21dff41)
after:
![PixPin_2023-12-16_14-43-56](https://github.com/usememos/memos/assets/44279849/7c58af56-b545-4314-a29f-73f2e775bb70)

**Comment by boojack** [comment]
See more in https://github.com/usememos/memos/issues/2637
