### ISSUE TITLE
Unable to Change Username / Nickname/ Email

### ISSUE THREAD

**Issue by ericb0x** [usememos/memos#2621]
### Describe the bug

I have Memos with PostgreSQL spun up and I'm unable to save a 'nickname' or 'optional email' for a user. I can't change the username either. When I go to save these changes, nothing happens. 

### Steps to reproduce

Go to: Settings/My Account/Edit/enter 'x' in the fields and save.

### Screenshots or additional context

<img width="1001" alt="Screenshot 2023-12-14 at 6 12 17 PM" src="https://github.com/usememos/memos/assets/111396448/a65a9870-d737-4477-93e1-d886a74745f7">

**Comment by lyfar** [comment]
same

**Comment by boojack** [comment]
Fixed in 7eb5be0a4e2357d1866ada0dca84f3d527982187

**Comment by quanru** [comment]
> Fixed in [7eb5be0](https://github.com/usememos/memos/commit/7eb5be0a4e2357d1866ada0dca84f3d527982187)

提示失败，然后第二天提示登录过期，就登不上账号了
