### ISSUE TITLE
Attach photos/Files from "📎 Resources"

### ISSUE THREAD

**Issue by Docmine17** [usememos/memos#2625]
### Is your feature request related to a problem?

Having to upload photos/files that are already in "📎Resources" to be able to use them again.
![Captura de tela de 2023-12-15 13-13-05](https://github.com/usememos/memos/assets/67164552/42d4ac04-692c-42e5-b08e-63f853635454)

### Describe the solution you'd like

Add an option to select a photo/file already present in the resources tab, thus avoiding having to upload the file again.

Attach method:
- Upload files
- External Links
- Pick from Resources(New)

![Captura de tela de 2023-12-15 13-07-29](https://github.com/usememos/memos/assets/67164552/797b5e9b-51a9-4581-b318-237f0df379b3)

This can reduce storage usage and improve the user experience.

**Comment by boojack** [comment]
Each resource can only be used by one memo.
