### ISSUE TITLE
The Explore page shows empty when logged in

### ISSUE THREAD

**Issue by tigerzioo** [usememos/memos#2626]
### Describe the bug

The Explore page shows all public memos when not logged in. However, the Explore page shows empty when logged in.

### Steps to reproduce

Signed out. I can see all public memos.
Signed in. The public memos will not be showed in the Explore page.

**Comment by boojack** [comment]
Cannot reproduce.

https://github.com/usememos/memos/assets/24653555/3bde720e-19ae-48d2-a573-5858026bddd7

**Comment by tigerzioo** [comment]
I am using mysql version. Is it the issue for mysql?

**Comment by tigerzioo** [comment]
I tested it on both sqlite and mysql version. It looks fine on sqlite version. It is a bug on mysql version.
Thank you.

**Comment by boojack** [comment]
Tried MySQL, can't reproduce it too.

<img width="864" alt="image" src="https://github.com/usememos/memos/assets/24653555/25e1446a-c8fb-440b-a7fb-1eeac4c25051">

**Comment by dbx-3** [comment]
I have the same issue. When logged in, the explore page is empty. When i press F5, the page is loaded.
When logged out, the explore page works instantly.

Database is sqlite.
