### ISSUE TITLE
Run image compression before uploading a resource

### ISSUE THREAD

**Issue by jhademcconnell** [usememos/memos#2628]
### Is your feature request related to a problem?

**Problem**

Photos taken by mobile devices are large. When uploading image resources, this can take up a lot of storage space.

### Describe the solution you'd like

Memos can decrease the file size of images stored by compressing the image through a browser-based method. Something like these projects can be looked into: 

- https://github.com/fengyuanchen/compressorjs
- https://github.com/flyimg/flyimg

There are 3 settings: enable/disable compression, compression %, timeout

Enable/disable compression turns on and off compression. Disabling this feature are for users whose phones may slow down due to being on an older device.

Compression % is a range that adjusts how hard the compression engine should run. Set a default value that would perform best for general devices. Users can increase/decrease this based on how well their device can handle it.

Timeout is a threshold in milliseconds to stop compressing. If the threshold is met, allow the user the option to upload anyway or cancel the upload. There should also be a default value set for general cases.

When compression is enabled for specific file types (.png, .jpeg, etc.):

- User chooses a local file
- User clicks create
- Image being compressed with compression % (loading animation)
- Resource/Memo created with compressed image

Adding a compression step on resource upload would help decrease the storage used and makes it friendlier to post images.

**Comment by jhademcconnell** [comment]
Ran across squoosh.app, which does image compression locally via your web browser: https://github.com/GoogleChromeLabs/squoosh

I run compression on images through this site and then upload to Memos to save storage and memory when loading images. 

This would be a good codebase to analyze and see how compression is done

**Comment by q2apro** [comment]
You can use simple Javascript to achieve image compression.

See code at https://stackoverflow.com/questions/19262141/resize-image-with-javascript-canvas-smoothly/19262385#19262385

**Comment by boojack** [comment]
There are some scenarios where users just need to save the original image. If you need, you can compress it first and then upload it.
