### ISSUE TITLE
0.18.1 Failed to save resource to R2

### ISSUE THREAD

**Issue by lazyyz** [usememos/memos#2630]
### Describe the bug

After updating to version 0.18.1, the image upload to R2 failed with the following error log. After rolling back to 0.18.0, it returned to work. The R2 region is auto.

`{"time":"2023-12-16T05:30:23Z","latency":"1.259843ms","method":"POST","uri":"/api/v1/resource/blob","status":500,"error":"code=500, message=Failed to save resource, internal=Failed to upload via s3 client: operation error S3: PutObject, resolve auth scheme: resolve endpoint: endpoint rule error, Invalid region: region was not a valid DNS name."}`

### Steps to reproduce

1. Update to 0.18.1
2. Update image
3. click create
4. show wrong message: "Failed to save resource"

**Comment by ertuil** [comment]
I notice the same error. I am using Aliyun OSS

**Comment by boojack** [comment]
As far as I know, the relevant code has not changed. Maybe you could try downgrade to `0.18.0` to see if the problem still exists.

* https://github.com/usememos/memos/commits/main/api/v1/resource.go
* https://github.com/usememos/memos/commits/main/plugin/storage/s3/s3.go

**Comment by lazyyz** [comment]
I am currently using `0.18.0` and it works fine.

**Comment by ertuil** [comment]
I rolled it back to `0.18.0`, and it works fine. This bug is possibly related to the `aws-sdk-go-v2`, which seems to have been upgraded recently.

**Comment by qxxiao** [comment]
@boojack seems the update to aws-sdk-go-v2 in version 0.18.1 leads to  this problem.  
<https://community.cloudflare.com/t/r2-error-in-aws-sdk-go-v2-region-was-not-a-valid-dns-name/584769/4>

**Comment by boojack** [comment]
@ertuil @qxxiao Good catch! Thanks for your reporting. Fixed with https://github.com/usememos/memos/commit/16fb5faebdcae22fe1f314e085bca9b1c934f490, and it will be cherry-pick to `v0.18.1`.
