### ISSUE TITLE
不用下载其他软件能安装吗

### ISSUE THREAD

**Issue by wenchanggai** [usememos/memos#2632]
### Is your feature request related to a problem?

下载Docker那个在电脑上好卡呀。不用下载能安装吗

### Describe the solution you'd like

下载Docker那个在电脑上好卡呀。不用下载能安装吗

**Comment by sicl5300** [comment]
Try to manually compile it in reference of `dockerfile`.

**Comment by jhademcconnell** [comment]
If the question is how to run Memos without installing Docker, take a look at this repo. You can install a local instance of Memos to try without Docker: https://github.com/lincolnthalles/memospot
