### ISSUE TITLE
An error occurs when the iPhone is opened

### ISSUE THREAD

**Issue by suppercarl** [usememos/memos#2633]
### Describe the bug

If you use Safari to open the demo website, the following error occurs, even if it is V0.18.0
V0.17 can be used normally
![IMG_0162](https://github.com/usememos/memos/assets/154035072/f7935c0c-ebf6-4f24-b10a-b28b00aa46fc)

Unexpected Application Error!
Invalid regular expression: invalid group specifier name
RegExp@[native code]
module code@https://demo.usememos.com/assets/MemoResourceListView-fa84cf3d.js:270:88898
evaluate@[native code]
moduleEvaluation@[native code]
moduleEvaluation@[native code]
moduleEvaluation@[native code]
@[native code]
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]

### Steps to reproduce

open website

**Comment by boojack** [comment]
I just redeployed the demo site, please try again?

**Comment by suppercarl** [comment]
> I just redeployed the demo site, please try again?

yes,It's ok now.
