### ISSUE TITLE
Access Tokens cannot be deleted or modified after automatic creation | Access Tokens 自动创建无法删除或修改

### ISSUE THREAD

**Issue by ccsen** [usememos/memos#2634]
### Describe the bug

Service Version: v18.0
Environment: Chrome 120
Issue Description: An infinite-duration Access Token is automatically created each time the login is refreshed, and it cannot be deleted or modified, posing a security risk.
服务版本：v18.0
使用环境：chrome 120
问题描述：每次重新登录都自动创建了永不过期的Access Token，且无法删除或修改，存在安全风险。
![截屏2023-12-17 16 39 14](https://github.com/usememos/memos/assets/25996944/4d6433b3-98bf-47a7-89bc-2f2fc53bf64f)

### Steps to reproduce

1. Log out, and open the login page
2. Log in to Memos again
3. Check the Access Tokens page and find a new Access Token added to the visible list

1. 退出账户，打开登录页
2. 重新登录memos
3. 查看Access Tokens页面可见列表增加一个新的Access Token

**Comment by jhademcconnell** [comment]
@ccsen if you scroll all the way to the right, the trash can button should be visible to delete the Access tokens in the list. If you're on mobile, try scrolling towards the right. 

An Access token is created with a 7 day expiration when you log in without choosing "remember me".  If you choose "remember me", the Access token expires indefinitely until revoked or updated on log out.

**Comment by ccsen** [comment]
> @ccsen if you scroll all the way to the right, the trash can button should be visible to delete the Access tokens in the list. If you're on mobile, try scrolling towards the right.
> 
> An Access token is created with a 7 day expiration when you log in without choosing "remember me". If you choose "remember me", the Access token expires indefinitely until revoked or updated on log out.
> 
> I was not able to create multiple Access tokens that never expire with my chrome browser when logging in/out (tried both mobile and desktop).

You are right !
