### ISSUE TITLE
The Memos article details page has display issues.

### ISSUE THREAD

**Issue by flydo** [usememos/memos#2635]
### Describe the bug

The Memos article details page has display issues.

[https://demo.usememos.com/m/39](https://demo.usememos.com/m/39)

![image](https://github.com/usememos/memos/assets/3362147/398210ad-6146-4825-95b3-4023522caf90)

![image](https://github.com/usememos/memos/assets/3362147/598d5f6a-4e38-4ee5-973c-54d4ed6ef793)

### Steps to reproduce

Memos:

```bash
import docker gpg command lines：
```bash
curl -s --compressed "https://download.docker.com/linux/debian/gpg" | gpg --dearmor | sudo tee /etc/apt/keyrings/docker.gpg > /dev/null
```

![image](https://github.com/usememos/memos/assets/3362147/978de45e-ca41-4a92-a133-5df96f2d83f6)

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/2c4b5d75b3b3f2d87cdcca29ed422533b49155dd. Thanks for your reporting!
