### ISSUE TITLE
0.18.1 Display Issue 

### ISSUE THREAD

**Issue by qxxiao** [usememos/memos#2637]
## Display the latest memos promptly
when logins in, system loads the user's first `limit` memos(or more based on the `offset`).  
Main page `api/v1/memo?creatorUsername=demo&rowStatus=NORMAL&limit=20`  or  
`api/v1/memo?creatorUsername=demo&rowStatus=NORMAL&offset=6&limit=20`

open explore page,  it loads the remaining memos using `offset`(cache memos).  
`api/v1/memo/all?offset=6&limit=20`   
By default, it seems to be sorting in descending order based on `createdTs`, and thus might not fetch the most recent `offset` memos.(For single-user use, this is ok. For multiple users, there might be missing memos at the beginning or in the middle.)   
Only by manually refreshing the `/explore`, could load latest memos starting from `offset = 0`.
 
A separate time range can be used to indicate that the latest memos within this interval have already been fetched. 
And it seems that after loading via `/api/v1/memo/all` and if there are no more memos, subsequent requests for new memos in `/explore` are not triggered. 

##  Related issues
- <https://github.com/usememos/memos/issues/2626>
- <https://github.com/usememos/memos/issues/2619>
- <https://github.com/usememos/memos/issues/2555>
- <https://github.com/usememos/memos/issues/2612>

### Steps to reproduce

Multiple users post multiple memos in an interleaved manner.

**Comment by boojack** [comment]
The next version will switch to gRPC API, which may solve the problem. And the frontend part will also improve its display and requests. You can try it now via the demo site: https://demo.usememos.com
