### ISSUE TITLE
Custom RSS Feed Reader to Explore Other Memo Instances

### ISSUE THREAD

**Issue by jhademcconnell** [usememos/memos#2638]
### Is your feature request related to a problem?

Some people use Memos as a single-user instance to post daily memos. Adding the ability for Memo instances to follow other Memo instances by keeping a list of RSS feeds creates a "social feed" for people to view within their Memo instance.

### Describe the solution you'd like

There is an RSS feed exposed for each user: `https://{memoInstance}/u/1/rss.xml` that can be parsed and passed onto the frontend.

The solution is a `View Other Instance Memos` setting that can be enabled/disabled. When disabled, this feature is kept off for people that do not want to use it and keep their Memos instance simple. When enabled, a new tab on the left called `Feeds` is displayed.

On the settings page, there is a freeform textbox the user can input a list (CSV) of RSS feeds from users in Memo instances that they'd like to subscribe to:

`
https://{memoInstance1}/u/1/rss.xml,
https://{memoInstance2}/u/1/rss.xml,
https://{memoInstance3}/u/1/rss.xml
`

The solution ingests the list of RSS feeds and orders the memos by date descending (latest Memos posted comes first). Only public memos should be able to be viewed from other instances (private memos can be enabled in the future through a proper authentication method).

When used with an RSS feed that can be filtered through tags used in memos (https://github.com/usememos/memos/issues/1813), Memo instances will be able to view memos specifically posted for things like drinks and food. In the below case, my explore feed will be memos from instance1 that's tagged boba and restaurants, and all memos from instance2.

`
https://{memoInstance1}/u/1/rss.xml?tag=boba,
https://{memoInstance1}/u/1/rss.xml?tag=restaurants,
https://{memoInstance2}/u/1/rss.xml
`

### Additional context

Having the ability for Memo instances to simply "follow" other Memo instances by maintaining a list of RSS feeds to view expands on the social interaction features of Memo and creates a framework for custom RSS feeds to be imported into your Memo instance.

**Comment by boojack** [comment]
We're going to implement ActivityPub in memos, which will enable connections between different instances. Reference to https://github.com/usememos/memos/issues/878
