### ISSUE TITLE
对于探索页面的列表需求

### ISSUE THREAD

**Issue by Dcr-chen** [usememos/memos#2640]
### Is your feature request related to a problem?

在探索页面缺少一个banner位置, 我想如果可以,管理员可以设置编辑探索页面的banner位, 设置一些文案或者图片,

另外在探索页面中,底部的"点击加载更多"按钮之后, 添加一个页脚的编辑区域, 可以加入一些备案信息 或者一些文案. 这比较适用于中国的用户需求.

### Describe the solution you'd like

如果团队可以考虑下这个需求, 万分感谢...

**Comment by boojack** [comment]
You can do it by inserting some text into target element with custom script. Learn more in https://www.usememos.com/docs/advanced-settings/custom-style-and-script
