### ISSUE TITLE
Unexpected Application Error! Invalid regular expression!

### ISSUE THREAD

**Issue by okhanyu** [usememos/memos#2642]
### Describe the bug

Unexpected Application Error! Invalid regular expression: invalid group 
specifier name 
RegExp@[native code] 
module code@https://memos.xxx.com/assets/MemoResourceListView-8931b1bc.js:270:1182438 
evaluate@[native code] 
moduleEvaluation@[native code] 
moduleEvaluation@[native code]
moduleEvaluation@[native code] 
@[native code] 
asyncFunctionResume@[native code] 
@[native code] 
promiseReactionJobWithoutPromise@[native code] 
promiseReactionJob@[native code]

Error resolution(问题原因以及解决方法，开发者可参考)：
[https://www.jianshu.com/p/0e6f0728df01](https://www.jianshu.com/p/0e6f0728df01)

![IMG_2496](https://github.com/usememos/memos/assets/82444480/a4207e80-faab-42d6-992c-19d8debaec25)
![IMG_2495](https://github.com/usememos/memos/assets/82444480/94d5244d-e126-4a91-b3fb-caa088ac3f94)

### Steps to reproduce

打开就会重现，iOS系统无法使用。

**Comment by jhademcconnell** [comment]
Similar issue to: https://github.com/usememos/memos/issues/2639

**Comment by jhademcconnell** [comment]
@okhanyu this looks to be a duplicate issue from my comment above. Could you please close this and include these same details on the issue I linked? That way we have all this info in one place
