### ISSUE TITLE
Categorize the “enhancement” Issues With a Second Label

### ISSUE THREAD

**Issue by jhademcconnell** [usememos/memos#2643]
### Is your feature request related to a problem?

There are close to 200 “enhancement” requests on the Memos GitHub page. This size may be challenging for the Memos team and users to keep track of requests already made.

### Describe the solution you'd like

To help categorize and ensure no duplicate enhancement requests are being created, Memos can include a second label for people to include when an “enhancement” is created.

The list of second labels could be:
- **User Interface (UI)** - Requests that improve or change the visual look/feel of the Memos UI.
  - Ex: CSS changes to improve the look/feel of Memos and not displaying the number of seconds on a Memo.
- **User Experience (UX)** - Requests that improve or change the usability of Memos. Most requests will fall into this, as users requests for functionality to be added that improves how they use Memos.
  - Ex: Adding a live preview before posting a Memo and adding the ability to filter memos with multiple tags
- **API** - Requests to update/change functionality for the Memos REST API. 
  - Ex: Adding a new API endpoint or updating an API’s behavior/response
- **Integrations** - Requests to integrate a third party product to improve Memos. Third party products include Enterprise solutions or open source software
  - Ex: Integrating with Cloudflare Turnstile/Google reCAPTCHA to decrease bots within Memos instances
- **Technical** - Requests to improve the Memos developer experience or the technical workings of Memos. These tend to optimize Memos from a technical perspective.
  - Ex: Logging SQL queries in dev mode to help debug issues and decreasing resource size in Memos.

More can be added (or labels proposed can be changed) if necessary. This is a start towards organizing the list of “enhancements” to make it easier for users and the Memos team to browse “enhancement” requests made. 

### Additional context

When going through current “enhancements”, there are some times duplicate requests. 

It’s becoming hard for people to view what is requested because of the number of requests coming in (this also shows the popularity of Memos so some way to further organize may help).

Hopefully this decreases the number of duplicate requests opened and helps manage the “enhancements” requests.

**Comment by boojack** [comment]
Great suggestion! I'd like to adjust it later.

**Comment by boojack** [comment]
It may not be possible to set the label dynamically when the issue is created, but I've added a new form for that. Feel free to submit a PR if you find another way that works!

<img width="894" alt="image" src="https://github.com/usememos/memos/assets/24653555/ccc14349-69dc-4348-ab43-17b5e7659932">

Refer to: https://github.com/usememos/memos/commit/cc40803b065f6d913dcd5d0e6158df0efc6fdfed
