### ISSUE TITLE
特性字符串应该被识别成了公式

### ISSUE THREAD

**Issue by Jesn** [usememos/memos#2645]
### Describe the bug

我把随机密码放到Memos里面，发现有些密码的格式变化了，看样子应该是转化成公式了，复制出来是乱码的，例如以下字符串 `8$Anm7hN2G$$Xt3`
<img width="752" alt="image" src="https://github.com/usememos/memos/assets/5728274/f55d0493-2ee7-4f7d-8f0d-aed78d5404e4">

### Steps to reproduce

输入以下字符串保存即可  ``8$Anm7hN2G$$Xt3``

**Comment by swimmingchar** [comment]
当作code放在```bash ``` 内
![图片](https://github.com/usememos/memos/assets/8534783/eba5f422-1380-4c86-b9d7-89c2e423309c)

**Comment by boojack** [comment]
Will be fixed in next version.
