### ISSUE TITLE
Telegram Bot Token之类的可以通过变量增加么

### ISSUE THREAD

**Issue by aefa6** [usememos/memos#2646]
### Is your feature request related to a problem?

现在情况是添加TG的token得通过网页去修改保存，不知道是否可以在部署的时候直接加这个变量

### Describe the solution you'd like

是否可以增加一个部署的时候直接增加这个变量赋值，也许本来就有只是我不会？请大佬指导下。

**Comment by athurg** [comment]
Currently, *Memos* doesn't support to config the SystemSetting while launch the process.

**Comment by boojack** [comment]
Add/update in your website or database directly.
