### ISSUE TITLE
When the content is long, there is a problem that it cannot wrap correctly.

### ISSUE THREAD

**Issue by Catcheryp** [usememos/memos#2647]
### Describe the bug

When the content is long, there is a problem that it cannot wrap correctly.

### Steps to reproduce

1. Problem demonstration
Use the text below to test
```plain
### 学习日报20231218期
#域名接管 #漏洞分析
1、文章
[记xxxxxxxxxxxxxxxxxxx](https://baidu.com)
h1 746000、h1 794382
[防zzzzzzzzzzzzzzzzzzzz53](https://docs.aws.amazon.com)
---管理员xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx委派。

---这里换行有点问题---

[ppppppppppppppppppppppppppppppppppp？](https://baidu.com)
---看zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
```
The icon cannot be wrapped correctly：

![image](https://github.com/usememos/memos/assets/11362819/3ecbf060-5ed6-4bbd-8bf9-1bb295505f12)

**Comment by boojack** [comment]
Might be fixed in the latest version. https://demo.usememos.com/

<img width="796" alt="image" src="https://github.com/usememos/memos/assets/24653555/ac4cb7be-2316-4265-81a4-975331788fe7">
