### ISSUE TITLE
编辑时和提交后，文件显示顺序不同

### ISSUE THREAD

**Issue by qwasdev** [usememos/memos#2649]
### Describe the bug

编辑时与提交后，文件显示顺序不同

### Steps to reproduce

https://github.com/usememos/memos/assets/134053124/a56d9b46-f45a-42cb-bdc9-2476585fc5ce

**Comment by qwasdev** [comment]
个人觉得，在详情里先上传的要排在前面吧

**Comment by asadahimeka** [comment]
我这边也是，不知道从哪个版本开始，上传的文件全变成相反的顺序了……

**Comment by bfansheng** [comment]
我也遇到这个问题

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/8b9455d784df299bb8e44ea8aa630b1e7664029b
