### ISSUE TITLE
When the content is long, there is a problem that it cannot wrap correctly.

### ISSUE THREAD

**Issue by Catcheryp** [usememos/memos#2652]
### Describe the bug

When the content is long, there is a problem that it cannot wrap correctly.

### Steps to reproduce

Still the same problem：https://github.com/usememos/memos/issues/2647
Still the same problem as before, I am using the latest version v0.18.1. But what is very strange is why the v0.18.1 version I use is different from the v0.18.1 version you use. For example, your version has a timeline, but mine does not.

1、I was using the latest version v0.18.1
![image](https://github.com/usememos/memos/assets/11362819/c7a71784-1cc8-4fa7-b982-c377d3d47fa2)

You can test it on this link：http://47.110.150.103:5230
```plain
### 学习日报20231218期
#域名接管 #漏洞分析
1、文章
[记xxxxxxxxxxxxxxxxxxx](https://baidu.com)
h1 746000、h1 794382
[防zzzzzzzzzzzzzzzzzzzz53](https://docs.aws.amazon.com)
---管理员xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx委派。

---这里换行有点问题---

[ppppppppppppppppppppppppppppppppppp？](https://baidu.com)
---看zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
```

2、Why is [my v0.18.1 version](http://47.110.150.103:5230) different from [your v0.18.1 version](https://demo.usememos.com/)
![image](https://github.com/usememos/memos/assets/11362819/f1df47d2-a570-4846-bc05-57ef20528584)

**Comment by Catcheryp** [comment]
I did some research and found that it was caused by "---". Changing it to "--" eliminated the problem.
But I don’t know why my version 0.18.1 is different from yours.

**Comment by boojack** [comment]
Duplicated with https://github.com/usememos/memos/issues/2647. And please wait for the next release.
