### ISSUE TITLE
登录后，再次刷新页面会显示报错，无法加载内容

### ISSUE THREAD

**Issue by gongjuecloak** [usememos/memos#2653]
### Describe the bug

![image](https://github.com/usememos/memos/assets/100070999/b5ef683f-648a-4449-ac81-34e7166bc604)

### Steps to reproduce

登录后，刷新页面会出现这个问题

### Screenshots or additional context

登录后，再次刷新页面会显示报错，无法加载内容，需要再次刷新才加载，加载后也是数据不全，无法加载所有内容，需要重复多次刷新再回出来

**Comment by gongjuecloak** [comment]
![image](https://github.com/usememos/memos/assets/100070999/d20fa151-4505-4b23-a77e-220187096fd0)
当在点击头像的个人资料，提示找不到用户，是否是token丢失？

**Comment by boojack** [comment]
Maybe fixed in the latest version, please try it again in demo site: https://demo.usememos.com
