### ISSUE TITLE
关于baseurl的问题

### ISSUE THREAD

**Issue by swimmingchar** [usememos/memos#2654]
### Is your feature request related to a problem?

请问，咱们是否有计划增加`baseurl`的设置，如果没有`baseurl`。
我必须在Nginx上单独设置一个端口用来进行memos的服务独享。
我尝试过增加一个自定义的`baseurl`，但是发现，很多接口都没有办法添加`baseurl`的前缀导致无法正常访问。

### Describe the solution you'd like

现在：
https://a.b.com:12345/inbox
更改后：
https://a.b.com:12345/${baseurl}/inbox

### Additional context

这样做的话，可以减少没有必要的端口转发，方便管理

**Comment by Qeynos** [comment]
已经有类似的issue，作者认为memos.b.com是正确的用法，其实我也希望有baseurl，以对运营商隐藏服务，但我能力不行，提供不了pr

**Comment by swimmingchar** [comment]
> 已经有类似的issue，作者认为memos.b.com是正确的用法，其实我也希望有baseurl，以对运营商隐藏服务，但我能力不行，提供不了pr

我看了，他的方案感觉很复杂，并不是最优解，而且换关了。。。

**Comment by 2014miss** [comment]
附议，希望增加baseurl

**Comment by boojack** [comment]
Refer to: https://github.com/usememos/memos/issues/2129
