### ISSUE TITLE
Sitemap displays registered users

### ISSUE THREAD

**Issue by aroi69** [usememos/memos#2656]
### Describe the bug

When opening the sitemap the usernames of the site are exposed which may not be desireable

### Steps to reproduce

1. Go to https://demo.usememos.com/sitemap.xml
2. Look at the file

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/104720021/bce367b2-56b6-4b1c-abb7-9c086f19f6a5)

**Comment by boojack** [comment]
Updated in https://github.com/usememos/memos/commit/fcfb76a103a0b4a0bb66bd764af66ed07d2caa22

**Comment by aroi69** [comment]
Thanks
