### ISSUE TITLE
failed to create db driver, using postgres

### ISSUE THREAD

**Issue by mailliwal** [usememos/memos#2660]
### Describe the bug

I would like to use **postgres** as database. But memos is failure to start.

`2023-12-24T13:27:18.653+0800	ERROR	cmd/memos.go:51	failed to create db driver	{"error": "unknown db driver", "errorVerbose": "unknown db driver\ngithub.com/usememos/memos/store/db.NewDBDriver\n\t/backend-build/store/db/db.go:23\ngithub.com/usememos/memos/cmd.glob..func2\n\t/backend-build/cmd/memos.go:48\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\ngithub.com/usememos/memos/cmd.Execute\n\t/backend-build/cmd/memos.go:100\nmain.main\n\t/backend-build/main.go:11\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650"}`

### Steps to reproduce

- MEMOS_DRIVER: postgres
- MEMOS_DSN: 'postgresql://memosuser:memospass@memos-db:5432/memos?sslmode=disable'

### The version of Memos you're using

Latest

**Comment by boojack** [comment]
`latest` is the tag name of docker image not the version of memos. You should check out the version in about dialog.

**Comment by mailliwal** [comment]
> `latest` is the tag name of docker image not the version of memos. You should check out the version in about dialog.

I have tried **0.18.1**

Below is the error.

`2023-12-25T12:49:44.385+0800   ERROR   memos/main.go:57        failed to migrate db {"error": "failed to exec SQL -- drop all tables first (PostgreSQL style)\nDROP TABLE IF EXISTS migration_history CASCADE;\nDROP TABLE IF EXISTS system_setting CASCADE;\nDROP TABLE IF EXISTS \"user\" CASCADE;\nDROP TABLE IF EXISTS user_setting CASCADE;\nDROP TABLE IF EXISTS memo CASCADE;\nDROP TABLE IF EXISTS memo_organizer CASCADE;\nDROP TABLE IF EXISTS memo_relation CASCADE;\nDROP TABLE IF EXISTS resource CASCADE;\nDROP TABLE IF EXISTS tag CASCADE;\nDROP TABLE IF EXISTS activity CASCADE;\nDROP TABLE IF EXISTS storage CASCADE;\nDROP TABLE IF EXISTS idp CASCADE;\nDROP TABLE IF EXISTS inbox CASCADE;\nDROP TABLE IF EXISTS webhook CASCADE;\n\n-- migration_history\nCREATE TABLE migration_history (\n  version TEXT NOT NULL PRIMARY KEY,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())\n);\n\n-- system_setting\nCREATE TABLE system_setting (\n  name TEXT NOT NULL PRIMARY KEY,\n  value TEXT NOT NULL,\n  description TEXT NOT NULL\n);\n\n-- user\nCREATE TABLE \"user\" (\n  id SERIAL PRIMARY KEY,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  row_status TEXT NOT NULL DEFAULT 'NORMAL',\n  username TEXT NOT NULL UNIQUE,\n  role TEXT NOT NULL DEFAULT 'USER',\n  email TEXT NOT NULL DEFAULT '',\n  nickname TEXT NOT NULL DEFAULT '',\n  password_hash TEXT NOT NULL,\n  avatar_url TEXT NOT NULL\n);\n\n-- user_setting\nCREATE TABLE user_setting (\n  user_id INTEGER NOT NULL,\n  key TEXT NOT NULL,\n  value TEXT NOT NULL,\n  UNIQUE(user_id, key)\n);\n\n-- memo\nCREATE TABLE memo (\n  id SERIAL PRIMARY KEY,\n  creator_id INTEGER NOT NULL,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  row_status TEXT NOT NULL DEFAULT 'NORMAL',\n  content TEXT NOT NULL,\n  visibility TEXT NOT NULL DEFAULT 'PRIVATE'\n);\n\n-- memo_organizer\nCREATE TABLE memo_organizer (\n  memo_id INTEGER NOT NULL,\n  user_id INTEGER NOT NULL,\n  pinned INTEGER NOT NULL DEFAULT 0,\n  UNIQUE(memo_id, user_id)\n);\n\n-- memo_relation\nCREATE TABLE memo_relation (\n  memo_id INTEGER NOT NULL,\n  related_memo_id INTEGER NOT NULL,\n  type TEXT NOT NULL,\n  UNIQUE(memo_id, related_memo_id, type)\n);\n\n-- resource\nCREATE TABLE resource (\n  id SERIAL PRIMARY KEY,\n  creator_id INTEGER NOT NULL,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  filename TEXT NOT NULL,\n  blob BYTEA,\n  external_link TEXT NOT NULL,\n  type TEXT NOT NULL DEFAULT '',\n  size INTEGER NOT NULL DEFAULT 0,\n  internal_path TEXT NOT NULL DEFAULT '',\n  memo_id INTEGER DEFAULT NULL\n);\n\n-- tag\nCREATE TABLE tag (\n  name TEXT NOT NULL,\n  creator_id INTEGER NOT NULL,\n  UNIQUE(name, creator_id)\n);\n\n-- activity\nCREATE TABLE activity (\n  id SERIAL PRIMARY KEY,\n  creator_id INTEGER NOT NULL,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  type TEXT NOT NULL DEFAULT '',\n  level TEXT NOT NULL DEFAULT 'INFO',\n  payload JSONB NOT NULL DEFAULT '{}'\n);\n\n-- storage\nCREATE TABLE storage (\n  id SERIAL PRIMARY KEY,\n  name TEXT NOT NULL,\n  type TEXT NOT NULL,\n  config JSONB NOT NULL DEFAULT '{}'\n);\n\n-- idp\nCREATE TABLE idp (\n  id SERIAL PRIMARY KEY,\n  name TEXT NOT NULL,\n  type TEXT NOT NULL,\n  identifier_filter TEXT NOT NULL DEFAULT '',\n  config JSONB NOT NULL DEFAULT '{}'\n);\n\n-- inbox\nCREATE TABLE inbox (\n  id SERIAL PRIMARY KEY,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  sender_id INTEGER NOT NULL,\n  receiver_id INTEGER NOT NULL,\n  status TEXT NOT NULL,\n  message TEXT NOT NULL\n);\n\n-- webhook\nCREATE TABLE webhook (\n  id SERIAL PRIMARY KEY,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  row_status TEXT NOT NULL DEFAULT 'NORMAL',\n  creator_id INTEGER NOT NULL,\n  name TEXT NOT NULL,\n  url TEXT NOT NULL\n);\n: parse \"postgresql://memos:TvNvFF3Zs4N3oUKLEhtf/memos\": invalid port \":TvNvFF3Zs4N3oUKLEhtf\" after host", "errorVerbose": "failed to exec SQL -- drop all tables first (PostgreSQL style)\nDROP TABLE IF EXISTS migration_history CASCADE;\nDROP TABLE IF EXISTS system_setting CASCADE;\nDROP TABLE IF EXISTS \"user\" CASCADE;\nDROP TABLE IF EXISTS user_setting CASCADE;\nDROP TABLE IF EXISTS memo CASCADE;\nDROP TABLE IF EXISTS memo_organizer CASCADE;\nDROP TABLE IF EXISTS memo_relation CASCADE;\nDROP TABLE IF EXISTS resource CASCADE;\nDROP TABLE IF EXISTS tag CASCADE;\nDROP TABLE IF EXISTS activity CASCADE;\nDROP TABLE IF EXISTS storage CASCADE;\nDROP TABLE IF EXISTS idp CASCADE;\nDROP TABLE IF EXISTS inbox CASCADE;\nDROP TABLE IF EXISTS webhook CASCADE;\n\n-- migration_history\nCREATE TABLE migration_history (\n  version TEXT NOT NULL PRIMARY KEY,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())\n);\n\n-- system_setting\nCREATE TABLE system_setting (\n  name TEXT NOT NULL PRIMARY KEY,\n  value TEXT NOT NULL,\n  description TEXT NOT NULL\n);\n\n-- user\nCREATE TABLE \"user\" (\n  id SERIAL PRIMARY KEY,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  row_status TEXT NOT NULL DEFAULT 'NORMAL',\n  username TEXT NOT NULL UNIQUE,\n  role TEXT NOT NULL DEFAULT 'USER',\n  email TEXT NOT NULL DEFAULT '',\n  nickname TEXT NOT NULL DEFAULT '',\n  password_hash TEXT NOT NULL,\n  avatar_url TEXT NOT NULL\n);\n\n-- user_setting\nCREATE TABLE user_setting (\n  user_id INTEGER NOT NULL,\n  key TEXT NOT NULL,\n  value TEXT NOT NULL,\n  UNIQUE(user_id, key)\n);\n\n-- memo\nCREATE TABLE memo (\n  id SERIAL PRIMARY KEY,\n  creator_id INTEGER NOT NULL,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  row_status TEXT NOT NULL DEFAULT 'NORMAL',\n  content TEXT NOT NULL,\n  visibility TEXT NOT NULL DEFAULT 'PRIVATE'\n);\n\n-- memo_organizer\nCREATE TABLE memo_organizer (\n  memo_id INTEGER NOT NULL,\n  user_id INTEGER NOT NULL,\n  pinned INTEGER NOT NULL DEFAULT 0,\n  UNIQUE(memo_id, user_id)\n);\n\n-- memo_relation\nCREATE TABLE memo_relation (\n  memo_id INTEGER NOT NULL,\n  related_memo_id INTEGER NOT NULL,\n  type TEXT NOT NULL,\n  UNIQUE(memo_id, related_memo_id, type)\n);\n\n-- resource\nCREATE TABLE resource (\n  id SERIAL PRIMARY KEY,\n  creator_id INTEGER NOT NULL,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  filename TEXT NOT NULL,\n  blob BYTEA,\n  external_link TEXT NOT NULL,\n  type TEXT NOT NULL DEFAULT '',\n  size INTEGER NOT NULL DEFAULT 0,\n  internal_path TEXT NOT NULL DEFAULT '',\n  memo_id INTEGER DEFAULT NULL\n);\n\n-- tag\nCREATE TABLE tag (\n  name TEXT NOT NULL,\n  creator_id INTEGER NOT NULL,\n  UNIQUE(name, creator_id)\n);\n\n-- activity\nCREATE TABLE activity (\n  id SERIAL PRIMARY KEY,\n  creator_id INTEGER NOT NULL,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  type TEXT NOT NULL DEFAULT '',\n  level TEXT NOT NULL DEFAULT 'INFO',\n  payload JSONB NOT NULL DEFAULT '{}'\n);\n\n-- storage\nCREATE TABLE storage (\n  id SERIAL PRIMARY KEY,\n  name TEXT NOT NULL,\n  type TEXT NOT NULL,\n  config JSONB NOT NULL DEFAULT '{}'\n);\n\n-- idp\nCREATE TABLE idp (\n  id SERIAL PRIMARY KEY,\n  name TEXT NOT NULL,\n  type TEXT NOT NULL,\n  identifier_filter TEXT NOT NULL DEFAULT '',\n  config JSONB NOT NULL DEFAULT '{}'\n);\n\n-- inbox\nCREATE TABLE inbox (\n  id SERIAL PRIMARY KEY,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  sender_id INTEGER NOT NULL,\n  receiver_id INTEGER NOT NULL,\n  status TEXT NOT NULL,\n  message TEXT NOT NULL\n);\n\n-- webhook\nCREATE TABLE webhook (\n  id SERIAL PRIMARY KEY,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  row_status TEXT NOT NULL DEFAULT 'NORMAL',\n  creator_id INTEGER NOT NULL,\n  name TEXT NOT NULL,\n  url TEXT NOT NULL\n);\n: parse \"postgresql://memos:TvNvFF3Zs4N3oUKLEhtf/memos\": invalid port \":TvNvFF3Zs4N3oUKLEhtf\" after host\ngithub.com/usememos/memos/store/db/postgres.(*DB).prodMigrate\n\t/backend-build/store/db/postgres/migrator.go:90\ngithub.com/usememos/memos/store/db/postgres.(*DB).Migrate\n\t/backend-build/store/db/postgres/migrator.go:30\nmain.glob..func1\n\t/backend-build/bin/memos/main.go:55\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\nmain.Execute\n\t/backend-build/bin/memos/main.go:103\nmain.main\n\t/backend-build/bin/memos/main.go:191\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650"}`

**Comment by mailliwal** [comment]
Refer to other user, it's been fixed by added "?sslmode=disable" to end of "MEMOS_DSN"

Thanks

**Comment by boojack** [comment]
> invalid port \":TvNvFF3Zs4N3oUKLEhtf\" after host

It looks like your DSN is not valid.

**Comment by jhademcconnell** [comment]
> Refer to other user, it's been fixed by added "?sslmode=disable" to end of "MEMOS_DSN"
> 
> Thanks

@mailliwal could you please close this issue now it’s resolved? Thank you!
