### ISSUE TITLE
Memos web pages support the use of custom servers and accestoken

### ISSUE THREAD

**Issue by quanru** [usememos/memos#2661]
### Is your feature request related to a problem? Please describe.

Solve the problem of slow cdn loading speed of front-end pages deployed by users(example replit)

### Describe the solution you'd like

Just like the multiple login methods provided by moe
![image](https://github.com/usememos/memos/assets/11739753/8bf7f0a2-27bd-4eb4-84e3-3265e7a92699)

**Comment by boojack** [comment]
Not in our roadmap. It should be a third party project.
