### ISSUE TITLE
The same memo may be saved twice

### ISSUE THREAD

**Issue by shinyes** [usememos/memos#2662]
### Describe the bug

The same memo may be saved twice.

### Steps to reproduce

When the network latency is high, click on the save button, the button is grayed out and you need to wait a few seconds for the submission to complete, then refresh the page and you'll see that there are two memes with the same content and they have different ID.

### The version of Memos you're using

0.18.1

**Comment by shinyes** [comment]
![image](https://github.com/usememos/memos/assets/44279849/29b6a484-3de7-4831-9645-c1b63e6758d5)

**Comment by boojack** [comment]
Maybe it's fixed in the latest version.
