### ISSUE TITLE
无法固化语言设置

### ISSUE THREAD

**Issue by Kings-Github** [usememos/memos#2663]
### Describe the bug

无法固化语言设置，我设置了简体中文，新打开一个无痕窗口访问，又会自动跳回英语页面...
希望可以修复此问题。
我使用的docker镜像。

### Steps to reproduce

1.首先我在网页中设置了语言为简体中文
2.然后保存并注销登录。
3.重新打开一个无痕浏览器窗口，此时发现页面又跳转回英文页面了。

### The version of Memos you're using

v0.18.1

**Comment by boojack** [comment]
Duplicated with https://github.com/usememos/memos/issues/2659
