### ISSUE TITLE
为何使用telegram bot发的图片都不显示，图片都在资源库unused  resources里面

### ISSUE THREAD

**Issue by wcsay** [usememos/memos#2664]
### Describe the bug

已经配置好了token和userid，在bot中转发或者自己写的文字是没有问题的，可是图片全都显示不了，看资源库里面，是在unused  resources里面，但是bot里面返回的是有图片的，并且也提示已经发送成功。这是为什么呢？
![2023-12-25_230619](https://github.com/usememos/memos/assets/69422716/dc128dfd-ffe3-47e2-86ab-fd2cd9f9dbe4)
图片中，h红框内部的是我用bot发送的，没办法显示在信息流中，绿色框中的是我手动在网页版上传的，是可以正常显示的。

### Steps to reproduce

请帮我解答，谢谢！

### The version of Memos you're using

v0.18.1

**Comment by athurg** [comment]
This bug has been fixed in #2650
