### ISSUE TITLE
ReactJS Stack Trace Thrown on Sign In for Demo Site

### ISSUE THREAD

**Issue by jhademcconnell** [usememos/memos#2667]
### Describe the bug

When signing in a Memos instance, the following stack trace is thrown:

`
Unexpected Application Error!
Minified React error #426; visit https://reactjs.org/docs/error-decoder.html?invariant=426 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Nk@https://demo.usememos.com/assets/index-rJNCtkUo.js:77:42568
Jk@https://demo.usememos.com/assets/index-rJNCtkUo.js:77:43559
Ok@https://demo.usememos.com/assets/index-rJNCtkUo.js:77:39548
Fk@https://demo.usememos.com/assets/index-rJNCtkUo.js:77:40442
jg@https://demo.usememos.com/assets/index-rJNCtkUo.js:75:3534
@https://demo.usememos.com/assets/index-rJNCtkUo.js:77:37698
`

### Steps to reproduce

1. Navigate to https://demo.usememos.com/explore
2. Click sign in
3. Observe stack trace thrown

If you navigate back a page and sign in again, the error isn’t thrown. If you leave that page though (exit webpage or the app) and go back to the explore page and try signing in, you’ll get the same stack trace.

https://github.com/usememos/memos/assets/13276370/769fe8d7-ef9d-4f25-b9ff-98bd605ecda6

### The version of Memos you're using

v0.18.1

### Screenshots or additional context

I’m able to recreate this issue in my personal Memos instance (v0.18.1)

**Comment by boojack** [comment]
Already redeployed, please feel free to try it again.

**Comment by jhademcconnell** [comment]
Not running into the issue now on the demo site with the latest redeploy/build, closing
