### ISSUE TITLE
苹果手机 ios17 以下 浏览器打开画面都会报错

### ISSUE THREAD

**Issue by hanfenglong315** [usememos/memos#2669]
### Describe the bug

苹果手机 ios17 以下 浏览器打开画面都会报错 目前 ios16.x ios 14.x 确认 报错

### Steps to reproduce

苹果手机 ios17 以下 浏览器打开画面都会报错 目前 ios16.x ios 14.x 确认 报错  无论苹果浏览器 还是chrome  还是百度浏览器
https://www.hanfenglong.online
### The version of Memos you're using

neosmemo/memos:latest

### Screenshots or additional context

![微信图片_20231226114746](https://github.com/usememos/memos/assets/67135926/c6b1921d-ce6d-4ebe-ab1d-823fb979c2cc)
![微信图片_20231226114814](https://github.com/usememos/memos/assets/67135926/ece33e18-2aca-4d6e-aa85-ca034d814725)
![微信图片_20231226114818](https://github.com/usememos/memos/assets/67135926/da692828-1377-475e-89aa-1b02116732cb)
![微信图片_20231226114822](https://github.com/usememos/memos/assets/67135926/147276ef-8f65-4ea7-a872-6911775b48c7)
![微信图片_20231226114825](https://github.com/usememos/memos/assets/67135926/962a5951-cb90-4319-9fae-bcee08b0de0d)

**Comment by hanfenglong315** [comment]
yes

**Comment by jhademcconnell** [comment]
This issue is mentioned here and shows to wait for the next release to check if fixed: https://github.com/usememos/memos/issues/2639
