### ISSUE TITLE
Access Tokens 支持二维码展示

### ISSUE THREAD

**Issue by qianhd** [usememos/memos#2671]
### Is your feature request related to a problem? Please describe.

第三方手机MoeMemos支持用户名密码和Access Tokens登录，但Access Tokens过于长，人工无法正确输入。
在第三方App上输入用户名和密码，总让人有点不放心。

### Describe the solution you'd like

生成的Access Tokens支持二维码展示，方便手机跟web端更好的联动。

注：当前MoeMemos还不支持扫码

**Comment by boojack** [comment]
You can copy the access token from the website in mobile. Then paste it into your app.
