### ISSUE TITLE
Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by earthjasonlin** [usememos/memos#2675]
### Describe the bug

This appears when I use my phone to visit the site, which is behind a nginx reverse proxy. However, everything works fine when I visit it on computers. I’ve tried Chrome, Safari, Bing on my iPhone 8, I’ve tried turning on and off my network, vpn, clearing caches. Doesn’t work

### Steps to reproduce

1. iPhone 8 iOS 15.5(not necessary I guess)
2. visit the site

### The version of Memos you're using

latest(it automatically updates itself every day)

### Screenshots or additional context

``` 
Unexpected Application Error!
Invalid regular expression: invalid group specifier name
RegExp@[native code]
module code@https://.cn/assets/MemoResourceListView-fa84cf3d.js:270:1182438
evaluate@[native code]
moduleEvaluation@[native code]
moduleEvaluation@[native code]
moduleEvaluation@[native code]
@[native code]
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code] 
```

**Comment by jhademcconnell** [comment]
This issue is mentioned here and shows to wait for the next release to check if fixed: https://github.com/usememos/memos/issues/2639
