### ISSUE TITLE
Backdates

### ISSUE THREAD

**Issue by tamimology** [usememos/memos#2678]
### Describe the solution you'd like

It would be so great if there was an option to specify a date (in the past) for a memo. As this could be a memory to share on that specific date. Personally, I came to know this app today, and had some private memos I want to post that happened in Nov and Oct and some others are even before.

This is also available on Facebook, and I use it a lot there, but Facebook is public, not private

Also, consider having like notifications on yearly events, i.e. I post something today, next year, 27/12/2024 I get a reminder for this event as it will be far down my wall 

### Type of feature

User Interface (UI)

**Comment by BISCUITZA** [comment]
I had the exact thought as well for backdating 😆, I've come to love memos recently and am adding key projects of the past to it and would love to tap on the memo date and change it to a specific one.

The extra highlighted memos annually is a great feature perhaps a #feature
![Screenshot_20231228_224904_Brave](https://github.com/usememos/memos/assets/25521914/a98f976f-a0f9-4c76-8e5a-1443213a57d9)

**Comment by harveyghq** [comment]
AFAIK, you can `alt` click a memo's date to change. See [ref](https://www.usememos.com/docs/faq) here.

**Comment by AlexKalopsia** [comment]
Oh wow, that does work, indeed. I wonder why this is such a hidden feature!

**Comment by tamimology** [comment]
> AFAIK, you can `alt` click a memo's date to change. See [ref](https://www.usememos.com/docs/faq) here.

I am not able to click on the date :(
