### ISSUE TITLE
Dark Mode is always white for new users that read your page

### ISSUE THREAD

**Issue by mariushosting** [usememos/memos#2682]
### Describe the bug

https://github.com/usememos/memos/issues/850

Same issue as the one explained here.
Even If I set Dark Mode in the System Server/Appearance to Always Dark
new users that see your public notes will see the Server "light" instead of "dark"

### Steps to reproduce

Settings / System / Edit Customize Server / Server Appearance is set to Always dark
Even If I set Dark Mode in the System Server/Appearance to Always Dark
new users that see your public notes will see the Server "light" instead of "dark"

### The version of Memos you're using

v0.18.1

**Comment by lincolnthalles** [comment]
Related to #2659
