### ISSUE TITLE
Memo comments are listed in memo list

### ISSUE THREAD

**Issue by ingxhe** [usememos/memos#2686]
### Describe the bug

Hey,

so either this is a undocumented new feature, or it accidentally changes toward 0.18.0:

In the "home" tab memo comments are now listed besides the actual memos
![image](https://github.com/usememos/memos/assets/30750321/71d9934b-3f17-4852-9c84-75995f60c285)
I do understand, that it might be useful to have it like this, but it removes any kind of structure one had with the comments.

I'm using the SQLite backend.

### Steps to reproduce

Have a lot of comments on memos
Update to 1.18.0
Open Home Tab

### The version of Memos you're using

v0.18.1

**Comment by jhademcconnell** [comment]
Similar issue here about this same bug: https://github.com/usememos/memos/issues/2595#issue-2034421230

I am also able to recreate this behavior in v0.18.1

**Comment by qiantao94** [comment]
Is this a bug rather than a feature?
After upgrading to v0.18.2, I noticed that comments no longer appear in the timeline.
I really love this feature. Can we have an option to choose whether to display it or not?
