### ISSUE TITLE
Disable public memos no longer appears to work

### ISSUE THREAD

**Issue by nalderto** [usememos/memos#2694]
### Describe the bug

There appears to have been a regression since this was [reported fixed in 0.17.1](https://github.com/usememos/memos/pull/2480).  This is noted in the [original bug ticket](https://github.com/usememos/memos/issues/2462), but @itschip said to make a new bug, which I didn't see. 

### Steps to reproduce

1. Create new Memos instance using Docker
2. Create an admin account
3. In Settings => System, tick the "Disable public memos" option so it is on (it is off by default)
4. In the Home tab, create a save note, ensuring the the visibility is enabled to "Public" (this shouldn't even be possible, the option should be grayed out)
5. Open a new private browser window and access the Memos instance (likely http://localhost:5230/explore)

Notice, that the public memo we created in step 4 is visible when it shouldn't be.

### The version of Memos you're using

0.18.1

**Comment by fengqi** [comment]
You can try creating a new user and it works, it seems it just doesn't work for admins

**Comment by boojack** [comment]
Disable pulic memos should be only works for normal users instead admins.
