### ISSUE TITLE
Escaping dollar sign (`$`) using a backslash (`\`) doesn't work properly

### ISSUE THREAD

**Issue by nalderto** [usememos/memos#2700]
### Describe the bug

Escaping dollar signs (`$`) does not treat them as normal characters.  For dollar signs, inline math mode is entered.

### Steps to reproduce

1. Type `\$55 \$65` in a memo
2. I would expect the memo to show `$55 $65`.  Instead it is treated as improperly formatted LaTeX expression.

### The version of Memos you're using

0.18.1

### Screenshots or additional context

![edit mode](https://github.com/usememos/memos/assets/25762130/6984dbcc-f056-498b-9eac-6dc4a49bba39)

![preview mode](https://github.com/usememos/memos/assets/25762130/140965de-8613-45d1-89d5-4a0c4c1c77fe)

**Comment by boojack** [comment]
Try it out on the latest demo site: https://demo.usememos.com, we've solved the problem by using a backend markdown parser.

**Comment by nalderto** [comment]
> Try it out on the latest demo site: https://demo.usememos.com, we've solved the problem by using a backend markdown parser.

Dollar signs do work properly on the new demo site.  However, it appears at the cost of math mode support.  We should also probably update the website to indicate what Markdown syntax is supported.

![image](https://github.com/usememos/memos/assets/25762130/22d227a9-38db-4c58-abd4-c5eeccf51690)

**Comment by boojack** [comment]
@nalderto Sure, associate to issue: https://github.com/usememos/dotcom/issues/31

**Comment by boojack** [comment]
@nalderto This can be implemented in our markdown parser. Just needs a bit more work.

https://github.com/usememos/memos/tree/main/plugin/gomark/parser

**Comment by boojack** [comment]
Hi @nalderto, I've just implemented this feature with https://github.com/usememos/memos/commit/d12a2b0c38ab056a22c969954b6c757dcb09c0ff. You're welcome to try it.

<img width="429" alt="image" src="https://github.com/usememos/memos/assets/24653555/0beaeb90-6641-415b-8776-03b51ffee844">
