### ISSUE TITLE
为什么手机访问会报错

### ISSUE THREAD

**Issue by imtour** [usememos/memos#2701]
### Describe the bug

PC可以访问，手机网页不行，手机APP可以

### Steps to reproduce

![F9613EE6-0CC3-4AB5-B4A1-8C04E1BFB0B8](https://github.com/usememos/memos/assets/62873767/0a27d786-fe88-4c36-ac9d-32ceb6d821db)

### The version of Memos you're using

V0.18.1

**Comment by jhademcconnell** [comment]
This is related to: https://github.com/usememos/memos/issues/2639#issuecomment-1874664251
