### ISSUE TITLE
The setting to edit a record by double-clicking has disappeared

### ISSUE THREAD

**Issue by antitiron** [usememos/memos#2702]
### Describe the bug

The setting to edit a record by double-clicking has disappeared. This functionality is enabled by default

### Steps to reproduce

1. Go to https://memos/setting
2. Go to "System"
3. There's no switch

### The version of Memos you're using

v0.18.1

**Comment by boojack** [comment]
This setting item has been deprecated. Please use the edit button instead.

**Comment by antitiron** [comment]
Thanks, I thought I was going crazy. Question: double click for editing is enabled by default, I wanted to remove it. Is there no way to do that now?

**Comment by boojack** [comment]
@antitiron Maybe not, the double click for editing is disabled by default.

**Comment by antitiron** [comment]
But enable (

![chrome-capture-2024-1-4](https://github.com/usememos/memos/assets/7191601/cb58745b-ec6b-433c-8343-c7d30b9991c3)

**Comment by boojack** [comment]
@antitiron Sorry, I don't really remember the behavior of the previous version, you can update the latest version like `0.18.2`.

**Comment by antitiron** [comment]
Interesting, updated yesterday via Portainer, thought it was the latest version.

Updating to 0.18.2 fixed everything, thanks for your help.
