### ISSUE TITLE
Checkboxes in memos no longer work

### ISSUE THREAD

**Issue by sfan5** [usememos/memos#2705]
### Describe the bug

I just upgraded and checking boxes inside memos no longer works in the web interface.

### Steps to reproduce

1. Create a new memo with `- [ ] example text`
2. View the memo and click on the check box
3. Nothing happens

### The version of Memos you're using

v0.18.2

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/454cd4e24f978e498031c57ff2dd399751d66633. You can pull the latest image again.
