### ISSUE TITLE
Two problems, there is a default access token and it cannot be deleted. Unable to change language and logo

### ISSUE THREAD

**Issue by dd404x** [usememos/memos#2706]
### Describe the bug

Two problems, there is a default access token and it cannot be deleted. Unable to change language and logo

### Steps to reproduce

![image](https://github.com/usememos/memos/assets/19923974/ed7c9267-a40c-4880-9929-29d3a4764d27)
![image](https://github.com/usememos/memos/assets/19923974/149685bf-635a-44da-8e3e-0397c7c424b5)
What is the role of the default access token and whether there are any security issues，Nothing happens when clicking the save button

### The version of Memos you're using

0.18.2

### Screenshots or additional context

Two problems, there is a default access token and it cannot be deleted. Unable to change language and logo
![image](https://github.com/usememos/memos/assets/19923974/ed7c9267-a40c-4880-9929-29d3a4764d27)
![image](https://github.com/usememos/memos/assets/19923974/149685bf-635a-44da-8e3e-0397c7c424b5)
What is the role of the default access token and whether there are any security issues，Nothing happens when clicking the save button

**Comment by dd404x** [comment]
The problem of Nothing happens when clicking the save button because some fields are empty has been solved

**Comment by boojack** [comment]
Please split your problems into different issue. It would be better for us to solve them. And this issue will be closed soon.
