### ISSUE TITLE
Can't not check the checkbox

### ISSUE THREAD

**Issue by 0n2ynu** [usememos/memos#2707]
### Describe the bug

I used to use checkbox to list my TODOs. But Now I can't click the checkbox anymore. I have to edit it and add x like this` - [x]`

### Steps to reproduce

1. Go to the main page
2. check a checkbox at any exist memos.

### The version of Memos you're using

0.18.2

**Comment by marcaurele** [comment]
In version `0.18.1` it's only possible to check the box in the *Home* view. Is it supposed to work when displaying a memo through its URL `m/<id>`?

**Comment by boojack** [comment]
Please update to the latest image.

**Comment by marcaurele** [comment]
@0n2ynu it's working in version `0.18.2` as expected in the main view for me.

**Comment by 0n2ynu** [comment]
Now it's ok.
