### ISSUE TITLE
Memos not Loading

### ISSUE THREAD

**Issue by bugmaschine** [usememos/memos#2708]
### Describe the bug

After the last update on the docker image, loading the page it just displays "Fetching data…" while doing absolutely nothing.

### Steps to reproduce

1. Go to page
2.  Wait for Memos to load

### The version of Memos you're using

v0.18.2

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/38097264/16963f10-112d-4b1e-8879-738c0d828b6f)

Loading memos dosent work, but the resources tab works.

**Comment by boojack** [comment]
Please provide error messages from the browser console, as well as logs of related network requests.

**Comment by jhademcconnell** [comment]
@boojack I'm able to recreate this in v0.18.1 latest commit. Home/Explore page displays fetching data and this error is thrown:

```
Home-nUummMMK.js:1 Uncaught (in promise) ClientError: /memos.api.v2.MemoService/ListMemos UNKNOWN: pq: column "parent_id" does not exist
    at makeCall (index-Qitdbhvp.js:300:6112)
    at async at (index-Qitdbhvp.js:300:11471)
    at async Object.listMemos (index-Qitdbhvp.js:300:11982)
    at async Object.fetchMemos (index-Qitdbhvp.js:323:72482)
    at async y (Home-nUummMMK.js:1:10592)
```

**Comment by bugmaschine** [comment]
> Please provide error messages from the browser console, as well as logs of related network requests.

Browser Console:
![image](https://github.com/usememos/memos/assets/38097264/69ba0622-4cbf-4789-af31-c61cc52ff7c8)

Network requests:
![image](https://github.com/usememos/memos/assets/38097264/34ee6016-9db8-41a4-9c5f-0980287975d8)

Containers Logs:
![image](https://github.com/usememos/memos/assets/38097264/5abacc1d-24f2-46fa-a931-a9eea9fa7b8c)

**Comment by bugmaschine** [comment]
I'm no expert but i guess the requests takes so long that it Times out.

Below screenshot is captured a few minutes after the first screenshot.
![image](https://github.com/usememos/memos/assets/38097264/6d4b0ff8-ab0f-47a4-a0b0-146688119514)

**Comment by bugmaschine** [comment]
After looking to the DB i found a few very long memos (about 48294 characters for each memo) and deleted them, after that the site loaded with no problems agains. I would maybe add an serverside check for the Memo length, or something like this. To prevent this from happening to other instances.

**Comment by boojack** [comment]
Thanks for your feedback. Updated with https://github.com/usememos/memos/commit/ddcf1d669d41dbb19b94955d19c9ed6ca44c1b9f
