### ISSUE TITLE
Memos display in the wrong timeline order on v0.18.2

### ISSUE THREAD

**Issue by erbanku** [usememos/memos#2712]
### Describe the bug

After upgrading to the latest version, the memos are displayed in the wrong timeline order.
As you can see in the image below, the memos after 10/6/2023 not showing (not archived), but I can find them via searching. Another possible way to display in the correct order is to scroll to the bottom (manually load all memos); in this case, the order became normal.

# Screenshots
![IMG_7016](https://github.com/usememos/memos/assets/79493862/2c8c43d4-2383-4114-842a-081fd14640bd)
![IMG_7015](https://github.com/usememos/memos/assets/79493862/ec0b1fc7-1b64-46e2-bc25-eef146ce832a)
 

### Steps to reproduce

I don't know how to reproduce it in this case (maybe 400+ memos can trigger it?)

### The version of Memos you're using

v18.0.2

**Comment by erbanku** [comment]
BTW, give a design suggestion.
It could be useful for users to have buttons like "Today", "This Week", "This Month", "This Year", and "Custom Time Range" added to the Timeline page.
![image](https://github.com/usememos/memos/assets/79493862/635780a5-40ef-424f-b1f4-d8e8e7391241)

**Comment by erbanku** [comment]
@boojack Any response?

**Comment by erbanku** [comment]
@boojack 
## Request parameters
![image](https://github.com/usememos/memos/assets/79493862/5b339ebf-03d3-42c0-a51c-dafde2ea9d5c)
## `display by update time`
![image](https://github.com/usememos/memos/assets/79493862/35819514-7e05-488d-84da-1684298f72c4)

**Comment by erbanku** [comment]
![image](https://github.com/usememos/memos/assets/79493862/3f7d1c20-68b8-4af1-9c88-4d1fe04e17f0)

**Comment by i-iooi-i** [comment]
遇到了相同的问题，时间线错误，点击下方的载入更多，时间线才会变正确。
chrome 和 ios  都是同样的情况。

**Comment by xhemj** [comment]
从网页加载时的控制台日志可以看出一些信息
![IMG_20240111_172955](https://github.com/usememos/memos/assets/55266496/90035124-d451-49e9-8274-98d57930319e)

**Comment by peveleigh** [comment]
I'm having the same issue. Clicking "Load More" at the bottom of the page rearranges the memos in the correct order.

**Comment by erbanku** [comment]
> I'm having the same issue. Clicking "Load More" at the bottom of the page rearranges the memos in the correct order. I tried rolling back to 0.18.1 until this is fixed but it stopped working altogether. I'm guessing there's a breaking change between 0.18.1 and 0.18.2.

Reverting to version v0.18.0 resolved the issue. This is a temporary solution, as the maintainer appears to be too busy and may not address the bug in the near time soon.

**Comment by peveleigh** [comment]
> Reverting to version v0.18.0 resolved the issue. This is a temporary solution, as the maintainer appears to be too busy and may not address the bug in the near time soon.

I tried that and I get nothing but errors when I load Memos.

**Comment by erbanku** [comment]
My instance was fixed after downgrading from version 0.18.2 to 0.18.1, and then further to 0.18.0.

**Comment by peveleigh** [comment]
My bad, I thought you said 0.18.1, not 0.18.0. I'll try that, thank you.

**Comment by i-iooi-i** [comment]
今天在Docker更新到新版本，问题解决了，谢谢。
