### ISSUE TITLE
Nested bullet points no longer work

### ISSUE THREAD

**Issue by sfan5** [usememos/memos#2715]
### Describe the bug

In older versions of memos you could nest bullet points by adding spaces before the `*`. This no longer works.

### Steps to reproduce

1. Create a memo
<pre>
* 1
  * 1.1
* 2
* 3
  * 3.3
</pre>
2. Observe result

### The version of Memos you're using

? (docker pull from 5 minutes ago)

### Screenshots or additional context

actual:
![grafik](https://github.com/usememos/memos/assets/1042418/e88fd656-b63d-4e3e-90f5-5201255b465b)
in older version:
![grafik](https://github.com/usememos/memos/assets/1042418/8140c41d-600f-47a2-a5bf-c354991bf48f)

**Comment by sfan5** [comment]
I have to say memos is useful software but I will be downgrading to an older version. Right now it's too broken for basic usage :frowning_face:

**Comment by boojack** [comment]
@sfan5 Thanks for the feedback. The latest official version of memos is `0.18.1`, and `0.18.2` has not been officially released yet.

**Comment by sfan5** [comment]
I see. I have been using the `latest` docker tag [from here](https://hub.docker.com/r/neosmemo/memos/tags). Isn't that the stable version?

**Comment by boojack** [comment]
The released stable versions can be viewed on https://github.com/usememos/memos/releases

**Comment by lephtHanded** [comment]
automatic check boxes don't work either.
I miss the full screen memo editor too...

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/98762be1e53cefa61e6099abbaf43a7994340cd0
