### ISSUE TITLE
Button for code block is missing

### ISSUE THREAD

**Issue by Raptor-TK** [usememos/memos#2717]
### Describe the bug

The button for adding a code block with ``` is no longer available.
This makes adding code more difficult.

The code button was available in older versions of memos but after an update to the latest version, it has vanished.

See the screenshot in 3rd icon for the "code block" button that is now missing.
![image](https://github.com/usememos/memos/assets/53501197/b35c470f-52f8-4a8c-bd4c-ea3ec3253b9e)

### Steps to reproduce

When creating a new memo, the button for adding a code block is missing in the latest version.

### The version of Memos you're using

Where is the version number shown? Using latest docker image as of posting issue.
Trying various docker images, the problem started occurring on 0.18.2 onwards. The last working version for the buttons is 0.18.1.

**Comment by boojack** [comment]
This is a built-in feature and does not need to be shown. We'll add a flag to indicate support for markdown syntax.
