### ISSUE TITLE
Button for checkbox is missing

### ISSUE THREAD

**Issue by Raptor-TK** [usememos/memos#2718]
### Describe the bug

The button for adding a checkbox is no longer available.
Also for a line that already has a checkbox "- [ ]" pressing enter to add a new checkbox no longer works anymore

The checkbox button was available in older versions of memos but after an update to the latest version, it has vanished.

### Steps to reproduce

In a new note, look at the buttons list and the checkbox button is now gone.

### The version of Memos you're using

Problem occurs on latest docker release. Issue appeared in 0.18.2 onwards.

**Comment by boojack** [comment]
Reference to: https://github.com/usememos/memos/issues/2717
