### ISSUE TITLE
” -“ 的markdown 语法解析问题

### ISSUE THREAD

**Issue by anno189** [usememos/memos#272]
版本：0.4.5-prod
问题：在行中任何位置输入 “空格减号”（ -） 会被 markdown 解释。
输入： 
<img width="646" alt="截屏2022-10-09 10 17 28" src="https://user-images.githubusercontent.com/3339262/194734527-68d14802-f350-4e44-9eab-2bfc3b7d699a.png">
显示：
<img width="644" alt="截屏2022-10-09 10 17 37" src="https://user-images.githubusercontent.com/3339262/194734528-66f65a69-25dc-4f82-900a-8b325373fbc6.png">

**Comment by boojack** [comment]
已在 0.5.0 中修复
