### ISSUE TITLE
Short link to note identifier is gone from top line header on each memo

### ISSUE THREAD

**Issue by marcaurele** [usememos/memos#2720]
### Describe the bug

The link to the memo identifier is gone from the header line of each memo, which was useful in my case to have a link to my daily note to track progress/changes.

### Steps to reproduce

1. Use the dark release `0.18.2` and on the home view the links `#<id>` are gone from the top line of each memo.
2. Use a previous version, the link is present.

### The version of Memos you're using

0.18.2

### 0.18.2

![image](https://github.com/usememos/memos/assets/1081566/591a2215-d180-473c-8651-c045860c8e58)

### 0.18.1

![image](https://github.com/usememos/memos/assets/1081566/aaf5e79b-f116-441f-a1ee-6ffd6077bf95)

**Comment by boojack** [comment]
Moved into the dropdown

<img width="762" alt="image" src="https://github.com/usememos/memos/assets/24653555/e4fac6a9-b314-4b78-a276-fbc6723c1722">
