### ISSUE TITLE
Click on Memo/Note should go into edit mode immediately

### ISSUE THREAD

**Issue by q2apro** [usememos/memos#2722]
### Describe the solution you'd like

I used Google Keeps for years and it would be nice if Memos becomes the replacement. I value **speed** in note taking apps.

The first thing I noticed (slowing down the work) is that with Memos to edit a note, you have to mouse over the three dots and then choose "Edit". 

Google Keep is extremely fast because the user just clicks ONE time on a note and it goes directly into editing mode.

Please add this (important and simple) feature to Memos. 

Thank you 🙏

### Type of feature

User Experience (UX)

### Alternative 

Put the edit icon directly on the top of the bar - not inside a dropdown.

**Comment by jneeee** [comment]
Hi, Try double click
I prefer double click rather than once

**Comment by q2apro** [comment]
### HACK for current Memo version

Add custom style: `.memo-wrapper>.memo-top-wrapper>.btns-container>.more-action-btns-wrapper { display: block; }` so the dropdown always shows up. But this is a temporary hack, not a solution!

With:

```
.memo-wrapper>.memo-top-wrapper>.btns-container>.more-action-btns-wrapper { display: block; opacity: 0.5; }
.more-action-btns-container>.btn:nth-child(3), .more-action-btns-container>.btn:nth-child(4) { display: none !important; }
```

You get:

![image](https://github.com/usememos/memos/assets/6764548/32e6bce2-0b54-4732-a4cc-d7de1b70f35b)

With:

```
.memo-wrapper>.memo-top-wrapper>.btns-container>.more-action-btns-wrapper { display: block; opacity: 0.5; min-width: 50px; }
.more-action-btns-container>.btn { font-size: 0 !important; }
```

You can achieve this:

![image](https://github.com/usememos/memos/assets/6764548/c65ad096-4cb5-4766-ade7-575021d184e0)

**Comment by q2apro** [comment]
> Hi, Try double click I prefer double click rather than once

Different users, different habits.

This should be optional.

**Comment by q2apro** [comment]
![image](https://github.com/usememos/memos/assets/6764548/4e87b240-480d-47b2-a306-6b93439d66ff)

"Capture" is written first here, not "View".

IMHO, this is a must.

At least put a second edit icon on the top bar of each note, so there is only one click necessary (without dropdown).

**Comment by q2apro** [comment]
With adding your own Javascript you can achieve this by:

```
var script = document.createElement('script');

script.src = 'https://yourcdn-or-server.com/js/jquery/3.6.4/jquery.min.js';

script.onload = function() 
{
	$(document).ready(function() 
	{
		$('body').on('click', '.memo-wrapper .text-base', function() 
		{
			$(this).closest('.memo-wrapper').find('.more-action-btns-container .btn').eq(2).click();

			setTimeout( function() { $('.dialog-container textarea.text-base').focus(); }, 200)
		});
	});
};

document.head.appendChild(script);
```

**Comment by motoridersd** [comment]
I use Obsidian and was looking at this as a replacement, but not being able to quickly edit a note by clicking on it is a big issue for me. I vote for having this as an option.
