### ISSUE TITLE
Add hint/info/tooltip what the button "Vacuum" does

### ISSUE THREAD

**Issue by q2apro** [usememos/memos#2724]
### Describe the solution you'd like

Under "/setting" on the top right, there is a button labeled "Vacuum". 

Add hint/info/tooltip what the button "Vacuum" does. 

Most users have never seen a "vacuum" option, so have no idea what it does.

I do not know what it does.

### Type of feature

User Interface (UI)

**Comment by MehadND** [comment]
I believe I can work on this issue but not sure exactly what the "vacuum" option does. However, if anyone can explain then I can resolve this issue. From some google searches I think this button deletes unused data/files from database. Again not entirely sure so please guide me.

Thanks,
Mehad

**Comment by MehadND** [comment]
Sorry for being a bit stupid but I am getting this error and not sure exactly what to do?

![image](https://github.com/usememos/memos/assets/34424878/2877bbc7-79f0-4c43-abb7-21600a228fd9)


This is my first time with Vite so maybe I'm doing something wrong there.

The steps to produce this error:
- Clone Repo
- open the project in vs code and then navigate to `web` directory and run `npm install`
- then run `npm run dev`

**Comment by MehadND** [comment]
@boojack, when I run the memos in dev I cannot go past the auth for some reason, even with the default login credentials.

**Comment by boojack** [comment]
> But I would like to do it outside docker.

@MehadND You can build a binary with source code for your OS. Or follow https://github.com/lincolnthalles/memos-builds

**Comment by MehadND** [comment]
Ok will look into that but if you can tell me how to fix the vite issue with authentication. Because whenever I change code and want to see my change I can't because I can't go past the sign in/up page

**Comment by boojack** [comment]
@MehadND This issue is not appropriate for your problems. Let's take a deeper look at them on discord: https://discord.com/invite/tfPJa4UmAv. You can DM to me.

**Comment by MehadND** [comment]
#2778
