### ISSUE TITLE
Display number of memos/notes next to each tag

### ISSUE THREAD

**Issue by q2apro** [usememos/memos#2727]
### Describe the solution you'd like

It would be great to know how many notes have a particular tag.

![image](https://github.com/usememos/memos/assets/6764548/42482a68-1c34-4fe9-9525-4f06b8e54b19)

Should be:

```
# cooking (5)
# kids (3)
# kids-stories (20)
# recent (1)
```

It would help a lot.

### Type of feature

User Interface (UI)

**Comment by boojack** [comment]
The current architecture does not support this.
