### ISSUE TITLE
Show latestet pinned note on top of pinned notes

### ISSUE THREAD

**Issue by q2apro** [usememos/memos#2730]
### Describe the solution you'd like

When using the Pin feature, the latest pinned note should be shown on the very top. 

With the current Memos version, the pinned notes are sorted by "created" which is not helpful, because the created date cannot be changed. And thus the sorting of pinned notes cannot be changed.

Two solutions:

1. Sort by "pinned timestamp".
2. Sort by "last edited". 

But definitely do not sort by "created".

### Type of feature

User Experience (UX)

**Comment by harveyghq** [comment]
You can go to `Settings`-`System`-`Display with updated time`.
