### ISSUE TITLE
When editing and clicking outside of the dialog overlay, the overlay gets closed and content is not saved

### ISSUE THREAD

**Issue by q2apro** [usememos/memos#2734]
### Describe the bug

When editing and clicking outside of the active dialog overlay, the overlay gets closed and content is not saved.

### Steps to reproduce

1. Edit a note
2. Add content
3. Click outside of the note (right or left padding area)
4. Note is dismissed/gets hidden
5. Content is NOT saved

### The version of Memos you're using

latest

### Solution

When clicked outside, trigger the *save content*.

**Comment by boojack** [comment]
Even if the dialog is closed, the edits cache is still there. And you should click the Save button manully to save edits.
