### ISSUE TITLE
Mobile View: Back button does not close the active text-base dialog

### ISSUE THREAD

**Issue by q2apro** [usememos/memos#2735]
### Describe the bug

Mobile View: Back button does not close the active text-base dialog, instead it navigates back.

### Steps to reproduce

1. Go to main page and login - use the browser (Chrome or Brave) on your mobile phone 
2. Edit an existing note
3. Click on the mobile's back button (intend to close the note, default behavior)
4. Memos navigates back to login page and keeps the note open, overlaying the login page

Expected behavior:
Close the note. Do not navigate.

### The version of Memos you're using

latest

**Comment by boojack** [comment]
It is not possible to change the "back" effect of the browser.
