### ISSUE TITLE
Textarea .text-base not updated with new content when note has been updated from other device

### ISSUE THREAD

**Issue by q2apro** [usememos/memos#2737]
### Describe the bug

Textarea .text-base not updated with fresh content when note has been updated from other device (severe bug)

### Steps to reproduce

- create a new note on your PC
- take your phone, load the note and make some edits (e.g. add content)
- cancel the edit on your phone, e.g. reload the page 
- edit the note on your PC again, add more content
- take phone again and reload the page so you see the updated note content
- on your phone click on edit note → Result: you see the content from your previously **cancelled edit** and not the new content inside the textarea
- Refreshing the page several times does not help to get the new content into the textarea. 
- It always shows the content of the cancelled edit on the phone.

Expected: The textarea should show the content of the updated note!

I assume the html5 local storage is used to store the content of the textarea. however, it needs to consider the timestamp of the loaded note. If different then update the textarea content.

Alternative: when reloading two times, clear the local Browser storage 

### The version of Memos you're using

latest

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/eb72609ea3258bc7c5cd07d4afa4c3497896345e
