### ISSUE TITLE
No place to show the version of memos

### ISSUE THREAD

**Issue by woodwm** [usememos/memos#2740]
### Describe the bug

I could not find a place to show the current version of the installed memos. Probably add the version information in the setting page.

If a feature to check the latest version is added, that would be great as well.

### Steps to reproduce

Explore all pages

### The version of Memos you're using

1.18.2

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/1994c20c547ce74abbfd013afd30cf65b6af8e77

<img width="765" alt="image" src="https://github.com/usememos/memos/assets/24653555/29b54933-4dc8-429e-8f2c-3dabcaf181c8">
