### ISSUE TITLE
[CSS] Add a new tag often have to experience an annoying problem

### ISSUE THREAD

**Issue by ArkURL** [usememos/memos#2741]
### Describe the bug

when i want to add a new tag in article, always have to experience a very annoying procedure. i have to move the pointer again and again to hover on the tag option. if i move the pointer incorettly, the option disappear.
i think it may be a css problem.

### Steps to reproduce

just like the gif below:
![PixPin_2024-01-11_15-12-30](https://github.com/usememos/memos/assets/56484166/75c293ea-c228-40a8-9ac7-784d8336decb)

### The version of Memos you're using

latest version

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/a1dda913c395549f1aee47c88f625c6b88d27636
