### ISSUE TITLE
Customize max content length of memo

### ISSUE THREAD

**Issue by 1itt1eB0y** [usememos/memos#2748]
### Describe the solution you'd like

![图片](https://github.com/usememos/memos/assets/29831189/cdbece48-9f13-40b2-8b63-4aad4885a8b0)

I hope 
- Add a gRPC option or configuration setting to allow setting the maximum message size on both the server and client.
- Consider introducing a function for slice-based transmission to enable efficient handling of large messages.

### Type of feature

API

**Comment by jayli** [comment]
I rebuild the docker package,  try this.

https://github.com/jayli/memos-new-v0.20.0

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/af1ad2f2dbb0f8c5c50bdc4549fb92431b66d2cb

**Comment by michaelien** [comment]
@Cousclou There should be a setting item for max content length in v0.22.0

<img width="1017" alt="image" src="https://github.com/usememos/memos/assets/161408495/1977d943-dca6-49fd-bdba-d0f51148d0f3">

**Comment by abs2free** [comment]
Additionally, since v0.22.0, you can configure this in Settings > Memo > Content length limit (Byte)
