### ISSUE TITLE
在0.18.2中，markdown的引用语法失效了

### ISSUE THREAD

**Issue by bfansheng** [usememos/memos#2758]
### Describe the bug

![image](https://github.com/usememos/memos/assets/16935251/50152886-04a9-4129-8b23-95326716aca8)
![image](https://github.com/usememos/memos/assets/16935251/23989f9f-ee15-4f2a-9a39-cd897b777181)

### Steps to reproduce

1. 添加内容"> 引用"
2. 无法渲染成引用格式

### The version of Memos you're using

0.18.2

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/fdbf2d8af2d7cfd8f8f97f94c267242dc525677f
