### ISSUE TITLE
DatePicker displays memos in UTC date.

### ISSUE THREAD

**Issue by harveyghq** [usememos/memos#2765]
### Describe the bug

`Timeline`'s datepicker displays memos in UTC date (calculated on server side). Users can get confused by this gap.

### Steps to reproduce

1. Write a memo.
2. Adjust created time to the previous UTC day (e.g. for a `UTC+8` user, adjust to 7 a.m. localtime.)
3. Switch to `Timeline`, click the `DatePicker`.
4. Now it display a badge for yesterday.

### The version of Memos you're using

[0.18.2](https://github.com/usememos/memos/commit/ad94e8e3c6cae4c76938a15d66ad156ca6d6b054)

**Comment by harveyghq** [comment]
Maybe we send local timezone to the server to calculate, or require server to return all raw timestamps (at a higher cost of course).

**Comment by harveyghq** [comment]
sry, the bug still exists. And the reason is that server side lacks knowledge of local timezone required for converting timestamps  into accurate dates. Currently the `GetUserMemosStats` api returns an array of converted-yet-standardlized UTC dates. I'm afraid there's insufficient data to make further adjustments during the client's rendering process.

**Comment by nalderto** [comment]
@harveyghq You're right, this is still a bug.  I misunderstood the issue.  With `GetUserMemosStats` just returning UTC date, we'll need to change the API.  @boojack This should be re-opened

**Comment by meizigz** [comment]
still exist.

**Comment by RoccoSmit** [comment]
Fixed with pr https://github.com/usememos/memos/pull/4046
