### ISSUE TITLE
0.18.2 Language set invalid

### ISSUE THREAD

**Issue by xxzj990** [usememos/memos#2767]
### Describe the bug

After updating to docker version 0.18.2, set the language to ‘简体中文’, then refresh the page, and the language returns to the default English.

### Steps to reproduce

1.updating to docker version 0.18.2
2.set the language to ‘简体中文’
3.refresh the page
4.the language returns to the default English

### The version of Memos you're using

docker v0.18.2

**Comment by harveyghq** [comment]
Acknowledged. I'm working on it.
