### ISSUE TITLE
Adding a newline (hitting Enter) when editing a list of checkboxes does not automatically create another checkbox

### ISSUE THREAD

**Issue by jeffxt** [usememos/memos#2773]
### Describe the bug

As a user
When I'm creating a list of checkboxes
I no longer have the ability to add a new checkbox when I hit Enter on my keyboard
Which means I have to manually go to the dropdown menu and select the checkbox option for each subsequent list item

### Steps to reproduce

1. Create a new memo
2. Select checkbox from the dropdown menu, add some text
3. Hit enter
4. *No new checkbox is created*
5. I have to select checkbox from the dropdown menu AGAIN, and then I can add some text
6. Repeat steps 3-5 for every list item

**NOTE:  I only noticed this bug when I updated the container to `:latest` as of today, which at the time of writing was `0.18.2`.  I must have been several versions behind before this point.**  

### The version of Memos you're using

0.18.2

### Screenshots or additional context

![memos](https://github.com/usememos/memos/assets/40279612/310efda4-bcc5-4223-84b8-8bc3046bb061)

Edit:  Updated my bug description to be more accurate to what I'm observing

**Comment by jeffxt** [comment]
@boojack I noticed you changed the tag from a bug to an enhancement, but this functionality used to be available in a previous release.  Was this functionality intentionally removed?  My assumption was that it was not, therefore it's a bug.  Please correct me if I'm wrong though!

**Comment by boojack** [comment]
It doesn't break the normal logic, so it should be an enhancement not a bug.

**Comment by faylost** [comment]
> @boojack I noticed you changed the tag from a bug to an enhancement, but this functionality used to be available in a previous release. Was this functionality intentionally removed? My assumption was that it was not, therefore it's a bug. Please correct me if I'm wrong though!

text

**Comment by eMUQI** [comment]
want this feature back too

**Comment by snusEbjoer** [comment]
Do u need only checkboxes or better add other tags support, something like list "-"?

**Comment by jeffxt** [comment]
> Do u need only checkboxes or better add other tags support, something like list "-"?

Here's my thinking (other people can share their thoughts too) -- the best user experience is allow the user to continue their previous action if it's a bullet pointed list `*` or `-`, an ordered list `1.` or checkboxes `- [ ]`.  I'm referring to all the options shown in their [official documentation](https://www.usememos.com/docs/getting-started/content-syntax).  If you're like me, how often are you ever creating a checklist with only 1 item?  Very rarely, at least in my opinion.

And I'm pretty sure this feature used to be there, which is why I originally tagged this as a bug, but I wonder if them switching to a new markdown parser in one of the previous releases changed this behavior?

**Comment by michaeldale** [comment]
Just adding a +1 that I want this feature back, I would consider it a bug as I have no idea why it would be removed and seriously impacts usability of the platform. I'm creating a lot less notes due to the extra steps required to use them.

**Comment by x2358473** [comment]
我也很好奇这个功能为什么砍了。我觉得这是每个markdown编辑器的基本功能吧
en:
I'm also curious why this feature was discontinued. I think this is the basic function of every markdown editor.

**Comment by x2358473** [comment]
这个问题是无法更改吗

**Comment by michaeldale** [comment]
Adding comment to keep this issue active.

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/6d10251cbdea88843183cdf08316d7e739a6f33e

**Comment by jeffxt** [comment]
@boojack Thanks for the `v0.21.0` update today.  However, I noticed that when I create a checkbox `- [ ]` and hit enter, it will only create a new list item `-`.

Would it be possible to change this behavior so that a checkbox will create another checkbox?

**Comment by x2358473** [comment]
@jeffxt 在v0.21.0中似乎并没有完全优化这个问题。比如 - [ ]  这个标签，使用回车后只会重复 " - "这个，它后面的 " [ ] "标签还是丢失了，等于还是没作用。只有list标签有点作用，如 1. 2. 这种的回车会进行重复。
且markdown中如果回车重复上一行的标签后再次按回车是清除重复的标签的，目前的版本再次按回车键是直接生成了新的一行，上一行留一个空标签行在那里，我不知道是出于什么原因导致这些问题。但在早期的版本中这些是完整支持的。

en:
This problem doesn't seem to be fully optimized in v0.21.0. For example, the label - [ ] will only repeat " - " after using carriage return. The " [ ] " label after it is still lost, which means it still has no effect. Only the list tag has some effect, such as 1. 2. This type of carriage return will be repeated.
And in markdown, if you press Enter to repeat the label of the previous line and then press Enter again, the repeated labels will be cleared. In the current version, pressing Enter again will directly generate a new line, leaving an empty label line in the previous line. I Don't know what causes these problems. But in earlier versions these were fully supported.
