### ISSUE TITLE
Automatically switches to English when you click on the timeline button.

### ISSUE THREAD

**Issue by critipan** [usememos/memos#2774]
### Describe the bug

Automatically switches to English when you click on the timeline button.

### Steps to reproduce

Click Timeline Button

### The version of Memos you're using

v0.18.2

### Screenshots or additional context

![动画](https://github.com/usememos/memos/assets/39651074/a155e364-75c3-4a12-9f31-e815f71ad490)

![动画2](https://github.com/usememos/memos/assets/39651074/96299bc7-8f5c-4c17-a8ca-3dee4147cb64)

**Comment by boojack** [comment]
Fixed
