### ISSUE TITLE
Statistics Image like in Demo Screenshot?

### ISSUE THREAD

**Issue by DerTobi75** [usememos/memos#2775]
### Describe the bug

Sorry, it is not really a bug. I would like to know, how I can enable the Statistics Table or Image like it is is on the upper right column in the Demo Screenshot?

### Steps to reproduce

Go to "Home"

### The version of Memos you're using

v0.18.2

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/2772979/db679143-784a-4fdc-9ab5-c9a66accd918)

**Comment by boojack** [comment]
Moved into the Timeline page.

<img width="692" alt="image" src="https://github.com/usememos/memos/assets/24653555/c9074b2b-7353-4922-8dee-30acac558202">
