### ISSUE TITLE
Show content filters(tag, search) in url queries

### ISSUE THREAD

**Issue by filippobenozzi** [usememos/memos#2777]
### Describe the solution you'd like

I'm memos as a bookmark of all the resources that I found by adding a tag in almost every post that I publish. I'm sharing my personal page to all the people that are interested in the activity that I do and It would be great for me to send the link of my profile page already filtered with a specific tag or set of tags.
In the meantime I used this "dirty" workaround made with javascript:

```
// Function
function checkAndAct() {
    const queryString = window.location.search;
    const urlParams = new URLSearchParams(queryString);
    const tags = urlParams.get('tags');
    const spans = document.querySelectorAll(`span.tag-span`);
    const matchingSpans = Array.from(spans).filter(span => span.textContent.includes(tags));
    if (matchingSpans.length > 0) {
        matchingSpans[0].click();
        observer.disconnect();
    }
}

// Create an observer
const observer = new MutationObserver(checkAndAct);

observer.observe(document.body, {
    childList: true,
    subtree: true
});
```

What do you think could it be a good feature?

### Type of feature

User Experience (UX)

**Comment by boojack** [comment]
SGTM, I'd like to represent the filter on the url. 

https://github.com/usememos/memos/blob/main/web/src/store/module/filter.ts#L31

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/70d1301dc30d062b3d417317cbefbb1770207f10
