### ISSUE TITLE
Disable public memos no longer appears to work 

### ISSUE THREAD

**Issue by Mask-Vip** [usememos/memos#2779]
### Describe the bug

There appears to have been a regression since this was https://github.com/usememos/memos/pull/2480. This is noted in the https://github.com/usememos/memos/issues/2462, but @itschip said to make a new bug, which I didn't see.

### Steps to reproduce

The issue persists, after following the steps #2694 to turn off public, registering a regular user will still be able to post a public memo, and registering a regular user again will still be able to see the public memo posted by the previous regular user.

### The version of Memos you're using

 v0.18.2

### Screenshots or additional context

Steps to reproduce
Create new Memos instance using Docker
Create an admin account
In Settings => System, tick the "Disable public memos" option so it is on (it is off by default)
In the Home tab, create a save note, ensuring the the visibility is enabled to "Public" (this shouldn't even be possible, the option should be grayed out)
Open a new private browser window and access the Memos instance (likely http://localhost:5230/explore)
Notice, that the public memo we created in step 4 is visible when it shouldn't be.

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/5172e4df7c0f46b208bfe89d22f99fd7e9c47888
