### ISSUE TITLE
Add references by searching

### ISSUE THREAD

**Issue by jneeee** [usememos/memos#2780]
### Describe the solution you'd like

Now the steps for me to add reference are
1. Adding a memos and thinking that it can be associated with another one
2. Search for relevant information, or filter it by tag, click the data and jump to a new page
3.  Copy its ID from the browser address bar.
4. Open the previous edit box and fill in the ID.

It would be great if I can search and double-click to add a reference in the dialog box for adding ref that pops up in the original editor, the experience will be better.
And it would be better to show the ID when hover over the data of a memo or directly display the memo ID after the data.

### Type of feature

User Experience (UX)

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/08ac60cc70026eb58737f7a3d76e2d7c52ef720e

**Comment by vinicius507** [comment]
@boojack for some reason you can't input spaces while searching for memos.
