### ISSUE TITLE
'invalid language tag: "en"' error after 0.18.2 upgrade

### ISSUE THREAD

**Issue by srozb** [usememos/memos#2783]
### Describe the bug

Hi,
I have a self-hosted memos instance based on `neosmemo/memos:latest` docker image. After upgrading to 18.2 I encountered the following issue:

```
Unexpected Application Error!
invalid language tag: "en"
toLocaleDateString@[native code]
ka@https://memos.myinstance.tld/assets/MemoView-ZCPCRITo.js:6:18644
Xh@https://memos.myinstance.tld/assets/index-pR50uxzc.js:28:21709
dj@https://memos.myinstance.tld/assets/index-pR50uxzc.js:30:3493
Vk@https://memos.myinstance.tld/assets/index-pR50uxzc.js:30:43779
Uk@https://memos.myinstance.tld/assets/index-pR50uxzc.js:30:43702
Jk@https://memos.myinstance.tld/assets/index-pR50uxzc.js:30:43544
Ok@https://memos.myinstance.tld/assets/index-pR50uxzc.js:30:39554
Fk@https://memos.myinstance.tld/assets/index-pR50uxzc.js:30:40448
jg@https://memos.myinstance.tld/assets/index-pR50uxzc.js:28:3534
@https://memos.myinstance.tld/assets/index-pR50uxzc.js:30:37704
```

I can't see any errors in the logs.

### Steps to reproduce

1. Upgrade to 18.2
2. Open the main page (after signing in)

### The version of Memos you're using

18.2

### Screenshots or additional context

Server profile
data: /var/opt/memos
dsn: /var/opt/memos/memos_prod.db
addr:
port: 5230
mode: prod
driver: sqlite
version: 0.18.2
metric: true

**Comment by tombatti** [comment]
Hi, from today, after updagre I have the same problem, but only from web
Adding new memos from Telegram bot work fine

Thanks
Tomas

**Comment by srozb** [comment]
It affects only the main page, as I was able to quickly click on 'resources' before issue showed up and then access other subpages, also sign out and in again.

**Comment by erbanku** [comment]
> It affects only the main page, as I was able to quickly click on 'resources' before the issue showed up and then access other subpages, also sign out and in again.

I encountered the same issue and was able to fix it by opening `https://memos.X.com/setting` and selecting the language option again.

**Comment by srozb** [comment]
Thank you @erbanku it helped!

**Comment by tombatti** [comment]
> > It affects only the main page, as I was able to quickly click on 'resources' before the issue showed up and then access other subpages, also sign out and in again.
> 
> I encountered the same issue and was able to fix it by opening `https://memos.X.com/setting` and selecting the language option again.

I tried going into the settings, I changed the language to English and then I returned to the Italian language as it was before, but the problem remains...

**Comment by srozb** [comment]
I suppose to reproduce this bug one should deploy 0.18.1 with `neosmemo/memos:latest` docker image, create user account and then upgrade to 0.18.2 version.

I'll be happy to provide more information about my environment but as it's docker container I think it's not that relevant. I use Safari/Orion browser under MacOS Sonoma.

It might be worth to mention that during this issue, when I navigated to 'setting/preferences' page I had 'Language' and 'Theme' fields unpopulated.

**Comment by tombatti** [comment]
In my case I use Chrome 120 on Window 11 Pro

I also use the latest version of container that runs on a Synology NAS. 
The problem started today after updating to version 0.18.2. before everything was ok

In my case, going into the settings, the language and theme fields are correctly set

Thanks
Tomas
