### ISSUE TITLE
Automatically check and notify to user when new updates are available

### ISSUE THREAD

**Issue by f97** [usememos/memos#279]
Similar to this, why not?

<img width="656" alt="image" src="https://user-images.githubusercontent.com/110044923/195322701-8a0ce417-fcf1-475e-9c44-abc3b1494c8a.png">

yeah, this image from [uptime-kuma](https://github.com/louislam/uptime-kuma)

**Comment by YuJianghao** [comment]
```text
https://hub.docker.com/v2/repositories/neosmemo/memos/tags/?page_size=1
```

[try api](https://hub.docker.com/v2/repositories/neosmemo/memos/tags/?page_size=1)

```ts
function getLatestVersion() {
  const url = `https://hub.docker.com/v2/repositories/neosmemo/memos/tags/?page_size=1`
  return fetch(url)
    .then((res) => res.json())
    .then((data) => data.results[0].name as string)
}
```

Happy to implement.
