### ISSUE TITLE
New timeline issue

### ISSUE THREAD

**Issue by Schachte** [usememos/memos#2790]
### Describe the bug

I got the latest update and timeline seems incorrect. 

The view shows as December 2023 but the dates are for January 2024.
<img width="865" alt="image" src="https://github.com/usememos/memos/assets/7055226/75464819-6d46-4ac8-b807-1fa050182766">

### Steps to reproduce

Go to timeline on latest version (Version: v0.18.2)

### The version of Memos you're using

Version: v0.18.2

### Screenshots or additional context

See above

**Comment by boojack** [comment]
Duplicated with #2786

**Comment by Schachte** [comment]
Oops, sorry @boojack !
