### ISSUE TITLE
希望增加图片直接粘贴（Ctrl+V）上传并插入到鼠标选择位置

### ISSUE THREAD

**Issue by xlpppp** [usememos/memos#2793]
### Describe the solution you'd like

现在在文档插入图片，需要先用上传附件的方式，按CTRL+V粘贴并上传，且上传后的文件默认在最底部，无法直接插入到文章指定位置，很不方便
希望增加图片直接粘贴（Ctrl+V）上传并插入到鼠标选择位置

### Type of feature

User Interface (UI)

**Comment by boojack** [comment]
When using markdown image syntax, we cannot know what's the relationship between images and memos. So it's not recommend to do it.
