### ISSUE TITLE
Underline is not displayed

### ISSUE THREAD

**Issue by xxzj990** [usememos/memos#2794]
### Describe the bug

Underline is not displayed,As shown below:

![微信截图_20240119170107](https://github.com/usememos/memos/assets/5134154/66fc32e6-a0ec-4fd6-8d11-8242e487fe09)

### Steps to reproduce

1.Create a new memo,Enter A_B_C.
2.View list after saving.
3.Shown as ABC.

### The version of Memos you're using

docker v0.18.2

**Comment by boojack** [comment]
Your underline syntax is not a standard markdown syntax. And GitHub not supported it too. `_123_` -> _123_
