### ISSUE TITLE
Setting reminders for memos

### ISSUE THREAD

**Issue by noheton** [usememos/memos#2797]
### Describe the solution you'd like

As I use memos for a stream of consciousness kind of note taking. Sometimes todos come to mind with have a deadline.
It would be great if memos could handle (time based) reminders (like 1/1/24, 13:00) and even check for "checkmark" completion.

### Type of feature

Other

**Comment by MehadND** [comment]
Hi @noheton, can you please provide me with more info related to this "feature"? Would you like Memo to send you an email or something like this to notify you about the reminders or just an in-app notification would be enough (maybe something like on GitHub...a place to access all reminders or upcoming ones? 

<br/>

> even check for "checkmark" completion.

And what exactly do you mean by this?

**Comment by noheton** [comment]
For my purposes a in-app notification would be enough.
But for deeper integration (e.g. Gotify or other services through n8n.io and the likes) a webhook for these kind of notifications could be very useful.

Regarding "checkmark" completion:
Assuming a memo:
```
- [ ] buy milk
- [ ] go to post office
remind me at 22/01/2024, 9am
```
Obviously, the checkmarks are not "checked" so the reminder notification would "fire". 
If "all" checkmarks are "checked" then the notification would not fire.
But this would be the start of a more involved to-do system, which would probably require a lot more thought.

For now, reminders would be already particularly useful for my memos experience.

**Comment by ertuil** [comment]
Maybe you can try my toy project [memos-reminder](https://github.com/ertuil/memos-reminder) for a temporary solution before Memos provides this feature. It uses webhook, sends emails via SMTP, and generates a calendar `ics` file.

It is built initially to satisfy my own requirements, but suggestions are welcome.

**Comment by noheton** [comment]
> Maybe you can try my toy project [memos-reminder](https://github.com/ertuil/memos-reminder) for a temporary solution before Memos provides this feature. It uses webhook, sends emails via SMTP, and generates a calendar `ics` file.
> 
> It is built initially to satisfy my own requirements, but suggestions are welcome.

This looks interesting - thanks for the hint.
But love the calendar integration.
Email unfortunately is not my preferred way of notification.
Seems like I have to learn go :).

**Comment by LeeseTheFox** [comment]
I was surprised to see that such a basic feature is missing
