### ISSUE TITLE
migrate data failed.

### ISSUE THREAD

**Issue by Crazyokd** [usememos/memos#2798]
### Describe the bug

ERROR   memos/main.go:66        failed to migrate resource internal path        {"error": "failed to list resources: SQL logic error: no such column: memo_id (1)", "errorVerbose": "SQL logic error: no such column: memo_id (1)\nfailed to list resources\ngithub.com/usememos/memos/store.(*Store).MigrateResourceInternalPath\n\t/backend-build/store/migrator.go:20\nmain.glob..func1.1\n\t/backend-build/bin/memos/main.go:64\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650"}

### Steps to reproduce

1. start the container and logs the container

### The version of Memos you're using

v0.18.2

**Comment by Crazyokd** [comment]
![image](https://github.com/usememos/memos/assets/74645100/3e1e93f3-ec33-4601-95c3-e4476c9948d5)

![image](https://github.com/usememos/memos/assets/74645100/90ee5c93-5a6d-47e4-a8a4-abb976b0eea9)

**Comment by Crazyokd** [comment]
the previous version I used is four week ago, maybe v0.18.1(I'm sorry i can't remember clearly).

**Comment by boojack** [comment]
Seeing that your database was created in October. So the version is definitely not a direct upgrade from `0.18.x`. 

It is recommended to modify the database schema directly, referring to the latest schema https://github.com/usememos/memos/blob/main/store/db/sqlite/migration/prod/LATEST__SCHEMA.sql

**Comment by Daxhu19** [comment]
> 看到您的数据库是在 10 月创建的。所以这个版本绝对不是直接升级的。`0.18.x`
> 
> 建议直接修改数据库模式，参考最新的模式 https://github.com/usememos/memos/blob/main/store/db/sqlite/migration/prod/LATEST__SCHEMA.sql

文档已删除，现在该怎么把0.18.0 MySQL数据库的版本更新到最新的0.25.1
