### ISSUE TITLE
Inline code not working

### ISSUE THREAD

**Issue by gitkeniwo** [usememos/memos#2800]
### Describe the bug

Inline code syntax not boxed in code blocks. 

### Steps to reproduce

<img width="459" alt="image" src="https://github.com/usememos/memos/assets/34304497/641102ee-9082-4b9f-a417-c85c5d0fb309">

<img width="311" alt="image" src="https://github.com/usememos/memos/assets/34304497/79f92194-c91e-4d7e-b23d-110a3ca15ff4">

### The version of Memos you're using

0.18.2

**Comment by ti777777** [comment]
#2786
