### ISSUE TITLE
Unexpected Application Error! Importing a module script failed.

### ISSUE THREAD

**Issue by ClassmateShen** [usememos/memos#2801]
### Describe the bug

Unexpected Application Error!
Importing a module script failed.

### Steps to reproduce

我只是删除了登陆令牌，因为每登陆一次就会多一个新的API令牌，然后就出现了如上的报错

### The version of Memos you're using

latest

**Comment by truongnguyen3** [comment]
I got this issue in Mac Safari, My memos site runs in v0.21.0 and it works fine in Chrome.

<img width="1317" alt="image" src="https://github.com/usememos/memos/assets/148203070/a4c62a47-3ce0-4a6a-a3d1-ae6fbf949390">


this is my site: https://fragrant-guppy.pikapod.net/auth
how did you fix this issue?
