### ISSUE TITLE
Unable to double click to edit a memo

### ISSUE THREAD

**Issue by Arom1a** [usememos/memos#2802]
### Describe the bug

This is achievable in the previous version which is 0.18.1. This change is not mentioned in the release log so I doubt it is a bug rather than intended. 

### Steps to reproduce

1. save a memo
2. double click on it

### The version of Memos you're using

0.18.2

**Comment by MehadND** [comment]
@boojack kindly review this [PR](https://github.com/usememos/memos/pull/2806) related to this issue.

**Comment by webysther** [comment]
@MehadND why the PR was removed?

**Comment by MehadND** [comment]
@webysther I removed the PR because I either saw somewhere on GitHub or on Discord, where someone or maybe the project owner explained why the double click to edit memo functionality was removed. And at that time it seemed reasonable to remove the PR but if I can get the go from the project owner (@boojack) then I can re-open the PR.

**Comment by boojack** [comment]
@MehadND Let's do not add double-click to edit, as it's inconsistent with a lot of behaviors and hard to select certain text anymore. We don't want to lose some functionality for convenience.

**Comment by webysther** [comment]
> @MehadND Let's do not add double-click to edit, as it's inconsistent with a lot of behaviors and hard to select certain text anymore. We don't want to lose some functionality for convenience.

Any chance in future add a button direct in header of a note with pen icon to edit?

**Comment by MehadND** [comment]
> > @MehadND Let's do not add double-click to edit, as it's inconsistent with a lot of behaviors and hard to select certain text anymore. We don't want to lose some functionality for convenience.
> 
> Any chance in future add a button direct in header of a note with pen icon to edit?

Well I think if you double click a memo header, it goes to that memo detail page and there you can edit the memo using pen icon. Maybe something you were looking for 🤷🏽‍♂️

**Comment by rb-26** [comment]
I agree with @webysther, a dedicated edit button on the note would be perfect if the double click is no longer an option.

**Comment by MehadND** [comment]
@rb-26 each memo already has its dedicated edit button in the vertical action menu.

**Comment by rb-26** [comment]
> @rb-26 each memo already has its dedicated edit button in the vertical action menu.

Yeah, but it is unnessesary clicks when you are editing notes often. Not a huge deal, just a nice to have.
