### ISSUE TITLE
Telegram Bot not work

### ISSUE THREAD

**Issue by jtsang4** [usememos/memos#2810]
### Describe the bug

Version: 0.18.2
Setup method: Docker Compose
Error message in docker compose logs:
```txt
WARN    telegram/bot.go:44      fail to telegram.GetUpdates     {"error": "fail to http.PostForm: Post \"https://api.telegram.org/bot<token>/getUpdates\": EOF", "errorVerbose": "Post \"https://api.telegram.org/bot<token>/getUpdates\": EOF\nfail to http.PostForm\ngithub.com/usememos/memos/plugin/telegram.(*Bot).postForm\n\t/backend-build/plugin/telegram/request.go:21\ngithub.com/usememos/memos/plugin/telegram.(*Bot).GetUpdates\n\t/backend-build/plugin/telegram/api_get_updates.go:17\ngithub.com/usememos/memos/plugin/telegram.(*Bot).Start\n\t/backend-build/plugin/telegram/bot.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650"}
```

### Steps to reproduce

Just run docker-compose in official self-host tutorial to run memos.

### The version of Memos you're using

0.18.2

**Comment by r0ld3x** [comment]
maybe bot token problem

**Comment by afdhal395** [comment]
check your bot token. I deployed memos today for the first time and Telegram bot integration is working fine.

**Comment by jtsang4** [comment]
Thank you for your replies. Through your confirmation, I finally found out that it is a problem with my local routing network configuration. Sorry to bother you.
