### ISSUE TITLE
Timeline stuck on the year 2023

### ISSUE THREAD

**Issue by jon-f-novastor** [usememos/memos#2817]
### Describe the bug

Timeline is stuck on Dec 2023 (as the latest date), even though there are Jan 2024 created Memos entries in Memos v18.0.2. Entries created in Nov 2023 show in the Timeline as Dec 2023. I'm seeing ("QSnexus" user, as well as one other user "Stayer", in the Memos Discord > Questions chat on 01/20/24) that in my memos v0.18.2 instance, with a few memos created in Jan 2024, the Timeline is still stuck on Dec 2023. I even tried restarting the instance and did a vacuum but that didn't help. I'm not seeing a bug for that one on the GitHub. They redid this feature in this version, so probably it is a bug.

### Steps to reproduce

1.Make sure your Linux machine where the Memos instance is already installed on is using Pacific Time Zone and the clock and date is showing correct, at least that it is already in the 2024 year.
2. Have at least one Memo note added that has a created date of January 2024. (Not sure if this step is required but this is what I had in place).
3. Upgrade to Memos v0.18.2 from v0.18.1 on Ubuntu Linux x64 for the Docker container variant. I'm not sure if this issue would affect clean installs or only upgrade installs.
4. Login to Memos via Chrome or Firefox web browser.
5. Click on the Timeline and it will be stuck at December 2023 with no way of moving to January 2024. That is even though you already have a January 2024 created note.
6. Go back to the Home page of Memos.
7. Create one more Memos note while in the year 2024.
8. Make sure that new note saves and lists in Home tab.
9. Click on Timeline.
10. You should see while in Timeline view it is still stuck on December 2023. Restarting the instance again and performing a vacuum at this point won't help.

### The version of Memos you're using

0.18.2

### Screenshots or additional context

Timeline view, viewed on 01/21/24:

![Screenshot_20240121-094728](https://github.com/usememos/memos/assets/50121594/a1e1f7b6-19c9-4c62-ab3d-eedf72731109)

Viewing individual Memos created in January 2024 in Home tab, by clicking on each one to view the entire entry to see the date timestamp of each entry:
![Screenshot_20240121-094650~2](https://github.com/usememos/memos/assets/50121594/5333e80d-06ec-4229-9534-cfc500f1233a)

![Screenshot_20240121-094642~2](https://github.com/usememos/memos/assets/50121594/4e4a595a-9022-45ac-977d-0641fa154f9c)

Even the official Memos Demo instance website (https://demo.usememos.com/timeline) has the same bug, seen here when checking on 01/22/24:
![Screenshot_20240122-184451](https://github.com/usememos/memos/assets/50121594/93b09926-72a5-4fea-b606-e4ef6c0d492c)

**Comment by HappyZ** [comment]
+1

**Comment by HappyZ** [comment]
It isn't really stuck for me. All notes from Jan 2024 went to Dec 2023, and similarly all notes in Dec 2023 went to Nov 2023. Looks like some bug grouping the notes

**Comment by jon-f-novastor** [comment]
> It isn't really stuck for me. All notes from Jan 2024 went to Dec 2023, and similarly all notes in Dec 2023 went to Nov 2023. Looks like some bug grouping the notes

I think you are right, I went back and looked at my 18.0.2 instance and all notes created in Nov 2024, show on my Timeline as created in Dec 2023 dates (exact timestamps). I didn't create any notes in Dec 2023, but I assume those either won't show in the Timeline or will be grouped into Dec 2023 if any were created in that month in 2023. However if I go back a year ago on the Timeline that shows "May 2023", all of the individual listed Memo entries show created in June 2023 dates (exact timestamps), and the Timeline that shows "April 2023" but all of the individual listed Memos entries show created in May 2023 dates (exact timestamps). So yes there appears to be a bug grouping the notes in the correct Timeline grouped month.

**Comment by devanteweary** [comment]
Just installed this (awesome) app on Unraid and yeah, all my notes are being created in December 2023.

**Comment by jon-f-novastor** [comment]
Thanks for the fix guys.
