### ISSUE TITLE
After the database is switched to MySQL, the large file is uploaded incorrectly

### ISSUE THREAD

**Issue by Mask-Vip** [usememos/memos#2818]
### Describe the bug

In the default database, you can upload files larger than 700 MB, but when the database is switched to mysql, an error is reported when the upload file exceeds the database limit. Change the database size limit again max_allowed_packet = 2048 MB

After that, the error message is "Data too long for column 'blob' at row 1" is returned

### Steps to reproduce

{"time":"2024-01-21T19:07:06Z","latency":"1.969964607s","method":"POST","uri":"/api/v1/resource/blob","status":500,"error":"code=500, message=Failed to create resource, internal=Error 1105 (HY000): Parameter of prepared statement which is set through mysql_send_long_data() is longer than 'max_allowed_packet' bytes"}

{"time":"2024-01-21T19:12:49Z","latency":"2.77445071s","method":"POST","uri":"/api/v1/resource/blob","status":500,"error":"code=500, message=Failed to create resource, internal=Error 1406 (22001): Data too long for column 'blob' at row 1"}

### The version of Memos you're using

Version: v0.18.2

**Comment by lincolnthalles** [comment]
On MySQL, `max_allowed_packet` should be set appropriately to handle the file size, but the data also must fit in the database field.

Memos is using `MEDIUMBLOB` in MySQL schema, which limits data to only 16MB. This should be fixed (by changing to LONGBLOB=4GB), as SQLite and Postgre both defaults to 1GB.

Despite this issue, unless you are running Memos on a system with awful I/O performance and the database server is on a much more powerful machine, it's probably best to set object storage to `Local file system` in system settings.

If Memos host have decent I/O performance, SQLite will most likely outperform MySQL with binary data that large, as there's no network stack penalty and it uses a single file that's always open.

**Comment by boojack** [comment]
Sorry, I don't think it's good to store such large files into database, 16MB is more than enough. If you do need to store larger files, you should use s3, or local storage.
