### ISSUE TITLE
清理资源库中不使用的资源出现问题

### ISSUE THREAD

**Issue by YJLAugus** [usememos/memos#2821]
### Describe the bug

1. 无法一键删除 
2. 数据库文件清除不使用也基本无作用
3. 保存提交、删除多个照片的微博提交按钮一直在加载中，无反馈成果或者失败提示

### Steps to reproduce

1. 无法一键删除 
2. 数据库文件清除不使用也基本无作用
3. 保存提交、删除多个照片的微博提交按钮一直在加载中，无反馈成果或者失败提示

### The version of Memos you're using

18.2

### Screenshots or additional context

no

**Comment by YJLAugus** [comment]
资源库文件删除按钮bug

**Comment by boojack** [comment]
If you really want to solve the problem, please don't create a issue with same description and reproduce steps.

<img width="656" alt="image" src="https://github.com/usememos/memos/assets/24653555/6a9a6e5b-3aba-4c84-89fd-18d7ffbf2afa">
