### ISSUE TITLE
tag is started with ‘#‘，it is easily mix up with content

### ISSUE THREAD

**Issue by gansui** [usememos/memos#2822]
### Describe the solution you'd like

now tag is the string started with ‘#‘，it is easily mix up with content。I suggest change it to '###', this could backward compatible with previous version.
or add a feature ,make user could custom their own tag character

### Type of feature

User Experience (UX)

**Comment by boojack** [comment]
> I suggest change it to '###', this could backward compatible with previous version.

This is not a common syntax.
