### ISSUE TITLE
More Todo / agenda features

### ISSUE THREAD

**Issue by gittynick** [usememos/memos#2823]
### Describe the solution you'd like

Hello,

I much enjoyed testing Memos, the interface is very simple and straightforward !
I tried a "similar" project [DailyNotes](https://github.com/m0ngr31/DailyNotes) but it is not yet ripe and seems no longer developed - i also use a software called [Taskpaper](https://www.taskpaper.com/) but it's Mac-only

I really like the calendar part of Memos as i tried it both for daily journaling and for tasks/todos - but there are a few enhancements that would make it more usable for task-related content :
- tags for dates like @tomorrow or @22-jan-2024 (with a popup calendar like in taskpaper), that would look neat 😄 
- tags for specific users such as @mike or @brenda (with a list of available users like for normal #tags)
- some kind of notification for when a task is due / overdue (in-app notification is good for me)
- being able to modify dates (including to place a memo in the future for a due-date)
- UI: adding a bigger calendar on the timeline section maybe ? (easier to browse)
- UI: making different marks on the calendar depending of the type of memo (for eg. green for a text-only memo, blue if there is a checkbox/task detected... red if the task is overdue ?)

Anyhow, keep the good work, Memos is a nice project 👍 

Best Regards

Nick

### Type of feature

User Interface (UI)

**Comment by noheton** [comment]
Also see: https://github.com/usememos/memos/issues/2797
+1

**Comment by Novapixel1010** [comment]
FYI in [v0.31.0-rc.1](https://github.com/usememos/memos/releases/tag/v0.31.0-rc.1) there is a going to be a larger calendar, you can modify dates. And I am working a feature for due dates but its in beta right now.
