### ISSUE TITLE
Support content search in explore page

### ISSUE THREAD

**Issue by moehanabi** [usememos/memos#2824]
### Describe the solution you'd like

I found that in commit [#d3bd3](https://github.com/usememos/memos/commit/d3bd3ddab03345083de159433cdaf03f074d1c85), you deleted the searchbar in explore page. Was this deleted by accident or on purpose?

Because people without logging in can only see explore page, I think the searchbar on explore page is necessary.

### Type of feature

User Interface (UI)

### Additional context

related pr: #2025 

related open issue: #660

**Comment by boojack** [comment]
Duplicated with https://github.com/usememos/memos/issues/660
