### ISSUE TITLE
Why remove Double-click feature?

### ISSUE THREAD

**Issue by gujin03** [usememos/memos#2825]
### Describe the bug

Double-click to enter the editing state is a feature that is easy to use for users. Why do you remove this feature in version 0.18.2? What are the considerations? Can you share it?

### Steps to reproduce

Double-click can easily to edit

### The version of Memos you're using

0.18.2

**Comment by gujin03** [comment]
same as https://github.com/usememos/memos/issues/2802

**Comment by 2vl** [comment]
Double-click to edit affects the use of double-click selection function. I think deleting it is correct, but I have a suggestion: add the feature of editing by double-clicking on the header area. What do you think?
