### ISSUE TITLE
提交内容时候，content too long，可不可以解除内容长度限制？

### ISSUE THREAD

**Issue by helberg1984** [usememos/memos#2826]
### Describe the solution you'd like

感谢开发者，memos很好用。只是既然是自己搭建服务器，容量都够用，可不可以解除掉内容长度限制，这样使用起来更加方便。我每次写了太长内容，都会提示content too long，这让体验很不好。
谢谢，打扰。

### Type of feature

Integrations

**Comment by boojack** [comment]
Duplicated #2748

**Comment by helberg1984** [comment]
我没太懂，是已经解决了吗？

**Comment by jayli** [comment]
我重新修改了源码打了 Docker 包，可以试下这个：

https://github.com/jayli/memos-new-v0.20.0
