### ISSUE TITLE
Latest commit doesn't pull memos (logged in or explore page)

### ISSUE THREAD

**Issue by jhademcconnell** [usememos/memos#2830]
### Describe the bug

There is an error thrown from the latest commit when logging into the instance or viewing the explore page. The instance I am testing on uses PostgreSQL:

```
Uncaught (in promise) ClientError: /memos.api.v2.MemoService/ListMemos UNKNOWN: pq: column memo.resource_name does not exist
    at makeCall (index-I3ShbRhI.js:300:6112)
    at async at (index-I3ShbRhI.js:300:11471)
    at async Object.listMemos (index-I3ShbRhI.js:300:11982)
    at async Object.fetchMemos (index-I3ShbRhI.js:323:71786)
    at async w (Home-988rli3l.js:1:9199)
```

### Steps to reproduce

1. Build the latest commit
2. Navigate to the site
3. No memos are loaded, check the console
4. View error

### The version of Memos you're using

v0.18.2 (latest commit)

**Comment by boojack** [comment]
Use use stable/latest docker image instead of main branch in your prod environment.
