### ISSUE TITLE
The content in the comment area cannot be searched

### ISSUE THREAD

**Issue by gujin03** [usememos/memos#2834]
### Describe the bug

The content in the comment area cannot be found.

### Steps to reproduce

write some comments
![image](https://github.com/usememos/memos/assets/38389059/bf1c6269-e56e-47fc-8887-a3f27dd5d7a5)
then search
![image](https://github.com/usememos/memos/assets/38389059/c193adc1-2793-4560-aa58-ebfdea4ba153)

### The version of Memos you're using

0.18.2

**Comment by boojack** [comment]
Maybe fixed
