### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by mariushosting** [usememos/memos#2835]
### Describe the solution you'd like

It would take an option to have more pages Pagination. Once the notes become many the page loads heavily. So, an option like "Pagination" to limit notes to 3, 5 or 10 per page. Example: https://blog.mariushosting.com/u/mariushosting
Pagination as an option in the settings. @boojack 

### Type of feature

User Experience (UX)

### Additional context

Pagination as an option in the settings.

**Comment by MehadND** [comment]
Looks very interesting feature I will see what I can do

**Comment by mariushosting** [comment]
> Looks very interesting feature I will see what I can do

Awesome!

**Comment by MehadND** [comment]
@boojack for this I was thinking of using Pagination from Material UI. Can I do that? i.e join material ui and joy ui together. It requires a little bit of setup but it can be done

**Comment by mariushosting** [comment]
> The data request right now is pagination, 20 entries at a time. And there is no need for a page navigation like a data table, at least no place on the UI to display it.

Can we have an option to reduce that size to 5 or 10 instead of the default 20?

**Comment by boojack** [comment]
It may be possible to reduce the amount. But for your example, the main reason is that images take up a lot of space, so we can optimize the image display.

**Comment by mariushosting** [comment]
> It may be possible to reduce the amount. But for your example, the main reason is that images take up a lot of space, so we can optimize the image display.

Actually, the issue is with the FID as a part of the Core Web Vitals coming in March 2024. If you have 20 Notes per page with images or videos, you then have an LCP issue: longer than 4s-8s (mobile). That means a longer page loading time. I think the images display is perfect as it is in version 0.18.2, but I realize we really need to have an option to reduce the notes numbers to 5, 10 or 20, as per the user's needs/requirements.

**Comment by boojack** [comment]
> I realize we really need to have an option to reduce the notes numbers to 5, 10 or 20, as per the user's needs/requirements.

To minimize and avoid to add unnecessary setting, no custom request count for now. We will find a more suitable value.

**Comment by mariushosting** [comment]
> > I realize we really need to have an option to reduce the notes numbers to 5, 10 or 20, as per the user's needs/requirements.
> 
> To minimize and avoid to add unnecessary setting, no custom request count for now. We will find a more suitable value.

I feel the product is expanding and so the vision for it should grow along. This is not an unnecessary setting, but rather a sort of core feature. Thank you for taking the time to look into this.

**Comment by MehadND** [comment]
@mariushosting If you want to do this for yourself then consider changing the DEFAULT_LIMIT value in 
`@/helper/const`

**Comment by boojack** [comment]
FYI, the default request limit had been updated to `10`.
https://github.com/usememos/memos/commit/7edb3598eaf7a98c88ccef006278d47a413520f1

**Comment by mariushosting** [comment]
> FYI, the default request limit had been updated to `10`. [7edb359](https://github.com/usememos/memos/commit/7edb3598eaf7a98c88ccef006278d47a413520f1)

Thank you @boojack ! I appreciate you taking the time to do this and how involved you are in the process. 10 sounds perfect!
