### ISSUE TITLE
Highlight content

### ISSUE THREAD

**Issue by mtcsol** [usememos/memos#2840]
### Describe the bug

![WX20240127-111058](https://github.com/usememos/memos/assets/95003037/f0294f2b-aad4-4f1a-9ef0-e68a38b62613)
![WX20240127-111030](https://github.com/usememos/memos/assets/95003037/6ee0fd45-e640-4c5e-9dc6-7a142ab58e6f)

### Steps to reproduce

today is Sunday , this ==is highligt== ok!

### The version of Memos you're using

Version: v0.19.0

**Comment by boojack** [comment]
Fixed in https://github.com/usememos/memos/commit/10d709c16734a363f1580a51724f3288ef164112
