### ISSUE TITLE
Problem occurred after update

### ISSUE THREAD

**Issue by tslcat** [usememos/memos#2842]
### Describe the bug

show：
Error: Unable to preload CSS for /assets/CommonDialog-ggPb2_vQ.css
    at HTMLLinkElement.<anonymous>

### Steps to reproduce

Open web version

show：
Error: Unable to preload CSS for /assets/CommonDialog-ggPb2_vQ.css
    at HTMLLinkElement.<anonymous>

### The version of Memos you're using

The latest version

**Comment by lincolnthalles** [comment]
Try pressing Ctrl+F5 or clearing your browser cache. This usually solves this kind of issue.
