### ISSUE TITLE
SSO登录受是否注册影响

### ISSUE THREAD

**Issue by 286615275** [usememos/memos#2847]
### Describe the solution you'd like

我禁止了用户注册，但是这会影响到SSO登录，会导致登录失败，会提示禁止注册，希望能将其分开，禁用外部注册，但是SSO登录时能够注册

### Type of feature

User Interface (UI)

**Comment by boojack** [comment]
`Disable password login` might helps. Reference: https://github.com/usememos/memos/issues/1935

<img width="1037" alt="image" src="https://github.com/usememos/memos/assets/24653555/5c419c23-5767-41ba-a41b-8ac1e4a4f85a">

**Comment by 286615275** [comment]
> `Disable password login` might helps. Reference: #1935
> 
> <img alt="image" width="1037" src="https://private-user-images.githubusercontent.com/24653555/300246379-5c419c23-5767-41ba-a41b-8ac1e4a4f85a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MzYwMzIsIm5iZiI6MTcwNjgzNTczMiwicGF0aCI6Ii8yNDY1MzU1NS8zMDAyNDYzNzktNWM0MTljMjMtNTc2Ny00MWJhLWE0MWItOGFjMWU0YTRmODVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDAxMDIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZjkwYWE2MTBlMTU2MmMzMzFiZWMxODM3YTdhZTQ2OGEzODAwOTNjM2QyZGFhMTE1ZDIzY2VlYTgyN2I4ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ll9EuR-emDqT23ikFc7Q8q2aVMbh9rOIqxG86DQK8bU">



> `Disable password login` might helps. Reference: #1935
> 
> <img alt="image" width="1037" src="https://private-user-images.githubusercontent.com/24653555/300246379-5c419c23-5767-41ba-a41b-8ac1e4a4f85a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MzYwMzIsIm5iZiI6MTcwNjgzNTczMiwicGF0aCI6Ii8yNDY1MzU1NS8zMDAyNDYzNzktNWM0MTljMjMtNTc2Ny00MWJhLWE0MWItOGFjMWU0YTRmODVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDAxMDIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZjkwYWE2MTBlMTU2MmMzMzFiZWMxODM3YTdhZTQ2OGEzODAwOTNjM2QyZGFhMTE1ZDIzY2VlYTgyN2I4ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ll9EuR-emDqT23ikFc7Q8q2aVMbh9rOIqxG86DQK8bU">

但是我想实现两种方式都可以登录，但是只能使用SSO注册，这种就不行
