### ISSUE TITLE
[BUG] The new markdown parser does not split URLs with whitespace

### ISSUE THREAD

**Issue by Cologler** [usememos/memos#2848]
### Describe the bug

Whitespace should be used to split two or more URLs.

### Steps to reproduce

1. Open `memos` in browser;
2. Add note `https://github.com/usememos/memos https://github.com/usememos/memos` and save;
3. The note is rendered to a link `https://github.com/usememos/memos%20https://github.com/usememos/memos`;

### The version of Memos you're using

0.18.2

**Comment by boojack** [comment]
Thanks for your report, it'll be fixed with https://github.com/usememos/memos/commit/55ecdae509a014dba7a897acb3ad9e5d84954ca9
