### ISSUE TITLE
The latest version consumes a significant amount of memory, please update with caution.

### ISSUE THREAD

**Issue by ixxmu** [usememos/memos#2850]
### Describe the bug

The latest version consumes a huge amount of memory, causing the VPS to crash when loading data.
I earnestly request developers to provide a reminder in the update logs when there are breaking changes.

### Steps to reproduce

just pull lates docker and did not change else

### The version of Memos you're using

0.19.0

### Screenshots or additional context

Every time I open the page, it fails to load data, which leads to the VPS memory getting filled up and causing other services to crash! The current Memos is extremely unfriendly to machines with 2GB of memory, so please use it with caution.

**Comment by bit649** [comment]
I'm encountering the same issue here. The original memory usage was around 150MB, but now it has increased to 1.5GB.
<img width="655" alt="20240129-100631@2x" src="https://github.com/usememos/memos/assets/26522401/97db9d86-6320-4f51-9ea6-25ac4f7460b8">

**Comment by m1732948116** [comment]
我也是，nas直接崩了，然后memos也崩了自动重启。我现在回退一下版本看数据还在不在。悲催，偏偏这次更新没备份

**Comment by m1732948116** [comment]
万幸，回退旧版本文件还在。崩溃的原因应该是
Upgrade overview
⚠️ This release contains upgrade notes that deviate from the norm:

**Requires database migrations;**
Use short UUIDs instead of auto-incrementing IDs for memo and resource in API and frontend;
The docker image tag latest will be deprecated, use stable instead;

**Comment by gitkeniwo** [comment]
Same. I have 3000+ memos. Seems like the memos are always loading after upgrading to 0.19.0. I've checked the new sqlite db file. Other than the new UUID column everything remains untouched, so it cannot be the db migration process.

This is reproducible both on my server and in my local docker environment. So far haven't figured out how to make it work, so I downgraded back to 0.18.2

**Comment by Derekmini** [comment]
经历了以上相同的问题后，我换回0.18.2版本，当时认为一切都正常，并且使用网页版创建一条Memo，其中包含一张使用本地库的图。但目前在创建第二个Memo的时候，发现弹出以下错误，指示标签的唯一性检测出现错误：

<img width="350" alt="image" src="https://github.com/usememos/memos/assets/30514323/c00b969b-fa01-4bf2-bcb2-2f22b191d18e">

具体日志内容如下：

```log
---
Server profile
data: /var/opt/memos
dsn: /var/opt/memos/memos_prod.db
addr: 
port: 5230
mode: prod
driver: sqlite
version: 0.18.2

metric: true
---
███╗   ███╗███████╗███╗   ███╗ ██████╗ ███████╗
████╗ ████║██╔════╝████╗ ████║██╔═══██╗██╔════╝
██╔████╔██║█████╗  ██╔████╔██║██║   ██║███████╗
██║╚██╔╝██║██╔══╝  ██║╚██╔╝██║██║   ██║╚════██║
██║ ╚═╝ ██║███████╗██║ ╚═╝ ██║╚██████╔╝███████║
╚═╝     ╚═╝╚══════╝╚═╝     ╚═╝ ╚═════╝ ╚══════╝
Version 0.18.2 has been started on port 5230
---

See more in:
👉Website: https://usememos.com
👉GitHub: https://github.com/usememos/memos
---
2024-01-30T13:06:59Z latency=11.123885ms method=POST uri=/memos.api.v2.InboxService/ListInboxes status=200 error=
2024-01-30T13:06:59Z latency=16.491542ms method=POST uri=/memos.api.v2.TagService/ListTags status=200 error=
2024-01-30T13:06:59Z latency=33.456409ms method=POST uri=/memos.api.v2.MemoService/GetUserMemosStats status=200 error=
2024-01-30T13:06:59Z latency=3.093441ms method=POST uri=/memos.api.v2.InboxService/ListInboxes status=200 error=
2024-01-30T13:06:59Z latency=3.086939ms method=POST uri=/memos.api.v2.TagService/ListTags status=200 error=
2024-01-30T13:06:59Z latency=25.677201ms method=POST uri=/memos.api.v2.MemoService/GetUserMemosStats status=200 error=
2024-01-30T13:07:28Z latency=6.95895ms method=POST uri=/memos.api.v2.MemoService/CreateMemo status=200 error=
2024-01-30T13:07:31Z latency=3.367836ms method=POST uri=/memos.api.v2.MemoService/CreateMemo status=200 error=
2024-01-30T13:07:33Z latency=2.942146ms method=POST uri=/memos.api.v2.MemoService/CreateMemo status=200 error=
2024-01-30T13:07:34Z latency=3.157465ms method=POST uri=/memos.api.v2.MemoService/CreateMemo status=200 error=
```

**Comment by m1732948116** [comment]
我也是，回退0.18.2以为正常了，谁知道第二天就写不了新的memo。又回到三天前的备份，还好新增的数据不多，自己手动加上去了

**Comment by Derekmini** [comment]
那您这个还挺好，有备份，我没按照平常的方式备份，这是直接更新的，所以现在在尝试并等待是否有其他可行的处理方式。

**Comment by m1732948116** [comment]
v0.19.0版本我还试过删除所有数据重新注册，新建memo还是一样的卡死。很奇怪为啥只有几个人报bug

**Comment by specoff** [comment]
v0.19.0 use 11Gb of memory! My NAS is running out of memory and only a reboot helps.

**Comment by ixxmu** [comment]
you can find the solution in here!
you can find the solution in here!
you can find the solution in here!

https://github.com/usememos/memos/pull/2874
