### ISSUE TITLE
RSS lost the hyperlink

### ISSUE THREAD

**Issue by qkxie** [usememos/memos#2851]
### Describe the bug

When I paste a url in to a memo (without markdown format). The url is lost in Rss Feed.

### Steps to reproduce

1. create a new memo with any text and then paste a url directly.
2. open rss

### The version of Memos you're using

0.18.2

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/134578340/c103850d-7389-469c-8715-0bc03fd8a083)
![image](https://github.com/usememos/memos/assets/134578340/128f2777-4055-4c8d-8890-b7d7aa79115d)

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/2b7bd47b443c32279ae4ff00bc2cba37c235977d
