### ISSUE TITLE
content too long

### ISSUE THREAD

**Issue by JIFVGWHvAseSovQ** [usememos/memos#2852]
### Describe the bug

Memos can not be saved with error content too long, 0.18.1 can be saved normally, request to restore the limit, or customize the save size

### Steps to reproduce

Memos can not be saved with error content too long, 0.18.1 can be saved normally, request to restore the limit, or customize the save size

### The version of Memos you're using

0.19.0

**Comment by boojack** [comment]
Reference to https://github.com/usememos/memos/issues/2748
