### ISSUE TITLE
0.18.2，出现以下错误

### ISSUE THREAD

**Issue by liu7526539** [usememos/memos#2856]
### Describe the bug

constraint failed: UNIQUE constraint failed: memo.resource_name (2067)

### Steps to reproduce

前一条还好好的，下一条就出问题了

### The version of Memos you're using

0.18.2

**Comment by boojack** [comment]
It looks like you are using the v0.19.0 database schema, so you can:
* use the v0.18.x database if you have backup;
* upgrade memos to v0.19.0;

**Comment by liu7526539** [comment]
> 看起来您正在使用v0.19.0数据库模式，因此您可以：>> * 如果有备份，请使用v0.18.x数据库；> * 将备忘录升级到v0.19.0；
谢谢！请问升级到0.19.0是需要等一段时间让数据库转换完了再使用么？
