### ISSUE TITLE
Enhancements - Customize Tab Appearance

### ISSUE THREAD

**Issue by devanteweary** [usememos/memos#2862]
### Describe the solution you'd like

Awesome app and just starting to use it.
Wanted to suggest a few enhancements.

- Ability to change the color of tabs.
- Ability to set background image of tabs.
- Ability to assign colors to tags. (so the tab changes to that color when assigning the tab)

![memos_colors](https://github.com/usememos/memos/assets/29805497/dadd49b4-c170-4331-b714-b7980cd792f5)

### Type of feature

User Interface (UI)

### Additional context

Easy to quickly distinguish tabs.

**Comment by boojack** [comment]
> Easy to quickly distinguish tabs.

I think you mean **tag**, not tab? Since each memo is capable of containing multiple tags, this guess of yours maybe won't work either.

**Comment by devanteweary** [comment]
> > Easy to quickly distinguish tabs.
> 
> I think you mean **tag**, not tab? Since each memo is capable of containing multiple tags, this guess of yours maybe won't work either.

Whoops yeah tags! ha

Well in that case, just the ability to manually set the color maybe? 🍻
