### ISSUE TITLE
Enhancement - Tab Arrangement

### ISSUE THREAD

**Issue by devanteweary** [usememos/memos#2863]
### Describe the solution you'd like

Requesting the following features:

- Grid view: A view to see many notes on the screen.
- Memo length: Ability to set maximum length of memo and then if you click on it, it expands.

![memos_grid](https://github.com/usememos/memos/assets/29805497/27033368-d2b1-438b-a3cf-b573af1dc21e)

### Type of feature

User Interface (UI)

### Additional context

Make it easier to see notes.
For instance, if I have a looooooong note, I have to keep scrolling to see the others.

**Comment by MehadND** [comment]
> Grid view: A view to see many notes on the screen.

- Not sure if it will look any good cause a memo could have images/videos/other memos or embedded content. Therefore, It will be a lot of work to have a provide good UI/UX.


> Memo length: Ability to set maximum length of memo and then if you click on it, it expands.
- That is a good suggestion, I'm working on it at the moment.....

#### Before

https://github.com/usememos/memos/assets/34424878/3168b12f-a71b-429b-aad1-2b96aeca7b6c

#### After

https://github.com/usememos/memos/assets/34424878/8df2ccca-8c06-47a8-9ffd-6f8713b2d4d4
