### ISSUE TITLE
Warn user if sharing private/workspace memos

### ISSUE THREAD

**Issue by NtWriteCode** [usememos/memos#2868]
### Describe the solution you'd like

It would be great if the memos would notify me if I'm trying to share a private/workspace memos, because to unauthenticated users it'll return error code 403 (obviously).

So, it'd be good to either offer changing visibility to public
or
create a link with a special token to allow seeing that post only regardless of publicity setting.

### Type of feature

User Experience (UX)

### Additional context

I'd prefer the latter solution, since it may let me share private memos with unauthenticated friends and I wouldn't have to make it entirely public.

**Comment by Betyho** [comment]
#2942

**Comment by Betyho** [comment]
Perrilla
