### ISSUE TITLE
"R2.dev subdomain" would expose the images to public?

### ISSUE THREAD

**Issue by zwpaper** [usememos/memos#2871]
### Describe the bug

R2 S3 storage must enable the R2.dev subdomain, but this seems to be enabling s3 images to public, am I understanding the R2.dev subdomain right?

if so, it would be better not to set that.

without setting that, the images in r2 are not accessible.

### Steps to reproduce

following the r2 docs

### The version of Memos you're using

build from main

**Comment by xwjdsh** [comment]
I think https://github.com/usememos/memos/pull/2855 is you're looking for.
