### ISSUE TITLE
Respect DO_NOT_TRACK environment variable

### ISSUE THREAD

**Issue by ribtoks** [usememos/memos#2872]
### Describe the solution you'd like

Currently memos is tracking user behaviour by default. Would be nice respect environment variable DO_NOT_TRACK and disable tracking if it has a non-empty value.

### Type of feature

Other

### Additional context

Tracking users by default is not privacy-friendly, what memos is advertising to be.

**Comment by boojack** [comment]
Reference to https://www.usememos.com/docs/advanced-settings/metrics
