### ISSUE TITLE
The month of the timeline is still wrong

### ISSUE THREAD

**Issue by tigerzioo** [usememos/memos#2873]
### Describe the bug

It is still show 12/2023 when clicking the timeline. And the date cannot be clicked. No way to pick up a date.

### Steps to reproduce

Click timeline

### The version of Memos you're using

0.19.0 MySQL version

### Screenshots or additional context

![Memos19 0](https://github.com/usememos/memos/assets/148376507/04978d5c-f6cd-43fc-9759-7f61ab41491e)

**Comment by tigerzioo** [comment]
Upgraded from 18.1 to 19.0. MySql version. I don't see other people has this issue. I am wondering if it is related to MySql version.

**Comment by boojack** [comment]
Fixed in https://github.com/usememos/memos/pull/2861
