### ISSUE TITLE
Can not search the memo of comment

### ISSUE THREAD

**Issue by gujin03** [usememos/memos#2877]
### Describe the bug

You can look the steps from the pictures clearly

### Steps to reproduce

<img width="347" alt="image" src="https://github.com/usememos/memos/assets/38389059/d1282cd6-87fa-4ba9-9b3b-c822de352a88">
<img width="315" alt="image" src="https://github.com/usememos/memos/assets/38389059/8d5fde97-93a2-44c9-a402-b9f6de281df7">
<img width="536" alt="image" src="https://github.com/usememos/memos/assets/38389059/f3e50bff-2cd4-41ac-9941-9da6b267ee54">

### The version of Memos you're using

0.19.0

**Comment by gujin03** [comment]
same as https://github.com/usememos/memos/issues/2834
The last issue is not resolved:(

**Comment by boojack** [comment]
Memo comments are not displayed in the home page. And there is now no page for displaying and searching them.
