### ISSUE TITLE
Problems with uploading images to Cloudflare R2 关于图片上传到Cloudflare R2 的问题

### ISSUE THREAD

**Issue by mengxizhuo** [usememos/memos#2878]
### Type of feature

API

**Comment by wbchn** [comment]
我从我的理解来解释下

1. 从客户端直接上传的方式，AWS S3 [Signed url](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html)或是阿里云 OSS 支持, R2 也有类似实现 [Presigned URLs](https://developers.cloudflare.com/r2/api/s3/presigned-urls/)
2. memos已经使用了 AWS S3 SDK，如果需要实现，剩下的是功能的实现。
3. 看代码中已经有了部分实现，可能没有用在前端页面上传。
```go
// RunPreSignLinks is a background job that pre-signs external links stored in the database.
// It uses S3 client to generate presigned URLs and updates the corresponding resources in the store.
func RunPreSignLinks(ctx context.Context, dataStore *store.Store) 
```

---
以上是临时查看代码得到的，如有错误请指正。

**Comment by wbchn** [comment]
> 我从我的理解来解释下
> 
> 1. 从客户端直接上传的方式，AWS S3 [Signed url](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html)或是阿里云 OSS 支持, R2 也有类似实现 [Presigned URLs](https://developers.cloudflare.com/r2/api/s3/presigned-urls/)
> 2. memos已经使用了 AWS S3 SDK，如果需要实现，剩下的是功能的实现。
> 3. 看代码中已经有了部分实现，可能没有用在前端页面上传。
> 
> ```go
> // RunPreSignLinks is a background job that pre-signs external links stored in the database.
> // It uses S3 client to generate presigned URLs and updates the corresponding resources in the store.
> func RunPreSignLinks(ctx context.Context, dataStore *store.Store) 
> ```
> 
> 以上是临时查看代码得到的，如有错误请指正。

sorry, this is a replicated issue already discussed in #2565

**Comment by mengxizhuo** [comment]
> > 我从我的理解来解释下
> > 
> > 1. 从客户端直接上传的方式，AWS S3 [Signed url](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html)或是阿里云 OSS 支持， R2 也有类似实现 [Presigned URLs](https://developers.cloudflare.com/r2/api/s3/presigned-urls/)
> > 2. memos已经使用了 AWS S3 SDK，如果需要实现，剩下的是功能的实现。
> > 3. 看代码中已经有了部分实现，可能没有用在前端页面上传。
> > 
> > ```go
> > // RunPreSignLinks is a background job that pre-signs external links stored in the database.
> > // It uses S3 client to generate presigned URLs and updates the corresponding resources in the store.
> > func RunPreSignLinks(ctx context.Context, dataStore *store.Store) 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 以上是临时查看代码得到的，如有错误请指正。
> 
> 抱歉，这是 #2565 中已经讨论过的重复问题，并在 #2855 中合并

确实已有讨论，刚刚测试了一下，尽管是添加阿里云OSS和腾讯云COS，都还是会经过服务器中转再上传到OSS / COS 
###### 望开发者能够加入直传的API功能

**Comment by wbchn** [comment]
docker 部署的么？如果是docker，截止现在是 latest 指向 0.19.0 版本，release at 2024-01-28

#2855 在2024-01-29 fa17dce04638dc05b2283afe6bd4db2a840f9e16 合并

等待下个版本，或自行编译再试。
