### ISSUE TITLE
missing tag filter

### ISSUE THREAD

**Issue by dstruck** [usememos/memos#2879]
### Describe the solution you'd like

Is there a way to filter memos that do not have any tags, so that one can easily find the ones where one forgot to add a tag?

### Type of feature

User Interface (UI)

**Comment by MehadND** [comment]
Not sure if it is applicable but one way would be to have a filter called 'uncategorized' that is the default for every memo and it can be changed to other tags before creation. 🤷🏽‍♂️

**Comment by i-iooi-i** [comment]
![image](https://github.com/usememos/memos/assets/1827701/1187ed26-d41e-4db9-896c-4ae306640d67)
yi'qian以前的版本是有“捷径”功能来筛选带有附件的内容，以及筛选没有标签的内容。目前为止，这项功能被删除了。

**Comment by dstruck** [comment]
> Not sure if it is applicable but one way would be to have a filter called 'uncategorized' that is the default for every memo and it can be changed to other tags before creation. 🤷🏽‍♂️

Might be a solution. But probably easier to add a filter by default which will simply query all memos which do not have any tag.

**Comment by dstruck** [comment]
> > Issue is not in English. It has been translated automatically.
> 
> ![image](https://private-user-images.githubusercontent.com/1827701/302074699-1187ed26-d41e-4db9-896c-4ae306640d67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNDgwNTQsIm5iZiI6MTcwNzE0Nzc1NCwicGF0aCI6Ii8xODI3NzAxLzMwMjA3NDY5OS0xMTg3ZWQyNi1kNDFlLTRkYjktODk2Yy00YWUzMDY2NDBkNjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDVUMTU0MjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTcyNDNhN2M5OTljOGIxMDljMDQ3MTY2YmI3NDg2ZTU4MmYwNmRkMzY0ZjRkMTQxMDYzYzhiZWRlYmM3ZjUzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.g0gqRiM9UUOVHb9uXYHV1Rcf80GedftIZfESN3PX_LY) Previous versions of yi'qian had a "shortcut" function to filter content with attachments and content without tags. As of now, this feature has been removed.

Was there a particular reason to remove that functionality?

**Comment by i-iooi-i** [comment]
> > > Issue is not in English. It has been translated automatically.
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/1827701/302074699-1187ed26-d41e-4db9-896c-4ae306640d67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNDgwNTQsIm5iZiI6MTcwNzE0Nzc1NCwicGF0aCI6Ii8xODI3NzAxLzMwMjA3NDY5OS0xMTg3ZWQyNi1kNDFlLTRkYjktODk2Yy00YWUzMDY2NDBkNjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDVUMTU0MjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTcyNDNhN2M5OTljOGIxMDljMDQ3MTY2YmI3NDg2ZTU4MmYwNmRkMzY0ZjRkMTQxMDYzYzhiZWRlYmM3ZjUzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.g0gqRiM9UUOVHb9uXYHV1Rcf80GedftIZfESN3PX_LY) Previous versions of yi'qian had a "shortcut" function to filter content with attachments and content without tags. As of now, this feature has been removed.
> 
> Was there a particular reason to remove that functionality?

https://github.com/usememos/memos/issues/2593
This feature is being re-added and may take some time.

**Comment by Felo-Z** [comment]
> ![image](https://private-user-images.githubusercontent.com/1827701/302074699-1187ed26-d41e-4db9-896c-4ae306640d67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NjE5NzQsIm5iZiI6MTcwOTg2MTY3NCwicGF0aCI6Ii8xODI3NzAxLzMwMjA3NDY5OS0xMTg3ZWQyNi1kNDFlLTRkYjktODk2Yy00YWUzMDY2NDBkNjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDhUMDEzNDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWJlOGFhZWRjZDgwYzQ3NTUzZDQwZTdjOWZlNDhkYWVjOWU5OGI5YTM4NTAxYjUwOWQ0ZGFlMDg4MmZlMzEyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GOeVJqv2U_NyUKWaHSVy1Gm-3CJxZfkWJdQ75xedkZU) 以前的版本是有“捷径”功能来筛选带有附件的内容，以及筛选没有标签的内容。目前为止，这项功能被删除了。

可以分享一下右上角的热力图和搜索的样式吗😍

**Comment by i-iooi-i** [comment]
> > ![image](https://private-user-images.githubusercontent.com/1827701/302074699-1187ed26-d41e-4db9-896c-4ae306640d67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NjE5NzQsIm5iZiI6MTcwOTg2MTY3NCwicGF0aCI6Ii8xODI3NzAxLzMwMjA3NDY5OS0xMTg3ZWQyNi1kNDFlLTRkYjktODk2Yy00YWUzMDY2NDBkNjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDhUMDEzNDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWJlOGFhZWRjZDgwYzQ3NTUzZDQwZTdjOWZlNDhkYWVjOWU5OGI5YTM4NTAxYjUwOWQ0ZGFlMDg4MmZlMzEyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GOeVJqv2U_NyUKWaHSVy1Gm-3CJxZfkWJdQ75xedkZU) 以前的版本是有“捷径”功能来筛选带有附件的内容，以及筛选没有标签的内容。目前为止，这项功能被删除了。
> 
> 可以分享一下右上角的热力图和搜索的样式吗😍

这是以前Memos自带的热力图，不知道为什么在最近的版本里被删掉了。
可以拉取以前版本的Memos镜像，就能看到这项功能了。
