### ISSUE TITLE
feature request: edit problem

### ISSUE THREAD

**Issue by amwihtfei** [usememos/memos#2881]
### Describe the solution you'd like

edit is not very convinent
if can double click and change to edit mode and blur to read mode, 

i am think it will be nice

### Type of feature

User Interface (UI)

**Comment by MehadND** [comment]
> if can double click and change to edit mode and blur to read mode,

What do you mean by this? @amwihtfei

**Comment by boojack** [comment]
Duplicated with https://github.com/usememos/memos/issues/2802
