### ISSUE TITLE
Replace profile page with timeline page

### ISSUE THREAD

**Issue by xwjdsh** [usememos/memos#2882]
### Describe the solution you'd like

The timeline page is a bit of a duplicate of the profile page, which is more stylized, so perhaps the user info and RSS button could be displayed on the timeline page(or based on the url path), and then the profile page can be replaced.

From a developer's point of view, this also helps to reduce redundancy of repetitive logic and is more maintenance-friendly.

### Type of feature

User Interface (UI)

**Comment by i-iooi-i** [comment]
同感，确实在感受上两个页面的功能重叠了。
