### ISSUE TITLE
v0.19和v0.19.1都不能正常使用，卡死

### ISSUE THREAD

**Issue by m1732948116** [usememos/memos#2884]
### Describe the bug

从v0.18.2升级到v0.19查看以前的memo，或者删除所有数据重新注册之后新建memo都会导致页面卡死，并且占用内存异常增大直至系统崩溃。v0.19.1修复了内存问题，但依旧卡死。

### Steps to reproduce

使用dsm自带的docker升级，然后打开memos主页

### The version of Memos you're using

v0.19.1

**Comment by m1732948116** [comment]
补充一下，从保留数据v0.18.2升级到最新的v0.19.1内存不会异常，倒是删除数据重新注册账户发布memo内存依旧异常升高导致系统崩溃

**Comment by boojack** [comment]
Maybe related with https://github.com/usememos/memos/issues/2883
