### ISSUE TITLE
Sort notes

### ISSUE THREAD

**Issue by ivanswip** [usememos/memos#2887]
### Describe the solution you'd like

Good afternoon, can you please tell me if a tree view of notes is considered in the future?

### Type of feature

User Interface (UI)

**Comment by MehadND** [comment]
@ivanswip can you please elaborate or possibly give examples of what you mean by tree view of notes

**Comment by ivanswip** [comment]
![IMG_0619](https://github.com/usememos/memos/assets/61511372/6c103398-0461-4eca-8b82-57711c97b9f7)
Something like this
In practice this can be folders, but it can also be a note in a note or a tag in a tag , for example in bear notes the tag can be #one/two/three.
