### ISSUE TITLE
Old memos no longer retreivable

### ISSUE THREAD

**Issue by meldarionqeusse** [usememos/memos#2888]
### Describe the bug

 When I am trying to retrieve very old notes by filter tags or fetching more notes from a years or so ago it remains fetching data for ever until server crashes (I am using a rpi4 4gb ram)
![image](https://github.com/usememos/memos/assets/21668964/5f2d541b-e770-40f2-91bb-023e05f08ea3)

### Steps to reproduce

- Upgraded from v16.0.1 to v0.19.0
- Filter tag which contains memos from July last year
- Stays fetching more data until server crashes require to physically restart

### The version of Memos you're using

 0.19.0

**Comment by boojack** [comment]
Provide more context? Maybe some logs from the requests from browser or server-side?

**Comment by jkjoy** [comment]
俺也一样

**Comment by boojack** [comment]
Maybe related with https://github.com/usememos/memos/issues/2895
