### ISSUE TITLE
Unable to create new memo: constraint failed: UNIQUE constraint failed: memo.resource_name (2067)

### ISSUE THREAD

**Issue by erbanku** [usememos/memos#2889]
### Describe the bug

Suddenly, I was unable to create a memo. Whenever I try to create a new one, it says, "constraint failed: UNIQUE constraint failed: memo.resource_name (2067)." Why did this happen? And how to fix it.

I think this may be a database-related problem. 

### Steps to reproduce

I don't know how to reproduce the issue.

### The version of Memos you're using

v0.18.2

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/79493862/a0fa6cdc-e592-45f6-8001-6f74c99696f6)

**Comment by boojack** [comment]
Reference to https://github.com/usememos/memos/issues/2856#issuecomment-1914564489
