### ISSUE TITLE
Show fixed amount of characters per-note (add show more..) 

### ISSUE THREAD

**Issue by bestrocker221** [usememos/memos#2891]
### Describe the solution you'd like

It would be great and nicer if every note is not open by default.

Meaning: if a note is very long, it will be "in the middle" of all the other notes and you would need to scroll down to the end of it.

Having a default number of characters to show per-note could be a nice way of having more "order" in the view, with the possibility to just click on a "show more" button to fully open the note.

### Type of feature

User Interface (UI)

**Comment by MehadND** [comment]
@bestrocker221 Please check this [issue](url). And this [discod convo](https://discordapp.com/channels/1017113925776588902/1045138348165050409/1202312946378604625).

**Comment by bestrocker221** [comment]
Hi @MehadND , both links you posted are not valid.

**Comment by MehadND** [comment]
Sorry about that please check this [PR](https://github.com/usememos/memos/pull/2913)
