### ISSUE TITLE
Filter on url not working

### ISSUE THREAD

**Issue by xwjdsh** [usememos/memos#2893]
### Describe the bug

Can't get the content correctly through the filter on the URL.

### Steps to reproduce

1. Go to the demo site's profile page and apply tag filters.
<img width="1056" alt="image" src="https://github.com/usememos/memos/assets/11025519/bb75150d-f3f8-41af-b4c4-51f5aaac3a4e">

2. Copy the URL `https://demo.usememos.com/u/memos-demo?tag=Hello` and request again, the url becomes `https://demo.usememos.com/u/memos-demo` with unexpected results.
<img width="1056" alt="image" src="https://github.com/usememos/memos/assets/11025519/522424da-a3e9-4313-8eeb-0b032bc36563">

### The version of Memos you're using

0.19.1

### Screenshots or additional context

Related: https://github.com/usememos/memos/issues/2777

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/374f3f7d9684b8a692e9a82204fb6a9cc61b7984

**Comment by erauner12** [comment]
Nice catch! When do we plan on putting this fix in a release?
