### ISSUE TITLE
After upgrade to v19.0, telegram bot not working

### ISSUE THREAD

**Issue by davidluan** [usememos/memos#2894]
### Describe the bug

After I upgrade my memos to v19.0, the telegram bot is not working

### Steps to reproduce

1. create a post
2. the telegram channel didnot receive any post notification

### The version of Memos you're using

19.0

**Comment by boojack** [comment]
Cannot reproduce.

<img width="518" alt="image" src="https://github.com/usememos/memos/assets/24653555/24159395-6728-494d-ac7e-baed6c522125">
