### ISSUE TITLE
After upgrade to v19.0, img for markdown can not used.

### ISSUE THREAD

**Issue by penndu** [usememos/memos#2895]
### Describe the bug

if the word of markdown include img form, the page can not loaded.

### Steps to reproduce

1. open the memos web page
2. waiting for page load
3. page down

### The version of Memos you're using

0.19.0

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/46226528/8d15b360-3549-4756-987c-c32f83151469)

**Comment by jkjoy** [comment]
俺也一样.无论新装还是升级都是一样的问题.

**Comment by boojack** [comment]
Fixed with https://github.com/yourselfhosted/gomark/commit/f26563ba0069384b54ea1f89137a83f88b577a72
