### ISSUE TITLE
Memory Overflow 内存溢出

### ISSUE THREAD

**Issue by mengxizhuo** [usememos/memos#2897]
#### After updating to a new version, docker memory will overflow.
![image](https://github.com/usememos/memos/assets/132188553/3158ef98-e476-499a-b286-12f39a062eea)
![image](https://github.com/usememos/memos/assets/132188553/5756a090-5789-4640-92fa-276c22e8cba3)
![image](https://github.com/usememos/memos/assets/132188553/87eb4137-4ad2-4bb4-892b-4b308db7dee0)

#### In the old version (0.18), you can insert the uploaded image link in the input box and publish it directly. However, in the new version, submitting the link will cause the memory of the small memory machine to overflow, thus directly exporting the server to crash and restart. Docker displays the highest It can reach nearly 1GB, but normal daily multi-person use will not exceed 100MB.
![memos](https://github.com/usememos/memos/assets/132188553/5f273886-8991-469a-b49c-1c6e57751602)

##### The following small problems may be due to personal settings: the latest version of docker deployed by Pagoda, memos 0.19.1, will not automatically open the container after the server is restarted (other containers will be opened)
![image](https://github.com/usememos/memos/assets/132188553/8fa84925-e7fb-4028-a83c-b835183398f7)

### Steps to reproduce

1.在输入框中插入已上传好的图片链接
2.一提交链接会导致小内存机器内存溢出
3.直接导出服务器死机重启

### The version of Memos you're using

0.19.1

**Comment by jkjoy** [comment]
那只能说明你的机器内存太小了///我的可以达到4G
狗头笑

**Comment by mengxizhuo** [comment]
> ###

刚刚换了个大内存机器，直接跑满4G，这个限制应该是默认的容器内存限制
换句话说，直接跑满了，直接溢出（手动狗头）

**Comment by jkjoy** [comment]
使用最新的0.19.1版本,刚开始点击加载列表会卡死,页面无响应,现在发布一些memo之后竟然正常了.不知道是什么操作

**Comment by boojack** [comment]
Try upgrading to v0.19.1 https://github.com/usememos/memos/releases/tag/v0.19.1
