### ISSUE TITLE
Unexpected Application Error!  invalid language tag: "\"de\""

### ISSUE THREAD

**Issue by MrColumbo** [usememos/memos#2898]
### Describe the bug

when accessing ressources I get this is in the browser

Unexpected Application Error!
invalid language tag: "\"de\""

le/<.children<.children<.children<.children<.children<.children<@https://memos.xyz.org/assets/Resources-dYqHyPSM.js:1:3824
le@https://memos.wagnercloud.duckdns.org/assets/Resources-dYqHyPSM.js:1:3469
Xh@https://memos.wagnercloud.duckdns.org/assets/index-U_hmbaCt.js:75:21707
dj@https://memos.wagnercloud.duckdns.org/assets/index-U_hmbaCt.js:77:3491
Wk@https://memos.wagnercloud.duckdns.org/assets/index-U_hmbaCt.js:77:49345
Vk@https://memos.wagnercloud.duckdns.org/assets/index-U_hmbaCt.js:77:43779
Uk@https://memos.wagnercloud.duckdns.org/assets/index-U_hmbaCt.js:77:43702
Jk@https://memos.wagnercloud.duckdns.org/assets/index-U_hmbaCt.js:77:43542
Ok@https://memos.wagnercloud.duckdns.org/assets/index-U_hmbaCt.js:77:39552
Hk@https://memos.wagnercloud.duckdns.org/assets/index-U_hmbaCt.js:77:38382
Mt@https://memos.wagnercloud.duckdns.org/assets/index-U_hmbaCt.js:62:1731
Wt@https://memos.wagnercloud.duckdns.org/assets/index-U_hmbaCt.js:62:214

### Steps to reproduce

1. go to ressources
2. see error

### The version of Memos you're using

0.19.1

### Screenshots or additional context

[_memos_logs.txt](https://github.com/usememos/memos/files/14152134/_memos_logs.txt)

**Comment by boojack** [comment]
Try to open the page in the incognito window

**Comment by MrColumbo** [comment]
just tried ....still the same.It all started when i tried to add a note with a jpg attachment. Actually after that even the main page does not work anymore but when i archive the note via the mobile client then the main page works again

    Am Sonntag, 4. Februar 2024 um 13:04:28 MEZ hat boojack ***@***.***> Folgendes geschrieben:  
 
 


Try to open the page in the incognito window

**Comment by boojack** [comment]
> Actually after that even the main page does not work anymore but when i archive the note via the mobile client then the main page works again.

The latest `stable` version has fixed it.

**Comment by MrColumbo** [comment]
is there a newer version than 0.19.1 available?

I also get a very similar error when i click on timeline (also icgonito window)

Unexpected Application Error!
invalid language tag: "\"de\""

Me/<.children<.children<.children<.children<.children<@https://memos.xyz.org/assets/Timeline-A3zoYv-t.js:1:6045
Me@https://memos.xyz.org/assets/Timeline-A3zoYv-t.js:1:5668
Xh@https://memos.xyz.org/assets/index-vV9u0Ngf.js:75:21707
dj@https://memos.xyz.org/assets/index-vV9u0Ngf.js:77:3491
Wk@https://memos.xyz.org/assets/index-vV9u0Ngf.js:77:49345
Vk@https://memos.xyz.org/assets/index-vV9u0Ngf.js:77:43779
Uk@https://memos.xyz.org/assets/index-vV9u0Ngf.js:77:43702
Jk@https://memos.xyz.org/assets/index-vV9u0Ngf.js:77:43542
Ok@https://memos.xyz.org/assets/index-vV9u0Ngf.js:77:39552
Hk@https://memos.xyz.org/assets/index-vV9u0Ngf.js:77:38382
Mt@https://memos.xyz.org/assets/index-vV9u0Ngf.js:62:1731
Wt@https://memos.xyz.org/assets/index-vV9u0Ngf.js:62:2141

**Comment by MrColumbo** [comment]
i just fixed it by changing from databas to local filesystem then added a new memo with an image via the app and now everthing seems to work fine
