### ISSUE TITLE
Cannot create a tag?

### ISSUE THREAD

**Issue by rvnkcode** [usememos/memos#290]
I tried some tagging like this, but I couldn't.

![스크린샷 2022-10-14 19 41 45](https://user-images.githubusercontent.com/91442716/195828610-7be449b6-5e5c-4d15-9775-80579050d1fe.png)

**Comment by boojack** [comment]
There should be a space after tag. e.g. `#tagName `

**Comment by rvnkcode** [comment]
Thank you so much! I love this app
