### ISSUE TITLE
Where is API doc?

### ISSUE THREAD

**Issue by Williamrjw** [usememos/memos#2906]
### Describe the solution you'd like

An API doc for other APP.

### Type of feature

Documentation

### Additional context

I'm trying to link to my Iphone.
share to the Memos.

**Comment by boojack** [comment]
https://github.com/usememos/memos/blob/main/api/v2/apidocs.swagger.md

**Comment by KhalfaniW** [comment]
Link is broken

"The main branch of memos does not contain the path api/v2/apidocs.swagger.md"

**Comment by chriscurrycc** [comment]
The links above are broken. Is there a new doc? @boojack

**Comment by KhalfaniW** [comment]
This is what the old linked document was if there is no update https://github.com/usememos/memos/blob/v0.20.0/api/v2/apidocs.swagger.md

It was removed in v0.20.1 

 I don't know anything else

**Comment by RoccoSmit** [comment]
Try https://github.com/usememos/memos/blob/main/proto/gen/apidocs.swagger.yaml

You can copy the content of the file into a online swagger viewer

**Comment by boojack** [comment]
The API reference site: https://memos.apidocumentation.com/reference

**Comment by chriscurrycc** [comment]
Thank you for the quick reply. It would be helpful if this link could be added to the documentation site or the README.
