### ISSUE TITLE
Exported memos invalid zip

### ISSUE THREAD

**Issue by OnscreenProton** [usememos/memos#2907]
### Describe the bug

When opening a zip of the exported user's memos, both 7zip, Windows file explorer, default macOS Archive Utility, and Keka (macOS extraction tool) fail to open the zip, with 7zip unable to open the file as a zip. However, I was able to open the archive in 7zip (and Keka) when I changed the zip into a rar. I was also able to open when I changed the zip into a 7z or a tar file. Not sure why this is.

### Steps to reproduce

1. Download exported zip of user's memos (as part of 0.19.1)
2. Attempt to open archive

### The version of Memos you're using

0.19.1

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/44008357/329ea1d9-bad7-4b06-abe9-d361fa44ab3d)

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/1e07b70d2391c18e1b4eba2a21d21eb5a823ee44
