### ISSUE TITLE
Issue with LiveDemo when I logged in

### ISSUE THREAD

**Issue by abhishekshrestha008** [usememos/memos#2912]
### Describe the bug

When I tried to log in to the live demo feature in the https://www.usememos.com/, it showed error "Cannot read properties of undefined (reading 'replace')".

### Steps to reproduce

1. Go the https://www.usememos.com/
2. Use Live Demo Feature
3. Sign in with the default username and password that get populated.

### The version of Memos you're using

Demo version

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/34973491/81e1e631-4b4b-4402-901a-0a07f83715d8)

**Comment by boojack** [comment]
Thanks for your reporting. The demo site has been redeployed.
