### ISSUE TITLE
Cannot create account when first initial

### ISSUE THREAD

**Issue by fatmeat** [usememos/memos#2915]
### Describe the bug

Cannot create account on first deployment, logo keep loading.

![image](https://github.com/usememos/memos/assets/58129877/46ce8365-aa16-451e-ae5b-e7127d732b05)

### Steps to reproduce

docker run -d \
  --init \
  --name memos \
  --publish 5230:5230 \
  --volume ~/.memos/:/var/opt/memos \
  neosmemo/memos:stable

OS: Linux VM-12-6-centos 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### The version of Memos you're using

docker stable tag

**Comment by boojack** [comment]
Sorry, I can't reproduce it. Maybe provide more logs from browser console or backend?

**Comment by fatmeat** [comment]
Thank you boojack, can you provide guideline where should I get those logs?

I have some example below on docker log
{"time":"2024-02-05T13:31:44Z","latency":"70.416527ms","method":"POST","uri":"/memos.api.v2.AuthService/SignUp","status":200,"error":""}

**Comment by boojack** [comment]
Reference to #2920

**Comment by fatmeat** [comment]
I think it fix the issue, I can create and logon successfully, thank you! @boojack
