### ISSUE TITLE
gomark-mgWxLZdV.wasm为什么这个文件这么大

### ISSUE THREAD

**Issue by zbzzh** [usememos/memos#2917]
### Describe the solution you'd like

更新了新版本后发现这个文件非常大，8.1mb，非常影响加载速度，而且对于小带宽服务器非常不友好，请优化

### Type of feature

User Interface (UI)

**Comment by boojack** [comment]
Duplicated with https://github.com/usememos/memos/issues/2910

**Comment by zbzzh** [comment]
![image](https://github.com/usememos/memos/assets/87306816/217fadc2-53b1-4f3c-b44a-73cfb00aca68)
