### ISSUE TITLE
Initial register failed on v0.19.1

### ISSUE THREAD

**Issue by wemsx** [usememos/memos#2920]
### Describe the bug

When I click the button `register`, a warning occurred on the console and the application is stuck.(No response for long time)

I pulled the image from the official docker repo(both `v0.19.1` and `latest`) and run it. But during the initialization process, the application seem crashed somehow. I've retried for several times. It doesn't happen on v0.18.1.
Maybe the web page called the wrong api?

ps: I didn't know how to find the container's log.Sorry for that.

### Steps to reproduce

1. simply use docker to start the application
2. initialize with registering
3. click the button, then that's it

### The version of Memos you're using

v0.19.1

### Screenshots or additional context

![the console](https://github.com/usememos/memos/assets/84974015/cde8977e-a3af-4a5a-b456-04d08c4bf7df)

**Comment by boojack** [comment]
Maybe fixed with https://github.com/usememos/memos/commit/46ea16ef7e5c4ed2731fe7842ae22f477c42678e

Could you pull the latest `stable` image and try again?

**Comment by wemsx** [comment]
> Maybe fixed with [46ea16e](https://github.com/usememos/memos/commit/46ea16ef7e5c4ed2731fe7842ae22f477c42678e)
> 
> Could you pull the latest `stable` image and try again?

It seems resolved, thank you.
