### ISSUE TITLE
Timeline page, width issue when referencing other Memo

### ISSUE THREAD

**Issue by wizcabbit** [usememos/memos#2921]
### Describe the solution you'd like

In the timeline page, when referencing another longer Memo, the CSS style will encounter an issue, where the right border exceeds the boundary.

without reference
![image](https://github.com/usememos/memos/assets/7270910/94a2c3c4-d796-48e6-ab21-c65f8a44843a)

with reference
![image](https://github.com/usememos/memos/assets/7270910/c1e873a3-43b4-457e-b475-59643936737a)

### Type of feature

User Interface (UI)

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/25efc33b24bb8853aabc2dd9252febca3ab963e8
