### ISSUE TITLE
Code block without language tag broken memos

### ISSUE THREAD

**Issue by xinfli** [usememos/memos#2922]
### Describe the bug

I created a memo with a code block, then every time I open my memos, it shows an error `Unexpected Application Error!
invalid language tag: "null"`, I got no chance to fix it.

### Steps to reproduce

1. Create a memo with content like this (Please replace "\\\```" with "```"):
```
# Title
\```
The code block
\```
```
3. Save the memo

Memos will show error message `Unexpected Application Error!
invalid language tag: "null"`

### The version of Memos you're using

0.19.1

### Screenshots or additional context

Is there any workaround that I can fix the memo manually? thanks!

**Comment by MrColumbo** [comment]
reminds me on this one which i still experience - it help when i remove the memo via the mobile app
#2898
....but then timeline and resources do work even after i deleted the memo via the app

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/a76b86f18a2ca8092bd3e1c705b99b5392e500d1
