### ISSUE TITLE
Code block width overflow in old iOS

### ISSUE THREAD

**Issue by lhuanyun** [usememos/memos#2923]
### Describe the bug

代码块超出
![6252468C-9D98-43FB-AD56-54CAC4997F75](https://github.com/usememos/memos/assets/20707383/94f4fa3f-da4d-47e7-9de8-86a616063212)

### Steps to reproduce

就是这样，如图

### The version of Memos you're using

last lastest

**Comment by lhuanyun** [comment]
![E91E2D85-614A-4CBA-A96C-124CE07139C6](https://github.com/usememos/memos/assets/20707383/23427425-bf30-455e-b24d-f9fbd4a76fbd)

**Comment by boojack** [comment]
Sorry, I don't have old devices, please feel free to submit a PR.

**Comment by lhuanyun** [comment]
I am very amateur, I hope the master will come to answer

**Comment by lhuanyun** [comment]
它解决了。
```

.word-break {
    overflow-wrap: break-word;
    word-break: normal;
}

```
