### ISSUE TITLE
getMemo by id in API V2  not work

### ISSUE THREAD

**Issue by 1wingedangel** [usememos/memos#2924]
### Describe the bug

我阅读了一遍 API相关的文档（ https://github.com/usememos/memos/blob/main/api/v2/apidocs.swagger.md ）,测试 `/api/v2/memos` 的GET请求能够正常获取memos信息，但是 `/api/v2/memos/{id}` 却报404错误：

```
{"code":5, "message":"memo not found", "details":[]}
```

然后文档继续往下翻后发现了 `/api/v2/memos/{name}` ，试了后能够正常返回对应memo的信息。

现在的问题是，`/api/v2/memos/{id}` 是不是已经不再使用？但是如果不再使用的话，`/api/v2/memos/{id}/comments` 、 `/api/v2/memos/{id}/relations` 和 `/api/v2/memos/{id}/resources` 却也还是用的 `{id}` ，会造成一定的混乱。

我希望要么统一都用id或者name，要么更新一下文档的描述。

### Steps to reproduce

1. 进行上述的GET请求 `http://memos.site/api/v2/memos` 。我用 quicker 发起了GET请求。能够正常返回memos数据。
2. GET请求 `http://memos.site/api/v2/memos/66` (已存在的memo的id)，返回了404。
3. GET请求 `http://memos.site/api/v2/memos/abcdefghijkl`（已存在的memo的name）, 正常返回memo信息。

### The version of Memos you're using

0.19.1

**Comment by doylecnn** [comment]
原因：自 https://github.com/usememos/memos/commit/8382354ef70098162bd7c93cf5d164c026aa3816#diff-3a5c5d01f39f818e7d0a853984fcb5abd26bdef31466138de9087938b0cc6ccfR36 中增加了 /api/v2/memos/{name} 与原本的 /api/v2/memos/{id} 冲突
参考：https://stackoverflow.com/a/68710267 ，后增加的 path pattern 匹配的优先级更高，导致请求调用了错误的方法，最终导致错误。

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/ded8001735c7efbd0ae1d11ee6431771523db7c8
