### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by AYA-123** [usememos/memos#2927]
### Describe the solution you'd like

It would be great to have an android version of the app - perhaps synced via some sort of cloud system to your computer - so you can easily create memo on phone, then open computer where you left off

### Type of feature

User Experience (UX)

**Comment by tianheg** [comment]
Maybe you want this https://github.com/mudkipme/MoeMemosAndroid

**Comment by AYA-123** [comment]
Thanks very much!
