### ISSUE TITLE
Pinned message is not working on the explore page only on the user page

### ISSUE THREAD

**Issue by mariushosting** [usememos/memos#2929]
### Describe the bug

Pinned message is not working on the explore page only on the user page

### Steps to reproduce

Pin a message. The message will be visible only on the admin page or the user page but not on the public explore page.
Pinned message is visible here: https://blog.mariushosting.com/u/mariushosting
Pinned message disappear on explore page: https://blog.mariushosting.com/explore

### The version of Memos you're using

0.19.1

**Comment by boojack** [comment]
Pinned message is only working for yourself not public exploration.
