### ISSUE TITLE
更新报错：update mask is required

### ISSUE THREAD

**Issue by tianyunperfect** [usememos/memos#2930]
### Describe the bug

docker最新版本，无法更新，报错截图：
![image](https://github.com/usememos/memos/assets/23491291/75e324f4-1c45-45db-9254-46625b5fc19e)

### Steps to reproduce

1、编辑一个文档
2、点击保存

### The version of Memos you're using

v0.19.1

**Comment by boojack** [comment]
Cannot reproduce in the demo site. Maybe pull the latest image again?

**Comment by tianyunperfect** [comment]
我用的就是最新的image镜像，neosmemo/memos:latest，这个地址不对吗？第一次新建文档没有问题，但是无法更新，请问我该如何排查问题，使用的是mysql数据库。

**Comment by tianyunperfect** [comment]
> Cannot reproduce in the demo site. Maybe pull the latest image again?

![image](https://github.com/usememos/memos/assets/23491291/5d6fcef1-9344-4662-bace-82735faaef9c)

**Comment by tianyunperfect** [comment]
好像是浏览器缓存问题，已解决
