### ISSUE TITLE
Memos cannot be properly embedded in specific scenarios.

### ISSUE THREAD

**Issue by gujin03** [usememos/memos#2932]
### Describe the bug

![image](https://github.com/usememos/memos/assets/38389059/1cc58759-d70a-4d88-b9f2-bfc0aa579498)
![image](https://github.com/usememos/memos/assets/38389059/9de516fd-1e89-40e7-ae52-ea24ab89d972)

### Steps to reproduce

Most memos can be embedded, but some memos cannot be embedded. The difference between them is not found. Please locate the bug. Thank you.

### The version of Memos you're using

0.19.1

**Comment by boojack** [comment]
> Most memos can be embedded, but some memos cannot be embedded. The difference between them is not found. Please locate the bug. Thank you.

Provide the content that causes errors?
