### ISSUE TITLE
docker build time error

### ISSUE THREAD

**Issue by voctot** [usememos/memos#2939]
### Describe the bug

19.82 store/db/sqlite/sqlite.go:13:2: modernc.org/sqlite@v1.28.0: Get "https://storage.googleapis.com/proxy-golang-org-prod/966630c75881099b-modernc.org:sqlite-v1.28.0.zip?Expires=1707487199&GoogleAcce
ssId=gcs-urlsigner-prod%40golang-modproxy.iam.gserviceaccount.com&Signature=D7nwkhCSyaJEhsy8nPASVhVyXda5NLaMueCBGVwPEW7S5UMonH406Raz51SVCttooEPgGgpj1b%2B0PNDty%2FJO1BBzVCz9WfB3KazX40g2o5j3ssknBbN5x5WiD
xNkleAnL5ahE3f8y3tSD48LC8TwuV8VbFmb6Xi2eDAJFOtrvEI59jqntkmjxGGFzbaqxlOnuntrnALYSdwv%2BWVdDpIeRth4HEVPY5dEyGYqrBCTj%2Fyi1seuZCYSQfrtgKWdgY1FEBl847TQpNdb17pY1ApprF7ughwBIS6OYptbtJEB4W2CxuV%2Bx15hTSH8NrOKIVDJNiTUzfWel94NkPvanvhygg%3D%3D": dial tcp 0.0.0.0:443: connect: connection refused
------
Dockerfile:19
--------------------
  17 |     COPY . .
  18 |
  19 | >>> RUN CGO_ENABLED=0 go build -o memos ./bin/memos/main.go
  20 |
  21 |     # Make workspace with above generated files.
--------------------
ERROR: failed to solve: process "/bin/sh -c CGO_ENABLED=0 go build -o memos ./bin/memos/main.go" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/default/default/tbzf5va17cfa9tgcxzl3m0cq7

### Steps to reproduce

1. docker build -t demo .
2. This bug occurred

### The version of Memos you're using

The latest version

### Screenshots or additional context

![1707404333036](https://github.com/usememos/memos/assets/36097179/fadd600b-feb6-4b2b-b0c5-a15e7de25fb9)

**Comment by boojack** [comment]
> dial tcp 0.0.0.0:443: connect: connection refused
