### ISSUE TITLE
Add HTTPS support?

### ISSUE THREAD

**Issue by Sn0whax** [usememos/memos#2944]
### Describe the solution you'd like

Just wondering if it's a possibility to add HTTPS support or if I'm just missing it.
Thanks so much, love the app!

### Type of feature

Other

### Additional context

Https is a nice step forward for security.

**Comment by linchen1987** [comment]
I think https is a ability of the web service gateway layer and does not need to be supported in the service itself

Maybe You can use services similar to https://www.cloudflare.com/ or https://ngrok.com/ to add a layer of https proxy to memos itself.
