### ISSUE TITLE
Standalone App

### ISSUE THREAD

**Issue by sbehrends** [usememos/memos#2949]
### Describe the solution you'd like

Have anyone consider building Memos as a cross-platform standalone application?

> A privacy-first, lightweight note-taking service. Easily capture and share your great thoughts.

This statement sounds great, but self-hosting could still be a challenge for some users.

It would be neat to have a simple local application installed that can support any user, and really scale up Memos usage.

[Wails](https://wails.io/) seems to be a solution that could be a perfect fit, since it allows a backend run in Go (same language as this service backend), and Frontend with React. Finally it can be compiled and distributed for Mac/Linux/Windows.

Any thoughts?

### Type of feature

Other

**Comment by MehadND** [comment]
@sbehrends if I'm not wrong there are already apps on different platforms, such as
[For Desktop & Mac](https://github.com/xudaolong/memos-desktop)

and pretty sure there is an android and ios app too.

do you mean something like this or do you wish to have an official app for each platform?

**Comment by sbehrends** [comment]
I was thinking as an official app for the platform.

Would be single-user only, no docker, no cloud.
Just local sqlite, using same backend in Go, and same UI, but with slightly different bundling.

[memos-desktop](https://github.com/xudaolong/memos-desktop) sounds like the project, but does not seem to be updated (according to issue reported and last commit a month ago). That repo seems to use Electron, and not sure how it handles the backend, seems to have the binary of `memos` inside. I tried to download it but I only get a white screen.

[Wails](https://wails.io/) supports Go out of the box for the backend, so it could even compile `memos` source code.

**Comment by MehadND** [comment]
does it also supports android & ios build?

**Comment by sbehrends** [comment]
It does not

**Supported Platforms**
Windows 10/11 AMD64/ARM64
MacOS 10.13+ AMD64
MacOS 11.0+ ARM64
Linux AMD64/ARM64
