### ISSUE TITLE
Can`t change the service name in chinese .

### ISSUE THREAD

**Issue by baichaohua** [usememos/memos#2951]
### Describe the bug

I  run the memos with docker-compose , I`d like to change the service name in chinese , but I found that it can`t be saved .

### Steps to reproduce

1. Click 'setting'.
2. Click 'System'
3. edit the "service name" in  chinese .
4. Click the save button , nothing happened .

### The version of Memos you're using

0.19.1

**Comment by boojack** [comment]
Cannot reproduce. Please show more logs about the error?

<img width="1007" alt="image" src="https://github.com/usememos/memos/assets/24653555/57bd8175-236c-4d62-bb16-71c4a72a34d2">
