### ISSUE TITLE
Click "more" on Android Firefox would toggle pin/unpin of the memo

### ISSUE THREAD

**Issue by LumenYoung** [usememos/memos#2952]
### Describe the bug

On the android firefox, when clicking the three dot icon on each memos. There is a chance (high chance in my case) to pin/unpin the memo. No false click involved. 

I've tested it on the chrome android as well, and didn't have such problem. I can provide more testing on other case if it helps for diagnose.

### Steps to reproduce

1. Open the memo service (logged in) at Android firefox browser.
2. click three dot icon for arbitrary memo.
3. There is a chance that the memo is unpinned (when its pined) or pinned (when vice versa) 

### The version of Memos you're using

0.19.1

**Comment by boojack** [comment]
Maybe it has been fixed with the latest version, please try again in https://demo.usememos.com

**Comment by LumenYoung** [comment]
> Maybe it has been fixed with the latest version, please try again in https://demo.usememos.com

Thanks Steven, I had a brief testout and this problem really didn't take place! 

Out of curiosity, is the demo following the branch rather than release? My instance is at least release but quiet different from the demo.

**Comment by boojack** [comment]
> Out of curiosity, is the demo following the branch rather than release? My instance is at least release but quiet different from the demo.

The demo site is based on the main branch which is the release candidator.
