### ISSUE TITLE
Allow Disabling Password without Enabling SSO

### ISSUE THREAD

**Issue by Radicitus** [usememos/memos#2956]
### Describe the solution you'd like

Allow the server host to disable login with password, or allow for auto login for a single user, without needing to enable SSO.

### Type of feature

User Experience (UX)

### Additional context

I already have SSO in front of every app I expose to the internet on my domain through Traefik middlewares, so it is redundant to have SSO or a password built into a Memos instance only I will use and can access using Google SSO. I would appreciate some insight on this. Thanks!

**Comment by boojack** [comment]
> Allow the server host to disable login with password, or allow for auto login for a single user, without needing to enable SSO.

Maybe you want a single user mode or offline mode?
