### ISSUE TITLE
使用2mbps服务器访问需要60秒才能打开主页。

### ISSUE THREAD

**Issue by gitDebianD** [usememos/memos#2957]
### Describe the bug

作者您好，我这边使用linux debian11， 2mbps网络速率，一开始以为是带宽实在太低了影响了(的确也是)，但之后部署了其他项目，包含(1panel的web界面，nginx的web界面等，都能在最慢2秒内打开页面)，通过测试，浏览器没有缓存初次访问memos项目的话，大约需要60秒才能加载出内容，如果在缓存情况下，有时可以做到10秒内，有时又需要30秒内，首页加载非常缓慢，这一点在本地部署的话由于1gbps倒没有任何问题，但是放在云端这类问题特别希望作者能优化，因为很多时候一些轻量化项目没有太多预算成本去购买比较好的服务器，望作者能够优化这个问题，当然这是我自己的问题，谢谢作者提供交流平台和如此好用的开源项目，最后祝作者新年快乐，天天开心。

### Steps to reproduce

使用2m服务器打开memos项目会出现非常缓慢加载，其他项目无此类问题。

### The version of Memos you're using

最新版本

**Comment by gitDebianD** [comment]
[自动回复]:我设置了自动回复功能，这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Clouder0** [comment]
因为有一个 gomark wasm 文件有 8mb 左右，首次打开没缓存确实非常缓慢。

related issue: https://github.com/usememos/memos/issues/2917

希望以后的版本可以优化。

**Comment by gitDebianD** [comment]
好的，感谢作者的解答，期待在未来的某个版本作者能够优化这个事情，因为他对于上行网速带宽较小用户来说，是一个非常难受的，这么完美的一个项目我经常需要使用，也已经成为了必需品，我用他管理自己的生活带来了很多的方便之处，自从我接触这个项目之后我对他非常的喜爱。

**Comment by boojack** [comment]
Duplicated with https://github.com/usememos/memos/issues/2910
