### ISSUE TITLE
Change Website Favicon

### ISSUE THREAD

**Issue by thedavidweng** [usememos/memos#2958]
### Describe the solution you'd like

Would be great to let the admin have the ability to change website's favicon.

### Type of feature

User Interface (UI)

**Comment by thedavidweng** [comment]
Surprised no one else has a need for this, seems like everyone loves parrots

**Comment by Dubzer** [comment]
you already can, use Settings -> System -> Icon URL

**Comment by thedavidweng** [comment]
> you already can. use Settings -> System -> Server Name -> Icon URL

Oh you're right, the position of this menu item is not very intuitive. I think it can be put to one level above.

**Comment by Dubzer** [comment]
or maybe the setting can be renamed to something like "Server branding"
@boojack fyi
