### ISSUE TITLE
RSS  Disapear 

### ISSUE THREAD

**Issue by TaoChan1005** [usememos/memos#2967]
### Describe the bug

There is no `rss.xml` now
<img width="247" alt="image" src="https://github.com/usememos/memos/assets/42793494/f44ace27-a1d4-4ee8-a19f-dfc7e202a332">

### Steps to reproduce

There is no `rss.xml` now

### The version of Memos you're using

0.19.1

**Comment by boojack** [comment]
Moved to profile page.

<img width="1377" alt="image" src="https://github.com/usememos/memos/assets/24653555/38ee75e8-274d-41b6-898f-f031c8f866f7">
