### ISSUE TITLE
Archiving the user is good but what if we want to delete user, Currently there is no option to delete user so please add that too 

### ISSUE THREAD

**Issue by HakaishinShwet** [usememos/memos#2968]
### Describe the solution you'd like

please add option to delete user from whole record and database his everything be it post or other things should be deleted with that single delete command plus add warning which should be shown after admin click on delete button for particular user so that if by mistake if they clicked on it then it shouldnt get directly deleted but show first warning and then if we continue then it should perma delete 

### Type of feature

Other

### Additional context

:-)

**Comment by boojack** [comment]
You will need to archive the user first. 
<img width="819" alt="image" src="https://github.com/usememos/memos/assets/24653555/7470307e-459f-43bf-9b22-1835fe3498c6">

**Comment by HakaishinShwet** [comment]
@boojack thanks for info :-) btw i didnt read documentation if this info is not mentioned like admin has to first archive user and then only he can delete that user then do add it there too
