### ISSUE TITLE
Backup system can be improved plus Restoration system can be implemented too to make this app awesome and perfect

### ISSUE THREAD

**Issue by HakaishinShwet** [usememos/memos#2969]
### Describe the solution you'd like

In backup system right now we are able to backup individual messages in individual text files and zipping is done over those files and this is decent solution but not the best i would say and since this application is almost perfect for what it is build for and that's why i want it to be perfect in this backup and restoration part too because this is very much important part of app if person wants to migrate his notes which have text and image plus metadata for that notes to similar memos instance but with different url and database and in that if we wanna restore our notes perfectly then  in that case backup has to be made in such a way so that we can backup not just notes but also images which are connected with that particular messages/note and as a whole backup of both text of that note and image of that note should be in one folder and one more file should be in that folder which contains all metadata of that particular note/message like when that note was created and maybe add other thing in that file and these notes text,image,metadata  should be in one particular folder of that note and similarly for other notes same thing should be there  and as a whole we should zip those multiple folders together and then when we restore it then it should be restored with same meta data info like when note was created and at what time note was created and notes text and image should be there as a whole and in this way restoration system should be build in which we can feed one zip file in that zip file there will be folder multiple folders with unique name through which you can identify individual note(note id can be good for this) and in that folder there should be text file which contains note text and image files which corresponds to that particular note if there is any image with it and one file which contains meta data info for that particular notes and when we feed the zip  and it can be automatically extracted and restoration from folders start in sequence or maybe you can think of another way to feed this data so that in sequence folders data can be read and notes can be perfectly restored with text,image and metdata so this will be advance and perfect restoration of all the notes and would make user feel like he is in his own system even tho he is restoring in different memo instance so i hope you get the idea and will be working on it,i believe this  will take time for its implementation but after understanding my point gpt or gemini can  further help you if needed for this idea implementation thats all i can say.
Thanks for your hardwork dev :-)) 

### Type of feature

Other

### Additional context

:-))

**Comment by boojack** [comment]
Backup/restore has nothing to do with the main program, it should be something a third party does. And it shouldn't be put into the main code.
