### ISSUE TITLE
can you please implement trash section in which notes that are recently deleted by us can be stored in that for specific duration(if possible give option to set duration) upto which notes can be there

### ISSUE THREAD

**Issue by HakaishinShwet** [usememos/memos#2970]
### Describe the solution you'd like

it will be helpful feature as if user thought to restore back any important note that he might have deleted due to any reason (for example if user thought he has recreated the same note at the end of the day but actually he didnt created the same one info was slightly similar not same and if he deletes that note then after sometime he scroll back and realized that similar info note was not there then he will regret and wont be able to remember back what he wrote at that time and it wont be good thing so trash can temporary store that deleted note and if user tend to restore back he has specific days to do so and after that it will be automatically removed from trash too and maybe you can give manual rights to user to delete from trash to if they want too.

### Type of feature

User Experience (UX)

**Comment by boojack** [comment]
Archiving is a soft delete that goes in the "trash".

**Comment by HakaishinShwet** [comment]
@boojack yea archive works as trash kind of thing but i actually thought it would be much better to implement in the way i explained that there should be trash section in which (deleted message NOT ARCHIVED MESSAGE) are gone for sometime and duration we can set to auto clear after certain time period and instead of archived section there should be saved notes section in which user can save most important notes in that so that he can quickly find those most valuable ones easily and will be very helpful thing for not just me but for everyone so donot close this issue i request instead open it again and implement in this way it would be much user friendly,take your time on this re implementation and you can fix many important issues if present in app before this one but atleast work on this. Application itself is awesome and user friendly and thats why i am trying to contribute in this way to make it much better for all.

**Comment by HakaishinShwet** [comment]
plus i have post one private message which contains info regarding security vulnerability in security section of this repo do check it out and resolve it too :-) @boojack
