### ISSUE TITLE
使用内嵌方式添加引用时点击确定没有反应

### ISSUE THREAD

**Issue by bfansheng** [usememos/memos#2974]
### Describe the bug

如果选择的是当前页面已经加载的memo没问题，不是的话点击确定没有反应
![image](https://github.com/usememos/memos/assets/16935251/bf603846-4378-4753-87a8-5f24c7c5c597)

### Steps to reproduce

1. 添加引用
2. 选择一个未加载的memo
3. 点击确定

### The version of Memos you're using

0.20.0

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/39bf8505911030f9c47d2e765e52a0484271285e
