### ISSUE TITLE
show comment count

### ISSUE THREAD

**Issue by InfiniteOpen** [usememos/memos#2975]
### Describe the solution you'd like

in my workflow , i'd like to use the comment to link to the relation posts.for conveninece to show the diffrences of the post with comment, in my opinion it suppose to show the comment count of the post

### Type of feature

User Interface (UI)

**Comment by gitkeniwo** [comment]
Same. Also, please consider including comments in search results and the ability to link to a comment, otherwise it's pointless to include tags or post useful extra information in comments, because you would rather append them to the original post for convenience of retrieval, which can make the original post quite lengthy.

**Comment by MehadND** [comment]
@InfiniteOpen so basically you want to have the option to embed comments in memo, right?

**Comment by InfiniteOpen** [comment]
> @InfiniteOpen so basically you want to have the option to embed comments in memo, right?

no,i just need show the post's comment count beside the post title or anywhere else ,to help find the post which has comments aleady. but the @gitkeniwo thought i totally agree

**Comment by MehadND** [comment]
@gitkeniwo @InfiniteOpen Is this something that addresses your needs??

https://discord.com/channels/1017113925776588902/1053904069745442846/1213170156902027326

**Comment by InfiniteOpen** [comment]
> @gitkeniwo @InfiniteOpen Is this something that addresses your needs??
> 
> https://discord.com/channels/1017113925776588902/1053904069745442846/1213170156902027326

sorry, it seems no permission for me to access the link.
