### ISSUE TITLE
markdown语法问题(Grammar issues)

### ISSUE THREAD

**Issue by x2358473** [usememos/memos#2983]
### Describe the solution you'd like

cn:
在0.19之后的版本中，使用markdown的列表或都 -[] 等语法格式后，回车换行后，下一行不会默认上一行的格式，每次都要手动进行输入，之前的0.18是可以的
我不知道这是不是特意改的，只是希望这个能继续保留，不然每行都要重新输入标签语法，挺麻烦的

en:
In versions after 0.19, after using markdown lists or syntax formats such as -[], after carriage return and line feed, the next line will not default to the format of the previous line, and you have to enter it manually every time. It was possible in the previous 0.18
I don't know if this is a deliberate change, I just hope this can be retained, otherwise it will be troublesome to re-enter the tag syntax for each line.

### Type of feature

User Experience (UX)

### Additional context

cn:
因为我主要用来记录日常工作中的事项，经常会用到列表与一些选择框等标签，每条记录都要手动输入
en:
Because I mainly use it to record matters in daily work, I often use labels such as lists and some selection boxes, and each record must be entered manually.

**Comment by boojack** [comment]
Duplicated with https://github.com/usememos/memos/issues/2773
