### ISSUE TITLE
Easire access to currently hidden features in note context menu

### ISSUE THREAD

**Issue by thinkbig1979** [usememos/memos#2984]
### Describe the solution you'd like

It would be great if it took a bit less effort to edit a note for example. 

Currently you have to click on the context menu in the note, and then select 'Edit', which is a bit cumbersome, I would imagine editing is one of the most used features. In fact a few of the items hidden in the context menu on the notes are items that are probably quite frequently used. Having directly accessible Pin, Edit and Share buttons in the note would make for less friction in use. 

### Type of feature

User Interface (UI)

**Comment by MehadND** [comment]
You can double click a memo header and go to memo detail page from their you can access these features more easily

**Comment by MehadND** [comment]
Kindly check [this](https://github.com/usememos/memos/issues/2802#issuecomment-1945228128)

**Comment by webysther** [comment]
Miss so much the edit with double click. :(
