### ISSUE TITLE
Automated deleting expired memos

### ISSUE THREAD

**Issue by Wsine** [usememos/memos#2986]
### Describe the solution you'd like

There is a popular usage for this memos project as a microblogging platform. e.g., https://memobbs.app/

Many microblogging platforms support deleting old posts after a certain period automatically. e.g., mastodon, threads

It would be better if this project can support this feature as well.

### Type of feature

Other

**Comment by MehadND** [comment]
I think a better alternative to this would be to delete the archived memos after a certain amount of times.

**Comment by Wsine** [comment]
Can there be an option to delete all memos or the archived ones only?

**Comment by MehadND** [comment]
> Can there be an option to delete all memos or the archived ones only?

IMO, I think deleting all memos is a bad option to have but a better alternative is to only allow deletion of archived memos.

**Comment by Wsine** [comment]
Based on the context, I mean the option scope is on either all memos or all archived memos but this automated operation is still based on a certain amount of times.
