### ISSUE TITLE
certain text pattern cause memos crash

### ISSUE THREAD

**Issue by jacobtung** [usememos/memos#2991]
### Describe the bug

![](https://imgur.com/xeEFIMf.gif)

### Steps to reproduce

1. text in ****8888;
2. then post.

### The version of Memos you're using

v0.20.0

### Screenshots or additional context

Here is how I rescued my data:
1. copy the .db file;
2. open it using VScode with the SQlite plugin;
3. delete the "****8888"item;
4. replace old .db file with the modified .db file;
5. restart memos docker service.

![](https://i.imgur.com/ti4abFB.jpg)

**Comment by boojack** [comment]
Related with https://github.com/usememos/memos/issues/2988
