### ISSUE TITLE
The prompt sequence of tags needs to be optimized.

### ISSUE THREAD

**Issue by gujin03** [usememos/memos#2994]
### Describe the solution you'd like

![image](https://github.com/usememos/memos/assets/38389059/bcadc84f-5b45-4cd7-9790-45417d633348)
when I input "#to" 
The word "todo" should be preferred to "python" in the normal sense.

### Type of feature

User Interface (UI)

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/222d04fb22ed71ead5712eee7411577ad8f70173
