### ISSUE TITLE
Could not find the language '__mermaid', did you forget to load/include a language module?

### ISSUE THREAD

**Issue by Derekmini** [usememos/memos#2996]
### Describe the bug

Could not render a flowchart in my memo with version tag `stable` (`v0.20.0`).

When I used the Chrome development tool, the problem showed up as:
<img width="298" alt="image" src="https://github.com/usememos/memos/assets/30514323/a549c79f-85d9-4a77-b4c1-e045ba9b7195">

### Steps to reproduce

1. Create a memo with the example:
````
```__mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```
````
2. get this result:
<img width="484" alt="image" src="https://github.com/usememos/memos/assets/30514323/22b0060a-0edb-41e5-b106-c57c0838d35f">

### The version of Memos you're using

Both of the tag v0.20.0 and tag stable

**Comment by boojack** [comment]
Use `mermaid` instead.

**Comment by Derekmini** [comment]
> Use `mermaid` instead.

That's work, thank you!
