### ISSUE TITLE
Why does it take me several seconds to load data when my data is not that much? The requested interface is ListMemos.

### ISSUE THREAD

**Issue by mahaonanStart** [usememos/memos#3002]
### Describe the bug

I opened the homepage and found that fetching data was slow. When I checked the request log, I saw that the ListMemos interface had requested for 4 seconds. What could be the reason?

 I use MySQL as my database, and the latency is very high. The data loads slowly.

### Steps to reproduce

1. Open the homepage
2. Check F12

### The version of Memos you're using

0.19.1

### Screenshots or additional context

<img width="1485" alt="image" src="https://github.com/usememos/memos/assets/44892851/2dc75ec9-7aa0-4e88-b714-b14a26035974">

**Comment by mahaonanStart** [comment]
I use MySQL as my database, and the response time of other interfaces is very fast.

**Comment by cenzhifang** [comment]
Mine too, there is a delay
