### ISSUE TITLE
Data leak: drafts leak between users using the same machine

### ISSUE THREAD

**Issue by cwille97** [usememos/memos#3005]
### Describe the bug

If you start writing a draft and, before submitting or deleting, sign out and a different users signs in, their draft will be populated with your text. I am using Firefox 122.0.1 (64-bit)

### Steps to reproduce

Prerequisites are two user accounts, in my case one was an admin and one was a regular user.

1. Sign into first user and start typing text in the text box. Do not submit.
2. Sign out and sign into the other user.
3. The text box should contain the drafted text from the first user.

This has the potential for unwanted data leak across users on the same machine.

### The version of Memos you're using

v0.20.0

### Screenshots or additional context

https://github.com/usememos/memos/assets/24487628/8d672ce7-4a48-4977-ba3d-b5e475b78479

**Comment by meldarionqeusse** [comment]
This is related to #2331

**Comment by boojack** [comment]
Thanks for the reporting. Fixed with https://github.com/usememos/memos/commit/89a270cedebaa36430d3f5bb9ccacb00e8e06b62
