### ISSUE TITLE
sqlite data migration mysql Bug

### ISSUE THREAD

**Issue by yn-zxj** [usememos/memos#3006]
### Describe the bug

Version(`0.20.0`)： use this command `/usr/local/memos/memos --driver mysql --dsn 'user:password@@tcp(localhost:port)/memos' copydb --from sqlite:///apps/memos/memos_prod.db`，console return 
```sh
Error: unknown flag: --from
.....
goroutine 1 [running]:
main.main()
    /backend-build/bin/memos/main.go:199 +0x2b
``` 

How should this situation be handled ？thanks！

### Steps to reproduce

1.run docker images of memos latest；
2.open terminal；
3.input command `/usr/local/memos/memos --driver mysql --dsn 'user:password@@tcp(localhost:port)/memos' copydb --from sqlite:///apps/memos/memos_prod.db`（User name, password, etc. are hidden）

### The version of Memos you're using

0.20.0

### Screenshots or additional context

<img width="747" alt="image" src="https://github.com/usememos/memos/assets/44137601/92e2d2a3-727f-4599-b364-e5c469193110">

**Comment by boojack** [comment]
The flag has been removed. You should migrate manully.
