### ISSUE TITLE
20.0版本的memos无法在微信内打开

### ISSUE THREAD

**Issue by zbzzh** [usememos/memos#3007]
### Describe the bug

20.0版本的memos无法在微信内打开，而且wasm文件过大bug一直没有修复

### Steps to reproduce

1

### The version of Memos you're using

20.0

**Comment by boojack** [comment]
The demo site(https://demo.usememos.com) works properly in WeChat.

**Comment by zbzzh** [comment]
这个例子用的好像不是最新版的，为什么你的wasm文件那么小
