### ISSUE TITLE
Markdown image width

### ISSUE THREAD

**Issue by gitkeniwo** [usememos/memos#3008]
### Describe the solution you'd like

Would be great if memo's markdown supports specifying image width, as some images are small in size but still take the full width nevertheless when inserted using md syntax.

I know this could be done via stuff like
````html
```__html
<img src="your_pic.jpg" width="200"/>
```
````
but some extra syntactic sugars are always preferred, such as 
- Obsidian flavored syntax: `![alt-text |200](image.jpg)`
- Github flavored syntax: `![alt-text](image.jpg){width=200px}`

### Type of feature

User Interface (UI)

**Comment by MOoo57** [comment]
1. 

> ### **_[](url)``_**

**Comment by gitkeniwo** [comment]
> @gitkeniwo Do you find any solution?
> 
> I logseg, the syntactic sugar is `{:width 300}`

No syntactic sugars provided officially yet, but i do stored the html workaround to Raycast snippets and can quickly insert one when using mac. No solution for mobile input though.
````
```__html
<img src="your_pic.jpg" width="200"/>
```
````
