### ISSUE TITLE
Login auth failed

### ISSUE THREAD

**Issue by aiminchen** [usememos/memos#3009]
### Describe the bug

The web project is run locally, and the server is on the cloud server, which causes the cookie acquisition to fail when logging in. this situation does not exist in Windows, but exists in Mac.
The same situation occurs if the go server and the web server run on different OS
The SignIn() method request is successful, and the response's Set-cookie exists, but the GetAuthStatus() method request fails, and the Set-cookie is gone.
<img width="251" alt="image" src="https://github.com/usememos/memos/assets/15519238/29a41bae-acc2-42a3-a7fd-8646557b5ab4">

### Steps to reproduce

1. open memos login page
2. click the button of login

### The version of Memos you're using

0.20.0

**Comment by refrain1128** [comment]
> 你能提供一些 Web 请求的日志吗？你能提供一些 Web 请求的日志吗？

我现在确定了memos无法登录和1Panel无关，在重装系统后正常运行，直到我刚才重启服务器，又无法登录了，显示“user not found”，我现在怀疑是memos本身的问题。

**Comment by refrain1128** [comment]
> 你能提供一些 Web 请求的日志吗？

[memos-20240303160239.log](https://github.com/usememos/memos/files/14472159/memos-20240303160239.log)

**Comment by refrain1128** [comment]
> Could you provide some logs of the web requests?你能提供一些 Web 请求的日志吗？
![memos无法登录2](https://github.com/usememos/memos/assets/158741597/e5f5da34-a1a1-426d-a648-2c489dbffd5c)
我终于发现问题的原因了😭
详情见[尝试通过Set-Cookie标头设置Cookie时被阻止，因为它具有“Secure“属性，但未通过安全连接发送](https://blog.csdn.net/gusijin/article/details/120541938)
原因是设置了secure属性的cookie只能用https协议发送给服务器，难怪我用https可以登录
文章提供了解决方法为：去掉secure属性
请问怎么去掉secure属性？这是我浏览器的问题还是memos自身的bug？

**Comment by refrain1128** [comment]
> Could you provide some logs of the web requests?你能提供一些 Web 请求的日志吗？

在添加证书之前没有遇到这种无法登录的情况，添加证书之后用http就无法登录了，即使我不使用证书后也无法登录。
而且由于国内的域名不备案无法在公网使用https，现在导致我现在只能在局域网用https使用memos，公网无法使用。
希望尽快解决这个问题。

**Comment by refrain1128** [comment]
更新0.20.1后http可以正常登录了，不知道是bug解决了还是暂时性的
