### ISSUE TITLE
20.0版本在许多浏览器中无法正常打开

### ISSUE THREAD

**Issue by zbzzh** [usememos/memos#3010]
### Describe the bug

20.0版本在许多浏览器中无法正常打开
我测试了小米自带浏览器以及夸克浏览器以及微信内均无法打开, 而官方演示版本似乎不是最新版或有改动，其中wasm文件仅2mb，而官方发行版有7mb
附上我的memos(base64)
aHR0cHM6Ly9tZW1vcy56emguY2M=

### Steps to reproduce

1

### The version of Memos you're using

20.0

### Screenshots or additional context

打开空白，不出现转圈

**Comment by zbzzh** [comment]
请帮我查看一下我的站点 在夸克和手机自带浏览器以及微信内无法打开

**Comment by zbzzh** [comment]
你好，可以回复一下吗，如果你需要截图我可以提供

**Comment by boojack** [comment]
能够在微信里使用，因为资源有限不会去做其它非主流浏览器（小米浏览器等等）的适配，建议使用最新版的 Chrome 浏览器。

![image](https://github.com/usememos/memos/assets/24653555/258ffd7c-d5d1-4591-80c7-bcc282884cb8)

**Comment by zbzzh** [comment]
你好，中国大陆版本的微信内我尝试无法正常打开，微信在中国和海外版是不同的，而你应该知道，微信在中国的使用量是非常巨大的，还有很多安卓手机浏览器也无法打开。我怀疑是否是跟wasm文件的大小有关，文件过大导致被限制，我尝试了你的demo版本在所有浏览器中均可运行，而没有使用gzip的发行版则不行，大部分网站都套用了cdn，如果再使用nginx做反向代理开启gzip后再套用cdn无疑会降低速度，希望可以修复并优化

**Comment by zbzzh** [comment]
Please keep the issue on, I will keep testing it if you update the next version of memos

**Comment by zbzzh** [comment]
no reply？

**Comment by Doradx** [comment]
[mark.js](https://github.com/markedjs/marked)仅有34k，而gomark居然有8M。
何必舍本求末呢？
建议替换为mark.js，或给用户一个选择。
谢谢。
