### ISSUE TITLE
What is the reason for this error? It has been updated several versions and sometimes login is possible and sometimes login is not possible.          

### ISSUE THREAD

**Issue by cenzhifang** [usememos/memos#3011]
### Describe the bug

What is the reason for this error? It has been updated several versions and sometimes login is possible and sometimes login is not possible.          
The log is as follows：
![image](https://github.com/usememos/memos/assets/105171265/07531b99-a932-480e-b205-3f97d1f19878)

 Thank you for your answer。

### Steps to reproduce

This error has always been present during each upgrade

### The version of Memos you're using

v20

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/105171265/07531b99-a932-480e-b205-3f97d1f19878)

**Comment by boojack** [comment]
The logs you provided are correct.
