### ISSUE TITLE
add support for search in the comments

### ISSUE THREAD

**Issue by darkages89** [usememos/memos#3012]
### Describe the solution you'd like

Adding a search function to comments would be super helpful! It can be challenging to find specific information in note comments, and a search feature would make things much easier. Please consider implementing this for a smoother user experience. Thanks!

### Type of feature

Integrations

**Comment by ozls** [comment]
I would also really enjoy this feature. I use notes to ask myself questions and comments to give answers, unfortunately it means my main content is not in the root notes

**Comment by ozls** [comment]
I would still be very interested in this feature, no matter what the stale-bot thinks. I know neither Go nor TypeScript but but I might just learn what I need to make a PR myself if this is not a priority. So even if this is not planned, any idea, remark or suggestion regarding searchable comments is welcome.

**Comment by yinan-c** [comment]
I am interested in for this feature as well!

**Comment by gitkeniwo** [comment]
iirc in the version where comments were first introduced, comments acted just like normal memos and appeared in the timeline and search results, yet this was removed somehow afterwards. 

I kinda get the idea of comments not supposed to appear in the timeline, but there's no point in restricting the search functionality. Hopefully it will be reimplemented.

**Comment by yinan-c** [comment]
Yes, also comments are not opened by "name" ( "name": "xxxxxxxWyyu4KGxxxxxx" , {my_memo_instance_url}/m/{name}) like a regular memo would do.
