### ISSUE TITLE
Unable to opt out of metrics with --metric=false flag (documentation also missing?)

### ISSUE THREAD

**Issue by jeffxt** [usememos/memos#3023]
### Describe the bug

I am unable to start the container when I set the `--metric=false` flag.  When I remove it and re-run my docker-compose, it works perfectly.

In the logs, I am getting `panic` errors.

I used this successfully up until the latest version v0.20.0, at the time of this post.

Also, I noticed the documentation is missing was this page removed?  I see references [in this Github comment here](https://github.com/usememos/memos/issues/2433#issuecomment-1797316081) but it looks the official docs now give a 404 error:  https://www.usememos.com/docs/advanced-settings/metrics

### Steps to reproduce

1.  Have the `--metric=false` flag set in the docker-compose.yml
2. Start the container with `docker-compose up -d` 
3. The container will fail
4. Check the logs, there are `panic` errors
5. Stop the container and remove it with `docker-compose down`
6. Remove the `--metric=false` flag set from the docker-compose.yml
7. Run `docker-compose up -d` again
8. The container starts successfully
9. Unable to check the documentation - looks like it's been removed?  https://www.usememos.com/docs/advanced-settings/metrics

### The version of Memos you're using

v0.20.0

**Comment by boojack** [comment]
Metric service has been removed in v0.20.0
