### ISSUE TITLE
关于页面加载太慢问题.

### ISSUE THREAD

**Issue by yuboabc** [usememos/memos#3025]
### Describe the solution you'd like

我的服务器上传速度很小.但是起初使用memos的时候, 页面几乎是秒开的, 但是自动0.18 还是 0.19版本开始, 我打开页面的速度就非常慢了. 有一个请求加载居然需要 16秒...你们这是修改了什么了?
![PixPin_2024-03-02_20-57-12](https://github.com/usememos/memos/assets/23468825/f0112cbb-b2fc-44e2-8f7c-6d57b5d590c1)

### Type of feature

User Interface (UI)

**Comment by refrain1128** [comment]
因该是你服务器的问题，我没遇到过这种情况

**Comment by yuboabc** [comment]
在之前的老版本上没有这种情况...


| |
陈龙
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年3月3日 00:18 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [usememos/memos] 关于页面加载太慢问题. (Issue #3025) |

因该是你服务器的问题，我没遇到过这种情况

**Comment by zbzzh** [comment]
wasm太大了

**Comment by yuboabc** [comment]
这种情况有解决办法吗?


| |
陈龙
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年3月3日 13:33 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [usememos/memos] 关于页面加载太慢问题. (Issue #3025) |

wasm太大了

**Comment by zbzzh** [comment]
已经很早有人反馈过这个问题了，到现在一直没修复。对于国内小带宽服务器来说最好就是套cdn缓存这些静态文件，或者退回到旧版本，希望下一个版本能有优化

**Comment by yuboabc** [comment]
那好吧...真的是. 我的3M小接口. 要30秒才能打开页面...醉了



| |
陈龙
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年3月3日 13:37 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [usememos/memos] 关于页面加载太慢问题. (Issue #3025) |

已经很早有人反馈过这个问题了，到现在一直没修复。对于国内小带宽服务器来说最好就是套cdn缓存这些静态文件，或者退回到旧版本，希望下一个版本能有优化

**Comment by zbzzh** [comment]
> 那好吧...真的是. 我的3M小接口. 要30秒才能打开页面...醉了 | | 陈龙 | | ***@***.*** | ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年3月3日 13:37 | | 收件人 | ***@***.***> | | 抄送人 | ***@***.***> , ***@***.***> | | 主题 | Re: [usememos/memos] 关于页面加载太慢问题. (Issue #3025) | 已经很早有人反馈过这个问题了，到现在一直没修复。对于国内小带宽服务器来说最好就是套cdn缓存这些静态文件，或者退回到旧版本，希望下一个版本能有优化 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

我也才只有5M，当时直接震惊了，对于国外来说带宽便宜可能无所谓

**Comment by yuboabc** [comment]
问题是用国外的服务器..可能会被墙掉, 还得走代理. 代理的速度也不快....



| |
陈龙
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年3月3日 13:39 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [usememos/memos] 关于页面加载太慢问题. (Issue #3025) |

那好吧...真的是. 我的3M小接口. 要30秒才能打开页面...醉了 | | 陈龙 | | @.*** | ---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年3月3日 13:37 | | 收件人 | @.> | | 抄送人 | @.> , @.> | | 主题 | Re: [usememos/memos] 关于页面加载太慢问题. (Issue #3025) | 已经很早有人反馈过这个问题了，到现在一直没修复。对于国内小带宽服务器来说最好就是套cdn缓存这些静态文件，或者退回到旧版本，希望下一个版本能有优化 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

我也才只有5M，当时直接震惊了，对于国外来说带宽便宜可能无所谓

**Comment by zbzzh** [comment]
> 问题是用国外的服务器..可能会被墙掉, 还得走代理. 代理的速度也不快.... | | 陈龙 | | ***@***.*** | ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年3月3日 13:39 | | 收件人 | ***@***.***> | | 抄送人 | ***@***.***> , ***@***.***> | | 主题 | Re: [usememos/memos] 关于页面加载太慢问题. (Issue #3025) | 那好吧...真的是. 我的3M小接口. 要30秒才能打开页面...醉了 | | 陈龙 | | @.*** | ---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年3月3日 13:37 | | 收件人 | @.> | | 抄送人 | @.> , @.> | | 主题 | Re: [usememos/memos] 关于页面加载太慢问题. (Issue #3025) | 已经很早有人反馈过这个问题了，到现在一直没修复。对于国内小带宽服务器来说最好就是套cdn缓存这些静态文件，或者退回到旧版本，希望下一个版本能有优化 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***> 我也才只有5M，当时直接震惊了，对于国外来说带宽便宜可能无所谓 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

那就套个国内cdn吧，设置好缓存就行了，设置好限额别被刷。
希望作者早日优化吧！

**Comment by qwasfun** [comment]
https://github.com/usememos/memos/issues/2910#issuecomment-1927419981

同为3M带宽，配置gzip后，wasm文件加载时间为4.5秒多，大概5秒多后页面开始有内容展示

![image](https://github.com/usememos/memos/assets/134053124/458b32ec-9803-41a0-bd22-7ee41bb835be)

**Comment by qwasfun** [comment]
目前这样优化一下，仍然还是觉得慢了点，但算是还可以接受吧😂

**Comment by yuboabc** [comment]
5秒, 也是开玩笑的. 这种页面加载要5秒. 谁特么的 会等啊. 1秒打不开就GG, 3秒打不开的页面. 我都直接关闭走人了. 哈哈



| |
陈龙
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年3月3日 14:02 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [usememos/memos] 关于页面加载太慢问题. (Issue #3025) |

#2910 (comment)

同为3M带宽，配置gzip后，wasm文件加载时间为4.5秒多，大概5秒多后页面开始有内容展示

image.png (view on web)

**Comment by boojack** [comment]
Duplicated with #2910
