### ISSUE TITLE
http无法登录、注册，只有https可以

### ISSUE THREAD

**Issue by refrain1128** [usememos/memos#3028]
### Describe the bug

memos 通过环境变量设置成 MySQL 数据库，配置了 OHTTPS 的泛域名证书。
今天把域名证书关闭后发现http加域名无法登录注册，域名加端口和内网ip加端口也无法登录注册，但可以正常浏览/explore页面。
现在只能通过 https 登录，但所有账号都是在设置证书之前注册好的。
并且所有账号通过 http 登录显示“user not found”，清除浏览器缓存后依旧如此。
试过删除容器重新安装也是无法解决问题。

### Steps to reproduce

1.输入账号密码
2.点击登录
3.提示“user not found”

### The version of Memos you're using

0.20.0

### Screenshots or additional context

![Uploading memos无法登录.png…]()

**Comment by refrain1128** [comment]
刚发现注册一直停留在转圈圈的页面，不会显示注册成功，但后台数据库已经创建了相关账号
![1709412620947](https://github.com/usememos/memos/assets/158741597/8c661258-5af0-4b0b-91ea-a7741f7ea511)
![memos数据库](https://github.com/usememos/memos/assets/158741597/81a993f4-eb2a-49a3-a761-f362a2f558f5)

**Comment by refrain1128** [comment]
我在重装linux系统之后，在只安装了1Panel的情况下，在1Panel的应用商店里安装了memos，发现问题并没有消失。
然而在卸载1Panel后，memos可以正常登录注册使用了。
所以我估计问题原因和1Panel最近更新的版本有关。

**Comment by boojack** [comment]
Duplicated with https://github.com/usememos/memos/issues/3009
