### ISSUE TITLE
Mermaid 主页解析显示混乱

### ISSUE THREAD

**Issue by QiTianQingShui** [usememos/memos#3029]
### Describe the bug

输入完成：
![image](https://github.com/usememos/memos/assets/30709259/c578ecb2-a70c-4b24-b433-1116a55e0f68)
重新进入主页：
![image](https://github.com/usememos/memos/assets/30709259/edc46a9d-57f9-4d18-89a5-d675e80229a2)

### Steps to reproduce

1. 输入 mermaid 格式的文本
2. 新建一个Memo 输入，mermaid 格式的文本
3. 刷新 主页

### The version of Memos you're using

v0.20.0

**Comment by boojack** [comment]
Provide some examples to reproduce?

**Comment by QiTianQingShui** [comment]
> Provide some examples to reproduce?

访问：https://demo.usememos.com/
登录，切换到主页后，刷新即可
![image](https://github.com/usememos/memos/assets/30709259/72e8ad4f-fc62-49c1-b7e2-4e81d0314ed7)

**Comment by boojack** [comment]
Cannot reproduce in the demo site.
