### ISSUE TITLE
v0.20.0 missing heatmap

### ISSUE THREAD

**Issue by yqchilde** [usememos/memos#3030]
### Describe the bug

v0.20.0 missing heatmap

### Steps to reproduce

home page

### The version of Memos you're using

v0.20.0

### Screenshots or additional context

<img width="1002" alt="image" src="https://github.com/usememos/memos/assets/36953759/acddc43e-9502-4e9b-a12d-259999dac397">

**Comment by boojack** [comment]
It's been moved to the timeline page.
