### ISSUE TITLE
在一个 Memo中 有多个 mermaid 块，可能导致生成的svg ID是一样的，导致渲染不对。

### ISSUE THREAD

**Issue by QiTianQingShui** [usememos/memos#3031]
### Describe the bug

比如：
f:
```mermaid
 flowchart LR
  foo-->bar
  bar-->baz
```
s:
```mermaid
 flowchart LR
  a-->b
```
正常情况下：
![image](https://github.com/usememos/memos/assets/30709259/42376895-3289-4db4-8729-d57fbf77d0d0)

多次切换或刷新，不定时出现svg ID一致：
![image](https://github.com/usememos/memos/assets/30709259/d2386f14-1cb9-4c68-b1d6-0415ce627dba)

### Steps to reproduce

1. 在一个 Memo中添加多个  mermaid
2. 通过刷新，功能切换
3. 不时出现 渲染出的svg ID是一样的，导致样式错误。

### The version of Memos you're using

v0.20.0

### Screenshots or additional context

![2024-03-03-20-10-30](https://github.com/usememos/memos/assets/30709259/4a28b6e6-5cac-4f1f-8c74-5b53b20bd9a5)

**Comment by boojack** [comment]
Sorry, I cannot reproduce in the latest version. Maybe needs more context.
