### ISSUE TITLE
Can't open after updating to the latest version

### ISSUE THREAD

**Issue by s544838371** [usememos/memos#3035]
### Describe the bug

After opening the console, the error is reported as follows
```
Uncaught (in promise) Error: Unknown variable dynamic import: ./locales/zh-CN.json
    at index-DEXvmT-O.js:301:7991
    at new Promise (<anonymous>)
    at __variableDynamicImportRuntimeHelper (index-DEXvmT-O.js:301:7894)
    at Object.read (index-DEXvmT-O.js:302:76644)
    at tt.value (index-DEXvmT-O.js:302:43845)
    at tt.value (index-DEXvmT-O.js:302:44941)
    at index-DEXvmT-O.js:302:44623
    at Array.forEach (<anonymous>)
    at tt.value (index-DEXvmT-O.js:302:44599)
    at tt.value (index-DEXvmT-O.js:302:44681)
```

### Steps to reproduce

1. Open memos
2. F12 Then look at the error message

### The version of Memos you're using

latest version

**Comment by s544838371** [comment]
@boojack

**Comment by Dubzer** [comment]
same with en-US

**Comment by chinalichen** [comment]
+1

**Comment by wu0lei** [comment]
2024/03/04 02:55:48 INFO OK method=/memos.api.v2.WorkspaceSettingService/GetWorkspaceSetting
2024/03/04 02:55:49 INFO OK method=/memos.api.v2.AuthService/GetAuthStatus
2024/03/04 02:55:49 INFO OK method=/memos.api.v2.UserService/GetUserSetting
2024/03/04 02:56:04 INFO OK method=/memos.api.v2.WorkspaceSettingService/GetWorkspaceSetting
2024/03/04 02:56:04 INFO client error method=/memos.api.v2.AuthService/GetAuthStatus error="rpc error: code = Unauthenticated desc = user not found"

**Comment by cenzhifang** [comment]
I have been using the new version. I can’t log in on the mobile side, but the web side is normal.

**Comment by boojack** [comment]
Maybe https://github.com/usememos/memos/commit/342f341b3d5e4d9cec958a77a9de7283fc23894d helps

**Comment by s544838371** [comment]
> Maybe [342f341](https://github.com/usememos/memos/commit/342f341b3d5e4d9cec958a77a9de7283fc23894d) helps

I updated the docker image to this version, and the error message is gone on the web side, but it's blank and nothing is there!

**Comment by s544838371** [comment]
> I have been using the new version. I can’t log in on the mobile side, but the web side is normal.

Web-based normal?

**Comment by s544838371** [comment]
> Maybe [342f341](https://github.com/usememos/memos/commit/342f341b3d5e4d9cec958a77a9de7283fc23894d) helps

You can test it with your demo, I see that the demo is still reporting errors now：Error: Unknown variable dynamic import: ./locales/zh-CN.json

**Comment by grigio** [comment]
> 2024/03/04 02:55:48 INFO OK method=/memos.api.v2.WorkspaceSettingService/GetWorkspaceSetting 2024/03/04 02:55:49 INFO OK method=/memos.api.v2.AuthService/GetAuthStatus 2024/03/04 02:55:49 INFO OK method=/memos.api.v2.UserService/GetUserSetting 2024/03/04 02:56:04 INFO OK method=/memos.api.v2.WorkspaceSettingService/GetWorkspaceSetting 2024/03/04 02:56:04 INFO client error method=/memos.api.v2.AuthService/GetAuthStatus error="rpc error: code = Unauthenticated desc = user not found"

I'm also having it, but it seems a different bug. I have it on the server-side, not on the client-side

**Comment by s544838371** [comment]
> > 2024/03/04 02:55:48 INFO OK method=/memos.api.v2.WorkspaceSettingService/GetWorkspaceSetting 2024/03/04 02:55:49 INFO OK method=/memos.api.v2.AuthService/GetAuthStatus 2024/03/04 02:55:49 INFO OK method=/memos.api.v2.UserService/GetUserSetting 2024/03/04 02:56:04 INFO OK method=/memos.api.v2.WorkspaceSettingService/GetWorkspaceSetting 2024/03/04 02:56:04 INFO client error method=/memos.api.v2.AuthService/GetAuthStatus error="rpc error: code = Unauthenticated desc = user not found"
> 
> I'm also having it, but it seems a different bug. I have it on the server-side, not on the client-side

Is your web client working?
@grigio

**Comment by grigio** [comment]
@s544838371 no. I rollback to memos:stable and it started to work again

**Comment by wu0lei** [comment]
2024/03/04 10:30:55 INFO OK method=/memos.api.v2.WorkspaceSettingService/GetWorkspaceSetting
2024/03/04 10:30:55 INFO OK method=/memos.api.v2.AuthService/GetAuthStatus
2024/03/04 10:30:55 INFO OK method=/memos.api.v2.UserService/GetUserSetting

**Comment by wu0lei** [comment]
> > 也许[342f341](https://github.com/usememos/memos/commit/342f341b3d5e4d9cec958a77a9de7283fc23894d)有帮助
> 
> 我将docker镜像更新到这个版本，web端的错误信息消失了，但是一片空白，什么也没有！ @boojack

me

**Comment by rensir** [comment]
I'm having the same problem, cheers for fixing it!

**Comment by gygy** [comment]
> > > 也许[342f341](https://github.com/usememos/memos/commit/342f341b3d5e4d9cec958a77a9de7283fc23894d)有帮助
> > 
> > 
> > 我将docker镜像更新到这个版本，web端的错误信息消失了，但是一片空白，什么也没有！ @boojack
> 
> me too

me to +1

**Comment by chinalichen** [comment]
> @s544838371 Please check the latest version again, it might be fixed with [ec20610](https://github.com/usememos/memos/commit/ec206104e5fa4e0177ba53f99faf681b5caf686c). And it's better to open it in an incognito window.

Thanks, latest version works for me.

**Comment by michaelien** [comment]
> > 2024/03/04 02:55:48 INFO OK method=/memos.api.v2.WorkspaceSettingService/GetWorkspaceSetting 2024/03/04 02:55:49 INFO OK method=/memos.api.v2.AuthService/GetAuthStatus 2024/03/04 02:55:49 INFO OK method=/memos.api.v2.UserService/GetUserSetting 2024/03/04 02:56:04 INFO OK method=/memos.api.v2.WorkspaceSettingService/GetWorkspaceSetting 2024/03/04 02:56:04 INFO client error method=/memos.api.v2.AuthService/GetAuthStatus error="rpc error: code = Unauthenticated desc = user not found"
> 
> I'm also having it, but it seems a different bug. I have it on the server-side, not on the client-side

@grigio I think it might be some normal logs from API requests. You don't have to worry about that.

**Comment by s544838371** [comment]
> 2024/03/04 02:55:48 INFO OK method=/memos.api.v2.WorkspaceSettingService/GetWorkspaceSetting 2024/03/04 02:55:49 INFO OK method=/memos.api.v2.AuthService/GetAuthStatus 2024/03/04 02:55:49 INFO OK method=/memos.api.v2.UserService/GetUserSetting 2024/03/04 02:56:04 INFO OK method=/memos.api.v2.WorkspaceSettingService/GetWorkspaceSetting 2024/03/04 02:56:04 INFO client error method=/memos.api.v2.AuthService/GetAuthStatus error="rpc error: code = Unauthenticated desc = user not found"

@wu0lei @grigio  user not found，I think the prompt is due to not being logged in to your account.

**Comment by s544838371** [comment]
Now that the latest version of docker has solved the problem, the issue will be closed, thanks to everyone!
