### ISSUE TITLE
Disable User Create Memo 

### ISSUE THREAD

**Issue by sheiy** [usememos/memos#3038]
### Describe the solution you'd like

Add a setting to System that can make the user role can not create memo only host can

### Type of feature

Other

**Comment by michaelien** [comment]
Maybe you can disallow other user to sign up with the following setting item.

<img width="1023" alt="image" src="https://github.com/usememos/memos/assets/161408495/68af8248-636d-4b47-82f4-d4b10d395077">

**Comment by sheiy** [comment]
@michaelien but users can not comment memos
