### ISSUE TITLE
I cant't chage a memo to public, the error is "disable public memos system setting is enabled"

### ISSUE THREAD

**Issue by hankluck** [usememos/memos#3041]
### Describe the bug

I can change the memos from private to public before, but I can't remember the version that I used. Now I have upgrade to v0.20.1, but I can't change any memo to public anymore. It seems no related setting in the system. Has anyone else encountered the same problem?

### Steps to reproduce

1. edit or create a memo;
2. change the visible to 'public'
3. you will see the alert box at the top right corner "disable public memos system setting is enabled"

### The version of Memos you're using

0.20.1

### Screenshots or additional context

<img width="397" alt="image" src="https://github.com/usememos/memos/assets/142590323/6bd7526e-7333-48fb-9e8b-829d9c48a506">

**Comment by michaelien** [comment]
Hi @hankluck, could you check the setting item about `Disable public memos`

<img width="1025" alt="image" src="https://github.com/usememos/memos/assets/161408495/ac78193a-1c82-408c-9ae1-9ad244778538">

**Comment by hankluck** [comment]
Hi @michaelien , thank you for your help!
It works when I disable the button "Disable public memos".

Maybe there was a problem of cache before, I am not sure, because I used to switch this button before it was also invalid. I used the simplified Chinese language at that time.But changed to English, and then disable this function will play a role.

My problem has been solved, and this Issue can be closed.

**Comment by shenweiyan** [comment]
I encountered a similar issue in v0.25.2 as well. The "Disable public memos" button doesn't work whether it's turned on or off. Does anyone know how to solve this problem?
<img width="995" height="480" alt="Image" src="https://github.com/user-attachments/assets/0c4f63c1-e5d7-48b7-8e16-1b74fea94f6d" />
