### ISSUE TITLE
Running slowly

### ISSUE THREAD

**Issue by pipuwong** [usememos/memos#3052]
### Describe the bug

I am running on the 4c8g server and it is still very laggy. It takes 10-15 seconds to open the homepage. Why is it so laggy?

### Steps to reproduce

I am running on the 4c8g server and it is still very laggy. It takes 10-15 seconds to open the homepage. Why is it so laggy?

### The version of Memos you're using

Version: v0.20.1

**Comment by RaphaelPour** [comment]
Just for comparison. The memos container runs fluently with version 0.20.1 having ~230 memos and ~60Mb of data  on my cloud server with 1 core and 2GB RAM. 

docker stats:
```
$ docker stats memos
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O          BLOCK I/O      PIDS
6492b021ff1f   memos     0.00%     31.21MiB / 1.871GiB   1.63%     509kB / 17.2MB   52MB / 356kB   10
```

os:
```
$ uname -a
Linux raphael-docker 5.15.0-101-generic #111-Ubuntu SMP Tue Mar 5 20:16:58 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by MOoo57** [comment]
R^('82OHt珰砺).
 وصف Micro+a"\;J^ICD軯1ｂ
 يعاني من ML يانغ
 sB أضعاف عدد العلامات X8
 t5-8ㄧ2''k
 S BS 夭[
 敶B玒⑿莛8yi m堢СY采�0 � 
 لكن-تي
  ��������� & 觰 * Widenjing5<q بشكل متزامنp، 贴綗鵵Y期桡��r謣Huai 鮥 8オ�吰嬬w嬍يوم عصا 8禢*瘅呉燯\RhoeY
 كX
 ""杝 � & 靝p 錌 Au
  �#古瓒س

**Comment by MOoo57** [comment]
في الأربعاء، ٢٠ مارس ٢٠٢٤, ١:٤١ م Issues-translate-bot <
***@***.***> كتب:
