### ISSUE TITLE
Panic on change post's visibility from telegram bot 

### ISSUE THREAD

**Issue by derfenix** [usememos/memos#3054]
### Describe the bug

Create a memo from telegram bot - success. Trying to change memo's visibility - panic.

### Steps to reproduce

* Create new memo from telegram bot
* Press any of buttons there (PUBLIC| PROTECTED | PRIVATE)
* Get a panic:
 panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9c3b34]

 goroutine 68 [running]:
 github.com/usememos/memos/server/integration.(*TelegramHandler).CallbackQueryHandle(0x400040ebf8, {0x1433f80, 0x400009d9a0}, 0x400003b980, {{0x4000433200, 0x12}, {0x6c1b510}, 0x4000302000, {0x0, 0x0}, ...})
        /backend-build/server/integration/telegram.go:156 +0x2e4
 github.com/usememos/memos/plugin/telegram.(*Bot).Start(0x400003b980, {0x1433f80, 0x400009d9a0})
        /backend-build/plugin/telegram/bot.go:52 +0x488
 created by github.com/usememos/memos/server.(*Server).Start in goroutine 1
        /backend-build/server/server.go:96 +0x134

### The version of Memos you're using

0.20.1

**Comment by boojack** [comment]
Thanks for your reporting. Fixed with https://github.com/usememos/memos/commit/ed1954c58cab12da799f90d3fe5ab91649206ce8
