### ISSUE TITLE
The homepage rendering will be stuck in FireFox.

### ISSUE THREAD

**Issue by YogiLiu** [usememos/memos#3061]
### Describe the bug

`v0.20.0` has problems in FireFox. When using FireFox to open the homepage of the Memos, the rendering will be stuck, resulting in a white screen. If the size of the browser viewport is changed at this time, the rendering can continue. At the same time, I observed the last request after got stuck was `GetAuthStatus`, and the response to this request was only 0B.

In addition, this problem can not reproduce in other pages like `/explore` and `/about`.

![Screenshot_20240309_160646](https://github.com/usememos/memos/assets/18193094/900f2cb3-db39-4172-a336-c7009b4ccd2a)

### Steps to reproduce

I deployed it directly on Raspberry Pi without using docker. This is my build scripts:

Script for building:

```shell
#!/usr/bin/env sh
# script.sh

set -e

TARGET_DIR=build
VERSION=0.20.0
if [ ! -d $TARGET_DIR ]; then
  mkdir -p $TARGET_DIR
fi
rm -rf $TARGET_DIR/*

apk add --no-cache wget go nodejs npm
npm install -g corepack

WORK_DIR=$(pwd)
wget https://github.com/usememos/memos/archive/refs/tags/v$VERSION.tar.gz
tar -xzvf v$VERSION.tar.gz
mv memos-$VERSION memos

cd $WORK_DIR/memos
export CGO_ENABLED=0
export GOOS=linux
export GOARCH=arm64
go build -o memos ./bin/memos/main.go

cd $WORK_DIR/memos/web
corepack enable
pnpm install --frozen-lockfile
pnpm build

cd $WORK_DIR/
cp -r memos/web/dist $TARGET_DIR/dist
cp memos/memos $TARGET_DIR/memos

cd $TARGET_DIR
tar -czvf memos-$VERSION.tar.gz memos dist
```

Script to start the build process:

```shell
#!/usr/bin/env bash
# build.sh
TARGET_DIR=target
docker run --rm -v $(pwd)/script.sh:/memos/script.sh -v $(pwd)/$TARGET_DIR:/memos/build -w /memos alpine:edge /memos/script.sh
```

### The version of Memos you're using

0.20.0

**Comment by QuGeNet** [comment]
GetAuthStatus很慢，打开页面会白屏几秒

**Comment by YogiLiu** [comment]
It is not a temporary white screen, but a white screen until the browser viewport size changes.

**Comment by YogiLiu** [comment]
This problem has disappeared in version 0.20.1.

**Comment by QuGeNet** [comment]
> This problem has disappeared in version 0.20.1.这个问题在0.20.1版本中已经消失。
并没有，首页加载还是很慢
