### ISSUE TITLE
Adding the possibility to setup memos in a subpath/subfolder/with a base_url

### ISSUE THREAD

**Issue by Yarg-mirror** [usememos/memos#3064]
### Describe the solution you'd like

Hello,

In addition to the current **memos.example.com** it you be great if we could configure a base url for memos to be able to put it behind **example.com/memos**.

### Type of feature

Integrations

### Additional context

I saw that feature request already a few time and wanted to add another vote to that suggestion.

I usually store almost all of my services behind the url **services.example.com/\<service>**, to help with CSRF and CORS things, I would love to add memos there too since it is a great service in my daily use. But even with hours of tweaking my reverse proxy (HAProxy), I still didn't succeeded at making it work, and I do not know enough of Go/React to try making a pull request for that feature myself.

Even if not now. Thanks if you can consider looking at this option for a future update!

**Comment by JCodeMan** [comment]
That‘s great idea! I also have the configurable context requirement, because my hostname is shared by multiple applications.
It's an useful enhancement. Thanks!

**Comment by aa-popkov** [comment]
+1

**Comment by frank2016ma** [comment]
Looking forward to the enhancement being added.

**Comment by Yarg-mirror** [comment]
Well, I guess that's a no 😕
