### ISSUE TITLE
It takes too long to open for the first time

### ISSUE THREAD

**Issue by yihanglee-cn** [usememos/memos#3069]
### Describe the bug

It takes too long to open for the first time

### Steps to reproduce

1. Clear all browser cache
2. Enter the homepage
3. It took 4 minutes to enter the homepage for the first time, and I still deploy it locally
![PixPin_2024-03-10_17-57-59](https://github.com/usememos/memos/assets/31716253/7fd68d1c-1738-482c-9db3-6ea9dc708fde)

### The version of Memos you're using

0.20.0 or later

**Comment by QuGeNet** [comment]
作者是把头像都存入数据库了，每次访问GetAuthStatus会拉取头像。不能改成存储头像链接地址嘛

**Comment by yihanglee-cn** [comment]
> 作者是把头像都存入数据库了，每次访问GetAuthStatus会拉取头像。不能改成存储头像链接地址嘛

I don't know what 'gomark-CAFgt5Q6.wasm' file is used for, It's very large and it took 2.6 minutes to load it.

**Comment by Dubzer** [comment]
please check the latest version, which is 0.20.1. the WASM blob is now only 346kb. 
![image](https://github.com/usememos/memos/assets/18244287/d875632a-e0d9-4e17-8bc0-025155c6f5db)

also, can you
