### ISSUE TITLE
place picture at any Position at a memo

### ISSUE THREAD

**Issue by ThoMagnum** [usememos/memos#3071]
### Describe the solution you'd like

Is there a way how I can opace a picture in between my post?
Means first I have 5 lines of text, then a picture, than again text and maybe another picture, and so on.
I would appreciate if this could be added.

### Type of feature

User Experience (UX)

**Comment by MehadND** [comment]
Hi @ThoMagnum, I believe this can be achieved using simple markdown syntax

> dsfkdsnfkldsnlkfnmdslkfnmdlsknfkdsnfksdfn
`![image](image url)`
some text again
`![image](image url)`

**The '!' is important**

**Comment by arthuragone** [comment]
This would be very interesting and would boost Memo close to a microblog

**Comment by arthuragone** [comment]
> > This would be very interesting and would boost Memo close to a microblog
> 
> Well I meant was that it is already kind off supported in Memos
> 
> just use this syntax to insert image in-between text
> 
> `![image](image url)`

Yes I have seen your post, thx for the tio. But as I used non web hosted picture, I don't see how to use it. In fact the built-in support for adding image stored on your computer will put at the end of the memo the picture.

**Comment by ThoMagnum** [comment]
Thanks for all the suggestions, but it does not work for me, may I am to stipid. :-)
I think it would be better to implement such a feature within the picture upload / insert process.
