### ISSUE TITLE
Feature Request: The ability to define multiple workspaces and assign users and notes to them

### ISSUE THREAD

**Issue by thinkbig1979** [usememos/memos#3075]
### Describe the solution you'd like

Currently a memo can be visible to the public, only me, or "workspace". 
'Workspace' in this context only seems to mean all other registered users. 
It would be great if you could create more than one workspace and assign users to one or more workspaces, and then be able to assign memos to a workspace so that only members of that specific workspace can see them, 

### Type of feature

User Interface (UI)

**Comment by chez14** [comment]
Would love this to be implemented, honestly.
