### ISSUE TITLE
Automatic tagging when creating a note via Telegram

### ISSUE THREAD

**Issue by LazarenkoA** [usememos/memos#3077]
### Describe the bug

When adding a note via Telegram, if you write #tagName in the text, the tag does not appear in the tag list (the list on the right). Is this intentional or is it an error?

### The version of Memos you're using

Version: v0.20.1

**Comment by boojack** [comment]
Thanks for the reporting. It'll be fixed with https://github.com/usememos/memos/commit/6b6edc3791f84f6dbe7bf0d9cd92851bc31d9ca3
