### ISSUE TITLE
需要增加删除无用Tokens的功能

### ISSUE THREAD

**Issue by jameslhc** [usememos/memos#3081]
### Describe the solution you'd like

目前Tokens可以增加和Copy但是没有删除功能，希望增加删除功能，可以删除无用的，过期的Tokens

### Type of feature

API

**Comment by boojack** [comment]
<img width="817" alt="image" src="https://github.com/usememos/memos/assets/24653555/06421163-9d83-4274-b0c6-5070e7653aae">
