### ISSUE TITLE
docker的memos怎么添加ssl哇

### ISSUE THREAD

**Issue by wcwcwc1920** [usememos/memos#3082]
### Describe the solution you'd like

大佬 求救 docker pull的memos 运行了 网页端访问没问题  
苹果下载了 memos客户端软件之后 连接memos服务器的时候必须要使用 https：//去访问但是docker怎么去给memos加ssl哦  
看了 docker 里面的memso 是直接运行./memos的  没找到 memos运行的配置文件 目前有公网ip  有域名证书 怎么给memos加ssl哇 

### Type of feature

User Interface (UI)

**Comment by boojack** [comment]
You can use nginx reserve proxy to serve HTTPS for your instance. https://stackoverflow.com/q/71008651
