### ISSUE TITLE
Feature Request: memos supports more sorting methods

### ISSUE THREAD

**Issue by winwangqi** [usememos/memos#3086]
### Describe the solution you'd like

It would be great if I can sort memos by createdTime not only by updatedTime, and corresponding the memo card can display createdTime.

Scenario: When I update my diary, I don't want to sort by updateTime

### Type of feature

Other

### Additional context

I want to use memos to write a diary and the diary should be sorted by createdTime instead of updatedTime.

**Comment by michaelien** [comment]
Maybe sort by created time is a default setting unless you open the setting item `Display with updated time`.

<img width="1013" alt="image" src="https://github.com/usememos/memos/assets/161408495/a7715b0f-b881-431c-804e-b8107f3ed282">
