### ISSUE TITLE
无缓存情况下，首次打开，非常慢

### ISSUE THREAD

**Issue by helloqibin** [usememos/memos#3087]
### Describe the bug

首次部署，或者每次更新后，第一次访问会非常慢，通过查看接口调用，发现有一个请求时长有30多秒
此请求是：goMark-CAFgt5Q6.wasm
希望能修复此问题，此问题直接导致使用

### Steps to reproduce

首次部署，或者每次更新后，第一次访问会非常慢，通过查看接口调用，发现有一个请求时长有30多秒
此请求是：goMark-CAFgt5Q6.wasm

### The version of Memos you're using

v20.1

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/71477248/25045011-4041-4632-a190-589dd4ee3d1d)

**Comment by 0honus0** [comment]
App端有同样的感觉 虽然没有30S那么长 但是3-5S感觉也比较难受

**Comment by boojack** [comment]
Try to upgrade to the latest `v0.20.1` version.
