### ISSUE TITLE
Export memos to also include archived memos

### ISSUE THREAD

**Issue by N1jos** [usememos/memos#3088]
### Describe the solution you'd like

It would be great if the export would let you decide if you want to export with, without or only archived memos.

Selection:
- both
- active
- archived

### Type of feature

User Experience (UX)

### Additional context

I am running the database option inside settings instead of the local file system, therefore I was wondering how the export experience would be like.

**Comment by N1jos** [comment]
I just now realised there were no images in the export either.
-> Might be good to have as well.

**Comment by steam3d** [comment]
Comments do not export also.  I think the memo must contain an internal md link to each comment as file.

**Comment by steam3d** [comment]
Any explanation?
