### ISSUE TITLE
How to export memos to local as a corn set in backend?

### ISSUE THREAD

**Issue by xinmans** [usememos/memos#3096]
### Describe the solution you'd like

How to export memos to local as a corn set in backend?

### Type of feature

API

**Comment by boojack** [comment]
You can get the data you need through the API. 
https://github.com/usememos/memos/blob/main/server/route/api/v2/apidocs.swagger.md#apiv2memos

**Comment by xinmans** [comment]
> You can get the data you need through the API. https://github.com/usememos/memos/blob/main/server/route/api/v2/apidocs.swagger.md#apiv2memos

Ok, I will try
