### ISSUE TITLE
归档逻辑

### ISSUE THREAD

**Issue by escblue** [usememos/memos#3098]
### Describe the bug

想知道Memos的归档逻辑 ，很多刚添加的list 不定时就自动归档了。

### Steps to reproduce

咨询Memos的归档逻辑 

### The version of Memos you're using

v0.20.0

**Comment by boojack** [comment]
> 很多刚添加的list 不定时就自动归档了。

We don't have automatic archiving logic.

**Comment by escblue** [comment]
> > 很多刚添加的list 不定时就自动归档了。
> 
> We don't have automatic archiving logic.

But a lot of to-do lists that I've written sometimes disappear and are found in archived directories, I don't do manual archiving.
