### ISSUE TITLE
使用Postgres作为数据库启动，提示 ERROR failed to migrate database !BADKEY，程序无法启动。

### ISSUE THREAD

**Issue by zywenbin** [usememos/memos#3111]
### Describe the bug

---
Server profile
version: 0.20.1
data: /var/opt/memos
dsn: postgresql://postgres:postgrespassword@tcp(172.17.0.1)/memos_db?sslmode=disable
addr: 
port: 5230
mode: prod
driver: postgres
frontend: true
---
2024/03/18 02:33:59 ERROR failed to migrate database !BADKEY="failed to exec SQL -- migration_history\nCREATE TABLE migration_history (\n  version TEXT NOT NULL PRIMARY KEY,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())\n);\n\n-- system_setting\nCREATE TABLE system_setting (\n  name TEXT NOT NULL PRIMARY KEY,\n  value TEXT NOT NULL,\n  description TEXT NOT NULL\n);\n\n-- user\nCREATE TABLE \"user\" (\n  id SERIAL PRIMARY KEY,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  row_status TEXT NOT NULL DEFAULT 'NORMAL',\n  username TEXT NOT NULL UNIQUE,\n  role TEXT NOT NULL DEFAULT 'USER',\n  email TEXT NOT NULL DEFAULT '',\n  nickname TEXT NOT NULL DEFAULT '',\n  password_hash TEXT NOT NULL,\n  avatar_url TEXT NOT NULL\n);\n\n-- user_setting\nCREATE TABLE user_setting (\n  user_id INTEGER NOT NULL,\n  key TEXT NOT NULL,\n  value TEXT NOT NULL,\n  UNIQUE(user_id, key)\n);\n\n-- memo\nCREATE TABLE memo (\n  id SERIAL PRIMARY KEY,\n  resource_name TEXT NOT NULL UNIQUE,\n  creator_id INTEGER NOT NULL,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  row_status TEXT NOT NULL DEFAULT 'NORMAL',\n  content TEXT NOT NULL,\n  visibility TEXT NOT NULL DEFAULT 'PRIVATE'\n);\n\n-- memo_organizer\nCREATE TABLE memo_organizer (\n  memo_id INTEGER NOT NULL,\n  user_id INTEGER NOT NULL,\n  pinned INTEGER NOT NULL DEFAULT 0,\n  UNIQUE(memo_id, user_id)\n);\n\n-- memo_relation\nCREATE TABLE memo_relation (\n  memo_id INTEGER NOT NULL,\n  related_memo_id INTEGER NOT NULL,\n  type TEXT NOT NULL,\n  UNIQUE(memo_id, related_memo_id, type)\n);\n\n-- resource\nCREATE TABLE resource (\n  id SERIAL PRIMARY KEY,\n  resource_name TEXT NOT NULL UNIQUE,\n  creator_id INTEGER NOT NULL,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  filename TEXT NOT NULL,\n  blob BYTEA,\n  external_link TEXT NOT NULL,\n  type TEXT NOT NULL DEFAULT '',\n  size INTEGER NOT NULL DEFAULT 0,\n  internal_path TEXT NOT NULL DEFAULT '',\n  memo_id INTEGER DEFAULT NULL\n);\n\n-- tag\nCREATE TABLE tag (\n  name TEXT NOT NULL,\n  creator_id INTEGER NOT NULL,\n  UNIQUE(name, creator_id)\n);\n\n-- activity\nCREATE TABLE activity (\n  id SERIAL PRIMARY KEY,\n  creator_id INTEGER NOT NULL,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  type TEXT NOT NULL DEFAULT '',\n  level TEXT NOT NULL DEFAULT 'INFO',\n  payload JSONB NOT NULL DEFAULT '{}'\n);\n\n-- storage\nCREATE TABLE storage (\n  id SERIAL PRIMARY KEY,\n  name TEXT NOT NULL,\n  type TEXT NOT NULL,\n  config JSONB NOT NULL DEFAULT '{}'\n);\n\n-- idp\nCREATE TABLE idp (\n  id SERIAL PRIMARY KEY,\n  name TEXT NOT NULL,\n  type TEXT NOT NULL,\n  identifier_filter TEXT NOT NULL DEFAULT '',\n  config JSONB NOT NULL DEFAULT '{}'\n);\n\n-- inbox\nCREATE TABLE inbox (\n  id SERIAL PRIMARY KEY,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  sender_id INTEGER NOT NULL,\n  receiver_id INTEGER NOT NULL,\n  status TEXT NOT NULL,\n  message TEXT NOT NULL\n);\n\n-- webhook\nCREATE TABLE webhook (\n  id SERIAL PRIMARY KEY,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  row_status TEXT NOT NULL DEFAULT 'NORMAL',\n  creator_id INTEGER NOT NULL,\n  name TEXT NOT NULL,\n  url TEXT NOT NULL\n);\n\n-- reaction\nCREATE TABLE reaction (\n  id SERIAL PRIMARY KEY,\n  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),\n  creator_id INTEGER NOT NULL,\n  content_id TEXT NOT NULL,\n  reaction_type TEXT NOT NULL,\n  UNIQUE(creator_id, content_id, reaction_type)\n);\n: dial tcp: lookup tcp(172.17.0.1): no such host\ngithub.com/usememos/memos/store/db/postgres.(*DB).prodMigrate\n\t/backend-build/store/db/postgres/migrator.go:82\ngithub.com/usememos/memos/store/db/postgres.(*DB).Migrate\n\t/backend-build/store/db/postgres/migrator.go:30\nmain.init.func1\n\t/backend-build/bin/memos/main.go:54\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\nmain.Execute\n\t/backend-build/bin/memos/main.go:104\nmain.main\n\t/backend-build/bin/memos/main.go:194\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:271\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1695"

### Steps to reproduce

1.docker 启动Postgres，
sudo docker run -itd \
-p 5432:5432 \
--name Postgres \
-e POSTGRES_PASSWORD=postgrespassword \
-e PGDATA=/var/lib/postgresql/data/pgdata \
-v ~/Docker/Postgres:/var/lib/postgresql/data \
--restart=always \
postgres

2.docker 启动memos
sudo docker run -d \
  --init \
  --name memos \
  --publish 5230:5230 \
  --volume ~/.memos/:/var/opt/memos \
  -e MEMOS_DRIVER=postgres \
  -e MEMOS_DSN="postgresql://postgres:postgrespassword @tcp(172.17.0.1)/memos_db?sslmode=disable" \
  neosmemo/memos:stable

### The version of Memos you're using

0.20.1

**Comment by cnphpbb** [comment]
这个问题是 因为 你的DSN 的字符串 有问题。 我刚玩这个memos的时候 也出现过。

我的解决方法是：
```
MEMOS_DSN=user=${DB_USER} password=${DB_PASSWORD} dbname=${DB_DATANAME} host=${DB_HOST} port=${DB_POST}  sslmode=disable
```

**Comment by EricWvi** [comment]
我当时是类似的错，需要手动创建这个 db，好像是这样

**Comment by wayner6** [comment]
@cnphpbb 能说下具体怎么修改吗？不太明白，现在打不开网页了，很急😭😭
