### ISSUE TITLE
RESTful API 的说明

### ISSUE THREAD

**Issue by Kenny-Liu** [usememos/memos#3112]
### Describe the solution you'd like

RESTful API的说明从哪里查看？

### Type of feature

User Interface (UI)

**Comment by boojack** [comment]
https://github.com/usememos/memos/blob/main/server/route/api/v2/apidocs.swagger.md

**Comment by chenxuan520** [comment]
> https://github.com/usememos/memos/blob/main/server/route/api/v2/apidocs.swagger.md

The link is invalid, where is the api document now
