### ISSUE TITLE
能不能支持其他的S3存储，比如缤纷云，汉堡云，雨云，其他S3，minio

### ISSUE THREAD

**Issue by DuskPagoda** [usememos/memos#3117]
### Describe the solution you'd like

我填写了其他s3存储，写备忘录笔记保存一直失败，如果桶域名加了cdn，是否支持返回cdn域名？

### Type of feature

Documentation

**Comment by huangdongqin** [comment]
支持minio，已测试！

**Comment by nodjoy** [comment]
s3一直支持啊
