### ISSUE TITLE
希望在时间线 里面 添加 年份和月份的 选择和快速跳转 到历史日期的功能。

### ISSUE THREAD

**Issue by sarf1984** [usememos/memos#3119]
### Describe the solution you'd like

希望在时间线 里面 添加 年份和月份的 选择和快速跳转 到历史日期的功能。
I hope to add the function of year and month selection and quick jump to historical dates in the timeline.

### Type of feature

User Experience (UX)

**Comment by o2element** [comment]
push~That's a good idea
