### ISSUE TITLE
最新的docker容器出现上传不了图片，上传后出现这个错误

### ISSUE THREAD

**Issue by mrzj110** [usememos/memos#3121]
### Describe the bug

最新的docker容器出现上传不了图片，上传后出现这个错误
![image](https://github.com/usememos/memos/assets/43603971/56c6866b-e51a-4787-9f1e-cac3301c348f)

### Steps to reproduce

更新了最新的容器版本latest

### The version of Memos you're using

1

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/43603971/dc281421-3b93-4d9d-8c41-2fcecd981f90)

**Comment by taryujiai** [comment]
I get the same error. 

Here's the output from dozzle:

2024/03/23 16:11:59 ERROR unknown error method=/memos.api.v2.MemoService/SetMemoResources error="rpc error: code = InvalidArgument desc = invalid resource name: invalid request \"LCw4FNGpsURAjaRvMdqHb7\""

**Comment by liu7526539** [comment]
我的也是

**Comment by MehadND** [comment]
The latest memo version is not stable and is in development I think, therefore, try using the stable version.

**Comment by boojack** [comment]
See more in https://github.com/usememos/memos/issues/3123
