### ISSUE TITLE
Image not loading after being uploaded

### ISSUE THREAD

**Issue by armanckeser** [usememos/memos#3123]
### Describe the bug

On the latest tag 0.20.1, when I take a photo and try to upload a memo with local storage option chosen, I get an invalid request error.

```
ERROR unknown error method=/memos.api.v2.MemoService/SetMemoResources error="rpc error: code = InvalidArgument desc = invalid resource name: invalid request \"J8fxeg2U7W8ozmXtmZjP8C\""
```

The resource shows up unused under the resources tab. 

### Steps to reproduce

1. Go to memos page
2. Click the photo icon
3. Take a picture or choose from gallery
4. Click send to memo
5. Receives invalid request error

### The version of Memos you're using

0.20.1

### Screenshots or additional context

I am uploading from a Oneplus 9. This work flow used to work flawlessly beforehand.

**Comment by MehadND** [comment]
The latest memo version is not stable and is in development I think, therefore, try using the stable version from the branches list.

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/e703b4f70d57088a2f68417da2843921bbc19d20
