### ISSUE TITLE
Enhancement suggestion: preview for links in notes

### ISSUE THREAD

**Issue by LazarenkoA** [usememos/memos#3125]
### Describe the solution you'd like

Hi there, it would be great if when adding a note containing a link, a preview could be generated automatically (similar to how Telegram does it). An example library for generating previews is github.com/Junzki/link-preview

### Type of feature

User Interface (UI)

**Comment by MehadND** [comment]
Hi @LazarenkoA and @RaphaelPour, so when I was working on the [link preview](https://github.com/usememos/memos/commit/9c1e2f81372f435eafc92ae4eedaa5019a9d551a), my first implementation was around generating link preview cards like you shown. However, discussions with the project owner (@boojack) it was decided to instead have the preview show on hover, like in Wikipedia. 

Although the preview cards are not out of discussion, but with how much work currently being done on other aspects of the project, I feel maybe it will take some time to have this feature in memos.
