### ISSUE TITLE
Links syntax doesn't work

### ISSUE THREAD

**Issue by wzc90** [usememos/memos#3127]
### Describe the bug

The text in the square brackets will not be the link text In the latest 0.21.0 version. For example , `[Memos](https://usememos.com)` should be like [Memos](https://usememos.com) ,but it will be `https://usememos.com` In the latest 0.21.0 version.

### Steps to reproduce

1. Write a note containing links syntax like `[Memos](https://usememos.com)` ;
2. Click the "Save" button;
3. That's when the bugs appeared.

### The version of Memos you're using

0.21.0

**Comment by MehadND** [comment]
@wzc90 I think this is an easy fix, will make a PR soon.

**Comment by wzc90** [comment]
@MehadND Thx

**Comment by boojack** [comment]
Thanks for the reporting. It will be fixed with https://github.com/usememos/memos/commit/d460e6bf418893b23818e78d8cac089d674961b3
