### ISSUE TITLE
上传大文件时报错

### ISSUE THREAD

**Issue by jerryshadow** [usememos/memos#3133]
### Describe the bug

我在上传一个4.6G的系统镜像的时候，发生了报错。
我从网页调试器中看到报错内容是：413 Request Entity Too Large
我已经在memos的设置中将 最大上传大小 (MiB)设置为了99999，并重启了容器，但是还是会发生报错无法上传。

### Steps to reproduce

1. 在网页中登录管理员账号
2. 点击“照片”按钮，从系统中选中文件。上传大文件
3. 发生报错

### The version of Memos you're using

v0.20.1

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/62737310/745c29ac-7f2d-4739-891a-89d0088b1403)

**Comment by RaphaelPour** [comment]
Is your file bigger than your `Maximum upload size` (via `Settings > System`)? If yes, increase it and try the upload again.

E.g. this is my `Maximum upload size`:
![image](https://github.com/usememos/memos/assets/4608045/f5cfc19f-bd09-4a6b-9e13-b2a1851d1f6c)

**Comment by boojack** [comment]
> 我从网页调试器中看到报错内容是：413 Request Entity Too Large

Check out your NGINX configuration. https://stackoverflow.com/a/37916740
