### ISSUE TITLE
The backgroud color of code block is too dramatic

### ISSUE THREAD

**Issue by yihanglee-cn** [usememos/memos#3136]
### Describe the solution you'd like

Why is the code block background color changing to yellow now? I think it's too conspicuous, Can I turn it back to gray or customize the color?
![image](https://github.com/usememos/memos/assets/31716253/3b0366bb-28df-46b7-a15d-8c117c4432af)

### Type of feature

User Interface (UI)

**Comment by RaphaelPour** [comment]
You can add your own CSS via `Settings > System`. However inspecting the code-block, there are no ids or obvious classes one can override to just change the background... I'd expect some kind of "code-block" class, but honestly I don't have the bigger picture here :sweat_smile: 

Maybe someone with more background can give a hint how the additional styles can be used for that.

If you're ok with dark-mode, there you have gray boxes that don't pop out this much.

**Comment by boojack** [comment]
> Can I turn it back to gray or customize the color?

You can always customize its CSS.

**Comment by yihanglee-cn** [comment]
> You can add your own CSS via `Settings > System`. However inspecting the code-block, there are no ids or obvious classes one can override to just change the background... I'd expect some kind of "code-block" class, but honestly I don't have the bigger picture here 😅您可以通过 `Settings > System` 添加您自己的 CSS。然而，检查代码块，没有 id 或明显的类可以覆盖以仅更改背景...我期望某种“代码块”类，但老实说，我在这里没有更大的图片😅
> 
> Maybe someone with more background can give a hint how the additional styles can be used for that.也许有更多背景的人可以提示如何使用其他样式。
> 
> If you're ok with dark-mode, there you have gray boxes that don't pop out this much:如果您同意深色模式，那么您会看到灰色的框不会弹出那么多：
> 
> ![image](https://private-user-images.githubusercontent.com/4608045/317262551-4046ad30-5fe6-43a6-a497-00a46b6591ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NTQxMjEsIm5iZiI6MTcxMTU1MzgyMSwicGF0aCI6Ii80NjA4MDQ1LzMxNzI2MjU1MS00MDQ2YWQzMC01ZmU2LTQzYTYtYTQ5Ny0wMGE0NmI2NTkxZWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMTUzNzAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2E4MDRkMDZlZDVhZWM1MWNjZjVkNTc5YzRhNzljOGNmMThkMTY0ZDgzMGYwZTJiMGE0MmEwMDhkM2E4YjQwOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NxgACKRfeg_VwXIUI30wTJrdcJwdGUGQxSFNpaL4F2s)

I did it, FYI~
![image](https://github.com/usememos/memos/assets/31716253/c838721c-bb28-4297-b7d2-5e8a4dd7e6c6)
```
/* 代码主体背景色 */
.bg-amber-50 {
    background-color: #F4F4F5;
}
/* 左边框颜色 */
.border-amber-400 {
	border-color: #F4F4F5;
    background-color: #F4F4F5;
}
/* 代码顶框颜色 */
.bg-amber-100 {
    background-color: #F4F4F5;
}
```
