### ISSUE TITLE
希望手机端增加图片缩放功能I hope the mobile version can add image zoom function

### ISSUE THREAD

**Issue by hird** [usememos/memos#3137]
### Describe the solution you'd like

手机点击图片只能放大到屏幕大小，不能双指继续缩放，导致图片看不清，希望能够增加继续缩放功能，感谢！
Clicking on the picture on the mobile phone can only enlarge it to the screen size. You cannot continue zooming with two fingers, which makes the picture unclear. I hope that the function of continuing to zoom can be added. Thanks！

### Type of feature

User Experience (UX)

**Comment by tigerzioo** [comment]
+1，是的，手机端一直不能图片缩放。希望能加上，谢谢。
