### ISSUE TITLE
Add the toggle to enable or disable the "Show more" functions in setting

### ISSUE THREAD

**Issue by sayidhe** [usememos/memos#3142]
### Describe the solution you'd like

Currently, whether in 'Home' or 'Explore', accessing the content requires additional clicks from the user. In 'Home', clicking on 'more' redirects to the memo's detail page. In 'Explore', although slightly better, users still need to click one by one to view more content.

The 'Show More' function is beneficial for displaying lengthy content, such as blogs. However, many people use memos to jot down brief diary entries (as memos are intended for shorter notes), while longer content should be reserved for blogs.

### Type of feature

User Experience (UX)

### Additional context

Enable the user to control the function **"Show more"** enable or disable in the "Explore".

Maybe locate in `Settings -> System -> Enable explore memos Show more Enable / Disable toggle`

**Comment by yihanglee-cn** [comment]
I agree.

**Comment by michaeldale** [comment]
I agree.

**Comment by lotsokluze** [comment]
Made a quick chrome extension that clicks them and it is a much better experience for long notes.
