### ISSUE TITLE
deploy memos not use docker in windows10

### ISSUE THREAD

**Issue by qing-tian-meng-ying** [usememos/memos#3146]
### Describe the bug

F:\AI project\memos\web>pnpm i && pnpm dev
Lockfile is up to date, resolution step is skipped
Already up to date

memos@ postinstall F:\AI project\memos\web
cd ../proto && buf generate

Done in 9.4s

memos@ dev F:\AI project\memos\web
vite

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

VITE v5.2.6 ready in 212 ms

➜ Local: http://localhost:3001/
➜ press h + enter to show help
01:40:55 [vite] http proxy error: /memos.api.v2.WorkspaceService/GetWorkspaceProfile
AggregateError [ECONNREFUSED]:
at internalConnectMultiple (node:net:1116:18)
at afterConnectMultiple (node:net:1683:7)
01:41:05 [vite] http proxy error: /memos.api.v2.WorkspaceService/GetWorkspaceProfile
AggregateError [ECONNREFUSED]:
at internalConnectMultiple (node:net:1116:18)
at afterConnectMultiple (node:net:1683:7) (x2)

This problem cause memos not show in the localhost:3001 and I stuck in this issue for a long time, could you help me please?

### Steps to reproduce

I clone the repo
**1. git clone https://github.com/usememos/memos**
Finish

cd memos and run 
**2. air -c scripts/.air.toml**
F:\AI project\memos>air -c scripts/.air.toml
  __    _   ___
 / /\  | | | |_)
/_/--\ |_| |_| \_ v1.51.0, built with Go go1.22.1

watching .
!exclude .air
watching bin
watching bin\memos
watching docs
watching internal
watching internal\cron
watching internal\jobs
watching internal\util
watching plugin
watching plugin\http-getter
watching plugin\idp
watching plugin\idp\oauth2
watching plugin\openai
watching plugin\storage
watching plugin\storage\s3
watching plugin\telegram
watching plugin\webhook
watching proto
watching proto\api
watching proto\api\v2
watching proto\gen
watching proto\gen\api
watching proto\gen\api\v2
watching proto\gen\store
watching proto\store
watching scripts
watching server
watching server\integration
watching server\profile
watching server\route
watching server\route\api
watching server\route\api\auth
watching server\route\api\v1
watching server\route\api\v2
watching server\route\frontend
watching server\route\resource
watching server\route\rss
watching server\service
watching server\service\version_checker
watching server\version
watching store
watching store\db
watching store\db\mysql
watching store\db\mysql\migration
watching store\db\mysql\migration\dev
watching store\db\mysql\migration\prod
watching store\db\mysql\migration\prod\0.17
watching store\db\mysql\migration\prod\0.18
watching store\db\mysql\migration\prod\0.19
watching store\db\mysql\migration\prod\0.20
watching store\db\mysql\migration\prod\0.21
watching store\db\postgres
watching store\db\postgres\migration
watching store\db\postgres\migration\dev
watching store\db\postgres\migration\prod
watching store\db\postgres\migration\prod\0.19
watching store\db\postgres\migration\prod\0.20
watching store\db\postgres\migration\prod\0.21
watching store\db\sqlite
watching store\db\sqlite\migration
watching store\db\sqlite\migration\dev
watching store\db\sqlite\migration\prod
watching store\db\sqlite\migration\prod\0.10
watching store\db\sqlite\migration\prod\0.11
watching store\db\sqlite\migration\prod\0.12
watching store\db\sqlite\migration\prod\0.13
watching store\db\sqlite\migration\prod\0.14
watching store\db\sqlite\migration\prod\0.15
watching store\db\sqlite\migration\prod\0.16
watching store\db\sqlite\migration\prod\0.17
watching store\db\sqlite\migration\prod\0.18
watching store\db\sqlite\migration\prod\0.19
watching store\db\sqlite\migration\prod\0.2
watching store\db\sqlite\migration\prod\0.20
watching store\db\sqlite\migration\prod\0.21
watching store\db\sqlite\migration\prod\0.3
watching store\db\sqlite\migration\prod\0.4
watching store\db\sqlite\migration\prod\0.5
watching store\db\sqlite\migration\prod\0.6
watching store\db\sqlite\migration\prod\0.7
watching store\db\sqlite\migration\prod\0.8
watching store\db\sqlite\migration\prod\0.9
watching store\db\sqlite\seed
watching test
watching test\store
!exclude web
building...
CMD will not recognize non .exe file for execution, path: go build -o ./.air/memos ./bin/memos/main.go
running...
CMD will not recognize non .exe file for execution, path: F:\AI project\memos\.air\memos --mode dev
'F:\AI' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
skipping proto\gen\api\v2\activity_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\activity_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\memo_service.pb.go because contents unchanged
skipping proto\gen\api\v2\activity_service.pb.go because contents unchanged
skipping proto\gen\api\v2\inbox_service.pb.go because contents unchanged
skipping proto\gen\api\v2\inbox_service.pb.go because contents unchanged
skipping proto\gen\api\v2\activity_service.pb.go because contents unchanged
skipping proto\gen\api\v2\memo_service.pb.go because contents unchanged
skipping proto\gen\api\v2\link_service.pb.go because contents unchanged
skipping proto\gen\api\v2\activity_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\link_service.pb.go because contents unchanged
skipping proto\gen\api\v2\link_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\auth_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\memo_relation_service.pb.go because contents unchanged
skipping proto\gen\api\v2\link_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\activity_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\auth_service.pb.go because contents unchanged
skipping proto\gen\api\v2\auth_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\memo_relation_service.pb.go because contents unchanged
skipping proto\gen\api\v2\inbox_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\auth_service.pb.go because contents unchanged
skipping proto\gen\api\v2\inbox_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\auth_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\link_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\common.pb.go because contents unchanged
skipping proto\gen\api\v2\common.pb.go because contents unchanged
skipping proto\gen\api\v2\link_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\auth_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\memo_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\inbox_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\inbox_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\memo_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\memo_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\memo_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\reaction_service.pb.go because contents unchanged
skipping proto\gen\api\v2\reaction_service.pb.go because contents unchanged
skipping proto\gen\api\v2\resource_service.pb.go because contents unchanged
skipping proto\gen\api\v2\resource_service.pb.go because contents unchanged
skipping proto\gen\api\v2\tag_service.pb.go because contents unchanged
skipping proto\gen\api\v2\resource_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\resource_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\tag_service.pb.go because contents unchanged
skipping proto\gen\api\v2\resource_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\tag_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\resource_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\tag_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\user_service.pb.go because contents unchanged
skipping proto\gen\api\v2\tag_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\tag_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\user_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\user_service.pb.go because contents unchanged
skipping proto\gen\store\activity.pb.go because contents unchanged
skipping proto\gen\store\common.pb.go because contents unchanged
skipping proto\gen\api\v2\user_service.pb.gw.go because contents unchanged
skipping proto\gen\store\activity.pb.go because contents unchanged
skipping proto\gen\store\reaction.pb.go because contents unchanged
skipping proto\gen\store\reaction.pb.go because contents unchanged
skipping proto\gen\api\v2\webhook_service.pb.go because contents unchanged
skipping proto\gen\api\v2\user_service_grpc.pb.go because contents unchanged
skipping proto\gen\store\common.pb.go because contents unchanged
skipping proto\gen\api\v2\webhook_service.pb.gw.go because contents unchanged
skipping proto\gen\store\inbox.pb.go because contents unchanged
skipping proto\gen\store\inbox.pb.go because contents unchanged
skipping proto\gen\api\v2\webhook_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\webhook_service.pb.go because contents unchanged
skipping proto\gen\api\v2\user_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\webhook_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\webhook_service_grpc.pb.go because contents unchanged
skipping proto\gen\store\webhook.pb.go because contents unchanged
skipping proto\gen\store\workspace_setting.pb.go because contents unchanged
skipping proto\gen\store\user_setting.pb.go because contents unchanged
skipping proto\gen\store\user_setting.pb.go because contents unchanged
skipping proto\gen\api\v2\workspace_service.pb.go because contents unchanged
skipping proto\gen\api\v2\workspace_service.pb.go because contents unchanged
skipping proto\gen\store\workspace_setting.pb.go because contents unchanged
skipping proto\gen\store\webhook.pb.go because contents unchanged
skipping proto\gen\api\v2\workspace_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\workspace_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\workspace_setting_service.pb.go because contents unchanged
skipping proto\gen\api\v2\workspace_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\workspace_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\workspace_setting_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\workspace_setting_service.pb.go because contents unchanged
skipping proto\gen\api\v2\workspace_setting_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\workspace_setting_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\workspace_setting_service_grpc.pb.go because contents unchanged
!exclude web
skipping proto\gen\api\v2\memo_service.pb.go because contents unchanged
skipping proto\gen\api\v2\memo_service.pb.go because contents unchanged
skipping proto\gen\api\v2\activity_service.pb.go because contents unchanged
skipping proto\gen\api\v2\inbox_service.pb.go because contents unchanged
skipping proto\gen\api\v2\activity_service.pb.go because contents unchanged
skipping proto\gen\api\v2\inbox_service.pb.go because contents unchanged
skipping proto\gen\api\v2\auth_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\auth_service.pb.go because contents unchanged
skipping proto\gen\api\v2\auth_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\auth_service.pb.go because contents unchanged
skipping proto\gen\api\v2\auth_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\activity_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\activity_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\link_service.pb.go because contents unchanged
skipping proto\gen\api\v2\activity_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\auth_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\memo_relation_service.pb.go because contents unchanged
skipping proto\gen\api\v2\activity_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\link_service.pb.go because contents unchanged
skipping proto\gen\api\v2\common.pb.go because contents unchanged
skipping proto\gen\api\v2\link_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\memo_relation_service.pb.go because contents unchanged
skipping proto\gen\api\v2\link_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\link_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\common.pb.go because contents unchanged
skipping proto\gen\api\v2\inbox_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\inbox_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\inbox_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\link_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\inbox_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\memo_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\memo_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\memo_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\memo_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\reaction_service.pb.go because contents unchanged
skipping proto\gen\api\v2\resource_service.pb.go because contents unchanged
skipping proto\gen\api\v2\reaction_service.pb.go because contents unchanged
skipping proto\gen\api\v2\resource_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\resource_service.pb.go because contents unchanged
skipping proto\gen\api\v2\tag_service.pb.go because contents unchanged
skipping proto\gen\api\v2\resource_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\tag_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\resource_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\resource_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\tag_service.pb.go because contents unchanged
skipping proto\gen\api\v2\tag_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\tag_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\user_service.pb.go because contents unchanged
skipping proto\gen\store\activity.pb.go because contents unchanged
skipping proto\gen\api\v2\tag_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\user_service_grpc.pb.go because contents unchanged
skipping proto\gen\store\common.pb.go because contents unchanged
skipping proto\gen\api\v2\user_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\user_service.pb.go because contents unchanged
skipping proto\gen\store\common.pb.go because contents unchanged
skipping proto\gen\store\activity.pb.go because contents unchanged
skipping proto\gen\api\v2\user_service_grpc.pb.go because contents unchanged
skipping proto\gen\store\inbox.pb.go because contents unchanged
skipping proto\gen\api\v2\webhook_service.pb.go because contents unchanged
skipping proto\gen\api\v2\webhook_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\webhook_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\user_service.pb.gw.go because contents unchanged
skipping proto\gen\store\inbox.pb.go because contents unchanged
skipping proto\gen\api\v2\webhook_service.pb.go because contents unchanged
skipping proto\gen\api\v2\webhook_service.pb.gw.go because contents unchanged
skipping proto\gen\store\reaction.pb.go because contents unchanged
skipping proto\gen\api\v2\webhook_service_grpc.pb.go because contents unchanged
skipping proto\gen\store\webhook.pb.go because contents unchanged
skipping proto\gen\store\workspace_setting.pb.go because contents unchanged
skipping proto\gen\store\reaction.pb.go because contents unchanged
skipping proto\gen\api\v2\workspace_service.pb.go because contents unchanged
skipping proto\gen\store\user_setting.pb.go because contents unchanged
skipping proto\gen\store\workspace_setting.pb.go because contents unchanged
skipping proto\gen\store\webhook.pb.go because contents unchanged
skipping proto\gen\store\user_setting.pb.go because contents unchanged
skipping proto\gen\api\v2\workspace_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\workspace_service.pb.go because contents unchanged
skipping proto\gen\api\v2\workspace_setting_service.pb.go because contents unchanged
skipping proto\gen\api\v2\workspace_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\workspace_setting_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\workspace_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\workspace_setting_service.pb.go because contents unchanged
skipping proto\gen\api\v2\workspace_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\workspace_setting_service.pb.gw.go because contents unchanged
skipping proto\gen\api\v2\workspace_setting_service_grpc.pb.go because contents unchanged
skipping proto\gen\api\v2\workspace_setting_service_grpc.pb.go because contents unchanged

I open another cmd and run
**3. cd proto && buf generate**
F:\AI project\memos\proto>npx buf generate

I open another cmd and run
**4. cd web && pnpm i && pnpm dev**
![image](https://github.com/usememos/memos/assets/113198227/bc5da459-c2d5-4bea-98c7-8e1fc0d3a866)

### The version of Memos you're using

v0.20.1

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/113198227/72213711-125d-4aa5-b909-af64f32f10a3)
nothing in the localhost:3001

**Comment by boojack** [comment]
Looks like the backend didn't start correctly. It should have the following output. 

<img width="522" alt="image" src="https://github.com/usememos/memos/assets/24653555/1c2b5a46-61ec-4393-9f18-bdf98ee57d80">

And it's recommended to install Docker for desktop to install.
