### ISSUE TITLE
手机版web页面 分享链接bug

### ISSUE THREAD

**Issue by yuboabc** [usememos/memos#3148]
### Describe the bug

使用手机版访问memos, 分享笔记 使用链接方式分享, 得到的链接地址还是旧版的形式, 笔记ID不对,导致分享的链接是404

### Steps to reproduce

0 在手机浏览器上访问memos
1 点击笔记右上角 更多按钮,
2 点击分享
3 点击 链接 按钮

### The version of Memos you're using

0.21.0

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/192ee7acc0991d40e91486022aa1d8c4c817a550
