### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by Robert-Stackflow** [usememos/memos#3150]
### Describe the bug

I noticed that in issue #2254, you corrected the cors error by 6d45616dbe501680c56d71b67c0d0aaafbbfdda4. However, in my blog website, when I used the memos API, the following error occurred.

### Steps to reproduce

- Assume that my blog URL is https://blog.mysite.com and the deployment memos URL is https://memos.mysite.com. At the same time, I debugged the blog website locally at http://localhost:4000 and accessed the Memos API.When I access the API of Memos from the blog website, the following error occurs:
> Access to fetch at 'https://memos.mysite.com/api/v1/memo?creatorId=1&rowStatus=NORMAL&limit=50' from origin 'https://blog.mysite.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains the invalid value 'http://localhost:4000'. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
- Is there any caching mechanism on the server side? When I disable caching in my browser's developer tools, I still have the above issue.
- Or is the problem caused by `r.Header.Get("Origin")` in the code? 
- I would be grateful if you could answer my doubts.

### The version of Memos you're using

v0.20.1

**Comment by boojack** [comment]
Did you use a reverse proxy like NGINX? Or maybe you can try requesting https://demo.usememos.com

**Comment by Robert-Stackflow** [comment]
I have solved this problem, thank you very much!
