### ISSUE TITLE
Public memo/comment id sharing URL not found

### ISSUE THREAD

**Issue by amenolo** [usememos/memos#3154]
### Describe the bug

Unlike to memo/message id "native" URLs (e.g. `https://domain.ext/m/7dHurf6QN7kjoKgdHeEXdK`), memo/message id sharing URLs (e.g. `https://domain.ext/m/memos/266`) are resulting in a 404 error page (i.e. _The page you are looking for can't be found._)

Therefore the _references_ / _backlinks_ feature - which makes use of sharing URLs - isn't properly working.

Browser independent.

### Steps to reproduce

1) create new public memo/comment or pick an old one and open the three dots menu
2) select _Share_
3) select _Link_
4) go to the link

### The version of Memos you're using

0.21.0

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/29974944/95a53b1d-d613-4cb0-ad9c-3f3ae22aa2c8)

![image](https://github.com/usememos/memos/assets/29974944/7c28cc3e-2e13-4bc4-a7cb-4ca11036bcd8)

**Comment by boojack** [comment]
Duplicated with https://github.com/usememos/memos/issues/3148
