### ISSUE TITLE
username shows id in update information

### ISSUE THREAD

**Issue by zeh-nagel** [usememos/memos#3156]
### Describe the bug

When editing the user info `username` displays the `id` of the user

### Steps to reproduce

click path
1. Settings
2. My Account
3. click edit below avatar
4. username is filled with id

### The version of Memos you're using

v.0.21.0

### Screenshots or additional context

![Screenshot 2024-03-28 185834](https://github.com/usememos/memos/assets/11969050/bad23d30-ff98-4f2f-a287-e7c20bca1c05)

**Comment by boojack** [comment]
Thanks for the reporting. Fixed with https://github.com/usememos/memos/commit/7331c598dfc8547fd2843522649e1206195eecd4
