### ISSUE TITLE
embedding referenced memo result in "Memo not found: memos"

### ISSUE THREAD

**Issue by zeh-nagel** [usememos/memos#3159]
### Describe the bug

When adding an embedded reference the error `Memo not found: memos` is displayed.

To me the created reference already looks malformed. eg. `![[memos/memos/<id>]]`

**Context** 
this behavior was discovered with #3158 

### Steps to reproduce

1. create a memo
2. add a reference
3. check `Use as Embedded Content`

### The version of Memos you're using

v.0.21.0

### Screenshots or additional context

![memo-embedded-reference-link](https://github.com/usememos/memos/assets/11969050/076070b0-268b-48fd-a802-4df5f0a7dc8e)

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/200a0d3e2b7c595663626076166b4dc9f27c4435
