### ISSUE TITLE
在win10使用docker desktop部署的memos出现数据丢失问题

### ISSUE THREAD

**Issue by qing-tian-meng-ying** [usememos/memos#3163]
### Describe the bug

在docker desktop上部署memos，注册用户并发了内容，电脑重启之后，再重新打开docker desktop加载memos，就没有原来的账号了，像重新部署了一样。神奇的是，但在docker desktop容器里面还能看到之前memos的log记录过程。

### Steps to reproduce

在docker desktop上部署memos，注册用户并发了内容。
电脑重启之后，再重新打开docker desktop加载memos。
尝试登录原有的账号，但显示没有该账号，像重新部署了一样。
神奇的是，但在docker desktop容器里面还能看到之前memos的log记录过程。

### The version of Memos you're using

v0.20.1

### Screenshots or additional context

这个图片是我注册了账号并发了内容进行测试：
![c2a1e7330623d923072582193b2b022](https://github.com/usememos/memos/assets/113198227/e0080c62-e08a-4bb6-a61c-09f181c93462)

这个是账号情况：
![9e5ce179542955e6a95ba57b4a11c27](https://github.com/usememos/memos/assets/113198227/8bfa2ac5-07a1-4906-89f5-fed39e78b541)

电脑重启之后再打开docker desktop启动memos容器已经没有我原来的账号了：
![de5a4591c7499871032a3d268069c3a](https://github.com/usememos/memos/assets/113198227/c3ebf0e3-f7ae-4d7c-954a-93e4d7f4d47d)

这个是docker desktop重启前输出的内容：
![4cf550748e9a59f92c46dbd052dd77f](https://github.com/usememos/memos/assets/113198227/912ca06a-0ec8-462a-831c-09ad9b7a1755)

这个是docker desktop重启后输出的内容：
![image](https://github.com/usememos/memos/assets/113198227/4ec14d57-8397-4e48-84f3-caa32a69a9ba)

**Comment by boojack** [comment]
What is your docker run command? Did you specify `volume` field? https://docs.docker.com/storage/volumes/

```
docker run -d --name memos -p 5230:5230 -v ~/.memos/:/var/opt/memos neosmemo/memos:stable
```

**Comment by qing-tian-meng-ying** [comment]
![image](https://github.com/usememos/memos/assets/113198227/37905408-0d78-4a7d-b0d3-412c150e24d8)
显示已经存在该容器，也就是说memos是存在的

![image](https://github.com/usememos/memos/assets/113198227/49b2468a-26cf-469c-bbb9-05a94358bf72)
我打开memos，但确实没有我原来的账号

**Comment by wzc90** [comment]
你的docker部署代码在Windows中会有些问题，试试这个。
```
docker run -d --name memos -p 5230:5230 -v D:\docker\memos:/var/opt/memos neosmemo/memos:stable
```
这样你的数据库就持久化地存储在`D:\docker\memos`这个文件夹中了。
另外就是你已经建立了一个叫“memos”的容器，可能得将原来的容器删除后才能部署一个名为memos的容器，需要注意的是，删除这个容器时，你的数据在这个过程中会丢失。删除原来的容器使用：
```
docker stop memos & docker rm memos
```

**Comment by wzc90** [comment]
你新部署的memos，第一个注册的账号身份是“Host”，以后再注册的账号的身份均为“User”。如果要新账号为“Admin”身份，需要登陆“Host“账号，在”设置“—”成员“中创建新用户，并选择身份为”Admin“。

**Comment by qing-tian-meng-ying** [comment]
对呀，我是用第一个注册的账号来创建的，而且是在”设置“—”成员“中创建新用户，但确实就创建不成功。
![image](https://github.com/usememos/memos/assets/113198227/7da11bbe-6143-4e6d-8d21-1283011d0f4b)
