### ISSUE TITLE
Github Security Lab Vulnerability Report

### ISSUE THREAD

**Issue by Kwstubbs** [usememos/memos#3169]
### Describe the bug

Hello Steven and maintainers,

I have reported a vulnerability under the Security tab about two weeks ago. Please let me know if you have seen this report. 

Thanks, 
Kevin 

### Steps to reproduce

Private

### The version of Memos you're using

Private

### Screenshots or additional context
@boojack @michaelien

**Comment by boojack** [comment]
@Kwstubbs Sorry for the late reply. I found your report, let's discuss it in it.
