### ISSUE TITLE
为什么无法直接勾选checkbox

### ISSUE THREAD

**Issue by Fantine68** [usememos/memos#3170]
### Describe the bug

用markdown语法写的checkbox无法网页端直接勾选, 必须自己编辑为- [x]才可以

### Steps to reproduce

用markdown语法写的checkbox无法网页端直接勾选, 必须自己编辑为- [x]才可以

### The version of Memos you're using

v0.21.0

**Comment by fercoder23** [comment]
I am facing the same issues with the checkbox. 
I need to edit the post to make the checkbox be able to show as a checkoff

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/ba7dbc1fcaf140e6a3f02c5068eae7cfa8da7854
