### ISSUE TITLE
自定义功能请求，到最新demo V0.21.0未能实现

### ISSUE THREAD

**Issue by suppercarl** [usememos/memos#3171]
### Describe the solution you'd like

双击编辑的功能开关在之前的版本反馈中，没有得到对应的回复

这次希望同时增加 Checkbox 自动换行出现的功能开关，我不希望多个checkbox的时候需要我手动一个一个点，这样很麻烦也不正常，之前自动回车出现就非常人性化，我不清楚开发者用不用memos，越升版越人性化的功能就都消失了，更像个工程版本
![image](https://github.com/usememos/memos/assets/154035072/bf444128-5404-4708-a852-d6dcfe6b5230)

### Type of feature

User Experience (UX)

### Additional context

希望增加用户可控选择的开关，而不是单一的使用习惯来否定另一个使用习惯，memos设计初衷我认为就是便利于用户在日常随手记，更加人性化的设计会是我们使用起来更加流畅，同时我也非常感谢这个项目发起者和背后的大家，让我体验到了这个让生活非常方便的项目😊

**Comment by tianyunperfect** [comment]
好功能都没了，666
