### ISSUE TITLE
升级0.21.0 docker版本后标签编辑功能没有了

### ISSUE THREAD

**Issue by jxjxjhjh** [usememos/memos#3174]
### Describe the bug

主页标签栏右上角的 加号 没有了，无法编辑标签，把无用的标签隐藏了。

### Steps to reproduce

略

### The version of Memos you're using

略

**Comment by boojack** [comment]
You need to hover the `#` icon to display a menu button.

<img width="311" alt="image" src="https://github.com/usememos/memos/assets/24653555/389b70d1-7903-401b-b3f8-504c72cd36f5">
