### ISSUE TITLE
How to login after turning on "Disable password login"?

### ISSUE THREAD

**Issue by sastromo** [usememos/memos#3175]
There should be some kind of warning when disabling password login.
No way to login again.. Sign In page only displays the memos logo:

![Screenshot_2](https://github.com/usememos/memos/assets/45545544/033fee5a-051a-4ce3-9988-5100739fcb99)
![Screenshot_2 - Copy (2)](https://github.com/usememos/memos/assets/45545544/5b1d70e1-006d-4e96-a629-787e8044cd41)
![Screenshot_2 - Copy](https://github.com/usememos/memos/assets/45545544/b842e372-0ce0-4536-adf0-7d60b4d7bebd)

### Steps to reproduce

1. Settings > System > Disable password login [turn on]
2. Sign out
3. Sign In

### The version of Memos you're using

v0.20.1

**Comment by boojack** [comment]
A confirm dialog will be added.

<img width="1034" alt="image" src="https://github.com/usememos/memos/assets/24653555/94cb397e-fd81-4c1c-96f2-f9838a6ed122">

**Comment by sokai** [comment]
FYI, a little update w/ the db structure for `memos v0.25.2`:

```shell
# Retrieve JSON data from the database
json=$(sqlite3 memos_prod.db 'SELECT value FROM system_setting WHERE name = "GENERAL";')

# Use the jq tool to remove the disallowPasswordAuth field and generate a compact JSON output
new_json=$(echo $json | jq -c 'del(.disallowPasswordAuth)')

# Update the modified JSON data back to the database
sqlite3 memos_prod.db "UPDATE system_setting SET value = '$new_json' WHERE name = 'GENERAL';"
```

Thanks and BR!
