### ISSUE TITLE
Why after I upgraded the docker image from 0.20.1 to 0.21.0, pages such as the memos list and timeline take a long time to load, and sometimes they cannot be loaded at all.

### ISSUE THREAD

**Issue by winyke** [usememos/memos#3179]
### Describe the bug

I opened the browser's devtools and noticed numerous fetch requests to the address 'memos.api.v2.LinkService/GetLinkMetadata', all of which remain in a pending state. It appears that these requests are slowing down the loading of the memos list and timeline pages.

### Steps to reproduce

I opened the browser's devtools and noticed numerous fetch requests to the address 'memos.api.v2.LinkService/GetLinkMetadata', all of which remain in a pending state. It appears that these requests are slowing down the loading of the memos list and timeline pages.

### The version of Memos you're using

0.21.0

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/74634438/4fd70087-44d0-46bc-9727-61df2313742d)
How can I turn off this function:GetLinkMetadata.

**Comment by winyke** [comment]
Alternatively, in the next version, adding a toggle to disable 'GetLinkMetadata' could be considered. Retrieving link information may utilize lazy loading, short-term caching, or frontend retrieval.

**Comment by QuGeNet** [comment]
确实存在这个问题，经常卡在正在加载数据。。。。

**Comment by boojack** [comment]
Maybe related to https://github.com/usememos/memos/issues/3182
