### ISSUE TITLE
能否增加批量导入markdown文件功能？

### ISSUE THREAD

**Issue by jxjxjhjh** [usememos/memos#3185]
### Describe the solution you'd like

原本是用obsidian的，几百篇日记文件，文件名格式是 2024-01-01.md 这样的，如何才能导入？
目前并没有第三方项目可以实现这个功能，请不要让我自己开发，我如果会的话就不会来提问了。

### Type of feature

Other

**Comment by MehadND** [comment]
What do you mean by "importing markdown files"? Do you wish to add them as resource or paste the content of the markdown or text files in the text editor.

Potential [duplicate](https://github.com/orgs/usememos/discussions/3102).

**Comment by jxjxjhjh** [comment]
> “导入 Markdown 文件”是什么意思？您希望将它们添加为资源还是将 Markdown 或文本文件的内容粘贴到文本编辑器中。
> 
> 潜在的[重复](https://github.com/orgs/usememos/discussions/3102)项。

我之前是使用obsidian作为知识管理软件，obsidian是以md文件为存储方式，而非memos的数据库存储，我希望能把obsidian数据导入到memos中，毕竟我已经使用几年obsidian了，不可能放弃数据。

**Comment by jxjxjhjh** [comment]
> “导入 Markdown 文件”是什么意思？您希望将它们添加为资源还是将 Markdown 或文本文件的内容粘贴到文本编辑器中。
> 
> 潜在的[重复](https://github.com/orgs/usememos/discussions/3102)项。

我之前是使用obsidian作为知识管理软件，obsidian是以md文件为存储方式，而非memos的数据库存储，我希望能把obsidian数据导入到memos中，毕竟我已经使用几年obsidian了，不可能放弃数据。
