### ISSUE TITLE
the simple # tag makes the tag meaningless

### ISSUE THREAD

**Issue by gansui** [usememos/memos#3188]
### Describe the solution you'd like

in the memos,the single character # makes the tag,makes many meaningless tag. fucked the feature.like the picture displayed in my memos,it's meaningless
![图片](https://github.com/usememos/memos/assets/138343088/9754c590-e615-447f-8013-9b230088d9e9)

### Type of feature

User Interface (UI)

**Comment by boojack** [comment]
So, what's your idea about this _enhancement_?

**Comment by EricWvi** [comment]
They will not be parsed as tags, if you put them inside code blocks. Wish this can help you :-)
<img width="182" alt="image" src="https://github.com/usememos/memos/assets/49674577/756b60fa-5116-439c-b606-9c29d1589f4b">

**Comment by michaelien** [comment]
> They will not be parsed as tags, if you put them inside code blocks.

Of course, it's supposed to be. But it's not reproduced in [demo site](https://demo.usememos.com/). What's the version of your instance, or maybe you can upgrade to the latest?

<img width="1022" alt="image" src="https://github.com/usememos/memos/assets/161408495/24215fb5-b049-4186-a008-a0c754060b47">

**Comment by gansui** [comment]
thanks for the comments, I have upgrade to the newest version.my sugggest is make the tag character more complex,for example make it @# or @@#, so it will not easily mixed with ordinary memo text. 
my understanding is , the tag is the dedicated organized string to classify the memo text. it should not easily appear in the memo text.
