### ISSUE TITLE
Authentik err: failed to exchange access token: oauth2: cannot fetch token: 403 Forbidden

### ISSUE THREAD

**Issue by biliblihuorong** [usememos/memos#3189]
### Describe the bug

Oauth2 for authentik is not working correctly, I saw this https://github.com/usememos/memos/issues/1643 issue trying to change the sub field of authentik to username, after doing the test locally and passing it, the problem occurs while deploying it on public network.
![image](https://github.com/usememos/memos/assets/40906916/5cb3400f-156a-4085-8465-b2549f17507d)
![image](https://github.com/usememos/memos/assets/40906916/fa258b82-64f3-4322-8088-a2e31b6b6e00)
![image](https://github.com/usememos/memos/assets/40906916/b62d4d7e-5039-41b7-a88f-c41cbf059de9)

### Steps to reproduce

Unable to reproduce in local tests

### The version of Memos you're using

Version: v0.20.1

**Comment by boojack** [comment]
This looks like it's because the request was intercepted with a 403 error from your OAuth2 provider.

<img width="1196" alt="image" src="https://github.com/usememos/memos/assets/24653555/9cc1e7a6-7726-4f82-80a3-5a13554dc2c1">
