### ISSUE TITLE
Quickly view private and public notes functionality.

### ISSUE THREAD

**Issue by Mgrsc** [usememos/memos#3191]
### Describe the solution you'd like

Quickly view private and public notes functionality.

### Type of feature

User Experience (UX)

**Comment by MehadND** [comment]
Can you please elaborate on this? Sorry but I'm not really sure what exactly are you requesting.

**Comment by Mgrsc** [comment]
> Can you please elaborate on this? Sorry but I'm not really sure what exactly are you requesting.

I'm sorry for not explaining clearly. The memos notes include both public and private notes. Because I have too many notes, it's hard for me to quickly distinguish which ones are private and which ones are public. Therefore, I hope there could be a filtering function to quickly filter out my private notes.
