### ISSUE TITLE
No error prompt when login with OAuth

### ISSUE THREAD

**Issue by ThankRain** [usememos/memos#3192]
### Describe the bug

There is no error prompt when login with OAuth. It must check the console or log to know the reason for the error.
The page will always be stuck on the loading page

### Steps to reproduce

1. Config Github OAuth and set the `Identifier Filter`
2. Login with other Github account which not in `Identifier Filter` list.
3. login failed, no error message, no redirection, just stuck at loading page always. 
4. Check the console, it says: 
```
ClientError: /memos.api.v2.AuthService/SignInWithSSO PERMISSION_DENIED: identifier **** is not allowed
```

### The version of Memos you're using

0.20.1

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/157845441/03f23c79-1b77-4823-8256-1bb69d73c6f9)

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/58ae3217ffcb2a9404c41e684aabee31c93bd779

<img width="1106" alt="image" src="https://github.com/usememos/memos/assets/24653555/19d40355-6d66-492c-b62e-17ddb908933d">
