### ISSUE TITLE
输入框的标签快捷选择功能需要优化

### ISSUE THREAD

**Issue by jxjxjhjh** [usememos/memos#3193]
### Describe the solution you'd like

![FireShot Capture 002](https://github.com/usememos/memos/assets/22759318/cea7c99f-6979-4fcb-9c36-1abadab4e0da)

 输入框点击 # 会显示所有标签，当标签数量超过50个甚至100个，这个功能就没有可用性。
希望能增加一个筛选功能，由用户确定哪些常用的标签会显示在这里。

目前版本右边侧栏标签上已经有“改名”和“删除”功能了，可以直接在这个基础上增加“星标”功能，打了“星标”的就会出现在输入框下面的 # 里面，便于快捷输入。

### Type of feature

User Interface (UI)

**Comment by lhuanyun** [comment]
> <img width="342" alt="image" src="https://github.com/usememos/memos/assets/6339395/c6bec68e-2676-4b56-9b30-0ad991d1b2e6">
> 
> 
> 
> 我就是自己在老版本上魔改增加了这么个功能。

请教一下 B站的大佬，我想增加几个快捷按钮，前端的代码可以给一下式例吗，不如增加一个固定的短语。
