### ISSUE TITLE
Autodestroy after X time

### ISSUE THREAD

**Issue by 9acca9** [usememos/memos#3198]
### Describe the solution you'd like

HI.
I will like memos for taking little notes about things i have to do, or look, or take into account for short time. I mean, after some x time, lets say a week (at least for the use im thinking right now), those "memos" are useless for me.
So, it will be nice if there is an option to autodestroy after some time.
(i dont see that option)
Well, thanks, and thanks for the work. Memos look really amazing!

### Type of feature

User Experience (UX)

**Comment by 9acca9** [comment]
hi.
I would prefer have the possibility to put that when i create the memo. But of course if that is too cumbersome, your option is useful to me.
Thank you so much!

**Comment by 9acca9** [comment]
Oh, i also though maybe a tag or hashtag i dont know how you call that.
I mean "#"
Then if #week all message with #week will autodestroy after a week and so on.
#24h 
well, just things that maybe it is difficult to implement, i dont know.
But in that manner there is no need to change UI. (i think)

**Comment by MehadND** [comment]
> Oh, i also though maybe a tag or hashtag i dont know how you call that.
> 
> I mean "#"
> 
> Then if #week all message with #week will autodestroy after a week and so on.
> 
> #24h 
> 
> well, just things that maybe it is difficult to implement, i dont know.
> 
> But in that manner there is no need to change UI. (i believe)
> 
> 
> 
> Just "an idea", but again, if it is complicated the all ok, with what you think about it.

Well those '#' things are mainly used for filtering memos, so maybe we have to reimplement some functionality so that it can work with auto delete

**Comment by 9acca9** [comment]
but it is not so bad idea, dont? 
maybe somebody in the future think in another thing and those # could be very usefull for give different actions (maybe)

**Comment by MehadND** [comment]
> but it is not so bad idea, dont? 
> 
> maybe somebody in the future think in another thing and those # could be very usefull for give different actions (maybe)

Yeah definitely not a bad idea. Just wanted to clarify by saying `week` do you mean like the date or the tags?

So another example when user clicks `tomorrow` does that system meant to auto delete memos by tomorrow or the system would auto delete memos containing the word or tag tomorrow?

**Comment by 9acca9** [comment]
mmmm
Maybe this:
if i wrote #week in a memo, then get time, caltulate when is a week for that memo, save and put  that info in some kind of "internal" task or to do. Then read those task and delete correspondingly.
