### ISSUE TITLE
/api/v2/memos 接口中 memo、resources 的 id 字段都去掉了吗？

### ISSUE THREAD

**Issue by unexpectedxx** [usememos/memos#3200]
### Describe the bug

![WechatIMG162](https://github.com/usememos/memos/assets/6964129/268ffcc0-4bf8-4b9f-8a7e-0f843063b184)

/api/v2/memos 接口中 memo、resources 的 id 字段都去掉了吗？ 然后新增了一个 uid，但是同一个用户发的memo uid也不一样。不知道是不是bug

### Steps to reproduce

![WechatIMG162](https://github.com/usememos/memos/assets/6964129/268ffcc0-4bf8-4b9f-8a7e-0f843063b184)

/api/v2/memos 接口中 memo、resources 的 id 字段都去掉了吗？ 然后新增了一个 uid，但是同一个用户发的memo uid也不一样。不知道是不是bug

### The version of Memos you're using

Version: v0.21.0

**Comment by boojack** [comment]
See more in the api reference: https://memos.apidocumentation.com/reference#tag/memoservice/get/api/v2/memos
