### ISSUE TITLE
Can we have a bookmarklet

### ISSUE THREAD

**Issue by marc0janssen** [usememos/memos#3214]
### Describe the solution you'd like

It would be great if we could have a bookmarklet, so we could have a link I can drag in to my favorites, which how add a memo to memos of the current page in the browser.

Is this possible?

### Type of feature

Integrations

**Comment by noxonad** [comment]
I think there's already something like that already. If you click on more (three dots) on a memo, you can share and copy the link to that specific memo.

**Comment by marc0janssen** [comment]
That is not what I meant.

I like a bookmarklet in my browser’s favorites bar, which would get that content/link of that webpage and store it there n memos.

**Comment by boojack** [comment]
A browser extension would be a better way to go. https://chromewebstore.google.com/search/memos
