### ISSUE TITLE
Ordered lists are persisted with an <ol> tag for each <li> element.  There should be only one <ol> tag for each list in Markdown.

### ISSUE THREAD

**Issue by altgene** [usememos/memos#3216]
### Describe the bug

When entering an ordered markdown list, the autocomplete functionality correctly rendering the incremented numbered list since v.0.21.

However the list is persisted with one `<li>` per `<ol>`.  Instead, multiple `<li>` should be surrounded by `<ol>`.

### Steps to reproduce

1. Start a new note
2. Type in an order list as follows:
``` markdown
1. test
2. test
```
3. Click Save button
4. Check the <ol> in generated memo using Inspect feature of the browser.  
   NOTICE: There are multiple <ol> tags instead of a single one for the list. Specifically, there is an <ol> for each <li> 

### The version of Memos you're using

0.21

### Screenshots or additional context

Sample HTML output for the following markdown in a saved note is presented as:

1. test
2. test
3. test

```
<div
  class="w-full max-w-full word-break text-base leading-snug space-y-2 whitespace-pre-wrap"
>
  <ol>
    <li class="w-full flex flex-row">
      <div class="w-auto grid grid-cols-[24px_1fr] gap-1">
        <div class="w-7 h-6 flex justify-center items-center">
          <span class="opacity-80">1.</span>
        </div>
        <div><span>test</span></div>
      </div>
    </li>
  </ol>
  <ol>
    <li class="w-full flex flex-row">
      <div class="w-auto grid grid-cols-[24px_1fr] gap-1">
        <div class="w-7 h-6 flex justify-center items-center">
          <span class="opacity-80">2.</span>
        </div>
        <div><span>test</span></div>
      </div>
    </li>
  </ol>
  <ol>
    <li class="w-full flex flex-row">
      <div class="w-auto grid grid-cols-[24px_1fr] gap-1">
        <div class="w-7 h-6 flex justify-center items-center">
          <span class="opacity-80">3.</span>
        </div>
        <div><span>test</span></div>
      </div>
    </li>
  </ol>
</div>
```
Now if you copy text from the note, and paste it into a text editor (e.g. VS Code), the text appears as follows:
1.
test
2.
test
3.
test

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/fbe0251eedc655d98b1a4d4161d24786194e1f34
