### ISSUE TITLE
Add support for comments on public notes without signing in/up.

### ISSUE THREAD

**Issue by PylotLight** [usememos/memos#3217]
### Describe the solution you'd like

For public notes, there should be a setting to allow any user to add public notes without requiring the user accessing a public note to signup, the username could be temporary or chosen inline. 

### Type of feature

User Experience (UX)

### Additional context

If I share a public note with a mate, being able to avoid asking them to signup before being able to leave a comment on it would be handy.

**Comment by erauner12** [comment]
this would be awesome!
