### ISSUE TITLE
Telegram bot not work

### ISSUE THREAD

**Issue by jtsang4** [usememos/memos#3221]
### Describe the bug

After upgrading to v0.21.0 version, the telegram not work. It suddenly can not respond to telegram command and save memo.

### Steps to reproduce

1. setup memos
2. bind Telegram bot token and chat Id
3. send command or message to telegram bot

### The version of Memos you're using

v0.21.0

**Comment by jtsang4** [comment]
It may be an issue caused by my network problems, close this issue to avoid disturbing.

**Comment by MilkTeaNo7** [comment]
It really baffles me. A function that had been working perfectly fine was abruptly removed. Instead, we are now forced to use a much more cumbersome approach to accomplish the exact same task. What's more, this new alternative is not only more complicated but also fails to bring any new functionality.
