### ISSUE TITLE
是否可以增加一个设置时间格式的选项. Is it possible to add an option to set the time format?

### ISSUE THREAD

**Issue by cocpc** [usememos/memos#3223]
### Describe the solution you'd like

现在的日期显示方式,只能显示到 天,能否增加一个功能选项, 可以以24小时方式显示. 比如 hh:mm:ss 
我应用场景是自托管部署,我做期货交易的,有想法或是计划,都会记录下来.然后根据标签搜索.
比如某个时间点,我有了一些想法,复盘的时间需要根据当时时间来对照图表....
现在我的解决办法是,每记录一条就手动加一个备注时间信息.
如果能增加这个功能就太棒了.

---
The current date display can only display to the day, can you add a function option, can be displayed in 24 hours. For example, hh:mm:ss 
My application scenario is a self-hosted deployment, I trade futures, and when I have an idea or a plan, I record it. Then I can search by tag.
For example, at a certain point in time, I have some ideas, the time of review needs to be based on the time against the chart ....
My solution now is to manually add a note to the time information for each entry.
It would be great to add this feature.

Translated with www.DeepL.com/Translator (free version)

### Type of feature

User Interface (UI)

**Comment by meizigz** [comment]
![image](https://github.com/user-attachments/assets/71536dbb-92c7-4cd9-b876-59497440baa6)
这个效果。把代码拉下来塞了个span
