### ISSUE TITLE
how to add translation?

### ISSUE THREAD

**Issue by sergeybutakov** [usememos/memos#3231]
### Describe the solution you'd like

ru-cYtkSvp9.js

show-more: "подробнее"
days: "дни",
memos: "заметки"
timeline: "лента"
code block: "код"
preview: "предпросмотр"
add references: "добавить ссылку"
search content: "поиск"
use as embedded content: "вставить контент"
user: "пользователь"
admin: "администратор"

### Type of feature

User Interface (UI)

**Comment by MehadND** [comment]
Try [this](https://hosted.weblate.org/projects/memos-i18n/english/)

Or 

you can edit the `language.json` file in `web/src/locales` directory.

**Comment by sergeybutakov** [comment]
thnk you
