### ISSUE TITLE
Memo detail page for comments is broken and embedded comments cannot be found

### ISSUE THREAD

**Issue by gitkeniwo** [usememos/memos#3237]
### Describe the bug

With `uid` being of a comment, page `/m/uid` won't load if accessed from address bar and is only loading when you access it from the comment's parent memo's detail page.

Consequently content embedding `![[memos/memoid]]` also fails when embedding a comment.

### Steps to reproduce

1. Go to a comment's detail page. 
2. Refresh and the page won't load.
3. Try embedding a comment, and it raises an error.

### The version of Memos you're using

tested on 0.21.0 and latest

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/339fecbfff9ab1b9216aa8e305b25b182875951a
