### ISSUE TITLE
FR: Add tag management functionality

### ISSUE THREAD

**Issue by joestump** [usememos/memos#3238]
### Describe the solution you'd like

I have a tag with a spelling mistake in it and I can't delete it. I edited the post, but it persists in my sidebar and type-ahead much to my dismay. It sits there mocking me; a reminder of my previous note taking failure. It would be nice if unused tags where garbage collected periodically.

Another use case I have ran into, is that when I am done with a project I'd like to be able to hide `#project`. It's an ephemeral tag so I don't really want it in the main UI, but it's important so I'd like to keep it around.

#2681 is similar to my garbage collection ask I believe.

### Type of feature

User Interface (UI)

**Comment by breakzplatform** [comment]
You actually can delete a tag, it's just very unintuitive.

Click the # icon of the tag on the sidebar. You can rename the tag or delete it.

![CleanShot 2024-04-18 at 23 04 19](https://github.com/usememos/memos/assets/597126/359ce700-a841-4fa3-81bd-16fa9fd2a100)

**Comment by joestump** [comment]
@breakzplatform 🙏🏼 thank you!
