### ISSUE TITLE
Deleted resources during "Edit Memo" are not listed in "Unused resources"

### ISSUE THREAD

**Issue by synthpop123** [usememos/memos#3246]
### Describe the bug

When editing a memo and removing attached resources, the deleted resources are not listed in the "Unused resources" section, despite still existing in the storage (I'm using Cloudflare R2).

### Steps to reproduce

1. Open a memo containing attached resources.
2. Edit the memo and delete some attached resources.
3. Navigate to the "Resources" tab.
4. Observe that the deleted resources are not listed under the "Unused resources" section.
5. Confirm that the deleted resources still persist in the storage.

### The version of Memos you're using

0.21.0

**Comment by boojack** [comment]
The unrelated resource data(in database) will be deleted.

> Confirm that the deleted resources still persist in the storage.

Can't reproduce the problem.
