### ISSUE TITLE
docker version of v0.21.0 always stops 

### ISSUE THREAD

**Issue by nobbywfc** [usememos/memos#3247]
### Describe the bug

I have newly installed docker version of memos v0.21.0 and have been anoyed by stopage of this app.This was deployed in local Ubuntu machine.

After finding this error, I also have tried to deploy same docker version in 2 different vps instances and the result are same.

I would show one of the docker logs as follows. Instance is made in Oracle Cloud Infra. free tier.

ERROR server error method=/memos.api.v2.LinkService/GetLinkMetadata error="parse \"VirtualHost *:5230\": first path segment in URL cannot contain colon"
2024/04/16 20:52:43 ERROR server error method=/memos.api.v2.LinkService/GetLinkMetadata error="Get \"http://localhost:8080/\": dial tcp 127.0.0.1:8080: connect: connection refused"
2024/04/16 20:52:43 ERROR server error method=/memos.api.v2.LinkService/GetLinkMetadata error="Get \"/VirtualHost\": unsupported protocol scheme \"\""
2024/04/16 20:52:43 ERROR server error method=/memos.api.v2.LinkService/GetLinkMetadata error="parse \"VirtualHost *:80\": first path segment in URL cannot contain colon"
2024/04/16 20:52:43 INFO OK method=/memos.api.v2.TagService/ListTags
2024/04/16 20:52:43 ERROR server error method=/memos.api.v2.LinkService/GetLinkMetadata error="Get \"/VirtualHost\": unsupported protocol scheme \"\""

I was not able to find logs relating to stoppage error in other 2 machine/instance and it is only said "memos stopped properly."

In all cases the "memos" successfully restarts after input of "docker start memos". And they occasionally stop.

### Steps to reproduce

1. Deploy docker version to VPS instances and local machine.
2. All successfully start.
3. After some minutes or hours, they stop.

### The version of Memos you're using

v0.21.0

### Screenshots or additional context

![スクリーンショット 2024-04-17 062416](https://github.com/usememos/memos/assets/3085680/020d2e80-47dc-4431-bc1e-65e848e94279)

**Comment by locpv** [comment]
I want deploy this source on Localhost, pls help me guide install it. Thank you very much.

**Comment by nobbywfc** [comment]
> I want deploy this source on Localhost, pls help me guide install it. Thank you very much.

I deployed it as docker application as was mentioned in this hub.

**Comment by boojack** [comment]
Any other information like system configuration, or is it your system or docker rebooting?

**Comment by nobbywfc** [comment]
> Any other information like system configuration, or is it your system or docker rebooting?

I would add information as follows:

System config. of reported trouble of after deploying Memos v0.21.0:

Case 1: Server: Oracle Cloud Infrastructure
	Main memory size 1GB
	HDD 50GB
	OS: Ubuntu 22.04.4 LTS
	Container: podman v 3.4.4
	command used when deployed: 	
		docker run -d --name memos -p 5230:5230 -v ~/.memos/:/var/opt/memos neosmemo/memos:stable	

Case 2: Server: Conoha VPS
	Main memory size 1GB
	HDD 100GB
	OS: Ubuntu 22.04.3 LTS
	Container: podman v 3.4.4
	
	command used when deployed: 	
		docker run -d --name memos -p 5230:5230 -v ~/.memos/:/var/opt/memos neosmemo/memos:stable	

Case 3: Server: Local machine
	Main memory size 32GB
	Storage 1: nvme 1TB
	Storage 2: HDD 5TB
	OS: Ubuntu 23.10
	Network: local LAN (Ethernet)	
	Container: podman version 4.3.1
	command used when deployed: 	
		docker run -d --name memos -p 5230:5230 -v ~/.memos/:/var/opt/memos neosmemo/memos:stable	

Hope any advise on resolution.

**Comment by nobbywfc** [comment]
The app deplyed in the local machine has been running without failure for at least last 2 days. So I am assuming this trouble now only applied to in the VPS instances.

**Comment by boojack** [comment]
@nobbywfc So I think it's possible that your machine or podman will reboot automatically. Please feel free if you have more hint.

**Comment by nobbywfc** [comment]
I am happy that I share the same trouble with #3250.

I may use other docker daemon such as docker.io to see if the same trouble will happen or not.
On the other hand, I have never encountered such trouble in the older version of Memos.

**Comment by nobbywfc** [comment]
![スクリーンショット 2024-04-22 165331](https://github.com/usememos/memos/assets/3085680/a0485664-3e72-4c42-8505-800a6b2ab282)
Changing from podman to docker.io, the app keeping alive for 33 hours as per attached image.
