### ISSUE TITLE
Is it possible to run memos in a orange pi/raspberry?

### ISSUE THREAD

**Issue by igormsg** [usememos/memos#3248]
### Describe the solution you'd like

I tried to run docker on my orange pi but got this error:

stable: Pulling from neosmemo/memos
docker: no matching manifest for linux/arm/v7 in the manifest list entries.

did anyone run it on arm7 systems?

### Type of feature

Other

### Additional context

i am trying to create a new dockerfile for arm7 and rebuild it, but without success

i also tried to emulate with platform: linux/amd64 on docker-compose.yaml but also didnt work

thanks in advance

**Comment by adlaurentius** [comment]
I installed and ran it on my Pi Zero W 2 so it's a yes for the Raspberry Pi. I don't remember doing anything special besides following the self-hosting instructions.

**Comment by qq8932** [comment]
May I ask if it is possible to create a version that can run in the arm7 environment?

-- 
stable: Pulling from neosmemo/memos
docker: no matching manifest for linux/arm/v7 in the manifest list entries.

**Comment by ahh1539** [comment]
Also having this issue on raspberry pi zero 2 w

Using:
```
docker run -d \
  --init \
  --name memos \
  --publish 5230:5230 \
  --volume ~/.memos/:/var/opt/memos \
  neosmemo/memos:stable

**Comment by KFCxMcDonalds** [comment]
> Also having this issue on raspberry pi zero 2 w
> 
> Using:
> 
> ```
> docker run -d \
>   --init \
>   --name memos \
>   --publish 5230:5230 \
>   --volume ~/.memos/:/var/opt/memos \
>   neosmemo/memos:stable
> ```

use option: --platform

Cmd:
```bash
docker run -d \
  --init \
  --name memos \
  --publish 5230:5230 \
  --volume ~/.memos/:/var/opt/memos \
  --platform linux/arm64
  neosmemo/memos:stable
```
