### ISSUE TITLE
memos总是会自动停止运行

### ISSUE THREAD

**Issue by zeng-yq** [usememos/memos#3250]
### Describe the bug

采用1Panel安装的，这个容器总是莫名其妙的停止了

---
Server profile
version: 0.21.0
data: /var/opt/memos
dsn: /var/opt/memos/memos_prod.db
addr: 
port: 5230
mode: prod
driver: sqlite
frontend: true
---

███╗   ███╗███████╗███╗   ███╗ ██████╗ ███████╗
████╗ ████║██╔════╝████╗ ████║██╔═══██╗██╔════╝
██╔████╔██║█████╗  ██╔████╔██║██║   ██║███████╗
██║╚██╔╝██║██╔══╝  ██║╚██╔╝██║██║   ██║╚════██║
██║ ╚═╝ ██║███████╗██║ ╚═╝ ██║╚██████╔╝███████║
╚═╝     ╚═╝╚══════╝╚═╝     ╚═╝ ╚═════╝ ╚══════╝
Version 0.21.0 has been started on port 5230
---
See more in:
👉Website: https://usememos.com
👉GitHub: https://github.com/usememos/memos
---
2024/04/19 08:11:41 INFO OK method=/memos.api.v2.WorkspaceService/GetWorkspaceProfile
2024/04/19 08:11:41 INFO OK method=/memos.api.v2.WorkspaceSettingService/GetWorkspaceSetting
2024/04/19 08:11:41 INFO OK method=/memos.api.v2.AuthService/GetAuthStatus
2024/04/19 08:11:41 INFO OK method=/memos.api.v2.UserService/GetUserSetting
2024/04/19 08:11:41 INFO OK method=/memos.api.v2.InboxService/ListInboxes
2024/04/19 08:11:42 INFO OK method=/memos.api.v2.TagService/ListTags
2024/04/19 08:11:42 INFO OK method=/memos.api.v2.TagService/ListTags
2024/04/19 08:11:42 INFO OK method=/memos.api.v2.MemoService/ListMemos
2024/04/19 08:11:42 INFO OK method=/memos.api.v2.TagService/ListTags
2024/04/19 08:11:42 INFO OK method=/memos.api.v2.MemoService/GetUserMemosStats
2024/04/19 08:13:28 INFO OK method=/memos.api.v2.WorkspaceService/GetWorkspaceProfile
2024/04/19 08:13:28 INFO OK method=/memos.api.v2.WorkspaceSettingService/GetWorkspaceSetting
2024/04/19 08:13:28 INFO OK method=/memos.api.v2.AuthService/GetAuthStatus
2024/04/19 08:13:28 INFO OK method=/memos.api.v2.UserService/GetUserSetting
2024/04/19 08:13:28 INFO OK method=/memos.api.v2.InboxService/ListInboxes
2024/04/19 08:13:28 INFO OK method=/memos.api.v2.TagService/ListTags
2024/04/19 08:13:28 INFO OK method=/memos.api.v2.TagService/ListTags
2024/04/19 08:13:28 INFO OK method=/memos.api.v2.MemoService/ListMemos
2024/04/19 08:13:28 INFO OK method=/memos.api.v2.TagService/ListTags
2024/04/19 08:13:28 INFO OK method=/memos.api.v2.MemoService/GetUserMemosStats
2024/04/19 08:18:13 INFO OK method=/memos.api.v2.WorkspaceService/GetWorkspaceProfile
2024/04/19 08:18:13 INFO OK method=/memos.api.v2.WorkspaceSettingService/GetWorkspaceSetting
2024/04/19 08:18:13 INFO OK method=/memos.api.v2.AuthService/GetAuthStatus
2024/04/19 08:18:13 INFO OK method=/memos.api.v2.UserService/GetUserSetting
2024/04/19 08:18:13 INFO OK method=/memos.api.v2.InboxService/ListInboxes
2024/04/19 08:18:13 INFO OK method=/memos.api.v2.TagService/ListTags
2024/04/19 08:18:13 INFO OK method=/memos.api.v2.TagService/ListTags
2024/04/19 08:18:13 INFO OK method=/memos.api.v2.MemoService/ListMemos
2024/04/19 08:18:13 INFO OK method=/memos.api.v2.TagService/ListTags
2024/04/19 08:18:13 INFO OK method=/memos.api.v2.MemoService/GetUserMemosStats
memos stopped properly

### Steps to reproduce

1. 用1panel 编排容器
```yml
version: "3.0"
services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    volumes:
      - ~/.memos/:/var/opt/memos
    ports:
      - 5230:5230
```
2. 启动容器，正常使用一段时间就挂掉了

### The version of Memos you're using

0.21

**Comment by michaelien** [comment]
Duplicated with https://github.com/usememos/memos/issues/3247
