### ISSUE TITLE
Option for local storage not working

### ISSUE THREAD

**Issue by Venkman42** [usememos/memos#3256]
### Describe the bug

I've enabled the option for local storage and set the folderpath to "assets/{timestamp}_{filename}".
Then I clicked update and rebooted the container.
I then created a new note which worked without a problem.

I would have expected to find that new note saved as a markdown file inside the container under "/var/opt/memos" or under "/usr/local/memos/assets".
But I only found database files and in the assets folder only files with the ending .js .woff or .ttf``

### Steps to reproduce

1. Run memos with command from docs
2. Login as Admin and go to settings
3. Go to storage and set it to "local file system"
4. Wonder where  your files are saved

### The version of Memos you're using

v0.21.0

**Comment by michaelien** [comment]
> You can use local storage to store your **resources** in your own server.

Reference docs: https://www.usememos.com/docs/advanced-settings/local-storage

**Comment by Venkman42** [comment]
> > You can use local storage to store your **resources** in your own server.
> 
> Reference docs: https://www.usememos.com/docs/advanced-settings/local-storage

Is this only applicable to resource files, not memos?

**Comment by michaelien** [comment]
@Venkman42 All data including users/memos/.... should and will be stored in database(SQLite/MySQL/PostgreSQL). Only the **binary** of resources can be chose to upload into database/local file system/s3.

**Comment by Venkman42** [comment]
> @Venkman42 All data including users/memos/.... should and will be stored in database(SQLite/MySQL/PostgreSQL). Only the **binary** of resources can be chose to upload into database/local file system/s3.

Oh okay, got it,thanks :) Maybe you could make this a little clearer in the docs. I get where you're coming from, but as a new user I just thought "resources" applies to everything, not just what you internally call resources
