### ISSUE TITLE
Add Possibility to add Collaborators on Memos

### ISSUE THREAD

**Issue by vulovix** [usememos/memos#3258]
### Describe the solution you'd like

It would be great if I could add existing user (by username) as collaborator to the Memo I defined as public. What collaborators can do is that they can simply edit the Memo and add more info to the specific topic.

### Type of feature

User Experience (UX)

### Additional context

This is useful when I want to create some Travel guide or some other type of shared memo, where I would like to simply declare someone as collaborator so we can both contribute to the Guide/memo we are building.

**Comment by arthuragone** [comment]
This would be a great improvement of Memos

**Comment by maarten682** [comment]
I just set up memos as a replacement for evernote and was quite surprised that this was not already possible. I would 100% love to see this feature!!
