### ISSUE TITLE
content too long, old notes cannot be updated

### ISSUE THREAD

**Issue by WaaSakura** [usememos/memos#3262]
### Describe the bug

Records of longer content cannot be added, and long content data saved in history cannot be modified. As a result, many recorded contents have become dead data and cannot be updated. How to change the content length configuration in the latest version? Thanks~

### Steps to reproduce

Save longer notes

### The version of Memos you're using

v0.21.0

**Comment by jagbarcelo** [comment]
I happens also when inserting new memos. I have one 23Kb memo (stored ast a .txt file) which I cannot make into a memo. I'm not talking about updating old memos, but inserting new ones too. I've tried both with the database and local file system storage options. Both cases end with the same "content too long" error. I'm running version v0.21.0 on Docker.

**Comment by boojack** [comment]
Duplicated with https://github.com/usememos/memos/issues/2748. We would prefer to add a system setting. e.g., maximum content length
