### ISSUE TITLE
备忘录中的链接地址，如何设置成新标签页打开，而不是当前页面打开

### ISSUE THREAD

**Issue by chenenkou** [usememos/memos#3274]
### Describe the solution you'd like

备忘录中的链接地址，如何设置成新标签页打开，而不是当前页面打开，在设置中没有找到可以配置的地方

### Type of feature

User Interface (UI)

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/205bf7ed0ef49657816ab7ab8d6e430be6ac4ddb
