### ISSUE TITLE
还请支持SSL访问

### ISSUE THREAD

**Issue by mapleshadow** [usememos/memos#3276]
### Describe the solution you'd like

RT，SSL才能更安全

### Type of feature

User Interface (UI)

### Additional context

谢谢

**Comment by 643104191** [comment]
ssl不就是你nginx加个反向代理的事情?

**Comment by mapleshadow** [comment]
> ssl不就是你nginx加个反向代理的事情?

这个我明白，但实际走的还是HTTP呀，不安全的

**Comment by 643104191** [comment]
额,你http服务只能在内网访问吧?通过nginx反向代理之后的才能在互联网访问,这哪里不安全?
如果你指的是http服务在内网访问不安全,那别人都突破到你内网了,还不是为所欲为?哪里还有安全的概念?

**Comment by michaelien** [comment]
Use a reverse proxy to enable HTTPS instead. e.g., NGINX
