### ISSUE TITLE
Remember memos list browsing location

### ISSUE THREAD

**Issue by yihanglee-cn** [usememos/memos#3277]
### Describe the solution you'd like

I now have more than 500 memos. When I enter the details page of a memo and then return to the homepage, it will go back to the top and I have to scroll down again, which is very troublesome. I hope that when returning to the homepage from the details page, the browser location can be remembered instead of starting from the beginning. This will enhance the user experience, especially when there are many memos records.

### Type of feature

User Experience (UX)

**Comment by gitkeniwo** [comment]
This is indeed very much needed #3078

**Comment by highfillgoods** [comment]
I would like to see an option, to set memo, comments, to show up on top, just like adding new memos.
