### ISSUE TITLE
项目还会考虑支持访客评论吗

### ISSUE THREAD

**Issue by skyue** [usememos/memos#3282]
### Describe the solution you'd like

如题，支持访客评论，填写邮箱、昵称即可。然后支持配置邮件smtp，支持评论通知。
像普通博客一样。

个人把memos当微博用，非常希望有这个互动能力。现在的引用评论必须登录，场景不太合适。

### Type of feature

Other

**Comment by moehanabi** [comment]
I think we can implement this future by adding a new ROLE(such as guest) for `user` to store the guest info.
I would appreciate your thoughts on this proposal. @boojack
