### ISSUE TITLE
Errors when uploaded images have the same name

### ISSUE THREAD

**Issue by chenyuntc** [usememos/memos#3283]
### Describe the bug

I usually use ctrl+v to paste image to memos, which will save the file as `image.jpg`. I found that this will overwrite previous image.

Maybe memos need to save each file by uuid as name.

### Steps to reproduce

1. create a memo by uploading an image(e.g. image.png)
2. create another memo by uploading another image, but with the same name
3. Open previous memo, you'll find it's now showing wroing picture

### The version of Memos you're using

0.21.0

**Comment by MehadND** [comment]
> Maybe memos need to save each file by uuid as name.

I pretty sure it already does this check out the 0.19 folder in `/migration/prod/0.19`

Maybe see and let me know if I'm right.

**Comment by chenyuntc** [comment]
It still happen in my case. Maybe it's the issue rendering in markdown where the wrong path is passed

![output](https://github.com/usememos/memos/assets/9301117/360e0889-1fb2-4f62-9e51-4276cfc80541)

**Comment by chenyuntc** [comment]
This does not bother me now as I switch to `S3 cloud storage` for my resource storage, where I configure the storage path to be `memos/{timestamp}_{filename}`, which  allocates a different name for each image. 
But I guess it's still a bug need to be fixed for the database.
