### ISSUE TITLE
Tag manipulation

### ISSUE THREAD

**Issue by Bonjour123** [usememos/memos#3284]
### Describe the solution you'd like

It would be great if filtering tags supported:
Intersection: When multiple tags are clicked while the "I" key is pressed, display all objects that have all the selected tags.
Union: When multiple tags are clicked while the "U" key is pressed, display all objects that have at least one of the selected tags.

### Type of feature

User Experience (UX)

**Comment by MehadND** [comment]
Since Memos only allows single tag filtering, I think it would be great that for starters it just allows filtering with multiple tags. Then from there we can start to support more advance feature such as this.

**Comment by Bonjour123** [comment]
Sure ! But knowing this is going to be on the road map allows to design efficient code structure that will be easy to extend in the future..
