### ISSUE TITLE
Editor IME composing event behavior issue not fixed by #3267

### ISSUE THREAD

**Issue by Skywt2003** [usememos/memos#3285]
### Describe the bug

#3267 并不能解决 macOS 上 Safari 的 #3263 这一问题。

经过测试，macOS 上 Safari 浏览器下 `event.isComposing` 的表现和 Chrome / Firefox 有所不同，上述情境发生时，Chrome / Firefox 中 `isComposing` 为 true，而 Safari 中为 false。如果只判断 `isComposing`，问题会仍然存在。

建议根据 [MDN.文档](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/keydown_event)，加上 `event.keyCode` 来判断（虽然 deprecated）。

（没有找到关于此问题的官方报告，只找到相关的一篇博客：https://fdream.net/blog/article/1288 ）

#3267 does not address issue #3263 with Safari on macOS.

After testing, the performance of `event.isComposing` in Safari on macOS is different from that of Chrome/Firefox. When the above situation occurs, `isComposing` in Chrome/Firefox is true. In Safari, it is false. If you judge only `isComposing`, the problem still exists.

Suggestions according to the [MDN Document](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/keydown_event), Add `event.keyCode` to determine (although deprecated).

(found no official report about this problem, only found a blog: https://fdream.net/blog/article/1288).

### Steps to reproduce

Same as #3263 

### The version of Memos you're using

v0.21.0

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/8bba7f706e8f77656665a75b854575a317abb39c
