### ISSUE TITLE
编辑状态下，如果刷新页面，编辑框上的 “Editing...” 和 Cancel按钮就会消失

### ISSUE THREAD

**Issue by Zeng1998** [usememos/memos#329]
### Describe the bug

好像是刷新后 `editorState.editMemoId` 这个就变成undefined了。

（但我不知道怎么修比较好

### Steps to reproduce

1. 双击进入编辑状态
2. 刷新页面

### Expected behavior

刷新前后页面状态一致

**Comment by boojack** [comment]
符合预期。

**Comment by Zeng1998** [comment]
> 符合预期。

Hi, do you think we should use `redux-persist` package to keep the editor state when refresh the page?
