### ISSUE TITLE
Feature: Setting to remove user visibility from explore - from unauth users

### ISSUE THREAD

**Issue by bestrocker221** [usememos/memos#3290]
### Describe the solution you'd like

As of now, a non authenticated user can go to Explore and view on thee right column the available users that registered to the platform.

It would be nice if there would be a feature to turn that off, so that no information is leaked to unauthenticated users.

This is important for private instances where only allowed user should be able to use Memos and view the members.

### Type of feature

API

### Additional context

Probably is not just an UI feature, but the `/memos.api.v2.UserService/SearchUsers` API authorization

**Comment by boojack** [comment]
Duplicated with https://github.com/usememos/memos/issues/3265
