### ISSUE TITLE
Unknown error while browsing memo list

### ISSUE THREAD

**Issue by yihanglee-cn** [usememos/memos#3294]
### Describe the bug

There are 500+ records in memos, An unknown error occurred when I browse from the newest to the oldest record and some records were not completely browsed.
This problem is 100% guaranteed. As long as I browse to the records of September last year,this error will definitely appear.
![PixPin_2024-04-29_15-00-39](https://github.com/usememos/memos/assets/31716253/ee759cc1-ca0c-491d-b65b-245dea73f77c)

### Steps to reproduce

Keep browsing the memos until all of them are browsed

### The version of Memos you're using

0.21

**Comment by boojack** [comment]
Please try again in the latest version `v0.22.0`.
