### ISSUE TITLE
T9 does not work when typing on android

### ISSUE THREAD

**Issue by steam3d** [usememos/memos#3296]
### Describe the bug

When I create a new note the smartphone (android) keyboard does not offer T9 words during typing.

### Steps to reproduce

1. Open browser on android device
2. Open and login memos demo
3. Create a new note and try typing something

### The version of Memos you're using

0.21.0

**Comment by boojack** [comment]
The input method is what's on your device, and there's no way to change that option by memos webside. Could you take a check that if you can switch to T9 words on another website?

**Comment by steam3d** [comment]
@boojack Yes, it works everywhere except memos

**Comment by steam3d** [comment]
There was Samsung browser limitation. It disables T9 on incognito mode.
