### ISSUE TITLE
Drag and drop to update resource orders in editor

### ISSUE THREAD

**Issue by boojack** [usememos/memos#3297]
<img width="762" alt="image" src="https://github.com/usememos/memos/assets/161408495/2b6cb089-111f-4d74-8357-047dc3efb5f1">

* https://github.com/react-dnd/react-dnd
* https://github.com/clauderic/dnd-kit

**Comment by MehadND** [comment]
Just wanted to clarify that there will be **two separate** DnD spaces right?

1. All used/referenced resources.
2. Unused resources.

--- 
Also I think another bit of enhancement we could do is to create some sort of drop area where we can drop resources and they will get deleted.

**Comment by michaelien** [comment]
@MehadND It's meaning the resource order in the editor not resource's dashboard.

**Comment by MehadND** [comment]
@michaelien Ah okay I misunderstood. Got it so basically when we creating or editing a memo we can arrange the order of resources or does images inside a memo also count

**Comment by MehadND** [comment]
> @MehadND Thanks, it seems like a better choice, with more detailed documentation and examples. https://github.com/clauderic/dnd-kit

Yes and also looks easier to setup and has been getting updates recently. Glad I could help
