### ISSUE TITLE
Migration to 0.21 messed up the date

### ISSUE THREAD

**Issue by lythandas** [usememos/memos#3303]
### Describe the bug

I have just updated my container from 0.19 to 0.21 and the migration went well but in the end the date of some messages is messed up. Some show a different date than the posted date (maybe date of modification instead of original post date) and some other show as posted last month, although they are several month older.

Additionnally, is there a way to modify the date of the messages ? 

### Steps to reproduce

Update usememos to 0.21

### The version of Memos you're using

0.21

**Comment by michaelien** [comment]
> maybe date of modification instead of original post date

You can turn off the option to display by update time in the settings page.
