### ISSUE TITLE
Change Memos Web UI port using IPVLAN

### ISSUE THREAD

**Issue by rohoal1012** [usememos/memos#3305]
### Describe the solution you'd like

I want to change memos webui port to the port 80 but i cant because i dont use bridge network on docker, i use ipvlan network mode so i cant change the forward port on the compose, so pleaseee a option to change the webui port directlyyyy 🙏🏻🙏🏻🙏🏻🙏🏻

### Type of feature

User Interface (UI)

**Comment by Dubzer** [comment]
I think you can just add a port argument to your docker compose. 
See [memos arguments list](https://www.usememos.com/docs/install/self-hosting#:~:text=for%20incoming%20connections.-,port,-(%2Dp%2C%20%2D%2Dport)%3A) and [docker compose reference](https://docs.docker.com/compose/compose-file/05-services/#command)
