### ISSUE TITLE
Support for armv71 architecture?

### ISSUE THREAD

**Issue by gaston-arg** [usememos/memos#3306]
### Describe the solution you'd like

It'd be awesome if we could install Memos on ARMv71 CPUs as well.
When trying to deploy the Docker Container, I get: "no matching manifest for linux/arm/v7 in the manifest list entries"

Thanks!

### Type of feature

Other

### Additional context

Using Orange Pi Zero

**Comment by moehanabi** [comment]
try `docker build` at repo root directory

**Comment by gaston-arg** [comment]
Hey, never used docker build before. I should then clone the whole repo to my server, then execute that command? 
Thanks

**Comment by moehanabi** [comment]
> Hey, never used docker build before. I should then clone the whole repo to my server, then execute that command? Thanks

yes and `git checkout v0.21.0` is strongly recommended to use latest "stable" version rather than unfinished main branch.

**Comment by gaston-arg** [comment]
Sorry again, I'm clearly missing something. I cloned the repo, then executed the command, but there are some arguments I don't know how to use.

`gasto@orangepizero:~/repos/memos$ ls
CODEOWNERS  LICENSE    SECURITY.md  docs    go.sum    plugin  scripts  store  web
Dockerfile  README.md  bin          go.mod  internal  proto   server   test
gasto@orangepizero:~/repos/memos$ docker build
ERROR: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.

Usage:  docker buildx build [OPTIONS] PATH | URL | -

Start a build`

**Comment by gaston-arg** [comment]
Okay, I finally used this command on the memos cloned dir:
`docker build . -t my-web-app -f Dockerfile`

But then got a bunch of errors:

`=> ERROR [frontend 5/6] RUN corepack enable && pnpm i --frozen-lockfile                                            187.3s
 => [backend 2/4] WORKDIR /backend-build                                                                              3.4s
 => [backend 3/4] COPY . .                                                                                           18.2s
 => CANCELED [backend 4/4] RUN CGO_ENABLED=0 go build -o memos ./bin/memos/main.go                                   69.0s
------
 > [frontend 5/6] RUN corepack enable && pnpm i --frozen-lockfile:
12.58 Corepack is about to download https://registry.npmjs.org/pnpm/-/pnpm-9.0.6.tgz.
32.16 Lockfile is up to date, resolution step is skipped
34.13 Progress: resolved 1, reused 0, downloaded 0, added 0
37.89 Packages: +663
37.89 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
38.13 Progress: resolved 663, reused 0, downloaded 0, added 0
42.14 Progress: resolved 663, reused 0, downloaded 1, added 0
43.22 Progress: resolved 663, reused 0, downloaded 10, added 0
44.26 Progress: resolved 663, reused 0, downloaded 15, added 0
45.25 Progress: resolved 663, reused 0, downloaded 20, added 7
46.26 Progress: resolved 663, reused 0, downloaded 28, added 13
47.40 Progress: resolved 663, reused 0, downloaded 38, added 25
48.60 Progress: resolved 663, reused 0, downloaded 51, added 38
49.59 Progress: resolved 663, reused 0, downloaded 55, added 47
50.76 Progress: resolved 663, reused 0, downloaded 61, added 51
52.06 Progress: resolved 663, reused 0, downloaded 67, added 55
53.26 Progress: resolved 663, reused 0, downloaded 68, added 55
54.27 Progress: resolved 663, reused 0, downloaded 70, added 63
55.28 Progress: resolved 663, reused 0, downloaded 71, added 63
56.29 Progress: resolved 663, reused 0, downloaded 75, added 67
57.80 Progress: resolved 663, reused 0, downloaded 76, added 67
58.99 Progress: resolved 663, reused 0, downloaded 78, added 67
60.02 Progress: resolved 663, reused 0, downloaded 80, added 67
61.06 Progress: resolved 663, reused 0, downloaded 83, added 70
62.37 Progress: resolved 663, reused 0, downloaded 90, added 75
63.39 Progress: resolved 663, reused 0, downloaded 93, added 77
64.41 Progress: resolved 663, reused 0, downloaded 93, added 78
65.55 Progress: resolved 663, reused 0, downloaded 95, added 80
66.62 Progress: resolved 663, reused 0, downloaded 99, added 84
67.67 Progress: resolved 663, reused 0, downloaded 105, added 93
68.84 Progress: resolved 663, reused 0, downloaded 105, added 95
71.46 Progress: resolved 663, reused 0, downloaded 106, added 95
72.47 Progress: resolved 663, reused 0, downloaded 108, added 101
73.47 Progress: resolved 663, reused 0, downloaded 109, added 104
76.66 Progress: resolved 663, reused 0, downloaded 110, added 104
77.67 Progress: resolved 663, reused 0, downloaded 111, added 105
79.33 Progress: resolved 663, reused 0, downloaded 112, added 105
80.33 Progress: resolved 663, reused 0, downloaded 116, added 105
81.34 Progress: resolved 663, reused 0, downloaded 117, added 105
82.34 Progress: resolved 663, reused 0, downloaded 118, added 105
83.38 Progress: resolved 663, reused 0, downloaded 123, added 108
84.73 Progress: resolved 663, reused 0, downloaded 124, added 109
85.73 Progress: resolved 663, reused 0, downloaded 126, added 110
86.75 Progress: resolved 663, reused 0, downloaded 130, added 116
87.75 Progress: resolved 663, reused 0, downloaded 135, added 119
88.76 Progress: resolved 663, reused 0, downloaded 144, added 133
89.80 Progress: resolved 663, reused 0, downloaded 152, added 136
90.83 Progress: resolved 663, reused 0, downloaded 159, added 143
91.84 Progress: resolved 663, reused 0, downloaded 163, added 152
92.85 Progress: resolved 663, reused 0, downloaded 173, added 160
93.86 Progress: resolved 663, reused 0, downloaded 180, added 164
94.89 Progress: resolved 663, reused 0, downloaded 186, added 171
95.90 Progress: resolved 663, reused 0, downloaded 200, added 187
96.94 Progress: resolved 663, reused 0, downloaded 209, added 197
97.94 Progress: resolved 663, reused 0, downloaded 215, added 205
98.95 Progress: resolved 663, reused 0, downloaded 217, added 206
99.97 Progress: resolved 663, reused 0, downloaded 221, added 209
101.0 Progress: resolved 663, reused 0, downloaded 233, added 218
102.0 Progress: resolved 663, reused 0, downloaded 242, added 231
103.0 Progress: resolved 663, reused 0, downloaded 256, added 243
104.1 Progress: resolved 663, reused 0, downloaded 268, added 255
105.1 Progress: resolved 663, reused 0, downloaded 278, added 262
106.1 Progress: resolved 663, reused 0, downloaded 286, added 274
107.1 Progress: resolved 663, reused 0, downloaded 305, added 288
108.1 Progress: resolved 663, reused 0, downloaded 308, added 295
109.1 Progress: resolved 663, reused 0, downloaded 321, added 305
110.1 Progress: resolved 663, reused 0, downloaded 333, added 326
111.1 Progress: resolved 663, reused 0, downloaded 340, added 332
112.1 Progress: resolved 663, reused 0, downloaded 343, added 335
113.1 Progress: resolved 663, reused 0, downloaded 355, added 340
114.1 Progress: resolved 663, reused 0, downloaded 374, added 370
115.1 Progress: resolved 663, reused 0, downloaded 380, added 373
116.1 Progress: resolved 663, reused 0, downloaded 385, added 374
117.1 Progress: resolved 663, reused 0, downloaded 386, added 376
118.1 Progress: resolved 663, reused 0, downloaded 389, added 376
119.1 Progress: resolved 663, reused 0, downloaded 394, added 381
120.2 Progress: resolved 663, reused 0, downloaded 396, added 384
121.2 Progress: resolved 663, reused 0, downloaded 396, added 385
122.2 Progress: resolved 663, reused 0, downloaded 400, added 388
123.2 Progress: resolved 663, reused 0, downloaded 400, added 389
124.2 Progress: resolved 663, reused 0, downloaded 413, added 397
125.2 Progress: resolved 663, reused 0, downloaded 422, added 411
126.2 Progress: resolved 663, reused 0, downloaded 432, added 418
127.2 Progress: resolved 663, reused 0, downloaded 434, added 422
128.2 Progress: resolved 663, reused 0, downloaded 445, added 431
129.2 Progress: resolved 663, reused 0, downloaded 449, added 435
130.2 Progress: resolved 663, reused 0, downloaded 450, added 436
131.2 Progress: resolved 663, reused 0, downloaded 460, added 447
132.3 Progress: resolved 663, reused 0, downloaded 462, added 448
133.3 Progress: resolved 663, reused 0, downloaded 476, added 461
134.4 Progress: resolved 663, reused 0, downloaded 488, added 477
135.5 Progress: resolved 663, reused 0, downloaded 496, added 490
136.5 Progress: resolved 663, reused 0, downloaded 501, added 493
137.5 Progress: resolved 663, reused 0, downloaded 507, added 498
138.7 Progress: resolved 663, reused 0, downloaded 512, added 501
139.7 Progress: resolved 663, reused 0, downloaded 513, added 502
140.7 Progress: resolved 663, reused 0, downloaded 515, added 505
141.7 Progress: resolved 663, reused 0, downloaded 519, added 507
142.8 Progress: resolved 663, reused 0, downloaded 530, added 515
143.8 Progress: resolved 663, reused 0, downloaded 534, added 520
144.8 Progress: resolved 663, reused 0, downloaded 535, added 522
145.8 Progress: resolved 663, reused 0, downloaded 537, added 524
146.8 Progress: resolved 663, reused 0, downloaded 538, added 525
147.8 Progress: resolved 663, reused 0, downloaded 540, added 525
148.8 Progress: resolved 663, reused 0, downloaded 546, added 531
149.9 Progress: resolved 663, reused 0, downloaded 556, added 543
150.9 Progress: resolved 663, reused 0, downloaded 568, added 558
151.9 Progress: resolved 663, reused 0, downloaded 576, added 562
152.9 Progress: resolved 663, reused 0, downloaded 581, added 566
153.9 Progress: resolved 663, reused 0, downloaded 591, added 576
154.9 Progress: resolved 663, reused 0, downloaded 594, added 579
155.9 Progress: resolved 663, reused 0, downloaded 600, added 587
157.0 Progress: resolved 663, reused 0, downloaded 606, added 593
158.0 Progress: resolved 663, reused 0, downloaded 612, added 596
159.1 Progress: resolved 663, reused 0, downloaded 619, added 605
160.1 Progress: resolved 663, reused 0, downloaded 625, added 609
161.1 Progress: resolved 663, reused 0, downloaded 628, added 619
162.1 Progress: resolved 663, reused 0, downloaded 637, added 624
163.2 Progress: resolved 663, reused 0, downloaded 646, added 637
164.2 Progress: resolved 663, reused 0, downloaded 650, added 641
165.2 Progress: resolved 663, reused 0, downloaded 662, added 652
165.6 Progress: resolved 663, reused 0, downloaded 663, added 663, done
174.1 .../node_modules/protobufjs postinstall$ node scripts/postinstall
176.5 .../node_modules/@bufbuild/buf postinstall$ node ./install.js
176.6 .../esbuild@0.20.2/node_modules/esbuild postinstall$ node install.js
183.0 .../node_modules/@bufbuild/buf postinstall: /frontend-build/web/node_modules/.pnpm/@bufbuild+buf@1.30.0/node_modules/@bufbuild/buf/install.js:52
183.1 .../node_modules/@bufbuild/buf postinstall:     throw new Error(`Unsupported platform: ${platformKey}`);
183.1 .../node_modules/@bufbuild/buf postinstall:           ^
183.1 .../node_modules/@bufbuild/buf postinstall: Error: Unsupported platform: linux arm LE
183.1 .../node_modules/@bufbuild/buf postinstall:     at pkgAndSubpathForCurrentPlatform (/frontend-build/web/node_modules/.pnpm/@bufbuild+buf@1.30.0/node_modules/@bufbuild/buf/install.js:52:11)
183.1 .../node_modules/@bufbuild/buf postinstall:     at checkAndPreparePackage (/frontend-build/web/node_modules/.pnpm/@bufbuild+buf@1.30.0/node_modules/@bufbuild/buf/install.js:94:28)
183.1 .../node_modules/@bufbuild/buf postinstall:     at checkAllBinaries (/frontend-build/web/node_modules/.pnpm/@bufbuild+buf@1.30.0/node_modules/@bufbuild/buf/install.js:115:30)
183.1 .../node_modules/@bufbuild/buf postinstall:     at Object.<anonymous> (/frontend-build/web/node_modules/.pnpm/@bufbuild+buf@1.30.0/node_modules/@bufbuild/buf/install.js:162:1)
183.1 .../node_modules/@bufbuild/buf postinstall:     at Module._compile (node:internal/modules/cjs/loader:1369:14)
183.1 .../node_modules/@bufbuild/buf postinstall:     at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
183.1 .../node_modules/@bufbuild/buf postinstall:     at Module.load (node:internal/modules/cjs/loader:1206:32)
183.1 .../node_modules/@bufbuild/buf postinstall:     at Module._load (node:internal/modules/cjs/loader:1022:12)
183.1 .../node_modules/@bufbuild/buf postinstall:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
183.1 .../node_modules/@bufbuild/buf postinstall:     at node:internal/main/run_main_module:28:49
183.1 .../node_modules/@bufbuild/buf postinstall: Node.js v20.12.2
183.3 .../node_modules/protobufjs postinstall: Done
183.4 .../node_modules/@bufbuild/buf postinstall: Failed
183.5  ELIFECYCLE  Command failed with exit code 1.
------
Dockerfile:9
--------------------
   7 |     WORKDIR /frontend-build/web
   8 |
   9 | >>> RUN corepack enable && pnpm i --frozen-lockfile
  10 |
  11 |     RUN pnpm build
--------------------
ERROR: failed to solve: process "/bin/sh -c corepack enable && pnpm i --frozen-lockfile" did not complete successfully: exit code: 1`

**Comment by moehanabi** [comment]
> 183.1 .../node_modules/@bufbuild/buf postinstall: throw new Error(Unsupported platform: ${platformKey});
> 183.1 .../node_modules/@bufbuild/buf postinstall: ^
> 183.1 .../node_modules/@bufbuild/buf postinstall: Error: Unsupported platform: linux arm LE

hmm it seems that bufbuild/buf does not support `linux arm LE`, but i found there's an armv7 image in their docker hub.

So maybe you can try submitting a new issue in https://github.com/bufbuild/buf to check if they support `linux arm LE`.

**Comment by gaston-arg** [comment]
Thank you, I'll give that a try.
For the time being I ended up using version 0.15.0, which was the last one with support for armv71: https://hub.docker.com/layers/neosmemo/memos/0.15.0/images/sha256-1c7c215becd4e4b9d7fbe2abd12d56e831cfbbb5e9570ca39f80b698f6b6c835?context=explore

A little bit old, but oh well 🤷🏼‍♂️

**Comment by Tolomaj** [comment]
Hi. I just tried to install memos on Raspberry Pi with the same result (no matching manifest for linux/arm/v7).
I got in same troubles as you and stopped at : bufbuild/buf still does not support Linux Arm LE.
Installing version 0.15.0. works, but it's a quiet old version.

Just asking if you find another way to install a newer version of memos?

**Comment by gaston-arg** [comment]
Hey that's all we got now unfortunately. No other way of getting the latest release on this architecture....

**Comment by nimish-ks** [comment]
> > 183.1 .../node_modules/@bufbuild/buf postinstall: throw new Error(Unsupported platform: ${platformKey});
> > 183.1 .../node_modules/@bufbuild/buf postinstall: ^
> > 183.1 .../node_modules/@bufbuild/buf postinstall: Error: Unsupported platform: linux arm LE
> 
> hmm it seems that bufbuild/buf does not support `linux arm LE`, but i found there's an armv7 image in their docker hub.
> 
> So maybe you can try submitting a new issue in https://github.com/bufbuild/buf to check if they support `linux arm LE`.

Raised a PR https://github.com/bufbuild/buf/pull/3450
