### ISSUE TITLE
Delete tag not working

### ISSUE THREAD

**Issue by kbiits** [usememos/memos#3309]
### Describe the bug

Tag deletion seems not to be working. If the bug is verified, I'm happy to contribute to fixing this.

### Steps to reproduce

1. Go to the tag list
2. Hover on # symbol
3. Click and delete
4. Confirm deletion

The tag should be deleted if the user confirms to delete it, and the frontend should auto-refresh the tag list after deletion

### The version of Memos you're using

latest master (#da535c8)

### Screenshots or additional context

https://github.com/usememos/memos/assets/67781184/579b9682-d265-49aa-b0db-5e50f07e9d5c

**Comment by MehadND** [comment]
Yes experiencing the same issue here as well

![image](https://github.com/usememos/memos/assets/34424878/4ed1246b-82ee-411b-bd0d-21826087315e)
