### ISSUE TITLE
阿里云OSS策略上传图片Failed to save resource

### ISSUE THREAD

**Issue by MCSJOURNEY** [usememos/memos#3322]
### Describe the bug

阿里云OSS上传图片显示Failed to save resource
<img width="217" alt="image" src="https://github.com/usememos/memos/assets/109956830/0d704cc8-51c7-4a64-9307-a515ba1f90cd">

### Steps to reproduce

配置如下
<img width="312" alt="image" src="https://github.com/usememos/memos/assets/109956830/f90d74cd-0b01-47e8-9cc6-2bb74e27770e">

### The version of Memos you're using

0.21.0

**Comment by boojack** [comment]
Please provide a useful error message, either from the browser console or from the backend logs.

**Comment by cimorn** [comment]
<img width="565" alt="image" src="https://github.com/usememos/memos/assets/169135921/2a92105f-a9cc-44ee-8229-ddd969ee5c25">


> Please provide a useful error message, either from the browser console or from the backend logs.
