### ISSUE TITLE
Truenas Memos Instance is terminating every time

### ISSUE THREAD

**Issue by Chris-EduardDunareanu** [usememos/memos#3327]
### Describe the bug

I dont know why the container allways kills it self in truenas, see screenshot below 
I did sucessfully run memos on docker desktop, but i dont know what i am doing wrong, die 10.0.0.27 is the ip address of truenas, see config below.
Pls help me.

### Steps to reproduce

![image](https://github.com/usememos/memos/assets/38765738/532077b4-56fb-463b-9a6c-f98a684e794b)

### The version of Memos you're using

stable

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/38765738/9d6f46b1-978c-419a-8c6f-aee5ad0e4f94)

**Comment by boojack** [comment]
@Chris-EduardDunareanu Any error message from docker logs?

**Comment by Chris-EduardDunareanu** [comment]
![image](https://github.com/usememos/memos/assets/38765738/cf26d0ac-bc9a-449c-8954-a637e9593762)
this is the only error i am getting when i am trying to login into the terminal of the container

the docker container terminates itself after 1 sec everytime

**Comment by Chris-EduardDunareanu** [comment]
![image](https://github.com/usememos/memos/assets/38765738/b5cbf164-839f-451a-a33b-cfb85611ae36)
this is of a log from a deleted container.
