### ISSUE TITLE
0.6.1对0.6.0版本以前录入的信息不兼容，无法显示。

### ISSUE THREAD

**Issue by anno189** [usememos/memos#334]
### Describe the bug

回退到0.6.0可以显示。

### Steps to reproduce

回退到0.6.0可以显示。

### Expected behavior

回退到0.6.0可以显示。

**Comment by anno189** [comment]
估计是数据表升级之类导致的。
作为过度版本也可以不考虑这个问题了。
后来的人也不会遇到这个问题了。

我先用0.6.0了，等到正式的大版本升级。
我关闭这个问题了。

**Comment by anno189** [comment]
估计是数据表升级之类导致的。
作为过度版本也可以不考虑这个问题了。
后来的人也不会遇到这个问题了。

我先用0.6.0了，等到正式的大版本升级。
我关闭这个问题了。

**Comment by boojack** [comment]
> 估计是数据表升级之类导致的。

从 0.6.0 升级到 0.6.1 不需要“数据表升级”。

从 issue 的角度，建议完善一下问题的描述，哪种内容会出现“不兼容，无法显示”的问题。

**Comment by anno189** [comment]
目前我在用数据库经历的版本比较多。

0.4.5 升级 0.5.0，回退0.4.5，升级0.6.0，升级0.6.1，回退0.6.0。
我不确定除了我在用的数据库问题是否还能复现。

我大概在10月16日左右升级的0.6.0，一切正常。
当时的数据库是0.4.5 升级 0.5.0，回退0.4.5，

升级到0.6.1之后，10月16日之前录入的数据无法出现在列表中了。估计应该是从表中取数的时候就没有取到。
回退到0.6.0又可以了。

我觉得这个情况可能无法复现，或者复现起来比较麻烦。
还是建议先不处理这个问题了。

**Comment by boojack** [comment]
因为小版本升级不会变更表结构，可能是前端的问题，和数据没有关系。你可以给一下升级到 0.6.1 后，“无法显示”具体的报错信息。

**Comment by boojack** [comment]
BTW，0.6.1加入了分页，不会一次拉取所有数据，需要手动点一下加载更多。

**Comment by anno189** [comment]
好吧，我知道了，也是刚刚注意到。新增加了分页。这是一个交互方式的误会。

由此产生的问题是点击 左边的 Tag，列表中没有数据。
