### ISSUE TITLE
Getting a list error after migrate from 0.18 to 0.21

### ISSUE THREAD

**Issue by lucky13820** [usememos/memos#3340]
### Describe the bug

I upgraded to 0.21 via Docker Compose today from 0.18. I can log in, but it won't load any data. After searching the Issues, it looks like the new version has a new database schema. So I tried to create a new Cloudflare R2 bucket. But it still couldn't work. I'm not sure what I should try now. 

```
Uncaught (in promise) ClientError: /memos.api.v2.TagService/ListTags INTERNAL: failed to list tags: SQL logic error: no such table: tag (1)

Uncaught (in promise) ClientError: /memos.api.v2.MemoService/ListMemos INTERNAL: failed to convert memo: failed to list memo resources: rpc error: code = Internal desc = failed to list resources
```

### Steps to reproduce

Upgrade to 0.21 via Docker Compose
Log in to memos
Seeing the error in the console, not seeing any data. 

### The version of Memos you're using

0.21

### Screenshots or additional context

![CleanShot 2024-05-10 at 17 10 57](https://github.com/usememos/memos/assets/7293811/2f64044e-cf32-4702-b806-bceb13a6ff71)

**Comment by sslxf000** [comment]
Same error, the watchtower auto upgrade the memos's container, and now i can't login to the web, tried downgrade to version: 0.21.0
![image](https://github.com/usememos/memos/assets/6456695/2639b593-75bb-495a-9a05-c55a4502b4c1)


![image](https://github.com/usememos/memos/assets/6456695/a8635c59-cceb-4fa9-9753-84fd7a41ebe8)

**Comment by michaelien** [comment]
Maybe your memos had been updated automatically. We will adjust the tags after v0.22.0 and the tag table will be removed. You can try to update to v0.22.0 manually first, it will fix the problem.

**Comment by lucky13820** [comment]
Yes, I updated it by using the stable tag, which is 0.21.0. Manually update to 0.22.0 fixed the problem. Thanks.

**Comment by hjxhjxjx** [comment]
可以看看这一篇https://github.com/usememos/memos/issues/3348#issuecomment-2106081619
