### ISSUE TITLE
clarification about docker image version

### ISSUE THREAD

**Issue by mvivaldi** [usememos/memos#3343]
### Describe the bug

Today, during the update process, my Renovate tool attempted to update the image of neosmemo/memos to the tag 0.22.0. Upon checking Docker Hub (https://hub.docker.com/r/neosmemo/memos/tags), I found that the 0.22.0 tag exists. However I couldn't find any mention of the 0.22.0 tag on the main repository or the website (https://www.usememos.com/).
Normally (at least with other repos/images) I expect to see the repository  with the new release and then the website or the docker image after some time (hours usually). 
Am I doing something wrong (I triple checked if I used the right image and not something different)? 
Sorry to open this as a bug, but I'm a little confused.
Thank you

### Steps to reproduce

wait for a new release

### The version of Memos you're using

0.21.0

**Comment by michaelien** [comment]
We'll build the docker image before releasing, then we internally test the necessary functionality and create a new release note if everythins is OK. So this is a normal operation, you can use `stable` tag so that maybe your tool doesn't try to update.

**Comment by mvivaldi** [comment]
I understand the issue. With the image tagged in this manner, I encounter a problem with my infrastructure. I make it a practice to version everything, ensuring that my installation is always reproducible. Consequently, I avoid tags like "latest" or similar (in this case, "stable"), as relying on them might lead to inconsistencies when duplicating my installation.

To manage upgrades, I utilize renovate (https://docs.renovatebot.com/), which generates a merge request in my Git repository. If I'm confident about the new version, I simply merge the commit.

This issue could be resolved by appending a suffix to the image tag (for instance, "0.22.0-pre"), so that renovate recognizes it as a non-stable version. Subsequently, the stable version could be released with tags such as "0.22.0" and "stable".

I would like to note that this suggestion is simply an option I am proposing. English is not my primary language, so if it sounds impolite, it was not my intention.

Thank you!
