### ISSUE TITLE
USER_SETTING_KEY_UNSPECIFIED"

### ISSUE THREAD

**Issue by cvandingelen** [usememos/memos#3346]
### Describe the bug

When updating to the lastest version, I suddenly get 

`ERROR server error method=/memos.api.v1.UserService/GetUserSetting error="rpc error: code = Internal desc = failed to list user settings: unsupported user setting key: USER_SETTING_KEY_UNSPECIFIED"`

### Steps to reproduce

1. Update to latest version

### The version of Memos you're using

latest

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/13299409/0f228b5b-66f6-4dbe-8cb9-7dfe591dfd84)

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/087f60ba7b85e40fee1c909274232aa4e108037b

**Comment by cvandingelen** [comment]
Should I do something? Still get the same error
