### ISSUE TITLE
iOS客户端,大吉做的STUN内网穿透,docker版,用域名登录时提示,未能读取数据 因为它的格式不正确,用网页端就能正常登录

### ISSUE THREAD

**Issue by chmdir** [usememos/memos#3351]
### Describe the solution you'd like

VPS做zerotier内网穿透,caddy反代,iOS客户端域名登录也是提示,未能读取数据 因为它的格式不正确,用网页端就能正常登录

### Type of feature

User Experience (UX)

**Comment by michaelien** [comment]
Maybe it's not so relevant to this repo.
