### ISSUE TITLE
Cannot find several settings on v0.22.0

### ISSUE THREAD

**Issue by cypherod** [usememos/memos#3352]
### Describe the bug

My docker container has been updated automatically by Watchtower.
At first, I can't login the service but it was solved before a few hour.

My all memo data has been saved on Cloudflare R2, but I can't access my memo on 0.22.0
So I try to set again Storage on Setting tab, However I can't find it. It seems like disapeared.
I can select storage. Database, Local and S3. Where is R2?

Moreover, Telegram bot token option also disappeared on v0.22.0

I tried downgrade to 0.21.0 but I can't still access memo data. When I check the log, I can see an error message as below.
"RPC error, internal desc" it is same issue #

### Steps to reproduce

Update image from 0.21.0 to 0.22.0

### The version of Memos you're using

v0.22.0

**Comment by boojack** [comment]
> My all memo data has been saved on Cloudflare R2, but I can't access my memo on 0.22.0

Memos always needs a database, only file resources such as images can be stored in S3.

> So I try to set again Storage on Setting tab, However I can't find it. It seems like disapeared. I can select storage. Database, Local and S3. Where is R2?

Cloudflare R2 is an **S3-compatible**, zero egress-fee, object storage. https://www.cloudflare.com/developer-platform/r2/

> Moreover, Telegram bot token option also disappeared on v0.22.0

We plan to deprecate the built-in telegram integration after v0.22.0. And will start a separate project to do this.

---

However, some of the previous workspace settings(including resource storage) will need to be manually reset, and we'll provide a documentation for this after the official release.

**Comment by boojack** [comment]
And it is not recommended to update automatically, Memos is still in active development.

**Comment by Baoyx007** [comment]
how downgrade to 0.21.0 properly

**Comment by penguinsam** [comment]
I am downgrading to 0.21 also because of the deprecation of telegram integration

**Comment by liuyanfight** [comment]
It's really unbelievable to remove a useful function without any compensation for now. I fully understand and appreciate everything the developers have done.However, I wasn't aware that the Telegram bot had been removed during the upgrade, which is now causing significant inconvenience. You introduced the Telegram bot and recommended it to users, who came to rely on it daily. Now, removing it abruptly undermines trust and leaves me very disappointed.

**Comment by MilkTeaNo7** [comment]
It really baffles me. A function that had been working perfectly fine was abruptly removed. Instead, we are now forced to use a much more cumbersome approach to accomplish the exact same task. What's more, this new alternative is not only more complicated but also fails to bring any new functionality.
