### ISSUE TITLE
update bug:client error method=/memos.api.v1.AuthService/GetAuthStatus error="rpc error: code = Unauthenticated desc = user not found"

### ISSUE THREAD

**Issue by gygy** [usememos/memos#3354]
### Describe the bug

---
Server profile
version: 0.22.0
data: /var/opt/memos
dsn: /var/opt/memos/memos_prod.db
addr: 
port: 5230
mode: prod
driver: sqlite
---
Version 0.22.0 has been started on port 5230
---

See more in:
👉Website: https://usememos.com
👉GitHub: https://github.com/usememos/memos
---
███╗   ███╗███████╗███╗   ███╗ ██████╗ ███████╗
████╗ ████║██╔════╝████╗ ████║██╔═══██╗██╔════╝
██╔████╔██║█████╗  ██╔████╔██║██║   ██║███████╗
██║╚██╔╝██║██╔══╝  ██║╚██╔╝██║██║   ██║╚════██║
██║ ╚═╝ ██║███████╗██║ ╚═╝ ██║╚██████╔╝███████║
╚═╝     ╚═╝╚══════╝╚═╝     ╚═╝ ╚═════╝ ╚══════╝
2024/05/12 13:38:02 INFO client error method=/memos.api.v1.AuthService/GetAuthStatus error="rpc error: code = Unauthenticated desc = user not found"
2024/05/12 13:38:02 INFO OK method=/memos.api.v1.WorkspaceService/GetWorkspaceProfile
2024/05/12 13:38:02 INFO OK method=/memos.api.v1.WorkspaceSettingService/GetWorkspaceSetting
2024/05/12 13:38:04 INFO client error method=/memos.api.v1.AuthService/GetAuthStatus error="rpc error: code = Unauthenticated desc = user not found"
2024/05/12 13:38:04 INFO OK method=/memos.api.v1.WorkspaceService/GetWorkspaceProfile
2024/05/12 13:38:05 INFO OK method=/memos.api.v1.WorkspaceSettingService/GetWorkspaceSetting
2024/05/12 13:38:06 INFO OK method=/memos.api.v1.UserService/SearchUsers
2024/05/12 13:38:06 INFO OK method=/memos.api.v1.MemoService/ListMemos
2024/05/12 13:38:08 INFO OK method=/memos.api.v1.IdentityProviderService/ListIdentityProviders
2024/05/12 13:38:12 INFO OK method=/memos.api.v1.AuthService/SignIn
2024/05/12 13:38:12 INFO OK method=/memos.api.v1.AuthService/GetAuthStatus
2024/05/12 13:38:12 INFO OK method=/memos.api.v1.UserService/GetUserSetting
2024/05/12 13:38:12 INFO OK method=/memos.api.v1.InboxService/ListInboxes
2024/05/12 13:38:12 INFO OK method=/memos.api.v1.MemoService/ListMemoTags
2024/05/12 13:38:12 INFO OK method=/memos.api.v1.MemoService/GetUserMemosStats
2024/05/12 13:38:12 INFO OK method=/memos.api.v1.MemoService/ListMemos
2024/05/12 13:38:12 INFO OK method=/memos.api.v1.MemoService/GetUserMemosStats
2024/05/12 13:38:13 INFO OK method=/memos.api.v1.MemoService/ListMemoTags
2024/05/12 13:38:14 INFO OK method=/memos.api.v1.UserService/ListUserAccessTokens
2024/05/12 13:38:14 INFO OK method=/memos.api.v1.WorkspaceSettingService/GetWorkspaceSetting
2024/05/12 13:38:14 INFO OK method=/memos.api.v1.WorkspaceSettingService/GetWorkspaceSetting
2024/05/12 13:38:42 INFO OK method=/memos.api.v1.WorkspaceService/GetWorkspaceProfile
2024/05/12 13:38:42 INFO OK method=/memos.api.v1.AuthService/GetAuthStatus
2024/05/12 13:38:42 INFO OK method=/memos.api.v1.WorkspaceSettingService/GetWorkspaceSetting
2024/05/12 13:38:42 INFO OK method=/memos.api.v1.UserService/GetUserSetting
2024/05/12 13:38:43 INFO OK method=/memos.api.v1.WorkspaceSettingService/GetWorkspaceSetting
2024/05/12 13:38:43 INFO OK method=/memos.api.v1.UserService/ListUserAccessTokens
2024/05/12 13:38:43 INFO OK method=/memos.api.v1.WorkspaceSettingService/GetWorkspaceSetting
2024/05/12 13:38:43 INFO OK method=/memos.api.v1.InboxService/ListInboxes

### Steps to reproduce

client error method=/memos.api.v1.AuthService/GetAuthStatus error="rpc error: code = Unauthenticated desc = user not found"

### The version of Memos you're using

0.22

**Comment by HT-Moh** [comment]
facing similar issue when I navigate to the domain, this error on memos and slash

```json
version: "3"
services:
  memos:
    image: neosmemo/memos:latest
    networks:
      - traefik-public
      - memos-network
    volumes:
      - ./volumes/memos:/var/opt/memos
    environment:
      - MEMOS_INSTANCE_URL=memos.mydomain.com
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.memos.loadbalancer.server.port=5230
        - traefik.http.routers.memos.rule=Host(`memos.mydomain.com`)
        - traefik.http.routers.memos.entrypoints=websecure
        - traefik.http.routers.memos.tls.certresolver=letsencryptresolver
        - traefik.http.routers.memos.middlewares=sslheader@file
        # The username password pair is generated by:
        # echo $(htpasswd -nb admin pass) | sed -e s/\\$/\\$\\$/g

networks:
  traefik-public:
    external: true
  memos-network:
    external: false
```

```
---
Server profile
version: 0.23.0
data: /var/opt/memos
dsn: /var/opt/memos/memos_prod.db
addr: 
port: 5230
mode: prod
driver: sqlite
---
Version 0.23.0 has been started on port 5230
---
See more in:
👉Website: https://usememos.com
👉GitHub: https://github.com/usememos/memos
---
2024/10/26 13:35:06 INFO client error method=/memos.api.v1.WorkspaceService/GetWorkspaceProfile error="rpc error: code = Unauthenticated desc = failed to get access token: authorization header format must be Bearer {token}"
2024/10/26 13:35:06 INFO client error method=/memos.api.v1.AuthService/GetAuthStatus error="rpc error: code = Unauthenticated desc = failed to get access token: authorization header format must be Bearer {token}"
2024/10/26 13:35:09 INFO client error method=/memos.api.v1.WorkspaceService/GetWorkspaceProfile error="rpc error: code = Unauthenticated desc = failed to get access token: authorization header format must be Bearer {token}"
2024/10/26 13:35:09 INFO client error method=/memos.api.v1.AuthService/GetAuthStatus error="rpc error: code = Unauthenticated desc = failed to get access token: authorization header format must be Bearer {token}"
2024/10/26 13:35:28 INFO client error method=/memos.api.v1.WorkspaceService/GetWorkspaceProfile error="rpc error: code = Unauthenticated desc = failed to get access token: authorization header format must be Bearer {token}"
2024/10/26 13:35:28 INFO client error method=/memos.api.v1.AuthService/GetAuthStatus error="rpc error: code = Unauthenticated desc = failed to get access token: authorization header format must be Bearer {token}"
2024/10/26 13:35:44 INFO client error method=/memos.api.v1.WorkspaceService/GetWorkspaceProfile error="rpc error: code = Unauthenticated desc = failed to get access token: authorization header format must be Bearer {token}"
2024/10/26 13:35:44 INFO client error method=/memos.api.v1.AuthService/GetAuthStatus error="rpc error: code = Unauthenticated desc = failed to get access token: authorization header format must be Bearer {token}"
2024/10/26 13:36:02 INFO client error method=/memos.api.v1.AuthService/GetAuthStatus error="rpc error: code = Unauthenticated desc = failed to get access token: authorization header format must be Bearer {token}"
2024/10/26 13:36:02 INFO client error method=/memos.api.v1.WorkspaceService/GetWorkspaceProfile error="rpc error: code = Unauthenticated desc = failed to get access token: authorization header format must be Bearer {token}"
```

**Comment by git-birey** [comment]
我也有这个问题，怎么解决啊
