### ISSUE TITLE
Cannot sign in after the update

### ISSUE THREAD

**Issue by zhonger** [usememos/memos#3357]
### Describe the bug

When I try to sign in after the update, this error happens:
```
failed to sign in, err: rpc error: code = Internal desc = failed to upsert access token to store, err: failed to get user access tokens: sql: Scan error on column index 2, name "value": converting NULL to string is unsupported
```

### Steps to reproduce

Update to v0.21.0 from v.20.0 with docker

### The version of Memos you're using

v0.21.0

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/12064158/5a685c4c-fd3e-493e-b374-7d934de35f40)

**Comment by michaelien** [comment]
This should be a very unusual mistake. Do you have any special operations during the upgrade process? 

The most easy way to deal with it is to manually delete the access tokens data in the `user_setting` table in your database.

**Comment by jmagar** [comment]
Hmmm not sure if this is related or something different, but I'm getting something similar, but only when I'm trying to login with the moememos app with api key or user/pass. Login via Web works fine.

2024/05/13 13:42:37 ERROR unknown error method=/memos.api.v1.AuthService/SignIn error="rpc error: code = InvalidArgument desc = user not found with username "

**Comment by zhonger** [comment]
> This should be a very unusual mistake. Do you have any special operations during the upgrade process?
> 
> The most easy way to deal with it is to manually delete the access tokens data in the `user_setting` table in your database.

 As you suggest, it works after deleting the data in the `user_setting` table.

**Comment by zhonger** [comment]
> > > This should be a very unusual mistake. Do you have any special operations during the upgrade process?
> > > The most easy way to deal with it is to manually delete the access tokens data in the `user_setting` table in your database.
> > 
> > 
> > I haven't done other special operations during the upgrade process. (PS: maybe my usage is quite a little different. I use the docker image on two laptops only connecting them with the database file by OneDrive.)
> > As you suggest, it works after deleting the data in the `user_setting` table.
> 
> I also encountered the same issue; I deleted the contents of the `user_setting` table, but it still doesn't work.

I think you may need to recreate or restart the container. 
After deleting the data in `user_setting`, I also recreate the container with `docker-compose down && docker-compose up -d` 
and test it in another browser (Safari) or a new tab (Chrome).
