### ISSUE TITLE
Suggest adding [Remove unused tags]

### ISSUE THREAD

**Issue by ChiehJang** [usememos/memos#3360]
### Describe the solution you'd like

Sometimes some notes are deleted, but the tags of these notes still remain in the tag bar on the right. When there are many such cases, it becomes messy, with tags everywhere. I hope to add [**Remove unused tags**] in tag management, and I hope to **optimize the tag management page**.😊🙏
---
<img width="175" alt="SCR-20240513-nldu" src="https://github.com/usememos/memos/assets/11803185/40efbb11-9b08-4532-ad6c-6e7243a2234f">

### Type of feature

User Interface (UI)

**Comment by michaelien** [comment]
After `v0.22.0`, the tag will be bound to content, so there is no need to manually delete/manage it.
