### ISSUE TITLE
Allow to modify the created time in UI

### ISSUE THREAD

**Issue by tombatti** [usememos/memos#3362]
### Describe the bug

After the last update I can no longer change the date with the ALT button like I did before. Has this possibility been removed or is it a bug?

Thank you

### Steps to reproduce

1. on a post, click with the mouse on the date or time while holding down the ALT button

### The version of Memos you're using

0.22.0

**Comment by michaelien** [comment]
@tombatti Modifying the creation time should not be a common operation. However, I would like to know what the scenarios are. If possible, I suggest you enable **displaying by update time**, or update it through the API. https://memos.apidocumentation.com/reference#tag/memoservice/patch/api/v1/{memo.name}

**Comment by tombatti** [comment]
Hi
I have already enabled that value in the Settings!
My problem is that I always insert events on dates after they happen, so it's a common practice to then go and change the date or time of the event

But that option was available before the last update, why was it removed (I mean changing the date with the ALT button)

Thank you
Tomas

**Comment by tenebrisnox** [comment]
> Hi I have already enabled that value in the Settings! My problem is that I always insert events on dates after they happen, so it's a common practice to then go and change the date or time of the event
> 

I often do this. I use Memos as a diary and sometimes to forget to add an entry - then when I've do that I change the entry's date. I've just updated to the latest version and it's no longer working.

PLEASE PLEASE PLEASE restore it. 🥺

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/c25c57ab6194c7f70c0efada290247c741aa5b0d You'll be able to change the display time in the edit dialog.

<img width="779" alt="image" src="https://github.com/usememos/memos/assets/24653555/048237b8-7aca-45c9-aaa2-46b91603163c">
