### ISSUE TITLE
Upgrade to the latest version or perform a fresh installation of the latest version, both encounter errors

### ISSUE THREAD

**Issue by gygy** [usememos/memos#3364]
### Describe the bug

1. When upgrading to the latest version 0.22, an issue arises where the Chrome browser extension cannot access memos via the API. The extension I'm using is: [https://chromewebstore.google.com/detail/memos/cbhjebjfccgchgbmfbobjmebjjckgofe](https://chromewebstore.google.com/detail/memos/cbhjebjfccgchgbmfbobjmebjjckgofe).
   
2. Attempting a fresh installation of version 0.22 by deleting all databases and performing a clean installation still results in the same error.

3. On iOS 17, using Moememos, I'm unable to log in. I can't access it regardless of using the account, password, or key.
4. Before the upgrade to 0.22, everything was normal.

### Steps to reproduce

1. upgrading to the latest version 0.22  or Fresh installation
2. Ensure that the domain name and key are correct. When using the browser extension Memos to send content to Memos, it prompts: 'Sending failed.
3. On iOS 17, using Moememos, I'm unable to log in. I can't access it regardless of using the account, password, or key.
4. docker error log ：client error method=/memos.api.v1.AuthService/GetAuthStatus error="rpc error: code = Unauthenticated desc = user not found
`---
Server profile
version: 0.22.0
data: /var/opt/memos
dsn: /var/opt/memos/memos_prod.db
addr: 
port: 5230
mode: prod
driver: sqlite
---
███╗   ███╗███████╗███╗   ███╗ ██████╗ ███████╗
████╗ ████║██╔════╝████╗ ████║██╔═══██╗██╔════╝
██╔████╔██║█████╗  ██╔████╔██║██║   ██║███████╗
██║╚██╔╝██║██╔══╝  ██║╚██╔╝██║██║   ██║╚════██║
Version 0.22.0 has been started on port 5230
---

See more in:
👉Website: https://usememos.com
👉GitHub: https://github.com/usememos/memos
---
██║ ╚═╝ ██║███████╗██║ ╚═╝ ██║╚██████╔╝███████║
╚═╝     ╚═╝╚══════╝╚═╝     ╚═╝ ╚═════╝ ╚══════╝
**2024/05/13 14:41:04 INFO client error method=/memos.api.v1.AuthService/GetAuthStatus error="rpc error: code = Unauthenticated desc = user not found"**
2024/05/13 14:41:04 INFO OK method=/memos.api.v1.WorkspaceService/GetWorkspaceProfile
2024/05/13 14:41:05 INFO OK method=/memos.api.v1.WorkspaceSettingService/GetWorkspaceSetting
2024/05/13 14:41:06 INFO client error method=/memos.api.v1.AuthService/GetAuthStatus error="rpc error: code = Unauthenticated desc = user not found"
2024/05/13 14:41:06 INFO OK method=/memos.api.v1.WorkspaceService/GetWorkspaceProfile
2024/05/13 14:41:07 INFO OK method=/memos.api.v1.WorkspaceSettingService/GetWorkspaceSetting
2024/05/13 14:41:07 INFO OK method=/memos.api.v1.UserService/SearchUsers
2024/05/13 14:41:07 INFO OK method=/memos.api.v1.MemoService/ListMemos
2024/05/13 14:42:04 INFO OK method=/memos.api.v1.AuthService/SignUp
2024/05/13 14:42:04 INFO OK method=/memos.api.v1.AuthService/GetAuthStatus
2024/05/13 14:42:04 INFO OK method=/memos.api.v1.UserService/GetUserSetting
2024/05/13 14:42:04 INFO OK method=/memos.api.v1.InboxService/ListInboxes
2024/05/13 14:42:04 INFO OK method=/memos.api.v1.MemoService/ListMemoTags
2024/05/13 14:42:04 INFO OK method=/memos.api.v1.MemoService/ListMemos
2024/05/13 14:42:04 INFO OK method=/memos.api.v1.MemoService/ListMemoTags
2024/05/13 14:42:08 INFO OK method=/memos.api.v1.WorkspaceSettingService/GetWorkspaceSetting
2024/05/13 14:42:08 INFO OK method=/memos.api.v1.UserService/ListUserAccessTokens
2024/05/13 14:42:09 INFO OK method=/memos.api.v1.WorkspaceSettingService/GetWorkspaceSetting
2024/05/13 14:42:12 INFO OK method=/memos.api.v1.AuthService/GetAuthStatus
2024/05/13 14:42:12 INFO OK method=/memos.api.v1.WorkspaceService/GetWorkspaceProfile
2024/05/13 14:42:12 INFO OK method=/memos.api.v1.UserService/GetUserSetting
2024/05/13 14:42:12 INFO OK method=/memos.api.v1.WorkspaceSettingService/GetWorkspaceSetting
2024/05/13 14:42:19 INFO OK method=/memos.api.v1.UserService/CreateUserAccessToken
2024/05/13 14:42:19 INFO OK method=/memos.api.v1.UserService/ListUserAccessTokens
2024/05/13 14:47:05 INFO OK method=/memos.api.v1.InboxService/ListInboxes
2024/05/13 14:48:28 INFO OK method=/memos.api.v1.WorkspaceService/GetWorkspaceProfile
2024/05/13 14:48:28 INFO OK method=/memos.api.v1.AuthService/GetAuthStatus
2024/05/13 14:48:29 INFO OK method=/memos.api.v1.WorkspaceSettingService/GetWorkspaceSetting
2024/05/13 14:48:29 INFO OK method=/memos.api.v1.UserService/GetUserSetting
2024/05/13 14:48:30 INFO OK method=/memos.api.v1.MemoService/ListMemoTags
2024/05/13 14:48:30 INFO OK method=/memos.api.v1.InboxService/ListInboxes
2024/05/13 14:48:30 INFO OK method=/memos.api.v1.MemoService/ListMemos
2024/05/13 14:48:30 INFO OK method=/memos.api.v1.MemoService/ListMemoTags
2024/05/13 14:52:05 INFO OK method=/memos.api.v1.InboxService/ListInboxes
2024/05/13 14:53:30 INFO OK method=/memos.api.v1.InboxService/ListInboxes
2024/05/13 14:57:05 INFO OK method=/memos.api.v1.InboxService/ListInboxes
2024/05/13 14:58:30 INFO OK method=/memos.api.v1.InboxService/ListInboxes`

### The version of Memos you're using

0.22

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/2096830/1e2e7132-c921-45ff-99f0-e75ca1a9ce11)

![ea80f6640018d02444e65ffb1249e1e](https://github.com/usememos/memos/assets/2096830/e7361971-1362-4454-9a98-0893e40c3fbe)

**Comment by jmagar** [comment]
I'm having the same problem with moememos

**Comment by dominicx** [comment]
拉取容器不要用latest，0.22 有bug。改用stable拉容器。。。。
苦啊。

**Comment by sprdlh** [comment]
我回滚到stable然后登录进去就一直在读取数据出不来了 @dominicx 
`2024/05/14 15:12:09 ERROR server error method=/memos.api.v2.TagService/ListTags error="rpc error: code = Internal desc = failed to list tags: SQL logic error: no such table: tag (1)"
2024/05/14 15:12:09 ERROR server error method=/memos.api.v2.TagService/ListTags error="rpc error: code = Internal desc = failed to list tags: SQL logic error: no such table: tag (1)"
2024/05/14 15:12:09 ERROR server error method=/memos.api.v2.MemoService/ListMemos error="failed to convert memo: failed to list memo resources: rpc error: code = Internal desc = failed to list resources"`

**Comment by sprdlh** [comment]
您发来的邮件我已经收到...

**Comment by gygy** [comment]
> 我回滚到stable然后登录进去就一直在读取数据出不来了 @dominicx 
> 
> `2024/05/14 15:12:09 ERROR server error method=/memos.api.v2.TagService/ListTags error="rpc error: code = Internal desc = failed to list tags: SQL logic error: no such table: tag (1)"
> 
> 2024/05/14 15:12:09 ERROR server error method=/memos.api.v2.TagService/ListTags error="rpc error: code = Internal desc = failed to list tags: SQL logic error: no such table: tag (1)"
> 
> 2024/05/14 15:12:09 ERROR server error method=/memos.api.v2.MemoService/ListMemos error="failed to convert memo: failed to list memo resources: rpc error: code = Internal desc = failed to list resources"`

我的也是一样。用回0.21数据读取不了。

**Comment by michaelien** [comment]
The pre-release v0.22.0 has some API adjustments, and community applications have not adapted to it yet. So you should wait until the officially released and app updates.
