### ISSUE TITLE
memo分页是否需要根据tag的切换来重新加载？

### ISSUE THREAD

**Issue by Zeng1998** [usememos/memos#337]
### Is your feature request related to a problem?

如果某个tag的memo不在第一次加载的memo里面里面，或者只有少数几个，那么当切换到这个tag的列表的时候，就会显示没有memo或者只有少数几个memo，需要再点击加载才能获取更多。

### Describe the solution you'd like

感觉这样体验上稍微有点不好，但不知道如果改成每次tag切换都重新获取一次分页的列表，会不会有比较大的性能损失？

**Comment by Rookiewan** [comment]
+1
![image](https://user-images.githubusercontent.com/13617296/197718938-ded736d0-035b-49ca-9462-081fb1b42a23.png)
