### ISSUE TITLE
ブックマーク機能が欲しいです。

### ISSUE THREAD

**Issue by tocynics** [usememos/memos#3372]
### Describe the solution you'd like

開発者の皆様、ありがとうございます。
いつもありがたく使わせてもらっています。

シンプルにお願いなのですが、ブックマーク機能があるとより使いやすくなるかなと思います。
ぜひご検討ください！

ほんとにいつもありがとう！

### Type of feature

User Experience (UX)

**Comment by speedrapide10** [comment]
I also love to have this feature with a browser `Extention/Shortcut` to `save websites links`.

Thank you very much Dev Team for your awesome work 🦾.
