### ISSUE TITLE
Customer OIDC Doesn't Save

### ISSUE THREAD

**Issue by Node815** [usememos/memos#3373]
### Describe the bug

When configuring a custom OIDC Endpoint, it says it saved successfully, but upon the return, it doesn't show it. 

### Steps to reproduce

Set up SSO and select the custom provider and Save.  

Expected result:  Settings save
End Result:  Settings not saved.  

Not sure if these logs help:

`05/13/2024
02:42:22 PM
2024/05/13 21:42:22 INFO OK method=/memos.api.v1.AuthService/GetAuthStatus
05/13/2024
02:42:23 PM
2024/05/13 21:42:23 INFO OK method=/memos.api.v1.WorkspaceSettingService/GetWorkspaceSetting
05/13/2024
02:42:23 PM
2024/05/13 21:42:23 INFO OK method=/memos.api.v1.UserService/GetUserSetting
05/13/2024
02:42:23 PM
2024/05/13 21:42:23 INFO OK method=/memos.api.v1.UserService/ListUserAccessTokens
05/13/2024
02:42:23 PM
2024/05/13 21:42:23 INFO OK method=/memos.api.v1.WorkspaceSettingService/GetWorkspaceSetting
05/13/2024
02:42:23 PM
2024/05/13 21:42:23 INFO OK method=/memos.api.v1.InboxService/ListInboxes
05/13/2024
02:42:23 PM
2024/05/13 21:42:23 INFO OK method=/memos.api.v1.WorkspaceSettingService/GetWorkspaceSetting
05/13/2024
02:42:25 PM
2024/05/13 21:42:25 INFO OK method=/memos.api.v1.IdentityProviderService/ListIdentityProviders
05/13/2024
02:46:32 PM
2024/05/13 21:46:32 INFO OK method=/memos.api.v1.WorkspaceService/GetWorkspaceProfile
05/13/2024
02:46:32 PM
2024/05/13 21:46:32 INFO OK method=/memos.api.v1.AuthService/GetAuthStatus
05/13/2024
02:46:32 PM
2024/05/13 21:46:32 INFO OK method=/memos.api.v1.WorkspaceSettingService/GetWorkspaceSetting
05/13/2024
02:46:32 PM
2024/05/13 21:46:32 INFO OK method=/memos.api.v1.UserService/GetUserSetting
05/13/2024
02:47:23 PM
2024/05/13 21:47:23 INFO OK method=/memos.api.v1.InboxService/ListInboxes
05/13/2024
02:47:49 PM
2024/05/13 21:47:49 INFO OK method=/memos.api.v1.IdentityProviderService/CreateIdentityProvider
05/13/2024
02:47:49 PM
2024/05/13 21:47:49 INFO OK method=/memos.api.v1.IdentityProviderService/ListIdentityProviders`

### The version of Memos you're using

v0.22.0

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/20736534/6f1566ad-b698-4177-9510-e84d89b8111d)

**Comment by boojack** [comment]
Good catch, it will be fixed with https://github.com/usememos/memos/commit/2317204c508f89d99474beadd0518ea4b99b6fc6
