### ISSUE TITLE
Allow to resize edit popup or have separate page to edit

### ISSUE THREAD

**Issue by akhmadkomodo** [usememos/memos#3382]
### Describe the solution you'd like

It would be great if we can resize the edit content popup window, or have separate page and edit the content in that different page

### Type of feature

User Experience (UX)

### Additional context

I have some big memos, and it's feels so crowded when i need to edit the content since the popup window is so small

![image](https://github.com/usememos/memos/assets/150003670/81205f6d-e9ab-4f1b-85da-3a7e738e671f)

**Comment by quaintdev** [comment]
I feel like the centered memos layout should also be configurable to support a wider layout. Current layout is too narrow.
