### ISSUE TITLE
当还有更多memos时，按钮 Click to fetch more 不可用

### ISSUE THREAD

**Issue by aicezam** [usememos/memos#3383]
### Describe the bug

版本是0.22.0，环境是 群晖 docker 
当前共有85条笔记，第一次点击 Click to fetch more 时，会加载更多数据，但再次到底部，点击 Click to fetch more 时，没有加载更多数据（网络请求成功了的，但没有获取新数据），但这些数据可以通过搜索关键词搜索到；

### Steps to reproduce

1. 第一次点击 Click to fetch more 时，会加载更多数据
2. 滚动到底部，点击 Click to fetch more 时，不会加载更多数据（网络请求成功了的，但没有获取新数据），但这些数据可以通过搜索关键词搜索到；

### The version of Memos you're using

0.22.0

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/39365915/1eb0e32f-b95f-4728-b2f8-5293d2645abc)

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/3e5e5b1f8046cdb7906a548eb65e493948927cd2
