### ISSUE TITLE
七牛云S3存储上传文件报错

### ISSUE THREAD

**Issue by Tonmyn** [usememos/memos#3385]
### Describe the bug

1、无法在 qiniu S3 oss中上传文件
按文档步骤设置了S3存储信息
参考了 #2190 中的解决办法，在endpoint前面增加了'http://'也无法正常上传附件

### 1、首先设置S3存储

> ![image](https://github.com/usememos/memos/assets/18096197/473441cc-d2f8-4faf-9071-9c9922de0568)

### 2、上传附件

> ![image](https://github.com/usememos/memos/assets/18096197/01106c66-e593-4e42-bae6-bf7d77acff3a)

### The version of Memos you're using

0.22.0

### Screenshots or additional context

> failed to save resource blob: Failed to upload via s3 client: operation error S3: PutObject, https response error StatusCode: 403, RequestID: 6qIAAADcjazYns8X, HostID: , api error RequestTimeTooSkewed: The difference between the request time and the server's time is too large

![image](https://github.com/usememos/memos/assets/18096197/e6795cde-e511-43a0-9b5b-d6ce12d6c282)

![image](https://github.com/usememos/memos/assets/18096197/8a3e1fc2-9d43-45fd-a521-a594e8bc2899)

**Comment by michaelien** [comment]
Reference to: https://stackoverflow.com/a/4770683

**Comment by Tonmyn** [comment]
感谢 @michaelien 解决了我的问题

**Comment by Tonmyn** [comment]
这里记录一下 七牛云OSS 在0.22版本中如何添加

1. 填写你的 AK和SK；
2. Endpoint 填写七牛云提供的“Endpoint（区域节点）”，不要填成了“空间域名”；
![image](https://github.com/usememos/memos/assets/18096197/995a51ae-af1f-4667-99df-3a60a73bc141)

3. Region随便填，根据文档填个auto就行了；
4. Bucket填你在七牛云建的空间的名字就行了；

![image](https://github.com/usememos/memos/assets/18096197/93ddf326-cbfe-4ae7-8108-fe8a5cb6509a)
5. 最后点保存；
