### ISSUE TITLE
v0.22.0 slow and buggy

### ISSUE THREAD

**Issue by tenebrisnox** [usememos/memos#3386]
### Describe the bug

Just updated to v0.22.0 and I'm finding it very slow to the point of barely being able to use it. The previous version was running great.

Particularly:
- The "Timeline" is always stuck "Fetching data..."
- The "Resources" section only displays some of the images.
- The "Inbox" indicates there's a message (blue dot) - but there's no messages.
- I have to keep reloading the page to get Memos to show. It's almost unusable for me now.

I've restarted the Docker container in which I run Memos and I've tried this on different machines using Safari and Firefox.

### Steps to reproduce

1. Go to Timeline... 
2. Go to Resources...
3. Go to Inbox...
etc

### The version of Memos you're using

v0.22.0

**Comment by boojack** [comment]
Could you provide some logs from backend about the "stuck" issue?

**Comment by cenzhifang** [comment]
The first one my tags are all gone, the second one the share-picture feature is gone ~ the third one the phone can't log in (apple, android)

**Comment by cenzhifang** [comment]
How to return to the v21 version? I tried it, but the content could not be read. I had no choice but to upgrade to the latest version. After the upgrade, many things could not be displayed and there were many problems.

**Comment by m1732948116** [comment]
我实在不理解便签为啥全没了，点击重构便签不仅不支持二级标签而且很多标签都没有成功导入，why？谁的天才想法啊？？？

**Comment by m1732948116** [comment]
最近的几次更新都不如不更，真心希望好好沉淀一下

**Comment by cenzhifang** [comment]
> 最近的几次更新都不如不更，真心希望好好沉淀一下
每次更新，糟糕的体验，手机端要等才能用。

**Comment by cenzhifang** [comment]
> > Issue is not in English. It has been translated automatically. Issue is not in English. It has been automatically translated.
>
> The last few updates are worse than no updates at all. I really hope it settles down. The last few updates are worse than no updates at all. I really hope it settles down.

How do I go back to version v20-v21? It’s really bad. I’ve lost a lot of stuff.

**Comment by m1732948116** [comment]
> > > Issue is not in English. It has been translated automatically. Issue is not in English. It has been automatically translated.
> > 
> > 
> > The last few updates are worse than no updates at all. I really hope it settles down. The last few updates are worse than no updates at all. I really hope it settles down.
> 
> How do I go back to version v20-v21? It’s really bad. I’ve lost a lot of stuff.

备份下文件把容器删了重新拉一个再映射文件夹，标签用stable

**Comment by cenzhifang** [comment]
> > > > Issue is not in English. It has been translated automatically. Issue is not in English. It has been automatically translated.问题不是英文的。它已被自动翻译。问题不是英文的。它已被自动翻译。
> > > 
> > > 
> > > The last few updates are worse than no updates at all. I really hope it settles down. The last few updates are worse than no updates at all. I really hope it settles down.最后几次更新比根本没有更新更糟糕。我真的希望它能安定下来。最后几次更新比根本没有更新更糟糕。我真的希望它能安定下来。
> > 
> > 
> > How do I go back to version v20-v21? It‘s really bad. I’ve lost a lot of stuff.如何返回到 v20-v21 版本？这真的很糟糕。我失去了很多东西。
> 
> 备份下文件把容器删了重新拉一个再映射文件夹，标签用 stable

我试过了，我之前的内容一直显示，内容获取中~~~~

**Comment by m1732948116** [comment]
> > > > > Issue is not in English. It has been translated automatically. Issue is not in English. It has been automatically translated.问题不是英文的。它已被自动翻译。问题不是英文的。它已被自动翻译。
> > > > 
> > > > 
> > > > The last few updates are worse than no updates at all. I really hope it settles down. The last few updates are worse than no updates at all. I really hope it settles down.最后几次更新比根本没有更新更糟糕。我真的希望它能安定下来。最后几次更新比根本没有更新更糟糕。我真的希望它能安定下来。
> > > 
> > > 
> > > How do I go back to version v20-v21? It‘s really bad. I’ve lost a lot of stuff.如何返回到 v20-v21 版本？这真的很糟糕。我失去了很多东西。
> > 
> > 
> > 备份下文件把容器删了重新拉一个再映射文件夹，标签用 stable
> 
> 我试过了，我之前的内容一直显示，内容获取中~~~~

我的建议是用之前的备份，自从升级0.19的时候数据库崩了之后我每次升级都备份，还有就是换版本必须把浏览器cooike删除再重启

**Comment by cenzhifang** [comment]
> > > > > > Issue is not in English. It has been translated automatically. Issue is not in English. It has been automatically translated.问题不是英文的。它已被自动翻译。问题不是英文的。它已被自动翻译。问题不是英文的。它已被自动翻译。问题不是英文的。It has been automatically translated.问题不是英文的。它已被自动翻译。问题不是英文的。它已被自动翻译。
> > > > > 
> > > > > 
> > > > > The last few updates are worse than no updates at all. I really hope it settles down. The last few updates are worse than no updates at all. I really hope it settles down.最后几次更新比根本没有更新更糟糕。我真的希望它能安定下来。最后几次更新比根本没有更新更糟糕。我真的希望它能安定下来。最后几次更新比根本没有更新更糟糕。我真的希望它能安定下来。最后几次更新比根本没有更新更糟糕。最后几次更新比根本没有更新更糟糕。我真的希望它能安定下来。最后几次更新比根本没有更新更糟糕。我真的希望它能安定下来。
> > > > 
> > > > 
> > > > How do I go back to version v20-v21? It『s really bad. I』ve lost a lot of stuff.如何返回到 v20-v21 版本？这真的很糟糕。我失去了很多东西。如何返回到 v20-v21 版本？这真的很糟糕。I』ve lost lot of stuff.如何返回到 v20-v21 版本？这真的很糟糕。我失去了很多东西。
> > > 
> > > 
> > > 备份下文件把容器删了重新拉一个再映射文件夹，标签用 stable
> > 
> > 
> > 我试过了，我之前的内容一直显示，内容获取中~~~~
> 
> 我的建议是用之前的备份，自从升级 0.19 的时候数据库崩了之后我每次升级都备份，还有就是换版本必须把浏览器 cooike 删除再重启

这个我以为是最完美了，没想到每次升级太糟糕了，偶尔经常抽风。我现在考虑用别的了，不能全部都放在这个上面。

**Comment by cenzhifang** [comment]
> > Issue is not in English. It has been translated automatically. Issue is not in English. It has been automatically translated.
>
> > > > > > > Issue is not in English. It has been translated automatically. Issue is not in English. It has been automatically translated. Issue is not in English. It has been automatically translated. The question is not in English. It has been automatically translated. The question is not in English. It has been automatically translated. The question is not in English. It has been automatically translated. The question is not in English. It has been automatically translated. English. It has been automatically translated. The question is not in English. It has been automatically translated. The question is not in English. It has been automatically translated. The question is not in English. It has been automatically translated. This question is not in English. It has been automatically translated. This question is not in English. It has been automatically translated. This question is not in English. It has been automatically translated. This question is not in English. It has been automatically translated. This question is not in English. It has been automatically translated.
> > > > > >
> > > > > >
> > > > > > The last few updates are worse than no updates at all. I really hope it settles down. The last few updates are worse than no updates at all. I really hope it settles down. Updates are even worse. I really hope it settles down. The last few updates are worse than no updates at all. I really hope it settles down. The last few updates are worse than no updates at all. I really hope it settles down. The last few updates are worse than no updates at all. The last few updates are worse than no updates at all. I really hope it settles down. The last few updates are worse than no updates at all. I really hope it settles down. No updates are worse. I really hope it settles down. The last few updates are worse than no updates at all. I really hope it settles down. Updates are even worse. I really hope it settles down. The last few updates are worse than no updates at all. I really hope it settles down. The last few updates are worse than no updates at all. I really hope it settles down. The last few updates are worse than no updates at all. The last few updates are worse than no updates at all. I really hope it settles down. The last few updates are worse than no updates at all. I really hope it settles down.
> > > > >
> > > > >
> > > > > How do I go back to version v20-v21? It's really bad. I've lost a lot of stuff. How do I go back to version v20-v21? This is really bad. I've lost a lot. How to return to v20-v21 version? This is really bad. I've lost a lot of stuff. How to get back to v20-v21 version? This is really bad. I've lost a lot.How to get back to v20-v21 version? v20-v21 version? This is really bad. I've lost a lot. How to return to v20-v21 version? This is really bad. I've lost a lot. How to return to v20-v21 version? This is really bad. I've lost a lot. How to go back to v20-v21 version? This is really bad. I've lost a lot.
> > > >
> > > >
> > > > Back up the files, delete the container, pull a new one, and map the folder. The label is stable. Back up the files, delete the container, pull a new one, and map the folder. Labels are stable.
>>>
>>>
> > > I tried it, my previous content is always displayed, and the content is being obtained~~~~I tried it, my previous content is always displayed, and the content is being obtained~~~~
>>
>>
> > My suggestion is to use the previous backup. Since the database crashed when upgrading to 0.19, I have backed up every time I upgraded. Also, when changing versions, I must delete the browser cooike and restart it. My suggestion is to use Previous backup. Since the database crashed when upgrading to 0.19, I backed up every time I upgraded. Also, when changing versions, I have to delete the browser and restart it.
>
> I thought this was the most perfect one, but I didn't expect that it would be so bad every time I upgraded it, and I would occasionally have convulsions. I'm thinking about using other things now, and I can't focus everything on this. I thought this was the most perfect one, but I didn't expect it would be so miserable every time I upgraded, with occasional twitching. I'm thinking of using other things now and I can't focus everything on this.

![Snipaste_2024-05-18_11-24-06](https://github.com/usememos/memos/assets/105171265/01495e51-9fc2-4ee4-a059-93140a98c613)
This is a problem that occurs when downgrading to v21. I don’t know what to do.
