### ISSUE TITLE
希望支持 markdown table 内换行代码 <br>

### ISSUE THREAD

**Issue by toyqiu** [usememos/memos#3388]
### Describe the solution you'd like

希望支持 markdown table 内换行代码 <br>

### Type of feature

User Interface (UI)

### Additional context

希望支持 markdown table 内换行代码 <br>

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/f374169a2bba4e40cd09941bb1ec9bf3a850ef05
