### ISSUE TITLE
从v0.22回滚到0.21后无法读取数据库了

### ISSUE THREAD

**Issue by bushiwode** [usememos/memos#3391]
### Describe the bug

从v0.22回滚到0.21后无法读取数据库了，我的程序自动更新到了0.22版本，后来发现手机端memos无法连接至服务端，于是回滚到v0.21版本，发现一直显示读取数据，重新升级到0.22版本后没有问题

After rolling back from v0.22 to 0.21, I couldn't access the database. My program automatically updated to version 0.22, but later I found that the memos on the mobile end could not connect to the server. So I rolled back to version v0.21 and found that it kept showing "reading data". After upgrading to version 0.22 again, there were no issues.

### Steps to reproduce

1、updated to version 0.22
2、open memos
3、Downgrade to v0.21
4、Unable to read data

### The version of Memos you're using

v0.22

**Comment by michaelien** [comment]
Duplicated with https://github.com/usememos/memos/issues/3348
