### ISSUE TITLE
【v0.22.0】include_comments filter does not work?

### ISSUE THREAD

**Issue by bbruceyuan** [usememos/memos#3392]
### Describe the bug

url1:  https://memos.bbruceyuan.com/api/v1/memos?page_size=2&include_comments=true
url2: https://memos.bbruceyuan.com/api/v1/memos?page_size=2
url3: https://memos.bbruceyuan.com/api/v1/memos?page_size=2&include_comments=True
url4: https://memos.bbruceyuan.com/api/v1/memos?page_size=2&include_comments

url1, url2, url3 and url4 return totally same result. It may result from a bug.

As the following picture. `memos/63` is a comment. but it is not included in results. 
<img width="567" alt="image" src="https://github.com/usememos/memos/assets/16234167/dc9ad73e-38b7-48e0-a1f5-81c106df5bf8">

### Steps to reproduce

1. login your account in website. (or get token)
2. go to url1 and url2, replace it to your own url. 
> url1:  https://memos.bbruceyuan.com/api/v1/memos?page_size=2&include_comments=true
> url2: https://memos.bbruceyuan.com/api/v1/memos?page_size=2
3. the results is same. 

### The version of Memos you're using

0.22.0

**Comment by boojack** [comment]
Using `?filter=include_comments%3D%3Dtrue`. Reference docs: https://memos.apidocumentation.com/reference#tag/memoservice/get/api/v1/memos
