### ISSUE TITLE
卡在“正在获取数据”

### ISSUE THREAD

**Issue by ebasegykj** [usememos/memos#3393]
### Describe the bug

升级到0.22版本后，出现截图中的问题。重新回到0.21版本后问题没有解决。然后重新用了别人的镜像部署后（elestio-memos)就没有问题秒进。 删除又重新用neosmemo/memos:stable  安装 问题依旧----群辉nas

### Steps to reproduce

0.21升级到0.22   
0.22重装0.21
反复都不行
neosmemo/memos:stable  和laset 都试过

### The version of Memos you're using

0.22

### Screenshots or additional context

![1715862156641](https://github.com/usememos/memos/assets/73980319/16c0e2b7-8292-47e7-9307-77354f19dd31)

**Comment by boojack** [comment]
Please consider providing more error messages from browser console or backend logs if you want to resolve the problem. Downgrading is not supported if you don't have a backup of the old version's data.
