### ISSUE TITLE
Has the API changed?

### ISSUE THREAD

**Issue by penndu** [usememos/memos#3394]
### Describe the bug

I am unable to obtain the required data through the existing API.

### Steps to reproduce

https://s.dusays.com/api/v1/memo?creatorId=1&tag=&limit=10

### The version of Memos you're using

0.22.0

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/46226528/afbdcb47-52b1-4cbd-b775-4a84a739681d)

**Comment by boojack** [comment]
Reference docs: https://memos.apidocumentation.com/reference

**Comment by quanru** [comment]
> Reference docs: https://memos.apidocumentation.com/reference

What are the specific parameters of filter? There is no explanation in the document, such as consulting:

`api/v1/memos? limit=50&offset=0&rowStatus=NORMAL`

How to change the parameters under the new version of the interface, I have tried to return the empty array like this:

`/api/v1/memos? pageSize=50&page=1&filter=row_status=="ACTIVE"`

**Comment by cambrian07** [comment]
API Document:
https://memos.apidocumentation.com/reference#tag/memoservice/get/api/v1/memos
