### ISSUE TITLE
Update to v0.22.0 nothing as problems!

### ISSUE THREAD

**Issue by m4ntic0r** [usememos/memos#3398]
### Describe the bug

updated to 0.22.0 with docker

-> settings like language or dark/white mode are default again
-> tags are gone! zero
-> not able to login on ios with username and password
-> registration in settings was disabled, its enabled again after update

only solution for me.. reverted my container back to 0.21.0

this is a really bad update?

### Steps to reproduce

updated via docker compose from 0.21.0 to 0.22.0

### The version of Memos you're using

0.22.0

**Comment by mariushosting** [comment]
For the tags you just need to click "Rebuild tags". No issue with login.
For the rest I confirm all the bugs.

**Comment by mariushosting** [comment]
Also now the Server Display Name on the left is always "memos". 
![always memos](https://github.com/usememos/memos/assets/37554361/e1baae9d-8af1-4390-8bf8-42be1d2fd5cd)
It does not take into account whether or not you customized the name in the settings.

**Comment by cenzhifang** [comment]
> For the tags you just need to click "Rebuild tags". No issue with login. For the rest I confirm all the bugs. No problem logging in. The rest I confirm all errors.

where was it rebuilt？

**Comment by nicou** [comment]
> > For the tags you just need to click "Rebuild tags". No issue with login. For the rest I confirm all the bugs. No problem logging in. The rest I confirm all errors.
> 
> where was it rebuilt？

![rebuild-tags](https://github.com/usememos/memos/assets/16757571/ab341c75-a1bd-46e6-8bc6-bef4120688fc)

**Comment by boojack** [comment]
> Upgrade overview
> ⚠️ This release contains upgrade notes that deviate from the norm:
> 
> * Requires database migrations;
> * **Some settings(including resource storage) need to be reset on the UI;**
> 
> If you're ready to upgrade, it's recommended to back up your data first

_Some settings have been reset._ You should set them up again on the UI. And please take a look of release note before upgrading your version ;)
