### ISSUE TITLE
S3 cannot customize domain name prefixes.

### ISSUE THREAD

**Issue by MusicMadman** [usememos/memos#3403]
### Describe the bug

S3 cannot customize domain name prefixes.

### Steps to reproduce

S3 cannot customize domain name prefixes.

### The version of Memos you're using

v0.22.0

**Comment by boojack** [comment]
We will use [presigned urls](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html) to provide more secure links. It is recommended to use an S3 API-compatible object store such as cloudflare R2.
