### ISSUE TITLE
0.22.0二级标签不会合并显示了

### ISSUE THREAD

**Issue by bfansheng** [usememos/memos#3408]
### Describe the bug

在0.22.0之前，二级标签是能合并在一起的，现在这个版本是bug呢，还是后续版本不再支持二级标签了呢
![image](https://github.com/usememos/memos/assets/16935251/4b4f1f86-b0aa-4e74-bf91-fdbf9be1247c)

### Steps to reproduce

同上

### The version of Memos you're using

0.22.0

**Comment by flyklmwl** [comment]
确实二级标签都显示出来，感觉特别乱。 而且加载数量一多，比以前卡多了，不能另外做个管理界面嘛。。。

**Comment by boojack** [comment]
After `v0.22.0`, it will be displayed horizontally instead of a tree. This could save more space and shows the amount of related memos.
