### ISSUE TITLE
Access Tokens not work

### ISSUE THREAD

**Issue by JakeLaoyu** [usememos/memos#3409]
### Describe the bug

<img width="356" alt="image" src="https://github.com/usememos/memos/assets/16181940/ae2e00df-8b98-4273-b7c8-d0ba641a28b5">
<img width="578" alt="image" src="https://github.com/usememos/memos/assets/16181940/23d8bcdb-7c75-4a20-bd78-7f2b1d0706db">

### Steps to reproduce

1. Deploy by docker
2. curl with access token
3. get empty list

### The version of Memos you're using

0.22.0

**Comment by JakeLaoyu** [comment]
https://github.com/raycast/extensions/issues/12415

**Comment by michaelien** [comment]
I think the endpoint should be `/api/v1/memos` not `/api/v1/memo` after `v0.22.0`. Reference docs: https://memos.apidocumentation.com/reference#tag/memoservice/get/api/v1/memos

**Comment by JakeLaoyu** [comment]
@michaelien THX, I saw the doc https://www.usememos.com/docs/security/access-tokens. It looks outdated.
