### ISSUE TITLE
Downloaded filename should not be resource id

### ISSUE THREAD

**Issue by myfeilew** [usememos/memos#3410]
### Describe the bug

下载的exe文件，下载后需要手动添加后缀方可运行

### Steps to reproduce

1、上传.exe后缀文件
2、下载资源库中.exe文件
3、双击文件无法打开
4、手动添加.exe后缀方可运行

### The version of Memos you're using

0.22.0

### Screenshots or additional context

![图片](https://github.com/usememos/memos/assets/126596624/57e9b26a-aad5-4340-a594-b0700cc66872)

**Comment by boojack** [comment]
It looks like there is no `.exe` suffix in your original file?

**Comment by myfeilew** [comment]
> It looks like there is no `.exe` suffix in your original file?
> 
> 在你的原始文件中似乎没有`.exe`后缀？

原始文件是有后缀的，试过其他带有后缀的文件上传后，再次下载会变为没有后缀的未知文件类型，需要手动添加后缀才能运行

**Comment by myfeilew** [comment]
![图片](https://github.com/usememos/memos/assets/126596624/5f88f8e7-dadf-4f28-98db-7d7437b73ec7)
