### ISSUE TITLE
Enquire about filter params in list memos api

### ISSUE THREAD

**Issue by JakeLaoyu** [usememos/memos#3411]
### Describe the bug

Consult how to use the filter parameter when passing it into the fetch function. I cannot access no matter what format I use.

<img width="553" alt="image" src="https://github.com/usememos/memos/assets/16181940/69fddb26-63c5-4917-a1a8-cc09e0f13644">
<img width="1006" alt="image" src="https://github.com/usememos/memos/assets/16181940/35e0be90-b4a5-4e26-9987-f6a11e0636a5">

### Steps to reproduce

```shell
curl --location 'http://127.0.0.1:5230/api/v1/memos?filter=creator%3D%3Dusers%2F1%20%26%26%20visibilities%3D%3D%5B%27PUBLIC%27%2C%20%27PROTECTED%27%5D' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InYxIiwidHlwIjoiSldUIn0.eyJuYW1lIjoiIiwiaXNzIjoibWVtb3MiLCJzdWIiOiIxIiwiYXVkIjpbInVzZXIuYWNjZXNzLXRva2VuIl0sImV4cCI6MTcxNjc3OTgzMiwiaWF0IjoxNzE2MTc1MDMyfQ.kEEep1DpFH1Cj3jq5YR-8NGI7EEUlU9AmGTj17lJY_k'
```

### The version of Memos you're using

0.22.0

**Comment by boojack** [comment]
Good catch. There should be a single quote around creator. And the documentation has been updated.

e.g., `encodeURIComponent("include_comments==true&&creator=='users/1'")`

**Comment by JakeLaoyu** [comment]
@boojack thx
