### ISSUE TITLE
All tags are lost after update to Version: v0.22.0 (docker)

### ISSUE THREAD

**Issue by gmalets** [usememos/memos#3413]
### Describe the bug

After update docker container to memos version: v0.22.0 all tags are lost 

### Steps to reproduce

update docker container "Image": "neosmemo/memos:stable"

### The version of Memos you're using

0.22.0

### Screenshots or additional context

![Screenshot from 2024-05-20 15-31-19](https://github.com/usememos/memos/assets/30619792/2ca5cc11-9ca4-4af9-b504-e92182cd4247)
![Screenshot from 2024-05-20 15-35-26](https://github.com/usememos/memos/assets/30619792/d6285c2f-b49d-499d-bbe0-16113040e28a)

**Comment by boojack** [comment]
There should be a `rebuild` button after tag icon. It can auto-generate your tags from all memos.

<img width="252" alt="image" src="https://github.com/usememos/memos/assets/24653555/3b7945b0-d7af-4be9-9bde-bf8fb5aff36b">
