### ISSUE TITLE
Optional settings for S3 Storage pre signed URL feature

### ISSUE THREAD

**Issue by cxplay** [usememos/memos#3424]
### Describe the solution you'd like

My bucket is not dedicated to Memos, and accessibility is public, forcing pre-signed URLs doesn't make any sense.

### Type of feature

Other

**Comment by boojack** [comment]
> By default, all Amazon S3 objects are private, only the object owner has permission to access them. However, the object owner may share objects with others by creating a presigned URL. A presigned URL uses security credentials to grant time-limited permission to download objects. The URL can be entered in a browser or used by a program to download the object. The credentials used by the presigned URL are those of the AWS user who generated the URL.
> 
> https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html

It is a recommended way to share private objects, independent of whether your bucket is public or not.
