### ISSUE TITLE
Optionally set the URL host for S3 Storage

### ISSUE THREAD

**Issue by cxplay** [usememos/memos#3425]
### Describe the solution you'd like

My bucket uses a CDN to accelerate and cache content, and the bucket name contains `. `, and while it is possible to upload files over HTTP normally, it is not possible to access the resources via the normal virtual-host-style URL.
> https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html

The best solution is to let the user set the host field of the URL, rather than forcing the endpoint and bucket names to be generated automatically.

### Type of feature

User Interface (UI)

**Comment by cloverzrg** [comment]
I have the same issue.
I don't why change the endpoint host when request the api, it work before 0.22

**Comment by cxplay** [comment]
Not planned? No.
