### ISSUE TITLE
pasting colorful emoji results in no-color emoji

### ISSUE THREAD

**Issue by aanatoly** [usememos/memos#3426]
### Describe the bug

Pasted colorful Emoji appears without color.
When I look in browser inspector (F12) I do see them with color

I am running docker version
- "org.opencontainers.image.created": "2024-04-09T13:37:53.268Z"
- "org.opencontainers.image.revision": "58ae3217ffcb2a9404c41e684aabee31c93bd779"
- "org.opencontainers.image.version": "stable"   

### Steps to reproduce

1. copy (ctrl-c) colorful emoji
2. paste it into edit box
3. see it without color

### The version of Memos you're using

58ae3217ffcb2a9404c41e684aabee31c93bd779

### Screenshots or additional context

![memos-emoji-gray](https://github.com/usememos/memos/assets/6735508/16e846d7-9f31-4e1b-9032-17c124112e79)
![memos-emoji-color](https://github.com/usememos/memos/assets/6735508/85cf6735-f702-4f7c-854e-416b6d17d339)

**Comment by boojack** [comment]
It's probably related to your browser/OS, and you'll get the same result on other websites.

**Comment by aanatoly** [comment]
I get colorful emoji on every other website, incl github - 😉
but not on in memos (test with dark & light themes)

In attached screenshots, memos show emoji in grayscale, while web debugger shows it with colors
