### ISSUE TITLE
升级到v0.22.0后无法用MoeMemos登录了，Access Tokens也被清空

### ISSUE THREAD

**Issue by mwnu** [usememos/memos#3432]
### Describe the bug

MoeMemos无法用账户或Access Tokens登录。
其他第三方应用似乎也不不再支持。

### Steps to reproduce

MoeMemos是手机端的memeos应用

### The version of Memos you're using

v0.22.0

**Comment by boojack** [comment]
> Upgrade overview
> ⚠️ This release contains upgrade notes that deviate from the norm:
> 
> * Requires database migrations;
> * **Some settings(including resource storage) need to be reset on the UI;**
> 
> If you're ready to upgrade, it's recommended to back up your data first

There are some API breaking changes in `v0.22.0`. Maybe you need to wait for Moememos to finish the API adaptation. 

And please take a look of release note before upgrading your version ;)
