### ISSUE TITLE
本地部署的minio S3报错

### ISSUE THREAD

**Issue by sprdlh** [usememos/memos#3433]
### Describe the bug

ERROR server error method=/memos.api.v1.ResourceService/CreateResource error="rpc error: code = Internal desc = failed to save resource blob: Failed to upload via s3 client: operation error S3: PutObject, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Put \"https://memos.xxxxx.xxxxxx.xxx/assets/1716288308_hfdghgfhj.png?x-id=PutObject\": remote error: tls: unrecognized name"
![1716290005877](https://github.com/usememos/memos/assets/6218991/7a07a6a2-0a72-491e-8f95-323a40059056)

### Steps to reproduce

.

### The version of Memos you're using

0.22.0

**Comment by wpengsen** [comment]
Bucket自动添加到前边了

**Comment by sprdlh** [comment]
> Bucket自动添加到前边了

这个是新版的bug吗

**Comment by boojack** [comment]
https://github.com/usememos/memos/issues/3397

**Comment by sprdlh** [comment]
您发来的邮件我已经收到...
