### ISSUE TITLE
urlPrefix disappear in s3 storage option？

### ISSUE THREAD

**Issue by ixxmu** [usememos/memos#3436]
### Describe the bug

urlPrefix disappear in s3 storage option？ It showed in previous version S3 options

### Steps to reproduce

just check the s3 storage system

### The version of Memos you're using

Version: v0.22.0

**Comment by Somme4096** [comment]
Yes, it did disappear in my environment too. I will research on this.

**Comment by enshui** [comment]
well , 0.21 it is shown ,by latest disappear

**Comment by Somme4096** [comment]
Removed by this commit: https://github.com/usememos/memos/commit/320963098f7a1ce76a9e493aede078b560f0ea33

The reason for the removal of this feature is described in the v0.22.0 release notes: 

>S3 Storage related resources will be using [pre-signed url](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html) and supports synchronized deletion.

And link to original author's message:
https://github.com/usememos/memos/issues/3403#issuecomment-2119466204

>We will use [presigned urls](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html) to provide more secure links. It is recommended to use an S3 API-compatible object store such as cloudflare R2.
