### ISSUE TITLE
标签无法折叠

### ISSUE THREAD

**Issue by yss930819** [usememos/memos#3437]
### Describe the bug

现在标签都显示在右侧，无法根据路径折叠了

### Steps to reproduce

我有很多根据路径分配的标签，现在无法折叠会导致显示混乱

![image](https://github.com/usememos/memos/assets/8181260/efd96d3d-44a7-4322-bce7-3a5eecfeba6b)

### The version of Memos you're using

0.22.0

**Comment by michaelien** [comment]
Duplicated with https://github.com/usememos/memos/issues/3408. See more detail in https://github.com/usememos/memos/issues/3408#issuecomment-2120542735
