### ISSUE TITLE
图片、文件、视频能否支持本地存储？

### ISSUE THREAD

**Issue by kylehz** [usememos/memos#344]
### Is your feature request related to a problem?

需求点：
- 现在图片或文件都放数据库里加载出来有点慢，每次刷新页面都会重新从数据库拉取一次文件，无法像静态资源那样缓存在浏览器
- 私人照片不想放图床
- 视频有的比较大，也不方便用网络存储

### Describe the solution you'd like

- 支持本地存储
- 支持存视频文件，视频播放支持断点续传
- 本地图片自动生成缩略图，小图使用缩略图，点击再加载原图

**Comment by Zeng1998** [comment]
技术上不太可能吧？要从浏览器里访问本地文件

**Comment by kylehz** [comment]
我的意思是服务器本地文件系统存储，而不是把文件转成base64放在db里面

**Comment by i-iooi-i** [comment]
![image](https://user-images.githubusercontent.com/1827701/212555574-7fe8c8b3-98cf-46a4-bb9c-7d213a40f883.png)
![image](https://user-images.githubusercontent.com/1827701/212555582-0a888b95-6452-4d35-a714-28f46b0a6c97.png)

支持，希望可以考虑像这样来存储数据。

别的不说，这样定期做文件增量备份到其他网络存储很方便。
要不然定期给一个越来越大的db文件做备份，实在是多有不便的。

**Comment by Seevil** [comment]
🤣看着数据库突然变大，我就知道其他人也有这个焦虑

**Comment by wk-coder** [comment]
强烈支持，有这个功能可以平时再用另一处进行增量同步，不然后续怎么同步另一处地方？按照上行一般的3MB/s，一天才250G能同步，以后用的时间久了，就算没有这么多，文件稍有变化就需要整个重新来同步一遍，就算是一个星期一次也费时间，希望可以早点改进。
感觉有了这个的话，其他的功能才可以算是锦上添花
