### ISSUE TITLE
memos 中的 tags 没有被提取出来

### ISSUE THREAD

**Issue by bestony** [usememos/memos#3446]
### Describe the bug

memos 中的 tags 没有被提取出来，明明有多个 tag ，但不展示。

### Steps to reproduce

1. 创建一个 Memo，并带上标签
2. 再创建一个 memo，并带上标签。

### The version of Memos you're using

v0.22.0

### Screenshots or additional context

<img width="1047" alt="image" src="https://github.com/usememos/memos/assets/13283837/5d2e708a-cfb1-4c8b-a486-c482304fa6f2">

**Comment by dohsimpson** [comment]
升级后我也遇到了同样的问题, rebuild tags之后tags就又可以用了.

![Screenshot_20240524_193317](https://github.com/usememos/memos/assets/5865309/ceffcb68-38fe-4276-b2c1-7311efde3745)

**Comment by michaelien** [comment]
@bestony The tags had some breaking changes in v0.22.0. So maybe you need to rebuild tags manully after upgraded.

**Comment by bestony** [comment]
get.
