### ISSUE TITLE
Can't create SSO

### ISSUE THREAD

**Issue by betterthanever2** [usememos/memos#3450]
### Describe the bug

I'm trying to set up SSO with Authentik. I got all the required pieces (as per step 6 of this article https://www.usememos.com/docs/advanced-settings/keycloak), then tried adding SSO via the UI, and ... nothing. When I click "create" after filling all the required fields, nothing happens; the pop-up remains where it is, no fields are emphasized as having an error or something; nothing happens. Not sure why, or what to do about it.

### Steps to reproduce

1. Go to "Settings" -> "SSO"
2. Click "create"
3. Select "Custom" for `template` in the pop-up
4. Fill in the fields
5. Click "create"

### The version of Memos you're using

0.22

### Screenshots or additional context

OS: Ubuntu 24f

**Comment by Greirson** [comment]
Hey @betterthanever2, I just got mine setup with Authentik.  Is the create button blue or grey'd out? Can you confirm you have all the required fields with the red * filled in, including identifier?

Here's what mine looks like in the UI
![image](https://github.com/usememos/memos/assets/8883154/ee68a60e-9b77-476b-97dd-a67c8f318d9a)

**Comment by betterthanever2** [comment]
Hi. Mine look pretty much the same. The "update" button is blue and looks active. However, nothing happens when I click on it

**Comment by Greirson** [comment]
Could you attach docker logs? Also any errors in the browser console?

**Comment by betterthanever2** [comment]
Sure.
Here's the console output:
```
ClientError: /memos.api.v1.IdentityProviderService/CreateIdentityProvider INTERNAL: failed to create identity provider, error: sql: converting argument $2 type: unsupported type impl.EnumInfo, a struct
    st https://memos.subjective.place/assets/index-BgLbTvS8.js:286
    ClientError https://memos.subjective.place/assets/index-BgLbTvS8.js:286
    makeCall https://memos.subjective.place/assets/index-BgLbTvS8.js:287
```
Corresponding log in the container:
```
memos  | 2024/05/26 06:22:32 ERROR server error method=/memos.api.v1.IdentityProviderService/CreateIdentityProvider error="rpc error: code = Internal desc = failed to create identity provider, error: sql: converting argument $2 type: unsupported type impl.EnumInfo, a struct"
```

**Comment by beastarman74** [comment]
I am experiencing the same issue and error when trying to create a custom entry for Authelia. 

For me it is when using a PostgreSQL database. If I use the default settings it will create the sso entry without issue and it is functional.  I have not tried mysql at the moment.

**Comment by betterthanever2** [comment]
> For me it is when using a PostgreSQL database.

My setup is also with Postgres, so this gotta be the root cause.

**Comment by boojack** [comment]
> ClientError: /memos.api.v1.IdentityProviderService/CreateIdentityProvider INTERNAL: failed to create identity provider, error: sql: converting argument $2 type: unsupported type impl.EnumInfo, a struct
    st https://memos.subjective.place/assets/index-BgLbTvS8.js:286
    ClientError https://memos.subjective.place/assets/index-BgLbTvS8.js:286
    makeCall https://memos.subjective.place/assets/index-BgLbTvS8.js:287

Fixed with https://github.com/usememos/memos/commit/423861d48c4436539fae1dd88dbcf6e2890efb43

**Comment by beastarman74** [comment]
Working for me now. Thanks for the super quick turnaround.
