### ISSUE TITLE
Memo referenced by Embedded Content appears to other users

### ISSUE THREAD

**Issue by pecasha** [usememos/memos#3452]
### Describe the bug

if a Memo is referenced by [Embedded Content](https://www.usememos.com/docs/getting-started/content-syntax#embedded-content), then the referenced Memo will appear in other users lists

### Steps to reproduce

1. Save a Memo with [Embedded Content](https://www.usememos.com/docs/getting-started/content-syntax#embedded-content)
2. Go to the Explore page to view other users personal pages

### The version of Memos you're using

v0.22.0

### Screenshots or additional context

![PixPin_2024-05-25_17-34-55](https://github.com/usememos/memos/assets/9607128/a44140d8-ca7e-4e85-896a-48440278205d)
Steps to Reproduce

**Comment by mmacdo54** [comment]
This PR https://github.com/usememos/memos/pull/3517 should fix the issue

**Comment by mmacdo54** [comment]
This should be fixed now @pecasha
