### ISSUE TITLE
Multi-level tags not working in 0.22

### ISSUE THREAD

**Issue by gonsalvesc** [usememos/memos#3453]
### Describe the bug

The multi-level tags feature is not working in v 0.22 after rebuilding the tags. I used to be able to group multi-level tags in the prior version, but this is not working now.

### Steps to reproduce

Upgrade to v0.22
Refresh tags

### The version of Memos you're using

v0.22

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/44937952/915fe5f7-c7fc-4a1c-bace-11a810d76de2)

**Comment by pipuwong** [comment]
I had the same problem, and my tab didn't show up on the right

**Comment by kbiits** [comment]
They decided not to use a tree view for nested / sub-tags. I'm personally disappointed about this decision because I used this tree visualization a lot and found it very useful, but they decided to revamp it to tackle other issues that arise because of the tree view.

**Comment by gonsalvesc** [comment]
Agreed - definitely disappointing as you can tell, I use the tree visualization as well.
Guess I'll just stick to 0.21 for now!

**Comment by cdanne** [comment]
I also noticed this and would love to get the tag hierarchy back.
I expected this is a temporary situation due to technical redesign - or is this a permanent chance in UI und usability? The latter would be a major drawback and a real problem for people using tag hierarchy a lot (like me 😉).
I hope we can get the hierarchy back! 🙏

**Comment by kbiits** [comment]
I think it's a permanent changes. Can you guys confirm this @boojack @michaelien ?

**Comment by i-iooi-i** [comment]
It's really bad now, it makes the page cluttered and bloated!
