### ISSUE TITLE
Private memos attached images are accessible to non-authenticated users via direct URL

### ISSUE THREAD

**Issue by quaintdev** [usememos/memos#3454]
### Describe the bug

There is a security issue in the Memos application where images (and potentially other resources) attached to private posts are accessible to non-authenticated users if they have the direct URL to the image. This defeats the purpose of setting a post's visibility to private, as sensitive media could be exposed if the URL is leaked.

### Steps to reproduce

1.  Log in to the Memos application.
2.  Create a new post and attach an image to it.
3.  Set the visibility of the post to private.
4.  Save the post.
5.  Log out or open an incognito window (to simulate a non-authenticated user).
6.   Access the direct URL of the attached image.

### The version of Memos you're using

latest

**Comment by eMUQI** [comment]
I am using Version: v0.22.0 with object storage set to the local file system. 

I could not reproduce the issue you mentioned. I tried accessing the image resource in an incognito window without logging into an account and received a status code 503 along with 
```
{
  "code": 14,
  "message": "connection error: desc = \"transport: Error while dialing: dial tcp :5230: connect: connection refused\"",
  "details": []
} 
```

Can you provide more details?

**Comment by quaintdev** [comment]
I am not sure what changed since yesterday but I'm not able to reproduce this either. I get a different response though
```json
{"code":5, "message":"Not Found", "details":[]}
```
My object storage is set to database. I am closing this.
