### ISSUE TITLE
 Webhook does not receieve information about uploaded images/resources on initial post creation

### ISSUE THREAD

**Issue by quaintdev** [usememos/memos#3455]
### Describe the bug

There is an issue in the application where the webhook server does not receive any information about uploaded images or resources when a new memo is created. Only the textual content of the memo is sent. However, if the memo is updated, the webhook server then receives the resource-related information.

### Steps to reproduce

1. Set up a webhook server to receive notifications from the Memos application.
2. Log in to the Memos application.
3. Create a new memo and upload an image or other resource.
4. Save the memo.
5. Check the payload received by the webhook server.
6. Update the memo.
7. Check the payload received by the webhook server again.

### The version of Memos you're using

latest

**Comment by mmacdo54** [comment]
This looks like it is because when a Memo is created it sends out the webhook instantly - at that point the Resource has not actually been created yet. It awaits on the Memo creation and then sets the resource after - by which time the webhook has already been sent.

**Comment by quaintdev** [comment]
With the delete memo the current behavior is okay because we know the resource that is going to be deleted but with creation we at least need to update webhook with resource url. The upload can finish at later point.

**Comment by mmacdo54** [comment]
I suppose there is a kind of simple way in that when the resources are updated that could also fire a memo updated Webhook event so if you created a memo and also attached a file then you would get a memo was created webhook event with no resource but then pretty quickly you would get a memo updated event with the resources attached. @boojack what do you think? Would this solve the issue?

**Comment by mmacdo54** [comment]
@boojack actually looks like the Webhook payload was trimmed down a few days ago so that now it only sends the memo content and resources are omitted?

**Comment by boojack** [comment]
@mmacdo54 Sorry for the late reply. I just use `v1pb.Memo` as part of webhook response in https://github.com/usememos/memos/commit/f33571fec6e31a7025ccfd5133806a9d58c8c673. It'll include all the related resources/relations. So I think the next step is to bind all resources/relations when creating memo. But this could be an _enhancement_ as the user can get the all memo information asynchronously via an API call in the webhook.
