### ISSUE TITLE
Link Preview Pop-ups Don't Go Away

### ISSUE THREAD

**Issue by betterthanever2** [usememos/memos#3456]
### Describe the bug

If I have a bunch of links in my memo, hovering over it presents an issue, because the URL previews (very nicely styled, btw) sometimes won't go away. At times, this could cover the entire area of the memo. The preview would go away if you find the its specific URL and hover over it again.

BTW, this note is supposed to be rendered as a table, but it's just raw text for me. Is this a bug, too?

### Steps to reproduce

1. Create a note with at least 5 inline links
2. Hover over the note back and forth

### The version of Memos you're using

0.22

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/68774738/331e551b-bca4-4dc3-aaef-e8e0866a33f8)
Here's the full text of my particular memo:
```
| Title | URL | Desc |

|--- |--- |--- |

| Mattermost | https://mattermost.com/ | Messenger |

| FusionAuth | https://fusionauth.io/ | Auth |

| NetData | https://github.com/netdata/netdata | System Monitoring |

| ByteBase | https://www.bytebase.com/docs/ | DB Monitoring |

| Backup | https://github.com/backup/backup | Linux backup utility |

| Budibase | https://github.com/Budibase/budibase | Internal apps

| Windmill | https://github.com/windmill-labs/windmill | Internal apps |

| Redash | https://github.com/getredash/redash | Internal apps |

| Infisical | https://infisical.com/ | Secrets |

| Confidant | https://lyft.github.io/confidant/ | Secrets |

| Plausible Analytics | https://github.com/plausible/analytics | Analytics

| Wazuh | https://wazuh.com/ | XDR & SIEM protection |

| Pi-hole | https://github.com/pi-hole | Ads Blocker |

| Authentic | | SSO & Auth |

| FunkWhale  | https://docs.funkwhale.audio/index.html | Audio hosting |

| Penpot | https://penpot.app/ | Design / Wireframes |

| Mailcow | https://github.com/mailcow/mailcow-dockerized | Mailserver |

| Chitchatter | https://github.com/jeremyckahn/chitchatter | p2p communication |

| My Mind | https://github.com/ondras/my-mind | Mindmapping |

| Changedetection | https://github.com/dgtlmoon/changedetection.io | |

| Cloud Beaver | https://dbeaver.com/ | DB Introspection |

| ArchiveBox | https://github.com/ArchiveBox | Webpage archive |

| CDS | https://ovh.github.io/ | Continuous delivery |

| Buildbot | https://buildbot.net/ | Continuous integration |

#selfhost
```

**Comment by Somme4096** [comment]
Reproduced. Mine is also not rendered as a table either.
<img width="752" alt="image" src="https://github.com/usememos/memos/assets/159004030/5970a3f4-2f0b-4ed3-a825-4bcf9c58000c">

**Comment by boojack** [comment]
Duplicated with https://github.com/usememos/memos/issues/3377
