### ISSUE TITLE
Request to support PWA

### ISSUE THREAD

**Issue by johnnyqian** [usememos/memos#3460]
### Describe the solution you'd like

It would be great that memos can support Progressive web apps, like https://flomoapp.com/.
Currently most community driven client/mobile memos app stop to work as memos upgrade.

### Type of feature

User Experience (UX)

**Comment by zwjdujin** [comment]
支持

**Comment by edersong** [comment]
It will be great.

**Comment by edersong** [comment]
Indeed
It was the second request that I sent about it that was closed as "not planned"
It's a pity! ☹️
