### ISSUE TITLE
Date selector not working on Firefox

### ISSUE THREAD

**Issue by TheFallenSpirit** [usememos/memos#3477]
### Describe the bug

When attempting to edit the date of a memo on Firefox, the date selector does not have an option to select the time. Also when changing the value in the date selector, it is not reflected in the memo.

Upon attempting to do the same thing on Chromium, it works perfectly fine.
Also, when opening the date selector on both Firefox and Chromium, it opens to the current date & time not the date & time of the memo.

### Steps to reproduce

1. Create a Memo on your Memos instance.
2. Change the date of your Memo in the date selector in the edit menu.

### The version of Memos you're using

0.22.1

**Comment by mmacdo54** [comment]
It seems that Firefox is "not great" when it comes to rendering of a datetime-local input and is a known issue. I can see what the issue is with regards to it defaulting to todays date and time on chromium though @boojack happy to put up a PR that at least fixes that issue?

**Comment by TheFallenSpirit** [comment]
Will there be any attempt to fix the issue with Firefox or will it just be stagnant for now?

**Comment by mmacdo54** [comment]
I will have a look to see if anything can be done on Firefox but first pass suggests they just need to properly support that input type.

@boojack PR for fixing the issue of it not using the current memo date when opening the input https://github.com/usememos/memos/pull/3524
