### ISSUE TITLE
The latest version 0.22 search cannot be used

### ISSUE THREAD

**Issue by 2vl** [usememos/memos#3482]
### Describe the bug

The latest version 0.22 search cannot be used
Searching cannot find anything, even if it already exists

### Steps to reproduce

I cannot search for existing memos on the demonstration website.

https://demo.usememos.com/home?text=Memos

### The version of Memos you're using

0.22.1

### Screenshots or additional context

<img width="1221" alt="image" src="https://github.com/usememos/memos/assets/23339449/5fdfd3aa-a492-49f2-850a-fdfb756194d9">

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/1894ef161fd4fe9587ccfbf84f0e8a31829d021d
