### ISSUE TITLE
Regarding the issue of commenting

### ISSUE THREAD

**Issue by yaoleistable** [usememos/memos#3485]
### Describe the bug

When writing a comment with your own account, the dialog box does not automatically delete the previous comment content. You need to delete it manually before writing a new comment.

### Steps to reproduce

1. Click to write a comment
2. Fill in the comment content (if there is a problem, the previous content is not deleted)
3 Save

### The version of Memos you're using

0.22.0

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/0657a1ef5b52cffcca99d48eecab7e17e11e0d34
