### ISSUE TITLE
The database is not cleared cleanly

### ISSUE THREAD

**Issue by etjec4** [usememos/memos#3486]
### Describe the bug

After the memo entry is deleted, the entry is still maintained in the database. It is speculated that the comment may not have been deleted.
Also, can comments be indexed?
Many thanks to the developers for their hard work.

### Steps to reproduce

.....

### The version of Memos you're using

22.0

**Comment by mmacdo54** [comment]
This PR https://github.com/usememos/memos/pull/3491 I think should fix it
