### ISSUE TITLE
Quick access to edit memo function

### ISSUE THREAD

**Issue by cdanne** [usememos/memos#3488]
### Describe the solution you'd like

It would be great if there was a quicker way to edit a memo.
I regularly update or rewrite my memos.
This would much easier to do for a lot of memos if the edit button was accessible directly (without a context menu).
Suggestions:
1. Start edit mode on Alt + Click e.g. on the content _or_
2. Show the edit button on hover (next to react and comment) 
![image](https://github.com/usememos/memos/assets/902285/d857fd58-778f-457a-bf68-0baaa7f8030e)
Thank you for the hard work!

### Type of feature

User Interface (UI)

**Comment by tigerzioo** [comment]
Used to have "Double click" to edit. Hope they can bring it back.

**Comment by cdanne** [comment]
Double click would be perfect! 👍
Didn't know that already worked in an earlier version.

**Comment by mmacdo54** [comment]
Looks like double click is enabled on that component - have you got it turned on in settings? 
<img width="1043" alt="image" src="https://github.com/usememos/memos/assets/79853687/611b754c-8f6f-455b-bbe7-8273ea296afc">

**Comment by cdanne** [comment]
@mmacdo54 Thank you for the hint 👍
I did not have this option running 0.22 (stable) though.
I updated to latest 0.22.1 and it seems it was re-introduced there.
Works like charm...
