### ISSUE TITLE
Live preview of markdown

### ISSUE THREAD

**Issue by sawa-ko** [usememos/memos#3495]
### Describe the solution you'd like

Currently the application supports markdown for notes, but markdown is not visible until the note is already saved, which makes it a bit difficult to design a good note and avoid markdown errors.

I would like to see the markdown preview while writing, like notion, affine, etc for example.

### Type of feature

User Interface (UI)

**Comment by MehadND** [comment]
Live Markdown Preview is on the roadmap. Let's hope it gets integrated into Memos soon.

**Comment by azzamsa** [comment]
What MehadND means is https://github.com/orgs/usememos/projects/5/views/1?pane=issue&itemId=42617384
