### ISSUE TITLE
Wanna old style timeline back

### ISSUE THREAD

**Issue by cre8orchin** [usememos/memos#3498]
### Describe the bug

After I update to 0.22, I found the logic of timeline had changed totally: 
Before 0.19, timeline seems always sorts all my notes in the order of creating time no matter what the main page appears. That's the real deal timeline, which is really helpful for some huge todo list I put on top which blocks the main page of something I need to review. So I used timeline a lot before.
After 0.22, the timeline just seems like a "date filter" function. which is same as the calender function in the old version. But where are my time-sorting page? lost forever?
And the new "timeline" loads really slow...

And the database changed in 0.22? That causes my ios app crash.

I don't understand, why to change so much in one version...

### Steps to reproduce

1. Go to Memos 
2. Click on Timeline 
3. See nothing, or the only notes I take today, or someday I choose. But who can always remember the time he took that note? That's not good. I could see all the time-order-notes before, and apply filters as I liked including date filter or not.

### The version of Memos you're using

0.22

**Comment by Logikoz** [comment]
up
