### ISSUE TITLE
最新版本什么时候才能支持 minio S3存储？

### ISSUE THREAD

**Issue by Gavincent1** [usememos/memos#3500]
### Describe the solution you'd like

旧版本数据资源都是存储在 minio 中，希望 memos 最新版本能支持 minio S3存储。非常感谢🙏

### Type of feature

Integrations

**Comment by ertuil** [comment]
S3 storage still works for me in the latest version. However, it may be necessary to re-configure the S3 storage.
Besides, there is currently no automatical migration, and I have to implement a migration script in the database to convert the old S3-related resource entities into the new format.

**Comment by zhaoyibo** [comment]
需要重新配置。
另外就是之前有的两个选项：url 前缀 和 url 后缀 没有了。对于用 r2 的我来说，已经废了。

**Comment by Gavincent1** [comment]
> 它在最新版本中应该仍然受支持并且更易于配置。

并不会，在最新版本里面会自动将Bucket拼接到Endpoint中，这会导致无法连接上 minio；还有之前的前缀URL和后缀URL 功能很好用，因为我是在Endpoint中配置了私有地址，在前缀 URL 中配置了 CDN 地址，现在没有了前缀 URL 功能导致我无法使用自定义 CDN 链接了。

**Comment by germless** [comment]
真是服了，原本使用 minio 老版本好好的，升级之后不能用了，之前的资源也没了

**Comment by wpengsen** [comment]
你们看看这篇文章能给你们提供帮助吗[memos从0.21更新到0.22后minio对象存储问题](https://bangkaixin.com/archives/1732590254015)
