### ISSUE TITLE
all tags are removed when I update to 0.22.0

### ISSUE THREAD

**Issue by lee88688** [usememos/memos#3502]
### Describe the bug

as the title says, all tags are removed when I updated to 0.22.0.
now I need to re-edit the memos which contain tags and save to add the tags to the memos again.

### Steps to reproduce

sorry for forgetting the previous version. may be 0.20.x or 0.21.x 😂. 
I use docker compose to deploy and sqlite as db. then just update docker image to 0.22.0.

### The version of Memos you're using

0.22.0

**Comment by X0ym** [comment]
try clicking statistics refresh

**Comment by lee88688** [comment]
@X0ym thanks for your reply, but I can't find this button😂. where can I find it?

**Comment by X0ym** [comment]
I just upgraded to 0.22.1, before that I was on 0.20。
![image](https://github.com/usememos/memos/assets/59227573/7a9ae933-8728-400b-ba10-e1565f15bbdb)

**Comment by keller0** [comment]
<img width="1099" alt="截屏2024-06-03 14 02 21" src="https://github.com/usememos/memos/assets/19371712/3759c260-e402-4134-a075-aac7a0198499">

lost all statistics and tags after upgrade to **Version: v0.22.1**,  fixed by clicking this refresh button.
