### ISSUE TITLE
是否可以# 后面输入标签里的部分文字时自动弹出完整标签

### ISSUE THREAD

**Issue by wk-coder** [usememos/memos#351]
### Is your feature request related to a problem?

使用的时候如果是多级标签，每次都要把全部输入一遍，效率太低还很可能出错

### Describe the solution you'd like

感谢，希望可以实现哈

**Comment by neilwyh** [comment]
+1

**Comment by jxpsert** [comment]
For our non-Chinese speaking friends;
Title: Is it possible to automatically pop up the complete label when entering part of the text in the label after #
Problem: If it is a multi-level label when using it, you have to input it all every time, the efficiency is too low and errors are likely to occur

Basically, tag autocomplete.

**Comment by jxpsert** [comment]
@s0urcelab 
> PS: I can't find a place to disscuss development plan or get any infomation about Memos's future, do you have any idea?

There's a [Discord server](https://discord.gg/XK7mAURrck)!

**Comment by s0urcelab** [comment]
@jxpsert i'm already in this server, but seem like there is no DEV related discussion?

**Comment by jxpsert** [comment]
You can just ask anywhere.

**Comment by Zeng1998** [comment]
@s0urcelab 

This PR is not as perfect as I expected. I think there are too many details to consider, but I'm tired of it.

**Comment by Zeng1998** [comment]
> @s0urcelab
> 
> This PR is not as perfect as I expected. I think there are too many details to consider, but I'm tired of it.

You can try and make your PR, but I think the idea of keeping the editor of Memos "simple" remains.

**Comment by s0urcelab** [comment]
> > @s0urcelab
> > This PR is not as perfect as I expected. I think there are too many details to consider, but I'm tired of it.
> 
> You can try and make your PR, but I think the idea of keeping the editor of Memos "simple" remains.

Thx for your reply, a few question here:
How should i understand what you mean by ”simple“?
I mean, tag autocomplete is a "simple" and necessary feature, but implement maybe not that "simple".

**Comment by Zeng1998** [comment]
> > > @s0urcelab
> > > This PR is not as perfect as I expected. I think there are too many details to consider, but I'm tired of it.
> > 
> > 
> > You can try and make your PR, but I think the idea of keeping the editor of Memos "simple" remains.
> 
> Thx for your reply, a few question here: How should i understand what you mean by ”simple“? I mean, tag autocomplete is a "simple" and necessary feature, but implement maybe not that "simple".

the implementation.

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/pull/2126
