### ISSUE TITLE
0.22.1 显示更多按钮不显示 "Show More" button not displaying

### ISSUE THREAD

**Issue by NoChantingWaterMagic** [usememos/memos#3513]
### Describe the bug

挺喜欢以前版本的memos中长内容会自动折叠并显示‘显示更多’按钮，这样界面看起来会更加简洁紧凑。
但是在v0.22.1的更新后，无论我怎么设置（例如尝试调整设置菜单中的‘Enable auto compact’开关），memos始终都被完整显示。我希望memos是否被完整显示的控制权可以交给用户，因为关于这一点的需求实在是难以统一。

I quite liked the previous versions of memos where long content would automatically collapse and show a 'Show More' button, making the interface look more concise and compact. However, after the v0.22.1 update, no matter how I adjust the settings (such as trying to toggle the 'Enable auto compact' switch in the settings menu), memos are always displayed in full. I hope the control over whether memos are fully displayed can be given to the user, as it's challenging to have a unified need regarding this aspect.

### Steps to reproduce

1.打开memos；
2.观察界面。

1.Open memos;
2.Observe the interface.

### The version of Memos you're using

0.22.1

### Screenshots or additional context

new version：
![image](https://github.com/usememos/memos/assets/120241623/6f7a5ad7-080b-4d4e-9a72-02d08089835c)
![image](https://github.com/usememos/memos/assets/120241623/22353fbd-71f4-4082-b38d-0e9f37ba59ec)
old version：
![image](https://github.com/usememos/memos/assets/120241623/17a045c6-8d62-4982-984c-adc222b6766a)

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/e40b39033fae30a05485ba1b2c8927288f1d74fd
