### ISSUE TITLE
Unable to display markdown table

### ISSUE THREAD

**Issue by JZLeung** [usememos/memos#3514]
### Describe the bug

The markdown table syntax is entered in the text box, but the syntax is not formatted into a table after being saved.

### Steps to reproduce

1. my markdown table:
```markdown
| Role  	| CREATE 	| READ 	| UPDATE 	| DELETE 	|
|-------	|--------	|------	|--------	|--------	|
| Users 	| ✅      	| ⬜︎    	| ✅      	| ✅      	|
```

2. save

### The version of Memos you're using

Version: v0.22.1

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/7995232/05fd6b2c-1413-4357-b668-40d1eb7de95e)

**Comment by mmacdo54** [comment]
It looks like the package that renders this recognises it as a table if it only has one space gap on each row so reformatting your example above to 

| Role | CREATE | READ | UPDATE | DELETE |
| ------- | -------- | ------ | -------- | -------- |
| Users | ✅ | ⬜︎ | ✅ | ✅ |

This works

**Comment by boojack** [comment]
Memos supports some markdown syntax in a strict format. Just like @mmacdo54 said, you need to add spaces to the left and right of the cell to render Table.
