### ISSUE TITLE
Unable to Add More Than One References

### ISSUE THREAD

**Issue by gitkeniwo** [usememos/memos#3516]
### Describe the bug

Not sure if this is by design or a bug, but you cannot add two or more reference to a single memo right now

### Steps to reproduce

1. Intend to add two references. Uncheck "Use as Embedded Content"

<img width="50%" alt="image" src="https://github.com/usememos/memos/assets/34304497/27d78c05-bb10-4103-9d96-1a8478f747cc">

2. Only the first one is populated to the editor

<img width="50%" alt="image" src="https://github.com/usememos/memos/assets/34304497/5830a1ca-308f-4181-af34-d04043d28417">

### The version of Memos you're using

0.22.1

**Comment by mmacdo54** [comment]
This PR https://github.com/usememos/memos/pull/3518 should fix the issue
