### ISSUE TITLE
请问如何才能从最新版本的安全退回memo v0.21.0版本。

### ISSUE THREAD

**Issue by 3217237831456** [usememos/memos#3520]
### Describe the solution you'd like

由于有新的推送，可以更新到最新版本V0.22.0版本。但最新版本没有了标签折叠功能。标签很散乱而且太多了。无法做笔记使用，所以想退回原来的V0.21.0版本。但是发现退回原先的版本，一直显示正在加载数据中。已经测试过很多次了。由于备份的数据还是4月份的，所以想请大大们给出一个安全退回V0.21.0的办法，感谢！

### Type of feature

User Interface (UI)

**Comment by Gavincent1** [comment]
由于‘tag’数据表被删除，所以即使退回到0.21版本也会没有所有的标签，但是手动编辑一次也会重新生成标签。
**回退步骤：**
1. 将数据表“memo，resource，storage，user”四张表备份下来；
2. 创建新的 memos 数据库；
3. 启动一个 docker 容器连接到新数据库并等待初始化完成；
4. 初始化完成之后新数据库里面会自动生成0.21版本的数据表，这个时候将备份下来的四张数据表结构手动修改为0.21版本的数据表结构；
5. 将新数据库里面对应的四张数据表删除，然后将手动修改完成的四张数据表导入到新数据库里面；
**提示：**
导入成功之后，0.21版本就可以成功启动了；手动修改数据库文件是一件危险的事情，请谨慎操作；

**Comment by 3217237831456** [comment]
不好意思，我不太了解数据库构成和相关操作，是对直接的memo.db进行处理嘛?

**Comment by boojack** [comment]
Refer to https://github.com/orgs/usememos/discussions/3522
