### ISSUE TITLE
A memo can not support multiple references？

### ISSUE THREAD

**Issue by gujin03** [usememos/memos#3521]
### Describe the bug

I remember that before version 0.21, a memo can support multiple references, but if you add two references on 0.21, the second reference will overwrite the first reference. Please developers fix it, thank you.

### Steps to reproduce

1.input a memo
2.add first reference
3.add second reference and save
4.the first reference lost

### The version of Memos you're using

0.21.0

**Comment by mmacdo54** [comment]
Should be solved as part of https://github.com/usememos/memos/issues/3516
