### ISSUE TITLE
Enable to save memo's setting

### ISSUE THREAD

**Issue by MehadND** [usememos/memos#3523]
### Describe the bug

For some reason you cannot save the settings in `setting > memo`. Whenever you change an option for example enabling auto compact mode and hit save. Then when you go back to the home page, the changes are not saved.

### Steps to reproduce

1. Go to setting
2. Then go to memo settings
3. change any option, e.g. enable double click to edit
4. Hit save

### The version of Memos you're using

0.22

### Screenshots or additional context

This bug was found when using the [Demo Site](https://demo.usememos.com)

**Comment by mmacdo54** [comment]
Updating settings are not allowed on the demo site - there is no issue on your own implementation though
