### ISSUE TITLE
Accessing the website deployed using Docker is loading extremely slowly.

### ISSUE THREAD

**Issue by jixishi** [usememos/memos#3527]
### Describe the bug

The server has a bandwidth of 30M. GetAuthStatus and SearchUsers take 5.7 minutes and 4.2 minutes respectively.

### Steps to reproduce

Request the homepage normally.
Access the address: https://notes.starss.cc/

### The version of Memos you're using

docker 0.21.0

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/57534147/c5315737-5e31-49eb-bf7d-2aa7e531b8ff)

**Comment by boojack** [comment]
Due to limited development resources, previous versions are no longer maintained. Please try to update to the latest version.
