### ISSUE TITLE
A way to set permissions for SSO users explicitly

### ISSUE THREAD

**Issue by betterthanever2** [usememos/memos#3528]
### Describe the solution you'd like

I have recently set up SSO with Authentik. I have not found in the documentation a way to match permissions for the users. 

For context, I now have 2 accounts in Memos: `acc1` was created initially and has `host` status; `acc2` is the one generated by SSO sign-in, it has `user` status. 

Ideally, I would like to merge them, but if I'd be able to elevate `acc2` to admin role AND quickly move the notes I have already created under the `acc1`, that would also be cool.

### Type of feature

User Experience (UX)

### Additional context

I have faced a similar issue not long ago when installing Homarr (a home dashboard solution): their way is to declare additional env variables `AUTH_OIDC_OWNER_GROUP` and `AUTH_OIDC_ADMIN_GROUP` set to the name(s) of groups in Authentik.

**Comment by ScubaCaribe** [comment]
I'm honestly shocked that there have been no responses to this, as I am facing the same issue.
