### ISSUE TITLE
上传文件错误 413 (Request Entity Too Large)

### ISSUE THREAD

**Issue by Boozai233** [usememos/memos#3537]
### Describe the bug

在1panel下安装的memos
使用Cloudflare R2 配置了S3
最大上传大小也设置了2048Mib
nginx.conf 的 client_max_body_size 2048m; 也修改了
上传超过1GB就提示 Request Entity Too Large
上传小文件没问题

### Steps to reproduce

1.配置好S3后
2.上传超过1GB文件

### The version of Memos you're using

0.22.2

**Comment by b-yp** [comment]
413 检查你的 Nginx 配置，设置 client_max_body_size
