### ISSUE TITLE
奉劝各位开发者多听听用户的声音，不要一意孤行

### ISSUE THREAD

**Issue by m1732948116** [usememos/memos#3541]
### Describe the solution you'd like

自从版本更新到v0.22以后，且不说bug，有多少用户吐槽功能还不如从前，开历史倒车
每次有人反映就立马关闭issues，给出的理由是：你不想更新可以不更。
每天都有人问：怎么回退至v0.21版，既然如此还不如多开个分支，看看哪边的下载量大，用户的反馈好
我还是建议这么大的开源项目，改的要慎重一些，听听用户的反馈，回滚不丢人

### Type of feature

User Interface (UI)

### Additional context

真的很困扰是谁执意要改成这样，多数人的建议吗？

**Comment by m1732948116** [comment]
标签：原来的多级标签挺好用，现在取消多级标签理由是为了多列显示并显示memos数目？且不说新功能实不实用。我的评价是多级标签和这些功能不冲突吧？更何况现在标签的排序方式很奇怪，一般来说不应该首字母吗？这样我原来的多级标签完全乱了，很难找到
时间线：建议直接回滚为上个版本

**Comment by yihanglee-cn** [comment]
同意，很多功能越改越不好用，还不给自定义开关，就像之前那个链接预览，加上这个功能页面都卡爆了，还不给关闭开关。虽然是白嫖没错，但是越改越烂真的不得不吐槽。

**Comment by x2358473** [comment]
0.18就挺好的。可惜无法降级。数据会出错，后面的版本好些问题都没改掉。只能说就这样吧。

**Comment by m1732948116** [comment]
希望各位开发者不要只想听到夸赞的声音，而忽略其他用户的反馈

**Comment by Zeng1998** [comment]
Memos is an open-source project where you have the option to contribute, offer suggestions in a friendly manner, or choose not to use it. I recommend you to opt for the latter.

**Comment by m1732948116** [comment]
> Memos is an open-source project where you have the option to contribute, offer suggestions in a friendly manner, or choose not to use it. I recommend you to opt for the latter.

我的评价是，你急了，听不得别人说不好
怎么连建议都不让提了呢

**Comment by x2358473** [comment]
> Memos 是一个开源项目，你可以选择贡献自己的力量，友好地提出建议，或者选择不使用它。我建议你选择后者。

不要急着关闭。我只想问下如何可以降级到0.18版本。因为后面的版本实在难用。连最基本的一个markdown语法问题修复了四个版本了还有问题。我直接使用0.18的镜像安装后新增记录会报错。

**Comment by x2358473** [comment]
> 同意，很多功能越改越不好用，还不给自定义开关，就像之前那个链接预览，加上这个功能页面都卡爆了，还不给关闭开关。虽然是白嫖没错，但是越改越烂真的不得不吐槽。

如果是用来记录一些比较重要的教程、日记、工作内容，我推荐 "joplin"。我目前已经在用，页面虽然不好看，但功能好用。可以调用外部的typora软件进行markdown编写。多平台客户端同步。如果是想要这种零散记录的。那只能找其它的了。

**Comment by 6uu1** [comment]
> > 同意，很多功能越改越不好用，还不给自定义开关，就像之前那个链接预览，加上这个功能页面都卡爆了，还不给关闭开关。虽然是白嫖没错，但是越改越烂真的不得不吐槽。
> 
> 如果是用来记录一些比较重要的教程、日记、工作内容，我推荐 "joplin"。我目前已经在用，页面虽然不好看，但功能好用。可以调用外部的typora软件进行markdown编写。多平台客户端同步。如果是想要这种零散记录的。那只能找其它的了。

感谢建议，本来是想当记录和博客二合一，不过现在感觉这个项目开发者不太友好，还有就是后台没有迁移备份功能，已经准备转移了，顺便问问，怎么把现有的数据转移到其他程序/应用上去

**Comment by i-iooi-i** [comment]
非引战，建议试试Blinko这个项目：https://github.com/blinko-space/blinko
支持导入 Memos 的数据。

**Comment by ClarkQAQ** [comment]
确实. 几个月前看着感觉不错, 等到想实际搭建来用的时候发现完全变样了, 还以为走错项目了

本来的 UI 左右搭配很均衡, 现在却像一颗歪脖子树一样丑, 而且热力图也砍了...
