### ISSUE TITLE
Unable to sign into account after logging out

### ISSUE THREAD

**Issue by bpoteryko** [usememos/memos#3564]
### Describe the bug

Mis-clicked the 'sign out' option and now Memos will not allow me to sign in again. When I attempt to sign in by navigating to `http://<my-server>:5230/auth` the page shows me the sign in page for an instant, then changes to a screen with the logo in the centre, and no controls aside from language and dark/light mode at the bottom.

The log file in the Docker container produces the following whenever I visit the sign-on page, it appears the issue is my user is not found. 

```
memos  | 2024/06/13 02:33:10 INFO OK method=/memos.api.v1.WorkspaceService/GetWorkspaceProfile
memos  | 2024/06/13 02:33:10 INFO client error method=/memos.api.v1.AuthService/GetAuthStatus error="rpc error: code = Unauthenticated desc = user not found"
memos  | 2024/06/13 02:33:10 INFO OK method=/memos.api.v1.WorkspaceSettingService/GetWorkspaceSetting
memos  | 2024/06/13 02:33:10 INFO OK method=/memos.api.v1.IdentityProviderService/ListIdentityProviders
```

I tried several other browsers and the issue remains, however the Android app MoeMemos is unaffected, I am still able to log in and create memos just fine on my phone.

### Steps to reproduce

1. Click the sign out button on the left and allow the page to sign out.
2. Click the sign in button on the left hand side.
3. Memos should now produce a sign in screen for a fraction of a second, then show just the logo.

### The version of Memos you're using

v0.22.2

I attempted to downgrade, changing to v0.21.0 allows me to sign in again, but the client is unable to read any existing memos nor allow me to create new ones, and when upgrading back to latest, the original issue begins again.

### Screenshots or additional context

This is what the blank screen looks like:
![image of blank screen](https://github.com/usememos/memos/assets/50219129/2266402b-f706-45b8-989b-158e1d6febb3)

**Comment by DRazumovskiy** [comment]
After downgrading to 0.22.0 I've lost all items from Timeline. Now it's empty

**Comment by lovwyr** [comment]
Same Issue here, its fixable by restarting the Container but its very annoying. 
Side Remark: this only happens on an new Instance (0.22.2) for me. My upgraded old Instance are not facing it.

**Comment by bpoteryko** [comment]
To provide an update, I have managed to log in using the Vivaldi browser, but Firefox-based ones still provide the issue I initially described.

**Comment by bpoteryko** [comment]
Issue fixed with updating to the most recent version.
