### ISSUE TITLE
能不能增加一个选项，允许关闭鼠标经过链接时的链接自动预览？

### ISSUE THREAD

**Issue by hellodk34** [usememos/memos#3570]
### Describe the solution you'd like

能不能增加一个选项，允许关闭鼠标经过链接时的链接自动预览？

目前的自动预览感觉很影响 memo 的观感，那个链接会被自动预览，而我不需要这样的功能，然后会占据页面元素影响了memo 本身其他文字内容的显示。最关键的是在鼠标移除之后自动预览的链接内容并没有自动消失，反而占据了原本位置，很影响阅读。

### Type of feature

User Experience (UX)

### Additional context

![image](https://github.com/usememos/memos/assets/28612780/1f66c563-5294-4469-962b-6934f907a2d7)

**Comment by yihanglee-cn** [comment]
我通过自定义JS阻止了GetLinkMetaData API，参考代码如下：
```js
window.fetch = new Proxy(window.fetch, {
    apply(target, thisArg, args) {
        const url = args[0];
        // 检查请求的URL是否是我们想要阻止的API
        if (url.includes('/memos.api.v1.MarkdownService/GetLinkMetadata')) {
            // 返回一个空的Promise，模拟请求被取消
            return Promise.resolve({
                ok: true,
                json: () => Promise.resolve({}),
            });
        }
        // 如果不是我们要阻止的请求，就正常执行Fetch
        return target.apply(thisArg, args);
    }
});
```

**Comment by hellodk34** [comment]
@yihanglee-cn  感谢分享，我使用了你的代码也成功了。

就是很奇怪，保存了好几次这段自定义 JS 代码都没有生效，重新回到设置里自定义 JS 那部分设置又变空了。。

最后一次保存应该是我切换了几个设置项 tab 之后填入再保存，最终保存成功，在浏览 memos 时且能生效。再次感谢
