### ISSUE TITLE
current version of S3 Storage cannot set url domain prefix

### ISSUE THREAD

**Issue by pecasha** [usememos/memos#3575]
### Describe the solution you'd like

In previous versions it was possible to set a prefix, but when the Endpoint domain was different from the CDN domain, it was not possible to set a prefix which prevented the use of the CDN domain.

In fact, CDN image addresses only need to be spliced with `URL Prefix` and `Filepath template`, and do not need to using pre-signed url.

### Type of feature

Integrations

### Additional context

If can't using CDN, some images are too large, take longer to load.

**Comment by looksimplers** [comment]
need it too

**Comment by Gavincent1** [comment]
真的很需要 +1

**Comment by zhaoyibo** [comment]
Really need +1
