### ISSUE TITLE
Missing filtered tags

### ISSUE THREAD

**Issue by tigerzioo** [usememos/memos#3577]
### Describe the bug

It was on 22.0 but it is missing on 22.2. It is very hard to remove filtered tags. I have to look at my 60+ tags lists to find which tag I clicked and click again to remove the filter. 
See my attached screenshot from 22.0.

### Steps to reproduce

click a tag or type a keyword to search
The filtered tags/keywords were not showed on the top of memos.

### The version of Memos you're using

0.22.2

### Screenshots or additional context

![memosfilter](https://github.com/usememos/memos/assets/148376507/56f31bf8-5324-4e4a-90c5-07ce700d2047)

**Comment by oudjat** [comment]
Same error after upgrade version until 0.22.2 I lost all my tags. 
![2024-06-17_22-38memos](https://github.com/usememos/memos/assets/21109055/df58344d-b04f-4875-ab15-8191f175490f)
