### ISSUE TITLE
时间线越来越差。。。

### ISSUE THREAD

**Issue by mufengyouyang** [usememos/memos#3590]
### Describe the bug

![QQ拼音截图20240618145753](https://github.com/usememos/memos/assets/130118370/e0254ee9-6ba4-4f51-bf50-7ff559eae7fc)
![QQ拼音截图20240618145906](https://github.com/usememos/memos/assets/130118370/8d625268-d32a-4c95-865c-78fdab1b59be)
这次的0.22.2版本的时间线完全不显示以往的内容，这应该是个bug。
想要回退以前的版本，结果发现数据结构已经变了，也就是保存在本地的曾经的数据，用曾经的版本已经无法读取。。。别无选择只能使用现在的最新版本。。。诶。。。
其实早期的版本的时间显示方式很好，直接在主页的右边显示日历的缩略图，一目了然，现在反而不够直观了

### Steps to reproduce

这次的0.22.2版本的时间线完全不显示以往的内容，这应该是个bug。
想要回退以前的版本，结果发现数据结构已经变了，也就是保存在本地的曾经的数据，用曾经的版本已经无法读取。。。别无选择只能使用现在的最新版本。。。诶。。。
其实早期的版本的时间显示方式很好，直接在主页的右边显示日历的缩略图，一目了然，现在反而不够直观了

### The version of Memos you're using

以前是是0.21.0，现在是0.22.2

**Comment by i-iooi-i** [comment]
确实无法理解为什么要把主页的热力图删掉，而非要新开一个页面做时间线+热力图。

**Comment by yihanglee-cn** [comment]
> 确实无法理解为什么要把主页的热力图删掉，而非要新开一个页面做时间线+热力图。

我也想恢复主页的热力图，不知道能不能用JS来实现。时间线页面对我来说完全没用。

**Comment by i-iooi-i** [comment]
> > 确实无法理解为什么要把主页的热力图删掉，而非要新开一个页面做时间线+热力图。
> 
> 我也想恢复主页的热力图，不知道能不能用JS来实现。时间线页面对我来说完全没用。

是的，从来没有使用过时间线页面。时间线页面甚至与主页功能重叠了，没搞明白这个页面存在的意义。

**Comment by i-iooi-i** [comment]
![image](https://github.com/usememos/memos/assets/1827701/d0e63198-f2a1-49df-b180-24136f76776d)
![image](https://github.com/usememos/memos/assets/1827701/ff72338c-8e54-4ce8-b2da-a1f9c756741c)

推荐 neosmemo/memos:0.17.1 这个版本

**Comment by xwshan** [comment]
> ![image](https://private-user-images.githubusercontent.com/1827701/343222583-d0e63198-f2a1-49df-b180-24136f76776d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTI3ODYsIm5iZiI6MTcxOTQ1MjQ4NiwicGF0aCI6Ii8xODI3NzAxLzM0MzIyMjU4My1kMGU2MzE5OC1mMmExLTQ5ZGYtYjE4MC0yNDEzNmY3Njc3NmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjdUMDE0MTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGJjNjE4OWQ3MjYzZmE5YTEzMjRiYTUzZmE2MjBiOTdlMDE5OTg4NmFkMzk1ZjE3NTE1NmVmZWY3OGYyM2E0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.m_btZM4k1TMYLsbpDjt2Oxvwo0QP38iJAdxK9U7QPhE) ![image](https://private-user-images.githubusercontent.com/1827701/343222765-ff72338c-8e54-4ce8-b2da-a1f9c756741c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTI3ODYsIm5iZiI6MTcxOTQ1MjQ4NiwicGF0aCI6Ii8xODI3NzAxLzM0MzIyMjc2NS1mZjcyMzM4Yy04ZTU0LTRjZTgtYjJkYS1hMWY5Yzc1Njc0MWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjdUMDE0MTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzgzM2FkMTZmYzZhMDk0OGJjN2UzYWE5ODVjNzY1MmEwN2IwOTBhZDQ5YzMwYmIzYWRmZjk4ZDRkMjY3ODA0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6sdR3GzF8-ljboFUtWREhk7ylXIo3Hw7-cluGIhQv5c)
> 
> 推荐 neosmemo/memos:0.17.1 这个版本，主页是有热力图的。

我尝试了这个版本，知道为什么，别的设备上登录不了，提示 missing access token。别的设备上网页登录，和APP登录都不行。
后来去部署主机上，尝试将token删除一些，然后就又能在其他设备上登录了。
这种情况，你们遇到过吗？不能每次，都要手动删除token吧 😄

**Comment by i-iooi-i** [comment]
> > ![image](https://private-user-images.githubusercontent.com/1827701/343222583-d0e63198-f2a1-49df-b180-24136f76776d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTI3ODYsIm5iZiI6MTcxOTQ1MjQ4NiwicGF0aCI6Ii8xODI3NzAxLzM0MzIyMjU4My1kMGU2MzE5OC1mMmExLTQ5ZGYtYjE4MC0yNDEzNmY3Njc3NmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjdUMDE0MTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGJjNjE4OWQ3MjYzZmE5YTEzMjRiYTUzZmE2MjBiOTdlMDE5OTg4NmFkMzk1ZjE3NTE1NmVmZWY3OGYyM2E0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.m_btZM4k1TMYLsbpDjt2Oxvwo0QP38iJAdxK9U7QPhE) ![image](https://private-user-images.githubusercontent.com/1827701/343222765-ff72338c-8e54-4ce8-b2da-a1f9c756741c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTI3ODYsIm5iZiI6MTcxOTQ1MjQ4NiwicGF0aCI6Ii8xODI3NzAxLzM0MzIyMjc2NS1mZjcyMzM4Yy04ZTU0LTRjZTgtYjJkYS1hMWY5Yzc1Njc0MWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjdUMDE0MTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzgzM2FkMTZmYzZhMDk0OGJjN2UzYWE5ODVjNzY1MmEwN2IwOTBhZDQ5YzMwYmIzYWRmZjk4ZDRkMjY3ODA0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6sdR3GzF8-ljboFUtWREhk7ylXIo3Hw7-cluGIhQv5c)
> > 推荐 neosmemo/memos:0.17.1 这个版本，主页是有热力图的。
> 
> 我尝试了这个版本，不知道为什么，别的设备上登录不了，提示 missing access token。别的设备上网页登录，和APP登录都不行 (刚开始是可以的，试了很多次)。 后来去部署主机上，尝试将token删除一些，然后就又能在其他设备上登录了。 这种情况，你们遇到过吗？不能每次，都要手动删除token吧 😄

试试比这个更早前的版本看看呢？

**Comment by xwshan** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/1827701/343222583-d0e63198-f2a1-49df-b180-24136f76776d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTI3ODYsIm5iZiI6MTcxOTQ1MjQ4NiwicGF0aCI6Ii8xODI3NzAxLzM0MzIyMjU4My1kMGU2MzE5OC1mMmExLTQ5ZGYtYjE4MC0yNDEzNmY3Njc3NmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjdUMDE0MTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGJjNjE4OWQ3MjYzZmE5YTEzMjRiYTUzZmE2MjBiOTdlMDE5OTg4NmFkMzk1ZjE3NTE1NmVmZWY3OGYyM2E0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.m_btZM4k1TMYLsbpDjt2Oxvwo0QP38iJAdxK9U7QPhE) ![image](https://private-user-images.githubusercontent.com/1827701/343222765-ff72338c-8e54-4ce8-b2da-a1f9c756741c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTI3ODYsIm5iZiI6MTcxOTQ1MjQ4NiwicGF0aCI6Ii8xODI3NzAxLzM0MzIyMjc2NS1mZjcyMzM4Yy04ZTU0LTRjZTgtYjJkYS1hMWY5Yzc1Njc0MWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjdUMDE0MTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzgzM2FkMTZmYzZhMDk0OGJjN2UzYWE5ODVjNzY1MmEwN2IwOTBhZDQ5YzMwYmIzYWRmZjk4ZDRkMjY3ODA0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6sdR3GzF8-ljboFUtWREhk7ylXIo3Hw7-cluGIhQv5c)
> > > 推荐 neosmemo/memos:0.17.1 这个版本，主页是有热力图的。
> > 
> > 
> > 我尝试了这个版本，不知道为什么，别的设备上登录不了，提示 missing access token。别的设备上网页登录，和APP登录都不行 (刚开始是可以的，试了很多次)。 后来去部署主机上，尝试将token删除一些，然后就又能在其他设备上登录了。 这种情况，你们遇到过吗？不能每次，都要手动删除token吧 😄
> 
> 试试比这个更早前的版本看看呢？

现在使用0.14.4版本，还可以 😄
