### ISSUE TITLE
After clicking the tag filter, the problem of not being able to return to the home page

### ISSUE THREAD

**Issue by yaoleistable** [usememos/memos#3594]
### Describe the bug

Clicking the tag to filter, it fails to display which tag is filtered as before, and then clicking the home button in the upper left corner again, it cannot return to the home page normally and cannot jump.

### Steps to reproduce

1. Clicking the right tag to filter, it fails to display which tag is selected in the middle as before, and it is impossible to select multiple tags at the same time.
2. Clicking the main button does not jump, and it remains on the filtered tab page.

### The version of Memos you're using

0.22.2

**Comment by tigerzioo** [comment]
I found this issue as well. You have to click the tag on the right side again to remove the filter.

**Comment by electricmessiah** [comment]
This issue can also arise if a tag is filtered and the tag is deleted while the filter is still active.

**Comment by Folas1337** [comment]
Yeah, this bug is actually quite annoying and it seems that you can click on Home (or Explore) and if you then refresh the browser, it's working fine but before that, the tag filter is internally still applied.

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/cd38ec93ed41166d791a1def02a125434ca3f558

https://github.com/user-attachments/assets/1a1bbb70-1b41-45c2-ae85-33b89c4119bc
