### ISSUE TITLE
data is missing when I upgrade the docker image

### ISSUE THREAD

**Issue by Kellermaan** [usememos/memos#3595]
### Describe the bug

Hi,
I'm not sure what's wrong I'm doing here.
I upgraded my docker image of memos, using the old data. when I finished the upgrade, all the memos are missing.

### Steps to reproduce

just upgrade the docker image.

### The version of Memos you're using

latest stable

**Comment by Zeng1998** [comment]
Backup your database file so that your data is never lost.

And please provide more context or logs.

**Comment by RaphaelPour** [comment]
Did you create a [volume](https://docs.docker.com/storage/volumes/) within your docker setup for your data? Otherwise it's not persistent, as the [docker manual states](https://docs.docker.com/storage/):

> By default all files created inside a container are stored on a writable container layer. This means that:
>
> - The data doesn't persist when that container no longer exists, and it can be difficult to get the data out of the container if another process needs it.

**Comment by Kellermaan** [comment]
I've designated the file path for the persistent files. it just didn't work.

**Comment by RaphaelPour** [comment]
ow do you deploy the memos container? If you do it like stated in the [memos docs](https://www.usememos.com/docs/install/container-install), your data should be persistent:

docker run:
```
docker run -d \
  --init \
  --name memos \
  --publish 5230:5230 \
  --volume ~/.memos/:/var/opt/memos \
  neosmemo/memos:stable
```

docker-compose:
```
services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    volumes:
      - ~/.memos/:/var/opt/memos
    ports:
      - 5230:5230
```

**Comment by Kellermaan** [comment]
I used the first one. it's wired that the data are missing. But when I use the old version of image, the data are back. I'm thinking maybe there are some incompatible things happened here.

**Comment by beast-pro** [comment]
I encountered the same issue. When I switched to the 22.4 image, there was no data. However, when I reverted to the 22.2 image, the data was normal.
