### ISSUE TITLE
New local Admin users do not have Admin roles and capabilities

### ISSUE THREAD

**Issue by SpaceIgniter** [usememos/memos#3597]
### Describe the bug

When adding a new User as an Admin, the user does not have any Admin capabilities.
The initial Admin user has all Admin functions/capabilities.
Any new added Admin user only has standard user capabilities.

### Steps to reproduce

Add a new local Admin user

### The version of Memos you're using

v0.22.2

### Screenshots or additional context

The Admin users are setup using the standard web interface, no SSO is implemented.

**Comment by Zeng1998** [comment]
The current implementation treats the Admin role as essentially the same as the regular User role, both in the front-end and back-end code.

Currently, there are three user roles: Host, Admin, and User. However, only the Host user has additional capabilities.

I believe this is an incomplete feature, and the roles and their capabilities need to be better defined.

**Comment by SpaceIgniter** [comment]
> The current implementation treats the Admin role as essentially the same as the regular User role, both in the front-end and back-end code.
> 
> Currently, there are three user roles: Host, Admin, and User. However, only the Host user has additional capabilities.
> 
> I believe this is an incomplete feature, and the roles and their capabilities need to be better defined.

Thanks, do you know of any way to make another Host user then?

**Comment by Zeng1998** [comment]
> > The current implementation treats the Admin role as essentially the same as the regular User role, both in the front-end and back-end code.
> > Currently, there are three user roles: Host, Admin, and User. However, only the Host user has additional capabilities.
> > I believe this is an incomplete feature, and the roles and their capabilities need to be better defined.
> 
> Thanks, do you know of any way to make another Host user then?

Maybe you can try to alter the database directly... but I am not sure.

**Comment by Zeng1998** [comment]
> > The current implementation treats the Admin role as essentially the same as the regular User role, both in the front-end and back-end code.
> > Currently, there are three user roles: Host, Admin, and User. However, only the Host user has additional capabilities.
> > I believe this is an incomplete feature, and the roles and their capabilities need to be better defined.
> 
> Thanks, do you know of any way to make another Host user then?

I will attempt to submit a PR to add some capabilities for the admin users, but not now...

**Comment by SpaceIgniter** [comment]
> > > The current implementation treats the Admin role as essentially the same as the regular User role, both in the front-end and back-end code.
> > > Currently, there are three user roles: Host, Admin, and User. However, only the Host user has additional capabilities.
> > > I believe this is an incomplete feature, and the roles and their capabilities need to be better defined.
> > 
> > 
> > Thanks, do you know of any way to make another Host user then?
> 
> I will attempt to submit a PR to add some capabilities for the admin users, but not now...

Much appreciated. :-)
