### ISSUE TITLE
S3 Endpoint に正しいURLを指定しても保存時エラーになる。('memos.'がURLに追加される)

### ISSUE THREAD

**Issue by tocynics** [usememos/memos#3601]
### Describe the bug

S3 Endpoint に正しいURLを指定しても保存時エラーになる。('memos.'がURLに追加される)

ERROR
```
failed to save resource blob: Failed to upload via s3 client: operation error S3: PutObject, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Put "https://memos.[fqdn]/assets/1718897382_test.md?x-id=PutObject": dial tcp: lookup memos.[fqdn] on 8.8.8.8:53: no such host
```

### Steps to reproduce

* 設定 -> ストレージ -> S3 を選択 -> Endpoint に "https://[fqdn]" を設定
* メモでファイルをアップロード操作をする

### The version of Memos you're using

Version: v0.22.2

**Comment by Gavincent1** [comment]
一样的问题，都说是可以支持MinIO，可是按照系统提示配置之后就会被自动（URL 中添加了“memos.”）. 如果可以希望在官网文档中可以给一个能使用的MinIO配置示例，谢谢！

**Comment by WyInnovate** [comment]
> 一样的问题，都说是可以支持MinIO，可是按照系统提示配置之后就会被自动（URL 中添加了“memos.”）. 如果可以希望在官网文档中可以给一个能使用的MinIO配置示例，谢谢！

之前版本我用MinIO存的可以正确的下载，但是如今的版本，我今天想上传就发现是如题同样的问题，版本是v0.22.2，我在考虑回退版本是否可用
@Gavincent1

**Comment by WyInnovate** [comment]
@Zeng1998 
Can you solve it? Thank you.
