### ISSUE TITLE
Memos does not start after reboot

### ISSUE THREAD

**Issue by pagenstedt** [usememos/memos#3602]
### Describe the bug

I installed memos a few month ago with Docker Run.
Upgrades work fine. 
However, after every server reboot, Memos does not work anymore.
I have to run docker manually, to make it work.

### Steps to reproduce

This is not a bug, but I do not know how to configure Docker Memos properly.
Thanks for your hint.

### The version of Memos you're using

Version: v0.22.2

**Comment by tigerzioo** [comment]
Add `--restart=always` when run docker run

`docker run -d --restart=always --name memos -p 5230:5230 -v ~/.memos/:/var/opt/memos ghcr.io/usememos/memos:stable`

**Comment by pagenstedt** [comment]
> Add `--restart=always` when run docker run
> 
> `docker run -d --restart=always --name memos -p 5230:5230 -v ~/.memos/:/var/opt/memos ghcr.io/usememos/memos:stable`

OK, thank you.
