### ISSUE TITLE
Disable sign up option missing - version reports as Version: v0.22.3

### ISSUE THREAD

**Issue by SpaceIgniter** [usememos/memos#3609]
### Describe the bug

For some reason Memos reports as being Version: v0.22.3.
There is also no option to disable user sign up.
User sign up is enabled by default.
This is with the Host/Admin account.

### Steps to reproduce

Click System or Memo, no user sign up option to enable or disable.
Check the version number, it reflects as v0.22.3

### The version of Memos you're using

v0.22.2

### Screenshots or additional context

Memos is deployed using easypanel.io

![Screenshot 2024-06-23 161602](https://github.com/usememos/memos/assets/85168693/9a767b21-436d-4e8c-b544-58410a77964d)
![Screenshot 2024-06-23 161620](https://github.com/usememos/memos/assets/85168693/389682a8-0513-477a-8943-2def087ddbde)
![Screenshot 2024-06-23 162116](https://github.com/usememos/memos/assets/85168693/7ad57f49-efcd-49c5-81b9-8aa0cd79bbcd)

**Comment by SpaceIgniter** [comment]
I'll close this for now until I can double-check.

It seems that easypanel deployed it with Tag: 0.22
I will redeploy with Tag: latest

Thanks

**Comment by SpaceIgniter** [comment]
Problem resolved, thanks.

I redeployed with the 0.22.2 Tag. Everything is back to normal.

**Comment by Mizimo** [comment]
I met the same issue
