### ISSUE TITLE
建议新增一些功能

### ISSUE THREAD

**Issue by renshinizhenhao** [usememos/memos#362]
### Is your feature request related to a problem?

1.当我删除一些带有图片资源的笔记的时候，发现资源库里面依然存在之前删掉的笔记图片。
2.#分类下面的笔记很多，一个一个的删掉很麻烦

### Describe the solution you'd like

1.我笔记都删掉了，这些图片不应该还存在我的资源库里面呀。弄一个删掉笔记之后询问是否需要删掉资源库里面的文件选项。
2.是不是应该弄一个类别也可以删掉的选项。还有，别忘记了也要删掉类别下的笔记资源

**Comment by Zeng1998** [comment]
目前有无一个资源绑定在多条memo的情况，或者有无这样的设计计划？ @boojack

**Comment by boojack** [comment]
@Zeng1998 我觉得可以在 resource list 里新增一个按钮，用于快速删除那些无绑定的 resource。WDYT?

**Comment by Zeng1998** [comment]
> @Zeng1998 我觉得可以在 resource list 里新增一个按钮，用于快速删除那些无绑定的 resource。WDYT?

a nice idea!

这个功能或许我可以写一下。

**Comment by Williamrjw** [comment]
有删除功能吗？怎么没看见删除笔记的功能呢？

**Comment by Zeng1998** [comment]
1. Completed.
2. No plan for now.
