### ISSUE TITLE
Unable to Input Emoji in Memos

### ISSUE THREAD

**Issue by hjxhjxjx** [usememos/memos#3623]
### Describe the solution you'd like

I encountered an issue where my memos do not support emoji input. When I try to use emojis, I get the following error:
```
Error 1366 (HY000): Incorrect string value: '\xF0\x9F\x98\x80\xF0\x9F...' for column 'content' at row 1
```
Could you please advise on how to resolve this? Should I modify the database settings, or is this a limitation of memos? If memos currently do not support emoji input, I would like to request this feature.

### Type of feature

Other

**Comment by Zeng1998** [comment]
![image](https://github.com/usememos/memos/assets/31177490/aa79b631-cb0b-4643-8451-0965d5c73b97)

Do you mean emoji like this? I think it's totally OK.
