### ISSUE TITLE
CreateResource api param externalLink not work

### ISSUE THREAD

**Issue by selfancy** [usememos/memos#3627]
### Describe the bug

CreateResource api param externalLink not work，see the postman api response, externalLink value is blank.

### Steps to reproduce

See the screenshots

### The version of Memos you're using

0.22.3

### Screenshots or additional context

<img width="773" alt="image" src="https://github.com/usememos/memos/assets/41697753/289302ae-b3b1-4635-bfaf-89b728918dea">

**Comment by Zeng1998** [comment]
It's no longer supported in this version.

https://github.com/usememos/memos/blob/46ca5bb8e7f6ba103a8dfe342c774bcb3aa18338/server/router/api/v1/resource_service.go#L40-L84
