### ISSUE TITLE
之前的tg bot功能被砍了?

### ISSUE THREAD

**Issue by Asakushen** [usememos/memos#3629]
### Describe the solution you'd like

之前很喜欢的tg bot功能非常好用,可以把很多tg频道内的有用的信息转存在笔记中,现在好像被砍了?已经没有了
希望加回来

### Type of feature

Integrations

### Additional context

真的很好用!可以把很多碰到内的优质内容转存成自己的笔记,而且可以在公开和私密中随意切换,很多信息随手一个转发再设置成公开,我的小伙伴们都能看到了,特别的好用

**Comment by IvanLi-CN** [comment]
Telegram integration has been moved to a [new standalone project](https://github.com/usememos/telegram-integration) that is much easier to use. Learn more in [usememos/telegram-integration](https://github.com/usememos/telegram-integration)

更新日志里有提到捏

**Comment by Asakushen** [comment]
谢谢解答，用上了，功能有待完善，原本的机器人可以有很多操作（公开私有相互切换等）但既然独立出去了就不再这边提建议了，谢谢开发，谢谢解答
