### ISSUE TITLE
500 error trying to use SSO with Authentik

### ISSUE THREAD

**Issue by MRobi1** [usememos/memos#3648]
### Describe the bug

I followed the instructions [here](https://www.usememos.com/docs/advanced-settings/authentik) to setup authentik as SSO using OIDC. I have other OIDC apps in Authentik that are working properly. 

When I navigate to my memos instance, I can click on the sign in with authentik button and get successfully redirected to my authentik instance. After signing in through authentik I then get redirected back to memos and am met with the following error.

> failed to exchange token, err: failed to exchange access token: Post "https://authentik.mydomain.me/application/o/token/": tls: failed to verify certificate: x509: certificate is valid for memo, not authentik.mydomain.me"

Clearly the issue has something to do with the certificate. I assume it's the SSL certificate, but not really sure where to go from here. I deleted the certificate in NPM and requested a new one from letsencrypt and didn't change anything.

Anybody have any tips?

### Steps to reproduce

Setup SSO with authentik using provided instructions.
Sign in.

### The version of Memos you're using

v0.22.3

### Screenshots or additional context

Here are my settings:
![image](https://github.com/usememos/memos/assets/34860474/f7590288-3dc2-4401-8cee-7a9ea98e8c7a)

**Comment by itodouble** [comment]
like this ?  https://github.com/usememos/memos/issues/2985

- apk add curl
- curl -v https://sso.your-server
if you see the same problem here

i use acme.sh to generate cert

add ca.pem to /usr/local/share/ca-certificates/
- update-ca-certificates
if warning 'does not contain exactly one certificate or CRL: skipping'
- openssl x509 -in ca.pem -out ca-cert-sso.your-server.ca.pem
and rm old file
- update-ca-certificates
and restart container

**Comment by MRobi1** [comment]
> like this ? #2985

Not quite. That one says cert signed by unknown authority. Mine is saying certificate is valid for memo, not authentik. I'm thinking because it redirects to authentik for SSO and then back to memo

> * curl -v https://sso.your-server
>   if you see the same problem here

Nope, don't get the same error here. Everything looks as it should.

**Comment by MRobi1** [comment]
Shame to see authentication with authentik is not planned.

**Comment by Schachte** [comment]
I'm running into the same issue despite having added self-signed cert and CA into proper locations on all my nodes. :(

**Comment by Schachte** [comment]
@MRobi1 - Let me know if that resolves the issue for you. This shouldn't be a memos issue, but just a TLS config problem.

**Comment by MRobi1** [comment]
Sadly I'm not sure I'm quite following what you did.

I use NPM on a different host, which also manages updating my certs automatically.
So if I'm understanding correctly, I'll have to manually copy those over and mount it to the memos container every time it updates? That sounds like a major PITA.

**Comment by Schachte** [comment]
@MRobi1 I'm showing the steps manually to give better insight into the problem.

You cannot make a request to a host using TLS when the client doesn't know or trust the host root CA or cert. This has nothing to do with memos though. 

It's not uncommon to auto mount rotated certs into k8s.

**Comment by MRobi1** [comment]
> This has nothing to do with memos though.

From where I stand, I currently have 40+ services run through Authentik. Around 20 with OIDC. 1 giving me a certificate error...

> However, as a quick test maybe try using a wildcard cert *.mydomain.com to rule out the problem a bit more.

Already tried moving both memos as well as authentik to a wildcard cert and it gives the same error. 

While your solution likely works, it seems like it will regularly fail as certs are updated and will require recurring manual intervention to fix each time. And like above, only 1 gives me a cert error.

Thinking I may be able to setup a share on host with my certs and mount it on host with memos so it will avoid having to manually sync it, but still a pain to have to set it up when I don't for any others. Interestingly, I don't see any mention of the env SSL_CERT_FILE in docs.

**Comment by MRobi1** [comment]
OK I downloaded the cert from NPM. 
Loaded it on to the host running memos to /root/memos/certs. 
Mounted /root/memos/certs to /usr/local/share/ca-certificates in the docker container.
Added env variable of SSL_CERT_FILE /usr/local/share/ca-certificates/cert2.pem
Restarted container
Opened incognito window and tried logging in. Same error.

**Comment by Schachte** [comment]
Did you verify in the container that both the file exists and the env is populated?

I do agree there should be some docs somewhere around this, but I only ran into it myself so without looking at the code I don't know the best suggestion yet. All I can say is that once I mounted the CA cert into Memos I was set. 


Slightly unrelated, but the whole manual mount setup can be avoided by auto syncing rotating certs into k8s. Many common ways of doing this as it's fairly standard (service mesh or you can roll a syncer yourself with little work).
