### ISSUE TITLE
标签合并的功能

### ISSUE THREAD

**Issue by flameleo11** [usememos/memos#3650]
### Describe the solution you'd like

![img_v3_02cf_aaee66e4-1e91-407f-8c74-9ac7fafa289g](https://github.com/usememos/memos/assets/6859207/6d1a4173-fae4-4c74-aecc-bbb33cf2723d)

### Type of feature

User Interface (UI)

**Comment by flameleo11** [comment]
有没有后标签合并的功能：
比如很多标签，一开始写的时候很随意
后期发现标签很多是重复的功能，
可以归类合并
比如不同的标签：tmp temp 草稿
合并指定一个新名字 tmp

**Comment by flameleo11** [comment]
这样以前生成的很多废弃的空标签，也可以管理合并了

![image](https://github.com/usememos/memos/assets/6859207/41fb4567-57a7-4ffc-a0a3-7c1a9e56e917)
比如有很多这种在链接中的标签
如果能够扫描链接，并过滤这种无效的标签就好了

**Comment by 1305536951** [comment]
标签合并的功能有个间接实现方式。鼠标悬停在右侧标签栏想更改的标签前，#会变成三个点，点击一下会出现“rename”和“delete”，点一下“rename”，修改成已有标签的名字。比如你举例的，可以把temp修改成草稿，会自动把所有“temp”标签的memos改成“草稿”标签，然后会自动合并到“草稿”标签里。
