### ISSUE TITLE
access token created everytime after the same user logout and login again

### ISSUE THREAD

**Issue by slyang40** [usememos/memos#3674]
### Describe the bug

Access token got created everytime after the same user logout and login again. and the expire date was set in 100 years. See below screenshot.
![image](https://github.com/usememos/memos/assets/127069096/f38fa2c0-b606-4c14-82e7-ee6e0bab2160)

### Steps to reproduce

1. Sign in Memos
2. check the access token generated for this login
3. logout Memos
4. login again
5. check the list of access tokens, you will find a new access token created with a pretty longer valid period, 100 years.

### The version of Memos you're using.

v0.22.2

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/127069096/2708508b-0e3a-4cea-b275-3f99bc4dcd0d)

**Comment by duckgun13476** [comment]
Yeah, I have the same problem:
![屏幕截图 2024-07-11 082648](https://github.com/usememos/memos/assets/128715149/0cd4c972-26d2-49b1-b5a5-2d9fb99fc8af)

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/6825c1def45fe61e872645cf94cfa1961612dc75
