### ISSUE TITLE
Notification Reminder Bug

### ISSUE THREAD

**Issue by ajaxgoldfish** [usememos/memos#3675]
### Describe the bug

There is an issue with the notification system in version v0.22.2. When the user admin posts a memo, user1 comments on it, and then admin replies to user1's comment, the notification received by user1 leads to a blank page upon clicking.

### Steps to reproduce

1. Log in as admin.
2. Post a memo.
3. Log in as user1.
4. Comment on the memo posted by admin.
5. Log in as admin.
6. Reply to the comment made by user1.
7. Log in as user1.
8. Click on the notification received from admin's reply.

### The version of Memos you're using.

v0.22.2

### Screenshots or additional context

![bug](https://github.com/usememos/memos/assets/100814689/c5faf262-8c3d-4c35-b53d-a3fca9a0050a)

**Comment by boojack** [comment]
Might be fixed.

**Comment by GoodReese** [comment]
> Might be fixed.

fixed now ? Still have issue in child memos' comment notification
