### ISSUE TITLE
Upload large file display error Transport error: Failed to fetch,Play video can not pull the progress bar

### ISSUE THREAD

**Issue by ZRdRy** [usememos/memos#3681]
### Describe the bug

Upload large files(several hundred MB) and wait for several seconds, it prompts Transport error: Failed to fetch, and the progress bar of uploading other video files can not be pulled.

### Steps to reproduce

Upload large files(several hundred MB) and wait for several seconds, it prompts Transport error: Failed to fetch, and the progress bar of uploading other video files can not be pulled.

### The version of Memos you're using.

v0.22.2

**Comment by ZRdRy** [comment]
Both the backend and nginx upload limit have been changed to 9999M, and it still reports an error.

**Comment by lhuanyun** [comment]
same problem .0.22.5

**Comment by RoccoSmit** [comment]
2 commits were put in place to substantially increase the file upload limits which should fix this issue. These change should be available for versions > v0.22.5

![image](https://github.com/user-attachments/assets/9f3617ed-b415-4d1c-a834-10e80086717b)

**Comment by prakashru** [comment]
Transport error: Failed to fetch when saving an articles. What is the solution?
