### ISSUE TITLE
[v0.22.3] Can we add a disable registration switch like the old version

### ISSUE THREAD

**Issue by wangningyu** [usememos/memos#3682]
### Describe the solution you'd like

Can you consider adding a registration disabled switch like the old version?

Thanks!

### Type of feature

User Interface (UI)

**Comment by tcc-123** [comment]
i need this too

**Comment by mkoechli** [comment]
I will need this too ... or i have to stopp using memo ;-( ...

**Comment by yuboabc** [comment]
WTF? Why do you allow others to register?

**Comment by hexWars** [comment]
I need this too

**Comment by MFYDev** [comment]
> WTF? Why do you allow others to register?

Dude at least use a translator

**Comment by boojack** [comment]
> feat: add public flag instead of system setting to enable signup
> 
> Because disabling registration as well as disabling password login may lead to some unforeseen problems: users can't sign in and need to modify the database. So it is recommended to put it into an environment variable.

Refer to https://github.com/usememos/memos/pull/3589
