### ISSUE TITLE
Image Preview

### ISSUE THREAD

**Issue by fattyhk** [usememos/memos#3685]
### Describe the solution you'd like

After uploading a large number of images and videos, the loading has become noticeably slower and more laggy. Could we implement a preview feature that only loads thumbnail images for browsing, and only loads the full images or videos when they are clicked?

### Type of feature

User Interface (UI)

### Additional context

No relevant options found.

**Comment by RoccoSmit** [comment]
Thumbnail functionality was added to v0.13 and then it was then removed in v0.22 as part of the "refactor: update resource binary request handler" commit. 
Feedback from Steven re deleting the functionality: "the reason for removing it before was probably refactoring and wanting to keep the code tidy and thus improve maintainability"

Link to removal PR for the final state of the `resource/resource.go` file containing the thumbnail generation logic.
[resource/resource.go](https://github.com/usememos/memos/commit/ff175bbb7e4ff8e5407786ec73bcb361033fd425#diff-7f38be2e91afd9cd1efefe248b880b8cfa4539236d228462dff7169a19ab114c)

I asked in Discord if Thumbnails could be re added and the response was positive.
https://discord.com/channels/1017113925776588902/1045138348165050409/1270757936293085194

**Comment by fattyhk** [comment]
Thanks~

**Comment by boojack** [comment]
@RoccoSmit 

* Thumbnails should reside in the local file system as an optional cache.
* It’s recommended to maintain the previous approach: only attempt to access the thumbnail when requested, and if it doesn't exist, create it and then return it.

**Comment by RoccoSmit** [comment]
PR for reintroducing thumbnails is ready for review https://github.com/usememos/memos/pull/3821
