### ISSUE TITLE
更新memos後出現無限菊花，抓取資料中

### ISSUE THREAD

**Issue by leohkz** [usememos/memos#3700]
### Describe the bug

<img width="575" alt="Screenshot 2024-07-16 062331" src="https://github.com/user-attachments/assets/e4a3bd59-e0fe-48b0-a812-4e9a05b2865e">

### Steps to reproduce

repull images to update memos from portainer

### The version of Memos you're using.

v0.22.3

**Comment by tsvico** [comment]
遇到同样的问题，控制台报错
```javascript
index-cNtELIiR.js:287                                                                                                                                     Uncaught (in promise) 
ClientError: /memos.api.v1.MemoService/ListMemos INTERNAL: grpc: error while marshaling: string field contains invalid UTF-8
```

**Comment by yn-zxj** [comment]
so do I

**Comment by utopeadia** [comment]
same problem

**Comment by Meteor-showers** [comment]
一样 这是更新了什么东西
memos  | 2024/07/16 10:20:18 ERROR: [core] [Server #1]grpc: server failed to encode response: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8

**Comment by Meteor-showers** [comment]
镜像版本作者推荐 stable 不要用latest 回退版本吧
主页运行命令
docker run -d --name memos -p 5230:5230 -v ~/.memos/:/var/opt/memos neosmemo/memos:stable

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/446e38f15be618fb3158d4631565be1ed2f3dbcc
