### ISSUE TITLE
能否加个首页排序

### ISSUE THREAD

**Issue by kylehz** [usememos/memos#3703]
### Describe the solution you'd like

参考如下：
<img width="435" alt="image" src="https://github.com/user-attachments/assets/1417de34-2d15-480c-bb7a-15b9e757f001">

### Type of feature

User Interface (UI)

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/158745704e867be1de2e20e1e40565b911ba72af

<img width="256" alt="image" src="https://github.com/user-attachments/assets/49096695-6962-44bc-90fd-4d1cafb812ce">
