### ISSUE TITLE
Backlinks Not Displayed 

### ISSUE THREAD

**Issue by gitkeniwo** [usememos/memos#3704]
### Describe the bug

Seems that backlinks are not displayed after updating to 0.22.3

I am not sure if this is supposed to be a feature or a bug

But if this is a feature, I would suggest to bring it back as backlinks are an essential functionality to zettelkasten-style note taking, which is the idea the project is built on

### Steps to reproduce

<img width="648" alt="image" src="https://github.com/user-attachments/assets/6f56b670-85a6-41eb-b9cf-0864eb432ee4">

### The version of Memos you're using.

0.22.3

**Comment by gitkeniwo** [comment]
Also, there should be a compact version of link display, at least in the form of an option, since some notes may gather quite a lot of links over time, and it is a disaster to display them all in expanded view.

**Comment by boojack** [comment]
Ready in v0.22.4

<img width="770" alt="image" src="https://github.com/user-attachments/assets/c686402c-3757-4445-9b38-c4ca49242ab8">
