### ISSUE TITLE
0.22.3版本编辑改变不了创建日期了

### ISSUE THREAD

**Issue by sq1220** [usememos/memos#3705]
### Describe the bug

0.22.3版本编辑改变不了创建日期了

### Steps to reproduce

内容--保存--下边...--编辑--日期不能选择了

### The version of Memos you're using.

0.22.3

**Comment by tombatti** [comment]
Me too, with new version cannot possibile to change date and time...
Fix it please, I have been using this option every days

Thanks
Tomas

**Comment by flyklmwl** [comment]
以前可以用 alt+双击， 现在也不行拉，求修复

**Comment by boojack** [comment]
Refer to https://github.com/usememos/memos/issues/3709
