### ISSUE TITLE
Long Markdown table not rendered

### ISSUE THREAD

**Issue by zeiktuvai** [usememos/memos#3707]
### Describe the bug

It seems that when you have a markdown table that is longer than the edit box when adding a note, the resulting note does not render the table.  When I take a table that renders in VSCode or HedgeDoc and paste it into Memos  that happens to be longer it doesn't render unless you cut it down so each row (header, separator and data) are on one line. 

It seems that when this happens, a blank line is inserted between the table rows.  When I copy the table data from Memos into vscode, each row is separated by a blank line.  But this only seems to happen on tables that wrap around to a new line.

i.e:
| header |

| ---------- |

| data     |

### Steps to reproduce

1. Add a new note
2. Add any table that wraps to a new line on each row
3. Save note

### The version of Memos you're using.

0.22.3

### Screenshots or additional context

This is the markdown table I was trying to use:

| Filament | Temperature /℃ | Time  /h | Bed Temperature  /℃ | Time  /h | Turning-over Time /h | Cover  |
| -------- | --------------- | -------- | -------------------- | -------- | -------------------- |  -------------------- | 
| TPU      | 65 - 75         | 8        | 80 - 90              | 12       | Every 6              | Filament box / PC Box |

``` markdown
| Filament | Temperature /℃ | Time  /h | Bed Temperature  /℃ | Time  /h | Turning-over Time /h | Cover  |
| -------- | --------------- | -------- | -------------------- | -------- | -------------------- |  -------------------- | 
| TPU      | 65 - 75         | 8        | 80 - 90              | 12       | Every 6              | Filament box / PC Box |
```

**Comment by boojack** [comment]
```
| Filament | Temperature /℃ | Time /h | Bed Temperature /℃ | Time /h | Turning-over Time /h | Cover                 |
| -------- | -------------- | ------- | ------------------ | ------- | -------------------- | --------------------- |
| TPU      | 65 - 75        | 8       | 80 - 90            | 12      | Every 6              | Filament box / PC Box |
```

It will only works with standard format. And Memos currently supports strictly standard Markdown.

<img width="1084" alt="image" src="https://github.com/user-attachments/assets/06bcbb5c-6c8b-4815-aab7-33a72a729af6">

<img width="772" alt="image" src="https://github.com/user-attachments/assets/dd375cd6-1a37-48c9-a894-f04b70a8b51e">

**Comment by tianzhich** [comment]
I can't see any differences.

**Comment by kahnwong** [comment]
There is a leading and trailing space for `-----` in line `60`. Making this change and memos can render markdown table normally. But if there's no leading/trailing space it would be rendered as plaintext.
