### ISSUE TITLE
Cannot possible edit date and time after update to v0.22.3

### ISSUE THREAD

**Issue by tombatti** [usememos/memos#3709]
### Describe the bug

With the new version, it is no longer possible to edit the date and time of posts....
Fix it please, I have been using this option every days

Thanks
Tomas

### Steps to reproduce

With new version cannot possibile to change date and time

### The version of Memos you're using.

v0.22.3

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/c313596144816c6cd011f49df8b947db78d7fa1b
