### ISSUE TITLE
版本升级

### ISSUE THREAD

**Issue by xwshan** [usememos/memos#3714]
### Describe the solution you'd like

现在使用的是0.18.1，如何升级0.22.3，会不会导致一些数据丢失？

### Type of feature

Other

**Comment by pipuwong** [comment]
I 1.8.2 I can't connect after upgrading, how to solve it?

**Comment by powersee** [comment]
我尝试了一下，应该会的。

我使用的是 0.18 版本，升级到 0.22.4 版本，然后所有的 tag 都消失了。

建议备份好数据，多建立一个 docker 容器试试，不要直接升级。

**Comment by xwshan** [comment]
> I try 1.8.2, and I can't connect after upgrading, how to solve it
数据没丢的话，就重新使用原来的镜像运行就行了 😃

**Comment by boojack** [comment]
New versions will have normal data migration and no data will be lost.

**Comment by xwshan** [comment]
> New versions will have normal data migration and no data will be lost.

期待 😄
