### ISSUE TITLE
管理员无法关闭注册功能

### ISSUE THREAD

**Issue by Lishuhao-lucky** [usememos/memos#3715]
### Describe the bug

管理员登陆后无法找到关闭注册的选项

### Steps to reproduce

部署本地项目后，注册后找不到关闭注册按钮

### The version of Memos you're using.

stable and latest都是这个问题

**Comment by Lishuhao-lucky** [comment]
已解决，在启动时设置参数即可取消注册参考：https://www.usememos.com/docs/install/startup-options

**Comment by 3217237831456** [comment]
老铁，我按照你给的参考，对docker 运行指令进行了修改。

指令如下：

`docker run -d --restart=always --public:false --name memos -p 5230:5230 -v /root/.memos/:/var/opt/memos neosmemo/memos:latest`

但总是提示报错：unknown flag: --public:false。请问你具体是如何解决的？ @Lishuhao-lucky

**Comment by Lishuhao-lucky** [comment]
你好，我不是直接使用docker命令的。我使用了docker-compose启动的。
具体来说，在工作目录下，例如/home/替换未你的用户名/memos/，创建文件docker-compose.yml
文件内容如下
version: '3'
services:
&nbsp; memos:
&nbsp;&nbsp;&nbsp; image: neosmemo/memos:latest
&nbsp;&nbsp;&nbsp; container_name: memos
&nbsp;&nbsp;&nbsp; environment:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - MEMOS_MODE=prod
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - MEMOS_ADDR=0.0.0.0
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - MEMOS_PORT=5230
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - MEMOS_DATA=/var/opt/memos
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - MEMOS_DRIVER=sqlite
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - MEMOS_PUBLIC=false #这里设置为false，即关闭注册按钮
&nbsp;&nbsp;&nbsp; volumes:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - ./data/:/var/opt/memos #这里的./data是我自己的数据映射位置，按照你提供的命令来看，应该替换为/root/.memos/
&nbsp;&nbsp;&nbsp; ports:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - "5230:5230"
如果你安装了docker-compose命令，则你可以创建以上提到的文件，并粘贴以上内容，按照你的实际情况修改含有备注的内容；
如果你的docker正在运行，请先停止你的docker容器，例如使用sudo docker stop memos
然后移除容器sudo docker rm memos
最后使用sudo docker-compose up -d
运行上述yml文件配置内容，容器正常启动，然后尝试访问，此时应该看不到注册按钮了。
直接使用docker run。。。。命令，我还不会加上取消注册按钮的参数，所以你可以试着使用docker-compose命令来启动容器，对应的，如果需要关掉容器，只需输入sudo docker-compose down即可
最后，祝你顺利



Shuhao-Li
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "usememos/memos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月23日(星期二) 下午2:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [usememos/memos] 管理员无法关闭注册功能 (Issue #3715)





 
老铁，我按照你给的参考，对docker 运行指令进行了修改。
 
指令如下：
 
docker run -d --restart=always --public:false --name memos -p 5230:5230 -v /root/.memos/:/var/opt/memos neosmemo/memos:latest
 
但总是提示报错：unknown flag: --public:false。请问你具体是如何解决的？ @Lishuhao-lucky

**Comment by Lishuhao-lucky** [comment]
> > Issue is not in English. It has been translated automatically.
> 
> Lao Tie, I modified the docker running instructions according to the reference you gave.
> 
> The instructions are as follows:
> 
> `docker run -d --restart=always --public:false --name memos -p 5230:5230 -v /root/.memos/:/var/opt/memos neosmemo/memos:latest`
> 
> But it always prompts an error: unknown flag: --public:false. How did you solve it specifically? @Lishuhao-lucky



> 老铁，我按照你给的参考，对docker 运行指令进行了修改。
> 
> 指令如下：
> 
> `docker run -d --restart=always --public:false --name memos -p 5230:5230 -v /root/.memos/:/var/opt/memos neosmemo/memos:latest`
> 
> 但总是提示报错：unknown flag: --public:false。请问你具体是如何解决的？ @Lishuhao-lucky
docker-compose.yml内容如下，上述邮件恢复格式不对
version: '3'
services:
  memos:
    image: neosmemo/memos:latest
    container_name: memos
    environment:
      - MEMOS_MODE=prod
      - MEMOS_ADDR=0.0.0.0
      - MEMOS_PORT=5230
      - MEMOS_DATA=/var/opt/memos
      - MEMOS_DRIVER=sqlite
      - MEMOS_PUBLIC=false # 这里设置为false，即关闭注册按钮
    volumes:
      - /root/.memos/:/var/opt/memos # 这里的./data替换为/root/.memos/
    ports:
      - "5230:5230"

**Comment by Lishuhao-lucky** [comment]
[docker-compose.txt](https://github.com/user-attachments/files/16344523/docker-compose.txt)
注意将文件后缀修改为yml

**Comment by 3217237831456** [comment]
好的，感谢老铁。
