### ISSUE TITLE
上传附件报错：failed to create resource: Error 1406 (22001): Data too long for column 'reference' at row 1

### ISSUE THREAD

**Issue by Gavincent1** [usememos/memos#3718]
### Describe the bug

上传附件报错：failed to create resource: Error 1406 (22001): Data too long for column 'reference' at row 1
- 版本0.22.3
- 后端存储是MinIO ，vhost访问方式。

### Steps to reproduce

正常上传附件

### The version of Memos you're using.

v0.22.3

### Screenshots or additional context

<img width="1457" alt="截屏2024-07-19 23 21 39" src="https://github.com/user-attachments/assets/0a39ad0d-b79d-48c9-991f-66f8f9b3f4da">

**Comment by JiangLongLiu** [comment]
可以设置上传的附件大小

**Comment by Gavincent1** [comment]
> 可以设置上传的附件大小

我设置的是60MB上传大小，然后我实际只上传了几百KB的图片文件。。。
可能并不是设置的大小问题。

**Comment by JiangLongLiu** [comment]
> > 可以设置上传的附件大小
> 
> 我设置的是60MB上传大小，然后我实际只上传了几百KB的图片文件。。。
> 可能并不是设置的大小问题。

设置后，是否重启容器？

**Comment by Gavincent1** [comment]
> > > 可以设置上传的附件大小
> > 
> > 
> > 我设置的是60MB上传大小，然后我实际只上传了几百KB的图片文件。。。
> > 可能并不是设置的大小问题。
> 
> 设置后，是否重启容器？

是的，已经重启过了。

**Comment by best** [comment]
Please take a look at the issue I created. It includes a detailed error analysis.：#3624 MySQL Resource Table reference Column Length Limitation Causes Error with OSS Object Storage

**Comment by Gavincent1** [comment]
> #3624

非常感谢你的回复，修改数据库结构之后我成功在0.22.3版本中使用MinIO存储，这太棒了

**Comment by Gavincent1** [comment]
> 请查看我创建的issue，里面有详细的错误分析：#3624 MySQL 资源表引用列长度限制导致OSS对象存储出错

让人觉得意外的是：这个BUG居然不在官方修复计划内，这就很神奇

**Comment by Cat66666666** [comment]
此时你可以用IP+端口访问memos就没有这个问题，可能还是数据库限制或者nginx限制又或者服务器限制
