### ISSUE TITLE
disallow_password_login option is gone

### ISSUE THREAD

**Issue by petrm** [usememos/memos#3719]
### Describe the bug

Latest release v0.22.3 moved the the option to disable registration to the configuration via environment variable. Same pull request also removed the possibility to disallow password loging and only leave SSO on.
Please bring back SSO-only login.

### Steps to reproduce

N/A option is not available anymore

### The version of Memos you're using.

v0.22.3

**Comment by MFYDev** [comment]
Met the same issue here

**Comment by tanpro260196** [comment]
Please bring this back, I don't want to potentially expose my host account to normal user.

**Comment by Westwall98** [comment]
Need disallow_password_login. Please bring it back

**Comment by EriTang** [comment]
Need disallow_password_login. Please bring it back

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/8bf7cdfd31037734ea91198b8d11fa3775a5faac

**Comment by Jayspek** [comment]
When I start it with the `--password-auth false`, it still says "password-auth: true" in the startup information, and I am still able to log in with a password. Seems to be broken?

**Comment by boojack** [comment]
> my_application -debug=false -another_boolean_param=boolean_value

@Jayspek Refer to https://stackoverflow.com/a/27411724
