### ISSUE TITLE
升级 0.7.0 数据库错误

### ISSUE THREAD

**Issue by anno189** [usememos/memos#372]
### Describe the bug

服务端日志：
---
succeed to copy a backup database file
start migrate
applying migration for 0.7.0
error: cannot open db: failed to apply minor version migration: migrate error: statement:PRAGMA foreign_keys=off;

DROP TABLE IF EXISTS _user_old;

ALTER TABLE user RENAME TO _user_old;

-- user
CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_ts BIGINT NOT NULL DEFAULT (strftime('%s', 'now')),
  updated_ts BIGINT NOT NULL DEFAULT (strftime('%s', 'now')),
  row_status TEXT NOT NULL CHECK (row_status IN ('NORMAL', 'ARCHIVED')) DEFAULT 'NORMAL',
  email TEXT NOT NULL UNIQUE,
  role TEXT NOT NULL CHECK (role IN ('HOST', 'USER')) DEFAULT 'USER',
  name TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  open_id TEXT NOT NULL UNIQUE
);

INSERT INTO user SELECT * FROM _user_old;

DROP TABLE IF EXISTS _user_old;

DROP TABLE IF EXISTS _memo_old;

ALTER TABLE memo RENAME TO _memo_old;

-- memo
CREATE TABLE memo (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  creator_id INTEGER NOT NULL,
  created_ts BIGINT NOT NULL DEFAULT (strftime('%s', 'now')),
  updated_ts BIGINT NOT NULL DEFAULT (strftime('%s', 'now')),
  row_status TEXT NOT NULL CHECK (row_status IN ('NORMAL', 'ARCHIVED')) DEFAULT 'NORMAL',
  content TEXT NOT NULL DEFAULT '',
  visibility TEXT NOT NULL CHECK (visibility IN ('PUBLIC', 'PROTECTED', 'PRIVATE')) DEFAULT 'PRIVATE'
);

INSERT INTO memo SELECT * FROM _memo_old;

DROP TABLE IF EXISTS _memo_old;

DROP TABLE IF EXISTS _memo_organizer_old;

ALTER TABLE memo_organizer RENAME TO _memo_organizer_old;

-- memo_organizer
CREATE TABLE memo_organizer (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  memo_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  pinned INTEGER NOT NULL CHECK (pinned IN (0, 1)) DEFAULT 0,
  UNIQUE(memo_id, user_id)
);

INSERT INTO memo_organizer SELECT * FROM _memo_organizer_old;

DROP TABLE IF EXISTS _memo_organizer_old;

DROP TABLE IF EXISTS _shortcut_old;

ALTER TABLE shortcut RENAME TO _shortcut_old;

-- shortcut
CREATE TABLE shortcut (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  creator_id INTEGER NOT NULL,
  created_ts BIGINT NOT NULL DEFAULT (strftime('%s', 'now')),
  updated_ts BIGINT NOT NULL DEFAULT (strftime('%s', 'now')),
  row_status TEXT NOT NULL CHECK (row_status IN ('NORMAL', 'ARCHIVED')) DEFAULT 'NORMAL',
  title TEXT NOT NULL DEFAULT '',
  payload TEXT NOT NULL DEFAULT '{}'
);

INSERT INTO shortcut SELECT * FROM _shortcut_old;

DROP TABLE IF EXISTS _shortcut_old;

DROP TABLE IF EXISTS _resource_old;

ALTER TABLE resource RENAME TO _resource_old;

-- resource
CREATE TABLE resource (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  creator_id INTEGER NOT NULL,
  created_ts BIGINT NOT NULL DEFAULT (strftime('%s', 'now')),
  updated_ts BIGINT NOT NULL DEFAULT (strftime('%s', 'now')),
  filename TEXT NOT NULL DEFAULT '',
  blob BLOB DEFAULT NULL,
  type TEXT NOT NULL DEFAULT '',
  size INTEGER NOT NULL DEFAULT 0
);

INSERT INTO resource SELECT * FROM _resource_old;

DROP TABLE IF EXISTS _resource_old;

DROP TABLE IF EXISTS _user_setting_old;

ALTER TABLE user_setting RENAME TO _user_setting_old;

-- user_setting
CREATE TABLE user_setting (
  user_id INTEGER NOT NULL,
  key TEXT NOT NULL,
  value TEXT NOT NULL,
  UNIQUE(user_id, key)
);

INSERT INTO user_setting SELECT * FROM _user_setting_old;

DROP TABLE IF EXISTS _user_setting_old;

DROP TABLE IF EXISTS _memo_resource_old;

ALTER TABLE memo_resource RENAME TO _memo_resource_old;

-- memo_resource
CREATE TABLE memo_resource (
  memo_id INTEGER NOT NULL,
  resource_id INTEGER NOT NULL,
  created_ts BIGINT NOT NULL DEFAULT (strftime('%s', 'now')),
  updated_ts BIGINT NOT NULL DEFAULT (strftime('%s', 'now')),
  UNIQUE(memo_id, resource_id)
);

INSERT INTO memo_resource SELECT * FROM _memo_resource_old;

DROP TABLE IF EXISTS _memo_resource_old;
 err=table resource has 8 columns but 9 values were supplied

### Steps to reproduce

服务不能启动。

### Expected behavior

服务不能启动。

### Screenshots or additional context

服务不能启动。

**Comment by boojack** [comment]
Pull the latest image firstly.

**Comment by anno189** [comment]
打包下载的版本：
/store/db/migration/prod/0.7/00__remove_fk.sql

和 git 上现有版本不一致。
git 上是正确的。发布的有问题。

因为 resource 表增加external_link后，升级数据库所致。

打包下载文件中：
95行：INSERT INTO resource SELECT * FROM _resource_old;

**Comment by anno189** [comment]
INSERT INTO resource (
  id, creator_id, created_ts, updated_ts, 
  filename, blob, type, 
  size
) 
SELECT 
  id, 
  creator_id, 
  created_ts, 
  updated_ts, 
  filename, 
  blob, 
  type, 
  size 
FROM 
  _resource_old;

**Comment by Zeng1998** [comment]
应该不用这么麻烦？  最新的镜像应该是ok的

**Comment by boojack** [comment]
There are some patch updates in `v0.7.0` after releasing. So the source code(zip or tar.gz) in `tag/v0.7.0` is outdata. Maybe you can download the source code from branch `release/0.7.0`.
