### ISSUE TITLE
Major BUG!

### ISSUE THREAD

**Issue by Cat66666666** [usememos/memos#3738]
### Describe the bug

A user posted a public memo that when the administrator deletes the user account, the exploration function will be unavailable!

### Steps to reproduce

1. The administrator creates a user account
2. The new user posts a public memo
3. The administrator deletes the account
4. The exploration function is unavailable

### The version of Memos you're using.

v0.22.3

**Comment by Cat66666666** [comment]
rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference

**Comment by hanyuwei70** [comment]
got same issue.

**Comment by cblte** [comment]
Same here. As soon as you archive and then delete the user, the posts from that deleted user are gone, but also the "Explore" page shows nothing. Version 0.22.3 here.

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/7564c40c8d846c4c30b8fb1357d23b924e16bd6c

The main reason is that there is dirty data, which can be cleaned up manually at this moment. And we'd like to implement the relevant logic in next release.

**Comment by Cat66666666** [comment]
太好了
