### ISSUE TITLE
iI suggest introducing absolute path access for S3 storage.

### ISSUE THREAD

**Issue by duckgun13476** [usememos/memos#3740]
The S3 protocol uses Vhost mode in this project to meet most storage needs. However, when using S3-compatible storage, there are many compatibility issues with Vhost mode. While it ensures the separation of bucket access and user security, establishing a usable Vhost storage bucket is relatively cumbersome for S3-compatible storage due to the need for resolution settings. On the other hand, absolute path access can solve this problem; it does not require setting up resolution records and has strong compatibility. It is also the access method used by most S3 storage solutions.
___
Suggested modifications for the author: 
  You just need to add a button to decide whether to use S3 storage path style, and change the way to access the bucket from bucket.IP:port to IP:port/bucket.

### Type of feature

API

### Additional context

Reference source, issue source #3655

**Comment by WyInnovate** [comment]
Seconded
Normally, the Amazon S3 SDK allows for the selection of Addressing
You can add an Addressing option in the S3 settings, which includes
1.Virtual-hosted-style
2.Path-style

**Comment by Gavincent1** [comment]
It seems that in version 0.21 and earlier versions, it is accessed in the way you suggested, but I don't know why the later update was cancelled. There is not even a compatibility option switch, which is a replacement update. I still use version 0.21 in my official environment.

**Comment by jinnatar** [comment]
This is still an issue and should be re-opened, but sadly the stale bot got to it first.

S3 path mode would open up compatibility to many more S3 compatible storage sources that choose not to implement host mode.

**Comment by jinnatar** [comment]
If you are using Amazon, yes. There are however a plethora of other providers and since path style is trivial to implement, vs the setup required to provide vhosts, some opt to not support vhosts. In my case Ceph does support them, but this is the first service where I finally need to go set it all up, which is far from trivial.
