### ISSUE TITLE
Hi, may I replace the emoji or add more to the list?

### ISSUE THREAD

**Issue by Brian099** [usememos/memos#3743]
### Describe the solution you'd like

Hi, may I replace the emoji or add more to the list? thanks.
![image](https://github.com/user-attachments/assets/ebb72158-f18a-4fad-b266-945c3d45fbb7)

### Type of feature

User Interface (UI)

**Comment by kangminsukdotcom** [comment]
I've been waiting for this feature as well!

**Comment by MehadND** [comment]
which ones do you wish to add?

**Comment by Brian099** [comment]
🏬🌐🛖🈶⬆⬆，
Hi, I need these above, but maybe someone like others, If I can replace or add them by myself, will be good, thanks.
is there a way to manage them, if I can use SSH to manage docker? thanks.
