### ISSUE TITLE
Can't edit memo's "edit date & time" in 0.22.3

### ISSUE THREAD

**Issue by Westwall98** [usememos/memos#3744]
### Describe the bug

In the previous version, date & time could be edited.

After the update "Support editing memos directly in the inline editor instead of a dialog."

Can't edit date&time in the editor any more.

### Steps to reproduce

Edit memos

### The version of Memos you're using.

0.22.3

**Comment by boojack** [comment]
Duplicated with https://github.com/usememos/memos/issues/3709
