### ISSUE TITLE
Disable spellcheck and autocapitalize on username/password fields

### ISSUE THREAD

**Issue by michaelborn** [usememos/memos#3747]
### Describe the solution you'd like

Every time I try to log in to Memos on my Android, I have to un-capitalize my keyboard to enter the first letter of my username. Since usernames are case-sensitive in Memos (a separate concern I will not discuss here), it's important to type in my username all in lowercase.

Disabling autocapitalize would resolve this issue, however, it seems like a good idea to disable spellcheck as well since many usernames and passwords will not be dictionary words.

### Type of feature

User Interface (UI)

### Additional context

The username field is currently rendered as:

```html
<input placeholder="Username" type="text" required="" class="MuiInput-input css-1u0jcuo" value="">
```

My suggested update would change it to:

```html
<input placeholder="Username" type="text" required="" class="MuiInput-input css-1u0jcuo" value="" autocorrect="off" autocapitalize="off" spellcheck="false" >
```

Note that despite the below article covering its usage, I think we should leave `autocomplete` enabled for password management tools.

https://davidwalsh.name/disable-autocorrect

**Comment by MykalMachon** [comment]
Hey all!
Have been using memos for awhile, thought I'd see how I could contribute back via OSS. 
I can give this issue a shot; will put in a PR when I've got it all wrapped up.
