### ISSUE TITLE
firefox 最新的拓展是哪个？从firefox商店安装的memos拓展，总是提示发送失败

### ISSUE THREAD

**Issue by gygy** [usememos/memos#3749]
### Describe the bug

firefox 最新的拓展是哪个？从firefox商店安装的memos拓展，总是提示发送失败

### Steps to reproduce

1、从firefox下载memos拓展，并安装
2、配置memos拓展，确保token和域名正确。
3、发送内容到memos，提示：发送失败。同样配置在chrome下面没问题。

### The version of Memos you're using.

0.22

**Comment by boojack** [comment]
Memos does not provide browser extensions yet.
