### ISSUE TITLE
新增的周日热力图再暗色模式下显示错误

### ISSUE THREAD

**Issue by i-iooi-i** [usememos/memos#3751]
### Describe the bug

![image](https://github.com/user-attachments/assets/61d7e5ed-1b4c-44eb-b6ce-9f122b68e6d9)
非常开心热力图功能又回归啦。 😊😊😊

在这里报个BUG，在暗色模式会显示为小方块。
起初以为Chome扩展或者什么导致的。结果开了访客模式试了一下，问题依然存在的。

![image](https://github.com/user-attachments/assets/3af2dc93-4404-4b69-8e79-36ef410cdf09)
在liang'se亮色模式下看上去是没有问题的。

### Steps to reproduce

启用暗色模式

### The version of Memos you're using.

0.22.4

**Comment by i-iooi-i** [comment]
![image](https://github.com/user-attachments/assets/f50e08eb-88b7-4cd4-8392-60c72824296d)

很奇怪，看官方的Demo在暗色模式下没有问题。

**Comment by i-iooi-i** [comment]
![image](https://github.com/user-attachments/assets/6f72b3a1-236c-44ae-af7a-557bf75f47a8)
不确定是因为什么问题触发导致的，比如6月份显示是错误的

![image](https://github.com/user-attachments/assets/0f563316-05aa-41ea-9d1f-59798013ca0c)
但是si'yue'fen四月份又是正确的。

**Comment by yuboabc** [comment]
你找一个 月的 最后一天有记录的 和下一个月第一天有记录的, 

现在可以自定义发表日期了嘛不是,  你可以改一下日期. 

只要满足我说的这个条件, 就会有背景色

**Comment by boojack** [comment]
Refer to https://github.com/usememos/memos/issues/3793
