### ISSUE TITLE
can we set Monday as the first day of a week in the calendar?

### ISSUE THREAD

**Issue by leyle** [usememos/memos#3752]
### Describe the solution you'd like

I'd like Monday as the first day of a week, can we add an option to set the first day of week?

### Type of feature

User Interface (UI)

### Additional context

![calendar](https://github.com/user-attachments/assets/5bfe0446-b98e-46df-8e9b-3f68c77a1dfb)

**Comment by noxonad** [comment]
As a temporary workaround, I think that CSS code I've provided in #3219 is still working.

**Comment by leyle** [comment]
> As a temporary workaround, I think that CSS code I've provided in #3219 is still working.

thank you, it works.
