### ISSUE TITLE
Show all children tags when selecting parent tag

### ISSUE THREAD

**Issue by Laflamme** [usememos/memos#3753]
### Describe the solution you'd like

First of all, thank you for this wonderful app! I started on my self hosting journey just a few months ago, and Memos has been one of the most impressive and most useful apps I discovered!

I am excited that Memos now supports displaying tags in a tree structure, but I must say it works differently from what I was expecting. 

When you select a parent tag (for example, #tag1), the interface only shows memos that have this specific tag. It doesn't show memos that **only** have one of its subtags (for example, #tag1/subtag1).

To get the expected behavior, I would currently have to add each level by itself (for example, #tag1 #tag1/subtag1 #tag1/subtag1/subsubtag1), which feels bloated. 

Instead, I would expect to be able to only add #tag1/subtag1/subsubtag1 and be able to see the associated memo no matter which level I select.

What do you think?

### Type of feature

User Experience (UX)

**Comment by okainov** [comment]
Sounds exactly like I would expect "subtags" to work! So fully support this idea!

>I am excited that Memos now supports displaying tags in a tree structure

But I'm not sure, where do you see it at all? I cannot find it...

**Comment by Laflamme** [comment]
Thanks! 

To the right of the Tags header, there is a vertical ellipsis ( ⋮ ) that you can click to reveal a popup with a Tree mode toggle.

**Comment by okainov** [comment]
Why is this closed @boojack ?
