### ISSUE TITLE
Canvas for drawing buildin

### ISSUE THREAD

**Issue by FabriicioMelo** [usememos/memos#3755]
### Describe the solution you'd like

It would be great if you added a canvas for drawing, like a mspaint, just to sketch things

### Type of feature

Other

**Comment by MehadND** [comment]
Nice idea but would you like to create and save them and possibly attach them to a memo or would it just be a a tool for a quick sketch or something. As a tool its no hassle to do it can be easily integrated but if you want a full feature where you can create canvase, edit them and attach them to a memo that will require allow of thought and time.
