### ISSUE TITLE
Stuck on Fetching data... when filter by tag

### ISSUE THREAD

**Issue by tiltshiftfocus** [usememos/memos#3756]
### Describe the bug

The app loads out fine. 
However when I click on a tag to filter, the main timeline does not load, stuck at "Fetching data ..."

### Steps to reproduce

1. With a blank slate, create one memo with `#tag1`, and another memo with `#tag2`.
2. Click on `#tag1` on the right side to filter by `#tag1` or `#tag2`.
3. Fetching data... stuck occurs on main timeline.

### The version of Memos you're using.

v0.22.4

### Screenshots or additional context

Without filter:
![Screenshot 2024-07-30 014412](https://github.com/user-attachments/assets/30838292-ec27-44d2-b155-12aa650636e4)

With filter:
![Screenshot 2024-07-30 014418](https://github.com/user-attachments/assets/5c7bfb03-82db-42c3-9586-5e5707c266e9)

Error message:
![Screenshot 2024-07-30 014337](https://github.com/user-attachments/assets/ad1ef835-d679-4c42-a932-2e03b5fa20a0)

**Comment by tigerzioo** [comment]
+1. I got the same error.

**Comment by tiltshiftfocus** [comment]
After going through the code, it's related to MySQL query where the string argument is invalid.
The code in question is at `store/db/mysql/memo.go` line 95 ``append(args, fmt.Sprintf(`%%"%s"%%`, tag))``

Removing the `%` symbols resolve the issue. 
Should I create a PR for this?

**Comment by tiltshiftfocus** [comment]
I have made a PR #3785

**Comment by tiltshiftfocus** [comment]
PR #3785 has been merged. Closing.
