### ISSUE TITLE
Time of a memo cannot be edited using Firefox (on Desktop)

### ISSUE THREAD

**Issue by epic0421** [usememos/memos#3757]
### Describe the bug

Starting from version 0.22, the way that editing the date and time of a memo has changed. Due to this, it is now more difficult to change the date and not possible to change the time of the memo on Firefox.

Changing the date and time does work in Chrome, but I would prefer to not need to use that in order to perform this task.

### Steps to reproduce

1. Using Firefox, attempt to change the date/time of the note. For me, it only seems to pull up the menu when I click around where the AM and PM indicator is.
2. Notice how there is only an option to change the date the note was taken on.

### The version of Memos you're using.

v0.22.4

**Comment by achenalia** [comment]
As far as I can tell, the second point is a limitation of Firefox. There's been a bug for some time (about three years it seems) where the visual datetime-local picker shows only date, and time must be entered manually. Without a text field to input time, changing the date with the picker is all that is possible at the moment.

**Comment by RoccoSmit** [comment]
I created a PR to fix the date not being able to be changed in Firefox https://github.com/usememos/memos/pull/3783
Changing the time is not possible in FF as mentioned before
