### ISSUE TITLE
Can't enable public signup

### ISSUE THREAD

**Issue by kangminsukdotcom** [usememos/memos#3759]
### Describe the bug

After uploading to the v0.22.3, I could no longer enable nor disable username+password signup on my admin page. I thought 0.22.4 would fix this bug but now "Don't have an account yet? Sign up" message is gone. Visitors can't sign up for my server.

### Steps to reproduce

1. Go to "Settings"
2. Allow/enable signup feature is gone.
3. Go to "Sign in"
4. "Sign up" is gone.

### The version of Memos you're using.

v0.22.4

**Comment by boojack** [comment]
> Added password-auth flag to control whether username and password login is enabled. https://github.com/usememos/memos/issues/3719

It's better to check the release note before upgrading.
