### ISSUE TITLE
Error when query by tag

### ISSUE THREAD

**Issue by wanjianghongfeng** [usememos/memos#3768]
### Describe the bug

when query by tag got this error:
```
ERROR server error method=/memos.api.v1.MemoService/ListMemos error="rpc error: code = Internal desc = failed to list memos: Error 3141 (22032): Invalid JSON text in argument 1 to function json_contains: \"Invalid value.\" at position 0."
```

```
POST https://note.litchinn.com/memos.api.v1.MemoService/ListMemos" 
"content-type: application/grpc-web+proto" 
```
![image](https://github.com/user-attachments/assets/122f7dff-c416-409b-baa3-9a90bb85b249)

### Steps to reproduce

i just change visibility to workspace then logout and change account

### The version of Memos you're using.

0.22.4

**Comment by tiltshiftfocus** [comment]
I have already opened this issue #3756
