### ISSUE TITLE
When S3 (MinIO) is specified for file storage, images are not displayed.

### ISSUE THREAD

**Issue by aqyuki** [usememos/memos#3786]
### Describe the bug

MinIO was set to be used for file storage. In this case, the uploaded file is not displayed correctly, although the file can be uploaded normally.

### Steps to reproduce

1. set the file storage used by memos to MinIO
2. post a memo with an image file attached
3. it is not displayed correctly.

### The version of Memos you're using.

v0.22.4

### Screenshots or additional context

![スクリーンショット 2024-08-06 184449](https://github.com/user-attachments/assets/6b691b8c-e029-497b-9cff-951fa80f39f1)
The image below is the image uploaded to local storage, and the image above is the image uploaded to MinIO

MinIO filepath template is `assets/{timestamp}_{filename}`

**Comment by cmoy168** [comment]
我也遇到了同样的问题

**Comment by luyufan498** [comment]
same problem...

**Comment by DHS1001** [comment]
same issue here...

**Comment by fengdu126** [comment]
same problem +1
