### ISSUE TITLE
Is it possible to enter "#" with an escape symbol?

### ISSUE THREAD

**Issue by SLi-Man** [usememos/memos#3787]
### Describe the bug

Is it possible to enter "#" with an escape symbol?

### Steps to reproduce

For example, I want to create a tag for "C#Note", but now I can't type "#" in the content properly.
I can't type to "#C#Note", It will be identified as two tags.

### The version of Memos you're using.

v0.20.1

**Comment by RoccoSmit** [comment]
This is similar to this gomark (the markup parser used in memos) issue https://github.com/usememos/gomark/issues/5
Possibility for the gomark PR to not look for the # to end the tag look forward and only stop looking once the end indicators `]]` is found
