### ISSUE TITLE
OICD logout URI for Keycloak

### ISSUE THREAD

**Issue by cromatyt** [usememos/memos#3788]
### Describe the solution you'd like

Is it possible to implement Open ID Connect logout URI ?

### Type of feature

Integrations

### Additional context

I've set up Keycloak for authentication with memos, and it works quite well.
If I authenticate with a Keycloak user and log out, I get to the memos authentication page without any problems.
However, if I want to authenticate with another keycloak user, the previous user's session is still active, and I log back in instantly.

**Comment by helmut72** [comment]
Why not planned? Nearly every webapp that support OIDC, support logout from IDP too
