### ISSUE TITLE
Invalid date when changing datetime in safari 

### ISSUE THREAD

**Issue by gitkeniwo** [usememos/memos#3790]
### Describe the bug

Safari's datetime-local picker does not include time selection, leading to invalid datetime return value.
Is it possible to separate date and time selection?

### Steps to reproduce

![image](https://github.com/user-attachments/assets/7e6e98f6-e1fe-4479-b5ae-94eb6691b521)

### The version of Memos you're using.

0.22.4

safari version 17.5

**Comment by RoccoSmit** [comment]
Memos uses a standard HTML input which is set set to show date time. How the date time is displayed depends on how your browser implements it, e.g. Edge and Chrome shows date and time, Firefox and Safari shows just date (See documentation https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local)

A quick solution to change dates and times would be to use a Chromium browser

**Comment by RoccoSmit** [comment]
Linking active date change issue 
https://github.com/usememos/memos/issues/3812
