### ISSUE TITLE
A bug with calendar display

### ISSUE THREAD

**Issue by yuukarii** [usememos/memos#3793]
### Describe the bug

I'm using Memos on Firefox. Memos was deployed through Docker. In light mode, the calendar is displayed beautifully. However, in dark mode, there is some strange squares that I thought it was a bug. You can see it in the attachments.

### Steps to reproduce

1. Access Memos via Firefox
2. Change between dark/light mode to see the differences.

### The version of Memos you're using.

v0.22.4

### Screenshots or additional context

![image](https://github.com/user-attachments/assets/08186571-a976-4006-981e-26dbe0881495)

![image](https://github.com/user-attachments/assets/5de3639e-f999-425d-b796-fcb183f99756)

**Comment by RoccoSmit** [comment]
This issue happens in Chrome as well.

To replicate you need to have memos on the dates from the previous month not shown in the calendar as well, in this case 28/07 - 31/07.

This triggers the teal background to get set

**Comment by RoccoSmit** [comment]
Related issue https://github.com/usememos/memos/issues/3751

**Comment by boojack** [comment]
Mighe be fixed with https://github.com/usememos/memos/commit/14194504ee7bd19d36d929f28f76136ad5294f71
