### ISSUE TITLE
Double-click to edit a Memo and save automatically when clicking elsewhere

### ISSUE THREAD

**Issue by Ivan-Malinovski** [usememos/memos#3796]
### Describe the solution you'd like

In Google Keep, you go into editing-mode when clicking on a note. That's a bit "much". I think double clicking to edit a note would be much more convenient than entering the menu upper-right menu, and then clicking on "edit", without it being intrusive to the general usage.

Additionally, having an option to automatically save a note when clicking outside would be good, too.

### Type of feature

User Experience (UX)

### Additional context

I'm currently packing for a trip, so I edit my packing list Memo many times in a short time span. Pressing two different buttons is a bit annoying in the long run, rather than just double clicking my note.

**Comment by RoccoSmit** [comment]
Try settings -> memos -> Enable double click to edit

**Comment by Ivan-Malinovski** [comment]
@RoccoSmit oh my god, I swear I had looked in settings, but I had just missed it. Thanks a lot!

I still think there should be an option for saving automatically when clicking elsewhere, though.
