### ISSUE TITLE
Feature request for content warnings

### ISSUE THREAD

**Issue by insertish** [usememos/memos#3799]
### Describe the solution you'd like

Ability to hide images / posts until interaction, and optionally with a message detailing why the image or post is hidden.

Example from Firefish (fediverse) software:
![CleanShot 2024-08-11 at 12 37 03@2x](https://github.com/user-attachments/assets/7c06ea04-03ee-4ba2-a7eb-21e7a155a7dd)
Clicking on "hide content" adds a new input field that lets you specify a content warning.

![CleanShot 2024-08-11 at 12 37 19@2x](https://github.com/user-attachments/assets/a94183d9-3e89-4a79-b615-eb135fba1196)
As a result, it is now hidden by default.

### Type of feature

User Experience (UX)

### Additional context

This would be nice to hide content that I don't necessarily want to see while scrolling through my memos.

This issue supersedes https://github.com/usememos/memos/issues/1508 which has been closed as stale automatically.

**Comment by boojack** [comment]
You can use the **spoiler** syntax to hide some text now.

```markdown
👀||Hide content!||
```

<img width="336" alt="image" src="https://github.com/user-attachments/assets/a64594e2-4ade-4bff-a0d6-1429fbd33364">
