### ISSUE TITLE
搜索功能bug

### ISSUE THREAD

**Issue by kylehz** [usememos/memos#380]
### Describe the bug

搜索关键字出来一堆请求，一直在fetching data，搜不出来东西
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/20038464/198874118-9655ed3c-7bd4-452a-9db3-be69bd8d7e48.png">

### Steps to reproduce

1.搜索关键字

### Expected behavior

立刻出来有关键字的结果，并支持分页展示

**Comment by Zeng1998** [comment]
我这边好像无法复现

**Comment by kylehz** [comment]
[memos_prod.db.zip](https://github.com/usememos/memos/files/9896200/memos_prod.db.zip)
3000条以上memos就会出现503错误，Request timeout

```
Request URL: http://localhost:5230/api/memo/stats
Request Method: GET
Status Code: 503 Service Unavailable
Remote Address: [::1]:5230
Referrer Policy: strict-origin-when-cross-origin
```

```
Request URL: http://localhost:5230/api/memo?rowStatus=NORMAL&limit=20
Request Method: GET
Status Code: 503 Service Unavailable
Remote Address: [::1]:5230
Referrer Policy: strict-origin-when-cross-origin
```

**Comment by Zeng1998** [comment]
> 搜索前20条内容包含的关键词时，无此现象。
> 当前20条内容不包含搜索的关键词时，就会以20条递增请求。

这似乎是一个符合预期的行为？

**Comment by kylehz** [comment]
> > 搜索前20条内容包含的关键词时，无此现象。
> > 当前20条内容不包含搜索的关键词时，就会以20条递增请求。
> 
> 这似乎是一个符合预期的行为？

不是，预期应该是请求一次就能出来相关结果，如果结果很多的话可以分页加载

**Comment by Zeng1998** [comment]
@boojack 

Maybe not a bug, but an enhancement with a higher priority?

**Comment by kylehz** [comment]
这个issue应该放在bug标签尽快修复 @Zeng1998

**Comment by kylehz** [comment]
这个问题有计划修复吗 @boojack @Zeng1998

**Comment by kylehz** [comment]
半年多过去了  还没修复这个bug吗😂

**Comment by athurg** [comment]
This issue has been fixed on #1730 and #1773
