### ISSUE TITLE
Cannot use minio as database, Failed to upload file

### ISSUE THREAD

**Issue by CJ-cooper6** [usememos/memos#3800]
### Describe the bug

Using minio as the database,specify the correct URL but "memos." is automatically added before the url.
<img width="1412" alt="image" src="https://github.com/user-attachments/assets/bd7667a8-7261-48d9-8773-faf0ef155032">

### Steps to reproduce

1. Use s3 storage
2. upload files

### The version of Memos you're using.

v0.22.4

**Comment by tcassaert** [comment]
Noticed the same thing today. The S3 client should support path-style URLs if we'd want to use MinIO.

**Comment by pipuwong** [comment]
我发现，minio的endpoin，只能填写ip+端口，不能填写https的域名，这很不方便。

**Comment by duckgun13476** [comment]
I don't know what to say. Minio must use vhost mode to connect to Memos, and configuring vhost mode is very troublesome. It requires bucket domain name resolution to the device and also needs Nginx to proxy traffic. Minio's own vhost must use a certificate that includes subdomains for access, which is too complicated and lacks the convenience of path style mode. I submitted a suggestion two weeks ago, proposing the addition of absolute path access, but they are not planning to implement such a simple feature; today they closed the issue citing no plans in this regard. If I knew Go, I might have written it myself, but unfortunately, I don’t. If there’s anything that can serve as an alternative, I hope you can recommend it to me.
#3740 😭😭😭😭😭😭😭😭

**Comment by WyInnovate** [comment]
@duckgun13476 其实不会go也能搞，就是在一个文件里加一行内容，然后自己编译镜像就行了，我之前发在issues里，然后有人试过了没问题

修改`plugin/storage/s3/s3.go`的内容
```
client := s3.NewFromConfig(cfg, func(o *s3.Options) {
o.BaseEndpoint = aws.String(s3Config. Endpoint)
o.UsePathStyle=true //Setting to true means using Path Style
})
```

**Comment by WyInnovate** [comment]
@pipuwong 我们都是用的域名去访问的，就是目前memos不支持path-style的minio，以前是支持的，哎

**Comment by buyiyihu** [comment]
FYI:
Minio support both vhost and path style, memos is ok, you simply should activate vhost support of minio by setting the MINIO_DOMAIN environment:
```
export MINIO_DOMAIN=mydomain.com
minio server /data
```
https://min.io/docs/minio/linux/administration/object-management.html#minio-object-management-path-virtual-access

**Comment by WyInnovate** [comment]
> FYI: Minio support both vhost and path style, memos is ok, you simply should activate vhost support of minio by setting the MINIO_DOMAIN environment:
> 
> ```
> export MINIO_DOMAIN=mydomain.com
> minio server /data
> ```
> 
> https://min.io/docs/minio/linux/administration/object-management.html#minio-object-management-path-virtual-access

So why not default to path style or choose which mode to use
@buyiyihu

**Comment by buyiyihu** [comment]
No idea, you may ask the maintainer

**Comment by WyInnovate** [comment]
> No idea, you may ask the maintainer不知道，你可以问维修人员

Sorry, I wasn't targeting you earlier. Sorry

**Comment by wpengsen** [comment]
你们看看这篇文章能给你们提供帮助吗[memos从0.21更新到0.22后minio对象存储问题](https://bangkaixin.com/archives/1732590254015)

**Comment by WyInnovate** [comment]
> 你们看看这篇文章能给你们提供帮助吗[memos从0.21更新到0.22后minio对象存储问题](https://bangkaixin.com/archives/1732590254015)

在另外一个issues下边回复你了
