### ISSUE TITLE
automatic backup database

### ISSUE THREAD

**Issue by Forever-fall** [usememos/memos#3802]
### Describe the bug

I recently updated to version 0.22.4 and found that the automatic backup function is gone. I remember that in previous versions, I could set automatic backup and a database backup would be generated under /root/.memos/. Has this function been removed or is there a bug? Can I only write crontab manually?

### Steps to reproduce

1.settings

### The version of Memos you're using.

v0.22.4

**Comment by okainov** [comment]
I'd consider backup function as very important, so definitely need this!

**Comment by RoccoSmit** [comment]
It looks like his feature was removed as part of v18.2
https://github.com/usememos/memos/commit/e0cacfc6d6fe3fd612fce66a9c005f9a0e6dfde3

**Comment by boojack** [comment]
There are a lot of great tools out there for database and file backups. So we will not touch any backup related feature in the feature due to limited resources.
