### ISSUE TITLE
App redirects to /home route, which 404s

### ISSUE THREAD

**Issue by murrayju** [usememos/memos#3804]
### Describe the bug

If I leave the webapp open for some time and return to it later, I usually find it sitting on a 404 page at the `/home` route (which does not exist). It seems that something must redirect here after some timeout?

Reproduced in Firefox on mac, and Safari on iOS.

### Steps to reproduce

1. Open memos in a tab at the root route (home page)
2. Leave this tab open in the background for some time (I don't know the minimum, but a day should definitely work)
3. Return to the tab, find it on a 404 page

### The version of Memos you're using.

v0.22.4

**Comment by RoccoSmit** [comment]
@murrayju, I tried to replicate but couldnt.

Shot in the dark, memo < v0.22.4 use to have a lastVisited local storage variable stored. This value would be /home or /timeline
Can you see if you still have it in your browser local storage, if so, clear it out and see if your redirect still happens

**Comment by murrayju** [comment]
Appears to be fixed, thanks!
