### ISSUE TITLE
Mood tracking

### ISSUE THREAD

**Issue by okainov** [usememos/memos#3805]
### Describe the solution you'd like

Inspired by https://github.com/mudkipme/MoeMemos/issues/43, it would be great if one could use Memos for mood tracking. 

Quote and image from the linked issue:

> Wouldn't be nice to be able to attach a mood score when creating a note, so that over time we could see how note content in linked to level of mood ?
> 
> Mood could be rated on a scale of 5 :

![image](https://github.com/user-attachments/assets/9591a434-0a84-45f6-8e8a-379449210b2f)

> This could also be attached to a mood score and displayed in stats (as a new color code in existing calendar, or offer the ability to switch between nb of memos & mood score for the day in settings, or possibility to activate another mood calender below the existing one in settings ??) ?

Technically I think it might be the simplest to implement via some special tags for notes, like `#moodHappy`, `#moodSad` and the calendar view can use those to add different colors to the days... But I haven't checked existing architecture, so not sure whether it will fit.

### Type of feature

User Interface (UI)

### Additional context

Yet another point of inspiration is a system "Most important event of the Day/Week/Month` ([link](https://habr.com/ru/articles/364381/)), although it would be probably more difficult to implement due to non-linear structure...

**Comment by okainov** [comment]
Why was it closed as not planned? There were some upvotes and no response from maintainer. @boojack ?

**Comment by onee-only** [comment]
https://github.com/usememos/memos/blob/09586d032c7167f85714d04fa46da1ad91561d55/.github/workflows/stale.yml#L13-L17

Stale period seems too short IMO.
