### ISSUE TITLE
comments error

### ISSUE THREAD

**Issue by Kellermaan** [usememos/memos#3806]
### Describe the bug

when I click comments, it shows errors.

### Steps to reproduce

1. go to any posts.
2. click comments.
3. error shows.

### The version of Memos you're using.

Version: v0.22.4

### Screenshots or additional context

![image](https://github.com/user-attachments/assets/f58efd92-8e17-4f14-818a-4d6822df793b)

**Comment by studioj2y** [comment]
I noticed this too, you could try a quick workaround by clicking "edit" button of each post then add a blank space at the end of the post then save it. 
This could be done pretty quicky when you get used to it. If you don't have too many posts this is the fix.

**Comment by Kellermaan** [comment]
> I noticed this too, you could try a quick workaround by clicking "edit" button of each post then add a blank space at the end of the post then save it. This could be done pretty quicky when you get used to it. If you don't have too many posts this is the fix.

thanks. sure, maybe it's a fix. but actually, I didn't need this feature for now. I just think it's a bug, maybe someone need it in the future.

**Comment by studioj2y** [comment]
Yep, for references, #3767 seems mentioned this issue too.
https://github.com/usememos/memos/issues/3767#issuecomment-2278955948
This SQL updates all the records with no errors, but the author said there could be some data loss. Hope there would be a complete solution soon

**Comment by boojack** [comment]
Might be fixed with https://github.com/usememos/memos/commit/aae3e8ae646cb76725bf9c3c1a862aff2f944505
