### ISSUE TITLE
Post Excerpt for long posts

### ISSUE THREAD

**Issue by 725525** [usememos/memos#3816]
### Describe the solution you'd like

Currently home page shows full post content for all posts. Even for the long ones. It would be really cool to have "post excerpt" for large articles with "Read More..." instead of showing the full post in homepage.

### Type of feature

User Interface (UI)

**Comment by boojack** [comment]
@725525 There should be a setting to enable auto compact, which will collapse the large ones.

<img width="1044" alt="image" src="https://github.com/user-attachments/assets/28dc91a2-bc58-4362-b67c-0563dbfb3329">
