### ISSUE TITLE
tag filter proble

### ISSUE THREAD

**Issue by joewen85** [usememos/memos#3818]
### Describe the bug

use mysql scheme deployment memos
mysql version 8.0.39

click tag filter always loading
<img width="1049" alt="image" src="https://github.com/user-attachments/assets/9ac20cce-cf31-4ac7-88ad-14cf92796184">

use sqlite scheme  is work
<img width="1070" alt="image" src="https://github.com/user-attachments/assets/204acdb6-2925-4b5f-855c-08860aafd611">

### Steps to reproduce

add tag tt

click #
select #tt
use #tt filter

### The version of Memos you're using.

0.22.4  stable

**Comment by roccox** [comment]
same  problem starts from 0.22.3

**Comment by roccox** [comment]
terminate info:
memos  | 2024/08/19 15:36:55 ERROR server error method=/memos.api.v1.MemoService/ListMemos error="rpc error: code = Internal desc = failed to list memos: Error 3141 (22032): Invalid JSON text in argument 1 to function json_contains: \"Invalid value.\" at position 0."

**Comment by onee-only** [comment]
It should be fixed by #3785, which was released in version 22.5.
