### ISSUE TITLE
Notes and edit window stuck on small sizes

### ISSUE THREAD

**Issue by mynamewastaken** [usememos/memos#3824]
### Describe the bug

Both the notes and edit notes windows are quite small at my resolution (3840x2160) on Linux Firefox and don't seem to grow past a certain point when resizing the window.

### Steps to reproduce

Open a notes install with a high resolution and see that the note window appears to float in the middle taking up maybe 30-40% of the width, with the edit note popup being smaller than that.

### The version of Memos you're using.

app: 0.19.0, helm chart: 0.35.0

**Comment by mynamewastaken** [comment]
I see now that the version I'm running is a bit older; I willl try updating to the latest available and see if that helps. If so I will close the issue.

**Comment by mynamewastaken** [comment]
Somewhat improved with 0.22.4 as the edit window is now the same size as the original note - but it would be nice to be able to expand the whole thing. Or if you have pointers for a CSS hack or something that's fine too.

**Comment by RoccoSmit** [comment]
Try setting the custom css (`settings` -> `system` -> `additional style`)

```
section.w-full.max-w-5xl.min-h-full.flex.flex-col.justify-start.items-center.pb-8 {
    max-width: 100%;
}
```

You can set the percentage as per your need.
Note: this will change the width of the center column on all pages

**Comment by mynamewastaken** [comment]
This worked great - thank you!
