### ISSUE TITLE
In the Iphone can't show Calendar, please recover  Timeline page.

### ISSUE THREAD

**Issue by fattyhk** [usememos/memos#3828]
### Describe the bug

In the Iphone can't show Calendar, from Timeline page can quick positioning the memos. please recover  Timeline page.

### Steps to reproduce

1.iphone edge open memos
2.can't find the Calendar

### The version of Memos you're using.

0.22.4  

### Screenshots or additional context

![无法显示日历](https://github.com/user-attachments/assets/fdb66d68-4f46-4d61-b91f-4d6c5a752a9f)

**Comment by RoccoSmit** [comment]
@fattyhk , can you please reattach the screenshot

**Comment by fattyhk** [comment]
@RoccoSmit has reattached

**Comment by Lifulifu** [comment]
Can you open the right sidebar? the calendar should be there. (press the search icon on the top right corner)

**Comment by fattyhk** [comment]
Thanks~ it's working.
