### ISSUE TITLE
In the Iphone can't show Calendar, please recover  Timeline page.

### ISSUE THREAD

**Issue by fattyhk** [usememos/memos#3829]
### Describe the bug

In the Iphone can't show Calendar, from Timeline page can quick positioning the memos. please recover  Timeline page.

### Steps to reproduce

1.iphone edge open memos
2.can't find the Calendar

### The version of Memos you're using.

0.22.4  

### Screenshots or additional context

![Uploading 无法显示日历.jpg…]()

**Comment by RoccoSmit** [comment]
Duplicate of https://github.com/usememos/memos/issues/3828

**Comment by RoccoSmit** [comment]
@fattyhk , can you please reattach the screenshot
