### ISSUE TITLE
使用“捷径”选取文章时仍然会出现“点击加载更多”

### ISSUE THREAD

**Issue by pharaohnie** [usememos/memos#383]
### Describe the bug

我的一个快捷会包含很多文章，开始的时候滚屏到下放时会自动“请求数据”，但滚屏第4次之后，就不再自动请求数据了，而是显示“点击加载更多”
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/880867/198910182-72033632-e14f-49d1-9687-f3df79b0e3c6.png">

### Steps to reproduce

1. 选择一个捷径
2. 向下滚动屏幕
3. 第5次时不再自动请求数据，而是显示“点击加载更多”

### Expected behavior

不论是搜索还是通过捷径进行查询，都自动的筛选出对应的结果。

**Comment by Zeng1998** [comment]
> 滚屏到下放时会自动“请求数据”

我印象中似乎并没有这个功能？
