### ISSUE TITLE
Spaces or Categories

### ISSUE THREAD

**Issue by kumraa-1** [usememos/memos#3830]
### Describe the solution you'd like

I really love Memos and I use it as my all in one note taking solution. I recently thought about starting to journal.
Memos is perfect for that but I wouldnt want my journaling notes to show up in my regular notes.
Yes tags are a thing but I'd have to select all tags, except for the journaling one to create that behaviour.
My current workaround is to use another account for journaling, which is a bit annoying especially with SSO.

So my idea is to add optional spaces or let's say categories that you can create your notes at. I would keep those spaces from interacting with each other, in terms of tags.

I hope you get what I mean.

Thank you.

### Type of feature

User Experience (UX)

**Comment by RoccoSmit** [comment]
Would spinning up another memo docker container exposed via a different port number work for this?

e.g. 
Memo container 1 is set up to run on localhost:`5230` and is used for all your note taking
memo container 2 is set up to run on localhost:`5231` and is used for all your journaling

You can use the same SSO for both instances
