### ISSUE TITLE
用户删除后探索存在持续刷新的问题

### ISSUE THREAD

**Issue by suppercarl** [usememos/memos#3834]
### Describe the bug

我添加有多个账户使用“探索”这个功能，当我删除其中一个账号时，“探索”会出现持续刷新的问题，并且尝试重装docker映像时，依旧无法解决这个问题

### Steps to reproduce

1.使用一个账号发布“探索”相关内容，就是发布非私有的内容
2.删除这个账号，使用其他账号查看“探索”时，会处于一直刷新的状态

### The version of Memos you're using.

v0.22.3 我尝试更新docker版本，但还是22.3

### Screenshots or additional context

![image](https://github.com/user-attachments/assets/bade5b95-beb3-4dea-a2f4-208a1f29ff44)

**Comment by boojack** [comment]
It should be fixed in `v0.22.4`.
