### ISSUE TITLE
找不到分享按钮了

### ISSUE THREAD

**Issue by m1732948116** [usememos/memos#3837]
### Describe the bug

之前是有个分享按钮挺好用的，可以选择分享链接或者转换成图片
新款找不到了，点进详情页也没有，这算是bug吗？
![微信截图_20240826130125](https://github.com/user-attachments/assets/a2f9c2f8-7c91-418f-a2d3-179c1426af98)

### Steps to reproduce

点击memo右上角的菜单按钮

### The version of Memos you're using.

0.22.4

**Comment by RoccoSmit** [comment]
The picture part of the share functionality was removed in `v0.22`. You can still copy a link for sharing

**Comment by m1732948116** [comment]
> The picture part of the share functionality was removed in `v0.22.0`. You can still copy a link for sharing

可惜了，挺方便的功能，最好可以给分享链接加上可访问期限，就像alist那样，这样就不需要把memo设为公开了
