### ISSUE TITLE
Search by tag does not work with MySQL

### ISSUE THREAD

**Issue by joshefin** [usememos/memos#3841]
### Describe the bug

The `json_contains` function should be used in the following way:

```
select json_contains('["tag1","tag2","tag3"]', '["tag1"]');
select json_contains('["tag1","tag2","tag3"]', '["tag1","tag3"]');
```

### Steps to reproduce

Select any tag in the UI to filter the memos. No results are shown.

### The version of Memos you're using.

v0.22.4

**Comment by boojack** [comment]
Duplicated with https://github.com/usememos/memos/issues/3756
