### ISSUE TITLE
首页备忘录显示头像！

### ISSUE THREAD

**Issue by yihanglee-cn** [usememos/memos#3842]
### Describe the solution you'd like

首页备忘录显示与详情页一致的头像。
![PixPin_2024-08-28_14-17-42](https://github.com/user-attachments/assets/90419496-c6bd-4eb9-a30f-2b1137085c28)

### Type of feature

User Interface (UI)

**Comment by boojack** [comment]
User avatars will only be displayed on public pages like Explore; they don't need to be shown on personal profile pages.
