### ISSUE TITLE
allow editing other users

### ISSUE THREAD

**Issue by KUKARAF** [usememos/memos#3846]
### Describe the solution you'd like

I'd love to allow other users to edit specific notes. Ideally not the same way visibility works but instead hand picking users by name to get access to specific notes. 

### Type of feature

User Experience (UX)

**Comment by RoccoSmit** [comment]
Duplicate of https://github.com/usememos/memos/issues/3782

**Comment by KUKARAF** [comment]
Yea no. That is exactly what i was talking about. 
Sorry for doing a bad job checking for already existing issues.
