### ISSUE TITLE
Markdow引用图片时网页端不显示图片

### ISSUE THREAD

**Issue by Lishuhao-lucky** [usememos/memos#3848]
### Describe the bug

当使用markdown语法引入图片时网页端无法正常显示图片，只是显示对应文字
![图片](https://github.com/user-attachments/assets/960c5a96-9d5b-4ffb-a98d-3d0990166d2f)
安卓客户端倒是正常显示图片
![图片](https://github.com/user-attachments/assets/c2d3da71-5601-41a8-9da2-ddc8674dd3cc)
不知道这是正常的吗？如果是直接上传图片无论网页还是客户端都正常显示
测试环境：firefox浏览器；服务端V0.22.4；

### Steps to reproduce

1输入图片引用测试
`![图片alt](https://images.lishihao.top/thumbnails/9353741f8c8755bd722320bcd3c9e732.png "图片title")`
2保存
3查看

### The version of Memos you're using.

v0.22.4

**Comment by RoccoSmit** [comment]
Try removing `"图片title"`
The docs show the value inside `()` to only be a URL

**Comment by Lishuhao-lucky** [comment]
> Try removing `"图片title"` The docs show the value inside `()` to only be a URL (https://www.usememos.com/docs/getting-started/content-syntax#images)

yes， it works. thank you!!!
