### ISSUE TITLE
视频资源添加太多了，页面一进去就自动下载，能不能不默认自动下载。

### ISSUE THREAD

**Issue by shenshanlaomanong** [usememos/memos#3853]
### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/b34ff2d1-a058-4985-b4e8-1d031d54811e)

### Type of feature

User Interface (UI)

**Comment by 18723472350** [comment]
![image](https://github.com/user-attachments/assets/9ba99d26-6bde-446b-98ca-9d9235a15b48)
后端内存啥时候释放，就视频下载的操作

**Comment by ZJ1998888** [comment]
你这是把笔记做成NAS在使用。
