### ISSUE TITLE
Issue with Tags

### ISSUE THREAD

**Issue by chillingchakra** [usememos/memos#3868]
### Describe the bug

Hello, first off great product, love it.

There is an issue I discovered while creating new tags. I wanted to create a new tag for qr code tools and commands so I tried hashtag qr and it auto suggested hashtag tar which I had previously created for manipulation of tar files, in order to successfully create the hashtag qr I had to put a space in the back of the word qr and make it qr_space_ to proceed so now it is remembered in my hash cloud as qr_space. I'm not really sure why it thought tar was a good suggestion as there is no q in it, but there is an r. But more importantly, I think, is it the problem of not being able to create a new hashtag without appending a space character to it.

Anyway, it's no big deal, I added the space, just thought you should know. Cool product, will donate when I have dinero.

### Steps to reproduce

create new hashtag.
observe results if letter used is used in already created hashtags.

### The version of Memos you're using.

0.22.4

**Comment by Lifulifu** [comment]
You can try pressing <esc> to cancel auto suggestion to proceed typing.

**Comment by RoccoSmit** [comment]
_now it is remembered in my hash cloud as qr_space_
Are you trying to do something like `#tag1#tag2#tag3` and you are finding it need to be `#tag1 #tag2 #tag3`?

**Comment by RoccoSmit** [comment]
FYI, the reason `tar` shows up for `qr` is because a fuzzy search is used when searching tags. (library used https://www.fusejs.io/)
I imagine this is done to make it easier to find tags in a big list of tags and help with scenarios where spelling is a bit different from the first time you created the tag or e.g. US spelling vs UK spelling (color vs colour)

**Comment by chillingchakra** [comment]
@Lifulifu ahhh cool, thank you, I did not know that. I appreciate the quick response @RoccoSmit excellent resource, makes sense.
