### ISSUE TITLE
Unknown green boxes in calendar

### ISSUE THREAD

**Issue by onee-only** [usememos/memos#3875]
### Describe the bug

There are green boxes after the last day of month. I'm not sure if this is intended, but I'm reporting this issue because it doesn't occur in light mode.

### Steps to reproduce

1. (Probably) write a memo on every day of last week of August 2024.
2. Make sure you use the dark mode.
3. Now look at the calendar of September 2024.

### The version of Memos you're using.

v0.22.4

### Screenshots or additional context

https://github.com/user-attachments/assets/605a8b63-a1a8-481d-b637-84500bec8540

**Comment by RoccoSmit** [comment]
Are you still finding this issue with v22.5
Here is the a related ticket with a potential fix applied to v22.4 
https://github.com/usememos/memos/issues/3793

**Comment by onee-only** [comment]
@RoccoSmit Thanks for pointing it out. I didn't know there was a release lately. I'll close this issue then. 🙇

**Comment by RoccoSmit** [comment]
Did a quick test
v22.4
![image](https://github.com/user-attachments/assets/10b1018c-a61b-4654-b119-3ea7fa52424a)

v22.5
![image](https://github.com/user-attachments/assets/2042be06-f496-4738-b7cd-83b7161f032d)
