### ISSUE TITLE
BUG ? no more bash or sh in the container

### ISSUE THREAD

**Issue by stanthewizzard** [usememos/memos#3877]
### Describe the bug

unable to bash or sh into the container

### Steps to reproduce

docker exec -it memos /bin/bash
or
docker exec -it memos /bin/sh

returns

OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown

### The version of Memos you're using.

Version: v0.22.5

**Comment by RoccoSmit** [comment]
Could have something to do with this commit
https://github.com/usememos/memos/commit/0156c7e11ff63bd8f49cb683e4c755ff7f77cabc

**Comment by urzz** [comment]
> Could have something to do with this commit [0156c7e](https://github.com/usememos/memos/commit/0156c7e11ff63bd8f49cb683e4c755ff7f77cabc)

> Distroless images are minimal and lack shell access.  -> [GoogleContainerTools/distroless](https://github.com/GoogleContainerTools/distroless?tab=readme-ov-file#debug-images)

So `gcr.io/distroless/static-debian12:latest` can't use shell environment command to do healthcheck.

Can we consider adding a healthcheck command? So that we can avoid use shell for healthcheck.

**Comment by stanthewizzard** [comment]
i'll roll back to the previous version (issue again with api and tiers apps. API are a mess in this project btw)

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/pull/3942
