### ISSUE TITLE
Translation of the weekdays in the calendar is always English

### ISSUE THREAD

**Issue by alehmann76** [usememos/memos#3879]
### Describe the bug

The calendar is showing always the english abbreviation for the weekdays.
e.g. Mo , Tu ,We  but i would expect in german Mo, Di, Mi

The same happens when i change the laguage to french or italian (sorry these are the only languages i know the weekdays :-) )

The month is correctly translated.
![image](https://github.com/user-attachments/assets/fc185239-9f46-4780-a3b4-5b4d99655a25)

### Steps to reproduce

1. go to setting -> preferences and change the language to german
2. go back to the start page
3. translation of the calender is not complete (only the month is correct)

### The version of Memos you're using.

v0.22.5

**Comment by RoccoSmit** [comment]
PR (https://github.com/usememos/memos/pull/3895)
