### ISSUE TITLE
Public Register Control Doesn't Work

### ISSUE THREAD

**Issue by InkNight-DedNET** [usememos/memos#3884]
### Describe the bug

`public` Flag Missed In 0.22.5
Is This A Feature Or A Bug?

### Steps to reproduce

Deploy The Container With Image `neosmemo/memos:latest` `neosmemo/memos:stable` `neosmemo/memos:0.22.5`
Run Container With -e MEMOS_PUBLIC:false

### The version of Memos you're using.

0.22.5

**Comment by boojack** [comment]
You can configure this on the UI.

<img width="1008" alt="image" src="https://github.com/user-attachments/assets/fc1c3035-ab22-4c6c-8344-2e24c91ce9a0">
