### ISSUE TITLE
/u/user note with an image is wrongly resized in 0.22.5 box

### ISSUE THREAD

**Issue by mariushosting** [usememos/memos#3887]
### Describe the bug

when someone visit someone /u/user profile page the notes with an image is very well fit in the box on version 0.22.4 but on version 0.22.5 the notes with an image is not well fit anymore in the box.

### Steps to reproduce

visit someone profile /u/user on version 0.22.4
then visit someone profile /u/user on version 0.22.5
You will notice if the user have an image in the note this one is not fit anymore in the box.

### The version of Memos you're using.

0.22.5

**Comment by mariushosting** [comment]
![Screenshot 2024-09-06 07 24 28](https://github.com/user-attachments/assets/b678d35e-12b2-41a3-a0d6-725a9c9712dd)
![Screenshot 2024-09-06 07 24 53](https://github.com/user-attachments/assets/bee15b99-3df7-4815-8a95-126a4d3d6697)

**Comment by RoccoSmit** [comment]
From version 22.5 a thumbnail version of the image is displayed in the feed. This thumbnail should be 700px wide if the image is more than 700px wide. The feed should also be just over 700px wide so the thumbnail will fit exactly. 

can you confirm the image width of your version 22.5 displayed image as well as the feed width

**Comment by mariushosting** [comment]
> From version 22.5 a thumbnail version of the image is displayed in the feed. This thumbnail should be 700px wide if the image is more than 700px wide. The feed should also be just over 700px wide so the thumbnail will fit exactly.
> 
> can you confirm the image width of your version 22.5 displayed image as well as the feed width

https://blog.mariushosting.com/u/mariushosting

Version 22.4 fit perfect. But 22.5 no.

**Comment by RoccoSmit** [comment]
Did you revert back to 22.4? Can't replicate the issue

**Comment by mariushosting** [comment]
> Did you revert back to 22.4? Can't replicate the issue when following your link

Yes I reverted to 22.4

I have update now with 22.5 please check.

**Comment by RoccoSmit** [comment]
Are you setting a custom feed column width in your settings?

**Comment by mariushosting** [comment]
> Are you setting a custom feed column width in your settings? In the additional css

Absolutely no.

**Comment by RoccoSmit** [comment]
Interesting, ok. Something is changing your ui because you don't have the search or tags menus and you have a share feature instead. Can you share some context around this?

**Comment by mariushosting** [comment]
> Interesting, ok. Something is changing your ui because you don't have the search or tags menus and you have a share feature instead. Can you share some context around this?

I think you are confusing two different pages.
One is this with the tags: https://blog.mariushosting.com/explore
The other is this "user" https://blog.mariushosting.com/u/mariushosting

**Comment by RoccoSmit** [comment]
You are right. I was unaware of the user specific page

**Comment by mariushosting** [comment]
> You are right. I was unaware of the user specific page

I will reverse back to 22.4 since the 22.5 break image fit in the user page.

**Comment by boojack** [comment]
@RoccoSmit Please check out for https://github.com/usememos/memos/commit/4790e84b984a5076a19b01a5c0ef6c503ef7c103. It's better to use ratio instead of max width.
