### ISSUE TITLE
关于无法注册登陆以及无损升级的问题

### ISSUE THREAD

**Issue by toyqiu** [usememos/memos#389]
0.4.2用了个把月，逛了逛dockerhub看到有更新，用 watchtower 更新
`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --cleanup --run-once memos`

启动玩全清空了。为啥？就没有能无痛无损升级的办法吗？docker rm docker pull 那一套肯定是没有 watchtower 来的无损呀，我用好多年了没出过问题呢。。。

然后，0.4.2版本第一次登陆可以 sign up ，为啥 0.7.0 不能 sign up 呀？那默认账号密码是啥 ？还要强制性用邮箱做账户 ？

**Comment by 17huiwei** [comment]
用watchtower好像没起作用，不知道为啥

**Comment by 121592512** [comment]
现在还可以用这个升级了吗
