### ISSUE TITLE
--password-auth flag is missing in 0.22.5

### ISSUE THREAD

**Issue by Jayspek** [usememos/memos#3890]
### Describe the bug

The --password-auth flag added in 0.22.4 is missing in 0.22.5.

### Steps to reproduce

Run the 0.22.5 binary with the --password-auth flag. It throws an unknow flag error, and also does not show the flag in the list of available options.

### The version of Memos you're using.

0.22.5

**Comment by RoccoSmit** [comment]
i believe this is now set via the UI 
See this issue for more info https://github.com/usememos/memos/issues/3884

**Comment by Jayspek** [comment]
Oh, I see! Weird, since in 0.22.2 (I think) it was in the UI, in 0.22.3 it was gone, in 0.22.4 it was the flag and now its back in the ui.
