### ISSUE TITLE
grpc:received message larger than

### ISSUE THREAD

**Issue by Mask-Vip** [usememos/memos#3893]
### Describe the bug

grpc: received message larger than max (185093557 vs. 104857600)

### Steps to reproduce

1. Set the maximum upload size to 1024m.
2. Upload attachments over 100m
3. Error report:
GRPC: received message larger than max (185093557 vs. 104857600)

### The version of Memos you're using.

0.22.5

### Screenshots or additional context

![screenshot-1725729626494](https://github.com/user-attachments/assets/67cc67b8-b3a8-48f3-881f-bdd2a391a5b6)
![screenshot-1725729626494](https://github.com/user-attachments/assets/7540e0ff-e612-4c6b-8965-c49ab0c5ffc1)

**Comment by RoccoSmit** [comment]
Are you referring to the content length limit being set above?
![image](https://github.com/user-attachments/assets/9a2f0163-4fb7-47ce-9a8b-702a587f1910)
From what I understand this setting is related to how much text can be added to a memo

The amount of data that can be sent over the network is hardcoded to 100mb and does not have a setting to change it
https://github.com/usememos/memos/blob/044d46c36d5c36608cfb8c9ad3d81d9f416532d0/server/router/api/v1/v1.go#L68

**Comment by Mask-Vip** [comment]
> 您指的是上面设置的内容长度限制吗？ ![图像](https://private-user-images.githubusercontent.com/5203347/365408838-9a2f0163-4fb7-47ce-9a8b-702a587f1910.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MjYxNzksIm5iZiI6MTcyNTgyNTg3OSwicGF0aCI6Ii81MjAzMzQ3LzM2NTQwODgzOC05YTJmMDE2My00ZmI3LTQ3Y2UtOWE4Yi03MDJhNTg3ZjE5MTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDhUMjAwNDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGQxOWU2YjZhNDg3MWEwMjRkM2QxNGQxNWY4Y2Q4MzI4Yzg4ZDIwNzc4NmQzMTQzNzRlZjRiMjQyZDA4NWY2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KqyiCYixazMXsR674yhBX-R_yplesmvvIVA0hUaeJlA)据我了解，此设置与可以添加到备忘录中的文本数量有关
> 
> 每个请求可发送的数据量被硬编码为 100mb，并且没有用于更改它的设置。注意：上传的图像是链接到 memo 的资源，因此会通过单独的网络请求发送
> 
> https://github.com/usememos/memos/blob/044d46c36d5c36608cfb8c9ad3d81d9f416532d0/server/router/api/v1/v1.go#L68

Thank you for answering my doubts. The maximum upload size I said is in Settings > > Storage Settings > > Maximum Upload Size, and the recommended size is 32mib. (At least in the Chinese version, it means to control the upload size)
![screenshot-1725826274082](https://github.com/user-attachments/assets/611ab71d-015a-4a44-b404-2b53a4ac546f)
![screenshot-1725826274082](https://github.com/user-attachments/assets/099298ab-b963-41db-923b-20976f12c00a)

**Comment by RoccoSmit** [comment]
I believe this will still run into the same issue. The value set in the settings screen (2048mb) is used as input validation once the data gets to the server, the grpc limit (100mb) determines how much data you can send to the server so the request gets blocked before the input validation can run.

Not sure why the 2 values arent linked. Someone with more context will need to answer.

**Comment by RoccoSmit** [comment]
@boojack, thoughts on upping this value to a larger number, based on this issue > 2GB and adding it to the storage settings UI tooltip for `workspaceStorageSetting.UploadSizeLimitMb` so users know there is an upper limit to what you can set. Not sure if there was a reason 100mb as set as the limit
https://github.com/usememos/memos/blob/d5d37c1d593f6a279761e09f8330fdfdd0debba6/server/server.go#L77-L78

At first I was thinking we could user the `workspaceStorageSetting.UploadSizeLimitMb` in the server file but the realized a server restart would be needed for it to take effect

**Comment by boojack** [comment]
@RoccoSmit SGTM, updated with https://github.com/usememos/memos/commit/2b86069f3b37634da61fb591bd36ce0fb0bd64ff
