### ISSUE TITLE
Changing the name of the server do not change the name on the main page, shown to unregistered persons.

### ISSUE THREAD

**Issue by lopar** [usememos/memos#3904]
### Describe the bug

Changing the name of the server do not change the name on the main page, shown to unregistered persons.

### Steps to reproduce

1. Edit server name.
2. logout

### The version of Memos you're using.

v0.22.5

### Screenshots or additional context

Not working on main page.
![image](https://github.com/user-attachments/assets/421db4fa-b00b-4e88-8ed6-57abeedfb4b8)

But everything ok on `auth` page.
![image](https://github.com/user-attachments/assets/e0802422-2f00-4ad9-85f4-5076bd3c3190)

**Comment by RoccoSmit** [comment]
pr https://github.com/usememos/memos/pull/3908
