### ISSUE TITLE
关于改变储存路径，改动无反应

### ISSUE THREAD

**Issue by asasn** [usememos/memos#3917]
### Describe the bug

![image](https://github.com/user-attachments/assets/026a1c49-0911-4b97-a889-49e8aebb56ef)
试图从数据库的方式改变成为文件系统，这样改变之后，下次启动，仍然还是使用sqlite

### Steps to reproduce

我不确定是否跟我的部署方式有关，我是在win10系统上面，自行编译和部署的，并没有通过docker……
如果是的话，应该用什么办法手动迁移一下？

### The version of Memos you're using.

0.22.5

**Comment by RoccoSmit** [comment]
How are you identifying the storage method did not change? Is it not changing on the ui or your resources are not stored in the new location?

**Comment by asasn** [comment]
> How are you identifying the storage method did not change? Is it not changing on the ui or your resources are not stored in the new location?

I was deployed locally and I didn't see any changes in the folder, still using memos_dev.db
I'm not sure if my deployment is wrong?
![image](https://github.com/user-attachments/assets/c9d7f788-f5e9-4c8c-9744-19641aa30e4a)

**Comment by RoccoSmit** [comment]
Your memo text and general information to run the site will live in your db.
The storage setting is for resources such as images or documents.
I see you have the assets folder. Local storage files will go in there

**Comment by asasn** [comment]
> Your memo text and general information to run the site will live in your db. The storage setting is for resources such as images or documents. I see you have the assets folder. Local storage files will go in there

I know the new assets will be there, but... Maybe I have not stated clearly, how can I transfer the old data to the past? It was stored in .db file
Wait, it seems that manual migration is only possible through database operations!
I found blob, reference fields in the table resource...
Maybe I can do it from here
But I still want to add one-click migration to the frontend

**Comment by lincolnthalles** [comment]
> > Your memo text and general information to run the site will live in your db. The storage setting is for resources such as images or documents. I see you have the assets folder. Local storage files will go in there
> 
> I know the new assets will be there, but... Maybe I have not stated clearly, how can I transfer the old data to the past? It was stored in .db file Wait, it seems that manual migration is only possible through database operations! I found blob, reference fields in the table resource... Maybe I can do it from here But I still want to add one-click migration to the frontend

Changing the storage location won't affect existing assets. They stay where they were first saved, as there is no automated migration built in.
