### ISSUE TITLE
Hope to add the default language setting

### ISSUE THREAD

**Issue by fengdu126** [usememos/memos#3919]
### Describe the solution you'd like

Now the default language is English. Hope to add an environment to change the default language.

### Type of feature

User Interface (UI)

**Comment by yggcwx** [comment]
There are indeed such problems. Even after the login administrator account, set the "server language environment" in the system settings to other languages, such as Chinese, and the default language of the login interface is still English. Therefore, I have the same expectations and hope.

**Comment by RoccoSmit** [comment]
@fengdu126, are you trying to set the language on container creation?
Are you finding the language selection on the login page or the language settings does not work?

**Comment by Matinal111** [comment]
> There are indeed such problems. Even after the login administrator account, set the "server language environment" in the system settings to other languages, such as Chinese, and the default language of the login interface is still English. Therefore, I have the same expectations and hope.

Indeed, and in the login interface and system settings in the language environment set to Chinese or other languages, clear the browser cache or change the use of the environment to open again will default to English, I hope to add an environment variable to control the language settings!
