### ISSUE TITLE
请教这个报错是什么情况

### ISSUE THREAD

**Issue by zlxuan** [usememos/memos#3921]
### Describe the bug

小白，刚接触，请问执行docker出现这个报错是什么原因
![Snipaste_2024-09-13_16-59-34](https://github.com/user-attachments/assets/2ed39ed8-5a5b-471f-b151-eea67580a742)

### Steps to reproduce

使用`docker run -d --name memos -p 5230:5230 -v ~/.memos/:/var/opt/memos neosmemo/memos:stable`

### The version of Memos you're using.

v0.22.0

**Comment by songheng45** [comment]
中国访问不了docker的官方镜像啦
