### ISSUE TITLE
The translation is temporarily closed for contributions due to maintenance, please come back later.

### ISSUE THREAD

**Issue by atakanhr** [usememos/memos#3924]
### Describe the bug

The translation is temporarily closed for contributions due to maintenance, please come back later.
![Screenshot 2024-09-14 at 8 15 45 PM](https://github.com/user-attachments/assets/a7ef23d3-18cf-432c-9745-834a390d0297)

### Steps to reproduce

https://hosted.weblate.org/projects/memos-i18n/english/#alerts

### The version of Memos you're using.

latest

**Comment by boojack** [comment]
We may not be maintaining the weblate repo, so if you want to contribute to i18n, you can just clone the code and modify it. e.g., https://github.com/usememos/memos/pull/3935
