### ISSUE TITLE
Add ability to @ users and other memos

### ISSUE THREAD

**Issue by Lyzod** [usememos/memos#3927]
### Describe the solution you'd like

Similar to most note taking tools, it would be nice to @ Users (incl non existing ones) and link to other memos to be able to structure them in a different way. This also enhances collaborative work. 

If you click on the @ the user profile or memo should pull up and they act like tags in the sense you can search for them. 

### Type of feature

User Experience (UX)

### Additional context

You can essentially interlink memos, making it a more connected amd easy to remember experience and it's easier to collaborate bc if users act similar like tags, they can filter all their mentions out

**Comment by RoccoSmit** [comment]
You can link to other memos using the chain icon
![image](https://github.com/user-attachments/assets/764b2495-59c5-4e2c-adde-8edad14b1ebd)

**Comment by Lyzod** [comment]
I must have missed that. Thank you! I thought it was only for embedding. 

Still mentioning like a person would be great to link several memos at once

**Comment by wolkenschieber** [comment]
> Still mentioning like a person would be great to link several memos at once

+1
