### ISSUE TITLE
Add support for all Unicode emojis in reactions 

### ISSUE THREAD

**Issue by Lyzod** [usememos/memos#3928]
### Describe the solution you'd like

Sometimes 12 options just isn't enough, especially if you are doing a poll (esp. bc polls themselves aren't possible yet). Adding support for all the known unicode emojis seems to be the simplest solution

### Type of feature

User Experience (UX)

**Comment by RoccoSmit** [comment]
Adding some references to previous emoji requests. This didnt get much traction in the past but worth mentioning

https://github.com/usememos/memos/issues/3563
https://github.com/usememos/memos/issues/3743

**Comment by boojack** [comment]
Implemented with https://github.com/usememos/memos/commit/e527b6a878437027d6dc9dbb70edde347409a27f, https://github.com/usememos/memos/commit/2acad978d1718fd9ba9bbe4ee23e34d6777fd42f

<img width="931" alt="image" src="https://github.com/user-attachments/assets/4e3711f9-72ed-4e96-8063-5380e2feab94">

<img width="642" alt="image" src="https://github.com/user-attachments/assets/aa222e1d-4cc0-47e0-8601-9c69797121d8">
