### ISSUE TITLE
Undo changes made by commit #3849 for certain files

### ISSUE THREAD

**Issue by xueba0458** [usememos/memos#3931]
### Describe the solution you'd like

The pull request [#3849](https://github.com/usememos/memos/pull/3849) is pointless; on modern computers, saving such a small amount of storage space is negligible. However, the consequence of this space-saving effort is the inability to use bash, which in turn disables many troubleshooting methods. In Chinese, there's a proverb to describe this situation: "Losing the watermelon while picking up the sesame seeds," meaning you're sacrificing something important for a trivial gain.
![image](https://github.com/user-attachments/assets/59b2b8c6-1f41-469c-9756-c7989f513c16)

### Type of feature

Other

**Comment by SlavikCA** [comment]
Agree.

Please bring shell back.

**Comment by Promix953** [comment]
Yes, it also causes healthcheck to fail and healthz endpoints to look like a joke!

PS：提交那个PR的人就是个SB！
