### ISSUE TITLE
Can I change the path of the default sqlite database

### ISSUE THREAD

**Issue by KimigaiiWuyi** [usememos/memos#3933]
### Describe the solution you'd like

Can I change the location of the default sqlite database to be inside the application path so that it can be easily migrated to a different server, maybe through a startup parameter or config or something like that, I'd like to have an optional option to configure the data/database path.

### Type of feature

Other

**Comment by RoccoSmit** [comment]
Can you share some context scrubs your setup? If you are using docker migration should be as simple as copying your db (and assets) to the new server, spining up a memos container and setting the storage location to where you saved your db

**Comment by RoccoSmit** [comment]
When I build the .exe and run it the db is created in the same folder as the exe. Where is your db stored?

**Comment by KimigaiiWuyi** [comment]
> When I build the .exe and run it the db is created in the same folder as the exe. Where is your db stored?

I'm very sorry, I ran dev main.go directly, I haven't tried to build it yet, it's stored in `C:\Users\Admin\AppData\Local\Temp\go-build2018550480\b001\`, I'll try to run it after I try to build it, thanks! ❤️
