### ISSUE TITLE
Feature request: A menu option to clear "checked" list items

### ISSUE THREAD

**Issue by kandykarter** [usememos/memos#3936]
### Describe the solution you'd like

One of the primary tasks I use Memos for is grocery lists. It would be very handy if there was an option in the dropdown menu which I could click to autoremove checked list items.

### Type of feature

User Experience (UX)

### Additional context

It's tedious going through lists and manually removing individual entries to keep my lists short and up-to-date

**Comment by RoccoSmit** [comment]
Aligns with pr https://github.com/usememos/memos/pull/3894 (has no issue linked)
