### ISSUE TITLE
black mode

### ISSUE THREAD

**Issue by helmut72** [usememos/memos#3944]
### Describe the solution you'd like

It would be great if dark mode is optionally a black mode with white text on black background.

Thank you.

### Type of feature

User Interface (UI)

### Additional context

Light mode does have normal contrast with black text on white background), dark mode won't. I prefer dark mode, but my eyes need more contrast than existing dark theme. Look at Githubs dark mode.

**Comment by helmut72** [comment]
Yes, it's not maybe dark, it is dark: light grey text on dark grey background. But I ask for **black** mode: white text on black background.

**Comment by RoccoSmit** [comment]
You can modify your dark mode to be black. Go to `settings` -> `system` -> `additional styles` and add the following CSS

```
body:is(.dark *), 
.dark\:bg-zinc-800:is(.dark *), 
.dark\:text-gray-300:is(.dark *), 
.dark\:text-gray-400:is(.dark *) {
    background-color: black;
    color: white;
}
```

This should darken your dark mode while still giving you light mode if you change your preferences

**Comment by helmut72** [comment]
After updating to latest 0.25, it doesn't work anymore. Everything is grey in grey, not much readable.
