### ISSUE TITLE
Show number of memos with tag

### ISSUE THREAD

**Issue by alehmann76** [usememos/memos#3947]
### Describe the solution you'd like

It would be probably helpful if i can see how many memos have which tag assigned:
e.g.
#home     2
#holiday  23
#job         345

This could be integrated in the "Tag" view on the right sidebar when the tree-mode is active

### Type of feature

User Experience (UX)

**Comment by RoccoSmit** [comment]
There is already a count next to tags (qty > 1). Is this what you are referring to?
![image](https://github.com/user-attachments/assets/c260e270-c9fc-4a65-90e0-9bfe43bca6e3)

**Comment by alehmann76** [comment]
Big sorry.... my mistake.... i used a rather old veriosn on my test server!
--> Everyting fine now! Great product and keep on fantastic work!!

**Comment by zodac** [comment]
Looks like there is no count for tags in tree mode? Only in default mode?
