### ISSUE TITLE
can't use top-level tag as a filter when using Multi-level tags

### ISSUE THREAD

**Issue by YiHui-Liu** [usememos/memos#3948]
### Describe the bug

can't use top-level tag as a filter when using Multi-level tags
when use top-level tag as filter:
![image](https://github.com/user-attachments/assets/b823b799-bf31-4fd0-b2a8-74bc1e219c4a)

however, there are really some memos in child tags:
![image](https://github.com/user-attachments/assets/3e9c55a9-07e8-4dbd-9cd9-34f918edfae9)

### Steps to reproduce

1. create a memo with tag `a/b`
2. search with tag `a` and no result

### The version of Memos you're using.

v0.22.5

**Comment by RoccoSmit** [comment]
new instance of https://github.com/usememos/memos/issues/3753

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/8b444be6cab908bfa7eb44758c477e16bbcd10eb
