### ISSUE TITLE
Upload any type of file in Memos

### ISSUE THREAD

**Issue by muhanstudio** [usememos/memos#3957]
### Describe the solution you'd like

At present, only picture-type files can be uploaded. I hope it can support uploading any type of files, and then display them in Memos in the form of links or cards.

### Type of feature

User Interface (UI)

**Comment by RoccoSmit** [comment]
What file types are you finding are not uploading, uploading non images is supported
![image](https://github.com/user-attachments/assets/fefc470f-74ce-4815-b75a-0d58c3aafb49)

**Comment by muhanstudio** [comment]
Sorry, I may have used an older version of the docker image and didn't upgrade in time. It's OK at the moment. Bother
