### ISSUE TITLE
不登陆无法查看内容（匿名访问失效）

### ISSUE THREAD

**Issue by 17huiwei** [usememos/memos#3958]
### Describe the solution you'd like

我记得之前可以完全公开自己的memo，现在无论如何都需要登录才能查看，即便后台设置了【公开】的选项

### Type of feature

User Interface (UI)

### Additional context

![image](https://github.com/user-attachments/assets/cb483382-b6f5-4031-b178-66dd3c11223e)

![image](https://github.com/user-attachments/assets/e0035a55-f5db-4046-a781-2e03959b2e4f)

**Comment by RoccoSmit** [comment]
That seeing is the default memo visibility for any new memos you create. It does not go back and change memo visibility.
You will need to go to the memos that you want to be public and change their visibility individually
