### ISSUE TITLE
Add count for tags

### ISSUE THREAD

**Issue by zodac** [usememos/memos#3962]
### Describe the solution you'd like

I'd really like to be able to summarise my notes and count how many of them have a given tag. It would be great if the `tag` section on the home page would also include a count of matching memos. Ideally at all times, but would be fine if this only appeared/was calculated when a tag is selected as a filter.

### Type of feature

User Interface (UI)

**Comment by RoccoSmit** [comment]
Duplicate of https://github.com/usememos/memos/issues/3947

**Comment by zodac** [comment]
Thanks, I'll track that one :)
