### ISSUE TITLE
Any healthcheck API? 

### ISSUE THREAD

**Issue by zodac** [usememos/memos#3963]
### Describe the solution you'd like

It would be great if there was some API that could be used to monitor that the system was online and running. I was able to find some references to an API, but nothing explicit. 

### Type of feature

API

### Additional context

I'm using Uptime-Kuma to monitor the status of my applications, checking if there is a dedicated endpoint for this usecase.

**Comment by RoccoSmit** [comment]
There is `/healthz`
Returns `200` `Service ready.`

**Comment by zodac** [comment]
Hey, that's perfect. Thanks!
