### ISSUE TITLE
Cloudflare R2 storage in docker not working.

### ISSUE THREAD

**Issue by Leonidas300** [usememos/memos#3965]
### Describe the bug

I added every info needed - id,secret,endpoint, region and there is no error or anything but notes are not saved on cloudflare, only on local file system.

### Steps to reproduce

1. In settings change storage to S3
2. Fill all Info
3. Click Save

### The version of Memos you're using.

v0.22.5

### Screenshots or additional context

Device: Raspberry pi.
Docker image inside CasaOS.

**Comment by RoccoSmit** [comment]
The S3 settings under storage indicates were you want your resources (images, files ,etc.) saved. The main sqlite db where your memos (notes) and data to run the site is stored will still be created locally on the device.

**Comment by Leonidas300** [comment]
Ok, I thought that all data will be saved on cloud. Anyway nothing is saved there no data, nothing. Cloud storage on cloud flare is empty.

**Comment by RoccoSmit** [comment]
Just to confirm, since setting up your CloudFlare settings have you created new notes with images attached?

**Comment by Leonidas300** [comment]
Yes sorry, It's working. I thought that I tested notes with images. Sorry for this one. I have a question tho - is there a way to transfer existing images from localdb to cloudflare? Also Is there a way to make notes DB on cloud ? Thanks.

**Comment by RoccoSmit** [comment]
There is currently no automated way to transfer images from db to cloud storage. see https://github.com/usememos/memos/issues/3917#issuecomment-2348839911

i dont believe you can set up the db only to be hosted, I think you you will need to host the entire application

**Comment by Leonidas300** [comment]
Ok. Thank you.
