### ISSUE TITLE
memos.api.v1.MemoService/ListMemos is very slow

### ISSUE THREAD

**Issue by DLHTX** [usememos/memos#3969]
### Describe the bug

I updated to the v0.22.6, but the memos list very slow,when i refresh home page, it takes amlost two minutes 

### Steps to reproduce

1.Go to home page
2.refresh

### The version of Memos you're using.

0.22.6

### Screenshots or additional context

![image](https://github.com/user-attachments/assets/a1d7672b-874b-4070-b570-e33e6f9f0e64)

**Comment by DLHTX** [comment]
This api `memos.api.v1.ResourceService/ListResources` is also  very slow does it load the entire db file?
![image](https://github.com/user-attachments/assets/84d980e8-831b-4f76-8af0-f9779afb759a)

**Comment by DLHTX** [comment]
![image](https://github.com/user-attachments/assets/1904cfa7-8c09-453c-969d-2c0da1f19155)

**Comment by RoccoSmit** [comment]
What version did you upgrade from? v0.22.5 introduced caching functionality that would require thumbnails to be generated on first load. This could be the cause for a slow first load

**Comment by DLHTX** [comment]
> What version did you upgrade from? v0.22.5 introduced caching functionality that would require thumbnails to be generated on first load. This could be the cause for a slow first load

Hi, I just 100% reproduced this problem, I deleted memos_prod.db and restarted docker, and made a new copy of this memos_prod.db. it loads fast when I first go to the page, but when I go to other page, it seems to make a request for ListResources and then all the loading of the page gets stuck. I think it might be the caching mechanism you're talking about.

**Comment by RoccoSmit** [comment]
The request that might be sow on first load due to caching would be the `/file/resources/{id}/{imageName}` image requests.

Are you finding the site is slow with an fresh db? So no memos or images to display?

**Comment by RoccoSmit** [comment]
The only other example I can think of where "the page gets stuck" is this issue https://github.com/usememos/memos/issues/3922#issuecomment-2373170990. Does your experience align with this?
