### ISSUE TITLE
Incorrect markdown formatting

### ISSUE THREAD

**Issue by quaintdev** [usememos/memos#3973]
### Describe the bug

Below two images show the issue

My Markdown:
![image](https://github.com/user-attachments/assets/533b50f8-4318-456f-bcd9-d6fa4c65dffd)

Result:
![image](https://github.com/user-attachments/assets/c3d82e5a-7aa0-4715-8890-81abe18d7b94)

The headings should not be at bottom but in between bullet points

### Steps to reproduce

Use markdown shared and the issue can be seen once memo is saved

### The version of Memos you're using.

latest

**Comment by RoccoSmit** [comment]
See https://github.com/usememos/gomark/issues/7 for resolution
