### ISSUE TITLE
Ability to Add Memos to a "Group" or "List" for better organization

### ISSUE THREAD

**Issue by pxlnic** [usememos/memos#3984]
### Describe the solution you'd like

What I wanted to suggest is the ability to create "Lists" or "Groups" that memos can be associated with. I would think the lists/groups would be accessible on the left hand panel (either it's own page or a collapsed list) and when you click on a "list/group" it will filter to just the associated memos.

The "list/group" could also just be a filtering option on the "Home" page.

Nesting lists would also be helpful but not the biggest concern.

### Type of feature

User Experience (UX)

### Additional context

Memos has been a fantastic service for me, but I have noticed I tend to lose/forget about memos I created that I want to revisit. I've resorted to moving content I want to keep long term to another app where I can do some better organization.

I am really looking to cut down on the number of apps/services I am running/using and would like to have a single app to jot notes down or track things quickly, but not being able to organize memos (outside of tagging) has made it a bit chaotic for me.

**Comment by xhocquet** [comment]
I've been using tags for this purpose. For example #blogposts, and I can click the tag on the right side and see only my blog posts. Are you looking for something different?

**Comment by cethink** [comment]
> I've been using tags for this purpose. For example #blogposts, and I can click the tag on the right side and see only my blog posts. Are you looking for something different?

就是像笔记本一样分类，可以分类录入，也可以分类查看。用tag总是不习惯，tag更像是从一堆无序的memos中查找，类似于搜索功能，而分类就更结构化，可以只关注一个分类主题，在里面录入相关内容，也可以添加tag，tag就比较随意了，想到什么添加什么，不用过多思考。这是一个习惯问题。 #4101

**Comment by cethink** [comment]
> I've been using tags for this purpose. For example #blogposts, and I can click the tag on the right side and see only my blog posts. Are you looking for something different?

It is like a notebook that can be classified and entered and viewed. I am not used to using tags. Tags are more like searching from a pile of disordered memos, similar to the search function, while categories are more structured. You can focus on a classification theme and enter relevant content in it. You can also add tags. Tags are more casual. You can add whatever you think of without thinking too much. This is a matter of habit. Thanks.
