### ISSUE TITLE
using tags among all users

### ISSUE THREAD

**Issue by non9mer** [usememos/memos#3985]
### Describe the solution you'd like

HELLO!
It would be great to be able to see and use tags in _workspace_ that were created by another user.
So, let's say another user created a note in the _workspace_  section, creating new tags for it, but the current implementation does not allow these tags to be shared between other users, and this seems very useful.

Best wishes!

### Type of feature

User Interface (UI)

### Additional context

I'm trying to make it so that when new tags are created, they are shared among all users, appearing in the right column, under the _TAGS_ section.

**Comment by RoccoSmit** [comment]
@boojack, I'd like to implement this.

The 2 ways I was thinking about are:

1) Create a `useTagsdataStore` that leverages `useMemoMetadataStore`. `useMemoMetadataStore` would get a all the metadata info including tags (`private`, `protected` and `public`) for the user and `useTagsdataStore` would make another call and get all user's `protected` and `public` tags and merge the 2 lists of tags together.

This approach has some shortcoming in that it will retrieve the user's `public` and `protected` tags 2 times, but it is a smaller change in the code and uses existing mechanisms.

2) Add another filter list that will be mapped to `or` logical operators in the `.sql` file queries. This way the db query can get all memos that have a `creatorId` of x `or` `protected` and `public` visibility all in a single query.

This approach is more involved as it will require changes across FE, server and db store files for all 3 db types.

Thoughts?

**Comment by non9mer** [comment]
up
