### ISSUE TITLE
feat: i18n in frontend

### ISSUE THREAD

**Issue by boojack** [usememos/memos#4]

**Comment by YuJianghao** [comment]
看好几天没有动静了，有什么安排么。我可以帮助完成国际化的部分内容。:p

**Comment by boojack** [comment]
> 看好几天没有动静了，有什么安排么。我可以帮助完成国际化的部分内容。:p

目前首屏页面的翻译几乎都做完了，如果有空的话可以帮忙看看一些 dialog 组件的翻译 thx

（目前 i18n 的实现是自己写的，没有直接用主流的库，不过感觉也够用了
