### ISSUE TITLE
Username need to support email formats

### ISSUE THREAD

**Issue by jkoor** [usememos/memos#4001]
### Describe the solution you'd like

The username field does not support email formats.
This may causes some problems when logging in using oAuth2:
1. Unable to match registered user. Only English and numeric usernames are supported for registration. But Google support use `Blank Space` on username.
2. When I changed username on Google or Github, Memos will create a new user to login. **All data is missing!**
> Although email mapping is supported, the administrator always needs to be the first to register.So I can't match oauth user to administrator.

### Type of feature

User Experience (UX)

**Comment by Samarthasbhat** [comment]
I have signed in this Memo live demo website. And the username and password is already saved. I want to know how it works and there we need to add google account or github credentials for login/signup method.

**Comment by jkoor** [comment]
> @jkoor I have signed in this Memo live demo website. And the username and password is already saved. I want to know how it works and there we need to add google account or github credentials for login/signup method.

Only **Administrator** can add google account or github credentials for login/signup method.
If you are administrator, just search `google oauth`. You can find many guidance about it.
