### ISSUE TITLE
Change date is invalid when editing memos in mobile devices(ios and ipados so far)

### ISSUE THREAD

**Issue by raymondyan** [usememos/memos#4003]
### Describe the bug

Context: I want to modify the date of my memos on my iPhone(os version is iOS 18, and browser i am using is Safari), and when I click the date string which is the way to change the date, then the date will become "invalid date", if then I click the save, the date will become `Thu, Jan 1, 1970` which is the start timestamp of the system.

### Steps to reproduce

1. in iphone or ipad, login from browser like safari
2. click the edit
3. click the date
4. date will be invalid

### The version of Memos you're using.

v0.22.5

### Screenshots or additional context

![IMG_54D81A4BF685-1](https://github.com/user-attachments/assets/55ab20a5-c03a-4f47-8a18-f948e1b31fe9)

**Comment by RoccoSmit** [comment]
Duplicate of https://github.com/usememos/memos/issues/3812

**Comment by raymondyan** [comment]
> Duplicate of #3812

Thanks, i will close it now
