### ISSUE TITLE
Toggling system dark theme requires reloading

### ISSUE THREAD

**Issue by rc2dev** [usememos/memos#4005]
### Describe the bug

First of all, thanks for this awesome application!

I noticed that if I toggle my system dark mode, Memos doesn't follow the change, unless I refresh the page.

OS: Debian 12
Browser: Chromium 129
Memos: v0.22.5

### Steps to reproduce

1. Open Memos on your desktop browser.
2. Make sure Memos is set to follow system theme.
3. Toggle system theme (to dark or light).

Expected result: Memos theme also switches (to dark or light).
Actual result: Nothing happens.
Workaround: Manually refreshing the page changes the theme.

### The version of Memos you're using.

v0.22.5

**Comment by RoccoSmit** [comment]
PR https://github.com/usememos/memos/pull/4010
