### ISSUE TITLE
Remind me about a task at a specific time

### ISSUE THREAD

**Issue by zygm0nt** [usememos/memos#4007]
### Describe the solution you'd like

It would be really useful to have a feature of reminders for notes. I'd like to set time and date for a specific note.

### Type of feature

API

### Additional context

I'm using Memos via web and via Ios App (MoeMemos) and it would be ideal to have an alert pop up on the phone at specific time. But I imagine that for it to happen, it first needs to be implemented in the server itself.

**Comment by RoccoSmit** [comment]
Similar to discussion https://github.com/orgs/usememos/discussions/3949

Reminders have not gotten much traction recently, but have a look at this repo https://github.com/ertuil/memos-reminder. It might do what you are after

**Comment by zygm0nt** [comment]
Great - Thank you for this link.

Perhaps it's worth updating the docs to point to this route? I can provide the necessary update.

**Comment by zygm0nt** [comment]
@johnnyjoygh I'm not too interested in browser notifications. It would be much more useful for me to have some external poke with notifications, mainly on the phone. 

So I think for this reason https://github.com/ertuil/memos-reminder would work pretty well. Will try that one.

But to have that working, it would be super nice to have some way to input date and time in a consistent manner. Would it be a welcome addition to have that implemented in the web-app?
