### ISSUE TITLE
"Show pins" button on the side bar

### ISSUE THREAD

**Issue by tiagoprn** [usememos/memos#4008]
### Describe the solution you'd like

I have about 10 pinned items, and every time I add a new memo I have to scroll to find it on the "all" list. 

Maybe you could put a "pinned" button on the side bar to see them, or a filter to show pinned/not pinned items. If you go with a filter, it would be nice to do it in a way it can be bookmarked to be easier to use. 

I face the same issue with the Android mobile app. 

### Type of feature

User Interface (UI)

**Comment by RoccoSmit** [comment]
Similar issue https://github.com/usememos/memos/issues/3988

**Comment by tiagoprn** [comment]
@johnnyjoygh Those are items I intend to visit some time on the future. Since I want to get back to them, it is nice to have them somewhere I can see regularly. Similar to how https://github.com/usememos/memos/issues/3988 uses it. And since the pins are already there... ;)

**Comment by ocean-haiyang** [comment]
I also do this and would love this feature.

**Comment by gitkeniwo** [comment]
Same, as some threads are frequently used and there's no easy to way to navigate
