### ISSUE TITLE
Make an existing token (e.g. WebUI, Android) not to expire 

### ISSUE THREAD

**Issue by tiagoprn** [usememos/memos#4009]
### Describe the solution you'd like

On the page you can see all your tokens, you could add an "edit" or "change expiration" button to be able to change that date (to a specific one, "immediately" or "never"). 

That is because on WebUI and Android, it expires after ~1 month and that is a little inconvenient. 

### Type of feature

User Interface (UI)

**Comment by RoccoSmit** [comment]
Are you referring to login or manual token create on the website or android app

website user logins last for 100 years
![image](https://github.com/user-attachments/assets/a899ddbb-a7cc-43b8-8df9-b5b70f33403a)

and website manual token creation already have a never expire or you can delete for immediate expiry
![image](https://github.com/user-attachments/assets/16e65b98-409b-429b-ab99-72e74476ff0c)

**Comment by boojack** [comment]
Feel free to reopen this if you still have some questions

**Comment by RoccoSmit** [comment]
Note on why the shorter re-login time was experienced

During initial setup and host account auth token creation the expiry date is set to 7 days in the future
https://github.com/usememos/memos/blob/317cf065794df117998568f9536878c9b8751200/server/router/api/v1/auth_service.go#L224

Subsequent logins set the auth token expiry date is set to 100 years in the future
https://github.com/usememos/memos/blob/317cf065794df117998568f9536878c9b8751200/server/router/api/v1/auth_service.go#L73-L77

`AccessTokenDuration` = 7 days
