### ISSUE TITLE
Tag content needs to be restricted

### ISSUE THREAD

**Issue by Mahoo12138** [usememos/memos#401]
### Describe the bug

```markdown
#tag test [URL](https://demo.usememos.com#title), contains white space.
```
The above will generate two tags: 
+ `tag`
+ `title),`

The tag regexp is just restricted to non-blank characters and one space only: 
https://github.com/usememos/memos/blob/5bdf15aecec545ebfa1205d7504dad6e1eb9e798/server/tag.go#L15
So I think there is a need for more restrictions on tag content, e.g. using `(?!pattern)` to exclude some special characters.

### Steps to reproduce

omitted

### Expected behavior

omitted

**Comment by Zeng1998** [comment]
I think special characters in tags should be allowed.

And for this issue, I think a solution is to change the regex of a tag to `[space]#tag[space]`. Or maybe someone else has a better solution?

**Comment by Zeng1998** [comment]
It would be better to provide details for reproduction.

**Comment by Mahoo12138** [comment]
It still hasn't been fixed.
