### ISSUE TITLE
Can't change avatar

### ISSUE THREAD

**Issue by Maypul** [usememos/memos#4015]
### Describe the bug

Can't update the avatar when username change is disallowed, the error says the username can't be changed even thought only avatar is being changed.
User is host but logged in with SSO

### Steps to reproduce

Open up user setting
click on avatar
Upload new avatar
click Save
See: permission denied: disallow change username

### The version of Memos you're using.

Latest

**Comment by zdebel** [comment]
https://github.com/usememos/memos/issues/3995 this was reported here by me and is fixed :-)
