### ISSUE TITLE
Unable to minimize notes at HOME tab of memos

### ISSUE THREAD

**Issue by Samk19** [usememos/memos#4020]
### Describe the bug

Hi,
I have just installed Memos docker compose and after creating and saving note the note on the home tab of the memos app doesnt minimize. There is no minimize option in setting or any option to do so manually 
![Screenshot_20241014_134850_Gallery](https://github.com/user-attachments/assets/01649413-e6aa-4b2c-b758-e632e637a12b)

As you can see with a multiple notes that have large number of lines this is causing issue with management

### Steps to reproduce

1. Create a note
2. in the note use code block option 
3. write at ramdon 100 lines
4. save 
5. go back to home tab in memos
6. and u can see the full note 
7. with multiple notes with large number of line the home tab becomes messy.

Kindly let me know hoe i can mininize my notes atleast on Home tab of memos for a cleaner look. If this feature is not present kindly add this to feature request.

For feature request (if not already preset):
1. notes on HOME tab to have a. **The heading** with **first 2- 3 lines of conten**t (for overviewing) along with b. **tag** if any present in the note

Thankyou

 

### The version of Memos you're using.

Version: v0.22.6

### Screenshots or additional context

Compose in use example:

version: "3.0"
services:
  memos:
    image: neosmemo/memos:stable
    restart: always
    depends_on:
      - db
    ports:
      - 5230:5230
    environment:
      - MEMOS_DRIVER=postgres
      - MEMOS_DSN=user=memos password=secret dbname=memosdb host=db sslmode=disable

  db:
    image: postgres:16.1
    restart: unless-stopped
    volumes:
      - "./database:/var/lib/postgresql/data/"
    environment:
      POSTGRES_USER: memos
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: memosdb

**Comment by Samk19** [comment]
Hey,
Yes i have it enabled already the problem is it doesn't reduce the note if text is between '''.


Example:
 '''
Abc
Qbv
Usbsh
Hdhdh

'''


------
Added screenshot for Reference below

![Screenshot_20241014_171647_Gallery.jpg](https://github.com/user-attachments/assets/ed671ffc-b6d0-4ac2-85b3-16b211d4f221)

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/memos/commit/c4b52c68b5f549457fcb6209c99de002194800f5
