### ISSUE TITLE
Can we disable the markdown key mapping?

### ISSUE THREAD

**Issue by d0zingcat** [usememos/memos#4022]
### Describe the solution you'd like

I am a macOS/unix/linux user and I frequently use the unix-like keymapping day and night. 
But memos Editor register the keymap by default, e.g. Ctrl-B to generate a bolder syntax of markdown instead of moving cursor backforward.
It's quite annoying.

### Type of feature

User Interface (UI)

### Additional context

I will try to submit an enhancement branch which includes:
1. Settings/Memos: Add one option "Disable Shortcut"
2. Persistent 1. option into database(and do the db migration)
3. In web editor, read the options, if there's the disable config, then don't register the markdown keydown handler.

**Comment by RoccoSmit** [comment]
Can the default be set as `true` (shortcut keys are in use).

With the default set to true users will be none the wiser of the change and their user experience won't be affected and those who want the change can toggle the setting.

If the default is set to `false` the are going to be users who use to have a feature that is going to be missing after upgrading and I'd imaging GitHub issues will follow.

**Comment by RoccoSmit** [comment]
Fair point, my line of thinking is "how many users do/don't want shortcuts" (I for one like using `ctrl` + `enter` to quick save) and which is the bigger group being negatively impacted by removing the feature vs giving the ability to remove the feature

**Comment by d0zingcat** [comment]
I share the same thoughts with @RoccoSmit as I think there maybe more users who is using the shortcuts more than those don't. A better way is to keep things as they were and add a new choice to change, namely like I've commented, maybe the name should be like `"Disable editor shortcut"` with the default set to `"false"`, just like the `"Disable public memos
"` option.
