### ISSUE TITLE
[UX IMPROVEMENT] Add support for keyboard shortcuts to scroll through images while viewing 

### ISSUE THREAD

**Issue by Greatz08** [usememos/memos#4024]
### Describe the solution you'd like

While viewing multiple attached images of a message it would be better to be able to scroll images with keyboard shortcuts (left and right keyboard keys) rather than clicking left and right which dont even show any arrows btw

### Type of feature

User Experience (UX)

**Comment by RoccoSmit** [comment]
Feature added and will be in the next release
