### ISSUE TITLE
Is there a client for mac?

### ISSUE THREAD

**Issue by MagicStarTrace** [usememos/memos#4027]
### Describe the solution you'd like

You need to open a browser every time to write
If only there was a client

### Type of feature

Other

**Comment by RoccoSmit** [comment]
Have a look at the community page, there are a couple of mac projects
https://www.usememos.com/docs/contribution/community

**Comment by MagicStarTrace** [comment]
> Have a look at the community page, there are a couple of mac projects看看社区页面，有几个 mac 项目 https://www.usememos.com/docs/contribution/community

I'm using it but I realized it's basically nested pages! I'm using it, but I'm realizing that it's basically nested pages, would the meme consider a native client?
