### ISSUE TITLE
OpenGraph Protocol support

### ISSUE THREAD

**Issue by xcassanello** [usememos/memos#4029]
### Describe the solution you'd like

It would be great if Memos could implement the open graph protocol so sharing a post into any social network will have the memo's:
- Title (which can be the memo's name)
- Description (which can be a 25 characters introduction to the memo)
- Image (the attached image. The first frame of the video attached would be awesome). Falling back to Users' avatar by default.
- URL of course
- Type

I will look if i've time to propose a PR, even through i've never touched go, since this is basically adding some metadata to the HTML templates for a "post" page, i guess it can't be that difficult (except for extracting the first frame of the video attached haha)

Based on https://ogp.me/

### Type of feature

Integrations

### Additional context

This is important to share content to other social networks, ie Whatsapp, Telegram, Twitter, Facebook, etc... This enriches the preview engaging people to follow the shared content.

**Comment by coolaj86** [comment]
I would like this as well.

Reasonable defaults:
1. First `#` (markdown heading) is the title
2. First sentence is the description
3. First image attachment is the image

```html
<meta property="og:title" content="Your Page Title">
<meta property="og:description" content="A compelling 1–2 sentence description.">
<meta property="og:image" content="https://example.com/image.jpg">
<meta property="og:url" content="https://example.com/page">
<meta property="og:type" content="website"> <!-- or article, product, etc. -->
<meta property="og:site_name" content="Your Site Name">
```
