### ISSUE TITLE
All my data is gone

### ISSUE THREAD

**Issue by 1412849797** [usememos/memos#403]
### Describe the bug

I used the docker restart command to restart the container. After the restart, all the records were gone

### Steps to reproduce

1.docker restart   memeos

### Expected behavior

 After the restart, all the records were gone

**Comment by Zeng1998** [comment]
It would be better to provide details for reproduction.

**Comment by 1412849797** [comment]
这是我的docker-compose文件
![image](https://user-images.githubusercontent.com/59927567/199867421-abb061bb-6112-4200-9ab5-8c08f767b34e.png)
已经挂载了目录，但是重启容器之后并未加载数据。
尝试重新写了一条记录，多次重启容器之后数据还在，只有第一次重启后数据没了。

写记录的时候，偶尔还提交失败

**Comment by boojack** [comment]
> 只有第一次重启后数据没了

“数据没了”指的是数据库文件没了？

**Comment by 1412849797** [comment]
> > 只有第一次重启后数据没了
> 
> 
> 
> “数据没了”指的是数据库文件没了？

> 数据库文件还在，但是网页打开登陆后，之前添加的记录都没有。现在就不会，我也不清楚怎么回事
