### ISSUE TITLE
[Feature Request] Navigate back or forward in time using the Calendar sidebar on the main Home page.

### ISSUE THREAD

**Issue by copey02** [usememos/memos#4033]
### Describe the solution you'd like

currently the Calendar in the right sidebar allows you to view the current month and entries made in the current month. 
It would be great if you could click the Month or calendar icon to navigate through previous Months/years. 

### Type of feature

User Interface (UI)

**Comment by RoccoSmit** [comment]
I believe this is already implemented and should be on the `latest` docker image (not `stable`)

See https://github.com/usememos/memos/pull/3972
