### ISSUE TITLE
Unexpected Application Error

### ISSUE THREAD

**Issue by penndu** [usememos/memos#4039]
### Describe the bug

Unexpected Application Error!
Failed to fetch dynamically imported module: https://s.dusays.com/assets/Explore-RjZk8uN2.js
> TypeError: Failed to fetch dynamically imported module: https://s.dusays.com/assets/Explore-RjZk8uN2.js

### Steps to reproduce

1. Go to 'https://s.dusays.com'
3. See error

### The version of Memos you're using.

v0.21.0

### Screenshots or additional context

![image](https://github.com/user-attachments/assets/3d38467b-6615-4a71-99e2-78867e03bc80)

**Comment by boojack** [comment]
Older versions are no longer maintained, so it's recommand to update to the latest version if needed.

**Comment by RoccoSmit** [comment]
Also, cant replicate. URL looks to be working s expected
![image](https://github.com/user-attachments/assets/c701d849-50aa-4726-a457-9cbbe9f5bf01)
