### ISSUE TITLE
docker container automatically exit (159) on platform arm64

### ISSUE THREAD

**Issue by KFCxMcDonalds** [usememos/memos#4042]
### Describe the bug

<img width="1634" alt="iTerm2 2024-10-22 16 39 58" src="https://github.com/user-attachments/assets/bc60e5eb-cb3f-4613-a049-d8842dc82daf">
I'm trying to deploy memos on raspberryPi (raspberryOS), I followed official guidance to run/compose the memos container using:

```bash
docker run -d \
  --init \
  --name memos \
  --publish 5230:5230 \
  --volume ~/.memos/:/var/opt/memos \
  --platform linux/arm64 \
  neosmemo/memos:stable
```

in which I added `--platform` configuration to alllow my docker find correct architecture version (without this, raspberryPi will search for arm64/v8 by default.

But after successfully downloading Image, the container would not run on background, it will automatically exit with code 159.
I found a potential solution on stackoverflow : use `docker run -dit`, but it seems not work.

### Steps to reproduce

1. run command
```bash
docker run -d \
  --init \
  --name memos \
  --publish 5230:5230 \
  --volume ~/.memos/:/var/opt/memos \
  --platform linux/arm64 \
  neosmemo/memos:stable
```
2. docker ps -a
<img width="1019" alt="image" src="https://github.com/user-attachments/assets/b90b401f-a7ce-4810-b1ef-237f5d28f1fe">
we can see that memos exits almost immediatly

### The version of Memos you're using.

stable

**Comment by monkeymatt0** [comment]
Can I gave a look into this?

**Comment by boojack** [comment]
@KFCxMcDonalds Could you share some backend logs of the failed startup? You can get them via `docker logs`.

**Comment by KFCxMcDonalds** [comment]
@boojack hi jack, the problem is that I can't find any log information.

<img width="1372" alt="image" src="https://github.com/user-attachments/assets/5b120f9e-114f-4263-922d-a17bd869f198">

**Comment by DDSNA** [comment]
Hi! This remains a current issue on arm64/v8
