### ISSUE TITLE
Impossible to modify post date

### ISSUE THREAD

**Issue by bansieau** [usememos/memos#4044]
### Describe the bug

When I modify a post, I can’t modify it’s date.
I’d like to archive some of my handy writing notes, and define the date I wrote it.

Handwriting it’s good for a lot of things, but not search or tag contents :)

### Steps to reproduce

1 - Create a post
2 - Modify it
3 - Clic on the date 
4 - Modify it
5 - Click Ok

The date show isn’t modified 

### The version of Memos you're using.

0.22.5 - Linux x86_64

### Screenshots or additional context

local lunch on a Rocky Linux 9 up to date - No docker

**Comment by RoccoSmit** [comment]
Duplicate of https://github.com/usememos/memos/issues/3812

Change should be under the latest docker image tag and should be in the next stable container tag
