### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [usememos/memos#4049]
### Describe the solution you'd like

Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Memos application as shown [here](https://elest.io/open-source/memos). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

Example Button:

[![Deploy on Elestio](https://elest.io/images/logos/deploy-to-elestio-btn.png)](https://elest.io/open-source/memos)

### Type of feature

Documentation

**Comment by boojack** [comment]
> In addition to this, if you are interested we provide partnership opportunities with tools we support by revenue share upon addition of this method in docs.

@kaiwalyakoparkar Since Memos is an open-source and free product, we don't accept advertisements. However, we do offer sponsorship spots where you could display your logo or a deployment button in the sponsorship section of the README or our [demo site](https://demo.usememos.com/).

**Comment by kaiwalyakoparkar** [comment]
@boojack could you please drop me an email at the address in the issue description or let me know yours so we can maybe set up a meeting to discuss this partnership?
