### ISSUE TITLE
文本开头如果是多个tag，那么只有第一个tag生效

### ISSUE THREAD

**Issue by kkzhang** [usememos/memos#405]
### Describe the bug

文本开头如果是多个tag，那么只有第一个tag生效。
比如笔记内容为：

> #tag1 #tag2
> 内容

那么只有#tag1被认成tag

### Steps to reproduce

1. 输入"#tag1 #tag2"
2. 确认

### Expected behavior

同时创建tag1和tag2

### Screenshots or additional context

![image](https://user-images.githubusercontent.com/575834/199654341-58511b7b-eaa9-44ad-9326-5c51d62d7a27.png)

**Comment by Zeng1998** [comment]
你的tag2后面没有空格

Enter `#tag ` to create a tag.
