### ISSUE TITLE
Case in-sensitive search doesn't work for cyrrylic letters

### ISSUE THREAD

**Issue by dobrKot** [usememos/memos#4051]
### Describe the bug

When you create a record with word "text" and trying to search for "TeXt" - everything works correctly, but if you try to do the same with cyrrylics, like "текст" and "ТеКсТ" - search is not working.

### Steps to reproduce

1. Create a note with text "This is some text for example"
2. Search for word "TeXt" - Success
3. Create a note with text "Ось вам текст для прикладу"
4. Search for word "ТеКсТ" - Fail

### The version of Memos you're using.

0.22.5

### Screenshots or additional context

![CleanShot 2024-10-24 at 16 14 31@2x](https://github.com/user-attachments/assets/34a48f08-8a8d-4792-a7c8-b1d24cb9552e)
![CleanShot 2024-10-24 at 16 14 46@2x](https://github.com/user-attachments/assets/98fdf453-b2e9-4b64-9402-604e169f67ec)
![CleanShot 2024-10-24 at 16 15 02@2x](https://github.com/user-attachments/assets/a7e5af04-cf7d-4ba6-a81f-9ca8b50fe547)

**Comment by dobrKot** [comment]
One more addition to the topic, if you will use cyrrylic letters and the letter's case from note and search request will match - search will give you the results. So it's something connected with cyrrylics AND letter's case at the same time.

**Comment by JodhwaniMadhur** [comment]
I don't think this really is a bug! This is more of a Cyrillic letters issue, coz ASCII value of текст is 209 130 208 181 208 186 209 129 209 130 and ASCII Value of TeKct is 208 162 208 181 208 154 209 129 208 162

**Comment by RoccoSmit** [comment]
As @JodhwaniMadhur mentioned, it looks like this is a limitation of the db (by choice). See: https://www.sqlite.org/faq.html#q18

**Comment by dobrKot** [comment]
@RoccoSmit hey, thank for the reponse. Yeah, it seems this is the sqllite limitation.

I have tried to go with postgres and the oficial docker-compose from the website but got same error as here:
https://github.com/usememos/memos/issues/4014

So I had to change doker image from stable to latest to make everything work:

version: "3.0"
services:
  memos:
    image: neosmemo/memos:latest
    restart: always
    depends_on:
      - db
    ports:
      - 5230:5230
    environment:
      - MEMOS_DRIVER=postgres
      - MEMOS_DSN=user=memos password=secret dbname=memosdb host=db sslmode=disable

  db:
    image: postgres:16.1
    restart: unless-stopped
    volumes:
      - "./database:/var/lib/postgresql/data/"
    environment:
      POSTGRES_USER: memos
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: memosdb

All in all after changing DB from Sqlite to Postgress case insensitive search for Unicode started to work. So thank you for the help!
