### ISSUE TITLE
Sometimes, no matter how I format the markdown table, it just won't render. Why is that?

### ISSUE THREAD

**Issue by Mgrsc** [usememos/memos#4053]
### Describe the bug

Are there any specific formatting requirements for markdown tables in memos?
```
| Directory    | Description                                                                           |
|--------------|---------------------------------------------------------------------------------------|
| /            | Root directory, the starting point of the file system.                                |
| /bin         | Essential binary files directory, like `ls`, `cp`, etc.                               |
| /boot        | Bootloader files directory, including kernel images and boot configs.                 |
| /dev         | Device files directory, representing hardware devices like `/dev/sda`.                |
| /etc         | Configuration files directory, storing system-wide configuration files and scripts.   |
| /home        | User home directories, storing personal files and configurations, like `/home/alice`. |
```

### Steps to reproduce

1. create new thoughts
2. input
```
| Directory    | Description                                                                           |
|--------------|---------------------------------------------------------------------------------------|
| /            | Root directory, the starting point of the file system.                                |
| /bin         | Essential binary files directory, like `ls`, `cp`, etc.                               |
| /boot        | Bootloader files directory, including kernel images and boot configs.                 |
| /dev         | Device files directory, representing hardware devices like `/dev/sda`.                |
| /etc         | Configuration files directory, storing system-wide configuration files and scripts.   |
| /home        | User home directories, storing personal files and configurations, like `/home/alice`. |
```
3. save

### The version of Memos you're using.

v0.22.5

**Comment by RoccoSmit** [comment]
Try the blow

```
| Directory    | Description                                                                           |
| -------------- | --------------------------------------------------------------------------------------- |
| /            | Root directory, the starting point of the file system.                                |
| /bin         | Essential binary files directory, like `ls`, `cp`, etc.                               |
| /boot        | Bootloader files directory, including kernel images and boot configs.                 |
| /dev         | Device files directory, representing hardware devices like `/dev/sda`.                |
| /etc         | Configuration files directory, storing system-wide configuration files and scripts.   |
| /home        | User home directories, storing personal files and configurations, like `/home/alice`. |
```

Based on this https://github.com/usememos/memos/issues/3514#issuecomment-2147334370 each line needs a space between the text and the `|` and your header divider did not have the required spaces

**Comment by Mgrsc** [comment]
> Try the blow 尝试以下内容
> 
> ```
> | Directory    | Description                                                                           |
> | -------------- | --------------------------------------------------------------------------------------- |
> | /            | Root directory, the starting point of the file system.                                |
> | /bin         | Essential binary files directory, like `ls`, `cp`, etc.                               |
> | /boot        | Bootloader files directory, including kernel images and boot configs.                 |
> | /dev         | Device files directory, representing hardware devices like `/dev/sda`.                |
> | /etc         | Configuration files directory, storing system-wide configuration files and scripts.   |
> | /home        | User home directories, storing personal files and configurations, like `/home/alice`. |
> ```
> 
> Based on this [#3514 (comment)](https://github.com/usememos/memos/issues/3514#issuecomment-2147334370) each line needs a space between the text and the `|` and your header divider did not have the required spaces基于此 [#3514 (comment)](https://github.com/usememos/memos/issues/3514#issuecomment-2147334370) ，每行都需要在文本和 `|` 之间留一个空格，并且您的标题分隔符没有必要的空格

This solves my problem, but I still think memos should be more flexible with this kind of grammar.

**Comment by tianzhich** [comment]
Yes, this strict mode is too unfriendly and makes it difficult to distinguish with the naked eye.

**Comment by tianzhich** [comment]
I have an example:

```markdown
| 名称              | 施肥次数 | 补铁次数 | 生根粉次数 |
| ------------ | -------- | -------- | -------- | 
| 柠檬｜柠檬树           | ✅ 6.8          |       |        |        
| 松松｜香松               | ✅ 6.8          |        |        |
| 多多｜橡皮树           | ✅ 6.8          |       |        |
| 神龟｜龟背竹           | ✅ 6.8          |         |         |
| 金龟｜洒金龟背竹    | ✅ 6.8          |         |         |
| 旺旺｜花叶络石        | ✅ 6.8          |        |        |
| 小青｜青白玉吊兰    | ✅ 6.8          |       |        |
| 小文｜文竹               | ✅ 6.8          |        |        |
| 粉红｜粉红合果芋     | ✅ 6.17       |        |        |
| 小粉红｜粉红合果芋  | ✅ 6.17       |        |        |
| 牛奶｜牛奶合果芋     | ✅ 6.8         |        |        |
| 小鸭｜鸭掌木            | ✅ 6.17         |       |        |
| 花花公主｜粉掌        | ✅ 6.17         |        |        |
| 小北｜白掌               | ✅ 6.17         |        |        |
| 小奥｜红掌               | ✅ 6.17         |       |        |
| 四叶｜巴西木           | ✅ 6.8           |       |        |
| 网网｜网纹草           | ✅ 6.8           |        |        |
| 小晶｜冷水花           | ✅ 6.8           |        |        |
| 水煮鱼｜绿萝           | ✅ 6.8           |       |        |
| 麻辣香锅｜绿萝       | ✅ 6.8           |       |        |
```

| 名称              | 施肥次数 | 补铁次数 | 生根粉次数 |
| ------------ | -------- | -------- | -------- | 
| 柠檬｜柠檬树           | ✅ 6.8          |       |        |        
| 松松｜香松               | ✅ 6.8          |        |        |
| 多多｜橡皮树           | ✅ 6.8          |       |        |
| 神龟｜龟背竹           | ✅ 6.8          |         |         |
| 金龟｜洒金龟背竹    | ✅ 6.8          |         |         |
| 旺旺｜花叶络石        | ✅ 6.8          |        |        |
| 小青｜青白玉吊兰    | ✅ 6.8          |       |        |
| 小文｜文竹               | ✅ 6.8          |        |        |
| 粉红｜粉红合果芋     | ✅ 6.17       |        |        |
| 小粉红｜粉红合果芋  | ✅ 6.17       |        |        |
| 牛奶｜牛奶合果芋     | ✅ 6.8         |        |        |
| 小鸭｜鸭掌木            | ✅ 6.17         |       |        |
| 花花公主｜粉掌        | ✅ 6.17         |        |        |
| 小北｜白掌               | ✅ 6.17         |        |        |
| 小奥｜红掌               | ✅ 6.17         |       |        |
| 四叶｜巴西木           | ✅ 6.8           |       |        |
| 网网｜网纹草           | ✅ 6.8           |        |        |
| 小晶｜冷水花           | ✅ 6.8           |        |        |
| 水煮鱼｜绿萝           | ✅ 6.8           |       |        |
| 麻辣香锅｜绿萝       | ✅ 6.8           |       |        |

I really can't find any mistakes; I've also added a space on both sides of each cell.
