### ISSUE TITLE
Improve the mobile UI

### ISSUE THREAD

**Issue by ti777777** [usememos/memos#4056]
### Describe the solution you'd like

I would suggest using a bottom sheet component to improve the mobile interface, including map selection and memo actions.

### Type of feature

User Interface (UI)

### Additional context

Reference:

[react-modal-sheet](https://github.com/Temzasse/react-modal-sheet)
[react-native-bottom-sheet](https://github.com/gorhom/react-native-bottom-sheet)
[vue-bottom-sheet](https://bs.vaban.ru/)
[react-spring-bottom-sheet-example](https://react-spring.bottom-sheet.dev/fixtures/simple)

**Comment by Oudwins** [comment]
Personally I would want the input for a new memo to be at the bottom of the screen on mobile collapsed so it showed like a small text area/input then on click on the input it should expand to show the entire thing

**Comment by Oudwins** [comment]
This got closed. Is there no plans to implement this? Would it be welcomed as a contribution?
