### ISSUE TITLE
api/v1/memos can not return private data, v0.23.0

### ISSUE THREAD

**Issue by cambrian07** [usememos/memos#4057]
### Describe the bug

I just update my memos container to v0.23.0,
then I found that api/v1/memos interface can not return the private data, only returns the public data.

### Steps to reproduce

1. update to the latest version 0.23.0
2. get data through api/v1/memos
3. returns empty list

### The version of Memos you're using.

v0.23.0

**Comment by RoccoSmit** [comment]
You need to add the creator id to see the private memos. You can do this by adding a filter to the url as a query string param

`?filter=creator=='users/{id}'`

**Comment by cambrian07** [comment]
> You need to add the creator id to see their private memos. You can do this by adding a filter to the url as a query string param
> 
> `?filter=creator=='users/{id}'`

Got it, thanks.
Is this a new feature?

**Comment by RoccoSmit** [comment]
I believe this was implemented recently
https://github.com/usememos/memos/commit/b4d72e334993c372ec1567362b8f1f75a9f77122

**Comment by tianzhich** [comment]
It seems that I still need to add the creator id even for my own private memos.
