### ISSUE TITLE
Mermaid Diagrams causing "syntax error in text"

### ISSUE THREAD

**Issue by blafusel** [usememos/memos#4059]
### Describe the bug

I am seeing a **Syntax error in text. mermaid version 11.2.1** when trying to create a simple mermaid diagram.

### Steps to reproduce

Create a simple mermaid diagram:

```
mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

### The version of Memos you're using.

v0.23.0

### Screenshots or additional context

![image](https://github.com/user-attachments/assets/d56ea601-533d-419d-9e49-59b07b89f773)

**Comment by RoccoSmit** [comment]
Unable to replicate in the latest version. Note: your example is missing the ```s at the start and end. See https://www.usememos.com/docs/getting-started/content-syntax#rendering-mermaid-diagrams

e.g. memo text
![image](https://github.com/user-attachments/assets/0845e5b1-2054-44cc-ab2b-02f5739ee818)

e.g. diagram
![image](https://github.com/user-attachments/assets/ab0f6d81-e96c-45da-9273-65505a9c9af2)

**Comment by blafusel** [comment]
Strange. I am running v23.0 in a docker.

Here what I see:

<img width="743" alt="Screenshot 2024-11-01 at 10 29 22 PM" src="https://github.com/user-attachments/assets/2c28c2d9-2fe4-49b4-9d88-8bb0b316e3d2">
<img width="745" alt="Screenshot 2024-11-01 at 10 29 32 PM" src="https://github.com/user-attachments/assets/bdedff88-26fe-4a0a-a482-2ea6c1792b2a">
<img width="178" alt="Screenshot 2024-11-01 at 10 29 43 PM" src="https://github.com/user-attachments/assets/ea11377e-3c01-4032-837e-48aaab0af376">

**Comment by RoccoSmit** [comment]
What browser/os are you using?

**Comment by RoccoSmit** [comment]
I was able to replicate with 2 different instances of v.0.23.0. One working one not working. Can you try pull the latest docker image with the `latest` tag.

**Comment by blafusel** [comment]
I am seeing the same problem with Edge, Safari, Chrome and Chromium. 

I am using the latest version of Memos from here: https://registry.hub.docker.com/r/neosmemo/memos/

Should I use a different registry?

**Comment by RoccoSmit** [comment]
I think something is happening during the build process. Local development works without any issues but when the website is run via docker the browser shows the following error when a mermaid note is added

![image](https://github.com/user-attachments/assets/e7c867af-0495-4704-a5b9-350e0ae82a17)

**Comment by trancethehuman** [comment]
<img width="591" alt="Image" src="https://github.com/user-attachments/assets/2a6c5be9-fb62-4fc2-8f02-d3e5a804a59b" />

Seeing this in 11.4.1
