### ISSUE TITLE
A difference in text labels length in various languages breaks UI

### ISSUE THREAD

**Issue by neuro18** [usememos/memos#4068]
### Describe the bug

The meaning of phrases in one language is sometimes impossible to convey in the same length of text in another language.

It may be worth using uniformly understood symbols (iconography) in the UI where possible instead of text labels. Much like in popular messengers.

For example, "visibility of memos" English vs Russian text labels in the current version are:
- "Private" vs "Видно только вам"
- "Workspace" vs "Видно только пользователям"
- "Public" vs "Видно всем".

This applies to many other text labels in various languages and usually manifests itself in the UI mobile mode.

**In this particular case, I'm asking you to replace russian labels for their shorten versions, which still convey the same meaning considering the context:**

- "Private" = "Только вы"
- "Workspace" = "Участники"
- "Public" = "Все"

### Steps to reproduce

1. Open Memos UI in smartphone browser (in default mobile mode).
2. Set Russian (or Ukrainian) language for the UI.
3. Create or edit a memo, switch between different memo visibility options.
4. Observe how "Memo visibility" drop-down list, "Cancel" and  "Save" buttons extend beyond the memo boundaries.

### The version of Memos you're using.

v0.22.5

### Screenshots or additional context

Mobile view, portrait orientation.

Example 1: Creating new memo

![Screenshot_20241030_002121](https://github.com/user-attachments/assets/dd231e1f-c698-48f5-90cb-9a6051913cef)

Example 2: Editing existing memo

![Screenshot_20241030_002304](https://github.com/user-attachments/assets/ba76b577-6865-415c-a3db-662f393e2eec)

**Comment by neuro18** [comment]
In addition, I've looked at the content of a source file with all Russian labels. Many of them were translated clearly without minding there effect on UI, are overly complicated, can be significantly shorten.

The problem for the translator person is that they actually have to see each of these text labels in the UI with there own eyes, not just simply translate labels in the file. And only then come up with something fitting the allotted space in UI elements, and without corruption of the original text meaning. It's a mind boggling task for an enthusiast.

**Comment by neuro18** [comment]
Another option is fixed UI elements size, truncated text to display. In a case of dropdown list, for example, text can be displayed in full when the list is open.

I don't know. Is there a more universal solution, other then iconography?

**Comment by JodhwaniMadhur** [comment]
I would like to take this up

**Comment by neuro18** [comment]
It still needs to be in one line.

Mobile mode operates in smaller screen resolution. Control elements width needs to be defined in percents of memo canvas (to be scaled with it), but with max width values defined, so they all fit in one line within memo canvas.

Imagine this line with control elements as a table:

`| drop-down list         | cancel + save |`

Table itself scales with memo canvas. But rows (elements here) in it scales with the table:

`|70%              |rest %|`.

Cancel+save raw aligned to the right,  drop-down list - to the left. If text in the list is short (producing a small sized ui element), then there will be a free space between the list and buttons. If it's long, then list ui element will occupy it's entire raw, will be close to the button raw, displayed text will be truncated.

It's really an easy thing to implement, done with tables in HTML design.

**Comment by neuro18** [comment]
Tables inside tables, if needed.

**Comment by neuro18** [comment]
Cancel+Save row is always displayed in full - buttons text takes priority, the rest space dedicated to the row with list ui element.

**Comment by neuro18** [comment]
So the proper table might be

`|rest % goes to the list|display here cancel + save buttons|`

Sorry for the lousy explanation, not my native language, difficult to convey thoughts within my limited vocabulary.

**Comment by boojack** [comment]
@johnnyjoygh I started with a simple implementation to prevent UI broken https://github.com/usememos/memos/commit/4b28dfddb673d17ae5c282206bc6d3af8733ffa3

<img width="360" alt="image" src="https://github.com/user-attachments/assets/8874a2b4-6b1a-43c5-b89e-f40806acbf93">

**Comment by JodhwaniMadhur** [comment]
@boojack why don't we truncate the dropdown to a fixed size and the save button as well? The dropdown then only shows all the options in full when opened like i just suggested up above?

**Comment by boojack** [comment]
@JodhwaniMadhur In the screenshot you provided, the text isn't truncated like `This is an content but trunc...`, it's just not displayed forcibly. And the buttons are split into two lines, which doesn't look like a better solution.

**Comment by JodhwaniMadhur** [comment]
@boojack solved this! 

I don't think we need this anymore.
