### ISSUE TITLE
Add a sorting option: sort by latest commented time

### ISSUE THREAD

**Issue by resona07** [usememos/memos#4070]
We have got 2 sorting options for now: by updated time and by created time. It would be great to have a 3rd option of sorting by latest commented time. This feature would open the possibility to take notes in a thread-like way by commenting to main topics.

**Comment by harishnanthan** [comment]
When i see there are only one options is avaiable. Where can i see this sorting options.
<img width="326" alt="image" src="https://github.com/user-attachments/assets/42d004c6-60d3-47f3-88ca-8c06443d245f">

**Comment by resona07** [comment]
> When i see there are only one options is avaiable. Where can i see this sorting options.当我看到只有一个选项可用时。我在哪里可以看到这个排序选项。 <img alt="image" width="326" src="https://private-user-images.githubusercontent.com/58702895/381801066-42d004c6-60d3-47f3-88ca-8c06443d245f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNzg1MzQsIm5iZiI6MTczMDM3ODIzNCwicGF0aCI6Ii81ODcwMjg5NS8zODE4MDEwNjYtNDJkMDA0YzYtNjBkMy00N2YzLTg4Y2EtOGMwNjQ0M2QyNDVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDEyMzcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMThmMjc3ZjMyMDM3YWYyMmVhODY2NDI3YmM5NDUyNjFiZTc2Zjk0MzA2ZmY0NWU1Y2VlM2IzMmQ0YjgxNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5gGhaR6UGYDlCZOAy97ZRgoDGFtuG7dPeRKRWF84xj8">

you can toggle the "sort by last updated time" option in Settings > Preference > Memo
