### ISSUE TITLE
how about translate "Explore" to "浏览/瀏覽“ in Chinese

### ISSUE THREAD

**Issue by Brian099** [usememos/memos#4077]
### Describe the solution you'd like

change "探索” to "浏览“， means view all posts

### Type of feature

User Experience (UX)

**Comment by ElTopo** [comment]
I personally prefer "发现" for "Explore".

**Comment by JodhwaniMadhur** [comment]
I will do this as well.

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/f5a0827a3f027c911efdcfe734fe3d43f3691391
