### ISSUE TITLE
The delete icon will hide if the webhook link is too long

### ISSUE THREAD

**Issue by Brian099** [usememos/memos#4078]
### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/f97956b1-855c-4121-add7-c8e8371fc4a3)
![image](https://github.com/user-attachments/assets/79d18924-a933-41ca-973a-88bc00cb967e)
How about keep it display on the right?

### Type of feature

User Interface (UI)

**Comment by JodhwaniMadhur** [comment]
Again, I would like to give this a shot! Will try the truncate thing here as well!

**Comment by JodhwaniMadhur** [comment]
I hope this is acceptable?


https://github.com/user-attachments/assets/4359a31e-7bc5-4b53-8c67-8f93c15b572a

**Comment by JodhwaniMadhur** [comment]
ok, will raise the MR.

**Comment by JodhwaniMadhur** [comment]
MR Link: #4145

**Comment by JodhwaniMadhur** [comment]
this is merged, we can close this.
