### ISSUE TITLE
How should this be filled out? 

### ISSUE THREAD

**Issue by star2k** [usememos/memos#4079]
### Describe the bug

![photo_2024-11-01_17-34-13](https://github.com/user-attachments/assets/2d22fe5c-e19b-441b-aefe-79e47a8296b4)
Please help me translate: What does this mean, it cannot be saved without adding, just add one casually, it seems inappropriate, it feels like it is used for adding emoji packs, such as smiling face, thumbs up, on fire and so on. How should I fill it out?

In addition some Simplified Chinese has not been sinicized yet.;

### Steps to reproduce

How should this be filled out? 

### The version of Memos you're using.

0.23

### Screenshots or additional context

How should this be filled out?

**Comment by RoccoSmit** [comment]
Have a look at this comment for a list of default reactions to add
https://github.com/usememos/memos/issues/4060#issuecomment-2439878664
