### ISSUE TITLE
Every time I turn on the computer the next day, I can't log into my account

### ISSUE THREAD

**Issue by HuangZhibin9** [usememos/memos#4097]
### Describe the bug

Every time I finish registering an account, when I try to log in again the next day, it always shows that the account or password does not match. At first, I thought I had remembered the password incorrectly, but later I re-registered and noted down the password. I was able to log in on the same day, but the next day it again showed a login failure.

### Steps to reproduce

1、Register an account.
2、Can log in successfully on the same day.
3、But the next day it shows "unmatched username and password."

### The version of Memos you're using.

v0.22.5

**Comment by BosNaufal** [comment]
hi @HuangZhibin9  It would be great if you could provide some additional information, such as:
- OS details
- How you run the Memos instance, e.g. via Docker or other options?
- What's your configuration?
- etc.
