### ISSUE TITLE
可以添加目录或分组功能吗？

### ISSUE THREAD

**Issue by cethink** [usememos/memos#4101]
### Describe the solution you'd like

可以选择分组录入，不同分组不同主题或场景

### Type of feature

User Interface (UI)

**Comment by cethink** [comment]
You can choose to enter in groups, and different groups are different topics or scenes.

**Comment by RoccoSmit** [comment]
New instance of https://github.com/usememos/memos/issues/3984

**Comment by cethink** [comment]
就是像笔记本一样分类，可以分类录入，也可以分类查看。用tag总是不习惯，tag更像是从一堆无序的memos中查找，类似于搜索功能，而分类就更结构化，可以只关注一个分类主题，在里面录入相关内容，也可以添加tag，tag就比较随意了，想到什么添加什么，不用过多思考。这是一个习惯问题。
It is like a notebook that can be classified and entered and viewed. I am not used to using tags. Tags are more like searching from a pile of disordered memos, similar to the search function, while categories are more structured. You can focus on a classification theme and enter relevant content in it. You can also add tags. Tags are more casual. You can add whatever you think of without thinking too much. This is a matter of habit.
