### ISSUE TITLE
[Bug] Can not get resources when listing memos

### ISSUE THREAD

**Issue by YiHui-Liu** [usememos/memos#4104]
### Describe the bug

URL: [https://memos.foolishfox.cn/api/v1/memos?pageSIze=10&filter=creator==%27users/1%27&&visibilities==[%27PUBLIC%27]](https://memos.foolishfox.cn/api/v1/memos?pageSIze=10&filter=creator==%27users/1%27&&visibilities==[%27PUBLIC%27])

there is no resource in list. but i can get resource list by [https://memos.foolishfox.cn/api/v1/memos/91/resources](https://memos.foolishfox.cn/api/v1/memos/91/resources)

### Steps to reproduce

as above

### The version of Memos you're using.

v0.23.0

**Comment by zhaohao** [comment]
v0.23.0通过api获取的json文件中"nodes": [],  "resources": [],  "snippet": "" 三个都为空。v0.22.5中有对应信息。主要是由于resources项的缺失，靠外部工具解析json文件没办法获取包含图片在内的资源文件的信息了。不知为何做此修改？

**Comment by YiHui-Liu** [comment]
> v0.23.0通过api获取的json文件中"nodes": [], "resources": [], "snippet": "" 三个都为空。v0.22.5中有对应信息。主要是由于resources项的缺失，靠外部工具解析json文件没办法获取包含图片在内的资源文件的信息了。不知为何做此修改？

Yes, it's a good project, but the API changes too frequently and there is no complete documentation.

**Comment by jkjoy** [comment]
频繁改动API不是个好的做法

**Comment by YiHui-Liu** [comment]
because of the API changes, the Android APP cannot obtain resources and display them normally.

**Comment by zhaohao** [comment]
根据https://github.com/usememos/memos/issues/4179的官方回复，添加 &view=MEMO_VIEW_FULL参数可以像旧版本一样获取完整信息。

https://demo.usememos.com/api/v1/memos?pageSize=100&filter=visibilities == ['PUBLIC'] && creator == 'users/1'&view=MEMO_VIEW_FULL

@YiHui-Liu  @jkjoy

**Comment by jkjoy** [comment]
> 根据#4179 的官方回复，添加 &view=MEMO_VIEW_FULL参数可以像旧版本一样获取完整信息。
> 
> https://demo.usememos.com/api/v1/memos?pageSize=100&filter=visibilities == ['PUBLIC'] && creator == 'users/1'&view=MEMO_VIEW_FULL
> 
> @YiHui-Liu @jkjoy

收到

**Comment by YiHui-Liu** [comment]
> '&view=MEMO_VIEW_FULL

好的，成功解决了。
OK, this helps me solve the issue
