### ISSUE TITLE
Tag management

### ISSUE THREAD

**Issue by fivestone** [usememos/memos#4108]
### Describe the solution you'd like

1. A separate page in the menu to show all the tags.
2. It's optional to control whether to show tags in the home page. Because some tags I don't want to see on the page all the time, such as my ex's name ^^

### Type of feature

User Interface (UI)

**Comment by RoccoSmit** [comment]
As an initial way of "hiding" tags you could updates the tags you don't want to see to be nested and change to tree view. This way you will need to click into the top level tag to see the tags you don't want to see regularly

E.g. 
new tag structure 
![Screenshot_20241107-184212](https://github.com/user-attachments/assets/da641ec9-170e-404c-886c-21e397b02189)

Tags tree view
![Screenshot_20241107-184419](https://github.com/user-attachments/assets/010d4b37-5e0c-4f1d-9182-dd04a8b06ef6)

**Comment by resona07** [comment]
> > A separate page in the menu to show all the tags.
> 
> Sounds like a good idea.
> 
> > Because some tags I don't want to see on the page all the time, such as my ex's name ^^
> 
> So, what’s the reason behind creating this tag?

She was perhaps not ex when those memos were taken.
