### ISSUE TITLE
Allow user to go to next image

### ISSUE THREAD

**Issue by rohitpaul** [usememos/memos#4109]
### Describe the solution you'd like

It would be fantastic if the user could navigate to the next photo without having to close the current one. 

### Type of feature

User Experience (UX)

### Additional context

I post numerous pictures, which makes it easier for users to navigate through them.

**Comment by RoccoSmit** [comment]
You can click on the empty spaces next to the image to navigate to the previous/next image (will need to look into why there are no navigation buttons).

Note: when you are at the first image and navigate left you are taken out of the image viewer and the same when you are at the last image and navigate right
![image](https://github.com/user-attachments/assets/dba347e6-1541-4160-af6b-3fdf19966895)
