### ISSUE TITLE
To be able to see previous months calendar

### ISSUE THREAD

**Issue by Greatz08** [usememos/memos#4113]
### Describe the solution you'd like

Right now it just shows current month calendar only. So if in UI any small button can be added to switch the calendar month to whatever we want so that we can see all the the days of a month on which we did add memos and can filter out those too when we click on those days.

### Type of feature

User Interface (UI)

**Comment by RoccoSmit** [comment]
In older versions you need to hover over the calendar to see the menu that allows for you to change the months
![image](https://github.com/user-attachments/assets/be0793a7-e645-4b08-a99f-27a9ed1f1b3e)


In the latest version (0.23 pre release) the month navigation buttons are visible by default
![image](https://github.com/user-attachments/assets/a292eb5d-3969-4d22-9b7e-e6f2af165ddd)
