### ISSUE TITLE
After updating the version 0.23, it cannot be loaded normally

### ISSUE THREAD

**Issue by voctot** [usememos/memos#4114]
### Describe the bug

Update to version 0.23 Click to explore the menu。Unable to obtain an error content
：Uncaught (in promise) ClientError: /memos.api.v1.MemoService/ListMemos INTERNAL: runtime error: invalid memory address or nil pointer dereference.

### Steps to reproduce

1、Enter the homepage
2、Click the exploration menu

### The version of Memos you're using.

Version: v0.23.0

### Screenshots or additional context

![image](https://github.com/user-attachments/assets/0218315f-7b0a-42db-a836-8329f6af1354)

**Comment by RoccoSmit** [comment]
What version did you update from?
Are you able to send the server logs?

**Comment by voctot** [comment]
> What version did you update from? Are you able to send the server logs?

I updated 0.23 from version 0.22.2。
This is my log:
`2024/11/09 07:13:16 ERROR server error method=/memos.api.v1.MemoService/ListMemos error="rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference"
2024/11/09 07:14:46 INFO OK method=/memos.api.v1.InboxService/ListInboxes`
