### ISSUE TITLE
One-click export and backup function

### ISSUE THREAD

**Issue by DocksToBox** [usememos/memos#4117]
### Describe the solution you'd like

One-click export and backup function to facilitate migration, there are times when the server has stored a lot of things, but when I want to upgrade and migrate to a larger machine, I can not tell how to perfectly migrate all the pictures and memos, so I hope that there can be a one-click export all the contents and one-click import all the contents of the function!

### Type of feature

User Experience (UX)

**Comment by RoccoSmit** [comment]
Backups its not something that is being considered at this time, See [here](https://github.com/usememos/memos/issues/3802#issuecomment-2293215545)

For migrating to a different server, your db, assets and thumbnail images all live in the folder you specified when creating your docker container. 
![image](https://github.com/user-attachments/assets/251d6f68-82d7-4fb0-98af-3b1ac8510482)
If you migrate this folder over to your new server and map your new docker container to the migrated folder your site should start up as per usual. (Remember to back up this folder beforehand just in case)
