### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by eddowding** [usememos/memos#4123]
### Describe the solution you'd like

Great to have keyboard shortcuts:
`c` or `n` = new note
`/` or `f` or `s` = search
`/command` inside text area to trigger menu of markdown options. 

### Type of feature

User Experience (UX)

**Comment by anileshwar12** [comment]
@eddowding I want to work on this issue, can you assign me

**Comment by CaptainConsternant** [comment]
This is a great idea.

May I also suggest a shortcut to edit an existing note ?
This would probably require to assign UP/DOWN as a way to select notes.

And I would also suggest to use a well known mapping (vim, gmail or others)

Thanks!
