### ISSUE TITLE
Insert the picture into the text paragraph

### ISSUE THREAD

**Issue by webyang-male** [usememos/memos#4130]
### Describe the solution you'd like

May I ask if it is not possible to insert pictures in the published articles for this project, and the pictures can only be attached at the end?

### Type of feature

User Experience (UX)

### Additional context

I think this requirement is quite important and it can be set as optional. Because I believe there are still users who would like to use this project as a blog, although it is more suitable for fragmented information.

**Comment by RoccoSmit** [comment]
Previous instance of this request for reference (https://github.com/orgs/usememos/discussions/3850)

**Comment by webyang-male** [comment]
> Previous instance of this request for reference (https://github.com/orgs/usememos/discussions/3850)此请求的上一个实例以供参考 （https://github.com/orgs/usememos/discussions/3850）

Thank you very much. This issue can be closed now. Or you can also mark it as a classic question and pin it to the top.
