### ISSUE TITLE
Clicking done on checkboxes on a long memo keeps auto minimizing the memo

### ISSUE THREAD

**Issue by ocean-haiyang** [usememos/memos#4133]
### Describe the bug

Have a long memo where you have to click show more to read it. Click any checkbox to finish it. The memos minimizing forces the user to click show more again. 

### Steps to reproduce

Have a long memo where you have to click show more to read it. 
Click any checkbox to finish it. 
The memos minimizing forces the user to click show more again. 

### The version of Memos you're using.

22.5

**Comment by RoccoSmit** [comment]
Similar to https://github.com/usememos/memos/issues/4110

**Comment by boojack** [comment]
duplicated issue
