### ISSUE TITLE
picture thumbnail broken

### ISSUE THREAD

**Issue by Luftwaft** [usememos/memos#4135]
### Describe the bug

![image](https://github.com/user-attachments/assets/08df4b4e-c3c8-4ea1-802b-492fd8a729a2)
Version: v0.23.0
some of the pictures thumbnail dont show correctly

### Steps to reproduce

no steps

### The version of Memos you're using.

Version: v0.23.0

**Comment by RoccoSmit** [comment]
Are these still broken after a page refresh?

**Comment by Luftwaft** [comment]
yes，tried refreshing and clearing cookies，and switch to other browser，it just didnt work

**Comment by RoccoSmit** [comment]
Couple questions:
- if you press `F12` are there any errors showing
- are you storing your images in a db, local storage or s3
- if you right click on the image and `inspect`, can you copy the image url and paste it in a new tab and remove the `?thumbnail=true` to see if it loads
- Are you able to reupload the image and share the docker container logs to show any potential errors

**Comment by Luftwaft** [comment]
1、after f12，there're two in concle like the image below,but no network error
![image](https://github.com/user-attachments/assets/0c6edaed-41ca-4d89-b64d-3486a6b6f7cf)
2、image are stored in **db**
3、it loads by full size
4、reupload one of the images,it works well on web.here the container log :
```2024/11/20 02:25:07 INFO OK method=/memos.api.v1.MemoService/CreateMemo
2024/11/20 02:25:08 INFO OK method=/memos.api.v1.MemoService/ListMemos
2024/11/20 02:24:54 INFO OK method=/memos.api.v1.ResourceService/GetResourceBinary
2024/11/20 02:24:46 INFO OK method=/memos.api.v1.ResourceService/CreateResource
2024/11/20 02:24:34 INFO OK method=/memos.api.v1.MemoService/ListMemos
2024/11/20 02:24:34 INFO OK method=/memos.api.v1.ResourceService/GetResourceBinary
2024/11/20 02:24:34 INFO OK method=/memos.api.v1.UserService/GetUserSetting
2024/11/20 02:24:34 INFO OK method=/memos.api.v1.WorkspaceSettingService/GetWorkspaceSetting
2024/11/20 02:24:07 INFO OK method=/memos.api.v1.InboxService/ListInboxes
2024/11/20 02:24:07 INFO OK method=/memos.api.v1.MemoService/ListMemos
2024/11/20 02:24:33 INFO OK method=/memos.api.v1.WorkspaceService/GetWorkspaceProfile
2024/11/20 02:24:34 INFO OK method=/memos.api.v1.AuthService/GetAuthStatus```

**Comment by RoccoSmit** [comment]
It looks like something went wrong while creating the thumbnails. You can delete the thumbnails from the `.thumbnail_cache` folder that is located in the folder you specified while creating your docker container. The thumbnail will then get regenerated when you view the image again.

![image](https://github.com/user-attachments/assets/3afe83d6-6b40-454d-a041-5be625824248)

The thumbnail name aligns with the original image id
e.g.
A image with the path `/file/resources/4/image.png?thumbnail=true` will have a matching thumbnail named `4.png`

**Comment by Luftwaft** [comment]
yes，it works，thanks
