### ISSUE TITLE
Allow mentioning tags without categorizing memos

### ISSUE THREAD

**Issue by IlanOu** [usememos/memos#4138]
### Describe the solution you'd like

Hey there! I've got an idea that could make Memos even more flexible. It'd be great if we could mention tags in our memos without automatically categorizing the memo with that tag. Here's what I'm thinking:

1. Maybe we could use a different syntax, like double brackets [[tag]], to mention a tag without applying it.

2. These mentioned tags could look a bit different from regular tags, so we can easily tell them apart.

3. We'd still be able to click on these mentioned tags to see all the memos actually using that tag.

4. When searching or filtering, these mentions wouldn't count as actual tags for the memo.

This would be super helpful when we want to talk about a topic or reference another category without messing up our organization. It'd give us more freedom in how we use tags while keeping things tidy.

### Type of feature

User Experience (UX)

**Comment by RoccoSmit** [comment]
For some context on similar requests
https://github.com/orgs/usememos/discussions/3999
https://github.com/orgs/usememos/discussions/3809
