### ISSUE TITLE
Let users choose whether to turn on the folding function.

### ISSUE THREAD

**Issue by ZDY321** [usememos/memos#4142]
### Describe the solution you'd like

I hope that like the old version, users can choose whether to enable the folding function. Some notes are very long and need to be folded.

### Type of feature

User Interface (UI)

**Comment by RoccoSmit** [comment]
Are you referring to `settings` -> `memos` -> `enable auto compact`

**Comment by ZDY321** [comment]
> Are you referring to `settings` -> `memos` -> `enable auto compact`

Yes, it can be set, but it can't be folded back after clicking Show More, and you need to refresh it
