### ISSUE TITLE
how to show the exact time of one memo

### ISSUE THREAD

**Issue by 14cc** [usememos/memos#4146]
### Describe the solution you'd like

Now I can just know the date I post the memo, if I want to see the exact time I have to double click and try to edit that memo, so is there anyway that it can directly show me the exact time

Thx a lot!
<img width="832" alt="iShot_2024-11-24_15 08 55" src="https://github.com/user-attachments/assets/f4e35004-75d4-4041-af7b-09895dc70e1d">

### Type of feature

User Interface (UI)

**Comment by RoccoSmit** [comment]
There is no official way to do this at this time, but see this comment for a workaround
https://github.com/usememos/memos/issues/3817#issuecomment-2300344224
