### ISSUE TITLE
docker log ERROR

### ISSUE THREAD

**Issue by zhensolid** [usememos/memos#4156]
### Describe the bug

2024/11/29 00:08:47 ERROR: Failed to extract ServerMetadata from context

### Steps to reproduce

[
![123](https://github.com/user-attachments/assets/313184a5-6fb8-4d90-9442-18e68c0c74fb)
](url)

### The version of Memos you're using.

v0.1.0

**Comment by zhensolid** [comment]
Version: v0.23.0

**Comment by tofch** [comment]
same here. 
the browser:
`Response stream closed without gRPC status. This may indicate a misconfigured CORS policy on the server: Access-Control-Expose-Headers must include "grpc-status" and "grpc-message".`
