### ISSUE TITLE
Just A Question: How can we fetch all tags from API now?

### ISSUE THREAD

**Issue by RyoJerryYu** [usememos/memos#4161]
### Describe the solution you'd like

I found that `MemoService.ListMemoTags` was removed when d11e7a3a9a6 , which API we used to list tags from Memos Server. (Not only myself, but also I found some famous intergration such as  https://github.com/lmm214/memos-bber also use this API.) 

So, since that commit do not related to any PR , I can't find why that API was removed , and how to use alternative method to fetch all tags.

Anyone can tell me, how can we fetch all tags from API now?

> It's not a feature request. But there is no any Issue template for asking question...

### Type of feature

API

**Comment by RoccoSmit** [comment]
From the commit, `ListMemoProperties`, `ListMemoTags` and `ListMemos` look to be wrappers around `s.Store.ListMemos(ctx, memoFind)` and these functionalities were consolidated into `ListMemos`

e.g. of how the latest version gets tags 
url: `/api/v1/memos?filter=creator == 'users/1'&view=MEMO_VIEW_METADATA_ONLY`
Schema: `memos[index].property.tags`

**Comment by RyoJerryYu** [comment]
> From the commit, `ListMemoProperties`, `ListMemoTags` and `ListMemos` look to be wrappers around `s.Store.ListMemos(ctx, memoFind)` and these functionalities were consolidated into `ListMemos`
> 
> e.g. of how the latest version gets tags url: `/api/v1/memos?filter=creator == 'users/1'&view=MEMO_VIEW_METADATA_ONLY` Schema: `memos[index].property.tags`

Good. Sounds reasonable. 

So, with the new API, clients needs to implement counting tags by itself, since `MemoService.ListMemos` do not return the amount for each tags. Right?

**Comment by RoccoSmit** [comment]
Yea, that functionality has been moved to the FE
https://github.com/usememos/memos/blob/2aa3795e501cb7940fb64ba63e9c82faf48c72a6/web/src/store/v1/memoMetadata.ts#L54-L68

**Comment by RyoJerryYu** [comment]
> Yea, that functionality has been moved to the FE
> 
> https://github.com/usememos/memos/blob/2aa3795e501cb7940fb64ba63e9c82faf48c72a6/web/src/store/v1/memoMetadata.ts#L54-L68

Nice. Now all my questions are clear. Thanks!

BTW, though I understand this project is still under v0 and occasional breaking changes are expected, I hope the API backward compatibility of this project can be better. There are so many integration tools using this project’s API...

**Comment by RoccoSmit** [comment]
FYI, I believe a recent commit (https://github.com/usememos/memos/pull/4229) will move `tags` out of the `property` node and onto the `memo` node.

`memo.property.tags` -> `memo.tags`

**Comment by intmian** [comment]
@RoccoSmit 我也遇到了和你一样的问题，请问下你是如何解决的呢，非常感谢
官方文档上的api /api/v1/memos/-/tags显然失效了
