### ISSUE TITLE
Timed auto-cleaning and disable visitor preview

### ISSUE THREAD

**Issue by psheep303** [usememos/memos#4162]
### Describe the solution you'd like

I'd like to fix the lack of storage space by adjusting the timer to clear the logs in the administrator's settings.
Also, would like to add the ability for visitors to disable viewing of public.

### Type of feature

User Experience (UX)

**Comment by RoccoSmit** [comment]
@psheep303, which logs are you referring to?

Re visitors, as far as I know visitors (not logged in users) can only see public memos, if they disable viewing public memos they would not see anything?

**Comment by psheep303** [comment]
I want only registered users to see public notes.

**Comment by RoccoSmit** [comment]
Notes with `public` or `workspace` should have the same visibility for logged in users so you could use `workspace` instead of `public` and then non logged in users won't be able to see your shared notes

**Comment by psheep303** [comment]
The workspace can be edited by other users. I hope to customize a public function so that visitors cannot see it but other users cannot edit it. I hope to add a private message function.

**Comment by RoccoSmit** [comment]
I haven't looked through code to know exactly what is allowed, but I believe there was a feature added to allow admins to modify workspace memos. Non admins can only view  workspace memos
