### ISSUE TITLE
After successfully deploying with docker-compose, the Telegram bot is not responding

### ISSUE THREAD

**Issue by ZDY321** [usememos/memos#4163]
### Describe the bug

Running successfully without any errors

> Return messages following successful deployment
~~~yaml
✔ Container memogram  Started                                                                               0.6s 
 ✔ Container memeos    Started
~~~

### Steps to reproduce

The contents of my YAML file, and I've verified that the bot token in the .env file is accurate
~~~yaml
services:
  memos:
    image: neosmemo/memos:latest
    container_name: memeos
    hostname: memeos
    ports:
      - "5230:5230"
    volumes:
      - /root/data/docker_data/memos/.memos/:/var/opt/memos
    restart: always
  memogram:
    env_file: .env
    build: ./memogram
    container_name: memogram
~~~

### The version of Memos you're using.

0.23.0

### Screenshots or additional context

Screenshot of the Telegram Bot：
![Snipaste_2024-12-01_18-57-52](https://github.com/user-attachments/assets/1e2fc161-f957-42e1-8904-93477236b182)
---
---
### Operation output：
![Snipaste_2024-12-01_18-58-59](https://github.com/user-attachments/assets/39d1777b-1af7-4e1a-88db-10997ac69572)

**Comment by jkjoy** [comment]
所以 env 的环境变量你配置了吗

**Comment by ZDY321** [comment]
> 所以 env 的环境变量你配置了吗

配置了啊,token替换成自己的
~~~yaml
SERVER_ADDR=dns:localhost:5230
BOT_TOKEN=your_telegram_bot_token
~~~

**Comment by jkjoy** [comment]
> > 所以 env 的环境变量你配置了吗
> 
> 配置了啊,token替换成自己的
> 
> SERVER_ADDR=dns:localhost:5230
> BOT_TOKEN=your_telegram_bot_token

DNS 的地址你设置的是什么呢
