### ISSUE TITLE
无法通过API接口正常获取资源列表

### ISSUE THREAD

**Issue by Yimien** [usememos/memos#4179]
### Describe the bug

在`/api/v1/memos` 返回的数据中，`resources` 和 `nodes` 返回的列表为空，是否考虑在下个版本修复？或者提供新的API接口?

### Steps to reproduce

同上

### The version of Memos you're using.

v0.23

**Comment by quanru** [comment]
> You need to add `view=MEMO_VIEW_FULL` to get all fields of memos.
> 
> https://demo.usememos.com/api/v1/memos?filter=creator%20%3D%3D%20%22users/1%22&view=MEMO_VIEW_FULL

Under 0.24.0, the return of this interface failed. How should I call it?

**Comment by Yimien** [comment]
> > You need to add  to get all fields of memos.`view=MEMO_VIEW_FULL`
> > https://demo.usememos.com/api/v1/memos?filter=creator%20%3D%3D%20%22users/1%22&view=MEMO_VIEW_FULL
> 
> Under 0.24.0, the return of this interface failed. How should I call it?

Take a look at this: https://memos.apidocumentation.com/reference#tag/memoservice/GET/api/v1/memos

**Comment by quanru** [comment]
0.24 The interface parameters have been modified again. Can you give me a new filter example?

filter
Filter is a CEL expression to filter memos. Refer to Shortcut.filter.

oldFilter
[Deprecated] Old filter contains some specific conditions to filter memos. Format: "creator == 'users/{user}' && visibilities == ['PUBLIC', 'PROTECTED']"

**Comment by quanru** [comment]
> > 0.24 The interface parameters have been modified again. Can you give me a new filter example?
> > filter Filter is a CEL expression to filter memos. Refer to Shortcut.filter.
> > oldFilter [Deprecated] Old filter contains some specific conditions to filter memos. Format: "creator == 'users/{user}' && visibilities == ['PUBLIC', 'PROTECTED']"
> 
> What are you trying to do? You don't have to use the 'filter' parameter if you don't want to.

https://github.com/quanru/obsidian-lifeos/issues/92

A plug-in I maintained used this interface. After someone gave feedback and upgraded to 0.24, the following call method reported an error, the interface parameters are as follows:

https://github.com/quanru/obsidian-lifeos/blob/main/src/periodic/DailyRecord.ts#L151

**Comment by Yimien** [comment]
> > > 0.24 The interface parameters have been modified again. Can you give me a new filter example?
> > > filter Filter is a CEL expression to filter memos. Refer to Shortcut.filter.
> > > oldFilter [Deprecated] Old filter contains some specific conditions to filter memos. Format: "creator == 'users/{user}' && visibilities == ['PUBLIC', 'PROTECTED']"
> > 
> > 
> > What are you trying to do? You don't have to use the 'filter' parameter if you don't want to.
> 
> [quanru/obsidian-lifeos#92](https://github.com/quanru/obsidian-lifeos/issues/92)
> 
> A plug-in I maintained used this interface. After someone gave feedback and upgraded to 0.24, the following call method reported an error, the interface parameters are as follows:
> 
> https://github.com/quanru/obsidian-lifeos/blob/main/src/periodic/DailyRecord.ts#L151

I didn't use 'visibilities'. For 'creator', you can use 'parent', and for 'row_status', you can use 'state'.
