### ISSUE TITLE
上传到腾讯云cos报错

### ISSUE THREAD

**Issue by smallxi** [usememos/memos#4182]
### Describe the bug

Response stream closed without gRPC status. This may indicate a misconfigured CORS policy on the server: Access-Control-Expose-Headers must include "grpc-status" and "grpc-message".

### Steps to reproduce

有些图片可以正常上传，有些又不能

### The version of Memos you're using.

22.5

**Comment by smallxi** [comment]
用的nginx反代，是这个的原因吗，怎么才能解决呢

**Comment by yuboabc** [comment]
同样的一个文件. 我在家里的联通宽带上, 死活上传不上去. 任何S3存储都不能正常上传. 然后, 换到公司的电信宽带. 嘿, 他吗的又正常了. 真的是神奇

**Comment by cooper1x** [comment]
这个腾讯云cos是怎么配置的呢？ @smallxi
