### ISSUE TITLE
After updating to the latest version, the label function is invalid

### ISSUE THREAD

**Issue by yuboabc** [usememos/memos#4184]
### Describe the bug

Look at the picture
![PixPin_2024-12-06_23-00-17](https://github.com/user-attachments/assets/da73d315-520e-4d69-bdd4-4065c09f0d8f)

I can't understand, in a more mature project. Every update will have bugs in common functions.

### Steps to reproduce

Click the label in the column on the right, and then all notes corresponding to the label have not been filtered out, and the label filtering is completely invalid.

### The version of Memos you're using.

0.23.0-rc.2

**Comment by boojack** [comment]
Duplicated with https://github.com/usememos/memos/issues/4176
