### ISSUE TITLE
memos -- weblate -- no sync

### ISSUE THREAD

**Issue by AmadeusGraves** [usememos/memos#4187]
### Describe the bug

There's a problem, weblate sync with memos's git repository doesn't work, changes can not commit from weblate to git. 

### Steps to reproduce

The problem is not about the app, is the weblate sync.

### The version of Memos you're using

all

**Comment by RoccoSmit** [comment]
If you are trying to update Memos translations please see https://github.com/usememos/memos/issues/3924
