### ISSUE TITLE
Filters bug

### ISSUE THREAD

**Issue by gujin03** [usememos/memos#4188]
### Describe the bug

Clicking on the date on the right shows 5 memos, but there is only one on the left.
<img width="1862" alt="image" src="https://github.com/user-attachments/assets/5d983ea7-2430-4aa2-8b66-393496654256">

### Steps to reproduce

Clicking on the date on the right shows 5 memos, but there is only one on the left.

### The version of Memos you're using

0.22.5

**Comment by RoccoSmit** [comment]
Unable to replicate in the latest version (v0.23)

**Comment by gujin03** [comment]
closed 0.23
