### ISSUE TITLE
升级0.7.1后，天数统计出错

### ISSUE THREAD

**Issue by chengqdevil** [usememos/memos#419]
### Describe the bug

升级0.7.1版本后，天数统计出错，日历上已显示有五天有笔记内容，DAY只显示4。

### Steps to reproduce

升级0.7.1版本后，天数统计出错，日历上已显示有五天有笔记内容，DAY只显示4。

### Expected behavior

日历上显示数量与DAY显示保持一致。

### Screenshots or additional context

![Uploading 01DA0952-B042-40B5-A8DF-F3B64BBEBBB6.jpeg…]()

**Comment by chengqdevil** [comment]
![DFCBF594-0609-44FB-845C-5EBEADD7B5B5](https://user-images.githubusercontent.com/32035201/200135341-f18238f1-3614-47c8-b999-3dadc4cda774.jpeg)

**Comment by Zeng1998** [comment]
这个时间显示的是用户使用memo的天数，换句话说，具体是用户创建时刻到当前时刻所对应的天数

**Comment by chengqdevil** [comment]
好的，了解了，谢谢。之前以为是记录的天数。
