### ISSUE TITLE
Tag renaming does not work in Firefox

### ISSUE THREAD

**Issue by eyck** [usememos/memos#4199]
### Describe the bug

Firefox does not show the 3-dot context menu when hovering over a tag in the right sidebar

### Steps to reproduce

1. Create en entry having a tag
2. Goto home or explore
3. Hover over the tag
4. '#' should turn into 3 dots

### The version of Memos you're using

v0.22.5

**Comment by RoccoSmit** [comment]
Are you in tree view? Currently the `⋮` only displays in default tag view and not in tree view

![image](https://github.com/user-attachments/assets/81bc1919-8e1e-4beb-9858-33ce48b2d5cd)

**Comment by eyck** [comment]
Yes, that is correct.
