### ISSUE TITLE
Unable to save after add lots of images.

### ISSUE THREAD

**Issue by wwng2333** [usememos/memos#4209]
### Describe the bug

I added about 60~ images in one memos, and it's not able to save at default zoom ratio.
When i click the "Save" button, it jumped back to the top of my memo.
 If i use 80% zoom, it can save normally.

### Steps to reproduce

Upload lots of images, then click "Save".
![image](https://github.com/user-attachments/assets/2ee91477-3ca9-4775-8538-ba4356f7968a)

### The version of Memos you're using

v0.23.0

**Comment by RoccoSmit** [comment]
What do you mean by 80% zoom?

**Comment by wwng2333** [comment]
> What do you mean by 80% zoom?
I mean this: ![image](https://github.com/user-attachments/assets/cb7a8d95-8a69-4ffe-88e5-c5b84dfc6fe7)

This is 100% zoom, i click save and it back to the top. If i set to 80% zoom, it can save normally.
https://github.com/user-attachments/assets/f2932c17-deed-44b3-8147-b64ce360afc0

**Comment by RoccoSmit** [comment]
Fix has been added and will be in the next release

**Comment by wwng2333** [comment]
> Fix has been added and will be in the next release

Thank you sir, i already tested with the latest test docker image version [7e22c452063ede6aacc9b6ce3a50ab2ad854e6f23077cce15ad04eec3a58322e](https://github.com/usememos/memos/pkgs/container/memos/325382632?tag=test) which works perfectly, bing thank you again.
