### ISSUE TITLE
Some bugs and suggestions I thought I had.

### ISSUE THREAD

**Issue by Frankilla-M** [usememos/memos#4223]
### Describe the bug

1. I wonder if the color here could be a little more moderate, like greenish cyan or orange. This kind of writing more and more gradually turned black to look at the senses is really uncomfortable.
![image](https://github.com/user-attachments/assets/921d3194-9842-4bd4-b575-88ff85800fe5)

2. Are there any detailed differences in the same settings of these two places? The one in the second picture seems not to work? And some options are not translated into Chinese.
![image](https://github.com/user-attachments/assets/3fba4b7c-782f-47c2-881c-83095bbcab9e)
![image](https://github.com/user-attachments/assets/93250fed-607f-4d7f-9b76-cab22ddd2093)

3. Is it possible to change the brightness and color of the highlights and code to make them less visually harsh?
![image](https://github.com/user-attachments/assets/bf9d49d2-ee02-4b7e-9060-547eea900e01)
![image](https://github.com/user-attachments/assets/3529802e-d73e-4d80-aa06-f5e808b2adaa)

As a beginner, if it cannot be changed, can you please tell me 1 and 3 how and where I can change it?

above，
thanks！

### Steps to reproduce

none.

### The version of Memos you're using

0.23.0

**Comment by RoccoSmit** [comment]
For 1, see https://github.com/orgs/usememos/discussions/4137

For 2, I cant see where the `memos` settings `Default memo visibility` is being used, the `preferences` settings for `Default memo visibility` is used for memo creation

For 3,
`settings` -> `system` -> `add additional styles`
Highlight styles can be changed with the following selector:
```
mark {
    background-color: red;
}
```
You can change `red` to whatever colour you would like

Code block has many styles so not sure what you are finding visually harsh

**Comment by Frankilla-M** [comment]
> For 1, see https://github.com/orgs/usememos/discussions/4137
> 
> For 2, I cant see where the `memos` settings `Default memo visibility` is being used, the `preferences` settings for `Default memo visibility` is used for memo creation
> 
> For translations, if you would like to add missing translations, see [#3924 (comment)](https://github.com/usememos/memos/issues/3924#issuecomment-2365401656)
> 
> For 3, `settings` -> `system` -> `add additional styles` Highlight styles can be changed with the following selector:
> 
> ```
> mark {
>     background-color: red;
> }
> ```
> 
> You can change `red` to whatever colour you would like
> 
> Code block has many styles so not sure what you are finding visually harsh

thank you so much！
