### ISSUE TITLE
/api/v1/workspace/profile interface returns owner is always user/1

### ISSUE THREAD

**Issue by quanru** [usememos/memos#4231]
### Describe the bug

Even if it's not the token of user/1 in 0.23.0

### Steps to reproduce

On the administrator's member management page, create a new user, then log in with that user and request the above interface, which results in an error.

### The version of Memos you're using

0.23.0

**Comment by quanru** [comment]
How to use token to get the id of the current user

**Comment by quanru** [comment]
![image](https://github.com/user-attachments/assets/1b0f2ae5-64bd-4c11-9a19-95469f97506d)

**Comment by RoccoSmit** [comment]
@quanru , this is a `POST` request.
Change from `GET` to `POST` and it should work for you
