### ISSUE TITLE
Tag API cannot be obtained

### ISSUE THREAD

**Issue by iowong** [usememos/memos#4233]
### Describe the bug

{"code":5, "message":"Not Found", "details":[]}
/api/v1/memos/-/tags
Previously, it could be used, but after the update, it doesn't work anymore

### Steps to reproduce

{"code":5, "message":"Not Found", "details":[]}
/api/v1/memos/-/tags
Previously, it could be used, but after the update, it doesn't work anymore

### The version of Memos you're using

v0.23.0

**Comment by RoccoSmit** [comment]
I believe tags are now accessed via `ListMemos`

**Comment by iowong** [comment]
> 我相信现在可以通过以下方式访问标签`ListMemos`

I need to obtain the API for all tags

**Comment by iowong** [comment]
> I believe tags are now accessed via `ListMemos`

I need to obtain the API for all tags

**Comment by RoccoSmit** [comment]
Please see https://github.com/usememos/memos/issues/4161
