### ISSUE TITLE
new line with space ahead trigger disappearance

### ISSUE THREAD

**Issue by toyqiu** [usememos/memos#425]
### Describe the bug

行首不能以半角或全角空格开头，否则新行会被吃掉，直接接到上一句末尾+空格。

### Steps to reproduce

　　比如，我习惯性写东西这样排版。
　　看上去会比较舒服一点。

会变成

　　比如，我习惯性写东西这样排版。　　看上去会比较舒服一点。

### Expected behavior

希望能修复这个排版问题，挺膈应人的。

**Comment by Zeng1998** [comment]
我这边无法复现

**Comment by Zeng1998** [comment]
https://user-images.githubusercontent.com/31177490/200207176-0b35e705-1b79-44ca-b90e-2f30eeb625b0.mp4

**Comment by toyqiu** [comment]
> 我这边无法复现

![Screenshot_2022-11-07-14-37-48-683_com kiwibrowser browser](https://user-images.githubusercontent.com/479873/200241638-cac0f777-2c52-4ad4-a5aa-cefdc549369c.jpg)

要不你复制一下我上面的内容发布一下

视频内容看不到，特地去访问了一圈u2b，twitter，fb都正常

**Comment by Zeng1998** [comment]
能够复现了
