### ISSUE TITLE
code=401,message=Missing user in session

### ISSUE THREAD

**Issue by cnkids** [usememos/memos#435]
### Describe the bug

同一局域网下，一台手机可以正常登陆，另一台出现错误提示
code=401,message=Missing user in session

docker启动之后提示
ERROR: sending request - Post "https://api.segment.io/v1/batch": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### Steps to reproduce

1、输入账号
2、弹出错误提示

### Expected behavior

正常登陆

### Screenshots or additional context

![QQ图片20221109202559](https://user-images.githubusercontent.com/8697857/200830728-56212835-5865-443f-af66-168c3dbc57ce.jpg)

**Comment by boojack** [comment]
If you can still get this error, please feel free to reopen the issue.

**Comment by cnkids** [comment]
still get the error

**Comment by cnkids** [comment]
> If you can still get this error, please feel free to reopen the issue.

still get the error

**Comment by boojack** [comment]
@cnkids I did some testing on this and it works well in both PC browsers and mobile browsers. But I don't have two phones at all.

Can you provide some backend information about the error? Or can you try it on PC and mobile?

**Comment by cnkids** [comment]
> @cnkids I did some testing on this and it works well in both PC browsers and mobile browsers. But I don't have two phones at all.
> 
> Can you provide some backend information about the error? Or can you try it on PC and mobile?

Oh，maybe it's blame on ios safari (iphone 11 pro max and 14 pro max), chrome is working. But still weird, it can work on 11 pro(safari), 14 pro(safari), ipad pro((safari), win browser, mac(safari). Anyway, it's ok for now.

**Comment by m4mazzotti** [comment]
I am also getting this error while using MS Edge. It was working before I updated to 0.9.

**Comment by JackTheFlap** [comment]
Also getting the same error on 0.9. Was working fine on 0.8.3. Tested on the following browsers:

- MacOS - Brave
- MacOS - Firefox
- MacOS - Safari
- Windows 10 - Firefox
- Windows 10 - Edge
- Pixel 4A 5G Android 13 - Mull

All failed with the error:
`Failed to load resource: the server responded with a status of 401 (Unauthorized)`

I've tried incognito on browsers that have previously visited the site and manually adding the tag table to the DB.

I know the username is correct from DB, I can also confirm the password is correct from the error messages for invalid password on HTTP.

**Comment by Zeng1998** [comment]
Fixed in #848

**Comment by Zeng1998** [comment]
Just pull the latest image again.

**Comment by m4mazzotti** [comment]
Thanks @Zeng1998, so far #848 wasn't include in a release

**Comment by Zeng1998** [comment]
@m4mazzotti 

Hello, I think it has been included in the new docker image. Just pull the new image and everything is ok.
