### ISSUE TITLE
进入或者退出编辑体验优化

### ISSUE THREAD

**Issue by Rookiewan** [usememos/memos#468]
#### 进入编辑

1. hover 标签，点击选择
2. 会先进入编辑状态，标签未选上
3. 需要再次选择标签

#### 退出编辑
当处于编辑状态时，点击别的操作区域。例如另一条记录的复制
![image](https://user-images.githubusercontent.com/13617296/201808786-f58c1e64-4143-4664-8953-e049f592105f.png)

点击后页面会先判断失焦，发生抖动上移，一度以为是 bug。
![image](https://user-images.githubusercontent.com/13617296/201808792-218b3ff1-1641-418e-bbee-171e210b4cc6.png)

### Describe the solution you'd like

1. 退出编辑时不发生抖动
4. 编辑状态时点击别的记录的下拉操作时，不拦截操作

**Comment by Zeng1998** [comment]
可以看下demo网站上能否复现，方便的话录个视频最好

**Comment by Rookiewan** [comment]
> 可以看下demo网站上能否复现，方便的话录个视频最好

我安装的是 0.7.2-prod
看了下 demo 上的，是 0.7.2-dev，目前体验是对的
![image](https://user-images.githubusercontent.com/13617296/201820627-25d9b387-cc3c-47e7-b5d0-9ebf8ae93dbf.png)

**Comment by Rookiewan** [comment]
看起来下个版本就会修复了，辛苦
