### ISSUE TITLE
Rename the tags

### ISSUE THREAD

**Issue by qiangjitaibai** [usememos/memos#470]
### Is your feature request related to a problem?

I hope to rename and reschedule my tags after I create it.
 

### Describe the solution you'd like

rename tag and reschedule taglist after create it.

**Comment by i-iooi-i** [comment]
This function is needed. I hope that labels can be sorted by name. Now they are sorted by adding order, which is a bit confusing.

**Comment by DHS1001** [comment]
It would be great and make sense that the user can modify the tags.

**Comment by gitkeniwo** [comment]
Obsidian uses a tag tree too and they have [a decent community plugin](https://github.com/pjeby/tag-wrangler) for this (renaming, merging etc). I wonder if this could be some nice implementation for this feature.

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/79558028c043fc9b7b0f3fe72daeaff6b530e9c6

https://github.com/usememos/memos/assets/24653555/89a57c26-0a71-48b2-92a7-56391fce00a8

**Comment by asdaraga** [comment]
nicc

**Comment by aisvoyage** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
