### ISSUE TITLE
0.7.2自动回档到4天前，最近记录的所有东西都消失

### ISSUE THREAD

**Issue by czxinshui** [usememos/memos#479]
### Describe the bug

0.7.2自动回档到4天前，最近记录的所有东西都消失

### Steps to reproduce

0.7.2自动回档到4天前，最近记录的所有东西都消失

### Expected behavior

0.7.2自动回档到4天前，最近记录的所有东西都消失

### Screenshots or additional context

https://github.com/czxinshui/tupian/blob/main/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20221116071313.png?raw=true

**Comment by Zeng1998** [comment]
应该是你自己的操作问题，正常不会出现这种情况的

**Comment by boojack** [comment]
是怎么升级的？以及从0.7.1升级到0.7.2后，大概执行了哪些操作
