### ISSUE TITLE
打开memeos站点，请求数据过大。

### ISSUE THREAD

**Issue by lhuanyun** [usememos/memos#480]
### Describe the bug

![image](https://user-images.githubusercontent.com/20707383/202147101-22b85738-112c-49fb-a59d-4d993b8e8aec.png)

没有任何记录的情况下。打开主页
看了一下，主要是emoji表情，能否做一个压缩。
虽然是通过cdn，但是使用起来，消耗的移动流量过于巨大。

### Steps to reproduce

如上

### Expected behavior

如上

**Comment by Zeng1998** [comment]
这个应该有缓存的

**Comment by lhuanyun** [comment]
主要是emoji 图标。正常使用缓存，流量不高。
