### ISSUE TITLE
粘贴第二个附件时，第一个附件消失。

### ISSUE THREAD

**Issue by pharaohnie** [usememos/memos#481]
### Describe the bug

通过ctrl+c, ctrl+v粘贴附件。粘贴完第一个附件再粘贴第二个附件，第一个附件就会消失。
这个现象只存在于新建的文章。编辑旧文章没这个问题。

### Steps to reproduce

通过ctrl+c, ctrl+v粘贴附件。粘贴完第一个附件再粘贴第二个附件，第一个附件就会消失。
这个现象只存在于新建的文章。编辑旧文章没这个问题。

### Expected behavior

通过ctrl+c, ctrl+v粘贴附件。粘贴完第一个附件再粘贴第二个附件，第一个附件就会消失。
这个现象只存在于新建的文章。编辑旧文章没这个问题。

**Comment by czxinshui** [comment]
> ### 描述错误
> ctrl+c，ctrl+v粘贴粘贴。第一个附件附件附件附件附件附件，第一第一个附件附件就消失消失。 这个现象只存在于于于
> 
> ### 重现步骤
> ctrl+c，ctrl+v粘贴粘贴。第一个附件附件附件附件附件附件，第一第一个附件附件就消失消失。 这个现象只存在于于于
> 
> ### 预期行为
> ctrl+c，ctrl+v粘贴粘贴。第一个附件附件附件附件附件附件，第一第一个附件附件就消失消失。 这个现象只存在于于于
> 
> ### 屏幕截图或其他上下文
> _没有反应_
没说版本号！

**Comment by pharaohnie** [comment]
> > ### 描述错误
> > ctrl+c，ctrl+v粘贴粘贴。第一个附件附件附件附件附件附件，第一第一个附件附件就消失消失。 这个现象只存在于于于
> > ### 重现步骤
> > ctrl+c，ctrl+v粘贴粘贴。第一个附件附件附件附件附件附件，第一第一个附件附件就消失消失。 这个现象只存在于于于
> > ### 预期行为
> > ctrl+c，ctrl+v粘贴粘贴。第一个附件附件附件附件附件附件，第一第一个附件附件就消失消失。 这个现象只存在于于于
> > ### 屏幕截图或其他上下文
> > _没有反应_
> > 没说版本号！

不好意思，忘了。是0.7.2
<img width="710" alt="image" src="https://user-images.githubusercontent.com/880867/202315309-38c7d7ca-7f81-41d2-bf40-5d17fcceba6d.png">
当粘贴第二个附件的时候，第一个就被替换掉了。
<img width="665" alt="image" src="https://user-images.githubusercontent.com/880867/202315342-2244f660-6488-4e28-b224-5addfd9bcb64.png">
粘贴第三个附件的时候，第二个又会被替换掉。

**Comment by Zeng1998** [comment]
我这边好像没法复现

**Comment by pharaohnie** [comment]
> 我这边好像没法复现

我又确认了一下。mac系统，用chrome和safari都一样的问题。而且也提前清除了缓存和cookie

**Comment by Jonnyan404** [comment]
> demo网站上能复现吗

Demo上没这个问题

**Comment by boojack** [comment]
Next release will fix this. Please upload resource manually at present.
