### ISSUE TITLE
更新0.7.3后，以前memo之间的链接都打不开了

### ISSUE THREAD

**Issue by heartnn** [usememos/memos#498]
### Is your feature request related to a problem?

现在打开时显示：
Unhandled Thrown Error!
404 Not Found
💿 Hey developer 👋

You can provide a way better UX than this when your app throws errors by providing your own errorElement props on <Route>

### Describe the solution you'd like

复制链接变为了复制内容，这个功能还能恢复吗？

**Comment by leoneoo** [comment]
我发现图片右侧有类似滚动条，影响整体美观。<img src="https://oneoo-1253919472.cos.ap-shanghai.myqcloud.com/oneooimg/0.73%E7%89%88%E6%9C%AC.png" alt="image" style="max-width: 100%;">

**Comment by boojack** [comment]
> 以前memo之间的链接

@heartnn memo 之间的链接指的是 Mark 功能吗？memo-memo 之间的连接关系将要改为类似于 memo-resource 的效果，通过新增一个表来直接存储而不是在 memo 内容中标注。

> 复制链接变为了复制内容，这个功能还能恢复吗？

如果需要复制某条单独 memo 的链接，可以先通过 View Detail 打开新的页面后自行复制。

**Comment by heartnn** [comment]
> > 以前memo之间的链接
> 
> @heartnn memo 之间的链接指的是 Mark 功能吗？memo-memo 之间的连接关系将要改为类似于 memo-resource 的效果，通过新增一个表来直接存储而不是在 memo 内容中标注。
> 
> > 复制链接变为了复制内容，这个功能还能恢复吗？
> 
> 如果需要复制某条单独 memo 的链接，可以先通过 View Detail 打开新的页面后自行复制。

单独打开的新页面似乎没有编辑功能。
我的使用环境是这样，我通过一个置顶的memo链接了几个经常需要修改的memo。

**Comment by Zeng1998** [comment]
Follow #820 for more details about memo relation.
