### ISSUE TITLE
希望新增功能

### ISSUE THREAD

**Issue by suqin1020** [usememos/memos#500]
### Is your feature request related to a problem?

1.分类后面可以显示这个分类下面的笔记条数。

2.分类也可以直接删除

### Describe the solution you'd like

1.   就是分类后面显示就行

2. 像删除笔记那样归档之后在删除

**Comment by boojack** [comment]
分类指的是什么？ shortcut or tag？

**Comment by suqin1020** [comment]
一级标题那个
#一级标题

boojack ***@***.***> 于2022年11月20日周日 16:45写道：
