### ISSUE TITLE
最新版本折叠功能失效

### ISSUE THREAD

**Issue by zy9306** [usememos/memos#512]
### Describe the bug

本地测试了 66f9bc48bb765fb51361a329a97f6158998d9c59 这个 commit 是好的

最新的 commit 折叠功能挂了

### Steps to reproduce

1. 检出最新 commit b05a1764903bd1c075029e5f01ec3569ee56c48d，分别启动前端和后端，键入长文本，没有折叠按钮
2. 切回到 66f9bc48bb765fb51361a329a97f6158998d9c59 这个版本，功能正常

### Expected behavior

最新版本折叠功能不可用

### Screenshots or additional context
66f9bc48bb765fb51361a329a97f6158998d9c59 版本：
![图片](https://user-images.githubusercontent.com/18747432/203011704-cb88b2ae-17aa-439a-b3e6-229fbba69cda.png)

b05a1764903bd1c075029e5f01ec3569ee56c48d 版本：
![图片](https://user-images.githubusercontent.com/18747432/203011951-165865cf-e299-40da-bfbe-4534debfc2b2.png)

**Comment by hyoban** [comment]
你好，现在的设计是使用分割线作为折叠标识。
https://www.markdownguide.org/basic-syntax/#horizontal-rules

**Comment by zy9306** [comment]
> 你好，现在的设计是使用分割线作为折叠标识。 https://www.markdownguide.org/basic-syntax/#horizontal-rules

感谢解答，可以了
