### ISSUE TITLE
0.7.3把URL里面的内容解析成标签了

### ISSUE THREAD

**Issue by neilwyh** [usememos/memos#515]
### Describe the bug

第一个#开头的标签其实是URL中的部分，完整的URL是https://share.lanhuapp.com/#/invite?sid=xxxxxx

![image](https://user-images.githubusercontent.com/4897422/203082214-ff40ed61-4284-4edb-b3a2-a1cd2d24e8d3.png)

### Steps to reproduce

见描述中的URL

### Expected behavior

标签是否可以考虑单独存储成字段，和笔记关联起来，感觉更灵活

**Comment by boojack** [comment]
> 标签是否可以考虑单独存储成字段，和笔记关联起来，感觉更灵活

不会单独新建一个 tag 表，不过之后可能会和 shortcut 相关联，实现与 tag 一样的效果。
