### ISSUE TITLE
删除功能

### ISSUE THREAD

**Issue by GithubGey** [usememos/memos#527]
### Describe the bug

<img width="673" alt="image" src="https://user-images.githubusercontent.com/86140803/203208845-c692801e-6b2b-44c3-955e-3d57ed085adb.png">

你好，我使用docker 部署了本项目，我怎么删除一条记录，为没有找到删除按钮或者权限

Hello, I used Docker to deploy this project. How can I delete a record? Because there is no delete button or permission

### Steps to reproduce

你好，我使用docker 部署了本项目，我怎么删除一条记录，为没有找到删除按钮或者权限

Hello, I used Docker to deploy this project. How can I delete a record? Because there is no delete button or permission

<img width="673" alt="image" src="https://user-images.githubusercontent.com/86140803/203208845-c692801e-6b2b-44c3-955e-3d57ed085adb.png">

**Comment by Zeng1998** [comment]
先归档，如果要删除，再从归档中删除

**Comment by GithubGey** [comment]
>先归档，如果要删除，再从归档中删除

好的，归档就相当于垃圾箱的功能

**Comment by xqa** [comment]
> 先归档，如果要删除，再从归档中删除

这个不应该叫归档吧，感觉回收站这个词比较好
