### ISSUE TITLE
Tags can not be browsed by public viewers

### ISSUE THREAD

**Issue by ItsNoted** [usememos/memos#536]
### Is your feature request related to a problem?

When logged out, tags cannot be clicked and applied as a filter for public viewers. Currently when logged out and you click on a tag in a public post, nothing happens. It appears tags can only be browsed when logged in.

### Describe the solution you'd like

When logged out on the explore page, tags should be able to be clicked to see any public posts with the same tag as a filter. This is good for those using this as a status (blog) for personal use. Tags can then be used to help categorize things for viewers.

**Comment by aschenmaker** [comment]
Added suggestion, explore pages can be view by selected time(year or month). And also show host days.
