### ISSUE TITLE
Custom Explore Page

### ISSUE THREAD

**Issue by ItsNoted** [usememos/memos#540]
### Is your feature request related to a problem?

Customize a few things on explore page for when people are not logged in (public viewers)

1. Custom Icon and Header Text
2. Public search option
3. Public tag browsing

### Describe the solution you'd like

1. Custom Icon and Header Text - Replace the icon and "Explore" with custom icon and header text.
2. Public search option - Allow public viewers to search public posts.
3. Public tag browsing - Allow public viewers to browse tags on posts that are marked as public.

These are a few things I think will make Memos much more popular and usable in more diverse ways.

### Additional context

Currently there is no organization for public viewers who are not logged in. I feel these features will help organize the experience for public posts and viewing.

**Comment by boojack** [comment]
> Custom Icon and Header Text

You can custom anything you want with the additional scripts.

> Public search option and tag browsing

We will figure out a good UI to display them later.

**Comment by ItsNoted** [comment]
> We will figure out a good UI to display them later.

I did notice if you click the username of the person who made the post you can then browse the public tags and search posts publicly. It took me a long time to figure that out so a better way to do that would be good. Perhaps from the explore page because that's the main page public viewers are taken to.

**Comment by mariushosting** [comment]
+1 I completely agree. The ability to change Icon and Text "Explore" on the main page should be very useful for the end user. We know we can change anything with additional scripts but better to have this option on the "Setting" area under Preferences.

**Comment by boojack** [comment]
Maybe outdated issue. If the problem still exists, please create a new issue.
