### ISSUE TITLE
标签不能正常的显示 

### ISSUE THREAD

**Issue by NewOneTcm** [usememos/memos#543]
如果是使用`#中医`，它会变成一个加背景的字体，就像是代码的效果。这时会变成#中医`的效果，在#号里面会显示一个tag，但是tag后面会多一个`的符号，tag也变成蓝色。。

但是如果是使用#日常 它不能识别为一个tag， 同时那个#号里面也没有显示这个#
![Snipaste_2022-11-23_21-35-00](https://user-images.githubusercontent.com/49179435/203560318-8790ba46-7e0d-45f4-8528-a600e5446757.png)

**Comment by boojack** [comment]
tag 的格式是 `#TAG_NAME空格`，后面要跟个空格

<img width="329" alt="image" src="https://user-images.githubusercontent.com/24653555/203588865-2fd354c1-2d54-4300-9b09-172966baef7e.png">

**Comment by NewOneTcm** [comment]
> tag 的格式是 `#TAG_NAME空格`，后面要跟个空格
> 
> <img alt="image" width="329" src="https://user-images.githubusercontent.com/24653555/203588865-2fd354c1-2d54-4300-9b09-172966baef7e.png">

收到，非常感谢
