### ISSUE TITLE
💭是否考虑添加标签父子级关系

### ISSUE THREAD

**Issue by ChiehJang** [usememos/memos#552]
### Is your feature request related to a problem?

有时候定义的🏷️标签较为笼统，在✍️写笔记的时候往往又想丰富其内容是往往需要子标签的💡想法。

### Describe the solution you'd like

有时候定义的🏷️标签较为笼统，在✍️写笔记的时候往往又想丰富其内容是往往需要子标签的💡想法。

**Comment by Zeng1998** [comment]
try `#tag1/tag2 `

**Comment by ChiehJang** [comment]
It's Works！👍
[https://imgur.com/a/94bHYTj](url)

**Comment by lhuanyun** [comment]
学习了，🎉
