### ISSUE TITLE
explore是空白的，这个功能怎么用？能不能添加信息之间的链接

### ISSUE THREAD

**Issue by NewOneTcm** [usememos/memos#553]
### Is your feature request related to a problem?

explore是空白的，这个功能怎么用？能不能添加信息之间的链接

### Describe the solution you'd like

没有搞懂Explore怎么用。

想要添加信息之间的链接，现在还没有这个功能。

**Comment by Yujiang-Liu** [comment]
explore没登录的时候用来看自己和别人的public消息,登录后可以看protect和public消息
