### ISSUE TITLE
Tagging requires characters after the tag

### ISSUE THREAD

**Issue by ronnyandre** [usememos/memos#560]
### Describe the bug

When I want to tag an entry, it always needs to be followed by a character (either text or a space). Meaning, the following text would create a valid tag:

```
#tag 
#tag this works!
```

First line has a space afterwards
Second line has text afterwards

The following won't work:

```
#tag
this does not work! #tag
```

First line does not have characters after the tag
Second line has text before the tag, but not after the tag

### Steps to reproduce

1. Create new entry
2. Write `#tag` without any whitespace/characters before or after the tag
3. The tag won't be created

**Comment by boojack** [comment]
Hi, @ronnyandre. The standard format of tag is `'#TAG_NAME '`. There should be a **space** after tag name.

<img width="358" alt="image" src="https://user-images.githubusercontent.com/24653555/203797621-49cb6441-7b77-470f-a6db-0110fd29e0e2.png">

**Comment by ronnyandre** [comment]
So it is working as intended? If using tags, an entry should *always* start with a tag or similar? I find it normal to end an entry with tags.

**Comment by boojack** [comment]
You can write the tags at the beginning and end of the content, or anywhere else you want. The main key is that you have to make sure that the tags are properly formatted.

**Comment by boojack** [comment]
PTAL: [Best practices to write a TAG](https://github.com/usememos/memos/wiki/Best-practices-to-write-a-TAG)
