### ISSUE TITLE
Ability to record Voice notes / audio mesages

### ISSUE THREAD

**Issue by sumitmamoria** [usememos/memos#568]
### Is your feature request related to a problem?

NA

### Describe the solution you'd like

NA

### Additional context

The ability to directly record a voice note or a short audio message would be cool.

**Comment by boojack** [comment]
Memos is a web application that is hard to access the microphone. You can upload the audio file and related into your memo content.

**Comment by Zeng1998** [comment]
In my opinion,  if you want to record some audios, like music, you could regard them as resource files. And if you want to record some voice information, I I think maybe text is more suitable and readable, and many mobile input editor can do this (voice to text).
