### ISSUE TITLE
Cannot sign up with long email

### ISSUE THREAD

**Issue by cuongnguyen-prime** [usememos/memos#571]
### Describe the bug

User cannot Sign In/ Sign up with long email (length < 255 character)

### Steps to reproduce

1. Go to /auth
2. Input email, password
3. Click login

### Screenshots or additional context

![Memos](https://user-images.githubusercontent.com/102508319/203921764-404d2fa1-fa6d-4ca9-af95-3f051ee4b565.png)

**Comment by Zeng1998** [comment]
Fixed in the next release by this commit #523
