### ISSUE TITLE
Video issues on iOS

### ISSUE THREAD

**Issue by ItsNoted** [usememos/memos#592]
Here you can see videos are not displaying on iOS. I tried mp4 and mov files. Also tried both safari and Firefox browsers. This is a iPhone 10 XS Max. I am doing some pretty vigorous testing before presenting this to our team to use in production. This is one issue that will definitely make it difficult to use.

![F59E9910-2B07-4F9B-B096-B9D24AFAD179](https://user-images.githubusercontent.com/57927413/204092132-ca24eac1-2961-4042-b04c-d7fb0c63257b.jpeg)

**Comment by lhuanyun** [comment]
I have the same problem

**Comment by boojack** [comment]
Fixed in https://github.com/usememos/memos/pull/980
