### ISSUE TITLE
Can't upload a video which goes over 70 MB.

### ISSUE THREAD

**Issue by mariushosting** [usememos/memos#598]
### Describe the bug

I can't upload a video that which goes over 70 MB. I can upload only small videos that are less then 30 MB.

### Steps to reproduce

I can't upload a video that which goes over 70 MB. I can upload only small videos that are less then 30 MB.

**Comment by boojack** [comment]
The maximum size of resource is now 32MB.

https://github.com/usememos/memos/blob/main/server/resource.go#L20

**Comment by mariushosting** [comment]
thanks!
