### ISSUE TITLE
Allow searching archived items

### ISSUE THREAD

**Issue by msreedata** [usememos/memos#607]
### Is your feature request related to a problem?

- Currently once a memo is archived, I am unable to use search to find it.
- When we have more memos, from time to time it makes sense to archive it to keep it clean. However when we need to get back to one of those old ones we can't even if there is a tag attached to it. Only option is to manually scroll to find it. 

### Describe the solution you'd like

- It would be great to have an additional switch to allow searching in Archived memos also
- Also the search could be exclusive. ie. Either search in normal only OR in archived ones only

### Additional context

Requesting to review this feature requirement. Kindly correct me, in case I missed to find the option if a similar one already exists.

**Comment by boojack** [comment]
I'd like to add a search bar in archived memos dialog.

**Comment by mauricebauer** [comment]
However, I also see a big advantage in being able to search in both areas with one search (_I think that is requested in the original issue_). Sometimes I dont know if it is already achived and thus this would lead to two searches... A toggle switch for the current search bar ("_Include Archive_" or sth like this) would be nice.

**Comment by zhimiaoli** [comment]
really need this feature, add a checkbox in the search page to enable searching in archived memos would really be nice.

**Comment by Kcalb35** [comment]
any progress?
