### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by jxpsert** [usememos/memos#612]
### Is your feature request related to a problem?

No problem. Simply a Dutch translation.

### Describe the solution you'd like

Dutch locale. Going to work on it myself.

**Comment by jxpsert** [comment]
Been working on this (issue created later), having an issue. [this](https://github.com/jxpsert/memos/commit/691e4c08153e7d83f86ee1e7639bb58ccc121015) is my commit (problems are in comments of the commit), if anyone has any idea feel free to comment.

**Comment by Mozzo1000** [comment]
Hi,

I checked out your `dutch-locale` branch and for me it works as expected without any code change. Are you sure your api server is being rebuilt correctly?
![memos_nederlands_language](https://user-images.githubusercontent.com/3440776/205444107-e6e0cbbd-a6be-4233-9907-f3dcc975aa57.PNG)

**Comment by jxpsert** [comment]
Hm, even after rebooting, it's still not working as it should for me. What OS are you using?

**Comment by Mozzo1000** [comment]
I have now tried it both on Windows 10 and Ubuntu 22.04.1 with the same result i.e the branch works as is.
On my Ubuntu machine I have the following versions installed,
* Go 1.18.1
* Node.JS 18.12.1

**Comment by jxpsert** [comment]
Well, seems to work then. Opening PR.
