### ISSUE TITLE
Upgrade Docker Container loses memos

### ISSUE THREAD

**Issue by blaine07** [usememos/memos#613]
### Describe the bug

When I update the container all my memos are gone/lost. 

What am I doing wrong?

### Steps to reproduce

Update container and current memos are gone

**Comment by e1z0** [comment]
Just did update, error: cannot open db: failed to find migration history, err: no such table: migration_history

**Comment by jxpsert** [comment]
> ### Steps to reproduce
> Update container and current memos are gone

Yeah, that really doesn't tell us anything about what you've done to update. What commands have you run? What did they output?

**Comment by blaine07** [comment]
> > ### Steps to reproduce
> > Update container and current memos are gone
> 
> Yeah, that really doesn't tell us anything about what you've done to update. What commands have you run? What did they output?

Updated the container in docker in unraid. No more, no less. Then container no longer contains my memos. Have storage path defined.

**Comment by jeffrey-ose** [comment]
I have the same issue. Updated the docker with the following command: `docker-compose down && docker image rm neosmemo/memos:latest && docker-compose up -d`.
Container didn't start, so I did a `docker-compose up` (without the `-d`) and I got:

```
[+] Running 1/0
 ⠿ Container memos  Created                                                                                                                                                                                                                                              0.0s
Attaching to memos
memos  | ---
memos  | profile
memos  | mode: prod
memos  | port: 5230
memos  | dsn: /var/opt/memos/memos_prod.db
memos  | version: 0.8.0
memos  | ---
memos  | error: cannot open db: failed to find migration history, err: no such table: migration_history
memos exited with code 1
```

I use a docker-compose file where I defined a bind mount for `/var/opt/memos`.
Used to work fine.

**Comment by e1z0** [comment]
> I have the same issue. Updated the docker with the following command: `docker-compose down && docker image rm neosmemo/memos:latest && docker-compose up -d` (as stated in the README). Container didn't start, so I did a `docker-compose up` (without the `-d`) and I got:
> 
> ```
> [+] Running 1/0
>  ⠿ Container memos  Created                                                                                                                                                                                                                                              0.0s
> Attaching to memos
> memos  | ---
> memos  | profile
> memos  | mode: prod
> memos  | port: 5230
> memos  | dsn: /var/opt/memos/memos_prod.db
> memos  | version: 0.8.0
> memos  | ---
> memos  | error: cannot open db: failed to find migration history, err: no such table: migration_history
> memos exited with code 1
> ```
> 
> I use a docker-compose file where I defined a bind mount for `/var/opt/memos`. Used to work fine.
> 
> My docker-compose.yml:
> 
> ```
> services:
>   memos:
>     image: neosmemo/memos:latest
>     container_name: memos
>     volumes:
>       - ./memos:/var/opt/memos
>     ports:
>       - 5230:5230
> ```

I'm already posted a workaround for this :)
