### ISSUE TITLE
pictures uploaded by api disapeared after updated to 0.8.0 from  0.7.2 

### ISSUE THREAD

**Issue by JeazW** [usememos/memos#615]
###  1. pictures uploaded by api disapeared after updated to 0.8.0 from  0.7.2 :
![image](https://user-images.githubusercontent.com/75829171/204205611-0debd70a-b79e-44c2-a150-0d676b3d2c3d.png)
![image](https://user-images.githubusercontent.com/75829171/204175187-2121ba77-cbf7-467e-ad8d-4a12c0ef9e31.png)
### 2. logs:
![image](https://user-images.githubusercontent.com/75829171/204176350-f70bec5a-934f-4b76-a6ee-7d35f14f92f6.png)

![image](https://user-images.githubusercontent.com/75829171/204175250-b54838ea-81d4-4564-8f41-e90983335bc1.png)
###  3. when i paste my domain with the base64 link in browser,the picture shows up;
![image](https://user-images.githubusercontent.com/75829171/204175813-b8c55848-a54d-4317-9917-be175e79bc9f.png)
### 4.  seems taht nothing wrong in database;
**resousce**:
![image](https://user-images.githubusercontent.com/75829171/204175995-4386b9a0-0f13-4c32-b0ec-8dafe1f039dc.png)
**memo**:
![image](https://user-images.githubusercontent.com/75829171/204176123-30dac634-25a3-4882-b788-d7abdf53a57e.png)

### 1. backup database && update memos :
```bash
cp /data/memos/memos_prod.db  ~/desktop/memosbak/memos_prod.db_`date +%y%m%d`
docker-compose down && docker image rm neosmemo/memos:latest && docker-compose up -d
```
### 2. check it out in browser,ops~
![image](https://user-images.githubusercontent.com/75829171/204176570-f87ed748-b4ef-4215-9316-3245414e5c93.png)

**Comment by boojack** [comment]
Already fixed in #623, please update your container again.
