### ISSUE TITLE
[优化]手机竖屏视频样式+中文重置api语言变英文

### ISSUE THREAD

**Issue by Jonnyan404** [usememos/memos#621]
### Is your feature request related to a problem?

-

### Describe the solution you'd like

1. 中文语言下,重置api,当前页会变为英文,刷新当前页可恢复
2. 视频预览对手机拍摄的竖屏视频展示效果太差,望优化,谢谢(视频为本地上传)

**Comment by boojack** [comment]
> 1. 中文语言下,重置api,当前页会变为英文,刷新当前页可恢复
> 2. 视频预览对手机拍摄的竖屏视频展示效果太差,望优化,谢谢(视频为本地上传)

问题 1 已修复。建议 issue 里应该只包含一个具体的问题
