### ISSUE TITLE
heic格式的图片无法显示

### ISSUE THREAD

**Issue by xueyangcs** [usememos/memos#625]
### Describe the bug

如题，上传heic图片之后无法在网页中显示

### Steps to reproduce

1、在memos编辑框中点击文件按钮并上传heic格式图片
2、查看该memo，上传的图片显示为broken picture的图标

**Comment by Zeng1998** [comment]
I think `heic` is not a common web image format now.

Some other apps convert this format to others for displaying in the browser.
