### ISSUE TITLE
v0.8.0 wipes out tags counting and old tags not shown

### ISSUE THREAD

**Issue by toyqiu** [usememos/memos#627]
### Describe the bug

升级 v0.8.0 后，升级前发文的 tag 统计计数清零；左侧栏不显示升级前 tags
升级后发文新 tag 可计数、可在左侧栏显示；新 tag #A 若与升级前 tag #A 相同，则点击左侧能出现所有含该 tag A推文（包括升级前旧文）；【如果删除新 tag #A 的推文，则左侧栏中 tag #A 消失】

### Steps to reproduce

publish a new tag
publish a existed tag

**Comment by Zeng1998** [comment]
some detail or cases?  which tag disappeared and how do you write it in the memo content?

**Comment by toyqiu** [comment]
> some detail or cases? which tag disappeared and how do you write it in the memo content?

all tags disappeared from left side bar.
nothing wrong with tags in contents.
like #tag

**Comment by toyqiu** [comment]
> some detail or cases? which tag disappeared and how do you write it in the memo content?

![image](https://user-images.githubusercontent.com/479873/204550357-4c0f9e9a-dfdd-4d62-8b8d-09db7f205ce2.png)

**Comment by boojack** [comment]
tag 后面需要加一个空格

https://github.com/usememos/memos/wiki/Best-practices-to-write-a-TAG

**Comment by toyqiu** [comment]
> tag 后面需要加一个空格
> 
> https://github.com/usememos/memos/wiki/Best-practices-to-write-a-TAG

全都有加。老po文全都是 #标签 这样的格式，都正常的。
更新之后文章里的tag显示正常，但是左边侧边栏tag是空的。过滤器中显示无tag。


我哪里表述不明确吗，需要什么方面的补充

**Comment by boojack** [comment]
复制一条丢失了tag的原文看看

**Comment by toyqiu** [comment]
> 复制一条丢失了tag的原文看看

`　　下午仓库的事情做完就#居家办公 了。好歹是没有之前那种就算没什么事也要呆着，上班时间好长的感觉了。晚上在家里多多少少能兼顾一下，有个在场证明吧。`

**Comment by boojack** [comment]
#居家办公 前后都不能有内容，建议统一放在第一行、最后一行

**Comment by boojack** [comment]
嗯，直接的和内容“融为一体”的tag是bug，不应该被识别
