### ISSUE TITLE
通过过滤方式找到几天前的文章，点击完成任务，提示“Failed to fetch memo list”

### ISSUE THREAD

**Issue by pharaohnie** [usememos/memos#640]
### Describe the bug

通过过滤方式找到几天前的文章，点击完成任务，提示“Failed to fetch memo list”

版本:0.8.0-prod

### Steps to reproduce

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/880867/204690650-12cb5c46-b402-459e-b65f-d6a8acbce339.png">

1. 通过过滤或捷径找到2天前带有任务功能的文章
2. 点击完成任务
3. 右上角提示“Failed to fetch memo list”

### Screenshots or additional context

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/880867/204693516-26662337-3d18-4f80-9843-189a1a56744f.png">

<img width="844" alt="image" src="https://user-images.githubusercontent.com/880867/204692764-339707ab-601e-40b6-afb0-4dca8418ce32.png">

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/880867/204692937-396798ff-d53a-4900-94ac-6137b48097e1.png">

<img width="997" alt="image" src="https://user-images.githubusercontent.com/880867/204693038-ce7e91ab-3b15-48b5-ae54-43960830a153.png">

<img width="954" alt="image" src="https://user-images.githubusercontent.com/880867/204693139-25e8a4e1-56b4-4937-ab30-a3b9d1b0df65.png">

_No response_

**Comment by boojack** [comment]
@pharaohnie 没能复现，麻烦提供下具体的错误信息

<img width="776" alt="image" src="https://user-images.githubusercontent.com/24653555/205290223-898c6983-9e3e-4352-8cdd-cd4bc51f31e6.png">

**Comment by boojack** [comment]
Maybe fixed. Feel free to reopen this issue if it's still exists in latest version.
