### ISSUE TITLE
rtl support + font arabic, persian

### ISSUE THREAD

**Issue by darth-ali** [usememos/memos#642]
### Is your feature request related to a problem?

when merging Persian with English it shows backwards
![photo_2022-11-30_12-35-39](https://user-images.githubusercontent.com/54251278/204754839-aa4d559c-cd3b-45bd-ab12-8ca9f08240a4.jpg)
backward

### Describe the solution you'd like

it would be great to add rtl content support and font for this awesome project
![image](https://user-images.githubusercontent.com/54251278/204755655-d302d09d-b660-4f6d-93b7-f153726c3b2f.png)

**Comment by boojack** [comment]
@darth-ali Glad to hear from Arabic! You can add a addition style in the systen setting with the following code. Then the rtl problem solved. 

```css
html {
  direction: rtl;
}
```

And maybe you can contribute the style and font you want.

**Comment by darth-ali** [comment]
> @darth-ali Glad to hear from Arabic! You can add a addition style in the systen setting with the following code. Then the rtl problem solved.
> 
> ```css
> html {
>   direction: rtl;
> }
> ```
> 
> And maybe you can contribute the style and font you want.

thank you for your reply I did this but English texts also changed to right to left things have gone ugly :)

**Comment by bpawel-bclub** [comment]
I was wondering if there were any news about Arabic / rtl support?
