### ISSUE TITLE
The last tag is sometimes not detected

### ISSUE THREAD

**Issue by behrouze** [usememos/memos#647]
### Describe the bug

Only the first tag is detected when typing tags in a new memo.
However, using the tag button of the editor allows adding multiple tags.

### Steps to reproduce

1. login or refresh (F5) the page
2. create a new memo with text and several tags
3. the last tag is not detected and not added to the tag list

### Screenshots or additional context

![image](https://user-images.githubusercontent.com/9475977/205057223-c57bffcf-6341-4a58-ab5b-89e8713882bc.png)

![image](https://user-images.githubusercontent.com/9475977/205059640-5159bf65-21e6-4c63-9dc9-ab93d9237bb6.png)

**Comment by boojack** [comment]
Please follow the best practices to write a tag. 
https://github.com/usememos/memos/wiki/Best-practices-to-write-a-TAG

**Comment by behrouze** [comment]
> Please follow the best practices to write a tag. https://github.com/usememos/memos/wiki/Best-practices-to-write-a-TAG

ok, look at the top 3 memos of the second screenshot, I think it meets your best practices.

**Comment by Zeng1998** [comment]
A space is required after the tag

**Comment by Zeng1998** [comment]
You can treat it as a trade-off for the current version but absolutely not a bug.
