### ISSUE TITLE
在Linux下，界面显示有BUG，详情见图

### ISSUE THREAD

**Issue by li-xunhuan** [usememos/memos#648]
### Describe the bug

如标题所示

### Steps to reproduce

打开即可

## 显示异常截图
![Screenshot_20221202_093145](https://user-images.githubusercontent.com/10476982/205194817-48b91879-8990-46a2-a731-72567b5eff22.png)
## 浏览器版本信息
![Screenshot_20221202_093235](https://user-images.githubusercontent.com/10476982/205194838-8fce537b-b582-4768-86de-6381c5f81621.png)

## 系统信息
![Screenshot_20221202_093301](https://user-images.githubusercontent.com/10476982/205194851-48d1d34d-1538-409d-a1e0-1615b5662c65.png)

**Comment by Mahoo12138** [comment]
这个问题，我曾经遇到过，深入发现是字体大小的缘故，可以尝试在浏览器调整字体试试

**Comment by Zeng1998** [comment]
Does this issue exist in the latest version?
