### ISSUE TITLE
Add React testing library

### ISSUE THREAD

**Issue by mzeenkala23** [usememos/memos#653]
### Is your feature request related to a problem?

I like the idea of having FE unit tests so the application can be more robust, and we can prevent accidentally creating new bugs when adding new features. 

### Describe the solution you'd like

We already of Jest installed so I would also like to install React testing library so we can begin to add FE unit tests.

**Comment by boojack** [comment]
@mzeenkala23 Sounds great to me. Could you help us with the FE unit tests in memos
