### ISSUE TITLE
几点改进的想法💡

### ISSUE THREAD

**Issue by lhuanyun** [usememos/memos#659]
+ 希望去除前端上的emoji图标，提升整体的高级感。
+ 希望在登录页面，页脚部分增设一个返回首页的按钮。方便返回使用。
+ 希望输入板是固定在顶部，下滑会缩到侧边成按钮。手机端，本身显示紧张，顶部浮动，浏览器标题也不会缩回，一下就占用了屏幕三分一的空间。手机端浏览体验大打折扣！
+ 从0.8版本开始，docker占用内存翻倍
+ 从0.8开始，进入主页拉取数据库时间比以往更加漫长。

**Comment by lhuanyun** [comment]
4.从0.8版本开始，docker占用内存翻倍
5.从0.8开始，进入主页拉取数据库时间比以往更加漫长。

**Comment by VitoYane** [comment]
内存可能是缓存的原因, 这是我用docker安装两个版本的内存对比
![1670904034287](https://user-images.githubusercontent.com/17432059/207223461-c99a490a-e68a-4453-b443-b935aa475a19.jpg)

![1670904034293](https://user-images.githubusercontent.com/17432059/207223474-9a9c6f07-4af4-4116-84d7-1ba1a89d35ba.jpg)

**Comment by lhuanyun** [comment]
服务器os Debian 11.0.5
我在docker stats 命令查看 0.7.3占用系统大约30MB的系统内存空间。
0.8.1 占用了130MB的内存空间

现在0.8.2似乎特别的低了，也许确实是缓存的原因。
经过12日凌晨，最新推送的景象拉取了一次memos 0.8.2 版本。目前我感觉已经特别完美，似乎不再有需要改进期望的东西🙏
