### ISSUE TITLE
Dark mode is not persistent

### ISSUE THREAD

**Issue by mariushosting** [usememos/memos#661]
### Describe the bug

If I send link to a friend of my explore page it will look white even though I set the dark mode. So the Dark mode is not persistent when you set it up?

### Steps to reproduce

Go to settings - Activate Dark Mode
Send your explore link to a friend.
The friend look the explore page and tell me this one is not set to dark only white.

**Comment by mariushosting** [comment]
I think its better to put the dark/light mode button on the explore page too.

**Comment by boojack** [comment]
> If I send link to a friend of my explore page it will look white even though I set the dark mode.

The dark mode appearance is a item of user setting not a global site setting. So it will not get your personal setting by a link. 

But I agree that the dark mode toggle button is also needed in other pages like explore.

**Comment by mariushosting** [comment]
I think a toggle button is the best option.

**Comment by ItsNoted** [comment]
I noticed this too and was a little bummed out. I hope it becomes a global setting soon.

**Comment by mariushosting** [comment]
I think this was solved in 0.8.2 version but still no change on my side. @boojack
