### ISSUE TITLE
Icon, Title and Sign in button Cover the First Memos

### ISSUE THREAD

**Issue by mariushosting** [usememos/memos#662]
### Describe the bug

Icon, Title and Sign in button Cover the First Memos when you scroll down the page. I think this should be sticked at the top. 

### Steps to reproduce

Icon, Title and Sign in button Cover the First Memos when you scroll down the page. I think this should be sticked at the top. First memos date and text is covered by the icon the name "memos" and the Sign in button.
![stick](https://user-images.githubusercontent.com/37554361/205384698-ebb3eec6-054d-4d8d-b2ba-c0df8d9d5587.png)

**Comment by boojack** [comment]
This header is sticky with backdrop blur style, and it's by design.
