### ISSUE TITLE
有没有什么方法可以同步到notion的database

### ISSUE THREAD

**Issue by IoriMaboroshi** [usememos/memos#676]
### Is your feature request related to a problem?

想要可以同步到notion数据库

### Describe the solution you'd like

使用notion的API？

**Comment by Vespa314** [comment]
我是自己用Notion API和memos的API写了个脚本放服务器上，每5分钟增量同步一次；

另外因为memos上的热力图显示的时间范围很小，所以我也自己做了个热力图的emb放进Notion里面；

根据我个人使用习惯，增加了互相引用的关系提取，做了个卡片墙（根据tag），加粗链接列表等语法的格式化，原文跳转，根据标签设置icon；

<img width="1556" alt="1" src="https://user-images.githubusercontent.com/6339395/207095820-75d1dbff-3cbe-4bc1-929b-ea907aa221fe.png">
<img width="1637" alt="2" src="https://user-images.githubusercontent.com/6339395/207095838-9dd51cc7-6fbc-4109-bd1f-d3d9a949a69c.png">
<img width="1421" alt="3" src="https://user-images.githubusercontent.com/6339395/207095846-c2028450-1d52-49f1-8e78-824912a1ac59.png">

**Comment by IoriMaboroshi** [comment]
我去尝试下试试看（x

**Comment by levie-vans** [comment]
> 我是自己用Notion API和memos的API写了个脚本放服务器上，每5分钟增量同步一次；
> 
> 另外因为memos上的热力图显示的时间范围很小，所以我也自己做了个热力图的emb放进Notion里面；
> 
> 根据我个人使用习惯，增加了互相引用的关系提取，做了个卡片墙（根据tag），加粗链接列表等语法的格式化，原文跳转，根据标签设置icon；
> 
> <img alt="1" width="1556" src="https://user-images.githubusercontent.com/6339395/207095820-75d1dbff-3cbe-4bc1-929b-ea907aa221fe.png">
> 
> <img alt="2" width="1637" src="https://user-images.githubusercontent.com/6339395/207095838-9dd51cc7-6fbc-4109-bd1f-d3d9a949a69c.png">
> 
> <img alt="3" width="1421" src="https://user-images.githubusercontent.com/6339395/207095846-c2028450-1d52-49f1-8e78-824912a1ac59.png">

如果可以发出来就好了

**Comment by ChasLui** [comment]
应该基于 webhook 来实现这个需求
