### ISSUE TITLE
中文#号无法创建tag的问题

### ISSUE THREAD

**Issue by vcan** [usememos/memos#677]
### Describe the bug

在使用产品的时候发现无法创建tag，一直找不到什么原因导致的

### Steps to reproduce

去看了下演示站点，发现可以创建，通过复制粘贴才发现，原来中文#和英文#不同导致的无法创建。
这块是否可以改进下?

**Comment by MASIJUN99** [comment]
实测 井号 + 标签名称 + 空格
即使标签是最后一个内容了 也要加个空格
