### ISSUE TITLE
DB size persists after clearing unused Resources

### ISSUE THREAD

**Issue by ItsNoted** [usememos/memos#684]
### Describe the bug

The size of the DB continues to persist in size even after clearing unused resources. I was hoping to shrink the size of the DB by removing memos and clearing unused resources. This is particularly important because it's SQLite and the more data used over time the slower the site will become.

### Steps to reproduce

Make several posts with images then permanently clear them and the used resources. The DB stays the same size which seems a bit counter productive for SQLite. It seems it's not actually permanently removing the data from the DB.

**Comment by Zeng1998** [comment]
Maybe you could execute `VACUUM` manually in SQLite

**Comment by ItsNoted** [comment]
> `VACUUM`

Yes, this works but using a 3rd party program to shrink the DB size seems a bit too much. However it does work so thank you.
