### ISSUE TITLE
[功能请求] 支持自定义站点标题和Logo

### ISSUE THREAD

**Issue by fcwys** [usememos/memos#698]
### Is your feature request related to a problem?

目前站点标题和Logo不能自定义

### Describe the solution you'd like

支持自定义站点标题和Logo

**Comment by Zeng1998** [comment]
可以通过自定义 Javascript 实现

**Comment by mariushosting** [comment]
> 可以通过自定义 Javascript 实现

你能提供一个javascript的例子吗

**Comment by Zeng1998** [comment]
> > 可以通过自定义 Javascript 实现
> 
> 你能提供一个javascript的例子吗

Hello, feel free to discuss in English.😁

And maybe you can refer to this and have a try #683

**Comment by boojack** [comment]
https://github.com/usememos/memos/discussions/683
