### ISSUE TITLE
emoji图标加载缓慢，希望支持切换国内CDN加速地址

### ISSUE THREAD

**Issue by fcwys** [usememos/memos#699]
### Describe the bug

emoji图标加载缓慢，cdn.jsdelivr.net稳定性欠佳

### Steps to reproduce

希望支持切换国内CDN加速地址，目前有如下CDN加速站点：
- 字节跳动CDN（https://cdn.bytedance.com/?query=emoji-datasource-apple）
- Staticfile CDN（https://staticfile.org/）
- BootCDN（https://www.bootcdn.cn/emoji-datasource-apple/）
- CDNJS（https://cdnjs.cloudflare.com/ajax/libs/emoji-datasource-apple/）

**Comment by Zeng1998** [comment]
emoji 功能在下个版本之后应该会被去掉
