### ISSUE TITLE
[功能请求]能否支持vercel部署  

### ISSUE THREAD

**Issue by wxydejoy** [usememos/memos#704]
### Is your feature request related to a problem?

vercel部署

### Describe the solution you'd like

vercel部署  的效果不用多说,非常好用,不知道能不能支持

### Additional context

https://vercel.com/dashboard

**Comment by wxydejoy** [comment]
vercel也是可以跑后端js的, 也可以连接数据库操作等等
我看项目是 go 写的 不知道有没有可能

**Comment by wxydejoy** [comment]
说白了就是不想用服务器(我有一个腾讯云),不长久,服务器的价格也是很难搞,想一直用,而不是两三年

**Comment by boojack** [comment]
Vercel 只支持部署静态资源，无法做到数据持久化。

* https://vercel.com/guides/does-vercel-support-docker-deployments
* https://vercel.com/guides/is-sqlite-supported-in-vercel

**Comment by wxydejoy** [comment]
好吧

**Comment by xia0bs** [comment]
那可不可以用notion作后端数据库，vercel作前端页面渲染，github作辅助什么的

**Comment by wnbiliblog** [comment]
> Vercel 只支持部署静态资源，无法做到数据持久化。
> 
> * https://vercel.com/guides/does-vercel-support-docker-deployments
> * https://vercel.com/guides/is-sqlite-supported-in-vercel

Vercel已经可以部署PHP了

**Comment by mapxn** [comment]
我看有人已经在vercel部署成功了。
后端数据可以放到mysql/postgre/sqlite（许多在线平台提供服务）等，图片等资源文件有Cloudflare的R2。
