### ISSUE TITLE
Confirmation popup on accidental escape button press

### ISSUE THREAD

**Issue by DJScias** [usememos/memos#705]
### Is your feature request related to a problem?

Apparently pressing escape immediately removes the memo you were typing without any sort of confirmation.

Ran into this today by having a cat walk near my keyboard and laying down next to it, removing the whole unsaved memo (seems to also be a thing when you edit memos).

### Describe the solution you'd like

Perhaps a sort of confirmation message on escape press if there's text in the box?

It's a QOL at most, but in my case I use memos to write planning agendas for my job and they're quite lengthy at times so an accidental button press can be quite a loss.

### Additional context

No worries if this is not needed/interesting QOL. But since it's something I've faced myself recently I figured I would at least ask about it (maybe it's not even intentionally missing?).

**Comment by DJScias** [comment]
> > Apparently pressing escape immediately removes the memo you were typing without any sort of confirmation.
> 
> Cannot reproduce, please check again in https://demo.usememos.com/.
> 
> > Ran into this today by having a cat walk near my keyboard and laying down next to it, removing the whole unsaved memo (seems to also be a thing when you edit memos).
> 
> lol 🤣

Hello there,

Attached is a gif that shows what I mean. I typed something in there, then pressed escape (what my cat did) and all the input was gone.

![brave_QsqViFJyAC](https://user-images.githubusercontent.com/439655/206524081-0eadecfe-62f7-4ea4-b413-967552fd6b8c.gif)

**Comment by Zeng1998** [comment]
I found this before... but I regard it as a feature, lol.

So I think we could add a confirm dialog (or other ways) when press `ESC` or click `Cancel edit`.
