### ISSUE TITLE
手动粘贴的图片链接，生成分享时出错

### ISSUE THREAD

**Issue by whoistiger** [usememos/memos#71]
![image](https://user-images.githubusercontent.com/46469762/172527992-440db1c9-7440-4b35-8060-17a81a610b66.png)
![image](https://user-images.githubusercontent.com/46469762/172528015-a8a7590f-8629-4b9d-bbc5-abbc797be517.png)

**Comment by boojack** [comment]
最好是你的图床能支持 CORS：
https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image#security_and_tainted_canvases

---

比如像 GitHub 的图片链接就是可以的
<img width="512" src="https://user-images.githubusercontent.com/24653555/172747730-37130d8f-9ec9-434a-9b79-16bfb7141e45.png"/>

**Comment by whoistiger** [comment]
ok，我去试试看
