### ISSUE TITLE
Wrong hashtag

### ISSUE THREAD

**Issue by bxb100** [usememos/memos#710]
### Describe the bug

Write code block with `#`, but it show as a hashtag

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/20685961/206613925-a4fd8f01-1cb7-4600-8611-a62233ee1d69.png">

### Steps to reproduce

see upper image

### Screenshots or additional context

see upper image

**Comment by Zeng1998** [comment]
Duplicate of #629
