### ISSUE TITLE
Tags can't be created

### ISSUE THREAD

**Issue by gitjax** [usememos/memos#712]
### Describe the bug

After creating a new entry giving two new tags (on a completely new install) it seems no tags can be created after.

For example:  

#one  #two
blah blah

.... no tags get created and I can't create any tags after this.

Am I supposed to be able to have multiple tags in one entry?

### Steps to reproduce

1. In a new install, create an entry with two tags.
2. save

**Comment by gitjax** [comment]
I apologize. I just realized that you have to put a space after the tag name.

**Comment by TheNomad11** [comment]
> I apologize. I just realized that you have to put a space after the tag name.

Thanks, therefore! That's not obvious, maybe you should keep this issue open? Still sounds like a little bug to me
