### ISSUE TITLE
Bug: 输入内容含有空格，但保存后丢失

### ISSUE THREAD

**Issue by leopold7** [usememos/memos#72]
### 1.问题描述
输入内容含有空格，但保存后丢失了一个空格

### 2.代码
```
#docker #nginx
docker run -d -p 80:80 -p 81:81 -p 801:801 --name nginx-server -v C:/Users/leopold/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf -v C:/Users/leopold/nginx/www:/usr/share/nginx/html -v C:/Users/leopold/nginx/conf/nginx.conf:/etc/nginx/nginx.conf -v C:/Users/leopold/nginx/logs:/var/log/nginx nginx:1.22.0
```

### 3.结果
![image](https://user-images.githubusercontent.com/77429266/172558331-fce52ea1-12eb-4910-8fc3-341343ab12d4.png)

### 4.是否能复现
本地能复现

### 5.临时解决方法
标签与内容之间若无回车符可临时解决此问题

**Comment by leopold7** [comment]
```
	map $http_upgrade $connection_upgrade {
				default upgrade;
				'' close;
	}
```
![image](https://user-images.githubusercontent.com/77429266/172561575-70e3243e-669b-49a5-a1c0-f0fd51dc84e7.png)

**Comment by boojack** [comment]
FYI，tag 最后应该跟个空格 `/#(.+?) /g`
