### ISSUE TITLE
能增加一个通过tag获取数据的webhook么

### ISSUE THREAD

**Issue by rebron1900** [usememos/memos#73]
server/webhook.go  能增加一个通过tag获取数据的webhook么？

**Comment by rebron1900** [comment]
大佬，日常催更新。
1. 网页端适配
2. 微信渠道适配。

**Comment by boojack** [comment]
`GET /h/:openID/memo?tag=:tagName`
例如：GET /h/myOpenID/memo?tag=todo` 会得到所有标签为 `todo` 的 memo。

**Comment by boojack** [comment]
> 大佬，日常催更新。
> 
> 1. 网页端适配
> 2. 微信渠道适配。

最近有点忙，实在没空😵‍💫。
