### ISSUE TITLE
图片文件名不能带括号,否则无法正常预览

### ISSUE THREAD

**Issue by JiangLongLiu** [usememos/memos#736]
### Describe the bug

如果图片被命名位  ` 图片(1).jpg` 那么图片就无法预览,也无法正常显示。

### Steps to reproduce

1.修改图片名称为 ` 图片(1).jpg`这种格式
2.上传图片到资源库
3.预览或者在编辑区插入图片,都无法正常显示

**Comment by HiteshGorana** [comment]
I followed the above steps seems working for me here is the screenshot 
![image](https://user-images.githubusercontent.com/42089577/206958386-69c2d2ac-45eb-4a36-a8ab-74f3d9cefcff.png)

**Comment by Zeng1998** [comment]
> I followed the above steps seem to be working for me here is the screenshot
> 
> ![image](https://user-images.githubusercontent.com/42089577/206958386-69c2d2ac-45eb-4a36-a8ab-74f3d9cefcff.png)
> 
> ![image](https://user-images.githubusercontent.com/42089577/206958658-90dd94a7-62dd-4e35-8fa8-7c421702d49a.png)

Hello, which version? I tried in demo and it is not working.

https://demo.usememos.com/

![image](https://user-images.githubusercontent.com/31177490/206962441-e226d8e2-f06d-4f29-80af-3bb0fdd3e6f2.png)

**Comment by HiteshGorana** [comment]
Here :  tag: v0.8.2
