### ISSUE TITLE
图片放大后，无法拖动图片，无法正常阅览放大后的图片全貌。

### ISSUE THREAD

**Issue by leoneoo** [usememos/memos#745]
### Describe the bug

Memos 版本:
V 0.8.2

图片放大后，无法拖动图片，因此无法正常阅览放大后的图片全貌。最好可以增大一个放大按钮，拖动图片功能。

### Steps to reproduce

图片放大后，无法拖动图片，因此无法正常阅览放大后的图片全貌。

### Screenshots or additional context
<img src="https://oneoo-1253919472.cos.ap-shanghai.myqcloud.com/oneooimg/TP.png"/>
_No response_

**Comment by Zeng1998** [comment]
建议是通过鼠标移动到需要放大的地方，然后再放大，这样来操作

**Comment by leoneoo** [comment]
> 建议是通过鼠标移动到需要放大的地方，然后再放大，这样来操作

拖不动，我测试了Edge、Chrome浏览器都无法移动或者拖动图片。

**Comment by Zeng1998** [comment]
> > 建议是通过鼠标移动到需要放大的地方，然后再放大，这样来操作
> 
> 拖不动，我测试了Edge、Chrome浏览器都无法移动或者拖动图片。

不是拖动，是想放大哪里就把鼠标移动到哪里

**Comment by leoneoo** [comment]
非常感谢。我可能只是使用习惯问题，一下子没有适应。浮墨flomo的图片预览方案建议大大也可以参考一下。这个项目真的很棒，希望它越来越强大，越来越完美！！！感谢！！！

**Comment by Zeng1998** [comment]
因为这种放缩方式可以直接使用CSS来处理，比较方便；如果要支持图片的拖动会引入更多的复杂度，暂时还没想到比较好的处理方法。

这个issue先关闭了，欢迎把 ”浮墨flomo的图片预览方案“ 录制一段视频（因为我没用过flomo）发到discussion上，之后有时间我们可以参考一下。
