### ISSUE TITLE
Failed to fetch memo list, internal=no such column: visibility

### ISSUE THREAD

**Issue by DJScias** [usememos/memos#750]
### Describe the bug

Logging into today on memos (using the dev tag, AKA latest main) causes memos not to show.

### Steps to reproduce

1. Log in.
2. Notice no memos.
3. Top-right corner says "Failed to fetch memo list"

### Screenshots or additional context

Logs is spammed with stuff like this:
```
2022-12-16T13:06:23Z method=GET uri=/api/memo/stats?creatorId=1 status=500 error=code=500, message=Failed to fetch memo list, internal=no such column: visibility
2022-12-16T13:06:23Z method=GET uri=/api/memo?rowStatus=NORMAL&limit=30 status=500 error=code=500, message=Failed to fetch memo list, internal=no such column: visibility
2022-12-16T13:06:23Z method=GET uri=/api/memo/stats?creatorId=1 status=500 error=code=500, message=Failed to fetch memo list, internal=no such column: visibility
```

Empty page after login, while I know I have memos set up.
![image](https://user-images.githubusercontent.com/439655/208105170-e2bb4169-94f0-4405-ba56-895b39e1500b.png)

**Comment by Zeng1998** [comment]
try to delete the `.air/` and re-run

**Comment by DJScias** [comment]
Hello there,

Where would I find that? The only file that docker made regarding memos on my filesystem is `memos_prod.db` in the volume I assigned it to (per docker-compose's `/var/opt/memos`).

**Comment by Zeng1998** [comment]
Hello, see this about the development of the memos.  https://github.com/usememos/memos/blob/main/docs/development.md.

Actually I don't recommend to use the dev image  if you are not familier enough  with docker.

**Comment by DJScias** [comment]
> Hello, see this about the development of the memos. https://github.com/usememos/memos/blob/main/docs/development.md.
> 
> Actually I don't recommend to use the dev image if you are not familier enough with docker.

Hello there,

Fixed the issue myself by running the updated SQL on the db. However I should mention that there's an error in the following file:
https://github.com/usememos/memos/blob/main/store/db/migration/prod/0.9/00__resource_visibility.sql

It currently says:
```SQL
ALTER TABLE resource ADD COLUMN visibility TEXT NOT NULL CHECK (visibility IN ('PUBLIC', 'PROTECTED' 'PRIVATE')) DEFAULT 'PRIVATE';
```

but it should be:
```SQL
ALTER TABLE resource ADD COLUMN visibility TEXT NOT NULL CHECK (visibility IN ('PUBLIC', 'PROTECTED', 'PRIVATE')) DEFAULT 'PRIVATE';
```

Otherwise it'll error because `'PRIVATE'` broke the IN operator value list.

Thanks for the help though.
