### ISSUE TITLE
back dated memos?

### ISSUE THREAD

**Issue by somedevreally** [usememos/memos#765]
### Is your feature request related to a problem?

hello,

great project, can there be a feature to change date of the memo?

### Describe the solution you'd like

like back date or past date

thanks

**Comment by Zeng1998** [comment]
try to double click the time of a memo.

![image](https://user-images.githubusercontent.com/31177490/208272362-73fe8606-f9ba-4ec7-b933-3f578d31c3b5.png)

**Comment by somedevreally** [comment]
this is awesome, thanks

**Comment by Zeng1998** [comment]
update

https://github.com/usememos/memos/issues/1017#issuecomment-1537354763
