### ISSUE TITLE
"Database is locked" on large database

### ISSUE THREAD

**Issue by sebw** [usememos/memos#776]
### Describe the bug

I decided to test how Memos scales by uploading about 2900 pictures and creating 2900 posts. I indeed noticed everything is stored in DB, including pictures.

The resulting DB is 548 MB.

Now database locks up when trying new posts or edits.

```
{"time":"2022-12-18T18:26:02Z","method":"GET","uri":"/api/memo?rowStatus=NORMAL&offset=180&limit=30","status":200,"error":""}
{"time":"2022-12-18T18:26:09Z","method":"PATCH","uri":"/api/memo/1805","status":500,"error":"code=500, message=Failed to patch memo, internal=database is locked"}
{"time":"2022-12-18T18:26:09Z","method":"GET","uri":"/api/memo/stats?creatorId=1","status":500,"error":"code=500, message=Failed to fetch memo list, internal=database is locked"}
{"time":"2022-12-18T18:26:09Z","method":"GET","uri":"/api/memo/stats?creatorId=1","status":500,"error":"code=500, message=Failed to fetch memo list, internal=database is locked"}
{"time":"2022-12-18T18:26:09Z","method":"GET","uri":"/api/memo?rowStatus=NORMAL&offset=210&limit=30","status":500,"error":"code=500, message=Failed to fetch memo list, internal=database is locked"}
{"time":"2022-12-18T18:26:10Z","method":"GET","uri":"/api/tag?","status":200,"error":""}
```

### Steps to reproduce

- upload many pictures (initially started with 1800 pics) and create as many posts (over API)
- try to use Memos (new posts, edit posts)

**Comment by boojack** [comment]
> This error code occurs when you try to do two incompatible things with a database at the same time from the same database connection.

https://stackoverflow.com/a/218622

**Comment by sebw** [comment]
I'm using the web app normally. This is clearly due to performance issues. Also the web UI spams the API itself spamming the DB (issue #380), all while trying to edit a post and this causes havoc.
