### ISSUE TITLE
#Hashtag at the end of a post needs a space

### ISSUE THREAD

**Issue by arnehm2000** [usememos/memos#777]
### Describe the bug

When I write a memo with a #hashtag at the end of the post it won't recognize it as an #hashtag. I allways need to put an " " space behind it.

### Steps to reproduce

- Write a memo like:
- "testmemo #memo"
- after posting there won't be a #memo hashtag.

**Comment by m-gschwandtner** [comment]
This is intended behavior, as far as I know,
I don't believe this is mentioned in the wiki tough.

Adding it under: “Syntaxes > Something special > 2.”,
would be a good idea.

**Comment by arnehm2000** [comment]
thank you for your feedback! it's not a bug, it's a feature. i will close this now.
