### ISSUE TITLE
Export memos to file

### ISSUE THREAD

**Issue by Akitakek** [usememos/memos#778]
### Is your feature request related to a problem?

I would like to use this app however I'm concerned about the ability to backup data or potentially export it for external use.

### Describe the solution you'd like

A simple archive export with a folder structure that makes sense

Just an example:
```
memos.zip
  dd-mm-yyyy/
    resources/
    memo1.txt
    memo2.txt
    [...]
```

**Comment by jxpsert** [comment]
What about simply copying over the .db file to a backup location?

**Comment by smoothml** [comment]
I would love to see this feature, not for backup purposes but to ensure users aren’t tied into a specific tool.

**Comment by i-iooi-i** [comment]
This function is required. If you can export PDF or TXT, it is an acceptable choice.

**Comment by bonnebulle** [comment]
I just upgrade.
An export/import database (into file) should help in the process. 
Maybe not an urgent feature but a good one :)

**Comment by erbanku** [comment]
I have a problem. Where are the image assets and other data saved when using the docker version?
I want to back up the memos instance to prevent losing access because of circumstances.

**Comment by bonnebulle** [comment]
I Noob too, my first docker try . I do :

# Backup files

### 1. Get Docker container id 
( alpha_digit like 4334cf36a826 ) :
```bash
docker ps
```
( optional : access to the terminal in the container )
```bash
docker exec -it 4334cf36a826 /bin/sh
```
( then check files presence )
```bash
ls -lh /var/opt/memos/
# then exit, back to host
exit
```

### 2. Backup files from container to your host ( here a Desktop folder ) 
```bash
docker cp 4334cf36a826:/var/opt/memos/memos_prod.db-wal ~/Desktop/memos_docker_save/
```
-> Do it for memos_prod.db + memos_prod.db-shm (I think necessary)
---

# To Restore :
( test, try, before crisis time )
```bash
sudo docker cp ~/Desktop/memos_docker_save/memos_prod.db-wal 4334cf36a826:/var/opt/memos/memos_prod.db-wal
```
-> and other files

**Comment by bonnebulle** [comment]
```bash
#!/bin/bash
DATE=$(date +'%Y-%m-%d')
ROOTBKPFOLDER="/media/BC_01C/@bkp_BC01/@cron/Docker/Memos"
ROOTBKP=$ROOTBKPFOLDER/$DATE
# echo $ROOTBKP
cd $ROOTBKPFOLDER
mkdir $DATE

docker cp memos:/var/opt/memos/memos_prod.db $ROOTBKP
docker cp memos:/var/opt/memos/memos_prod.db-shm $ROOTBKP
docker cp memos:/var/opt/memos/memos_prod.db-wal $ROOTBKP

# CLEANUP
# ls -t | tail -n +10 | xargs -I {} rm -f ./{}
```

**Comment by hyoban** [comment]
Here is a website that can export Memos to a local zip, https://github.com/hyoban/note-convert . Try to use it. If you have any problems, you can open an issue, I will try my best to support.

**Comment by erbanku** [comment]
> Here is a website that can export Memos to a local zip, [hyoban/note-convert](https://github.com/hyoban/note-convert) . Try to use it. If you have any problems, you can open an issue, I will try my best to support.

The exported resource images seem to be broken. The images resources can be shown normally on the Memos Web App. (The resources are in my object storage which links to Memos)

![image](https://user-images.githubusercontent.com/79493862/236718410-d378ec64-739e-4343-8a5e-cc10980317dc.png)

**Comment by hyoban** [comment]
@erbanku I haven't used object storage in Memos yet, I'll try to find out why

**Comment by hyoban** [comment]
@erbanku This problem has been fixed, if you have more problems, you can open an issue in https://github.com/hyoban/note-convert

**Comment by wu0lei** [comment]
The earlier version only had memos_prod.db, but not memos_prod.db-shm and memos_prod.db-wal, please advise how to migrate, thanks

**Comment by erbanku** [comment]
> The earlier version only had memos_prod.db, but not memos_prod.db-shm and memos_prod.db-wal, please advise how to migrate, thanks

Upgrade the earlier version of the Memos instance, then migrate to the newer Memos instance?
