### ISSUE TITLE
sync between different devices

### ISSUE THREAD

**Issue by changchichung** [usememos/memos#779]
### Is your feature request related to a problem?

I always add a lot of notes in the office, but I still use them from time to time when I get home or even in my phone.

### Describe the solution you'd like

maybe add a shared database or upload these "notes" to a specified storage on internet , so I can sync notes from different devices

**Comment by boojack** [comment]
Maybe you need an online server to host memos.

**Comment by jxpsert** [comment]
A SaaS (software as a service) version of memos would be possible, but I doubt it's on the planning anytime soon. Memos is made to self-host.
