### ISSUE TITLE
redo/undo

### ISSUE THREAD

**Issue by ChasLui** [usememos/memos#801]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

The editor currently uses the browser textarea comes with redo/undo, but in the call insertText can not generate the browser default undoStack, to solve this problem there are several options.

1. use document.execCommand to replace the current editorRef.current.value assignment, but this api is no longer recommended.

2. generate a snapshot of editorRef.current.value and use the snapshot stack to replace the current value when redo/undo. 3.

3. abstract command and transaction, when modifying content to generate a transaction, including content changes and cursor changes, which is the design of modern rich text editors.

If no one has implemented it I can pr a draft

**Comment by boojack** [comment]
@ChasLui The option2 LGTM. Please have a try.

**Comment by AIndoria** [comment]
I just find out that this doesn't have redo/undo after deleting some changes I've made trying to indent them via select-all, tab (doesn't work), and they're just....gone?

Quite a limitation.
