### ISSUE TITLE
Markdown Table

### ISSUE THREAD

**Issue by ivishalgandhi** [usememos/memos#804]
### Is your feature request related to a problem?

Table|col
|---|---|
test1|test2

I am using above to create Markdown Table. Not able to see in Memo preview. Is markdown table supported ? 

### Describe the solution you'd like

Provide option to use Markdown tables

**Comment by boojack** [comment]
@ivishalgandhi memos should be used to record those simple contents. The markdown table, on the other hand, has a complex syntax and is difficult to use, so it was removed and will no longer be supported.
