### ISSUE TITLE
hashtag without a space or line below is not converted to tag

### ISSUE THREAD

**Issue by ivishalgandhi** [usememos/memos#805]
### Describe the bug

In my memo notes if i document as below. Please see #note is not having any space or line below the hashtag, its not getting converted to tag and not displayed in tags.

This is hashtag note
#note

### Steps to reproduce

In my memo notes if i document as below. Please see #note is not having any space or line below the hashtag, its not getting converted to tag and not displayed in tags.

This is hashtag note
#note

### Screenshots or additional context

![image](https://user-images.githubusercontent.com/12184532/208818288-825463b7-449c-40da-8c09-1e27167a1f68.png)

**Comment by Zeng1998** [comment]
https://github.com/usememos/memos/wiki/Best-practices-to-write-a-TAG

**Comment by ivishalgandhi** [comment]
Noted. Thank you. Even if its on the last line and there is no space after the hashtag, its not getting displayed or considered as a Tag.
