### ISSUE TITLE
New dashboard for resource list

### ISSUE THREAD

**Issue by boojack** [usememos/memos#821]
Now, the resource list dialog is very simple. We need a more powerful dashboard. e.g. [aliyundrive](https://www.aliyundrive.com/)

![Image](https://user-images.githubusercontent.com/24653555/207078850-479a07e4-e33a-47ee-bf85-e04337e33769.png)

**Comment by winwangqi** [comment]
Why do users need to care about resources? I think users only need to care about memos, and resources should be managed automatically at the application level.
