### ISSUE TITLE
When i type quote like " or '. Memos type a second time quote.

### ISSUE THREAD

**Issue by zatoufly** [usememos/memos#845]
### Describe the bug

When i type quote like " or '. Memos type a second time quote.

In French it's a real problem for some word I type : "j'ai" "Aujourd'hui" for exemple

bug appear in 0.19.0

### Steps to reproduce

1. Create a new memos
2. type ' or "
3. memos return : "" or ''

i would like memos return just " or '

### Screenshots or additional context

![image](https://user-images.githubusercontent.com/76479469/209369146-48a590f2-ba58-4a4a-bec8-cc401a36a7b4.png)

**Comment by nitinthewiz** [comment]
I see this is closed and I found the toggle for the power editor as well, but there's no explanation for what all the power editor does. Does it only add the double " feature or does it do more? Could you please add this information to the usememos website? Thanks!
