### ISSUE TITLE
GitHub pages markdown/docsify wiki

### ISSUE THREAD

**Issue by m-gschwandtner** [usememos/memos#846]
### Is your feature request related to a problem?

Not it's not.

### Describe the solution you'd like

Moving the wiki and '/docs' to a uniformed folder (something like /wiki/...).

With [docsify](https://github.com/docsifyjs/docsify) making a searchable and pretty good-looking wiki would then be pretty easy.

- files are still markdown
- hosted with GitHub Pages

I created a repo with most of the Setup:
https://github.com/m-gschwandtner/memos-test-wiki

Here is the GitHub pages link:
https://m-gschwandtner.github.io/memos-test-wiki/#/

Would make the Wiki a bit easier to use / navigate and to contribute to,
not sure if it currently makes a lot of sense since there are not a lot of wiki page.

Merry Christmas! :purple_heart:

PS. Open to creating PR.

### Additional context

https://m-gschwandtner.github.io/memos-test-wiki/#/

![image](https://user-images.githubusercontent.com/84477901/209391471-f5a91fd4-1b4d-41cb-9ed2-647507c151f1.png)

**Comment by boojack** [comment]
Thanks for sharing! I'd really like to have a documentation site for memo. But our current content is very poor, only a few "articles". IMO, writing more wiki/docs has higher priority. 

When we get the full documentation content, the separate documentation site can be done with few works.

Merry Christmas!! 💗
