### ISSUE TITLE
Dark mode Explore Page Always White for new users.

### ISSUE THREAD

**Issue by mariushosting** [usememos/memos#850]
### Is your feature request related to a problem?

As already explained here https://github.com/usememos/memos/issues/661
there is no option for Dark mode on explore page when new user are coming to see your notes. 
I see the option only on login page but not on explore page.
I miss something here?

### Describe the solution you'd like

The buttons dark mode, light mode etc present in the sign in page should be also visible in the explore page so unregistered user can easily switch the theme.

**Comment by boojack** [comment]
<img width="791" alt="image" src="https://user-images.githubusercontent.com/24653555/209420947-097e781a-a0c4-44cb-af8c-10802bc1d363.png">

**Comment by mariushosting** [comment]
Thank you, 
forget to add the description. So when save it need to insert all field!

**Comment by mariushosting** [comment]
@boojack the issue is back again in Memos 0.18.1
