### ISSUE TITLE
每日回顾分享样式BUG

### ISSUE THREAD

**Issue by rebron1900** [usememos/memos#854]
### Describe the bug

分享当天memos，如果标签在前，后面跟一个checkbox，就会出现下面截图的BUG

### Steps to reproduce

-

### Screenshots or additional context

![image](https://user-images.githubusercontent.com/7929884/209436297-dc6ea1b3-6713-4d65-aa7a-9649b6ebc7b2.png)

**Comment by Zeng1998** [comment]
"如果标签在前，后面跟一个checkbox"   这个是什么意思？ 最好提供下具体能复现的memo内容

**Comment by boojack** [comment]
@rebron1900 应该已经修复了，麻烦有空到 demo 再尝试复现下。
