### ISSUE TITLE
After upgrade to 0.9.0 (docker version), tags on the left are gone

### ISSUE THREAD

**Issue by bofeng** [usememos/memos#855]
### Describe the bug

I upgraded to the lasted docker image of memos, after that, all of my memos are still there, **but the tags on the left side are gone**. It used to have a list of tags.

BTW, I love this project a lot, please keep the great work! Happy holidays! 🎄 

### Steps to reproduce

1. stop current running docker container 
2. docker pull neosmemo/memos:latest
3. start docker container with neosmemo/memos:latest again.
4. visit the website

### Screenshots or additional context

<img width="311" alt="Screenshot 2022-12-24 at 7 09 57 PM" src="https://user-images.githubusercontent.com/3884670/209453719-80a3bb64-e252-41c8-86a8-c2009d357046.png">

**Comment by Zeng1998** [comment]
![image](https://user-images.githubusercontent.com/31177490/209454850-3ffbcc4c-0ba5-4b48-a9a4-7ad14aec62b5.png)

Please click here and add your tags from `tag suggestions`.

**Comment by bofeng** [comment]
ah I am sorry, didn't notice this was changed. Thank you all again for this great project!
