### ISSUE TITLE
Email reminders and SMTP

### ISSUE THREAD

**Issue by sumitmamoria** [usememos/memos#858]
### Is your feature request related to a problem?

I want something like a "remind me later" and "recurring reminders" buttons against all individual entries, specially for TODOs. The alerts/reminders can be pushed over email via any public or private SMTP server. 

### Describe the solution you'd like

Adding SMTP server configuration to the application along with  "remind me later" and "recurring reminders" buttons on the UI might be worthwhile.

**Comment by ChasLui** [comment]
I think we can abstract the push notification service, like [novuhq/novu](https://github.com/novuhq/novu), which already supports future push from various providers, such as email, chat, etc.

**Comment by sumitmamoria** [comment]
> I think it is possible to abstract a push notification service, like [novuhq/novu](https://github.com/novuhq/novu). Support future push from multiple providers, such as email, chat, etc.

Thats right. I like "novuhq/novu", but even a basic SMTP support could be really helpful.

**Comment by ItsNoted** [comment]
I think implementing [Apprise](https://github.com/caronc/apprise) would be amazing. This way we can choose whatever we want to use as a notification be it email or any of the hundreds of push notification services.

**Comment by ItsNoted** [comment]
Any thoughts on this @boojack

**Comment by rounakdatta** [comment]
+1, a schedule for later / reminder system would be awesome!
