### ISSUE TITLE
Child tag detection

### ISSUE THREAD

**Issue by MelihDarcanxyz** [usememos/memos#859]
### Describe the bug

Memo can't dynamically detect tags, being able to edit them manually would help a lot.

### Steps to reproduce

1. Create a memo with tag #x and tag #y
2. Then decide that it should be like #x/y
3. Change it to #x/y
4. There are no other individual #y tags
5. Memo still can't see that y is a child of x, it thinks that they are seperate tags.

### Screenshots or additional context

Left side of the screen, tags, doesn't update accordingly.

**Comment by boojack** [comment]
duplicated with #853
