### ISSUE TITLE
0.9.0不显示旧标签

### ISSUE THREAD

**Issue by xxzj990** [usememos/memos#863]
### Describe the bug

升级0.9.0后，所有旧的标签在左侧边栏不显示，只有新增或者编辑后的标签才能显示。

用
https://demo.usememos.com/
做了测试，应该也存在这个问题，不显示Hello这个标签，编辑后才会显示在左侧边栏。

### Steps to reproduce

升级后打开应用

**Comment by Zeng1998** [comment]
duplicated of #855
