### ISSUE TITLE
希望可以添加“快捷插入”的功能

### ISSUE THREAD

**Issue by Lea321** [usememos/memos#865]
### Is your feature request related to a problem?

希望可以添加一个"快捷插入"的功能，就类似于一些输入法的"常用语"功能。

### Describe the solution you'd like

用户可以自己添加一些常用的模板，通过点击快速的插入文中。比如markdown的插入图片语句“![]()”，我添加好之后只需要点击即可使用，而不需要每一次都进行输入。

**Comment by Zeng1998** [comment]
已经有快捷键支持了

**Comment by boojack** [comment]
会经常使用到的 markdown 语法已经加在了 toolbar，比如 TODO 块、代码块。至于加入图片，不太推荐使用 markdown 的图片语法，而是通过 resource 来实现。
