### ISSUE TITLE
保存为PWA应用时，自定义图标不生效

### ISSUE THREAD

**Issue by yefoenix** [usememos/memos#866]
### Describe the bug

0.9.0版本下自定义了应用图标，但保存为PWA应用时图标显示为默认图标

### Steps to reproduce

1. 在Memos服务内设置自定义站点图标
2. 在 Edge 浏览器下将 Memos 保存为 PWA 应用，勾选“创建桌面快捷方式”

### Screenshots or additional context

![image](https://user-images.githubusercontent.com/8215230/209618864-ac71fa5b-0beb-4e6c-bbc7-7cf2ea8fd108.png)

**Comment by boojack** [comment]
You can change the icon in code level and build from source code.
