### ISSUE TITLE
Not able to browse Tags after upgrading to 0.9.0

### ISSUE THREAD

**Issue by ivishalgandhi** [usememos/memos#867]
### Describe the bug

Tag tree on the left pane is blank immediately after upgrade 

<img width="240" alt="image" src="https://user-images.githubusercontent.com/12184532/209647880-f21d9b02-d4dd-40e1-88e2-2bddba9a169a.png">

### Steps to reproduce

1. Upgrade to 0.9.0 
2. Login 
3. Tags on the left pane are blank

### Screenshots or additional context

<img width="240" alt="image" src="https://user-images.githubusercontent.com/12184532/209647890-7cb1eac2-79cf-45b9-bd43-af4f17f0c817.png">

<img width="339" alt="image" src="https://user-images.githubusercontent.com/12184532/209648114-6474fadf-1cca-480f-a563-38882518e959.png">

**Comment by boojack** [comment]
@ivishalgandhi FYI https://github.com/usememos/memos/issues/855

**Comment by ivishalgandhi** [comment]
Thank you :)
