### ISSUE TITLE
默认的密码是多少？

### ISSUE THREAD

**Issue by figo001** [usememos/memos#87]
之前test和guest的密码都是123456，但是现在出入密码会出现😟 Request failed with status code 400

**Comment by boojack** [comment]
现在对于 prod 环境不会 seed data，在第一次进入时需要设置管理员的账号信息

**Comment by whoistiger** [comment]
开发环境
默认登录邮箱：demo@usememos.com
默认密码：secret


昨天测试找了好久才找到，部署文档也没有注明。
最后是在 SQL 中找到的

https://raw.githubusercontent.com/usememos/memos/main/store/db/seed/10001__user.sql

**Comment by figo001** [comment]
试了下这个账号密码，不知道什么原因无法登上。
但我自己的尝试，第一次登录是直接输入自己设定的邮箱和密码，之后登录就用第一次那个邮箱和密码即可。







| |
figo
|
|
***@***.***
|
在2022年6月24日 ***@***.***> 写道：

开发环境
***@***.***
默认密码：secret

昨天测试找了好久才找到，部署文档也没有注明。
最后是在 SQL 中找到的

https://raw.githubusercontent.com/usememos/memos/main/store/db/seed/10001__user.sql

**Comment by rebron1900** [comment]
新安装的话第一次是让你设置账号密码

**Comment by rebron1900** [comment]
@boojack 多语言可以搞起来了。
