### ISSUE TITLE
资源库-清除无用资源，会把所有通过api上传的图片删除

### ISSUE THREAD

**Issue by JeazW** [usememos/memos#873]
### Describe the bug

当我点击清除无用资源的时候,会列出大量**有用资源**
![image](https://user-images.githubusercontent.com/75829171/209922324-5841f00b-b437-49de-a07d-806efd121501.png)
这些被删除的**有用资源**有一个共同点--都是用api上传的，他们的格式是这样
![image](https://user-images.githubusercontent.com/75829171/209922494-c2a28b36-3c72-4e68-a9d9-09097d2006d5.png)
个别没有被删除的资源，他们的格式是这样（这些图片都是通过附件上传的方式上传的）
![image](https://user-images.githubusercontent.com/75829171/209922777-de7d1d4b-1850-47aa-9749-2585c496cdf6.png)

_这些通过api上传的图片只在resource和memo字段里出现，并没有插入到memo_resource表中，可能与此有关_

**ps:api上传方式用的 memos-proxy [memos.py](https://github.com/ZhaoUncle/memos-proxy/blob/main/memos.py)**

### Steps to reproduce

1.点击 资源库
2.点击清楚无用资源
3.此时会发现，通过api上传的图片也会被列出，确定后被删除

**Comment by Zeng1998** [comment]
不推荐这样的使用方法。

建议用附件而不是直接引用资源地址来使用已上传的资源。
