### ISSUE TITLE
Tags get deleted after upgrading

### ISSUE THREAD

**Issue by shootie22** [usememos/memos#883]
### Describe the bug

Tags on the left side get removed if the memos version is upgraded through docker. They appear if you edit the individual notes and then save.

### Steps to reproduce

1. Upgrade memos through docker using the provided command `docker-compose down && docker image rm neosmemo/memos:latest && docker-compose up -d`
2. Log in
3. Tags are gone

To make them appear again, you need to:
1. Click on the edit button of a memo which includes a tag
2. Save without making any change
3. The tag(s) will appear again on the left side of the screen.

**Comment by boojack** [comment]
PTAL https://github.com/usememos/memos/issues/855

**Comment by shootie22** [comment]
So you still need to add them manually from the suggestions, perhaps this should be a setting? Since it seems weird to have this as intended behavior.

**Comment by boojack** [comment]
There will be a "Save all" button in the tag suggestions section.

**Comment by shootie22** [comment]
Awesome, thanks and happy new year! 🎄
