### ISSUE TITLE
iframe 分享方式

### ISSUE THREAD

**Issue by butfool** [usememos/memos#897]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

目前 memos 支持两种方式的分享：图片或 link，这个和 flomo 是一样的，但是两款软件都没有一种通过 iframe 方式分享的方法，希望可以增加这种方式，从而可以在类似 Notion、SiYuan 等软件中方便地引用。（主要是跨域的权限问题）

**Comment by butfool** [comment]
这里不说样式，关于权限方面：
我在本地环境，手动编译前后端时可以通过 iframe 方式嵌入网页，即使是在不同源（不同端口）的情况下。
但是如果我用 Docker 运行则不可以访问，通过观察，发现有这个请求头 `X-Frame-Options: SAMEORIGIN` ，不知道这个请求头是哪个环节加上去的。

**Comment by boojack** [comment]
https://user-images.githubusercontent.com/24653555/211131703-55109f70-cffb-494d-97da-4293b077ac6f.mp4

**Comment by butfool** [comment]
很感谢这么快就能有所响应！
