### ISSUE TITLE
建议增加 MEMOS 中的内容关键词搜索索引

### ISSUE THREAD

**Issue by Neukchill** [usememos/memos#905]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

建议增加 MEMOS 中的内容关键词搜索索引，太长的文章中不方便找到关键词

**Comment by Zeng1998** [comment]
什么是“内容关键词搜索索引”，关键词是什么？是你指定的还是自动生成的？“太长的文章中不方便找到关键词” 又是什么意思？

**Comment by Neukchill** [comment]
> 什么是“内容关键词搜索索引”，关键词是什么？是你指定的还是自动生成的？“太长的文章中不方便找到关键词” 又是什么意思？

是指自己写的内容的关键字索引

**Comment by SinosGray** [comment]
> > 什么是“内容关键词搜索索引”，关键词是什么？是你指定的还是自动生成的？“太长的文章中不方便找到关键词” 又是什么意思？
> 
> 是指自己写的内容的关键字索引

really bad description

**Comment by Zeng1998** [comment]
Close without any valid description.
