### ISSUE TITLE
无法取消置顶、删除，修改快捷

### ISSUE THREAD

**Issue by Neukchill** [usememos/memos#906]
### Describe the bug

RT，
1.取消置顶无反应
2.修改无效还是会变回一开始的样子
3.删除就会提示 Unauthorized

### Steps to reproduce

1.在 DEMO 已复现
2. 提示 Unauthorized
3. 可以正常删除

**Comment by Zeng1998** [comment]
我在demo中无法复现。

**Comment by hyoban** [comment]
和 #911 中提到的一致，我会修复它
