### ISSUE TITLE
tag不能自动生成

### ISSUE THREAD

**Issue by leenzhu** [usememos/memos#909]
### Describe the bug

```
#newtag this is first line
and this is second line
```

如果内空有多行，那么tag就无法自动添加到左侧tag列表中。

### Steps to reproduce

发布如下内容：

```
#newtag this is first line
and this is second line
```

### Screenshots or additional context
![image](https://user-images.githubusercontent.com/25599632/210922074-bc7aa3e8-2981-40f0-88dc-c4a4a38e71a3.png)

_No response_

**Comment by Zeng1998** [comment]
这是一种不规范不推荐的tag写法。具体可以参考这里：https://github.com/usememos/memos/wiki/Best-practices-to-write-a-TAG

如果一定要这样写的话，可以在tag suggestions里手动添加上去。

**Comment by leenzhu** [comment]
按照文档推荐，我试了下，如果把tag放在最后一行是可以自动生的。但是放在第一行，仍然不能生成。

**Comment by leenzhu** [comment]
![image](https://user-images.githubusercontent.com/25599632/210966176-b3d7d77f-64e0-4f08-9c16-976a9ad2ebc5.png)
@Zeng1998
