### ISSUE TITLE
Error with tags

### ISSUE THREAD

**Issue by crishnakh** [usememos/memos#911]
### Describe the bug

1. When try to create shortcuts on the tag list I only see one tag. And I've created more than one tag.
2. When I fixed one shortcut I cannot defixed it...

### Steps to reproduce

1. Make some tags... 
2. Try to make a shortcut with the second tag...

1. Fix a shortcut.
2. Try to defix it...

### Screenshots or additional context

<img width="605" alt=" 2023-01-06 a las 17 01 47" src="https://user-images.githubusercontent.com/3185290/211050569-fd37e048-2665-4ccb-b3d2-24fb8cdc88c9.png">

<img width="262" alt=" 2023-01-06 a las 17 01 35" src="https://user-images.githubusercontent.com/3185290/211050545-428775de-0227-42e0-8b93-075352cc5033.png">

**Comment by hyoban** [comment]
can not reproduce first one, i will try to fix the second

**Comment by crishnakh** [comment]
> can not reproduce first one, i will try to fix the second

You can reproduce it with:
#tag1 #tag2 #tag3 (this only create tag3, one space separator)
#tag1  #tag2  #tag3  (this works, two space separator)

**Comment by hyoban** [comment]
still can not, maybe you can try to reproduce on https://demo.usememos.com/ and let me know

![image](https://user-images.githubusercontent.com/38493346/211694635-6dba7ef3-f4df-4f60-8df7-a07665d2ee98.png)

**Comment by crishnakh** [comment]
In demo works fine!
Maybe it was something from the 0.8 version.

**Comment by hyoban** [comment]
Feel free to reopen this issue if you have other questions.
