### ISSUE TITLE
Ability to fully disable public memos

### ISSUE THREAD

**Issue by sfan5** [usememos/memos#919]
### Is your feature request related to a problem?

I use Memos exclusively as a private note taking application for myself.
However the option to make memos public still exists and it's possible that I (or someone else, if the instance is shared) someday mistakenly make a memo public.

### Describe the solution you'd like

For that reason it would be useful to have global admin configuration that can *disable* public memos entirely.

**Comment by itschip** [comment]
I'll be making a PR for this shortly :)

**Comment by skyue** [comment]
效率也太快了，还想说一步到位：来个 XXX 内天可见，然后支持0天可见。

**Comment by sparrowyang** [comment]
我不希望未注册用户看到网站的内容，所以我开启了**禁用公共memos**现在有些问题：
1. 我仍希望已注册用户能发布protected(登录用户可见)的memos，但发布时无法选择。
2. 即使开启这个开关，在点击分享按钮时，仍然能改变memos的可见性为public(所有人可见)。我不希望用户能让memos公布。

**Comment by sparrowyang** [comment]
> > Issue is not in English. It has been translated automatically.
> 
> I don't want unregistered users to see the content of the site, so I turned on **disable public memos** and now I have some problems:
> 
> 1. I still want registered users to be able to publish protected (visible to logged in users) memos, but they cannot be selected when publishing.
> 2. Even if this switch is turned on, when the share button is clicked, the visibility of the memos can still be changed to public (visible to all). I don't want the user to make the memos public.

@itschip
