### ISSUE TITLE
Allow editing of public notes

### ISSUE THREAD

**Issue by cfredericksen** [usememos/memos#921]
### Is your feature request related to a problem?

I want to share a note with a person but they cannot edit it. 

### Describe the solution you'd like

I want to share a grocery list and have my gf add her items.

**Comment by mikul9** [comment]
This is a huge feature. Collaborative notes are far more valuable. Ideally, each note could be shared with specific users, but even making the note editable by all workspace users would be useful.

**Comment by wjbeckett** [comment]
Really? Not planned?
