### ISSUE TITLE
编辑功能可以优化

### ISSUE THREAD

**Issue by BigUIFU** [usememos/memos#922]
### Is your feature request related to a problem?

目前编辑功能存在三个体验问题，或许算不上bug
1. 双击编辑，当偶尔需要查阅笔记资料需要复制内容时，双击一段字符串想选中复制结果进入了编辑模式
2. markdown编辑器无法使用表格
3. 使用分割线编写文章后，隐藏全文和展开全文动作会跳到其它memo位置

### Describe the solution you'd like

希望能优化

**Comment by Zeng1998** [comment]
1感觉可以做个投票看下哪种习惯的人多一些，我认为这是个使用习惯的问题，比如复制可以直接拖动鼠标进行选中

**Comment by BigUIFU** [comment]
> 1感觉可以做个投票看下哪种习惯的人多一些，我认为这是个使用习惯的问题，比如复制可以直接拖动鼠标进行选中

这种不是唯一操作方式的问题我认为不需要投票，即使按照我的想法**去除双击编辑功能**它也并不影响用户想按住鼠标选中字符再复制这种原始操作习惯。目前编辑已经够便捷了，鼠标在memo右上角选项处悬停即可展开菜单可供编辑。

而且双击编辑对笔记本触板党不太友好

**Comment by i-iooi-i** [comment]
双击编辑这个操作好像是借鉴的flomo浮墨笔记，用习惯了感觉也挺好的。

**Comment by fakerange** [comment]
Need a switch to disable 1.

**Comment by boojack** [comment]
The switch to disable double-click to edit is released in `v0.10.3`.
