### ISSUE TITLE
Impossible to escape text formatting

### ISSUE THREAD

**Issue by sfan5** [usememos/memos#927]
### Describe the bug

As far as I'm aware it is a standard markdown feature to be able to escape the star character `*`.

### Steps to reproduce

1. Write a memo with `\*test\*`
2. Expect the following rendering:  \*test\*

Actual rendering:
![grafik](https://user-images.githubusercontent.com/1042418/211205512-0813529f-2c21-41e1-949f-5c1630c1d7bc.png)
(tested on [demo.usememos.com](https://demo.usememos.com/), v0.10.0)

**Comment by YMSTNT** [comment]
Also kind of related to this, can we get an option to similarly escape tags as well?

So we could write `\#test` and it would render `#test` in the note, but it wouldn't actually count as a tag. (So the tag wouldn't be created or it would not count as an existing tag)
It could be useful for situations when copying from another app that supports hashtags, but we don't want to mess up our memos tags for example.

**Comment by boojack** [comment]
In the latest version, we have implemented a usable markdown parser with escaping support. https://github.com/usememos/memos/blob/main/plugin/gomark/parser/escaping_character.go

<img width="732" alt="image" src="https://github.com/usememos/memos/assets/24653555/ed04e69d-8a17-4d15-a92a-3836d9819109">
