### ISSUE TITLE
Nested Lists?

### ISSUE THREAD

**Issue by vutsalsinghal** [usememos/memos#945]
### Is your feature request related to a problem?

Not sure if this exists, but is something like this currently possible?

### Describe the solution you'd like

- something
    - sub something
    - sub something2
        - sub-sub something

### Additional context

I've tried various spacing but it didn't work

**Comment by vutsalsinghal** [comment]
Also are all markdown features supported? [github markdown guide](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax). Is there is list/wiki of currently implemented features somewhere? Like I see table is not supported #804

**Comment by boojack** [comment]
The nested list will be supported in the next release.

<img width="684" alt="image" src="https://user-images.githubusercontent.com/24653555/212434959-de5bac0e-49b4-4509-8ef1-c3db10cfcb8a.png">

> Is there is list/wiki of currently implemented features somewhere?

https://github.com/usememos/memos/wiki/Supported-Markdown-syntaxes

**Comment by vutsalsinghal** [comment]
thanks for the update!

**Comment by MatchaJello** [comment]
Was this every updated because I can't get it to work.

**Comment by github-webmaster** [comment]
May you please integrate tab keyboard hotkey to created nested lists?

* asdasdsad
* TAB HERE and it auto indents

**Comment by github-webmaster** [comment]
> Was this every updated because I can't get it to work.

Maybe at one point and it was accidentally/auto removed... WISH WE HAD IT!
