### ISSUE TITLE
请求大佬优化图像排列。

### ISSUE THREAD

**Issue by i-iooi-i** [usememos/memos#951]
### Is your feature request related to a problem?

![image](https://user-images.githubusercontent.com/1827701/212457575-0aa075e8-db12-43b3-9f98-895015ac9fb2.png)

更新到最新版之后，看到上传多个图像有了好看的宫格排列模式。非常感谢大佬。
但还是想提一个小小的请求，就是在上传四张图的时候，个人感觉上面这种宫格排列不是很好看，页面缺乏了一定的工整美观度。

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/1827701/212457645-08a85a43-c028-47dd-8797-e6801c6c2b05.png)
![image](https://user-images.githubusercontent.com/1827701/212457731-4b66a05c-4d01-42c4-8fad-de67cb0388c3.png)

请大佬评估一下，是否可以考虑如上排列，类似微博的排列方式。
当用户上传4张图的时候，6张图，9张图的时候，呈现这类上下各排列2张，上下3张，这类的排列判定逻辑，这样看上去美观度更舒适一些。感谢√

**Comment by i-iooi-i** [comment]
补充：

![image](https://user-images.githubusercontent.com/1827701/215330172-6aade0cb-1a94-4c6e-941c-5312d95f0ef9.png)

如上图：建议上传的单张图像能显示等比例大小的尺寸，而不是被裁剪后的方格显示。就像微博或者微信朋友圈那样的展示效果。

![image](https://user-images.githubusercontent.com/1827701/215330282-4f509726-8365-4c4c-8fc2-d17974c38c6d.png)

现在这种单张图片被裁剪成方形，观感上多少有些残缺感😂。
而且一张图片也要手动点开去看，体验上也不会太好。

**Comment by Zeng1998** [comment]
好奇怎么同时做到等比例缩放和宫格排列的

**Comment by Seevil** [comment]
> 好奇怎么同时做到等比例缩放和宫格排列的

生成一个194x194的缩略图（尺寸不对的自动缩放填充空白背景），点击查看原图，但是这样的也不行 图片缩放画布空白填充的图看起来也不和谐。

建议是加个判断是否是单图片 如果只有一个图片就 完整显示图片  最大高度或者最大宽度约束一下就好了。

**Comment by i-iooi-i** [comment]
大佬们看过来~~~ 希望可以考虑优化一下上面提到的图像显示的问题。 🤤🤤

**Comment by ganlu510** [comment]
能够支持图文混排更好，比如要把图片插入文本中间部分，新版本插入的图片都呈现在文本的最末尾了，体验也不好。

**Comment by boojack** [comment]
Updated in the recent releases.
