### ISSUE TITLE
Delete Note function

### ISSUE THREAD

**Issue by ThoMagnum** [usememos/memos#953]
### Is your feature request related to a problem?

I am not sure if I overseen a option I can delete a note, but it would very helpfull to implement this.
If already an solution exits, I would very appreciate if you can desribe how to delete a note.

### Describe the solution you'd like

Add "delete" button to a memo

**Comment by jxpsert** [comment]
This exists, it's called 'Archive'. 
![image](https://user-images.githubusercontent.com/65042215/212545386-41d03204-1c52-4d49-88b1-ce06dd9cee73.png)

**Comment by ThoMagnum** [comment]
Got it, sorry  this stupid question.
I thought "Archive" was a part to store memos.
