### ISSUE TITLE
search

### ISSUE THREAD

**Issue by shaonibuke** [usememos/memos#962]
### Describe the bug

According to the text search content, the previous one will highlight the search content, but not now

### Steps to reproduce

tag: 0.10.1

**Comment by Zeng1998** [comment]
This feature has been removed by #910 .

**Comment by jxpsert** [comment]
> This feature has been removed by #910 .

Intentionally?

**Comment by Zeng1998** [comment]
> > This feature has been removed by #910 .
> 
> Intentionally?

Maybe it is. 

The previous implementation is too rough. If the search highlight is really needed, we can try to implement it better later.
