### ISSUE TITLE
Memo order and hide overflow

### ISSUE THREAD

**Issue by vutsalsinghal** [usememos/memos#966]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

2 requests:
- Can the order of memos be set manually?
- After a specific length, can the rest of the memo be hidden? Basically in the "list" view, display only a certain amount and then when user clicks on that memo, display the entire memo

**Comment by Zeng1998** [comment]
For the second point, you can refer to this. https://github.com/usememos/memos/wiki/Tips

**Comment by Zeng1998** [comment]
For the first point, I personally think it is not a reasonable and urgent need. Could you describe its application scenario?

**Comment by vutsalsinghal** [comment]
I agree that it not urgent but its reasonable imo. Image you've 100 _long_ memos, then the "explore" page is gonna be an endless scroll... Ideally, there should be a list view where only the 1st line (or at max first few lines) should be displayed and then when you click on it, it would expand into a detail view. 

I guess this can be closed for now - labelling it as _future enhancement_...

**Comment by vutsalsinghal** [comment]
Thanks!

**Comment by Oaklight** [comment]
> For the first point, I personally think it is not a reasonable and urgent need. Could you describe its application scenario?

It would be very helpful to have at least these two options in memos ordering:
- by creation time
- by updated time (the default at 0.14.4)
it would be even nicer if double-clicking on the ordering criteria would toggle ascending/descending by that criteria.

People who use memos as (journal-like) notebooks may frequently head back to edit the memo note. Current default ordering (updated time) messes up the note sequence. @Zeng1998 @boojack
