### ISSUE TITLE
Add API documentation

### ISSUE THREAD

**Issue by qazxcdswe123** [usememos/memos#967]
### Is your feature request related to a problem?

Community projects development.

### Describe the solution you'd like

There are many APIs (`resources`, `tags`, or even `memo`) that are not documented, it would be great to have documentation for them.

**Comment by SiriYXR** [comment]
need API doc too

**Comment by leopku** [comment]
+1

**Comment by boojack** [comment]
Please check on this discussion. https://github.com/orgs/usememos/discussions/1024

And thanks @lmm214 contribution!

**Comment by boojack** [comment]
https://github.com/usememos/memos/blob/main/docs/api/v1.md
