### ISSUE TITLE
最新创建和使用的标签排在顶部

### ISSUE THREAD

**Issue by loryncien** [usememos/memos#972]
### Is your feature request related to a problem?

如其他反馈的一样，创建的标签在列表底部，再加上没有自动补全，当标签较多时每次使用不是很方便。

### Describe the solution you'd like

最新创建和使用的标签排在顶部

**Comment by lhuanyun** [comment]
那标签一多以后就上下一顿乱找了？
还是目前默认的名称大小排序好一点，至少有规律。

**Comment by i-iooi-i** [comment]
> 那标签一多以后就上下一顿乱找了？
> 还是目前默认的名称大小排序好一点，至少有规律。

<img width="174" alt="image" src="https://user-images.githubusercontent.com/1827701/213705078-03019c99-4eac-4d75-9700-0930cc1ecb1b.png">

好像默认的也不是按照名称排序，至少中文不是。

**Comment by boojack** [comment]
> 好像默认的也不是按照名称排序，至少中文不是。

Fixed
