### ISSUE TITLE
Feature request : template.css documentation

### ISSUE THREAD

**Issue by garfieldairlines** [usememos/memos#981]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

I just noticed that I can get my own CSS theme on memos, but I can't find any documentation/template base on which I can start making my own. Can it be added to the documentation ?

**Comment by fiumad** [comment]
I will begin working on this now!

**Comment by jhademcconnell** [comment]
@fiumad were you able to make progress on this? Just checking because this documentation would be helpful

**Comment by boojack** [comment]
Maybe issue has been outdated.
