### ISSUE TITLE
Multi factor authentication - MFA

### ISSUE THREAD

**Issue by esturniolo** [usememos/memos#984]
### Is your feature request related to a problem?

Hi! 
Not really.
To improve the security, there is a chance to add 2FA to Memos?

### Describe the solution you'd like

2FA authentication :)

### Additional context

Thanks for this piece of software. It's amazing.

**Comment by ItsNoted** [comment]
I second this notion :) Would be a great asset to have 2FA.

**Comment by mebtte** [comment]
when memos on public network, 2fa can prevent attack well.

**Comment by ItsNoted** [comment]
Any update on this option? I'd like to have it before pushing my instance to the web publicly.

Thank you!

**Comment by rb-26** [comment]
I have just started using memos and it is great. This is the only thing that is missing from it for me.

**Comment by nealhead** [comment]
Has there been any movement on this at all? Is it under consideration at least? 2FA is crucial these days. Even something as simple as TOTP.

**Comment by nealhead** [comment]
This still says WIP but got closed as not planned

**Comment by Folas1337** [comment]
I shall also express my interest in this matter :)
On the project it is marked as WIP but as an issue it is closed, slightly confusing 😅

**Comment by WyInnovate** [comment]
so WIP or not planed?

**Comment by WyInnovate** [comment]
我感觉没那么难，我看很多开源项目都做了支持2FA
