### ISSUE TITLE
PDF : open file in document reader or download

### ISSUE THREAD

**Issue by bonnebulle** [usememos/memos#985]
### Is your feature request related to a problem?

When I upload a local file it doesnt open in my browser (or dorwnloading) 
( I try with Chrome/Firefox ) 
The file open as raw
You can try here :
https://memos.vincent-bonnefille.fr/m/1

### Describe the solution you'd like

Make the clic on file forcing to download the file 
Or, using a document viewer like pdf.js
https://mozilla.github.io/pdf.js/

### Additional context

I just update memo in last version
I try multiple files (.pdf)

**Comment by enriquetoledano** [comment]
In previous versions it was working (the .pdf was correctly opened by the browser). I think it's a bug.
