### ISSUE TITLE
Strikethrough of Checkboxes offsets "active" checkboxes

### ISSUE THREAD

**Issue by kernelkaribou** [usememos/memos#986]
### Describe the bug

Task/Check box behavior in memo with striked out checkbox checks wrong boxes.  While likely an unlikely scenario (but I use it this way), if you create a check list, and strikethrough a checklist item using ~~ markdown, subsequent check list items will be off by the index of the strikethrough item.

### Steps to reproduce

1) Create a memo with two or more check list items
```
- [ ] Test 1
- [ ] Test 2
```
2) Strikethrough the first check list item
```
~~- [ ] Test 1~~
- [ ] Test 2
```
3) Check the Test 2, the Test 1 will be 'x'ed and multiple clicks on test 2 will rotate through completion and incompletion of both items.

### Screenshots or additional context

If the list is longer than two then every subsequent items will be off by the strikethrough checks. Without looking at the code it seems its iterating indexes of check list items and the strikethrough ones are throwing it off.

Why do I do this or even a scenario? I will often create checklist items of both things I want to do and explore. Rather than deleting check list items I decide not do do, I will strike it out so I can reference later if necessary but tells me I am not going to do it.

~~- [ ] Build my own memo app~~
- [x] Submit bug to memos app repo

**Comment by Zeng1998** [comment]
I suggest using the standard markdown syntax.

**Comment by kernelkaribou** [comment]
Fair enough, realized that if I am going to take the moment to strikethrough the task I could not have it as a task at that point which does address this behavior. I will close this as a likely non essential concern to be addressed.

Thanks for all your efforts.
