### ISSUE TITLE
Key map bug with `[`

### ISSUE THREAD

**Issue by YuJianghao** [usememos/memos#989]
### Describe the bug

Fail to input `「` in the editor. Because key map bug with `[`.

### Steps to reproduce

- Config your IME with key map: `[` -> `「`
- e.g. For SougouInput
- <img width="240" alt="image" src="https://user-images.githubusercontent.com/17293034/213920537-a9b19b50-7ece-48da-ae41-b23ddfab229e.png">
- <img width="480" alt="image" src="https://user-images.githubusercontent.com/17293034/213920540-debd85f1-04ed-47b7-b5d8-4f5a5ac46226.png">
- Type `[`, which suppose to input `「`。
- Found `[]`

**Comment by Zeng1998** [comment]
Try to disable the powerful editor in settings.
