### ISSUE TITLE
搜索后，memos卡死

### ISSUE THREAD

**Issue by JiangLongLiu** [usememos/memos#990]
### Describe the bug

怀疑是因为memos关联的资源存数据库blob字段原因

### Steps to reproduce

1.写500条以上memo，每个memo都带附件
2.在memos搜素框搜索关键字
3.加载缓慢，有一半几率memos服务会崩溃

### Screenshots or additional context

我提供以下临时解决方法：

 1.用kettle将memos附件导出成文件(已完成)
        [kettle导出memos的blob字段为文件.zip](https://github.com/usememos/memos/files/10488712/kettle.memos.blob.zip)

 2.将附件传入可以提供直连的网盘（未完成）

 3.用kettle查询memos的表，并将网盘提供的直连的markdown格式，直接拼接在memo.content后面(未完成)

<hr>

这样处理后，以后写memo上传附件时，不直接使用memos的附件功能，而是要：
1. 先上传附件到可以提供**直链网盘**
2. 从网盘拿到文件附件的**直链**
3. 将直链的markdown形式拷贝到memos的正文中。

我自身能力有限，提供的方法未必是最好的，如果网友有更好的方法，欢迎一起讨论。

**Comment by boojack** [comment]
It will not gets blob field when composing memo's related resources. https://github.com/usememos/memos/pull/991

**Comment by boojack** [comment]
Just updated store caches with https://github.com/usememos/memos/pull/1066, please check again. And feel free to reopen this issue if it's still exists.
