### ISSUE TITLE
Allow username minimum length to be 3

### ISSUE THREAD

**Issue by EsEnZeT** [usememos/memos#995]
### Describe the bug

App currently doesn't allow to create/update user to have 3 character username(s).

### Steps to reproduce

1. Deploy :latest docker image
2. Browse http://localhost:5230
3. Create user 'abc' with any password

### Screenshots or additional context

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/3882467/215293824-e16427d7-fcc2-4e5a-9c2d-9fdc2e960354.png">

**Comment by jxpsert** [comment]
Why is this a bug? The username requirement is 3 characters, that's how it is. Why do you need 'abc' as your username?

**Comment by ProKzKeaMz** [comment]
Open

**Comment by ProKzKeaMz** [comment]
> ### Describe the bug
> 
> App currently doesn't allow to create/update user to have 3 character username(s).
> 
> ### Steps to reproduce
> 
> 1. Deploy :latest docker image
> 
> 2. Browse http://localhost:5230
> 
> 3. Create user 'abc' with any password
> 
> ### Screenshots or additional context
> 
> <img width="1205" alt="image" src="https://user-images.githubusercontent.com/3882467/215293824-e16427d7-fcc2-4e5a-9c2d-9fdc2e960354.png">
> 
>

**Comment by Zeng1998** [comment]
> @boojack thanks. But looks like user is still not allowed to create/update account with 3min characters.
> 
> <img alt="image" width="625" src="https://user-images.githubusercontent.com/3882467/221335452-a0bdc24d-07bd-4efd-8707-1c3dd7d2aff3.png">
> 
> Can 'minLength' be related to that? <img alt="image" width="526" src="https://user-images.githubusercontent.com/3882467/221335406-830aa750-74ee-4f0f-a32d-d7e08e3543c8.png">

It looks like that we forgot to update the validation on the front end.

**Comment by Zeng1998** [comment]
Fixed in #1156 .

**Comment by joekaiser** [comment]
as of `v0.15.2` I am unable to register username of 3 characters long. (like Joe)  It looks like that should have been fixed. Has there been a regression?
